### ISSUE TITLE
changeset:   1019:b384cd168c19 breaks matplotlib doc build

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#100]
Building the matplotlib docs from svn trunk works with sphinx 0.5.1, but breaks with tip.  Using hg bisect yields this:

```
efiring@manini:~/programs/py/sphinx_hg$ hg bisect -g
The first bad revision is:
changeset:   1019:b384cd168c19
user:        mitsuhiko
date:        Thu Feb 05 13:28:46 2009 +0100
summary:     attribute documentation now overrides non attribute documentation.
```

The failure building mpl docs occurs almost immediately with this traceback: (triggered by objpath being an empty list)

```
efiring@manini:~/programs/py/mpl/mpl_trunk/doc$ python make.py html
Sphinx v0.6 (hg), building html
loading pickled environment... not found
animation, api, event_handling, misc, pngsuite, pylab_examples, tests, units, user_interfaces, widgets, 
building [html]: targets for 388 source files that are out of date
updating environment: 388 added, 0 changed, 0 removed
reading sources... api/afm_api Exception occurred while building, starting debugger:
Traceback (most recent call last):
  File "/usr/local/lib/python2.5/site-packages/Sphinx-0.6dev_20090206-py2.5.egg/sphinx/cmdline.py", line 151, in main
    app.build(all_files, filenames)
  File "/usr/local/lib/python2.5/site-packages/Sphinx-0.6dev_20090206-py2.5.egg/sphinx/application.py", line 142, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.5/site-packages/Sphinx-0.6dev_20090206-py2.5.egg/sphinx/builders/__init__.py", line 236, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/local/lib/python2.5/site-packages/Sphinx-0.6dev_20090206-py2.5.egg/sphinx/builders/__init__.py", line 254, in build
    for docname in self.status_iterator(iterator, 'reading sources... ', purple):
  File "/usr/local/lib/python2.5/site-packages/Sphinx-0.6dev_20090206-py2.5.egg/sphinx/builders/__init__.py", line 115, in status_iterator
    for item in iterable:
  File "/usr/local/lib/python2.5/site-packages/Sphinx-0.6dev_20090206-py2.5.egg/sphinx/environment.py", line 483, in update
    self.read_doc(docname, app=app)
  File "/usr/local/lib/python2.5/site-packages/Sphinx-0.6dev_20090206-py2.5.egg/sphinx/environment.py", line 542, in read_doc
    pub.publish()
  File "/usr/lib/python2.5/site-packages/docutils/core.py", line 204, in publish
    self.settings)
  File "/usr/lib/python2.5/site-packages/docutils/readers/__init__.py", line 71, in read
    self.parse()
  File "/usr/lib/python2.5/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/__init__.py", line 155, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/lib/python2.5/site-packages/docutils/statemachine.py", line 234, in run
    context, state, transitions)
  File "/usr/lib/python2.5/site-packages/docutils/statemachine.py", line 422, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 2844, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 309, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 377, in new_subsection
    node=section_node, match_titles=1)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 267, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python2.5/site-packages/docutils/statemachine.py", line 234, in run
    context, state, transitions)
  File "/usr/lib/python2.5/site-packages/docutils/statemachine.py", line 422, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 2619, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 309, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 377, in new_subsection
    node=section_node, match_titles=1)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 267, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python2.5/site-packages/docutils/statemachine.py", line 234, in run
    context, state, transitions)
  File "/usr/lib/python2.5/site-packages/docutils/statemachine.py", line 422, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 2200, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 2212, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 1974, in directive
    directive_function, match, type_name, option_presets)
  File "/usr/lib/python2.5/site-packages/docutils/parsers/rst/states.py", line 2019, in run_directive
    self.state_machine)
  File "/usr/local/lib/python2.5/site-packages/Sphinx-0.6dev_20090206-py2.5.egg/sphinx/ext/autodoc.py", line 665, in automodule_directive
    return _auto_directive(*args, **kwds)
  File "/usr/local/lib/python2.5/site-packages/Sphinx-0.6dev_20090206-py2.5.egg/sphinx/ext/autodoc.py", line 640, in _auto_directive
    generator.generate(what, name, members, content)
  File "/usr/local/lib/python2.5/site-packages/Sphinx-0.6dev_20090206-py2.5.egg/sphinx/ext/autodoc.py", line 476, in generate
    key = ('.'.join(objpath[:-1]), objpath[-1])
IndexError: list index out of range
> /usr/local/lib/python2.5/site-packages/Sphinx-0.6dev_20090206-py2.5.egg/sphinx/ext/autodoc.py(476)generate()
-> key = ('.'.join(objpath[:-1]), objpath[-1])
(Pdb) return
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/100
- Originally reported by: Eric Firing
- Originally created at: 2009-02-06T23:18:31.078

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-02-06 22:37:41+00:00_

Can you try with 1025:ad5867d84abf, which should have fixed that bug?

**Comment by shimizukawa** [comment]
_From Eric Firing on 2009-02-07 00:13:52+00:00_

Yes, I pulled and updated to 1026, and the mpl doc build is now proceeding, so you evidently fixed the bug.  Thank you.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-02-07 08:47:23+00:00_

Cool, thanks.
