### ISSUE TITLE
4.3.2: spinx fails in generate `myst-parser` 0.16.1 documentation

### ISSUE THREAD

**Issue by kloczek** [sphinx-doc/sphinx#10003]
### Describe the bug

sphinx<>setuptools integration fails in rendering man page documentaion.
It was OK with `myst-parser` 0.15.2 with sphinx v4.2.0.

I"m not sure is it new sphinx issue however sphinx fails with call trace.

### How to Reproduce

```
git clone https://github.com/executablebooks/MyST-Parser/
cd MyST-Parser
pip install build setuptools sphinx wheel sphinxcontrib-bibtex sphinxcontrib-mermaid sphinxext-opengraph sphinxext-rediraffe sphinx-panels
python3 -sBm build -w
python3 setup.py build_sphinx -b man --build-dir build/sphinx
```

### Expected behavior

docmentation should be generated

### Your project

MyST-Parser

### Screenshots

```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.3.2
loading translations [en]... done
making output directory... done
checking bibtex cache... out of date
parsing bibtex file /home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/examples/references.bib... parsed 1 entries
myst v0.16.1: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['dollarmath', 'amsmath', 'deflist', 'fieldlist', 'html_admonition', 'html_image', 'colon_fence', 'smartquotes', 'replacements', 'linkify', 'substitution', 'tasklist'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=True, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=2, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
loading intersphinx inventory from https://docs.python.org/3.7/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
loading intersphinx inventory from https://markdown-it-py.readthedocs.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 28 added, 0 changed, 0 removed
reading sources... [100%] syntax/syntax
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/sphinx/intro.md:102: WARNING: Unknown directive type "margin".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-myst-parser.3 { sphinx/intro syntax/syntax syntax/optional syntax/reference explain/index sphinx/index sphinx/use sphinx/roles-and-directives sphinx/reference sphinx/faq docutils api/index api/parsers api/renderers api/reference develop/index develop/contributing develop/architecture develop/test_infrastructure examples/index examples/wealth_dynamics_rst examples/wealth_dynamics_md develop/_changelog } failed

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 346, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
The full traceback has been saved in /tmp/sphinx-err-7yroqr2j.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
[tkloczko@ss-desktop SPECS]$ cat /tmp/sphinx-err-7yroqr2j.log
# Sphinx version: 4.3.2
# Python version: 3.8.12 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.3
# Last messages:
#   develop/index
#   develop/contributing
#   develop/architecture
#   develop/test_infrastructure
#   examples/index
#   examples/wealth_dynamics_rst
#   examples/wealth_dynamics_md
#   develop/_changelog
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   myst_parser (0.16.1) from /home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/myst_parser/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.intersphinx (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (4.3.2) from /usr/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   sphinxcontrib.bibtex (2.4.1) from /usr/lib/python3.8/site-packages/sphinxcontrib/bibtex/__init__.py
#   sphinx_panels (0.6.0) from /usr/lib/python3.8/site-packages/sphinx_panels/__init__.py
#   sphinxext.rediraffe (unknown version) from /usr/lib/python3.8/site-packages/sphinxext/rediraffe.py
#   sphinxcontrib.mermaid (4.3.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/mermaid.py
#   sphinxext.opengraph (unknown version) from /usr/lib/python3.8/site-packages/sphinxext/opengraph/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/setup_command.py", line 175, in run
    app.build(force_all=self.all_files)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 344, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 291, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 547, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 104, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 37, in translate
    visitor = self.builder.create_translator(self.document, self.builder)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 128, in create_translator
    return self.app.registry.create_translator(self, *args)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 346, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
```

### OS

Linux/x86_64

### Python version

3.8.12

### Sphinx version

4.3.2

### Sphinx extensions

sphinxcontrib-bibtex sphinxcontrib-mermaid sphinxext-opengraph sphinxext-rediraffe sphinx-panels

### Extra tools

N/A

### Additional context

N/A

**Comment by kloczek** [comment]
I forgot to add that I'm patching copy.py with below patch:
```patch
--- a/docs/conf.py~     2021-12-11 04:00:15.000000000 +0000
+++ b/docs/conf.py      2021-12-11 12:48:12.312377490 +0000
@@ -201,3 +201,14 @@
     # app.connect("builder-inited", run_apidoc)
     app.add_css_file("custom.css")
     app.add_directive("docutils-cli-help", DocutilsCliHelpDirective)
+
+# Man ------------------------------------------------------------------
+man_pages = [
+    (
+        'index',
+        'python-myst-parser',
+        'MyST-Parser Python Module Documentation',
+        author,
+        3,
+    )
+]
```

**Comment by tk0miya** [comment]
>It was OK with myst-parser 0.15.2 with sphinx v4.2.0.

To break down the error, could you check 0.15.2 and Sphinx v4.3.2, please? If failed, it must be a bug of Sphinx v4.3.2. We'll investigate soon. If not, it would be a bug of MyST-Parser. So this report should be posted to their project instead.

**Comment by kloczek** [comment]
> To break down the error, could you check 0.15.2 and Sphinx v4.3.2, please? 

Just tested that and older version of the `myst-parser` with latest sphinx is OK,
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.3.2
loading translations [en]... done
making output directory... done
myst v0.15.2: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['dollarmath', 'amsmath', 'deflist', 'html_admonition', 'html_image', 'colon_fence', 'smartquotes', 'replacements', 'linkify', 'substitution', 'tasklist'], dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=True, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=2, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
loading intersphinx inventory from https://docs.python.org/3.7/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
loading intersphinx inventory from https://markdown-it-py.readthedocs.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 27 added, 0 changed, 0 removed
reading sources... [100%] syntax/syntax
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/examples/index.md:22: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/examples/index.md:28: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/examples/wealth_dynamics_md.md:38: WARNING: Unknown interpreted text role "cite".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/examples/wealth_dynamics_md.md:479: WARNING: Unknown directive type "bibliography".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/examples/wealth_dynamics_rst.rst:40: WARNING: Unknown interpreted text role "cite".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/examples/wealth_dynamics_rst.rst:493: WARNING: Unknown directive type "bibliography".

.. bibliography:: references.bib
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/index.md:10: WARNING: Unknown directive type "panels".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/index.md:52: WARNING: Unknown directive type "panels".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/sphinx/intro.md:102: WARNING: Unknown directive type "margin".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/sphinx/intro.md:405: WARNING: Unknown directive type "mermaid".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/syntax/optional.md:158: WARNING: No render method for: math_block_label [myst.render]
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/syntax/optional.md:187: WARNING: No render method for: math_inline_double [myst.render]
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/syntax/optional.md:208: WARNING: No render method for: math_inline_double [myst.render]
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/syntax/optional.md:287: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/syntax/optional.md:304: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/syntax/optional.md:390: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/syntax/optional.md:408: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/syntax/syntax.md:414: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/syntax/syntax.md:428: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/syntax/syntax.md:442: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/syntax/syntax.md:454: WARNING: Unknown directive type "tabbed".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... mystparser.1 { sphinx/intro syntax/syntax syntax/optional syntax/reference explain/index sphinx/index sphinx/use sphinx/roles-and-directives sphinx/reference sphinx/faq api/index api/parsers api/renderers api/reference develop/index develop/contributing develop/architecture develop/test_infrastructure examples/index examples/wealth_dynamics_rst examples/wealth_dynamics_md develop/_changelog } /home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.15.2/docs/syntax/optional.md:162: WARNING: equation not found: eqn:best
done
build succeeded, 22 warnings.
```
OK will try to open issue ticket against `myst-parser`.
Please hold that ticket opened (just in case)
:)

**Comment by chrisjsewell** [comment]
> Just tested that and older version of the myst-parser with latest sphinx is OK,

This isn’t the same test though, because your not loading all the other extensions. It’s more likely to be an issue with one of them, given that myst-parser does not add any node visitors

**Comment by kloczek** [comment]
If you see that I can try to spent some time to perform some additional tests please describe that in few words and I'll try to test as much as possible :)

**Comment by chrisjsewell** [comment]
Well I would first try running with only the latest myst-parser and none of the other extensions

**Comment by kloczek** [comment]
> Well I would first try running with only the latest myst-parser and none of the other extensions

By extensions you mean sphinx extensions? If yes I've trimmed down build env to only those python modules which I have in rpm BuildRequires and some really small set of base modules which form relatively short list of installed modules:
```console
[tkloczko@ss-desktop SPECS]$ pip list
Package                       Version
----------------------------- -------------------
alabaster                     0.7.12
appdirs                       1.4.4
attrs                         21.2.0
Babel                         2.9.1
build                         0.7.0
chardet                       4.0.0
charset-normalizer            2.0.9
cycler                        0.11.0
dbus-python                   1.2.18
distro                        1.6.0
docutils                      0.17.1
extras                        1.0.0
fixtures                      3.0.0
gpg                           1.16.0-unknown
idna                          3.3
imagesize                     1.2.0
importlib-metadata            4.10.0
iniconfig                     1.1.1
Jinja2                        3.0.3
kiwisolver                    1.3.2
latexcodec                    2.0.1
libcomps                      0.1.18
linkify-it-py                 1.0.2
lxml                          4.7.1
Mako                          1.1.6.dev0
Markdown                      3.3.6
markdown-it-py                1.1.0
MarkupSafe                    2.0.1
matplotlib                    3.5.1
mdit-py-plugins               0.3.0
meson                         0.60.2
numpy                         1.21.4
olefile                       0.46
packaging                     21.3
pbr                           5.6.0
pep517                        0.12.0
Pillow                        8.4.0
pip                           21.3.1
pluggy                        1.0.0
py                            1.11.0
pybtex                        0.24.0
pybtex-docutils               1.0.1
Pygments                      2.10.0
PyGObject                     3.42.0
pyparsing                     3.0.6
pytest                        6.2.5
pytest-datadir                1.3.1
pytest-regressions            2.2.0
python-dateutil               2.8.2
pytz                          2021.1
PyYAML                        6.0
requests                      2.26.0
rpm                           4.17.0
scour                         0.38.2
setuptools                    60.0.0.post20211220
six                           1.16.0
smartypants                   2.0.1
snowballstemmer               2.1.0
Sphinx                        4.3.2.dev20211220
sphinx-panels                 0.6.0
sphinxcontrib-applehelp       1.0.2.dev20210802
sphinxcontrib-bibtex          2.4.1
sphinxcontrib-devhelp         1.0.2.dev20210801
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20210801
sphinxcontrib-mermaid         0.7.1
sphinxcontrib-qthelp          1.0.3.dev20210824
sphinxcontrib-serializinghtml 1.1.5
sphinxext-opengraph           0.4.2
sphinxext-rediraffe           main
testtools                     2.5.0
toml                          0.10.2
tomli                         2.0.0
typogrify                     2.0.7
uc-micro-py                   1.0.1
urllib3                       1.26.7
wheel                         0.37.0
zipp                          3.6.0
```
Result:
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.3.2
loading translations [en]... done
making output directory... done
checking bibtex cache... out of date
parsing bibtex file /home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/examples/references.bib... parsed 1 entries
myst v0.16.1: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['dollarmath', 'amsmath', 'deflist', 'fieldlist', 'html_admonition', 'html_image', 'colon_fence', 'smartquotes', 'replacements', 'linkify', 'substitution', 'tasklist'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=True, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=2, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
loading intersphinx inventory from https://docs.python.org/3.7/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
loading intersphinx inventory from https://markdown-it-py.readthedocs.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 28 added, 0 changed, 0 removed
reading sources... [100%] syntax/syntax
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/sphinx/intro.md:102: WARNING: Unknown directive type "margin".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-myst-parser.3 { sphinx/intro syntax/syntax syntax/optional syntax/reference explain/index sphinx/index sphinx/use sphinx/roles-and-directives sphinx/reference sphinx/faq docutils api/index api/parsers api/renderers api/reference develop/index develop/contributing develop/architecture develop/test_infrastructure examples/index examples/wealth_dynamics_rst examples/wealth_dynamics_md develop/_changelog } failed

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 346, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
The full traceback has been saved in /tmp/sphinx-err-fbk0jbqz.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
Still looks like `margin` directive is used without some necessary extension (nevertheless this does not affect that sphinx crash).

**Comment by chrisjsewell** [comment]
I mean in `conf.py` remove everything except for `myst_parser` in the `extensions` list

**Comment by chrisjsewell** [comment]
And also use alabaster as the html_theme

**Comment by kloczek** [comment]
Understand .. OK will try that :)

**Comment by chrisjsewell** [comment]
👍

**Comment by kloczek** [comment]
Sorry alost forgot about that ticket :/
Here is the output with eremoved all extensions (and left `myst_parser`)
```console
[tkloczko@ss-desktop MyST-Parser-0.16.1]$ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.3.2
loading translations [en]... done
myst v0.16.1: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['dollarmath', 'amsmath', 'deflist', 'fieldlist', 'html_admonition', 'html_image', 'colon_fence', 'smartquotes', 'replacements', 'linkify', 'substitution', 'tasklist'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=True, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=2, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 28 added, 0 changed, 0 removed
reading sources... [100%] syntax/syntax
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/api/reference.rst:10: WARNING: Unknown directive type "automodule".

.. automodule:: myst_parser.parse_directives
    :members:
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/api/reference.rst:26: WARNING: Unknown directive type "autoclass".

.. autoclass:: myst_parser.docutils_renderer.DocutilsRenderer
    :special-members: __output__, __init__
    :members: render, nested_render_text, add_line_and_source_path, current_node_context
    :undoc-members:
    :member-order: bysource
    :show-inheritance:
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/api/reference.rst:37: WARNING: Unknown directive type "autoclass".

.. autoclass:: myst_parser.sphinx_renderer.SphinxRenderer
    :special-members: __output__
    :members: handle_cross_reference, render_math_block_label
    :undoc-members:
    :member-order: alphabetical
    :show-inheritance:
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/api/reference.rst:51: WARNING: Unknown directive type "autoclass".

.. autoclass:: myst_parser.mocking.MockInliner
    :members:
    :undoc-members:
    :show-inheritance:
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/api/reference.rst:56: WARNING: Unknown directive type "autoclass".

.. autoclass:: myst_parser.mocking.MockState
    :members:
    :undoc-members:
    :show-inheritance:
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/api/reference.rst:61: WARNING: Unknown directive type "autoclass".

.. autoclass:: myst_parser.mocking.MockStateMachine
    :members:
    :undoc-members:
    :show-inheritance:
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/api/reference.rst:66: WARNING: Unknown directive type "autoclass".

.. autoclass:: myst_parser.mocking.MockIncludeDirective
    :members:
    :undoc-members:
    :show-inheritance:
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/api/reference.rst:75: WARNING: Unknown directive type "autofunction".

.. autofunction:: myst_parser.docutils_renderer.make_document
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/api/reference.rst:77: WARNING: Unknown directive type "autofunction".

.. autofunction:: myst_parser.docutils_renderer.html_meta_to_nodes
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/api/reference.rst:79: WARNING: Unknown directive type "autofunction".

.. autofunction:: myst_parser.sphinx_renderer.minimal_sphinx_app
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/api/reference.rst:81: WARNING: Unknown directive type "autofunction".

.. autofunction:: myst_parser.sphinx_renderer.mock_sphinx_env
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/api/reference.rst:89: WARNING: Unknown directive type "autoclass".

.. autoclass:: myst_parser.docutils_.Parser
    :members: parse
    :undoc-members:
    :member-order: bysource
    :show-inheritance:
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/api/reference.rst:103: WARNING: Unknown directive type "autoclass".

.. autoclass:: myst_parser.sphinx_parser.MystParser
    :members: supported, parse
    :undoc-members:
    :member-order: bysource
    :show-inheritance:
    :exclude-members: __init__
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/docutils.md:30: WARNING: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/examples/index.md:22: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/examples/index.md:28: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/examples/wealth_dynamics_md.md:38: WARNING: Unknown interpreted text role "cite".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/examples/wealth_dynamics_md.md:479: WARNING: Unknown directive type "bibliography".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/examples/wealth_dynamics_rst.rst:40: WARNING: Unknown interpreted text role "cite".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/examples/wealth_dynamics_rst.rst:493: WARNING: Unknown directive type "bibliography".

.. bibliography:: references.bib
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/index.md:10: WARNING: Unknown directive type "panels".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/index.md:53: WARNING: Unknown directive type "panels".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/sphinx/intro.md:102: WARNING: Unknown directive type "margin".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/sphinx/intro.md:405: WARNING: Unknown directive type "mermaid".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/sphinx/use.md:118: WARNING: Unknown directive type "autoclass".

.. autoclass:: myst_parser.mocking.MockRSTParser
    :show-inheritance:
    :members: parse
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/optional.md:290: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/optional.md:307: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/optional.md:393: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/optional.md:411: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/syntax.md:414: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/syntax.md:428: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/syntax.md:442: WARNING: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/syntax.md:454: WARNING: Unknown directive type "tabbed".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-myst-parser.3 { sphinx/intro syntax/syntax syntax/optional syntax/reference explain/index sphinx/index sphinx/use sphinx/roles-and-directives sphinx/reference sphinx/faq docutils api/index api/parsers api/renderers api/reference develop/index develop/contributing develop/architecture develop/test_infrastructure examples/index examples/wealth_dynamics_rst examples/wealth_dynamics_md develop/_changelog } /home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/optional.md:21: WARNING: 'myst' reference target not found: markdown_it:index
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/optional.md:21: WARNING: 'myst' reference target not found: markdown_it:md/plugins
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/optional.md:84: WARNING: 'myst' reference target not found: markdown_it:md/plugins
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/optional.md:503: WARNING: 'myst' reference target not found: markdown_it:md/plugins
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/optional.md:582: WARNING: 'myst' reference target not found: markdown_it:md/plugins
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/optional.md:653: WARNING: 'myst' reference target not found: sphinx:python-domain
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/sphinx/use.md:105: WARNING: 'myst' reference target not found: sphinx:sphinx.ext.autodoc
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/sphinx/use.md:126: WARNING: 'myst' reference target not found: myst_parser.mocking.MockRSTParser
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/sphinx/reference.md:9: WARNING: 'myst' reference target not found: markdown_it:using
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/sphinx/reference.md:114: WARNING: 'myst' reference target not found: markdown_it:using
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/CHANGELOG.md:200: WARNING: 'myst' reference target not found: markdown_it:md/plugins
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/syntax/optional.md:702: WARNING: undefined label: sphinx:rst-primer
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/explain/index.md:11: WARNING: undefined label: sphinx:rst-roles-alt
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/explain/index.md:11: WARNING: undefined label: sphinx:rst-directives
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.16.1/docs/api/reference.rst:100: WARNING: undefined label: sphinx:parser-api
done
build succeeded, 48 warnings.
```

**Comment by kloczek** [comment]
Testing just release of the `myst_parser` empirically I found that `sphinx_panels` is messing and after commenting out that ext I was able to generate documentation.
https://github.com/executablebooks/MyST-Parser/issues/556

Any suggestions what more I can do about diagnose `sphinx_panels`?

And small question: is it any other way to specify for autodoc path from where it should load module code to scan?
temporarry I'm injecting in copy.py
```python
import sys
import os
sys.path.append(os.path.abspath('..'))
```
But I suppose that it must be some better/proper way to specify that path.

**Comment by choldgraf** [comment]
@kloczek I'd recommend trying Sphinx Design before going too far down the path with Sphinx Panels. It is an "evolution" of sphinx panels, and will be more well-maintained moving forward: https://sphinx-design.readthedocs.io/en/latest/

See if you have the same issue with it?

**Comment by kloczek** [comment]
First of all: to be honest I'm not interested web/http sphinx output as I'm on buiding all sphinx based documentation as man pages 😋  (man page still is most common documentation format on all unix platforms)
Just one stat showin on what kind of scale I'm doing that
```console
[tkloczko@devel-g2v SPECS]$ grep %sphinx_build_man python-* | wc -l; ls -1 python-* | wc -l
515
904
```
So more than half of the packages have susch documentation included in the rpm package 😄 

Second thing is that in mean time I've found that currently it is not possible to generate `sphinx-panels` documentation 😵‍💫 https://github.com/executablebooks/sphinx-panels/issues/74
Looks like cause may be the same.

As maintanace of the `sphinx-panels` seems is in last year a bit sloppy probably will be trying to ask modules maintainers whcih are using that ext to switch to other extension 🤔 
Other (JFDI) option is disable in my builds use that ext as seems it is dedicated to alter only html output.

**Comment by choldgraf** [comment]
You are correct that Sphinx Panels is no longer actively developed, `sphinx-design` is where new development happens.

**Comment by tk0miya** [comment]
As you know, this is an issue of Sphinx itself (in other words, sphinx-core), not a forum. So I'd like to close this because this is not a problem of Sphinx. If you'd like to continue this, please use sphinx forum instead.

**Comment by kloczek** [comment]
Yep you are right.
Closing
