### ISSUE TITLE
EOFError with multiprocessing

### ISSUE THREAD

**Issue by JordanYates** [sphinx-doc/sphinx#10046]
### Describe the bug

Documentation builds fail when using multiprocessing with `EOFError`.
The failure does not always occur at the same point, and doesn't occur at all on a smaller project.
It also doesn't appear to be affecting the CI servers building the project.

pip extensions:
```
Sphinx                         3.5.4
sphinx-notfound-page           0.8
sphinx-rtd-theme               0.5.2
sphinx-tabs                    3.2.0
sphinxcontrib-applehelp        1.0.2
sphinxcontrib-devhelp          1.0.2
sphinxcontrib-htmlhelp         2.0.0
sphinxcontrib-jsmath           1.0.1
sphinxcontrib-qthelp           1.0.3
sphinxcontrib-serializinghtml  1.1.5
sphinxcontrib-svg2pdfconverter 1.2.0
```

Complete log:
```
jordan@comp:~/test/zephyr/doc$ cat /tmp/sphinx-err-ubn9kbkh.log
# Sphinx version: 3.5.4
# Python version: 3.8.10 (CPython)
# Docutils version: 0.18.1 release
# Jinja2 version: 2.10.1
# Last messages:
#   reading sources... [ 86%] samples/boards/bbc_microbit/line_follower_robot/README .. samples/drivers/clock_control_litex/README
#   reading sources... [ 88%] samples/drivers/counter/alarm/README .. samples/modules/canopennode/README
#   reading sources... [ 90%] samples/modules/index .. samples/net/sockets/sntp_client/README
#   reading sources... [ 92%] samples/net/sockets/socketpair/README .. samples/sensor/lis2dh/README
#   reading sources... [ 94%] samples/sensor/lps22hb/README .. samples/shields/x_nucleo_iks02a1/sensorhub/README
#   reading sources... [ 96%] samples/shields/x_nucleo_iks02a1/standard/README .. samples/subsys/portability/cmsis_rtos_v1/timer_synchronization/README
#   reading sources... [ 98%] samples/subsys/portability/cmsis_rtos_v2/philosophers/README .. security/reporting
#   reading sources... [100%] security/secure-coding .. security/vulnerabilities
#
#   waiting for workers...
# Loaded extensions:
#   sphinx.ext.mathjax (3.5.4) from /home/jordan/.local/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/jordan/.local/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/jordan/.local/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /home/jordan/.local/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /home/jordan/.local/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/jordan/.local/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/jordan/.local/lib/python3.8/site-packages/alabaster/__init__.py
#   breathe (4.31.0) from /home/jordan/.local/lib/python3.8/site-packages/breathe/__init__.py
#   sphinx.ext.todo (3.5.4) from /home/jordan/.local/lib/python3.8/site-packages/sphinx/ext/todo.py
#   sphinx.ext.extlinks (3.5.4) from /home/jordan/.local/lib/python3.8/site-packages/sphinx/ext/extlinks.py
#   sphinx.ext.autodoc.type_comment (3.5.4) from /home/jordan/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.5.4) from /home/jordan/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.graphviz (3.5.4) from /home/jordan/.local/lib/python3.8/site-packages/sphinx/ext/graphviz.py
#   zephyr.application (1.0) from /home/jordan/test/zephyr/doc/_extensions/zephyr/application.py
#   zephyr.html_redirects (unknown version) from /home/jordan/test/zephyr/doc/_extensions/zephyr/html_redirects.py
#   zephyr.kconfig-role (unknown version) from /home/jordan/test/zephyr/doc/_extensions/zephyr/kconfig-role.py
#   zephyr.dtcompatible-role (unknown version) from /home/jordan/test/zephyr/doc/_extensions/zephyr/dtcompatible-role.py
#   zephyr.link-roles (unknown version) from /home/jordan/test/zephyr/doc/_extensions/zephyr/link-roles.py
#   sphinx_tabs.tabs (unknown version) from /home/jordan/.local/lib/python3.8/site-packages/sphinx_tabs/tabs.py
#   zephyr.warnings_filter (0.1.0) from /home/jordan/test/zephyr/doc/_extensions/zephyr/warnings_filter.py
#   zephyr.doxyrunner (0.1.0) from /home/jordan/test/zephyr/doc/_extensions/zephyr/doxyrunner.py
#   zephyr.vcs_link (0.1.0) from /home/jordan/test/zephyr/doc/_extensions/zephyr/vcs_link.py
#   notfound.extension (0.8) from /home/jordan/.local/lib/python3.8/site-packages/notfound/extension.py
#   zephyr.external_content (0.1.0) from /home/jordan/test/zephyr/doc/_extensions/zephyr/external_content.py
Traceback (most recent call last):
  File "/home/jordan/.local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/jordan/.local/lib/python3.8/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/home/jordan/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/home/jordan/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/home/jordan/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 415, in read
    self._read_parallel(docnames, nproc=self.app.parallel)
  File "/home/jordan/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 466, in _read_parallel
    tasks.join()
  File "/home/jordan/.local/lib/python3.8/site-packages/sphinx/util/parallel.py", line 108, in join
    self._join_one()
  File "/home/jordan/.local/lib/python3.8/site-packages/sphinx/util/parallel.py", line 125, in _join_one
    exc, logs, result = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

### How to Reproduce

```
$ git clone https://github.com/zephyrproject-rtos/zephyr
$ cd zephyr
$ pip install -r scripts/requirements.txt
$ cd docs
$ make html-fast
```

### Your project

https://github.com/zephyrproject-rtos/zephyr

### OS

Ubuntu under WSL2

### Python version

3.8.10

### Sphinx version

3.5.4

**Comment by tk0miya** [comment]
Is there any reason not to update Sphinx? On my local, the latest Sphinx does not raise the error. It seems this bug was already fixed.

This is Dockerfile I tried:

```
RUN apt update; apt install -y build-essential curl git unzip vim
RUN git clone https://github.com/zephyrproject-rtos/zephyr
WORKDIR /zephyr
RUN pip install -r scripts/requirements.txt
WORKDIR /zephyr/doc
RUN curl -L -o - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
RUN echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
RUN apt update
RUN rm /usr/share/keyrings/kitware-archive-keyring.gpg
RUN apt install -y kitware-archive-keyring
RUN apt install -y cmake
RUN apt install -y ninja-build
RUN apt install -y doxygen
RUN apt install -y graphviz
RUN pip install -U Sphinx
RUN make html-fast
```

Note: I reproduced your error with Sphinx-3.5.4.

**Comment by JordanYates** [comment]
Good question, I didn't realise the version specified by Zephyr was so far out of date.
https://github.com/zephyrproject-rtos/zephyr/blob/7f5eb921dc8bb1b7014886986bbffdf111b68b15/scripts/requirements-doc.txt#L4
I will raise an issue there to see if it can be updated
