### ISSUE TITLE
EOFError using pypy3.8

### ISSUE THREAD

**Issue by thedjnK** [sphinx-doc/sphinx#10155]
### Describe the bug

Essentially the same scenario as https://github.com/sphinx-doc/sphinx/issues/10046 - using pypy3.8 to build the zephyr documentation fails but with newer versions of sphix:
```
[2/3] Running Sphinx HTML build...
Running Sphinx v4.4.0
making output directory... done
Preparing Doxyfile...
Checking if Doxygen needs to be run...
Running Doxygen...
WARNING: /tmp/aa/zephyr/include/kernel.h:5864: documented empty return type of k_sys_runtime_stats_disable
WARNING: /tmp/aa/zephyr/include/kernel.h:5853: documented empty return type of k_sys_runtime_stats_enable
WARNING: /tmp/aa/zephyr/include/bluetooth/audio/audio.h:1273: documented empty return type of bt_audio_stream_cb_register
WARNING: /tmp/aa/zephyr/include/kernel.h:4850: documented empty return type of k_pipe_buffer_flush
WARNING: /tmp/aa/zephyr/include/kernel.h:4836: documented empty return type of k_pipe_flush
WARNING: /tmp/aa/zephyr/include/bluetooth/audio/audio.h:1273: documented empty return type of bt_audio_stream_cb_register
WARNING: /tmp/aa/zephyr/include/kernel.h:4836: documented empty return type of k_pipe_flush
WARNING: /tmp/aa/zephyr/include/kernel.h:4850: documented empty return type of k_pipe_buffer_flush
WARNING: /tmp/aa/zephyr/include/kernel.h:5853: documented empty return type of k_sys_runtime_stats_enable
WARNING: /tmp/aa/zephyr/include/kernel.h:5864: documented empty return type of k_sys_runtime_stats_disable
WARNING: /tmp/aa/zephyr/include/bluetooth/audio/audio.h:1273: documented empty return type of bt_audio_stream_cb_register
WARNING: /tmp/aa/zephyr/include/kernel.h:4836: documented empty return type of k_pipe_flush
WARNING: /tmp/aa/zephyr/include/kernel.h:4850: documented empty return type of k_pipe_buffer_flush
Syncing Doxygen output...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 927 source files that are out of date
updating environment: [new config] 2050 added, 0 changed, 0 removed
reading sources... [100%] samples/subsys/video/video .. security/vulnerabilities
waiting for workers...
/tmp/aa/zephyr/doc/_build/src/envname/lib/pypy3.8/site-packages/sphinx/ext/autosummary/templates/autosummary/base.rst:3: ERROR: Error in "currentmodule" directive:
maximum 1 argument(s) allowed, 3 supplied.

.. currentmodule:: {{ module }}
/tmp/aa/zephyr/doc/_build/src/envname/lib/pypy3.8/site-packages/sphinx/ext/autosummary/templates/autosummary/class.rst:3: ERROR: Error in "currentmodule" directive:
maximum 1 argument(s) allowed, 3 supplied.

.. currentmodule:: {{ module }}
WARNING: invalid signature for autoclass ('{{ objname }}')
WARNING: don't know which module to import for autodocumenting '{{ objname }}' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: invalid signature for automodule ('{{ fullname }}')
WARNING: don't know which module to import for autodocumenting '{{ fullname }}' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
/tmp/aa/zephyr/doc/_build/src/envname/lib/pypy3.8/site-packages/sphinx/ext/autosummary/templates/autosummary/module.rst:53: ERROR: Unknown directive type "autosummary".

.. autosummary::
   :toctree:
   :recursive:
/tmp/aa/zephyr/doc/_build/src/envname/lib/pypy3.8/site-packages/sphinx/ext/autosummary/templates/autosummary/module.rst:56: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/tmp/aa/zephyr/doc/_build/src/envname/lib/pypy3.8/site-packages/sphinx/ext/autosummary/templates/autosummary/module.rst:58: WARNING: Definition list ends without a blank line; unexpected unindent.

Exception occurred:
  File "/opt/pypy3/lib-python/3/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```
And the contents of that file:
```
# Sphinx version: 4.4.0
# Python version: 3.8.12 (PyPy)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.3
# Last messages:
#   reading sources... [ 91%] samples/modules/index .. samples/net/sockets/can/README
#   reading sources... [ 92%] samples/net/sockets/coap_client/README .. samples/net/wpanusb/README
#   reading sources... [ 93%] samples/net/zperf/README .. samples/sensor/ina219/README
#   reading sources... [ 94%] samples/sensor/isl29035/README .. samples/sensor/ti_hdc/README
#   reading sources... [ 96%] samples/sensor/tmp108/README .. samples/subsys/debug/index
#   reading sources... [ 97%] samples/subsys/display/cfb/README .. samples/subsys/modbus/tcp_server/README
#   reading sources... [ 98%] samples/subsys/nvs/README .. samples/subsys/video/tcpserversink/README
#   reading sources... [100%] samples/subsys/video/video .. security/vulnerabilities
#
#   waiting for workers...
# Loaded extensions:
#   sphinx.ext.mathjax (4.4.0) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/alabaster/__init__.py
#   breathe (4.32.0) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/breathe/__init__.py
#   sphinx.ext.todo (4.4.0) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/ext/todo.py
#   sphinx.ext.extlinks (4.4.0) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/ext/extlinks.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.4.0) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.4.0) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.graphviz (4.4.0) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/ext/graphviz.py
#   zephyr.application (1.0) from /tmp/aa/zephyr/doc/_extensions/zephyr/application.py
#   zephyr.html_redirects (unknown version) from /tmp/aa/zephyr/doc/_extensions/zephyr/html_redirects.py
#   zephyr.kconfig-role (unknown version) from /tmp/aa/zephyr/doc/_extensions/zephyr/kconfig-role.py
#   zephyr.dtcompatible-role (unknown version) from /tmp/aa/zephyr/doc/_extensions/zephyr/dtcompatible-role.py
#   zephyr.link-roles (unknown version) from /tmp/aa/zephyr/doc/_extensions/zephyr/link-roles.py
#   sphinx_tabs.tabs (unknown version) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx_tabs/tabs.py
#   zephyr.warnings_filter (0.1.0) from /tmp/aa/zephyr/doc/_extensions/zephyr/warnings_filter.py
#   zephyr.doxyrunner (0.1.0) from /tmp/aa/zephyr/doc/_extensions/zephyr/doxyrunner.py
#   zephyr.vcs_link (0.1.0) from /tmp/aa/zephyr/doc/_extensions/zephyr/vcs_link.py
#   notfound.extension (0.8) from /tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/notfound/extension.py
#   zephyr.external_content (0.1.0) from /tmp/aa/zephyr/doc/_extensions/zephyr/external_content.py
Traceback (most recent call last):
  File "/tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/application.py", line 337, in build
    self.builder.build_update()
  File "/tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    len(to_build))
  File "/tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/builders/__init__.py", line 308, in build
    updated_docnames = set(self.read())
  File "/tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/builders/__init__.py", line 413, in read
    self._read_parallel(docnames, nproc=self.app.parallel)
  File "/tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/builders/__init__.py", line 464, in _read_parallel
    tasks.join()
  File "/tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/util/parallel.py", line 101, in join
    if not self._join_one():
  File "/tmp/aa/zephyr/doc/envname/lib/pypy3.8/site-packages/sphinx/util/parallel.py", line 120, in _join_one
    exc, logs, result = pipe.recv()
  File "/opt/pypy3/lib-python/3/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/pypy3/lib-python/3/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/pypy3/lib-python/3/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```
I'm not sure if pypy3 is supported or not since pypy2 support was removed and the bug mentioned pypy3 in passing. Python 3.10 is able to build the documentation successfully

### How to Reproduce

```
$ git clone https://github.com/zephyrproject-rtos/zephyr
$ cd zephyr/docs
$ virtualenv -p pypy3 envname
$ source envname/bin/activate
$ pip install -r ../scripts/requirements-base.txt
$ pip install -r ../scripts/requirements-docs.txt
$ make html-fast
```

### Expected behavior

(Assuming pypy3 is supported) for it to build successfully.

### Your project

https://github.com/zephyrproject-rtos/zephyr

### OS

Arch linux

### Python version

Pypy 3.8

### Sphinx version

4.4.0

**Comment by tk0miya** [comment]
I guess some child process was crashed for an unexpected reason. To investigate it, could you try building your document again by disabling parallel mode?

**Comment by thedjnK** [comment]
I think this error was caused by my own negligence of the number of processes that were launched and running in parallel and running out of RAM, works OK when forcing 4 threads for building but seems 20GB RAM is not enough for 12 threads when using pypy with default settings.
