### ISSUE TITLE
sphinx-autogen UnicodeDecodeError with source file containing non-ascii characters

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1019]
Using sphinx tip (6bb9dfbdf66e) with Python 3.2.3 on Gentoo Linux amd64:

```
matplotlib-1.2.0rc2 $ sphinx-autogen examples/pylab_examples/unicode_demo.py 
[autosummary] generating autosummary for: examples/pylab_examples/unicode_demo.py
Traceback (most recent call last):
  File "/usr/bin/sphinx-autogen-3.2", line 9, in <module>
    load_entry_point('Sphinx==1.1.3-dev-20121017', 'console_scripts', 'sphinx-autogen')()
  File "/usr/lib64/python3.2/site-packages/sphinx/ext/autosummary/generate.py", line 55, in main
    template_dir=options.templates)
  File "/usr/lib64/python3.2/site-packages/sphinx/ext/autosummary/generate.py", line 95, in generate_autosummary_docs
    items = find_autosummary_in_files(sources)
  File "/usr/lib64/python3.2/site-packages/sphinx/ext/autosummary/generate.py", line 212, in find_autosummary_in_files
    lines = f.read().splitlines()
  File "/usr/lib64/python3.2/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 134: ordinal not in range(128)
```

where unicode_demo.py is:

```
#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import pylab

pylab.plot([1, 2, 4])
pylab.title('Développés et fabriqués')
pylab.xlabel("réactivité nous permettent d'être sélectionnés et adoptés")
pylab.ylabel('André was here!')
pylab.text( 0.5, 2.5, 'Institut für Festkörperphysik', rotation=45)
pylab.text( 1, 1.5, 'AVA (check kerning)')

pylab.show()
```

Seems to be fixed for me, at least the above error is stopped (I haven't tried to generate any rst output) with:

```
--- sphinx/ext/autosummary/generate.py.orig
+++ sphinx/ext/autosummary/generate.py
@@ -18,6 +18,7 @@
     :license: BSD, see LICENSE for details.
 """

+import io
 import os
 import re
 import sys
@@ -208,7 +209,7 @@
     """
     documented = []
     for filename in filenames:
-        f = open(filename, 'r')
+        f = io.open(filename, 'r', encoding='utf-8')
         lines = f.read().splitlines()
         documented.extend(find_autosummary_in_lines(lines, filename=filename))
         f.close()

```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1019
- Originally reported by: Chris Mayo
- Originally created at: 2012-10-17T20:52:55.137

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2012-11-05 12:22:52+00:00_

We can not decide that file was encoded by 'utf-8' and Python 2.5 have no `io` module then we need another way to read safety.

**Comment by andreacassioli** [comment]
Hi,
I am facing a similar issue with a bibtex file. Any update?

**Comment by shimizukawa** [comment]
Fixed.
