### ISSUE TITLE
Exception during build process

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#10287]
### Describe the bug

During build process, an exception was raised
  ```
File "/usr/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
```

### How to Reproduce

Too many steps..

### Your project

https://github.com/python/python-docs-fr

### OS

Linux Rabelais 5.10.0-0.bpo.8-amd64 #1 SMP Debian 5.10.46-4~bpo10+1 (2021-08-07) x86_64 GNU/Linux

### Python version

3.7.3 (CPython)

### Sphinx version

3.2.1

### Additional context

```
# Sphinx version: 3.2.1
# Python version: 3.7.3 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 2.11.2
# Last messages:
#   construction [html]:cibles pour les fichiers sources 0 qui sont périmées
#   mise-à-jour de l'environnement :
#   0 ajouté, 41 modifié, 0 supprimé
#   lecture des sources... [ 20%] c-api/object .. library/asyncio
#   lecture des sources... [ 40%] library/dataclasses .. library/platform
#   lecture des sources... [ 60%] library/posix .. library/turtle
#   lecture des sources... [ 80%] library/unittest .. whatsnew/3.9
#   lecture des sources... [100%] whatsnew/changelog
#   
#   En attente des processus parallélisés...
# Loaded extensions:
#   sphinx.ext.mathjax (3.2.1) from /usr/local/lib/python3.7/dist-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/local/lib/python3.7/dist-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/local/lib/python3.7/dist-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/local/lib/python3.7/dist-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/local/lib/python3.7/dist-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/local/lib/python3.7/dist-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.8) from /usr/lib/python3/dist-packages/alabaster/__init__.py
#   sphinx.ext.coverage (3.2.1) from /usr/local/lib/python3.7/dist-packages/sphinx/ext/coverage.py
#   sphinx.ext.doctest (3.2.1) from /usr/local/lib/python3.7/dist-packages/sphinx/ext/doctest.py
#   pyspecific (1.0) from /home/thierry/Dépôts/python-docs-fr/venv/cpython/Doc/tools/extensions/pyspecific.py
#   c_annotations (1.0) from /home/thierry/Dépôts/python-docs-fr/venv/cpython/Doc/tools/extensions/c_annotations.py
#   escape4chm (1.0) from /home/thierry/Dépôts/python-docs-fr/venv/cpython/Doc/tools/extensions/escape4chm.py
#   asdl_highlight (1.0) from /home/thierry/Dépôts/python-docs-fr/venv/cpython/Doc/tools/extensions/asdl_highlight.py
#   peg_highlight (1.0) from /home/thierry/Dépôts/python-docs-fr/venv/cpython/Doc/tools/extensions/peg_highlight.py
#   glossary_search (0.1) from /home/thierry/Dépôts/python-docs-fr/venv/cpython/Doc/tools/extensions/glossary_search.py
#   python_docs_theme (unknown version) from /usr/local/lib/python3.7/dist-packages/python_docs_theme/__init__.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.7/dist-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.7/dist-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/usr/local/lib/python3.7/dist-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/usr/local/lib/python3.7/dist-packages/sphinx/builders/__init__.py", line 416, in read
    self._read_parallel(docnames, nproc=self.app.parallel)
  File "/usr/local/lib/python3.7/dist-packages/sphinx/builders/__init__.py", line 467, in _read_parallel
    tasks.join()
  File "/usr/local/lib/python3.7/dist-packages/sphinx/util/parallel.py", line 107, in join
    self._join_one()
  File "/usr/local/lib/python3.7/dist-packages/sphinx/util/parallel.py", line 112, in _join_one
    exc, logs, result = pipe.recv()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by tk0miya** [comment]
It seems some child process got crashed. To investigate what is happened, could you build your document again in single build mode (without `-j` option)?

>Sphinx version
>3.2.1

The latest version is 4.4.0. It would be better to upgrade to the latest one. Could you also try to upgrade it, please?

**Comment by AA-Turner** [comment]
Closing, please open a new issue if the problem persists on `5.0.0`.

A
