### ISSUE TITLE
cannot make html

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1032]
I get the following error when trying to `make html`:

```
#!
# Sphinx version: 1.1.3
# Python version: 2.6.7
# Docutils version: 0.9.1 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/Users/Steve/Virtual/crazytown/lib/python2.6/site-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/Users/Steve/Virtual/crazytown/lib/python2.6/site-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/Users/Steve/Virtual/crazytown/lib/python2.6/site-packages/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "/Users/Steve/Virtual/crazytown/lib/python2.6/site-packages/sphinx/builders/__init__.py", line 216, in build
    purple, length):
  File "/Users/Steve/Virtual/crazytown/lib/python2.6/site-packages/sphinx/builders/__init__.py", line 120, in status_iterator
    for item in iterable:
  File "/Users/Steve/Virtual/crazytown/lib/python2.6/site-packages/sphinx/environment.py", line 608, in update_generator
    self.clear_doc(docname)
  File "/Users/Steve/Virtual/crazytown/lib/python2.6/site-packages/sphinx/environment.py", line 447, in clear_doc
    domain.clear_doc(docname)
  File "/Users/Steve/Virtual/crazytown/lib/python2.6/site-packages/sphinxcontrib/httpdomain.py", line 400, in clear_doc
    for typ, routes in self.routes.iteritems():
  File "/Users/Steve/Virtual/crazytown/lib/python2.6/site-packages/sphinxcontrib/httpdomain.py", line 397, in routes
    return dict((key, self.data[key]) for key in self.object_types)
  File "/Users/Steve/Virtual/crazytown/lib/python2.6/site-packages/sphinxcontrib/httpdomain.py", line 397, in <genexpr>
    return dict((key, self.data[key]) for key in self.object_types)
KeyError: 'patch'

```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1032
- Originally reported by: Anonymous
- Originally created at: 2012-11-01T20:47:26.684

**Comment by shimizukawa** [comment]
_From Jon Waltman on 2012-11-01 21:54:06+00:00_

The error is raised in a third party extension `httpdomain` which is in the 
[sphinx-contrib](https://bitbucket.org/birkenfeld/sphinx-contrib/) package.  It might be an issue on their end.

Have you successfully used this package before and it just recently quit working? 

You might clearing the cache (`make clean`) before building and see if that happens to fix the problem.

**Comment by shimizukawa** [comment]
_From [speg](https://bitbucket.org/speg) on 2012-11-06 02:07:04+00:00_

Hmm, yes it worked a while ago (like 3 or 4 months ago?) but I went to use it again last week and ran into this.

**Comment by shimizukawa** [comment]
_From Jon Waltman on 2012-11-06 09:07:58+00:00_

It seems that `patch` support was recently added in httpdomain 
([sphinx-contrib d84f7bb](https://bitbucket.org/birkenfeld/sphinx-contrib/changeset/d84f7bbcfd2a409b12d307e885c152c48fb91806)) and it doesn't handle the case when the build cache is from a previous version.

Does removing the build cache (by deleting the `_build` directory) fix this problem?

Since this problem appears to be caused by the httpdomain extension, I'm going to close this ticket and suggest you report this issue to [sphinx-contrib](https://bitbucket.org/birkenfeld/sphinx-contrib).

**Comment by shimizukawa** [comment]
_From Jon Waltman on 2012-11-06 09:09:33+00:00_

Issue in third party extension `httpdomain`

**Comment by shimizukawa** [comment]
_From [speg](https://bitbucket.org/speg) on 2012-11-06 13:55:22+00:00_

Jon, you are a champ.  Removing `build` allowed me to `build html`! :thumbsup:
