### ISSUE TITLE
TypeError: expected string or bytes-like object (i am new with phinx)

### ISSUE THREAD

**Issue by blancos-dev** [sphinx-doc/sphinx#10339]
### Describe the bug

# Sphinx version: 4.5.0
# Python version: 3.10.2 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/enrique/.local/lib/python3.10/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/enrique/.local/lib/python3.10/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/home/enrique/.local/lib/python3.10/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/enrique/.local/lib/python3.10/site-packages/sphinx/registry.py", line 425, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/enrique/.local/lib/python3.10/site-packages/rinoh/__init__.py", line 41, in <module>
    from . import resource
  File "/home/enrique/.local/lib/python3.10/site-packages/rinoh/resource.py", line 205, in <module>
    from .template import DocumentTemplate
  File "/home/enrique/.local/lib/python3.10/site-packages/rinoh/template.py", line 42, in <module>
    from .stylesheets import sphinx
  File "/home/enrique/.local/lib/python3.10/site-packages/rinoh/stylesheets/__init__.py", line 42, in <module>
    .format(stylesheet.description, stylesheet))
  File "/home/enrique/.local/lib/python3.10/site-packages/rinoh/style.py", line 670, in __str__
    for name, entry_point in self.installed_resources:
  File "/home/enrique/.local/lib/python3.10/site-packages/rinoh/resource.py", line 54, in installed_resources
    for entry_point in ilm.entry_points()[cls.entry_point_group]:
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 980, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 429, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 977, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 592, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 842, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

### How to Reproduce

none

### Expected behavior

none

### Your project

lenguage python

### Screenshots

none

### OS

linux

### Python version

none

### Sphinx version

none

### Sphinx extensions

none

### Extra tools

none

### Additional context

ejecute make html

**Comment by blancos-dev** [comment]
I limit the error more, apparently the error occurs when placing the extension "rinoh.frontend.sphinx", when executing "python3 -m rinoh --help" I get the same error, I don't know if someone has an alternative to the extension.

**Comment by cblegare** [comment]
Hello @blancos-dev , I am no maintainer of Sphinx, just a human trying to help.

First, you should aim at helping others help you by formatting log output or code snippet with backticks:

````
```
Triple backticks, your stuff, then triple backticks again
```
````

See also https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

The error you are facing indeed comes from Rinohtype, an other project.  Here it is: https://github.com/brechtm/rinohtype/issues/285

You should be able to fix this by either

- Wait for the rinohtype release that include the fix to be available, then update your dependencies
- Install Rinohtype directly from their repository
- Use python 3.9 instead of 3.10 in the meantime

If this comment answers your question, you can close the issue

**Comment by matthew-ivre** [comment]
I encountered the same error. It seems related to this pull request: https://github.com/brechtm/rinohtype/commit/ad38d254efbcb24120ad4e73664ca2106e04f3f9

I manually made the same update in the file on my machine: C:\Users\<your_user_name>\AppData\Local\Programs\Python\Python310\Lib\site-packages\rinoh\resource.py

Things seem to be working as expected now. I can get a PDF output from rinohtype.

**Comment by tk0miya** [comment]
It seems this error was raised from rinohtype extension. So please post this to their project.
Thanks,
