### ISSUE TITLE
Sphinx4.5.0: ModuleNotFoundError: No module named 'attr.validators'; 'attr' is not a package

### ISSUE THREAD

**Issue by ebattat** [sphinx-doc/sphinx#10377]
### Describe the bug

Running Sphinx v4.5.0
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/benchmark-runner/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/benchmark-runner/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/benchmark-runner/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/benchmark-runner/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 438, in load_extension
    metadata = setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/benchmark-runner/envs/latest/lib/python3.7/site-packages/myst_parser/__init__.py", line 12, in setup
    from myst_parser.sphinx_parser import MystParser
  File "/home/docs/checkouts/readthedocs.org/user_builds/benchmark-runner/envs/latest/lib/python3.7/site-packages/myst_parser/sphinx_parser.py", line 15, in <module>
    from myst_parser.main import create_md_parser
  File "/home/docs/checkouts/readthedocs.org/user_builds/benchmark-runner/envs/latest/lib/python3.7/site-packages/myst_parser/main.py", line 7, in <module>
    from attr.validators import (
ModuleNotFoundError: No module named 'attr.validators'; 'attr' is not a package

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/benchmark-runner/envs/latest/lib/python3.7/site-packages/myst_parser/main.py", line 7, in <module>
    from attr.validators import (
ModuleNotFoundError: No module named 'attr.validators'; 'attr' is not a package
The full traceback has been saved in /tmp/sphinx-err-y0em6wfw.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. 

### How to Reproduce

```
$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

### Your project

https://benchmark-runner.readthedocs.io/en/latest/

### OS

Linux

### Python version

3.9.0

### Sphinx version

4.5.0

**Comment by ebattat** [comment]
Solved by adding to requirement:
attrs==21.4.0
