### ISSUE TITLE
Transitions cannot be used in only:: directives

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1040]
I am not sure if this is a bug of Sphinx or Docutils, but I decided to post it here anyway.

Trying to run sphinx on this source

```
#!ReST
Some text.

.. only:: html

   ----

Some more text.
```

Gives the following exception :

```
#!python
# Sphinx version: 1.1.3
# Python version: 2.7.3
# Docutils version: 0.9.1 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 216, in build
    purple, length):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 120, in status_iterator
    for item in iterable:
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 613, in update_generator
    self.read_doc(docname, app=app)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 761, in read_doc
    pub.publish()
  File "/usr/local/lib/python2.7/dist-packages/docutils/core.py", line 222, in publish
    self.apply_transforms()
  File "/usr/local/lib/python2.7/dist-packages/docutils/core.py", line 203, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/local/lib/python2.7/dist-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docutils/transforms/misc.py", line 98, in apply
    self.visit_transition(node)
  File "/usr/local/lib/python2.7/dist-packages/docutils/transforms/misc.py", line 109, in visit_transition
    isinstance(node.parent, nodes.section))
AssertionError
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1040
- Originally reported by: Tristan VINCENT
- Originally created at: 2012-11-15T02:01:13.664

**Comment by shimizukawa** [comment]
_From Jon Waltman on 2012-12-05 19:41:30+00:00_

This is indeed a problem with Sphinx.  It provides the `only` directive which tries to allow certain things (like titles and transitions) in the body even though they are normally document level elements.

This fails due because the body is parsed in a similar fashion as an empty document and a transition cannot be the first element in a document or after a title.

http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#transitions

Transitions should work though as long as they aren't the first element in the body.  
You might try adding a comment before it as a work-around.

**Comment by shimizukawa** [comment]
_From Tristan VINCENT on 2012-12-06 02:16:47+00:00_

The comment work-around works like a treat, thanks !
