### ISSUE TITLE
AssertionError: wrong color format 'var(--jp-mirror-editor-variable-color)'

### ISSUE THREAD

**Issue by taconet** [sphinx-doc/sphinx#10417]
### Describe the bug

jupyter-book build fails with "assert False, "wrong color format %r" % text"

[mybook]$ jupyter-book build . 2>error.txt
Running Jupyter-Book v0.12.2
Source Folder: /tmp/jupytertest/mybook
Config Path: /tmp/jupytertest/mybook/_config.yml
Output Path: /tmp/jupytertest/mybook/_build/html
Running Sphinx v4.5.0
[sphinx-err-p7mhayi1.log](https://github.com/sphinx-doc/sphinx/files/8611110/sphinx-err-p7mhayi1.log)
[error.txt](https://github.com/sphinx-doc/sphinx/files/8611133/error.txt)

[mybook]$ pip3 list > pip3_list.txt
[pip3_list.txt](https://github.com/sphinx-doc/sphinx/files/8611213/pip3_list.txt)

### How to Reproduce

```
$ jupyter-book create mybook
$ cd mybook
$ jupyter-book build .


### Expected behavior

html files created

### Your project

it is the the jupyter book created by jupyter-book create

### Screenshots

_No response_

### OS

linux debian 10.12

### Python version

 3.7.3 (CPython)

### Sphinx version

 4.5.0

### Sphinx extensions

_No response_

### Extra tools

jupyter-book

### Additional context

I found solutions that did not work in my case about the version of nbconvert and the  version of pygments

**Comment by AA-Turner** [comment]
From the logfile, looks like somehow `var(--jp-mirror-editor-variable-color)` is getting passed to Pygments. Can you search for that string and provide a link to where it appears please? 

```pytb
Traceback (most recent call last):
  File "/home/taconet/.local/lib/python3.7/site-packages/jupyter_book/sphinx.py", line 128, in build_sphinx
    keep_going=keep_going,
  File "/home/taconet/.local/lib/python3.7/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/home/taconet/.local/lib/python3.7/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/taconet/.local/lib/python3.7/site-packages/sphinx/registry.py", line 425, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/taconet/.local/lib/python3.7/site-packages/myst_nb/__init__.py", line 11, in <module>
    from jupyter_sphinx import REQUIRE_URL_DEFAULT
  File "/home/taconet/.local/lib/python3.7/site-packages/jupyter_sphinx/__init__.py", line 13, in <module>
    from .ast import (
  File "/home/taconet/.local/lib/python3.7/site-packages/jupyter_sphinx/ast.py", line 17, in <module>
    import nbconvert
  File "/home/taconet/.local/lib/python3.7/site-packages/nbconvert/__init__.py", line 4, in <module>
    from .exporters import *
  File "/home/taconet/.local/lib/python3.7/site-packages/nbconvert/exporters/__init__.py", line 4, in <module>
    from .slides import SlidesExporter
  File "/home/taconet/.local/lib/python3.7/site-packages/nbconvert/exporters/slides.py", line 12, in <module>
    from ..preprocessors.base import Preprocessor
  File "/home/taconet/.local/lib/python3.7/site-packages/nbconvert/preprocessors/__init__.py", line 7, in <module>
    from .csshtmlheader import CSSHTMLHeaderPreprocessor
  File "/home/taconet/.local/lib/python3.7/site-packages/nbconvert/preprocessors/csshtmlheader.py", line 14, in <module>
    from jupyterlab_pygments import JupyterStyle
  File "/home/taconet/.local/lib/python3.7/site-packages/jupyterlab_pygments/__init__.py", line 4, in <module>
    from .style import JupyterStyle
  File "/home/taconet/.local/lib/python3.7/site-packages/jupyterlab_pygments/style.py", line 10, in <module>
    class JupyterStyle(Style):
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 101, in __new__
    ndef[0] = colorformat(styledef)
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 58, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format 'var(--jp-mirror-editor-variable-color)'
```

A

**Comment by taconet** [comment]
In the file /home/taconet/.local/lib/python3.7/site-packages/jupyterlab_pygments/style.py I found that : 
[style.py.txt](https://github.com/sphinx-doc/sphinx/files/8611391/style.py.txt)

    styles = {
        Text:                      'var(--jp-mirror-editor-variable-color)',        # no class
        Whitespace:              
 '',                                              # class: 'w' 
        Error:                     'var(--jp-mirror-editor-error-color)',           # class: 'err'
        Other:                     '',                                              # class: 'x'

Is it what you are looking for ?

**Comment by AA-Turner** [comment]
Per https://github.com/jupyterlab/jupyterlab_pygments/issues/5#issuecomment-691958218, an you try with a fresh venv?

A

**Comment by taconet** [comment]
Do you mean something like that :

 python3 -m venv new-env

**Comment by AA-Turner** [comment]
Yes, reinstall all your dependencies -- Eric in that comment was saying it was an issue with pip (so do `python -m pip --upgrade pip` first).

A

**Comment by taconet** [comment]
I don't know if I have done properly : 

pip install --upgrade pip
python3 -m venv new-env
jupyter-book build .

But it gives the same result.

**Comment by tk0miya** [comment]
May I close this? I'm not sure why did you post this to the Sphinx project, but please post such a bug report to jupyter-book project, if you'll see another error next time.

**Comment by taconet** [comment]
Yes you can. 
I reported here because in the error message it was written "A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!" 
Next time I will switch. Thanks
