### ISSUE TITLE
TypeError: entry_points() got an unexpected keyword argument 'group'

### ISSUE THREAD

**Issue by martinobertoni** [sphinx-doc/sphinx#10479]
### Describe the bug

when running sphinx-build I get the following error:

Running Sphinx v4.5.0
making output directory... done

Traceback (most recent call last):
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/application.py", line 256, in __init__
    self._init_builder()
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/application.py", line 314, in _init_builder
    self.builder.init()
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 212, in init
    self.init_templates()
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 260, in init_templates
    self.theme = theme_factory.create(themename)
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/theming.py", line 232, in create
    self.load_extra_theme(name)
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/theming.py", line 177, in load_extra_theme
    self.load_external_theme(name)
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/theming.py", line 199, in load_external_theme
    theme_entry_points = entry_points(group='sphinx.html_themes')
TypeError: entry_points() got an unexpected keyword argument 'group'

### How to Reproduce

make docs

### Your project

https://gitlabsbnb.irbbarcelona.org/packages/chemical_checker/-/tree/master/package/docs

### OS

ubuntu 20.04

### Python version

3.7

### Sphinx version

4.5.0

### Sphinx extensions

autodoc

**Comment by AA-Turner** [comment]
What does `conda list` show? I imagine you have `importlib_metadata` 3.5.0 or earlier -- you need to update.

A

**Comment by panhongtao07** [comment]
I believe there's user who can't update `importlib_metadata`. I find the same error using Python 3.11, which is not expected especially when I installed more package to support `sphinx`. We should use `importlib.metadata` with priority after Python 3.10.
