### ISSUE TITLE
inconsistent leading whitespace ...causes exception

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1049]
# Sphinx version: 1.1.2
# Python version: 2.7.3
# Docutils version: 0.8.1 release
# Jinja2 version: 2.6

Traceback (most recent call last):
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/sphinx/builders/**init**.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/sphinx/builders/**init**.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/sphinx/ext/doctest.py", line 270, in write
    self.test_doc(docname, doctree)
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/sphinx/ext/doctest.py", line 329, in test_doc
    self.test_group(group, self.env.doc2path(docname, base=None))
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/sphinx/ext/doctest.py", line 379, in test_group
    filename, code[0].lineno)
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/doctest.py", line 645, in get_doctest
    return DocTest(self.get_examples(string, name), globs,
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/doctest.py", line 659, in get_examples
    return [x for x in self.parse(string, name)
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/doctest.py", line 621, in parse
    self._parse_example(m, name, lineno)
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/doctest.py", line 691, in _parse_example
    lineno + len(source_lines))
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/doctest.py", line 777, in _check_prefix
    (lineno+i+1, name, line))
ValueError: line 6 of the docstring for default has inconsistent leading whitespace: u"['South Dakota' 'Iowa' 'North Dakota' 'Missouri' 'Kansas' 'Nebraska']"

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1049
- Originally reported by: [philip_stephens](https://bitbucket.org/philip_stephens)
- Originally created at: 2012-11-30T23:48:42.090

**Comment by shimizukawa** [comment]
_From [philip_stephens](https://bitbucket.org/philip_stephens) on 2012-11-30 23:01:36+00:00_

fixed when I upgraded to sphinx v 1.1.3

**Comment by shimizukawa** [comment]
_From [philip_stephens](https://bitbucket.org/philip_stephens) on 2012-11-30 23:02:27+00:00_

fixed between 1.1.2 and 1.1.3
