### ISSUE TITLE
not able to build the documentation on Ubuntu 22.04

### ISSUE THREAD

**Issue by padhupradheep** [sphinx-doc/sphinx#10536]
### Describe the bug

```
# Sphinx version: 4.3.2
# Python version: 3.10.4 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 231, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 388, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3/dist-packages/sphinx/registry.py", line 442, in load_extension
    metadata = setup(app)
  File "/home/pradheep/.local/lib/python3.10/site-packages/breathe/__init__.py", line 13, in setup
    from . import directives
  File "/home/pradheep/.local/lib/python3.10/site-packages/breathe/directives.py", line 4, in <module>
    from .renderer import DoxygenToRstRendererFactory
  File "/home/pradheep/.local/lib/python3.10/site-packages/breathe/renderer/__init__.py", line 4, in <module>
    from ..node_factory import create_node_factory
  File "/home/pradheep/.local/lib/python3.10/site-packages/breathe/node_factory.py", line 5, in <module>
    import sphinx.ext.mathbase
ModuleNotFoundError: No module named 'sphinx.ext.mathbase'
```

### How to Reproduce

```
$ git clone https://github.com/ros-planning/navigation.ros.org
follow the readme
```

### Your project

https://github.com/ros-planning/navigation.ros.org

### OS

Ubuntu 22.04

### Python version

3.10

### Sphinx version

4.3

**Comment by AA-Turner** [comment]
sphinx.ext.mathbase was removed around Sphinx 2 -- it is no longer needed. Please check the documentation, or breathe issue 451 has more detail.

A

**Comment by AA-Turner** [comment]
(You are probably using an outdated version of breathe)

A

**Comment by padhupradheep** [comment]
> (You are probably using an outdated version of breathe)

Seems to be the case, we were using 4.9.1 and the latest being the 4.28.0! Sorry for the fuzz..
