### ISSUE TITLE
AttributeError: Neither 'Label' object nor 'Comparator' object has an attribute 'doc'

### ISSUE THREAD

**Issue by biyani701** [sphinx-doc/sphinx#10637]
### Describe the bug

```
# Sphinx version: 4.5.0
# Python version: 3.10.2 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.3
# Last messages:
#   myst v0.18.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['colon_fence'], disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=None, heading_slug_func=None, footnote_transition=True, words_per_minute=200, sub_delimiters=('{', '}'), linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area')
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 14 source files that are out of date
#   updating environment:
#   [new config]
#   14 added, 0 changed, 0 removed
#   reading sources... [  7%] about_me
#   reading sources... [ 14%] architecture
#   reading sources... [ 21%] index
#   reading sources... [ 28%] models
# Loaded extensions:
#   sphinx.ext.mathjax (4.5.0) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.2) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.3) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\alabaster\__init__.py
#   myst_parser (0.18.0) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\myst_parser\__init__.py
#   sphinx_sqlalchemy (0.1.1) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx_sqlalchemy\__init__.py
#   sphinx_rtd_theme (unknown version) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx_rtd_theme\__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\ext\autodoc\preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.5.0) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\ext\autodoc\type_comment.py
#   sphinx.ext.autodoc (4.5.0) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\ext\autodoc\__init__.py
#   sphinx.ext.viewcode (4.5.0) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\ext\viewcode.py
#   sphinx.ext.napoleon (4.5.0) from c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\ext\napoleon\__init__.py
Traceback (most recent call last):
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 846, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute 'doc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\application.py", line 330, in build
    self.builder.build_update()
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\builders\__init__.py", line 286, in build_update
    self.build(to_build,
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\builders\__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\builders\__init__.py", line 407, in read
    self._read_serial(docnames)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\builders\__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\builders\__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\io.py", line 181, in read_doc
    pub.publish()
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\io.py", line 101, in read
    self.parse()
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx\parsers.py", line 89, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 2344, in explicit_markup
    self.explicit_list(blank_finish)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 2369, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 318, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 2647, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 2096, in directive
    return self.run_directive(
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\docutils\parsers\rst\states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx_sqlalchemy\main.py", line 88, in run
    self.add_content(mapper, definition)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx_sqlalchemy\main.py", line 106, in add_content
    doc_column = any(column.doc for column in mapper.columns)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sphinx_sqlalchemy\main.py", line 106, in <genexpr>
    doc_column = any(column.doc for column in mapper.columns)
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 848, in __getattr__
    util.raise_(
  File "c:\users\dell\pycharmprojects\jiradashboard\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
AttributeError: Neither 'Label' object nor 'Comparator' object has an attribute 'doc'
```

### How to Reproduce

```
$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

### Your project

na

### OS

Win

### Python version

3.10

### Sphinx version

4.5.0

**Comment by tk0miya** [comment]
Could you let us know how to reproduce this error, please? It would be very nice if you create a minimal reproducible example.
Thanks,

**Comment by biyani701** [comment]
Thanks for your response. What I observed is that if I am using a column
property in my model class, I get this error.
I am using postgresql (postgresql+psycopg2://)

assignee_name =
column_property(select(User.displayName).where(User.accountId ==
assignee).scalar_subquery())

There are two tables in play. One i call User and another one i have
named it Issue which contains the assignee field.


See if this helps, otherwise, i will try to create a min working
application to replicate the issue.
