### ISSUE TITLE
LaTeX builds failing due to unresolvable references

### ISSUE THREAD

**Issue by Zeitsperre** [sphinx-doc/sphinx#10780]
### Describe the bug

Builds of my documentation for HTML are building with zero warnings, but when trying to build LaTeX PDFs, there are some esoteric errors that crash the build and don't explain very much:

```
# Sphinx version: 5.1.1
# Python version: 3.10.5 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.2
# Last messages:
#   xclim.indicators
#   xclim.indicators.atmos
#   xclim.indicators.land
#   xclim.indicators.seaIce
#   xclim.indices
#   xclim.sdba
#   xclim.testing
#   
#   resolving references...
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (5.1.1) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (5.1.1) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (5.1.1) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.viewcode (5.1.1) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.napoleon (5.1.1) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.coverage (5.1.1) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.todo (5.1.1) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/ext/todo.py
#   sphinx.ext.intersphinx (5.1.1) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.extlinks (5.1.1) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/ext/extlinks.py
#   rstjinja (unknown version) from /home/tjs/git/xclim/docs/rstjinja.py
#   nbsphinx (0.8.9) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/nbsphinx.py
#   IPython.sphinxext.ipython_console_highlighting (unknown version) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/IPython/sphinxext/ipython_console_highlighting.py
#   autodoc_indicator (unknown version) from /home/tjs/git/xclim/docs/autodoc_indicator.py
#   sphinxcontrib.bibtex (2.4.2) from /home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinxcontrib/bibtex/__init__.py
Traceback (most recent call last):
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/cmd/build.py", line 277, in build_main
    app.build(args.force_all, filenames)
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 298, in build_update
    self.build(['__all__'], to_build)
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 367, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/builders/latex/__init__.py", line 282, in write
    doctree = self.assemble_doctree(
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/builders/latex/__init__.py", line 346, in assemble_doctree
    self.env.resolve_references(largetree, indexfile, self)
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/environment/__init__.py", line 564, in resolve_references
    self.apply_post_transforms(doctree, fromdocname)
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/environment/__init__.py", line 576, in apply_post_transforms
    transformer.apply_transforms()
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/transforms/__init__.py", line 80, in apply_transforms
    super().apply_transforms()
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/transforms/post_transforms/__init__.py", line 35, in apply
    self.run(**kwargs)
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/builders/latex/transforms.py", line 349, in run
    self.document.walkabout(visitor)
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 6 more times]
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/docutils/nodes.py", line 219, in walkabout
    visitor.dispatch_visit(self)
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/docutils/nodes.py", line 2021, in dispatch_visit
    return method(node)
  File "/home/tjs/mambaforge/envs/xclim310/lib/python3.10/site-packages/sphinx/builders/latex/transforms.py", line 448, in visit_footnote_reference
    self.footnotes.remove(footnote)
ValueError: list.remove(x): x not in list
```

### How to Reproduce

```
$ git clone https://github.com/Ouranosinc/xclim
$ cd xclim
$ pip install -e .[docs]
$ cd docs
$ python -m sphinx -b latex -D language=en -d _build/doctrees . _build/latex 
```

### Expected behavior

Generation of LaTeX-based PDF

### Your project

https://github.com/Ouranosinc/xclim

### OS

Linux

### Python version

3.10

### Sphinx version

5.1.1

### Sphinx extensions

sphinx.ext.autodoc, sphinx.ext.viewcode, sphinx.ext.mathjax, sphinx.ext.napoleon, sphinx.ext.coverage, sphinx.ext.todo, sphinx.ext.autosectionlabel, sphinx.ext.intersphinx, sphinx.ext.extlinks, rstjinja, nbsphinx, IPython.sphinxext.ipython_console_highlighting, autodoc_indicator, sphinxcontrib.bibtex

### Extra tools

ReadTheDocs

### Additional context

https://readthedocs.org/projects/xclim/builds/17825507/
https://github.com/Ouranosinc/xclim/issues/1154

**Comment by Zeitsperre** [comment]
Resolved:

I had left one or two `footcite` references in the code base (a role used by [sphinxcontrib-bibtex](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html?highlight=footcite#role-footcite-p)) and this was causing errors in `sphinx.transform`. A more verbose error message would be nice, but this is more in the scope of `sphinxcontrib-bibtex`.
