### ISSUE TITLE
Better error message for non-installed program (dot)

### ISSUE THREAD

**Issue by oscargus** [sphinx-doc/sphinx#10795]
### Describe the bug

Not a big deal, but since reporting is encouraged according to the message:

On CI with 3.6:
```
Exception occurred:
  File "/usr/local/lib/python3.6/os.py", line 800, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Locally with 3.10 (full traceback):
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/cmd/build.py", line 277, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.10/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 301, in build_update
    self.build(to_build,
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 367, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 559, in write
    self._write_serial(sorted(docnames))
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 569, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 665, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/lib/python3.10/site-packages/docutils/writers/__init__.py", line 77, in write
    self.translate()
  File "/usr/lib/python3.10/site-packages/sphinx/writers/html.py", line 59, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.10/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.10/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.10/site-packages/docutils/nodes.py", line 178, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3.10/site-packages/sphinx/util/docutils.py", line 563, in dispatch_visit
    method(node)
  File "/usr/lib/python3.10/site-packages/sphinx/ext/inheritance_diagram.py", line 418, in html_visit_inheritance_diagram
    render_dot_html(self, node, dotcode, {}, 'inheritance', 'inheritance',
  File "/usr/lib/python3.10/site-packages/sphinx/ext/graphviz.py", line 272, in render_dot_html
    fname, outfn = render_dot(self, code, options, format, prefix, filename)
  File "/usr/lib/python3.10/site-packages/sphinx/ext/graphviz.py", line 246, in render_dot
    ret = subprocess.run(dot_args, input=code.encode(), stdout=PIPE, stderr=PIPE,
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1720, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I guess it depends on the following warning earlier:
```
WARNING: The config value `graphviz_dot' has type `NoneType', defaults to `str'.
```
I set 
```
graphviz_dot = shutil.which('dot')
```
but apparently I missed installing graphviz on the CI (and recreated it as below locally).

### How to Reproduce

Build with an inheritance diagram and set

```
graphviz_dot = None
```

### Expected behavior

It may be possible to get a better error message, either by checking that the exectuable is not None earlier or catching the TypeError.

Yet another option is to rely on the Python graphviz package, although there will be a bit of a transition there...

### Your project

https://gitlab.liu.se/da/B-ASIC

### OS

Arch Linux (local), Debian (CI)

### Python version

3.6 to 3.10

### Sphinx version

5.1.1

### Sphinx extensions

sphinx.ext.inheritancediagram

### Additional context

One set of failing pipelines is: https://gitlab.liu.se/da/B-ASIC/-/pipelines/74684

**Comment by AA-Turner** [comment]
Fixed in b3e3c1add9e512b21339a9f246454722ade9e340
