### ISSUE TITLE
Can't make documentation on Python 3.3

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1080]
```
#!python
# Sphinx version: 1.1.3
# Python version: 3.3.0
# Docutils version: 0.10 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/Users/dsx/Documents/Projects/Tata/Ananke/lib/python3.3/site-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/Users/dsx/Documents/Projects/Tata/Ananke/lib/python3.3/site-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/Users/dsx/Documents/Projects/Tata/Ananke/lib/python3.3/site-packages/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "/Users/dsx/Documents/Projects/Tata/Ananke/lib/python3.3/site-packages/sphinx/builders/__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/dsx/Documents/Projects/Tata/Ananke/lib/python3.3/site-packages/sphinx/builders/__init__.py", line 291, in write
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/Users/dsx/Documents/Projects/Tata/Ananke/lib/python3.3/site-packages/sphinx/environment.py", line 1230, in get_and_resolve_doctree
    doctree = self.get_doctree(docname)
  File "/Users/dsx/Documents/Projects/Tata/Ananke/lib/python3.3/site-packages/sphinx/environment.py", line 1215, in get_doctree
    doctree = pickle.load(f)
AttributeError: 'str' object has no attribute '__dict__'

```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1080
- Originally reported by: Anonymous
- Originally created at: 2013-01-14T20:28:33.414

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2013-01-14 19:30:46+00:00_

You'll have to do a clean build (e.g. "make clean html") when switching between Python versions used with Sphinx.

This is a known issue and will be fixed in the next version.
