### ISSUE TITLE
sphinx.ext.doctest: Doctest inside of project fails (params reversed)

### ISSUE THREAD

**Issue by tony** [sphinx-doc/sphinx#10801]
### Describe the bug

`sphinx.ext.doctest`'s [`is_allowed_version`](https://github.com/sphinx-doc/sphinx/blob/5.x/sphinx/ext/doctest.py#L40-L55) ([usage](https://github.com/sphinx-doc/sphinx/blob/5.x/sphinx/ext/doctest.py#L131-L133)) has its versions flipped

The params are reversed

### How to Reproduce

1. Extract doctest from sphinx.ext.doctest:

    _example.py_:
    
    ```python
    from packaging.specifiers import InvalidSpecifier, SpecifierSet
    from packaging.version import Version
    
    
    def is_allowed_version(spec: str, version: str) -> bool:
        """Check `spec` satisfies `version` or not.
    
        This obeys PEP-440 specifiers:
        https://peps.python.org/pep-0440/#version-specifiers
    
        Some examples:
    
            >>> is_allowed_version('3.3', '<=3.5')
            True
            >>> is_allowed_version('3.3', '<=3.2')
            False
            >>> is_allowed_version('3.3', '>3.2, <4.0')
            True
        """
        return Version(version) in SpecifierSet(spec)
    ```
2. Run through `doctest`:

    ```console
    $ python -m doctest example.py
    ```

### Expected behavior

Test should pass silently

### Your project

https://gist.github.com/tony/05c66199c003aaf712a39b5dbc103eba

### Screenshots

```
**********************************************************************
File "~/sphinx/example.py", line 13, in example.is_allowed_version
Failed example:
    is_allowed_version('3.3', '<=3.5')
Exception raised:
    Traceback (most recent call last):
      File "~/.python/installs/3.8.13/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest example.is_allowed_version[0]>", line 1, in <module>
        is_allowed_version('3.3', '<=3.5')
      File "~/sphinx/example.py", line 20, in is_allowed_version
        return Version(version) in SpecifierSet(spec)
      File "~/sphinx/.venv/lib/python3.8/site-packages/packaging/version.py", line 266, in __init__
        raise InvalidVersion(f"Invalid version: '{version}'")
    packaging.version.InvalidVersion: Invalid version: '<=3.5'
**********************************************************************
File "~/sphinx/example.py", line 15, in example.is_allowed_version
Failed example:
    is_allowed_version('3.3', '<=3.2')
Exception raised:
    Traceback (most recent call last):
      File "~/.python/installs/3.8.13/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest example.is_allowed_version[1]>", line 1, in <module>
        is_allowed_version('3.3', '<=3.2')
      File "~/sphinx/example.py", line 20, in is_allowed_version
        return Version(version) in SpecifierSet(spec)
      File "~/sphinx/.venv/lib/python3.8/site-packages/packaging/version.py", line 266, in __init__
        raise InvalidVersion(f"Invalid version: '{version}'")
    packaging.version.InvalidVersion: Invalid version: '<=3.2'
**********************************************************************
File "~/sphinx/example.py", line 17, in example.is_allowed_version
Failed example:
    is_allowed_version('3.3', '>3.2, <4.0')
Exception raised:
    Traceback (most recent call last):
      File "~/.python/installs/3.8.13/lib/python3.8/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest example.is_allowed_version[2]>", line 1, in <module>
        is_allowed_version('3.3', '>3.2, <4.0')
      File "~/sphinx/example.py", line 20, in is_allowed_version
        return Version(version) in SpecifierSet(spec)
      File "~/sphinx/.venv/lib/python3.8/site-packages/packaging/version.py", line 266, in __init__
        raise InvalidVersion(f"Invalid version: '{version}'")
    packaging.version.InvalidVersion: Invalid version: '>3.2, <4.0'
**********************************************************************
1 items had failures:
   3 of   3 in example.is_allowed_version
***Test Failed*** 3 failures.
```

### OS

WSL 2, Ubuntu, Windows 11

### Python version

3.8

### Sphinx version

5.2.0.dev20220905

### Sphinx extensions

sphinx.ext.doctest

### Extra tools

doctest

### Additional context

To fix, reverse:

```python
from packaging.specifiers import InvalidSpecifier, SpecifierSet
from packaging.version import Version


def is_allowed_version(spec: str, version: str) -> bool:
    """Check `spec` satisfies `version` or not.

    This obeys PEP-440 specifiers:
    https://peps.python.org/pep-0440/#version-specifiers

    Some examples:

        >>> is_allowed_version('<=3.5', '3.3')
        True
        >>> is_allowed_version('<=3.2', '3.3')
        False
        >>> is_allowed_version('>3.2, <4.0', '3.3')
        True
    """
    return Version(version) in SpecifierSet(spec)
```

```console
$ python -m doctest example.py -v
```

Output:

```
Trying:
    is_allowed_version('<=3.5', '3.3')
Expecting:
    True
ok
Trying:
    is_allowed_version('<=3.2', '3.3')
Expecting:
    False
ok
Trying:
    is_allowed_version('>3.2, <4.0', '3.3')
Expecting:
    True
ok
1 items had no tests:
    example
1 items passed all tests:
   3 tests in example.is_allowed_version
3 tests in 2 items.
3 passed and 0 failed.
Test passed.
```

**Comment by AA-Turner** [comment]
We should probably run doctests as part of our CI...

A
