### ISSUE TITLE
sphinx-quickstart fails on Python 3.3 on Mac OS X

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1081]
I have a fresh install of Sphinx and I've set my locale environment variables to work around what appears to be a shortcoming in the Max OS X Terminal.app to get Sphinx working at all, as per the response at http://stackoverflow.com/questions/10921430/fresh-installation-of-sphinx-quickstart-fails.

However, when I run sphinx-quickstart I'm getting this traceback:

```
Creating file ./source/conf.py.
Traceback (most recent call last):
  File "/Users/rjs/dev/virtualenvs/trailer/bin/sphinx-quickstart", line 9, in <module>
    load_entry_point('Sphinx==1.1.3', 'console_scripts', 'sphinx-quickstart')()
  File "/Users/rjs/dev/virtualenvs/trailer/lib/python3.3/site-packages/sphinx/quickstart.py", line 1068, in main
    generate(d)
  File "/Users/rjs/dev/virtualenvs/trailer/lib/python3.3/site-packages/sphinx/quickstart.py", line 1019, in generate
    write_file(path.join(srcdir, 'conf.py'), 'w', conf_text)
  File "/Users/rjs/dev/virtualenvs/trailer/lib/python3.3/site-packages/sphinx/quickstart.py", line 1007, in write_file
    f.write(content)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/codecs.py", line 699, in write
    return self.writer.write(data)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/codecs.py", line 356, in write
    self.stream.write(object)
TypeError: 'str' does not support the buffer interface
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1081
- Originally reported by: Robert Smallshire
- Originally created at: 2013-01-16T07:15:11.387

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-01-16 07:36:52+00:00_

Thanks for reporting.
My Mac OS X (10.7.5) environment can `sphinx-quickstart` with no problem. 
- Python 3.3.0 (v3.3.0:bd8afb90ebf2, Sep 29 2012, 01:25:11) 
- Sphinx-1.1.3 (install from pypi)
- install by easy_install (distribute 0.6.28)

Could you tell me which version of 'setuptools (easy_install)' you are using?

**Comment by shimizukawa** [comment]
_From Robert Smallshire on 2013-01-16 08:51:41+00:00_

My environment: Mac OS X (10.8.2)
- Python 3.3.0 (v3.3.0:bd8afb90ebf2, Sep 29 2012, 01:25:11)
- Sphinx-1.1.3 (install from PyPI)
- install by pip 1.1 (distribute 0.6.27)

**Comment by shimizukawa** [comment]
_From Robert Smallshire on 2013-01-16 08:53:02+00:00_

I don't know if this is relevant, but I'm also running inside a virtualenv.

**Comment by shimizukawa** [comment]
_From Robert Smallshire on 2013-01-16 13:37:20+00:00_

Looking at the Python 3 version of the sphinx (which is produced by 2to3) I can see

```
#!python

from codecs import open
```

so now the call to open() in write_file() returns a codecs.StreamReaderWriter object rather than the TextIOWrapper that would normally be returned by a call to the open() built-in without the binary flag. The codecs.StreamReaderWriter.write() method only accepts bytes objects and will fail with the TypeError in the original report.  This is easy to replicate at the REPL:

```
#!python

Python 3.3.0 (v3.3.0:bd8afb90ebf2, Sep 29 2012, 01:25:11) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from codecs import open
>>> f = open("foo.txt", 'w', encoding='utf-8')
>>> f
<codecs.StreamReaderWriter object at 0x100523bd0>
>>> f.write("This is a string") # This fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/codecs.py", line 699, in write
    return self.writer.write(data)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/codecs.py", line 356, in write
    self.stream.write(object)
TypeError: 'str' does not support the buffer interface
>>> f.write(b'These are bytes')  # This works
>>>
```

Of course, using the regular built-in open works as expected:

```
#!python

Python 3.3.0 (v3.3.0:bd8afb90ebf2, Sep 29 2012, 01:25:11) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> f = open("bar.txt", 'w', encoding='utf-8')
>>> f
<_io.TextIOWrapper name='bar.txt' mode='w' encoding='utf-8'>
>>> f.write("This is a string")
16
>>>
```

The solution then is to remove the offending,

```
#!python

from codecs import open
```

on Python 3, which then works so long as the "Create Makefile?" is answered with "no" because there is another encoding related bug in the Makefile writing code, which I have reported separately in [Issue 1083: sphinx-quickstart tries (and fails) to specify encoding for file opened in binary mode](#1083).

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-01-17 06:07:31+00:00_

[Robert Smallshire](https://bitbucket.org/rjs) sorry I was wrong to guide you. setuptools is not relevant.

BTW, my python3.3.0 environments (Mac, Win, Ubuntu) return same result as:

```
#!python

Python 3.3.0 (v3.3.0:bd8afb90ebf2, Sep 29 2012, 01:25:11) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import codecs
>>> f = open("foo.txt", 'w', encoding='utf-8')
>>> f.write("this is a string")
16
>>> f.write(b'These are bytes')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: must be str, not bytes

```

and codecs.open's official document says:

> Open an encoded file using the given mode and return a wrapped version providing transparent encoding/decoding. The default file mode is 'r' meaning to open the file in read mode.
> Note The wrapped version’s methods will accept and return strings only. Bytes arguments will be rejected.
> -- http://docs.python.org/3.3/library/codecs.html#codecs.open

I think pass `str` object to codecs.open('f', 'w', encoding='utf-8').write() method is correct.

**Comment by shimizukawa** [comment]
_From Robert Smallshire on 2013-01-17 07:53:43+00:00_

Well, I can't argue with what the documentations says, but the evidence from my installation doesn't agree with it. In any case, in your snippet you import the codecs module but then go on to call the built-in open function. If I modify your snippet to explicitly call the **codecs.open()** function I get a failure on passing string to write() :

```
#!python

Python 3.3.0 (v3.3.0:bd8afb90ebf2, Sep 29 2012, 01:25:11) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import codecs
>>> f = codecs.open("foo.txt", 'w', encoding='utf-8')
>>> f.write("this is a string")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/codecs.py", line 699, in write
    return self.writer.write(data)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/codecs.py", line 356, in write
    self.stream.write(object)
TypeError: 'str' does not support the buffer interface
```

This appears to be at odds with the documentation.

For your snippet as posted - with the unused import of codecs and then calling the built-in open() I get the same result as you:

```
#!python

Python 3.3.0 (v3.3.0:bd8afb90ebf2, Sep 29 2012, 01:25:11) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import codecs # Not used
>>> f = open("foo.txt", 'w', encoding='utf-8')
>>> f.write("this is a string")
16
>>> f.write(b'These are bytes')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: must be str, not bytes
```

which is what I would expect.  Can you try my first snippet where **codecs.open()** is called explicitly?

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-01-17 08:06:42+00:00_

> In any case, in your snippet you import the codecs module but then go on to call the built-in open function.

Oops, I posted wrong snippet.. but I correct it and got same result.

> Can you try my first snippet where codecs.open() is called explicitly?

Sure. This is your first snippet result on my Mac OS X.

```
#!python

Python 3.3.0 (v3.3.0:bd8afb90ebf2, Sep 29 2012, 01:25:11) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from codecs import open
>>> f = open("foo.txt", 'w', encoding='utf-8')
>>> f
<codecs.StreamReaderWriter object at 0x100543c90>
>>> f.write("this is a string")
>>> f.write(b'These are bytes')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: must be str, not bytes

```

Could you try it at any other environment?

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2013-01-17 18:21:53+00:00_

I see similar this as Takayuki, but with a different exception:

```
Python 3.3.0 (default, Oct 30 2012, 10:25:02) 
[GCC 4.6.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from codecs import open
>>> f=open('x','w',encoding='utf-8')
>>> f.write('test')
>>> f.write(b'test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.3/codecs.py", line 699, in write
    return self.writer.write(data)
  File "/usr/lib64/python3.3/codecs.py", line 355, in write
    data, consumed = self.encode(object, self.errors)
TypeError: Can't convert 'bytes' object to str implicitly
```

In any case, this looks like an issue with the Python interpreter, not Sphinx.

**Comment by shimizukawa** [comment]
_From Robert Smallshire on 2013-01-17 19:07:12+00:00_

I agree. I'd appreciate it if we could keep this issue 'on hold' until I can nail down the root cause for sure though... I'll report back soon.

**Comment by shimizukawa** [comment]
_From Robert Smallshire on 2013-01-20 12:53:40+00:00_

I have reinstalled Python 3.3 for Max OS X and, perhaps crucially, run the "Update Shell Profile" command supplied with the Python installer,  to add the "bin" directory inside the framework to my shell's search path.

Whatever the cause, the problem is fixed now. I can only assume that something was misconfigured at my end. There's nothing here to concern the Sphinx team. Thanks for your time.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-01-20 13:12:09+00:00_

[Robert Smallshire](https://bitbucket.org/rjs) Thanks.
