### ISSUE TITLE
sphinx-quickstart tries (and fails) to specify encoding for file opened in binary mode

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1083]
Assuming the fix suggested in [Issue 1081: sphinx-quickstart fails on Python 3.3 on Mac OS X](http://#1081) is along the right lines and that fix is applied, this then reveals another issue.

The code in sphinx-quickstart which writes the Makefile opens the file in binary mode (in order to get Unix line-endings when writing on Windows), but then also tries to specify an encoding.  This leads to an error:

```
Creating file ./Makefile
Traceback (most recent call last):
  File "/Users/rjs/dev/virtualenvs/trailer/bin/sphinx-quickstart", line 9, in <module>
    load_entry_point('Sphinx==1.1.3', 'console_scripts', 'sphinx-quickstart')()
  File "/Users/rjs/dev/virtualenvs/trailer/lib/python3.3/site-packages/sphinx/quickstart.py", line 1071, in main
    generate(d)
  File "/Users/rjs/dev/virtualenvs/trailer/lib/python3.3/site-packages/sphinx/quickstart.py", line 1031, in generate
    write_file(path.join(d['path'], 'Makefile'), 'wb', MAKEFILE &#37; d)
  File "/Users/rjs/dev/virtualenvs/trailer/lib/python3.3/site-packages/sphinx/quickstart.py", line 1006, in write_file
    if overwrite or not path.isfile(fpath):
ValueError: binary mode doesn't take an encoding argument
```

I think the UTF-8 text needs to be explicitly encoded to binary data using encode() before being written to a binary file.  A fix that does that seems to work. I changed write_file() to:

```
#!python

def write_file(fpath, mode, content):
        if overwrite or not path.isfile(fpath):
            print('Creating file &#37;s' &#37; fpath)
            if 'b' in mode:
                encoding = None
            else:
                encoding = 'utf-8'
            f = open(fpath, mode, encoding=encoding)
            try:
                f.write(content)
            finally:
                f.close()
        else:
            print('File &#37;s already exists, skipping.' &#37; fpath)
```

and modified the statement where the Makefile is written to:

```
#!python
write_file(path.join(d['path'], 'Makefile'), 'wb', (MAKEFILE &#37; d).encode('utf-8'))
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1083
- Originally reported by: Robert Smallshire
- Originally created at: 2013-01-16T15:26:31.921

**Comment by shimizukawa** [comment]
_From Robert Smallshire on 2013-01-20 12:54:36+00:00_

I have reinstalled Python 3.3 for Max OS X and, perhaps crucially, run the "Update Shell Profile" command supplied with the Python installer,  to add the "bin" directory inside the framework to my shell's search path.

Whatever the cause, the problem is fixed now. I can only assume that something was misconfigured at my end. There's nothing here to concern the Sphinx team. Thanks for your time.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-01-20 13:12:30+00:00_

[Robert Smallshire](https://bitbucket.org/rjs) Thanks.
