### ISSUE TITLE
plugin sphinxcontrib.bibtex.style.referencing.label not found

### ISSUE THREAD

**Issue by Martin-Seysen** [sphinx-doc/sphinx#10863]
### Describe the bug

When creating documentation with Sphinx as described in section 'How to Reproduce' then a bug occurs as indicated in the screenshot below.

Detailed bug report see section 'Additional Context'

### How to Reproduce

$ git clone https://github.com/Martin-Seysen/mmgroup
$ cd mmgroup
$ pip install -r requirements.txt
$ cd docs
$ set READTHEDOCS=True
$ make html 

### Expected behavior

I want to run 

make html

without errors, as it did before I had run 

pip install -r requirements.txt

the last time. Unfortunately I do not remember which Sphinx version had been installed before.

### Your project

 https://github.com/Martin-Seysen/mmgroup

### Screenshots

![image](https://user-images.githubusercontent.com/11430409/192142143-382e22bb-cd3f-4b14-8ffe-2e0e9d45ff56.png)

### OS

Windows 11

### Python version

Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

### Sphinx version

Sphinx v3.1.2

### Sphinx extensions

sphinxcontrib.bibtex, breathe

### Additional context

Content of file sphinx-err-7ursqtnk.log:

# Sphinx version: 3.1.2
# Python version: 3.8.3 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "C:\Users\mseys\anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "C:\Users\mseys\anaconda3\lib\site-packages\sphinx\application.py", line 275, in __init__
    self._init_env(freshenv)
  File "C:\Users\mseys\anaconda3\lib\site-packages\sphinx\application.py", line 308, in _init_env
    self.env.setup(self)
  File "C:\Users\mseys\anaconda3\lib\site-packages\sphinx\environment\__init__.py", line 218, in setup
    for domain in app.registry.create_domains(self):
  File "C:\Users\mseys\anaconda3\lib\site-packages\sphinx\registry.py", line 165, in create_domains
    domain = DomainClass(env)
  File "C:\Users\mseys\anaconda3\lib\site-packages\sphinxcontrib\bibtex\domain.py", line 277, in __init__
    style = sphinxcontrib.bibtex.plugin.find_plugin(
  File "C:\Users\mseys\anaconda3\lib\site-packages\sphinxcontrib\bibtex\plugin.py", line 29, in find_plugin
    raise ImportError(f"plugin {group}.{name} not found")
ImportError: plugin sphinxcontrib.bibtex.style.referencing.label not found

**Comment by Martin-Seysen** [comment]
This problem does not appear when using Python 3.10
