### ISSUE TITLE
Import Error Django 1.4 and Virtualenv on Ubuntu

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1089]
While trying to make html on my Ubuntu server I get an import error. Error, error traceback and double check that I'm in virtualenv and can import django.

**Building fails with error:**

```
#!bash

(django)admin@ububtu:/srv/company$ sudo make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.1.3

Exception occurred:
  File "/srv/company/conf.py", line 18, in <module>
    from django.core.management import setup_environ
ImportError: No module named django.core.management
The full traceback has been saved in /tmp/sphinx-err-fupgf1.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1
```

**Error Detail:**

```
#!bash

(django)admin@ubuntu:/srv/company$ sudo cat /tmp/sphinx-err-fupgf1.log
# Sphinx version: 1.1.3
# Python version: 2.7.3
# Docutils version: 0.10 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 188, in main
    warningiserror, tags)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 102, in __init__
    confoverrides or {}, self.tags)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/config.py", line 216, in __init__
    exec code in config
  File "/srv/company/conf.py", line 18, in <module>
    from django.core.management import setup_environ
ImportError: No module named django.core.management
```

**Make sure we can import django:**

```
#!bash

(django)admin@ubuntu:/srv/company$ python
Python 2.7.3 (default, Aug  1 2012, 05:16:07) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import django
>>> django
<module 'django' from '/home/admin/.virtualenvs/django/local/lib/python2.7/site-packages/django/__init__.pyc'>
>>> 
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1089
- Originally reported by: Anonymous
- Originally created at: 2013-01-28T22:01:58.735

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-01-29 03:06:53+00:00_

I could not reproduce the reported problem.

```
#!bash

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.1 LTS"
$ virtualenv --distribute django
$ cd django
$ source bin/activate
(django)$ pip install sphinx django
(django)$ django-admin.py startproject django
(django)$ cd django
(django)$ sphinx-quickstart doc
Welcome to the Sphinx 1.1.3 quickstart utility.
-snip-
Finished: An initial directory structure has been created.
-snip-
(django)$ cd doc
(django)$ echo "from django.core.management import setup_environ" >> conf.py
(django)$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Making output directory...
Running Sphinx v1.1.3
-snip-
Build finished. The HTML pages are in _build/html.
(django)$ make clean
rm -rf _build/*
(django)$ sudo make html
sphinx-build -b html -d _build/doctrees   . _build/html
Making output directory...
Running Sphinx v1.1.3
-snip-
Build finished. The HTML pages are in _build/html.
(django)$ 

```

BTW, why did you do 'sudo make html' instead of 'make html' ?
