### ISSUE TITLE
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: NeedRef

### ISSUE THREAD

**Issue by Pierre-Gronau-ndaal** [sphinx-doc/sphinx#10978]
### Describe the bug

failed

```pytb
Exception occurred:
  File "/usr/local/lib/python3.10/site-packages/docutils/nodes.py", line 2040, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: NeedRef
The full traceback has been saved in /var/folders/vf/rxgmxgc5225gcwgk4g9c8yq40000gn/T/sphinx-err-eq2bv6y0.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [singlehtml] Error 2
```

```
# Sphinx version: 5.3.0
# Python version: 3.10.8 (CPython)
# Docutils version: 0.19 
# Jinja2 version: 3.1.2
# Last messages:
#   _Documentation/Sphinx-create.sh
#   _document/Document
#   _legal/Information
#   _finalchapter/figs
#   _finalchapter/tables
#   _finalchapter/bib
#   _finalchapter/final
#   erledigt
#   writing...
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/local/lib/python3.10/site-packages/alabaster/__init__.py
#   sphinxcontrib.blockdiag (3.0.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/blockdiag.py
#   sphinxcontrib.actdiag (3.0.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/actdiag.py
#   sphinxcontrib.nwdiag (3.0.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/nwdiag.py
#   sphinxcontrib.rackdiag (3.0.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/rackdiag.py
#   sphinxcontrib.packetdiag (3.0.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/packetdiag.py
#   sphinxcontrib.seqdiag (3.0.0) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/seqdiag.py
#   sphinx.ext.coverage (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.doctest (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.extlinks (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/extlinks.py
#   sphinx.ext.githubpages (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/githubpages.py
#   sphinx.ext.graphviz (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/graphviz.py
#   sphinx.ext.ifconfig (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.inheritance_diagram (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/inheritance_diagram.py
#   sphinx.ext.autodoc.preserve_defaults (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc.typehints (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/autodoc/typehints.py
#   sphinx.ext.autodoc (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.napoleon (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinxcontrib.plantuml (unknown version) from /usr/local/lib/python3.10/site-packages/sphinxcontrib/plantuml.py
#   sphinx_data_viewer (0.1.2) from /usr/local/lib/python3.10/site-packages/sphinx_data_viewer/__init__.py
#   sphinx_needs (1.0.3) from /usr/local/lib/python3.10/site-packages/sphinx_needs/__init__.py
#   sphinxawesome_theme.jinja_functions (3.3.7) from /usr/local/lib/python3.10/site-packages/sphinxawesome_theme/jinja_functions.py
#   sphinxawesome_theme (3.3.7) from /usr/local/lib/python3.10/site-packages/sphinxawesome_theme/__init__.py
#   sphinxmark (0.2.1) from /usr/local/lib/python3.10/site-packages/sphinxmark/__init__.py
#   myst_parser (0.18.1) from /usr/local/lib/python3.10/site-packages/myst_parser/__init__.py
#   sphinxawesome_theme.highlighting (3.3.7) from /usr/local/lib/python3.10/site-packages/sphinxawesome_theme/highlighting.py
#   sphinxawesome_theme.html_translator (3.3.7) from /usr/local/lib/python3.10/site-packages/sphinxawesome_theme/html_translator.py
#   sphinxawesome_theme.postprocess (3.3.7) from /usr/local/lib/python3.10/site-packages/sphinxawesome_theme/postprocess.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sphinx/cmd/build.py", line 281, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/local/lib/python3.10/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 307, in build_update
    self.build(['__all__'], to_build)
  File "/usr/local/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 376, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.10/site-packages/sphinx/builders/singlehtml.py", line 155, in write
    self.write_doc(self.config.root_doc, doctree)
  File "/usr/local/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 666, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/local/lib/python3.10/site-packages/docutils/writers/__init__.py", line 77, in write
    self.translate()
  File "/usr/local/lib/python3.10/site-packages/sphinx/writers/html.py", line 59, in translate
    self.document.walkabout(visitor)
  File "/usr/local/lib/python3.10/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python3.10/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python3.10/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.10/site-packages/docutils/nodes.py", line 199, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/local/lib/python3.10/site-packages/sphinx/util/docutils.py", line 585, in dispatch_departure
    super().dispatch_departure(node)
  File "/usr/local/lib/python3.10/site-packages/docutils/nodes.py", line 2018, in dispatch_departure
    return method(node)
  File "/usr/local/lib/python3.10/site-packages/docutils/nodes.py", line 2040, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: NeedRef
```

OS macOS Ventura 13.01

make html works as a charme

### Environment Information

```text
Platform:              darwin; (macOS-13.0.1-x86_64-i386-64bit)
Python version:        3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)])
Python implementation: CPython
Sphinx version:        5.3.0 Docutils version:      0.19
Jinja2 version:        3.1.2
```

### Sphinx extensions

```
    # mandantory start     'sphinxcontrib.blockdiag',     'sphinxcontrib.actdiag',     'sphinxcontrib.nwdiag',     'sphinxcontrib.rackdiag',     'sphinxcontrib.packetdiag',     'sphinxcontrib.seqdiag', #    'sphinx.ext.autodoc', #    'sphinx.ext.autosummary', #    'sphinx_autopackagesummary', #    'sphinx-autosummary-accessors', #    'sphinx.ext.autosectionlabel',     'sphinx.ext.coverage',     'sphinx.ext.doctest',     'sphinx.ext.extlinks',     'sphinx.ext.githubpages',     'sphinx.ext.graphviz',     'sphinx.ext.ifconfig', #    'sphinx.ext.imgconverter', #    'sphinx.ext.imgmath',     'sphinx.ext.inheritance_diagram', #    'sphinx.ext.intersphinx',     'sphinx.ext.mathjax',     # end # https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html     'sphinx.ext.napoleon', #     'sphinx_sitemap', # https://www.markdownguide.org/getting-started/ # https://myst-parser.readthedocs.io/en/latest/sphinx/intro.html #    'sphinx.ext.todo', #    'sphinx.ext.viewcode', #    'recommonmark', #    'sphinx_markdown_tables', #    'sphinxcontrib.swaggerdoc', #    'sphinxcontrib.excel_table', #    'rusty.includesh', #    'sphinxcontrib.programoutput', # needflow uses PlantUML and the Sphinx-extension sphinxcontrib-plantuml for generating the flows.     'sphinxcontrib.plantuml', #    'sphinxcontrib.datatemplates', #    'sphinxcontrib.autoyaml', #    'sphinxcontrib.recentpages', #    'sphinxcontrib.confluencebuilder', # obselete 'nbsphinx', # we use instead #    'myst_nb', #     'sphinx_git', #     'variations', #     'sphinxcontrib.openapi', #    'sphinxcontrib.details.directive',     'sphinx_needs', #    'sphinxcontrib.test_reports', # https://hieroglyph.readthedocs.io #    'hieroglyph', #    'sphinxcontrib.shellcheck', #     'frigate.sphinx.ext', #     'sphinx_charts.charts',     #'sphinx-exec-directive', #    'sphinx-jsonschema',     'sphinxawesome_theme',     'sphinxmark', #    'sphinxcontrib-fulltoc',  #    'sphinxcontrib.mermaid', #    'sphinxcontrib.kroki', #   'sphinxcontrib.bibtex', #    'sphinx_gallery.load_style', #    'sphinx_copybutton', # https://pypi.org/project/myst-parser/ # MyST is a rich and extensible flavor of Markdown meant for technical documentation and publishing.     'myst_parser', #    'sphinxcontrib-applehelp', #    'sphinxcontrib-manpage', #    'sphinxcontrib.dashbuilder',
```

**Comment by AA-Turner** [comment]
This is a problem with one of your extensions, `NeedRef` isn't provided in the Sphinx core.

A

**Comment by Pierre-Gronau-ndaal** [comment]
the problem was/is caused by the extension spnix-needs 1.03
see also https://github.com/useblocks/sphinx-needs/issues/796
a downgrade to 1.02 is needed
with this workaround it works again also with 6.0b2
