### ISSUE TITLE
C domain: Expected identifier in nested name

### ISSUE THREAD

**Issue by ArnaudD-FR** [sphinx-doc/sphinx#10975]
### Describe the bug

I got  troubles when parsing a C source file using kernel-doc, sphinx consider `loff_t *` as invalid. Adding the keyword `struct` or removing the pointer (`*`) remove the issue but this is not what I need.

Here is the simple example: 
```c
typedef int (*register_cb)(struct file *filp, bool write,
                       void *buffer, size_t size, loff_t *ppos);
```
I suppose it tries to interpret `*` as an operator

### How to Reproduce

`conf.py`
```python
project = 'test'
author = 'test'

extensions = [
    'linuxdoc.rstKernelDoc',
    'linuxdoc.cdomain',
]
```

`index.rst`
```rst
.. kernel-doc:: header.h
```

`header.h`
```c
#include <linux/types.h>

/**
 * typedef register_cb - virtual register callback function
 * @filp: something
 * @write: something
 * @buffer: someting
 * @size: something
 * @ppos: something
 *
 * Returns: return something
 */
typedef int (*register_cb)(struct file *filp, bool write,
				       void *buffer, size_t size, loff_t *ppos);
 
```

### Environment Information

```text Platform:              linux; (Linux-5.15.0-52-generic-x86_64-with-glibc2.29) Python version:        3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0]) Python implementation: CPython Sphinx version:        5.3.0 Docutils version:      0.16 Jinja2 version:        3.0.3 ```

### Sphinx extensions

linuxdoc

**Comment by ArnaudD-FR** [comment]
I added some debug information to Sphinx to understand the issue and I raise an exception instead of error logging to get more information:
```python
Traceback (most recent call last):
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 281, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 310, in build_update
    self.build(to_build,
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 326, in build
    updated_docnames = set(self.read())
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 433, in read
    self._read_serial(docnames)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 454, in _read_serial
    self.read_doc(docname)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 510, in read_doc
    publisher.publish()
  File "/usr/local/lib/python3.8/dist-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/io.py", line 104, in read
    self.parse()
  File "/usr/local/lib/python3.8/dist-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/parsers.py", line 78, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/local/lib/python3.8/dist-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/local/lib/python3.8/dist-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/linuxdoc/rstKernelDoc.py", line 341, in run
    self.nodes.extend(self.getNodes())
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/linuxdoc/rstKernelDoc.py", line 429, in getNodes
    self.state.nested_parse(content, 0, node, match_titles=1)
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python3.8/dist-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/local/lib/python3.8/dist-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python3.8/dist-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/local/lib/python3.8/dist-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/__init__.py", line 281, in run
    return super().run()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 3256, in run
    return super().run()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/directives/__init__.py", line 267, in run
    DocFieldTransformer(self).transform_all(contentnode)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/util/docfields.py", line 246, in transform_all
    self.transform(child)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/util/docfields.py", line 363, in transform
    new_list += fieldtype.make_field(fieldtypes, self.directive.domain, items,
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/util/docfields.py", line 224, in make_field
    bodynode += nodes.list_item('', handle_item(fieldarg, content))
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/util/docfields.py", line 207, in handle_item
    par.extend(self.make_xrefs(self.typerolename, domain, typename,
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/util/docfields.py", line 92, in make_xrefs
    return [self.make_xref(rolename, domain, target, innernode, contnode,
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/util/docfields.py", line 85, in make_xref
    ns, messages = role(rolename, target, target, lineno, inliner, {}, [])
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/__init__.py", line 262, in role_adapter
    return self.roles[name](fullname, rawtext, text, lineno,
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/util/docutils.py", line 473, in __call__
    return self.run()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 3736, in run
    ast = parser.parse_expression()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 3123, in parse_expression
    res = self._parse_expression()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2504, in _parse_expression
    return self._parse_assignment_expression()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2473, in _parse_assignment_expression
    orExpr = self._parse_logical_or_expression()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2458, in _parse_logical_or_expression
    return _parse_bin_op_expr(self, 0)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2430, in _parse_bin_op_expr
    exprs.append(parser())
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2427, in parser
    return _parse_bin_op_expr(self, opId + 1)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2430, in _parse_bin_op_expr
    exprs.append(parser())
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2427, in parser
    return _parse_bin_op_expr(self, opId + 1)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2430, in _parse_bin_op_expr
    exprs.append(parser())
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2427, in parser
    return _parse_bin_op_expr(self, opId + 1)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2430, in _parse_bin_op_expr
    exprs.append(parser())
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2427, in parser
    return _parse_bin_op_expr(self, opId + 1)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2430, in _parse_bin_op_expr
    exprs.append(parser())
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2427, in parser
    return _parse_bin_op_expr(self, opId + 1)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2430, in _parse_bin_op_expr
    exprs.append(parser())
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2427, in parser
    return _parse_bin_op_expr(self, opId + 1)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2430, in _parse_bin_op_expr
    exprs.append(parser())
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2427, in parser
    return _parse_bin_op_expr(self, opId + 1)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2430, in _parse_bin_op_expr
    exprs.append(parser())
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2427, in parser
    return _parse_bin_op_expr(self, opId + 1)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2430, in _parse_bin_op_expr
    exprs.append(parser())
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2427, in parser
    return _parse_bin_op_expr(self, opId + 1)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2448, in _parse_bin_op_expr
    expr = parser()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2427, in parser
    return _parse_bin_op_expr(self, opId + 1)
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2430, in _parse_bin_op_expr
    exprs.append(parser())
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2424, in parser
    return self._parse_cast_expression()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2406, in _parse_cast_expression
    return self._parse_unary_expression()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2382, in _parse_unary_expression
    return self._parse_postfix_expression()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2311, in _parse_postfix_expression
    prefix = self._parse_primary_expression()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2244, in _parse_primary_expression
    nn = self._parse_nested_name()
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2560, in _parse_nested_name
    raise "Expected identifier in nested name."
TypeError: exceptions must derive from BaseException
```
Here are my debug prints:
```
text: loff_t * # from CExprRole::run
self.definition = loff_t *[0: 8]  # from DefinitionParser::_parse_logical_or_expression::_parse, print("self.definition = %s[%s: %s]"%(self.definition, self.pos, self.end))
self.definition = loff_t *[0: 8]
self.definition = loff_t *[0: 8]
self.definition = loff_t *[0: 8]
self.definition = loff_t *[0: 8]
self.definition = loff_t *[0: 8]
self.definition = loff_t *[0: 8]
self.definition = loff_t *[0: 8]
self.definition = loff_t *[0: 8]
self.definition = loff_t *[0: 8]
self.definition = loff_t *[0: 8]
_parse_unary_expression; self.definition = loff_t *[0: 8] # from DefinitionParser::_parse_unary_expression
_parse_postfix_expression; self.definition = loff_t *[0: 8] # from DefinitionParser::_parse_postfix_expression
_parse_primary_expression; self.definition = loff_t *[0: 8] # from DefinitionParser::_parse_primary_expression
self.definition = loff_t *[8: 8]
_parse_unary_expression; self.definition = loff_t *[8: 8]
_parse_postfix_expression; self.definition = loff_t *[8: 8]
_parse_primary_expression; self.definition = loff_t *[8: 8]
Expected identifier in nested name loff_t *[8: 8]

Exception occurred:
  File "/home/devcontaineruser/.local/lib/python3.8/site-packages/sphinx/domains/c.py", line 2560, in _parse_nested_name
    raise "Expected identifier in nested name."
TypeError: exceptions must derive from BaseException

```

**Comment by ArnaudD-FR** [comment]
Forget this issue, side effect of debugging a macro issue with linuxdoc...
