### ISSUE TITLE
I don't understand what happened here, and the output told me to post it so I'll post it

### ISSUE THREAD

**Issue by da5nsy** [sphinx-doc/sphinx#11012]
### Describe the bug

Tried building a jupyter book, got a sphinx error.

```prompt
(jb_test) C:\Users\cege-user>cd C:\Users\cege-user\Documents\

(jb_test) C:\Users\cege-user\Documents>jupyter-book build mynewbook
Running Jupyter-Book v0.13.0
Source Folder: C:\Users\cege-user\Documents\mynewbook
Config Path: C:\Users\cege-user\Documents\mynewbook\_config.yml
Output Path: C:\Users\cege-user\Documents\mynewbook\_build\html
←[01mRunning Sphinx v4.5.0←[39;49;00m
←[01mmaking output directory... ←[39;49;00mdone
[etoc] Changing master_doc to 'intro'
checking bibtex cache... out of date
parsing bibtex file C:\Users\cege-user\Documents\mynewbook\references.bib... parsed 5 entries
←[01mmyst v0.15.2:←[39;49;00m MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist'], dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['mailto', 'http', 'https'], heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
←[01mbuilding [mo]: ←[39;49;00mtargets for 0 po files that are out of date
←[01mbuilding [html]: ←[39;49;00mtargets for 4 source files that are out of date
←[01mupdating environment: ←[39;49;00m[new config] 4 added, 0 changed, 0 removed
Executing: markdown-notebooks in: C:\Users\cege-user\Documents\mynewbook;00m

←[91mException occurred:←[39;49;00m
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
←[91mThe full traceback has been saved in C:\Users\cege-user\AppData\Local\Temp\sphinx-err-j7sx31fx.log, if you want to report the issue to the developers.←[39;49;00m
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_book\sphinx.py", line 167, in build_sphinx
    app.build(force_all, filenames)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\application.py", line 330, in build
    self.builder.build_update()
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\builders\__init__.py", line 286, in build_update
    self.build(to_build,
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\builders\__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\builders\__init__.py", line 407, in read
    self._read_serial(docnames)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\builders\__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\builders\__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\io.py", line 181, in read_doc
    pub.publish()
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\docutils\core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\io.py", line 101, in read
    self.parse()
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\myst_nb\parser.py", line 67, in parse
    ntbk = generate_notebook_outputs(
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\myst_nb\execution.py", line 137, in generate_notebook_outputs
    result = single_nb_execution(
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\nbclient\client.py", line 647, in async_execute
    async with self.async_setup_kernel(**kwargs):
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\nbclient\client.py", line 605, in async_setup_kernel
    await self.async_start_new_kernel(**kwargs)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\nbclient\client.py", line 516, in async_start_new_kernel
    await ensure_async(self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs))
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\nbclient\util.py", line 96, in ensure_async
    result = await obj
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\manager.py", line 83, in wrapper
    raise e
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\manager.py", line 75, in wrapper
    out = await method(self, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\manager.py", line 389, in _async_start_kernel
    await ensure_async(self._launch_kernel(kernel_cmd, **kw))
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\utils.py", line 38, in ensure_async
    return await obj
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\manager.py", line 307, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 204, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\launcher.py", line 170, in launch_kernel
    raise ex
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\launcher.py", line 158, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\jb_test\Scripts\jupyter-book-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_book\cli\main.py", line 323, in build
    builder_specific_actions(
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_book\cli\main.py", line 531, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError:
←[91m===============================================================================←[0m

There was an error in building your book. Look above for the cause.

←[91m===============================================================================←[0m


(jb_test) C:\Users\cege-user\Documents>
```

## C:\Users\cege-user\AppData\Local\Temp\sphinx-err-j7sx31fx.log

```log

# Sphinx version: 4.5.0
# Python version: 3.10.4 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.2
# Last messages:
#   myst v0.15.2: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist'], dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['mailto', 'http', 'https'], heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 4 source files that are out of date
#   updating environment:
#   [new config]
#   4 added, 0 changed, 0 removed
#   reading sources... [ 25%] intro
#   reading sources... [ 50%] markdown
#   reading sources... [ 75%] markdown-notebooks
#   Executing: markdown-notebooks in: C:\Users\cege-user\Documents\mynewbook
# Loaded extensions:
#   sphinx.ext.mathjax (4.5.0) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.2) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.3) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\alabaster\__init__.py
#   sphinx_togglebutton (0.3.1) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx_togglebutton\__init__.py
#   sphinx_copybutton (0.5.0) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx_copybutton\__init__.py
#   myst_nb (0.13.2) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\myst_nb\__init__.py
#   jupyter_book (0.13.0) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_book\__init__.py
#   sphinx_thebe (0.1.2) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx_thebe\__init__.py
#   sphinx_comments (0.0.3) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx_comments\__init__.py
#   sphinx_external_toc (0.2.4) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx_external_toc\__init__.py
#   sphinx.ext.intersphinx (4.5.0) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\ext\intersphinx.py
#   sphinx_design (0.1.0) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx_design\__init__.py
#   sphinx_book_theme (unknown version) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx_book_theme\__init__.py
#   sphinxcontrib.bibtex (2.4.2) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinxcontrib\bibtex\__init__.py
#   sphinx_jupyterbook_latex (unknown version) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx_jupyterbook_latex\__init__.py
#   pydata_sphinx_theme (unknown version) from C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\pydata_sphinx_theme\__init__.py
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_book\sphinx.py", line 167, in build_sphinx
    app.build(force_all, filenames)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\application.py", line 330, in build
    self.builder.build_update()
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\builders\__init__.py", line 286, in build_update
    self.build(to_build,
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\builders\__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\builders\__init__.py", line 407, in read
    self._read_serial(docnames)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\builders\__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\builders\__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\io.py", line 181, in read_doc
    pub.publish()
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\docutils\core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\sphinx\io.py", line 101, in read
    self.parse()
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\myst_nb\parser.py", line 67, in parse
    ntbk = generate_notebook_outputs(
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\myst_nb\execution.py", line 137, in generate_notebook_outputs
    result = single_nb_execution(
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\nbclient\client.py", line 647, in async_execute
    async with self.async_setup_kernel(**kwargs):
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\nbclient\client.py", line 605, in async_setup_kernel
    await self.async_start_new_kernel(**kwargs)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\nbclient\client.py", line 516, in async_start_new_kernel
    await ensure_async(self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs))
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\nbclient\util.py", line 96, in ensure_async
    result = await obj
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\manager.py", line 83, in wrapper
    raise e
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\manager.py", line 75, in wrapper
    out = await method(self, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\manager.py", line 389, in _async_start_kernel
    await ensure_async(self._launch_kernel(kernel_cmd, **kw))
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\utils.py", line 38, in ensure_async
    return await obj
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\manager.py", line 307, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 204, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\launcher.py", line 170, in launch_kernel
    raise ex
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\site-packages\jupyter_client\launcher.py", line 158, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Miniconda3\envs\jb_test\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

### Environment Information

```text
Platform:              win32; (Windows-10-10.0.19045-SP0)
Python version:        3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.17.1
Jinja2 version:        3.1.2
```

**Comment by electric-coder** [comment]
@AA-Turner 

I think this issue can be closed on the Sphinx side. The debug steps in the linked jupyter-book suggest this is a caching issue solved by running `make clean` after changes to toctree structure.
