### ISSUE TITLE
5.3.0: `sphinx-build` tries to install modules

### ISSUE THREAD

**Issue by kloczek** [sphinx-doc/sphinx#11048]
### Describe the bug

I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
First step of the template build procedure is `python3 -sBm build -w --no-isolation`.
Than if project provides sphinx based documentation I'm building documentation as man page using (if documentation is in docs/ it is used `sphinx-build -n -T -b man docs build/sphinx/man` command).

Recently I've started buiulding all my packages in build env which is cut off from public network and I found that above `sphinx-build` command tries to install some .whl archives downloaded from pypi which are specified in pyproject.toml. `requires`.

As example can be used https://github.com/jaraco/pip-run/
Part of the build log:
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
running egg_info
creating keyring.egg-info
writing keyring.egg-info/PKG-INFO
writing dependency_links to keyring.egg-info/dependency_links.txt

[..]

removing build/bdist.linux-x86_64/wheel
Successfully built keyring-23.13.1-py3-none-any.whl
+ PBR_VERSION=23.13.1
+ PDM_PEP517_SCM_VERSION=23.13.1
+ SETUPTOOLS_SCM_PRETEND_VERSION=23.13.1
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.3.0
making output directory... done
```
At this stage build is frozen on trying to install modues. `ps auxf` output shows
```
tkloczko  892625  2.0  0.0 282468 57260 pts/7    S+   09:08   0:00                          \_ /usr/bin/python3 /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
tkloczko  892640  2.2  0.0 268516 45516 pts/7    S+   09:08   0:00                              \_ /tmp/build-env-tlph6h46/bin/python -Im pip install --use-pep517 --no-warn-script-location -r /tmp/build-reqs-7nb6zin0.txt
```
```console
[tkloczko@devel-g2v SPECS]$ cat /tmp/build-reqs-7nb6zin0.txt
setuptools_scm[toml]>=3.4.1
```
After some time build fails with:
```console
ERROR: Could not find a version that satisfies the requirement setuptools_scm>=3.4.1 (from versions: none)
ERROR: No matching distribution found for setuptools_scm>=3.4.1

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/lib/python3.8/site-packages/jaraco/packaging/sphinx.py", line 30, in load_config_from_setup
    meta = load_metadata(root)
  File "/usr/lib/python3.8/site-packages/build/util.py", line 53, in project_wheel_metadata
    env.install(builder.build_system_requires)
  File "/usr/lib/python3.8/site-packages/build/env.py", line 211, in install
    _subprocess(cmd)
  File "/usr/lib/python3.8/site-packages/build/env.py", line 76, in _subprocess
    raise e
  File "/usr/lib/python3.8/site-packages/build/env.py", line 73, in _subprocess
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib64/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/build-env-tlph6h46/bin/python', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', '/tmp/build-reqs-7nb6zin0.txt']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 262, in __init__
    self._init_builder()
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 335, in _init_builder
    self.events.emit('builder-inited')
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 105, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function load_config_from_setup at 0x7f3cd81deb80> for event 'builder-inited' threw an exception (exception: Command '['/tmp/build-env-tlph6h46/bin/python', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', '/tmp/build-reqs-7nb6zin0.txt']' returned non-zero exit status 1.)

Extension error (jaraco.packaging.sphinx):
Handler <function load_config_from_setup at 0x7f3cd81deb80> for event 'builder-inited' threw an exception (exception: Command '['/tmp/build-env-tlph6h46/bin/python', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', '/tmp/build-reqs-7nb6zin0.txt']' returned non-zero exit status 1.)
```
In build env `setuptools_scm` of course is installed.

On first look it looks like `sphinx-build` is tring to build isolated env like `build` is doing but called without `--no-isolation`.

### How to Reproduce

As example can be used https://github.com/jaraco/pip-run/
- clone repo
- apply below patch
```patch
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -1,3 +1,7 @@
+import sys
+import os
+sys.path.insert(0, os.path.abspath(".."))
+
 extensions = [
     'sphinx.ext.autodoc',
     'jaraco.packaging.sphinx',
```
which allows build documentation without have `pip-run` installed
- in source tree needs to be executed `sphinx-build -n -T -b man docs build/sphinx/man`

### Environment Information
`sphinx-build --bug-report`
```text
Platform:              linux; (Linux-5.19.12-200.fc36.x86_64-x86_64-with-glibc2.34)
Python version:        3.8.16 (default, Dec  7 2022, 14:47:56)
[GCC 12.2.1 20221121 (Red Hat 12.2.1-4)])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.19
Jinja2 version:        3.1.2
```

### Sphinx extensions
sphinx.ext.autodoc
jaraco.packaging.sphinx

**Comment by kloczek** [comment]
I'm not 100% sure but looks like `jaraco.packaging.sphinx` in this case is tring to build documentation in its own isolated env.
I've created https://github.com/jaraco/jaraco.packaging/issues/10
