### ISSUE TITLE
`node.asdom()` broken if `toc_object_entries = False`

### ISSUE THREAD

**Issue by emilyalbini** [sphinx-doc/sphinx#11123]
### Describe the bug

When directives are used and the `toc_object_entries` configuration is set to `False`, calling the `asdom()` method on any node containing that directive results in this exception:

```
Traceback (most recent call last):
  File "[...]/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "repro_extension.py", line 2, in doctree_read
    doctree.asdom()
  File "[...]/docutils/nodes.py", line 1356, in asdom
    domroot.appendChild(self._dom_node(domroot))
  File "[...]/docutils/nodes.py", line 557, in _dom_node
    element.appendChild(child._dom_node(domroot))
  File "[...]/docutils/nodes.py", line 557, in _dom_node
    element.appendChild(child._dom_node(domroot))
  File "[...]/docutils/nodes.py", line 555, in _dom_node
    element.setAttribute(attribute, '%s' % value)
TypeError: not enough arguments for format string

```

### How to Reproduce

**conf.py**
```python
import sys
sys.path.append(".")

project = 'demo'
copyright = 'demo'
author = 'demo'

extensions = ["repro_extension"]

toc_object_entries = False
```

**repro_extension.py**
```python
def doctree_read(app, doctree):
    doctree.asdom()

def setup(app):
    app.connect("doctree-read", doctree_read)
```

**index.rst**
```rst
.. rst:directive:: foo

   Bar
```

### Environment Information

```text
Platform:              linux; (Linux-5.15.0-57-generic-x86_64-with-glibc2.35)
Python version:        3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0])
Python implementation: CPython
Sphinx version:        6.1.3
Docutils version:      0.19
Jinja2 version:        3.1.2
Pygments version:      2.14.0
```

### Sphinx extensions

Only the custom extension needed to call the `.asdom()` method.

### Additional context

Seems to be caused by this piece of code setting `_toc_parts` to `()`:

https://github.com/sphinx-doc/sphinx/blob/e17f39e7b535f4849754d46f2cd2e411df8aa535/sphinx/directives/__init__.py#L245-L250

...and docutils trying to convert that to a string:

https://github.com/docutils/docutils/blob/173189b4c1c095a43c9388f4edd9bf1ff5d5b49d/docutils/docutils/nodes.py#L548

**Comment by picnixz** [comment]
I also encountered this issue when debugging so I'd suggest creating an extension patching `docutils.nodes.Element._dom_node` as follows:

```python
def __dom_node(self, domroot):
    from docutils.nodes import serial_escape

    element = domroot.createElement(self.tagname)
    for attribute, value in self.attlist():
        if isinstance(value, (list, tuple)):  # allow list or tuple
            value = ' '.join([serial_escape('%s' % (v,)) for v in value])
        element.setAttribute(attribute, '%s' % value)
    for child in self.children:
        element.appendChild(child._dom_node(domroot))
    return element

def patch_docutils_node_to_dom_node():
    from docutils.nodes import Element

    Element._dom_node = __dom_node

def setup(app):
    patch_docutils_node_to_dom_node()
```

The issue is that Sphinx uses a tuple as an attribute value in a node. If it were a list, there would have been no issue.
