### ISSUE TITLE
Overzealous RemovedInSphinx80Warning for sphinx.util.progress_message?

### ISSUE THREAD

**Issue by jnikula** [sphinx-doc/sphinx#11138]
### Describe the bug

The **pytest test suite** for my Sphinx extension started emitting:

```
  /usr/lib/python3.9/importlib/__init__.py:127: RemovedInSphinx80Warning: The alias 'sphinx.util.progress_message' is deprecated, use 'sphinx.util.display.progress_message' instead. Check CHANGES for Sphinx API modifications.
    return _bootstrap._gcd_import(name[level:], package, level)
```

Normal usage of my extension in `sphinx-build` does **not** hit the warning.

The problem is, I don't use `progress_message` in the extension, at all.

I do still use the deprecated `sphinx_testing` package, but it doesn't use `progress_message` either. I don't use any other extensions.

I don't get where the message comes from and why.

### How to Reproduce

```
$ sudo apt install python3-clang # on apt systems
$ git clone https://github.com/jnikula/hawkmoth.git
$ cd hawkmoth
$ . venv
$ pytest test -vv -k test_directive_text[simple-macro]
```
or for the full test suite:
```
$ make test
```

### Environment Information

```text
Platform:              linux; (Linux-6.0.0-0.deb11.6-amd64-x86_64-with-glibc2.31)
Python version:        3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110])
Python implementation: CPython
Sphinx version:        6.1.3
Docutils version:      0.19
Jinja2 version:        3.1.2
Pygments version:      2.14.0
```

### Sphinx extensions

```python
https://github.com/jnikula/hawkmoth
```

**Comment by mgeier** [comment]
> I don't get where the message comes from and why.

This warning is ignored by default. The idea is that developers should actively enable the warning, while normal users are not bothered by it.

Many developers forget to enable those warnings in their tests, but thankfully PyTest automatically enables them for us. This is why you see them with PyTest and not with `sphinx-build`.

If you want to manually enable the warnings, you can set the environment variable `PYTHONWARNINGS=error`.

I have also noticed those warnings popping up and created issues #11098 and #11127.
This should also give you an idea where they come from.

The error message doesn't tell us where they come from, so you'll have to dig a bit deeper and look at the error log file (whose file name should be mentioned at the end of the Sphinx run, it's probably something like `/tmp/sphinx-err-*.log`).

**Comment by jnikula** [comment]
@mgeier thanks!

Turns out this is just a dupe of #11127. I really did not expect Sphinx to deprecate something, while at the same time depending on packages using the deprecated interfaces.

```
# Platform:         linux; (Linux-6.0.0-0.deb11.6-amd64-x86_64-with-glibc2.31)
# Sphinx version:   6.1.3
# Python version:   3.9.2 (CPython)
# Docutils version: 0.19
# Jinja2 version:   3.1.2
# Pygments version: 2.14.0

# Last messages:


# Loaded extensions:


# Traceback:
Traceback (most recent call last):
  File "/path/to/venv/lib/python3.9/site-packages/sphinx/cmd/build.py", line 279, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/path/to/venv/lib/python3.9/site-packages/sphinx/application.py", line 219, in __init__
    self.setup_extension(extension)
  File "/path/to/venv/lib/python3.9/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/path/to/venv/lib/python3.9/site-packages/sphinx/registry.py", line 443, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/path/to/venv/lib/python3.9/site-packages/sphinxcontrib/htmlhelp/__init__.py", line 26, in <module>
    from sphinx.util import progress_message
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/path/to/venv/lib/python3.9/site-packages/sphinx/deprecation.py", line 46, in __getattr__
    warnings.warn(f"The alias '{self._modname}.{name}' is deprecated, "
sphinx.deprecation.RemovedInSphinx80Warning: The alias 'sphinx.util.progress_message' is deprecated, use 'sphinx.util.display.progress_message' instead. Check CHANGES for Sphinx API modifications.
```
