### ISSUE TITLE
ValueError: Empty module name

### ISSUE THREAD

**Issue by yukio916** [sphinx-doc/sphinx#11136]
### Describe the bug

```
# Sphinx version: 5.3.0
# Python version: 3.9.8 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.2
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "D:\py39\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "D:\py39\lib\site-packages\sphinx\application.py", line 223, in __init__
    self.setup_extension(extension)
  File "D:\py39\lib\site-packages\sphinx\application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "D:\py39\lib\site-packages\sphinx\registry.py", line 459, in load_extension
    mod = import_module(extname)
  File "D:\py39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1027, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _sanity_check
ValueError: Empty module name
```

### How to Reproduce

.\make html

### Environment Information

```text
Please paste all output below into the bug report template



Platform:              win32; (Windows-10-10.0.17763)
Python version:        3.9.8 (tags/v3.9.8:bb3fdcf, Nov  5 2021, 20:48:33) [MSC v.1929 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        6.1.3
Docutils version:      0.19
Jinja2 version:        3.1.2
Pygments version:      2.13.0
```

**Comment by tk0miya** [comment]
It seems Sphinx got an error on loading extensions specified in your conf.py. Could you show me your conf.py, please? I guess your `extensions` settings would be not good.

**Comment by rjfbamdatex** [comment]
I also encountered this when I was testing different themes. I found out that during me switching to between themes, I edited my conf.py and emptied my `extensions` to something like this

```python
extensions = ['']
``` 

instead of this

```python
extensions = []
``` 

Maybe that's what happened.
