### ISSUE TITLE
Type error with default celery_task_prefix

### ISSUE THREAD

**Issue by eghuro** [sphinx-doc/sphinx#11186]
### Describe the bug

`make html` crashed after adding `celery.contrib.sphinx` extension with default settings. Changing to `celery_task_prefix = []` resolved the problem.

### How to Reproduce

- Add celery.contrib.sphinx extension (you might need celery installed)
- Have at least one celery task to document
- run make html
Sphinx crashes

### Environment Information

```text
Platform:              darwin; (macOS-12.6.1-arm64-arm-64bit)
Python version:        3.9.10 (main, Jan 15 2022, 11:40:36) 
[Clang 13.0.0 (clang-1300.0.29.3)])
Python implementation: CPython
Sphinx version:        6.1.3
Docutils version:      0.19
Jinja2 version:        3.1.2
Pygments version:      2.14.0
```

### Sphinx extensions

```python
extensions = [
    "celery.contrib.sphinx",
    "sphinx_click",
    "sphinx.ext.autodoc",
]
```

### Additional context

```
# Platform:         darwin; (macOS-12.6.1-arm64-arm-64bit)
# Sphinx version:   6.1.3
# Python version:   3.9.10 (CPython)
# Docutils version: 0.19
# Jinja2 version:   3.1.2
# Pygments version: 2.14.0

# Last messages:
#   [new config]
#   8 added, 0 changed, 0 removed
#   reading sources... [ 12%] cli
#   reading sources... [ 25%] history
#   reading sources... [ 37%] index
#   reading sources... [ 50%] modules
#   reading sources... [ 62%] readme
#   reading sources... [ 75%] tsa
#   reading sources... [ 87%] tsa.public
#   reading sources... [100%] tsa.tasks

# Loaded extensions:
#   sphinx.ext.mathjax (6.1.3)
#   sphinxcontrib.applehelp (1.0.4)
#   sphinxcontrib.devhelp (1.0.2)
#   sphinxcontrib.htmlhelp (2.0.1)
#   sphinxcontrib.serializinghtml (1.1.5)
#   sphinxcontrib.qthelp (1.0.3)
#   alabaster (0.7.13)
#   sphinx.ext.autodoc.preserve_defaults (6.1.3)
#   sphinx.ext.autodoc.type_comment (6.1.3)
#   sphinx.ext.autodoc.typehints (6.1.3)
#   sphinx.ext.autodoc (6.1.3)
#   celery.contrib.sphinx (unknown version)
#   sphinx_click (unknown version)

# Traceback:
Traceback (most recent call last):
  File "XXX/lib/python3.9/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, args.filenames)
  File "XXX/lib/python3.9/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "XXX/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 311, in build_update
    self.build(to_build,
  File "XXX/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 327, in build
    updated_docnames = set(self.read())
  File "XXX/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 434, in read
    self._read_serial(docnames)
  File "XXX/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 455, in _read_serial
    self.read_doc(docname)
  File "XXX/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 511, in read_doc
    publisher.publish()
  File "XXX/lib/python3.9/site-packages/docutils/core.py", line 224, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "XXX/lib/python3.9/site-packages/sphinx/io.py", line 105, in read
    self.parse()
  File "XXX/lib/python3.9/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "XXX/lib/python3.9/site-packages/sphinx/parsers.py", line 80, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "XXX/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "XXX/lib/python3.9/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "XXX/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "XXX/lib/python3.9/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "XXX/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "XXX/lib/python3.9/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2355, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
  File "XXX/lib/python3.9/site-packages/sphinx/ext/autodoc/directive.py", line 147, in run
    result = parse_generated_content(self.state, params.result, documenter)
  File "XXX/lib/python3.9/site-packages/sphinx/ext/autodoc/directive.py", line 90, in parse_generated_content
    nested_parse_with_titles(state, content, node)
  File "XXX/lib/python3.9/site-packages/sphinx/util/nodes.py", line 327, in nested_parse_with_titles
    return state.nested_parse(content, 0, node, match_titles=1)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "XXX/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "XXX/lib/python3.9/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2357, in explicit_markup
    self.explicit_list(blank_finish)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2382, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 316, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "XXX/lib/python3.9/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "XXX/lib/python3.9/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2660, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
  File "XXX/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
  File "XXX/lib/python3.9/site-packages/sphinx/domains/__init__.py", line 286, in run
    return super().run()
  File "XXX/lib/python3.9/site-packages/sphinx/directives/__init__.py", line 236, in run
    name = self.handle_signature(sig, signode)
  File "XXX/lib/python3.9/site-packages/sphinx/domains/python.py", line 540, in handle_signature
    raise TypeError(
TypeError: Python directive method get_signature_prefix() must return a list of nodes. Return value was '(task)'.
```

**Comment by zbhuiyan** [comment]
Also have this issue and not sure how to resolve.

**Comment by gmacon** [comment]
This was an intentional breaking change in Sphinx 6.0. Celery has fixed the issue on their side, see https://github.com/celery/celery/pull/7978, but that change has not yet made it into a release.

**Comment by AA-Turner** [comment]
Thanks @gmacon!

A
