### ISSUE TITLE
C and C++ domain: Function Typedef (not Function Pointer typedef) Parses Incorrectly and Triggers Error

### ISSUE THREAD

**Issue by ThePhD** [sphinx-doc/sphinx#11236]
### Describe the bug

Hi,

I have a project that makes use of function `typedef`s (**not** function pointer `typedef`s) and that look like this:

```
/* non-pointer function typedef */
typedef void*(TestTypedefFunc)(long long, double, int*, void*);
```

Sphinx parses this incorrectly and claims it's an invalid type definition. The first time I encountered this error was in a breathe project, where, Sphinx says:

```
Exception occurred while building, starting debugger:
Traceback (most recent call last):
  File "breathe/.venv/lib/python3.11/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, args.filenames)

  File "breathe/.venv/lib/python3.11/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "breathe/.venv/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 311, in build_update
    self.build(to_build,
  File "breathe/.venv/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 326, in build
    with logging.pending_warnings():
  File "/usr/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "breathe/.venv/lib/python3.11/site-packages/sphinx/util/logging.py", line 222, in pending_warnings
    memhandler.flushTo(logger)
  File "breathe/.venv/lib/python3.11/site-packages/sphinx/util/logging.py", line 187, in flushTo
    logger.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.11/logging/__init__.py", line 974, in handle
    rv = self.filter(record)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 830, in filter
    result = f.filter(record)
             ^^^^^^^^^^^^^^^^
  File "breathe/.venv/lib/python3.11/site-packages/sphinx/util/logging.py", line 427, in filter
    raise exc
sphinx.errors.SphinxWarning: breathe/documentation/source/specific.rst:22:Error in type declaration.
If typedef-like declaration:
  Type must be either just a name or a typedef-like declaration.
  If just a name:
    Error in declarator or parameters-and-qualifiers
    Invalid C++ declaration: Expected identifier in nested name, got keyword: void [error at 4]
      void *() TestTypedefFunc (long long, double, int *, void *)
      ----^
  If typedef-like declaration:
    Error in declarator
    If declarator-id with parameters-and-qualifiers:
      Invalid C++ declaration: Expected identifier in nested name. [error at 6]
        void *() TestTypedefFunc (long long, double, int *, void *)
        ------^
    If parenthesis in noptr-declarator:
      Error in declarator or parameters-and-qualifiers
      If pointer to member declarator:
        Invalid C++ declaration: Expected identifier in nested name. [error at 7]
          void *() TestTypedefFunc (long long, double, int *, void *)
          -------^
      If declarator-id:
        Invalid C++ declaration: Expected identifier in nested name. [error at 7]
          void *() TestTypedefFunc (long long, double, int *, void *)
          -------^
If type alias or template alias:
  Invalid C++ declaration: Expected identifier in nested name, got keyword: void [error at 4]
    void *() TestTypedefFunc (long long, double, int *, void *)
    ----^
```

Dropping down a level and getting rid of Breathe, we then try the same test code directly for `index.rst`, we see the error for trying to have a non-pointer function `typedef`. Errors in all cases, no matter arguments or name. It works fine if you remove the parentheses in the name, as displayed below in the reproduction. Are we meant to rip the parenthesis out, should the parser tolerate such a thing? If so, then the below might help. If not, then I need to go back to Breathe and ask them to remove the parentheses from the name.

### How to Reproduce

(Windows Command Line has `type` to display text from a file, rather than `echo` and redirection.)

# Self-contained `index.rst`

```sh
$> type index.rst
```

Output:
```
Bug Report Test: C and C++ Domain
=================================

.. cpp:type:: TestTypedefFuncPointer = void*(*)(long long, double, int*, void*)

        function pointer typedef


.. cpp:type:: TestTypedefFunc = void*()(long long, double, int*, void*)

        non-pointer function typedef


.. cpp:type:: TestTypedefFunc2 = void*(long long, double, int*, void*)

        non-pointer function typedef
```

# Self-contained `conf.py`

```sh
$> type conf.py
```

Output:
```py
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'Bug Report Test: C and C++ Domain'
copyright = '2023, ThePhD'
author = 'ThePhD'
release = '0.0.0'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration
extensions = []

templates_path = ['_templates']
exclude_patterns = []



# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'alabaster'
html_static_path = ['_static']
```

# `sphinx-build` Invocation

```sh
$> sphinx-build -M html . _build
```

Output:
```
Running Sphinx v5.3.0
WARNING: html_static_path entry '_static' does not exist
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [config changed ('project')] 1 added, 0 changed, 0 removed
reading sources... [100%] index
sphinx-error\index.rst:9: WARNING: Invalid C++ declaration: Expected end of definition. [error at 25]
  TestTypedefFunc = void*()(long long, double, int*, void*)
  -------------------------^
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 2 warnings.

The HTML pages are in _build\html.
```

### Environment Information

```text
Platform:              win32; (Windows-10-10.0.19045-SP0)
Python version:        3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.17.1
Jinja2 version:        3.0.3
```

### Additional context

Original (mistaken?? maybe??) Breathe Issue: https://github.com/breathe-doc/breathe/issues/894
Real-world repository with documentation failure: https://github.com/soasis/cuneicode

**Comment by jakobandersen** [comment]
Thanks for the report, though in the translation from the Breathe issue I think some parts got mixed up.
The one it complains about here is ``TestTypedefFunc = void*()(long long, double, int*, void*)`` which is not valid C++.  With GCC 9.4 I get
```
test.cpp:7:25: error: ‘type name’ declared as function returning a function
    7 | using TestTypedefFunc = void*()(long long, double, int*, void*);
      |                         ^~~~
```

The original issue is with Doxygen/Breathe, so I'll comment over there. Please reopen if I misunderstood something.

**Comment by ThePhD** [comment]
I think you understand it correctly and it might be something I have to ask Doxygen to output differently (probably an incredibly high bar considering how many people use it / work with it) or if I should figure out a mitigation strategy for Sphinx/Breathe.

Nevertheless, it'd probably be best to discuss it over in Breathe. Thanks for the comments over there, too; I appreciate you taking the time.
