### ISSUE TITLE
AttributeError module types has no attribute UnionType using python 3.10 and sphinx 5.3 

### ISSUE THREAD

**Issue by joeldodson** [sphinx-doc/sphinx#11377]
### Describe the bug

Hi,
My build is failing on rtd.org  with the exception:
AttributeError: module 'types' has no attribute 'UnionType'

I found a reverence to a similar issue in a closed ticket from July 2021 which says it was fixed in sphinx 4.3:
https://github.com/sphinx-doc/sphinx/issues/9512
 

The full traceback has been saved in /tmp/sphinx-err-kiu2ys4z.log, if you want to report the issue 

I've tried going back to python 3.9 but I appear to be using modules/extensions requiring python 3.10.  The requirements.txt file in my docs directory initially had no versions specified, 3.9 still failed.  I tried adding the versions I was using locally to docs/requirements.txt to force RTD to use the same versions, no luck.

I'm using a cookiecutter (cookiecutter https://github.com/py-pkgs/py-pkgs-cookiecutter.git) which created the docs directory, including the makefile, config, and requirements.txt and the root level .readthedocs.yml.

 

Locally I setup my virtual env using python -m venv ...  then manage it using poetry.

I can build the docs locally in both a 3.10.11 and a 3.11.2 virtual env.

thanks,
Joel  

### How to Reproduce

the build is initiated on readthedocs.org automatically when I push to https://github.com/joeldodson/domible 

### Environment Information

```text
here's the output from my browser:

We encountered a problem with a command while building your project. To resolve this error, double check your project configuration and installed dependencies are correct and have not changed recently.
git clone --no-single-branch --depth 50 https://github.com/joeldodson/domible.git .
git checkout --force origin/main
git clean -d -f -f
python3.10 -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH
python -m pip install --upgrade --no-cache-dir pip setuptools<58.3.0
python -m pip install --upgrade --no-cache-dir pillow mock==1.0.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.9.1 recommonmark==0.5.0 sphinx sphinx-rtd-theme readthedocs-sphinx-ext<2.3
python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
python -m pip install --upgrade --upgrade-strategy eager --no-cache-dir .
cat docs/conf.py
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
Running Sphinx v5.3.0

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/domible/envs/latest/lib/python3.10/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/domible/envs/latest/lib/python3.10/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/domible/envs/latest/lib/python3.10/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/domible/envs/latest/lib/python3.10/site-packages/sphinx/registry.py", line 472, in load_extension
    metadata = setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/domible/envs/latest/lib/python3.10/site-packages/myst_nb/__init__.py", line 8, in setup
    from .sphinx_ext import sphinx_setup
  File "/home/docs/checkouts/readthedocs.org/user_builds/domible/envs/latest/lib/python3.10/site-packages/myst_nb/sphinx_ext.py", line 16, in <module>
    from myst_nb.core.config import NbParserConfig
  File "/home/docs/checkouts/readthedocs.org/user_builds/domible/envs/latest/lib/python3.10/site-packages/myst_nb/core/config.py", line 18, in <module>
    def custom_formats_converter(value: dict) -> Dict[str, Tuple[str, dict, bool]]:
  File "/home/docs/.pyenv/versions/3.10.0b4/lib/python3.10/typing.py", line 298, in inner
    return cached(*args, **kwds)
  File "/home/docs/.pyenv/versions/3.10.0b4/lib/python3.10/typing.py", line 1171, in __getitem__
    return self.copy_with(params)
  File "/home/docs/.pyenv/versions/3.10.0b4/lib/python3.10/typing.py", line 1082, in copy_with
    return _GenericAlias(self.__origin__, params,
  File "/home/docs/.pyenv/versions/3.10.0b4/lib/python3.10/typing.py", line 972, in __init__
    self.__parameters__ = _collect_type_vars(params, typevar_types=_typevar_types)
  File "/home/docs/checkouts/readthedocs.org/user_builds/domible/envs/latest/lib/python3.10/site-packages/typing_extensions.py", line 142, in _collect_type_vars
    if _should_collect_from_parameters(t):
  File "/home/docs/checkouts/readthedocs.org/user_builds/domible/envs/latest/lib/python3.10/site-packages/typing_extensions.py", line 116, in _should_collect_from_parameters
    t, (typing._GenericAlias, _types.GenericAlias, _types.UnionType)
AttributeError: module 'types' has no attribute 'UnionType'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/domible/envs/latest/lib/python3.10/site-packages/typing_extensions.py", line 116, in _should_collect_from_parameters
    t, (typing._GenericAlias, _types.GenericAlias, _types.UnionType)
AttributeError: module 'types' has no attribute 'UnionType'
The full traceback has been saved in /tmp/sphinx-err-kiu2ys4z.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Command time: 0s Return: 2 



the problem I'm seeing is on readthedocs.org auto build.  It works fine locally using sphinx 5.3 and python 3.10.11 or 3.11.2.
I added the reference to where the full stack is stored at readthedocs.org, hopefully that's sufficient.
 


the problem I'm seeing is on readthedocs.org auto build.  It works fine locally using sphinx 5.3 and python 3.10.11 or 3.11.2.
I added the reference to where the full stack is stored at readthedocs.org, hopefully that's sufficient.
```

**Comment by picnixz** [comment]
This repository is for Sphinx core developement and this is issue is likely an issue on RTD side. 

Nevertheless, you can force RTD to use the latest Python version by specifying `build.os` and `build.tool` inside the `.readthedocs.yml` configuration file:

```yml
build:
  os: "ubuntu-22.04"  
  tools:
    python: "3.10"  # or python: "3" for the latest version
```

**Comment by picnixz** [comment]
Python 3.10 on RTD seems to be older than your local installation. This may also be the issue.

(I removed my previous comment because I misunderstood).

**Comment by AA-Turner** [comment]
We only support latest Sphinx -- please forward your problem to Read the Docs support if the issue only manifests there.

A

**Comment by joeldodson** [comment]
thanks all.

yeah, very fair point.  I guess I wasn't appreciating the difference between sphinx and readthedocs.  I thought sphinx came from readthedocs.  Apologies for not doing due diligence prior to posting.

FWIW, I was thinking of moving to MkDocs.  I tried the basic intro and found some frustrating accessibility issues on the simplest areas.  As a totally blind developer, I appreciate how accessible sphinx generated docs are.

**Comment by AA-Turner** [comment]
> I tried the basic intro and found some frustrating accessibility issues on the simplest areas. As a totally blind developer, I appreciate how accessible sphinx generated docs are.

Thank you! Please let us know if there are further improvements we can make, I would really appreciate any input!

Thanks,
Adam
