### ISSUE TITLE
Cannot load json as figure in sphinx

### ISSUE THREAD

**Issue by GeorgeMargineanu** [sphinx-doc/sphinx#11398]
### Describe the bug

Hello,

We installed sphinx with rtd-theme and sphinx_charts and added it in the conf sphinx_charts.charts as extensions.
We created a json file that we attached below, added it in index.rst as per the documentation but the plots do not render in Chrome or Edge.
<img width="924" alt="Screenshot 2023-05-05 004355" src="https://user-images.githubusercontent.com/63586499/236336647-314db4de-f46a-4085-a46c-2f62f5896b30.png"> --- conf.py 

<img width="575" alt="Screenshot 2023-05-05 004514" src="https://user-images.githubusercontent.com/63586499/236336782-86b8e48f-ad9f-48a2-83f1-1f6aabc8d1ee.png"> --- index.rst

Also we`ve created under _static folder, an custom.js
<img width="472" alt="Screenshot 2023-05-05 004626" src="https://user-images.githubusercontent.com/63586499/236336982-9a9e0037-a2c8-42aa-84e4-fb3f334431fd.png"> ---custom.js

---- this is the test.json------ 
{"data": [{"x": [1, 2, 3, 4, 5], "y": [1, 2, 4, 8, 81]}], "layout": {"margin": {"t": 15, "b": 30, "r": 15, "l": 35}}}
----------------------------------------------------------

Doing this ( html_js_files in index and custom.js we managed to have our html file compiled) but that chart existing in the test.json wasn`t visible.

We`ve tried again with the make clean and make html again and we got the following error:   ERROR: Content block expected for the "chart" directive; none found. and also     FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\x\\x\\x\\source\\chartstest.json --- As I understand it there is a missing \ between charts and test.json 

Can you please give us a hint of what we are doing wrong ? I`ve tried multiple things that I found over the internet and none really worked as expected. 

Thank you in advance ! 

 

### How to Reproduce

quick-start
make html
edited the files as descried above..
make clean 
make html 
and here the magic happens... nothing works.

### Environment Information

```text
# Sphinx version: 5.0.2
# Python version: 3.9.13 (CPython)
# Docutils version: 0.18.1 release
# Jinja2 version: 2.11.3
# Last messages:
#   Running Sphinx v5.0.2
#   Plotly requires an SVG renderer for LaTeX elements, not an HTML renderer. Adding https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js.
#   making output directory...
#   done
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 1 source files that are out of date
#   updating environment:
#   [new config]
#   1 added, 0 changed, 0 removed
#   reading sources... [100%] index
# Loaded extensions:
#   sphinx.ext.mathjax (5.0.2) from C:\Users\rbsct\anaconda3\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from C:\Users\rbsct\anaconda3\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.2) from C:\Users\rbsct\anaconda3\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from C:\Users\rbsct\anaconda3\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from C:\Users\rbsct\anaconda3\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.3) from C:\Users\rbsct\anaconda3\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from C:\Users\rbsct\anaconda3\lib\site-packages\alabaster\__init__.py
#   sphinx_charts.charts (unknown version) from C:\Users\rbsct\anaconda3\lib\site-packages\sphinx_charts\charts.py
#   sphinx_rtd_theme (unknown version) from C:\Users\rbsct\anaconda3\lib\site-packages\sphinx_rtd_theme\__init__.py
Traceback (most recent call last):
  File "C:\Users\rbsct\anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "C:\Users\rbsct\anaconda3\lib\site-packages\sphinx\application.py", line 329, in build
    self.builder.build_update()
  File "C:\Users\rbsct\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 288, in build_update
    self.build(to_build,
  File "C:\Users\rbsct\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 302, in build
    updated_docnames = set(self.read())
  File "C:\Users\rbsct\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 409, in read
    self._read_serial(docnames)
  File "C:\Users\rbsct\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 430, in _read_serial
    self.read_doc(docname)
  File "C:\Users\rbsct\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 483, in read_doc
    publisher.publish()
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "C:\Users\rbsct\anaconda3\lib\site-packages\sphinx\io.py", line 103, in read
    self.parse()
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "C:\Users\rbsct\anaconda3\lib\site-packages\sphinx\parsers.py", line 78, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\statemachine.py", line 240, in run
    context, next_state, result = self.check_line(
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\statemachine.py", line 452, in check_line
    return method(match, context, next_state)
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 2779, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\statemachine.py", line 240, in run
    context, next_state, result = self.check_line(
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\statemachine.py", line 452, in check_line
    return method(match, context, next_state)
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 2352, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 2364, in explicit_construct
    return method(self, expmatch)
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 2101, in directive
    return self.run_directive(
  File "C:\Users\rbsct\anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 2151, in run_directive
    result = directive_instance.run()
  File "C:\Users\rbsct\anaconda3\lib\site-packages\sphinx_charts\charts.py", line 94, in run
    copyfile(src_uri, build_uri)
  File "C:\Users\rbsct\anaconda3\lib\site-packages\sphinx\util\osutil.py", line 88, in copyfile
    shutil.copyfile(source, dest)
  File "C:\Users\rbsct\anaconda3\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rbsct\\Desktop\\lucrare\\source\\chartstest.json'
```

**Comment by AA-Turner** [comment]
Please report to Sphinx Charts, this repo is only for core Sphinx.

A
