### ISSUE TITLE
Flask documentation: ImportError: No module named json

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1144]
With the latest Flask documentation from https://github.com/mitsuhiko/flask, I get several ImportErrors, though it still seems to build everything.

Note: I did `git submodule update --init` to fetch the theme first.

```
#!bash

(todo_cob)georger@mac-georger:~/src/flask/docs$ (master) make clean html
rm -rf _build/*
sphinx-build -b html -d _build/doctrees   . _build/html
Making output directory...
Running Sphinx v1.2b1
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/dev/objects.inv...
loading intersphinx inventory from http://werkzeug.pocoo.org/docs/objects.inv...
loading intersphinx inventory from http://wtforms.simplecodes.com/docs/0.5/objects.inv...
loading intersphinx inventory from http://www.sqlalchemy.org/docs/objects.inv...
loading intersphinx inventory from http://discorporate.us/projects/Blinker/docs/1.1/objects.inv...
building [html]: targets for 70 source files that are out of date
updating environment: 70 added, 0 changed, 0 removed
reading sources... [100&#37;] views
/Users/georger/src/flask/docs/api.rst:363: WARNING: autodoc: failed to import function u'jsonify' from module u'flask.json'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
ImportError: No module named json
/Users/georger/src/flask/docs/api.rst:365: WARNING: autodoc: failed to import function u'dumps' from module u'flask.json'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
ImportError: No module named json
/Users/georger/src/flask/docs/api.rst:367: WARNING: autodoc: failed to import function u'dump' from module u'flask.json'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
ImportError: No module named json
/Users/georger/src/flask/docs/api.rst:369: WARNING: autodoc: failed to import function u'loads' from module u'flask.json'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
ImportError: No module named json
/Users/georger/src/flask/docs/api.rst:371: WARNING: autodoc: failed to import function u'load' from module u'flask.json'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
ImportError: No module named json
/Users/georger/src/flask/docs/api.rst:373: WARNING: autodoc: failed to import class u'JSONEncoder' from module u'flask.json'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
ImportError: No module named json
/Users/georger/src/flask/docs/api.rst:376: WARNING: autodoc: failed to import class u'JSONDecoder' from module u'flask.json'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
ImportError: No module named json
/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/flask/helpers.py:docstring of flask.stream_with_context:26: ERROR: Unexpected indentation.
/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/flask/helpers.py:docstring of flask.stream_with_context:30: WARNING: Definition list ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100&#37;] views
writing additional files... genindex search
copying images... [100&#37;] _static/yes.png
copying static files... done
dumping search index... done
dumping object inventory... done
build succeeded, 9 warnings.

Build finished. The HTML pages are in _build/html.
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1144
- Originally reported by: George V. Reilly
- Originally created at: 2013-04-12T03:35:20.701

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-12 23:13:59+00:00_

Can't reproduce here. What is your Python version? Can you retry with Sphinx 1.2 final?

**Comment by shimizukawa** [comment]
_From George V. Reilly on 2014-01-12 23:30:28+00:00_

I can't repro it now either, after installing Sphinx and Flask in a fresh virtualenv.

Python 2.7.6, installed by Homebrew on OS X 10.9.1

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-13 06:34:09+00:00_

OK, let's close it and reopen should it resurface.
