### ISSUE TITLE
Multiple AttributeErrors in werkzeug documentation

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1145]
Several errors when building the [Werkzeug](http://werkzeug.pocoo.org/) docs:

```
#!bash

(todo_cob)georger@mac-georger:~/src/werkzeug/docs$ (master) make clean html
rm -rf _build/*
sphinx-build -b html -d _build/doctrees   . _build/html
Making output directory...
Running Sphinx v1.2b1
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/dev/objects.inv...
loading intersphinx inventory from http://www.sqlalchemy.org/docs/05/objects.inv...
building [html]: targets for 40 source files that are out of date
updating environment: 40 added, 0 changed, 0 removed
reading sources... [100&#37;] wsgi
/Users/georger/src/werkzeug/docs/exceptions.rst:47: WARNING: autodoc: failed to import exception u'PreconditionRequired' from module u'werkzeug.exceptions'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 333, in import_object
    obj = self.get_attr(obj, part)
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 232, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/util/inspect.py", line 78, in safe_getattr
    raise AttributeError(name)
AttributeError: PreconditionRequired
/Users/georger/src/werkzeug/docs/exceptions.rst:49: WARNING: autodoc: failed to import exception u'TooManyRequests' from module u'werkzeug.exceptions'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 333, in import_object
    obj = self.get_attr(obj, part)
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 232, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/util/inspect.py", line 78, in safe_getattr
    raise AttributeError(name)
AttributeError: TooManyRequests
/Users/georger/src/werkzeug/docs/exceptions.rst:51: WARNING: autodoc: failed to import exception u'RequestHeaderFieldsTooLarge' from module u'werkzeug.exceptions'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 333, in import_object
    obj = self.get_attr(obj, part)
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 232, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/util/inspect.py", line 78, in safe_getattr
    raise AttributeError(name)
AttributeError: RequestHeaderFieldsTooLarge
/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/werkzeug/formparser.py:docstring of werkzeug.formparser.parse_multipart_headers:5: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/werkzeug/formparser.py:docstring of werkzeug.formparser.parse_multipart_headers:7: ERROR: Unexpected indentation.
/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/werkzeug/formparser.py:docstring of werkzeug.formparser.parse_multipart_headers:8: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/georger/src/werkzeug/docs/serving.rst:29: WARNING: autodoc: failed to import function u'make_ssl_devcert' from module u'werkzeug.serving'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 333, in import_object
    obj = self.get_attr(obj, part)
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 232, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/Users/georger/.virtualenvs/todo_cob/lib/python2.7/site-packages/sphinx/util/inspect.py", line 78, in safe_getattr
    raise AttributeError(name)
AttributeError: make_ssl_devcert
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100&#37;] wsgi
writing additional files... genindex py-modindex search
copying images... [100&#37;] _static/shortly.png
copying static files... done
dumping search index... done
dumping object inventory... done
build succeeded, 7 warnings.

Build finished. The HTML pages are in _build/html.
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1145
- Originally reported by: George V. Reilly
- Originally created at: 2013-04-12T23:00:15.588

**Comment by tk0miya** [comment]
Nowadays, with Sphinx 1.3.3, There is no AttributeErrors:

```
$ git clone https://github.com/mitsuhiko/werkzeug
Cloning into 'werkzeug'...
remote: Counting objects: 16853, done.
remote: Total 16853 (delta 0), reused 0 (delta 0), pack-reused 16853
Receiving objects: 100% (16853/16853), 12.21 MiB | 643.00 KiB/s, done.
Resolving deltas: 100% (9079/9079), done.
Checking connectivity... done.
$ cd werkzeug/docs
$ make clean html
rm -rf _build/*
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.3+
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/dev/objects.inv...
loading intersphinx inventory from http://www.sqlalchemy.org/docs/05/objects.inv...
WARNING: intersphinx inventory 'http://www.sqlalchemy.org/docs/05/objects.inv' not fetchable due to <class 'urllib2.HTTPError'>: HTTP Error 404: OK
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 41 source files that are out of date
updating environment: 41 added, 0 changed, 0 removed
reading sources... [100%] wsgi
/Users/tkomiya/work/tmp/werkzeug/docs/debug.rst:83: ERROR: Unknown target name: "gist.github.com".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] wsgi
generating indices... genindex py-modindex
writing additional pages... search
copying images... [100%] _static/shortly.png
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2 warnings.

Build finished. The HTML pages are in _build/html.
```

please let us know again If you found similar errors.

Thanks,
