### ISSUE TITLE
Error encountered while using Ninja

### ISSUE THREAD

**Issue by skippy2004** [sphinx-doc/sphinx#11464]
### Describe the bug

Hello,
I am experiencing a problem with Ninja. I must admit that I'm not quite sure what Ninja is and what its actual purpose is, but I need it to set up the working environment for creating a weather station using the Nordic Thingy:53 component. When I use the Ninja command, I encounter the following error:

```powershell
PS C:\ncs\v2.4.0\nrf\doc\_build> ninja
[0/12] Building kconfig docset...Running Sphinx v5.3.0
loading pickled environment... done
Building Kconfig database...... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
no targets are out of date.
build succeeded.

The HTML pages are in html\kconfig.

[2/12] Generating Devicetree bindings documentation...
[3/12] Building mcuboot docset...Running Sphinx v5.3.0
loading pickled environment... done
loading intersphinx inventory from C:\ncs\v2.4.0\nrf\doc\_build\html\kconfig\objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
no targets are out of date.
build succeeded.

The HTML pages are in html\mcuboot.

[4/12] Building zephyr docset...Running Sphinx v5.3.0
loading intersphinx inventory from C:\ncs\v2.4.0\nrf\doc\_build\html\kconfig\objects.inv...
Preparing Doxyfile...
Checking if Doxygen needs to be run...
Running Doxygen...
WARNING: warning: Specified markdown mainpage 'mainpage.md' does not existC:/ncs/v2.4.0/zephyr/tests/kernel/mem_protect/userspace/src/main.c:419: no matching file member found for
WARNING: C:/ncs/v2.4.0/zephyr/tests/kernel/mem_protect/userspace/src/main.c:594: no matching file member found for
Syncing Doxygen output...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2753 source files that are out of date
updating environment: [new config] 2753 added, 0 changed, 0 removed
reading sources... [ 67%] connectivity/bluetooth/api/audio
Exception occurred:
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
The full traceback has been saved in C:\Users\STAGIA~1\AppData\Local\Temp\sphinx-err-nrcwa4ik.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

FAILED: CMakeFiles/zephyr-all C:/ncs/v2.4.0/nrf/doc/_build/CMakeFiles/zephyr-all
cmd.exe /C "cd /D C:\ncs\v2.4.0\nrf\doc\_build && "C:\Program Files\CMake\bin\cmake.exe" -E make_directory C:/ncs/v2.4.0/nrf/doc/_build/zephyr C:/ncs/v2.4.0/nrf/doc/_build/zephyr/src && "C:\Program Files\CMake\bin\cmake.exe" -E env "DOXYGEN_EXECUTABLE=C:/Program Files/doxygen/bin/doxygen.exe" C:/Users/stagiaire/AppData/Local/Programs/Python/Python310/Scripts/sphinx-build.exe -b html -c C:/ncs/v2.4.0/nrf/doc/zephyr -d C:/ncs/v2.4.0/nrf/doc/_build/zephyr/doctree -w C:/ncs/v2.4.0/nrf/doc/_build/zephyr/html.log -j auto C:/ncs/v2.4.0/nrf/doc/_build/zephyr/src C:/ncs/v2.4.0/nrf/doc/_build/html/zephyr"
ninja: build stopped: subcommand failed.
``` 

I would greatly appreciate it if you could take the time to help me, as I am completely lost.
skippy2004

### How to Reproduce

I followed the instructions from this website using version 2.4.99.

https://developer-nordicsemi-com.translate.goog/nRF_Connect_SDK/doc/latest/nrf/documentation/build.html?_x_tr_sl=auto&_x_tr_tl=fr&_x_tr_hl=fr#doc-build

### Environment Information

```text
Platform:              win32; (Windows-10-10.0.19045-SP0)
Python version:        3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        7.0.1
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.15.1
```

### Additional context

**The full traceback**
# Sphinx version: 5.3.0
# Python version: 3.10.9 (CPython)
# Docutils version: 0.18.1 release
# Jinja2 version: 3.1.2
# Last messages:
#   reading sources... [ 67%] build/kconfig/setting
#   reading sources... [ 67%] build/kconfig/tips
#   reading sources... [ 67%] build/snippets/design
#   reading sources... [ 67%] build/snippets/index
#   reading sources... [ 67%] build/snippets/using
#   reading sources... [ 67%] build/snippets/writing
#   reading sources... [ 67%] build/sysbuild/index
#   reading sources... [ 67%] build/zephyr_cmake_package
#   reading sources... [ 67%] connectivity/bluetooth/api/att
#   reading sources... [ 67%] connectivity/bluetooth/api/audio
# Loaded extensions:
#   sphinx.ext.mathjax (5.3.0) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.4) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.2) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (2.0.1) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.3) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.13) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\alabaster\__init__.py
#   sphinx.ext.intersphinx (5.3.0) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\ext\intersphinx.py
#   breathe (4.35.0) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\__init__.py
#   sphinx.ext.todo (5.3.0) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\ext\todo.py
#   sphinx.ext.extlinks (5.3.0) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\ext\extlinks.py
#   sphinx.ext.autodoc.preserve_defaults (5.3.0) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\ext\autodoc\preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (5.3.0) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\ext\autodoc\type_comment.py
#   sphinx.ext.autodoc.typehints (5.3.0) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\ext\autodoc\typehints.py
#   sphinx.ext.autodoc (5.3.0) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\ext\autodoc\__init__.py
#   sphinx.ext.graphviz (5.3.0) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\ext\graphviz.py
#   zephyr.application (1.0) from C:\ncs\v2.4.0\zephyr\doc\_extensions\zephyr\application.py
#   zephyr.html_redirects (unknown version) from C:\ncs\v2.4.0\zephyr\doc\_extensions\zephyr\html_redirects.py
#   zephyr.kconfig (0.1.0) from C:\ncs\v2.4.0\zephyr\doc\_extensions\zephyr\kconfig\__init__.py
#   zephyr.dtcompatible-role (unknown version) from C:\ncs\v2.4.0\zephyr\doc\_extensions\zephyr\dtcompatible-role.py
#   zephyr.link-roles (unknown version) from C:\ncs\v2.4.0\zephyr\doc\_extensions\zephyr\link-roles.py
#   sphinx_tabs.tabs (unknown version) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx_tabs\tabs.py
#   zephyr.warnings_filter (0.1.0) from C:\ncs\v2.4.0\zephyr\doc\_extensions\zephyr\warnings_filter.py
#   zephyr.doxyrunner (0.1.0) from C:\ncs\v2.4.0\zephyr\doc\_extensions\zephyr\doxyrunner.py
#   zephyr.vcs_link (0.1.0) from C:\ncs\v2.4.0\zephyr\doc\_extensions\zephyr\vcs_link.py
#   notfound.extension (0.8.3) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\notfound\extension.py
#   sphinx_copybutton (0.5.2) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx_copybutton\__init__.py
#   zephyr.external_content (0.1.0) from C:\ncs\v2.4.0\zephyr\doc\_extensions\zephyr\external_content.py
#   sphinx_ncs_theme (unknown version) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx_ncs_theme\__init__.py
#   sphinx_rtd_theme (unknown version) from C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx_rtd_theme\__init__.py
Traceback (most recent call last):
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\domains\c.py", line 3258, in handle_signature
    ast = self.parse_definition(parser)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\domains\c.py", line 3230, in parse_definition
    return parser.parse_declaration(self.object_type, self.objtype)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\domains\c.py", line 3088, in parse_declaration
    declaration = self._parse_enum()
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\domains\c.py", line 3033, in _parse_enum
    name = self._parse_nested_name()
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\domains\c.py", line 2555, in _parse_nested_name
    self.fail("Expected identifier in nested name.")
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\util\cfamily.py", line 293, in fail
    raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C declaration: Expected identifier in nested name. [error at 0]
  
  ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\cmd\build.py", line 281, in build_main
    app.build(args.force_all, args.filenames)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\application.py", line 347, in build
    self.builder.build_update()
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\builders\__init__.py", line 310, in build_update
    self.build(to_build,
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\builders\__init__.py", line 326, in build
    updated_docnames = set(self.read())
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\builders\__init__.py", line 433, in read
    self._read_serial(docnames)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\builders\__init__.py", line 454, in _read_serial
    self.read_doc(docname)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\builders\__init__.py", line 510, in read_doc
    publisher.publish()
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\io.py", line 104, in read
    self.parse()
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\parsers.py", line 78, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\statemachine.py", line 240, in run
    context, next_state, result = self.check_line(
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\statemachine.py", line 452, in check_line
    return method(match, context, next_state)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 2779, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\statemachine.py", line 240, in run
    context, next_state, result = self.check_line(
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\statemachine.py", line 452, in check_line
    return method(match, context, next_state)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 2779, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\statemachine.py", line 240, in run
    context, next_state, result = self.check_line(
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\statemachine.py", line 452, in check_line
    return method(match, context, next_state)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 2352, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 2364, in explicit_construct
    return method(self, expmatch)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 2101, in directive
    return self.run_directive(
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\docutils\parsers\rst\states.py", line 2151, in run_directive
    result = directive_instance.run()
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\directives\content_block.py", line 97, in run
    node_list.extend(object_renderer.render(context.node_stack[0], context))
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2624, in render
    result = method(self, node)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2503, in dispatch_compound
    return self.visit_file(node)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 1254, in visit_file
    return self.visit_compound(node, render_signature=render_signature)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 1163, in visit_compound
    rendered_data = self.render(file_data, parent_context)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2624, in render
    result = method(self, node)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 1008, in visit_doxygendef
    return self.render(node.compounddef)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2624, in render
    result = method(self, node)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 1360, in visit_compounddef
    child_nodes = self.render(sectiondef)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2624, in render
    result = method(self, node)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 1407, in visit_sectiondef
    node_list.extend(self.render_iterable(member_def))
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2634, in render_iterable
    output.extend(self.render(entry))
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2624, in render
    result = method(self, node)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2513, in dispatch_memberdef
    return self.visit_enum(node)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 2106, in visit_enum
    return self.handle_declaration(
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 667, in handle_declaration
    nodes_ = self.run_directive(obj_type, declaration, content_callback, options)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\breathe\renderer\sphinxrenderer.py", line 619, in run_directive
    nodes = directive.run()
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\domains\c.py", line 3250, in run
    return super().run()
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\directives\__init__.py", line 234, in run
    name = self.handle_signature(sig, signode)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\domains\c.py", line 3279, in handle_signature
    logger.warning(e, location=signode)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1847, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\site-packages\sphinx\util\logging.py", line 123, in log
    super().log(level, msg, *args, **kwargs)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1879, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1547, in log
    self._log(level, msg, args, **kwargs)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1624, in _log
    self.handle(record)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 964, in handle
    rv = self.filter(record)
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 821, in filter
    result = f.filter(record)
  File "C:\ncs\v2.4.0\zephyr\doc\_extensions\zephyr\warnings_filter.py", line 55, in filter
    if re.match(expression, record.msg):
  File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

**Comment by picnixz** [comment]
It appears that the `zephyr.warnings_filter` extension is compiling an invalid regular expression pattern as shown here:

> File "C:\ncs\v2.4.0\zephyr\doc_extensions\zephyr\warnings_filter.py", line 55, in filter
if re.match(expression, record.msg):
File "C:\Users\stagiaire\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

Either the `expression` or the `record.msg` value is of incorrect type, so I would advise opening an issue on the nRF repository directly (since you are building their project).
