### ISSUE TITLE
Report of a possible bug as requested. 

### ISSUE THREAD

**Issue by ubaldot** [sphinx-doc/sphinx#11461]
### Describe the bug

I use conda and I am trying to build docs for [this](https://github.com/manimCommunity/manim) package.
After having run make html I get many complaints about missing sphinx extensions and I installed one by one through conda install ... 
... until I reached the point where I get an error and the following message:

```
Exception occurred:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/inspect.py", line 920, in getfile
    raise TypeError('module, class, method, function, traceback, frame, or '
TypeError: module, class, method, function, traceback, frame, or code object was expected, got builtin_function_or_method
The full traceback has been saved in /var/folders/m1/bmnznpdx31v2_lcjnf0nmc3m0000gn/T/sphinx-err-fdjo_83g.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

Given the last part of the error message (_"report also if it is a user error"_), I am taking the opportunity to report the issue. The complete log follows:
```

# Platform:         darwin; (macOS-13.4-arm64-arm-64bit)
# Sphinx version:   6.2.1
# Python version:   3.11.4 (CPython)
# Docutils version: 0.19
# Jinja2 version:   3.1.2
# Pygments version: 2.15.1

# Last messages:
#   reading sources... [ 28%] reference/manim.animation.numbers
#   reading sources... [ 28%] reference/manim.animation.numbers.ChangeDecimalToValue
#   reading sources... [ 28%] reference/manim.animation.numbers.ChangingDecimal
#   reading sources... [ 29%] reference/manim.animation.rotation
#   reading sources... [ 29%] reference/manim.animation.rotation.Rotate
#   reading sources... [ 29%] reference/manim.animation.rotation.Rotating
#   reading sources... [ 29%] reference/manim.animation.specialized
#   reading sources... [ 30%] reference/manim.animation.specialized.Broadcast
#   reading sources... [ 30%] reference/manim.animation.speedmodifier
#   reading sources... [ 30%] reference/manim.animation.speedmodifier.ChangeSpeed

# Loaded extensions:
#   sphinx.ext.mathjax (6.2.1)
#   alabaster (0.7.13)
#   sphinxcontrib.applehelp (1.0.4)
#   sphinxcontrib.devhelp (1.0.2)
#   sphinxcontrib.htmlhelp (2.0.1)
#   sphinxcontrib.serializinghtml (1.1.5)
#   sphinxcontrib.qthelp (1.0.3)
#   sphinx.ext.autodoc.preserve_defaults (6.2.1)
#   sphinx.ext.autodoc.type_comment (6.2.1)
#   sphinx.ext.autodoc.typehints (6.2.1)
#   sphinx.ext.autodoc (6.2.1)
#   sphinx_copybutton (0.5.2)
#   sphinx.ext.napoleon (6.2.1)
#   sphinx.ext.autosummary (6.2.1)
#   sphinx.ext.doctest (6.2.1)
#   sphinx.ext.extlinks (6.2.1)
#   sphinx.ext.viewcode (6.2.1)
#   sphinxext.opengraph (unknown version)
#   manim.utils.docbuild.manim_directive (unknown version)
#   sphinx.ext.graphviz (6.2.1)
#   sphinx.ext.inheritance_diagram (6.2.1)
#   sphinxcontrib.programoutput (unknown version)
#   myst_parser (2.0.0)
#   furo (2022.06.21)
#   sphinx_basic_ng (1.0.0.beta1)

# Traceback:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app.build(args.force_all, args.filenames)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/application.py", line 353, in build
    self.builder.build_update()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 311, in build_update
    self.build(to_build,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 328, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 435, in read
    self._read_serial(docnames)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 456, in _read_serial
    self.read_doc(docname)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 512, in read_doc
    publisher.publish()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/core.py", line 224, in publish
    self.document = self.reader.read(self.source, self.parser,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/io.py", line 108, in read
    self.parse()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/parsers.py", line 80, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
                   ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2357, in explicit_markup
    self.explicit_list(blank_finish)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2382, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 316, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2660, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/ext/autodoc/directive.py", line 146, in run
    result = parse_generated_content(self.state, params.result, documenter)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/ext/autodoc/directive.py", line 89, in parse_generated_content
    nested_parse_with_titles(state, content, node)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/util/nodes.py", line 328, in nested_parse_with_titles
    return state.nested_parse(content, content_offset, node, match_titles=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2355, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/domains/__init__.py", line 286, in run
    return super().run()
           ^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/directives/__init__.py", line 266, in run
    nested_parse_with_titles(self.state, self.content, contentnode, self.content_offset)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/sphinx/util/nodes.py", line 328, in nested_parse_with_titles
    return state.nested_parse(content, content_offset, node, match_titles=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2357, in explicit_markup
    self.explicit_list(blank_finish)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2382, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 316, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2660, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/manim/utils/docbuild/manim_directive.py", line 276, in run
    run_time = timeit(lambda: exec("\n".join(code), globals()), number=1)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/timeit.py", line 234, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<timeit-src>", line 6, in inner
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/manim/utils/docbuild/manim_directive.py", line 276, in <lambda>
    run_time = timeit(lambda: exec("\n".join(code), globals()), number=1)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 15, in <module>
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/manim/scene/scene.py", line 223, in render
    self.construct()
  File "<string>", line 8, in construct
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/manim/scene/scene.py", line 1082, in play
    self.renderer.play(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/manim/renderer/cairo_renderer.py", line 71, in play
    hash_current_animation = get_hash_from_play_call(
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/manim/utils/hashing.py", line 354, in get_hash_from_play_call
    animations_list_json = [get_json(x) for x in sorted(animations_list, key=str)]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/manim/utils/hashing.py", line 354, in <listcomp>
    animations_list_json = [get_json(x) for x in sorted(animations_list, key=str)]
                            ^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/manim/utils/hashing.py", line 320, in get_json
    return json.dumps(obj, cls=_CustomEncoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/manim/utils/hashing.py", line 304, in encode
    return super().encode(obj)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/manim/utils/hashing.py", line 209, in default
    code = inspect.getsource(obj)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/inspect.py", line 1262, in getsource
    lines, lnum = getsourcelines(object)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/inspect.py", line 1244, in getsourcelines
    lines, lnum = findsource(object)
                  ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/inspect.py", line 1063, in findsource
    file = getsourcefile(object)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/inspect.py", line 940, in getsourcefile
    filename = getfile(object)
               ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/inspect.py", line 920, in getfile
    raise TypeError('module, class, method, function, traceback, frame, or '
TypeError: module, class, method, function, traceback, frame, or code object was expected, got builtin_function_or_method

```

### How to Reproduce

1. Install miniconda 
2. `conda create -n my-manim-environment`
3. `conda activate my-manim-environment`
4. `conda install -c conda-forge manim`
5. `conda install -c conda-forge sphinx`
6. Clone the manim repo from [here](https://github.com/manimCommunity/manim)
7. `cd docs`
8.  `make html`
9. `conda install` the various missing dependencies as error messages show along the way

### Environment Information

```text
Platform:              darwin; (macOS-13.4-arm64-arm-64bit)
Python version:        3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:41) [Clang 15.0.7 ])
Python implementation: CPython
Sphinx version:        6.2.1
Docutils version:      0.19
Jinja2 version:        3.1.2
Pygments version:      2.15.1
```

### Sphinx extensions
The extension can be viewed from the log I wrote in the _Describe the bug_ Section.

**Comment by picnixz** [comment]
The issue seems to come from `manim.utils.docbuild.manim_directive`:

>   File "/opt/homebrew/Caskroom/miniconda/base/envs/manim_ce/lib/python3.11/site-packages/manim/utils/hashing.py", line 209, in default
    code = inspect.getsource(obj)

You should probably post an issue on their repo since you are building their doc.

**Comment by ubaldot** [comment]
OK! Thanks for the tip!
