### ISSUE TITLE
module 'sphinx.domains.python' has no attribute 'PyModulelevel'

### ISSUE THREAD

**Issue by ChinaXing** [sphinx-doc/sphinx#11490]
### Describe the bug

try to make docs for HomeKitADK failed

### How to Reproduce

```
git clone https://github.com/apple/HomeKitADK.git
cd HomeKitADK
make docs
```

### Environment Information

```text
# Platform:         darwin; (macOS-13.4.1-arm64-arm-64bit)
# Sphinx version:   7.0.1
# Python version:   3.10.8 (CPython)
# Docutils version: 0.20.1
# Jinja2 version:   3.1.2
# Pygments version: 2.15.1

# Last messages:


# Loaded extensions:


# Traceback:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/opt/homebrew/lib/python3.10/site-packages/sphinx/application.py", line 229, in __init__
    self.setup_extension(extension)
  File "/opt/homebrew/lib/python3.10/site-packages/sphinx/application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "/opt/homebrew/lib/python3.10/site-packages/sphinx/registry.py", line 442, in load_extension
    metadata = setup(app)
  File "/opt/homebrew/lib/python3.10/site-packages/breathe/__init__.py", line 13, in setup
    from . import directives
  File "/opt/homebrew/lib/python3.10/site-packages/breathe/directives.py", line 4, in <module>
    from .renderer import DoxygenToRstRendererFactory
  File "/opt/homebrew/lib/python3.10/site-packages/breathe/renderer/__init__.py", line 5, in <module>
    from . import sphinxrenderer
  File "/opt/homebrew/lib/python3.10/site-packages/breathe/renderer/sphinxrenderer.py", line 76, in <module>
    class DomainDirectiveFactory(object):
  File "/opt/homebrew/lib/python3.10/site-packages/breathe/renderer/sphinxrenderer.py", line 96, in DomainDirectiveFactory
    'function': (python.PyModulelevel, 'function'),
AttributeError: module 'sphinx.domains.python' has no attribute 'PyModulelevel'
```

**Comment by picnixz** [comment]
Hi,

this is a `breathe` issue so it should be reported on their side (check that your `breathe` version is up-to-date before that).

**Comment by picnixz** [comment]
Closing for now since it relates to a deprecated feature and external package.
