### ISSUE TITLE
Git version check for `_in_development` should run with C locale

### ISSUE THREAD

**Issue by birkenfeld** [sphinx-doc/sphinx#11553]
### Describe the bug

In `sphinx/__init__.py`, when `_in_development` is set to true, the git version check is run and its output decoded using the "ascii" codec. On systems with a non-English locale this can lead to a UnicodeDecodeError if no repository is found.

This should run with `LC_ALL=C`, or alternatively ignore UnicodeDecodeErrors.

### How to Reproduce

Need to install German locale...

Don't reproduce within a git repository!

```bash
virtualenv test
source test/bin/activate
pip install git+https://github.com/sphinx-doc/sphinx
sphinx-build --version  ## works
LC_ALL=de_DE sphinx-build --version  ## breaks
```
Exception:
```
Traceback (most recent call last):
  File "/home/gbrandl/.virtualenvs/spre/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/home/gbrandl/.virtualenvs/spre/lib/python3.11/site-packages/sphinx/__init__.py", line 43, in <module>
    ret = subprocess.run(
          ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2150, in _communicate
    stderr = self._translate_newlines(stderr,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1086, in _translate_newlines
    data = data.decode(encoding, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 81: ordinal not in range(128)
```
The output from git is
```
Schwerwiegend: Kein Git-Repository (oder irgendein Elternverzeichnis bis zum Einhängepunkt /)
Stoppe bei Dateisystemgrenze (GIT_DISCOVERY_ACROSS_FILESYSTEM nicht gesetzt).
```

### Environment Information

```text
Not applicable
```

**Comment by AA-Turner** [comment]
Fixed in 062a2e1 (I hadn't considered running the ``_in_development`` logic outside of a repo!). Thanks for reporting @birkenfeld!

A
