### ISSUE TITLE
sphinx.ext.autodoc throws parse_name AssertionError when using (custom) template

### ISSUE THREAD

**Issue by MarvinWeitz** [sphinx-doc/sphinx#11632]
### Describe the bug

I am using `sphinx.ext.autodoc` together with `sphinx.ext.autosummary` to recursively autogenerate documentation from my Docstring.
I followed [this](https://stackoverflow.com/a/62613202/11785440) to make everything work (without custom templates). But as described in the answer, this won't generate separate documentation pages for each attribute, function, class, and exception.
So I tried to add the custom templates provided in my `_templates` directory (it doesn't work with `autosummay`'s original templates either. So this comes down to adding the template in the `_template` directory).
This is when the bug occurs...

running `make html` results in an exception from `sphinx.ext.autodoc`:
```zsh
Exception occurred:
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/sphinx/ext/autodoc/__init__.py", line 388, in parse_name
    assert matched is not None
           ^^^^^^^^^^^^^^^^^^^
```

### How to Reproduce

`index.rst`:
```rst
Some Heading
============

.. autosummary::
   :toctree: _autosummary
   :recursive:

   my_package
```

`conf.py`:
```python
import os
import sys
sys.path.insert(0, os.path.abspath('..'))

extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.autosummary']
autosummary_generate = True

templates_path = ['_templates']
```

### Environment Information

```text
Platform:              linux; (Linux-6.2.0-26-generic-x86_64-with-glibc2.35)
Python version:        3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0])
Python implementation: CPython
Sphinx version:        7.2.2
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.16.1
```

### Sphinx extensions

```python
['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.autosummary']
```

### Additional context

The log file with traceback:

```
# Platform:         linux; (Linux-6.2.0-26-generic-x86_64-with-glibc2.35)
# Sphinx version:   7.2.2
# Python version:   3.11.4 (CPython)
# Docutils version: 0.20.1
# Jinja2 version:   3.1.2
# Pygments version: 2.16.1

# Last messages:
#   _autosummary/docker_kernel.utils.filesystem
#   
#   [2K
#   reading sources... [ 56%]
#   _autosummary/docker_kernel.utils.notebook
#   
#   [2K
#   reading sources... [ 59%]
#   _template/custom-class-template
#   

# Loaded extensions:
#   sphinx.ext.mathjax (7.2.2)
#   alabaster (0.7.13)
#   sphinxcontrib.applehelp (1.0.7)
#   sphinxcontrib.devhelp (1.0.5)
#   sphinxcontrib.htmlhelp (2.0.4)
#   sphinxcontrib.serializinghtml (1.1.8)
#   sphinxcontrib.qthelp (1.0.6)
#   sphinx.ext.autodoc.preserve_defaults (7.2.2)
#   sphinx.ext.autodoc.type_comment (7.2.2)
#   sphinx.ext.autodoc.typehints (7.2.2)
#   sphinx.ext.autodoc (7.2.2)
#   sphinx.ext.napoleon (7.2.2)
#   sphinx.ext.autosummary (7.2.2)

# Traceback:
Traceback (most recent call last):
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 420, in read
    self._read_serial(docnames)
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 441, in _read_serial
    self.read_doc(docname)
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 498, in read_doc
    publisher.publish()
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/sphinx/io.py", line 105, in read
    self.parse()
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/sphinx/parsers.py", line 81, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2357, in explicit_markup
    self.explicit_list(blank_finish)
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2382, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 316, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2660, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/sphinx/ext/autodoc/directive.py", line 139, in run
    documenter.generate(more_content=self.content)
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/sphinx/ext/autodoc/__init__.py", line 1886, in generate
    return super().generate(more_content=more_content,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/sphinx/ext/autodoc/__init__.py", line 869, in generate
    if not self.parse_name():
           ^^^^^^^^^^^^^^^^^
  File "/home/marvin/anaconda3/envs/sphinx/lib/python3.11/site-packages/sphinx/ext/autodoc/__init__.py", line 388, in parse_name
    assert matched is not None
           ^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by AA-Turner** [comment]
Please test with [Sphinx 7.2.3](https://pypi.org/project/Sphinx/7.2.3/).

A

**Comment by MarvinWeitz** [comment]
Works with [Sphinx 7.2.3](https://pypi.org/project/Sphinx/7.2.3/). Thanks @AA-Turner
