### ISSUE TITLE
Unicode posixpath issue with html builder with 1.2b1

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1163]
Reopening Issue #1158 

```
#!python

# Sphinx version: 1.2b1
# Python version: 2.7.4
# Docutils version: 0.9.1 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 246, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 137, in __init__
    self._init_env(freshenv)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 182, in _init_env
    return self._init_env(freshenv=True)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 164, in _init_env
    self.env.find_files(self.config)
  File "/usr/lib/python2.7/site-packages/sphinx/environment.py", line 344, in find_files
    self.srcdir, config.source_suffix, exclude_matchers=matchers))
  File "/usr/lib/python2.7/site-packages/sphinx/util/__init__.py", line 86, in get_matching_docs
    for filename in get_matching_files(dirname, exclude_matchers):
  File "/usr/lib/python2.7/site-packages/sphinx/util/__init__.py", line 62, in get_matching_files
    for root, dirs, files in walk(dirname, followlinks=True):
  File "/usr/lib/python2.7/site-packages/sphinx/util/osutil.py", line 89, in walk
    for x in walk(fullpath, topdown, followlinks):
  File "/usr/lib/python2.7/site-packages/sphinx/util/osutil.py", line 79, in walk
    if path.isdir(path.join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 1: ordinal not in range(128)

```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1163
- Originally reported by: [tychoish](https://bitbucket.org/tychoish)
- Originally created at: 2013-05-06T18:31:04.924

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-10 05:02:05+00:00_

Issue #1158 was marked as a duplicate of this issue.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-10 05:30:36+00:00_

[tychoish](https://bitbucket.org/tychoish) I could not reproduce that behavior. I think your directory/file structure includes Multibyte/Fullwidth character's name, I have prepared Japanese file/dir source structure, but the problem did not reproduce.

Please attach your (minimal) sample project. Thanks.
