### ISSUE TITLE
UnboundLocalError: local variable 'membername' referenced before assignment

### ISSUE THREAD

**Issue by MetRonnie** [sphinx-doc/sphinx#11631]
### Describe the bug

This seems to be a bug in sphinx autodoc that affects Sphinx 7.2.0 - 7.2.2. When building the docs I get

> UnboundLocalError: local variable 'membername' referenced before assignment

### How to Reproduce

`git clone` method I'm afraid

```shell
git clone https://github.com/cylc/cylc-doc.git

# (graphviz is needed by cylc-doc)
conda install graphviz

cd cylc-doc
pip install -e .[all]

make clean html SPHINXOPTS='-Wn'  # (calls sphinx-build, see Makefile for details)
```

### Environment Information

```text
# Platform:         linux; (Linux-3.10.0-1160.95.1.el7.x86_64-x86_64-with-glibc2.17)
# Sphinx version:   7.2.0
# Python version:   3.10.6 (CPython)
# Docutils version: 0.18.1
# Jinja2 version:   3.0.3
# Pygments version: 2.16.1
```

Also tested with 7.2.2 and faced the same bug

### Sphinx extensions

```python
# Loaded extensions:
#   sphinx.ext.mathjax (7.2.0)
#   alabaster (0.7.12)
#   sphinxcontrib.applehelp (1.0.7)
#   sphinxcontrib.devhelp (1.0.5)
#   sphinxcontrib.htmlhelp (2.0.4)
#   sphinxcontrib.serializinghtml (1.1.9)
#   sphinxcontrib.qthelp (1.0.6)
#   sphinx.ext.autodoc.preserve_defaults (7.2.0)
#   sphinx.ext.autodoc.type_comment (7.2.0)
#   sphinx.ext.autodoc.typehints (7.2.0)
#   sphinx.ext.autodoc (7.2.0)
#   sphinx.ext.autosummary (7.2.0)
#   sphinx.ext.doctest (7.2.0)
#   sphinx.ext.graphviz (7.2.0)
#   sphinx.ext.intersphinx (7.2.0)
#   sphinxcontrib.spelling (8.0.0)
#   hieroglyph (2.1.0)
#   sphinxcontrib.jquery (4.1)
#   sphinx_rtd_theme (unknown version)
#   autodoc_traits (unknown version)
#   database_diagram (1.0.0)
#   autodoc_enum_values (unknown version)
#   cylc.sphinx_ext.cylc_lang (1.0.0)
#   cylc.sphinx_ext.diff_selection (1.0.0)
#   cylc.sphinx_ext.grid_table (1.0.0)
#   cylc.sphinx_ext.hieroglyph_addons (1.0.0)
#   cylc.sphinx_ext.minicylc (1.0.0)
#   cylc.sphinx_ext.practical (1.0.0)
#   cylc.sphinx_ext.rtd_theme_addons (1.0.0)
#   cylc.sphinx_ext.sub_lang (1.0.0)
#   cylc.sphinx_ext.literal_sub_include (1.0.0)
```

### Additional context

Full traceback
```
Traceback (most recent call last):
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 681, in filter_members
    membername = obj.__name__
AttributeError: 'tuple' object has no attribute '__name__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/application.py", line 354, in build
    self.builder.build_update()
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 420, in read
    self._read_serial(docnames)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 441, in _read_serial
    self.read_doc(docname)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 498, in read_doc
    publisher.publish()
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/io.py", line 105, in read
    self.parse()
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/parsers.py", line 81, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/statemachine.py", line 240, in run
    context, next_state, result = self.check_line(
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/statemachine.py", line 452, in check_line
    return method(match, context, next_state)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2779, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/statemachine.py", line 240, in run
    context, next_state, result = self.check_line(
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/statemachine.py", line 452, in check_line
    return method(match, context, next_state)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_markup
    self.explicit_list(blank_finish)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2379, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 318, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/statemachine.py", line 240, in run
    context, next_state, result = self.check_line(
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/statemachine.py", line 452, in check_line
    return method(match, context, next_state)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2657, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2364, in explicit_construct
    return method(self, expmatch)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2101, in directive
    return self.run_directive(
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2151, in run_directive
    result = directive_instance.run()
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/ext/autodoc/directive.py", line 139, in run
    documenter.generate(more_content=self.content)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 1886, in generate
    return super().generate(more_content=more_content,
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 950, in generate
    self.document_members(all_members)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 1872, in document_members
    super().document_members(all_members)
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 806, in document_members
    for (mname, member, isattr) in self.filter_members(members, want_all):
  File "~/.conda/envs/cylc8.1/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 779, in filter_members
    self.name, membername, member, exc, type='autodoc')
UnboundLocalError: local variable 'membername' referenced before assignment
```

**Comment by AA-Turner** [comment]
Almost certainly related: 6f3c5b8

A

**Comment by AA-Turner** [comment]
There are two errors here: the first is that we use ``membername`` in the error condition of the very same block where ``membername`` is defined -- the second is that ``obj.__name__`` fails, as ``obj`` is a tuple rather than an instance of ``ObjectMember``.

A

**Comment by AA-Turner** [comment]
Hi Ronnie,

I wonder if you'd be able to advise on setting things up locally?

I'm on Windows, so I've created an ``environment.yml`` with the following, running ``mamba env update``: 

```yaml
name: cylc-doc
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip

  - Sphinx>=7.2.3
  - graphviz
  - eralchemy==1.2.*
  - sphinx_rtd_theme>=1.0.0
  - sphinxcontrib-spelling
  - cylc-flow

  - pip:
    - cylc-sphinx-extensions>=1.4.1
    - enchant
    - hieroglyph>=2.1.0
    - sphinxcontrib-svg2pdfconverter
```

This though complains that ``cycl-flow`` can't be installed. When I remove the ``cycl-flow`` requirement, I then can't render the documentation, as your ``conf.py`` contains:

```python
from cylc.flow import __version__ as CYLC_VERSION
from cylc.flow.workflow_files import WorkflowFiles

sys.path.append(os.path.abspath('lib'))  # path to lib.

from cylc_release import CYLC_RELEASE
```

I'm also not entirely sure where ``cylc_release`` comes from?

I haven't been able to find any documentation about contributing to the documentation -- sorry if I've missed this!

As an aside, it might be useful if your repository contained an ``environment.yml`` file or similar, given you reccommend ``mamba`` in several places, so that users can get up to speed quicker. 

Similarly, I'd encourage you to consider moving to standards-based metadata instead of ``setup.cfg`` -- you can look at setuptools' documentation for how to migrate over. Your current ``setup.cfg`` doesn't install ``cylc-flow``, though -- I had to add that dependency myself, and got into the jam above where I can't get anything working!

Sorry not to be able to help quicker on this,
Thanks,
Adam

**Comment by MetRonnie** [comment]
Hi Adam, thanks for taking a look. Sorry I'm not really in a position to come up with a minimal example - not sure where to start.

> I'm on Windows

`cylc-flow` only runs on unix, so we don't have any Windows installable on conda-forge. Try pip instead - it may still be able to install for the purposes of building the docs (`cylc-flow==8.2.1`).

> Your current `setup.cfg` doesn't install `cylc-flow`

Not sure why we haven't listed `cylc-flow` as a dependency, though most of the time we wouldn't expect anyone to install the docs without `cylc-flow` already being installed.

**Comment by AA-Turner** [comment]
I've managed to reproduce this, I'm fairly sure. Looking into a fix.

A

**Comment by AA-Turner** [comment]
Hi Ronnie,

I've tracked down the issue to one of your custom extensions, rather than a problem in Sphinx itself (though the error message is unhelpful, as above). A minimal reproducer is:


``index.rst``
```rest
.. autoconfigurable:: cylc.uiserver.app.CylcUIServer
    :inherited-members: False
```

``conf.py``
```python
import os, sys
sys.path.append(os.path.abspath('ext'))
extensions = [
    'sphinx.ext.autodoc',
    'autodoc_traits',
]
```

The offending lines are here: https://github.com/cylc/cylc-doc/blob/17c24399954f7fdce596bfed61c43c68d37b735f/src/ext/autodoc_traits/autodoc_traits.py#L65-L78

I suggest fixing with the following:

```
def get_object_members(self, want_all: bool) -> tuple[bool, list[ObjectMember]]:
    """Add traits with .tag(config=True) to members list"""
    check, _members = super().get_object_members(want_all)
    if self.options.inherited_members:
        get_traits = self.object.class_own_traits
    else:
        get_traits = self.object.class_traits
    trait_members = [
        ObjectMember(name, trait, docstring=trait.help)
        for name, trait in sorted(get_traits(config=True).items())
    ]
    return check, trait_members
```

Sorry for writing on the bank holiday weekend, this issue took me quite a while to track down.

A

**Comment by MetRonnie** [comment]
Great, thanks!
