### ISSUE TITLE
Generating manpages throws a traceback

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1168]
For some reason, when I do a “make man”, it docutils throws a traceback for some pages.

```
#!python


# Sphinx version: 1.1.3
# Python version: 3.3.1
# Docutils version: 0.10 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/usr/lib/python3.3/site-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/usr/lib/python3.3/site-packages/sphinx/builders/__init__.py", line 191, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.3/site-packages/sphinx/builders/__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.3/site-packages/sphinx/builders/manpage.py", line 88, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.3/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python3.3/site-packages/sphinx/writers/manpage.py", line 35, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.3/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.3/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.3/site-packages/docutils/nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/lib/python3.3/site-packages/docutils/nodes.py", line 1640, in dispatch_departure
    return method(node)
  File "/usr/lib/python3.3/site-packages/docutils/writers/manpage.py", line 411, in depart_admonition
    self.depart_block_quote(node)
  File "/usr/lib/python3.3/site-packages/docutils/writers/manpage.py", line 449, in depart_block_quote
    self.dedent()
  File "/usr/lib/python3.3/site-packages/docutils/writers/manpage.py", line 865, in dedent
    self._indent.pop()
IndexError: pop from empty list

```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1168
- Originally reported by: Anonymous
- Originally created at: 2013-05-10T20:56:22.566

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-05-11 02:19:02+00:00_

Sphinx-1.1.3 did not support Python-3.3.x. Please use Sphinx-1.2b1 for Python-3.3.
