### ISSUE TITLE
sphinx-build -b man -d build/doctrees  source build/man throws exception

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1169]
```
# Sphinx version: 1.1.3
# Python version: 2.7.3
# Docutils version: 0.10 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/lab/epg_st_logs/elastav/.my/rhes6.x86_64/lib/python2.7/site-packages/Sphinx-1.1.3-py2.7.egg/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/lab/epg_st_logs/elastav/.my/rhes6.x86_64/lib/python2.7/site-packages/Sphinx-1.1.3-py2.7.egg/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/lab/epg_st_logs/elastav/.my/rhes6.x86_64/lib/python2.7/site-packages/Sphinx-1.1.3-py2.7.egg/sphinx/builders/__init__.py", line 191, in build_update
    self.build(['__all__'], to_build)
  File "/lab/epg_st_logs/elastav/.my/rhes6.x86_64/lib/python2.7/site-packages/Sphinx-1.1.3-py2.7.egg/sphinx/builders/__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/lab/epg_st_logs/elastav/.my/rhes6.x86_64/lib/python2.7/site-packages/Sphinx-1.1.3-py2.7.egg/sphinx/builders/manpage.py", line 72, in write
    tree = self.env.get_doctree(docname)
  File "/lab/epg_st_logs/elastav/.my/rhes6.x86_64/lib/python2.7/site-packages/Sphinx-1.1.3-py2.7.egg/sphinx/environment.py", line 1213, in get_doctree
    f = open(doctree_filename, 'rb')
IOError: [Errno 2] No such file or directory: '/home/elastav/proj/stlib/dox/build/doctrees/man.doctree'
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1169
- Originally reported by: Lars Stavholm
- Originally created at: 2013-05-12T07:29:40.251

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-19 16:36:59+00:00_

Should be fixed by d9a1814088ab.
