### ISSUE TITLE
test_texinfo fails: makeinfo exited with return code 1

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1175]
test_build_texinfo.test_texinfo fails here:

```
======================================================================
FAIL: test_build_texinfo.test_texinfo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jwilk/sphinx/tests/util.py", line 199, in deco
    func(app, *args2, **kwargs2)
  File "/home/jwilk/sphinx/tests/test_build_texinfo.py", line 67, in test_texinfo
    assert False, 'makeinfo exited with return code &#37;s' &#37; retcode
AssertionError: makeinfo exited with return code 1
-------------------- >> begin captured stdout << ---------------------

SphinxTests.texi:739: warning: [False](https://bitbucket.org/itemize) has text but no [False](https://bitbucket.org/itemize)
SphinxTests.texi:856: warning: [False](https://bitbucket.org/itemize) missing argument
SphinxTests.texi:857: warning: [False](https://bitbucket.org/itemize) missing argument
SphinxTests.texi:2648: bad argument to [False](https://bitbucket.org/itemize)


--------------------- >> end captured stdout << ----------------------
```

This is with GNU texinfo 5.1.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1175
- Originally reported by: Jakub Wilk
- Originally created at: 2013-05-27T13:26:12.032

**Comment by shimizukawa** [comment]
_From Dmitry Shachnev on 2013-07-10 15:39:06+00:00_

This is an issue in TeXinfo, which doesn't support arguments to `[False](https://bitbucket.org/enumerate)` more than 10 (see [this thread](https://lists.gnu.org/archive/html/bug-texinfo/2013-07/index.html)). Please close this.
