### ISSUE TITLE
ValueError: No template sub-directory with name 'rst' found in the following paths:

### ISSUE THREAD

**Issue by salvatore-ferrone** [sphinx-doc/sphinx#11870]
### Describe the bug

Hello, I want to include a Jupyter notebook as part of my documentation and build an html page with `make html`. Building the html when the project consists of only `*.rst` files works just fine.

This is my first time using Sphinx and am following this guide by [Bovy](https://pythonpackaging.info/04-Documentation.html).

However, when attempting to add a simple notebook to my `index.rst` file, sphinx complains. The program invited me to share this bug with the developers. 

The full error message is pasted in the Environment Information section. 

## File structure

```
/project/
    docs/
        make.bat
        Makefile
        build/
            doctrees/
            html/
        source/
            conf.py
            index.rst
            intro_notebook.ipynb
```

### Index.rst 
```
.. 
Welcome to PROJECTS documentation!
====================================

.. toctree::
   :maxdepth: 1
   :caption: Contents:

   intro_notebook.ipynb

Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
```

### conf.py
```python 
import os
import sys
sys.path.insert(0, os.path.abspath('../../'))

# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'PROJECT'
copyright = '2024, Salvatore Ferrone'
author = 'Salvatore Ferrone'
release = '0.0.1'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = ['sphinx.ext.autodoc',"sphinx.ext.napoleon","nbsphinx"]

templates_path = []
exclude_patterns = ['tstrippy/tstrippy/lib/*.so','.ipynb_checkpoints/*']


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'alabaster'
html_static_path = []

# -- Options for configuring jupyter notebooks --------------------------------
nbsphinx_prompt_width = 0
```

### intro_notebook.ipynb
```
------ cell 1: markdown
some markdown
------ cell 2: python
print("hello world")
```

### Environment Information

```text
# Platform:         darwin; (macOS-13.0-arm64-arm-64bit)
# Sphinx version:   7.2.6
# Python version:   3.11.2 (CPython)
# Docutils version: 0.20.1
# Jinja2 version:   3.1.2
# Pygments version: 2.17.2

# Last messages:


# Loaded extensions:


# Traceback:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/traitlets/traitlets.py", line 632, in get
    value = obj._trait_values[self.name]
            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/sphinx/cmd/build.py", line 293, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sphinx/application.py", line 233, in __init__
    self.setup_extension(extension)
  File "/opt/homebrew/lib/python3.11/site-packages/sphinx/application.py", line 406, in setup_extension
    self.registry.load_extension(self, extname)
  File "/opt/homebrew/lib/python3.11/site-packages/sphinx/registry.py", line 447, in load_extension
    mod = import_module(extname)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/homebrew/lib/python3.11/site-packages/nbsphinx/__init__.py", line 293, in <module>
    """.replace('__RST_DEFAULT_TEMPLATE__', nbconvert.RSTExporter().template_file)
                                            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nbconvert/exporters/templateexporter.py", line 350, in __init__
    super().__init__(config=config, **kw)
  File "/opt/homebrew/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 123, in __init__
    self._init_preprocessors()
  File "/opt/homebrew/lib/python3.11/site-packages/nbconvert/exporters/templateexporter.py", line 535, in _init_preprocessors
    conf = self._get_conf()
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nbconvert/exporters/templateexporter.py", line 553, in _get_conf
    for path in map(Path, self.template_paths):
                          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/traitlets/traitlets.py", line 687, in __get__
    return t.cast(G, self.get(obj, cls))  # the G should encode the Optional
                     ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/traitlets/traitlets.py", line 635, in get
    default = obj.trait_defaults(self.name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/traitlets/traitlets.py", line 1897, in trait_defaults
    return t.cast(Sentinel, self._get_trait_default_generator(names[0])(self))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/traitlets/traitlets.py", line 1241, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nbconvert/exporters/templateexporter.py", line 564, in _template_paths
    template_names = self.get_template_names()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nbconvert/exporters/templateexporter.py", line 652, in get_template_names
    raise ValueError(msg)
ValueError: No template sub-directory with name 'rst' found in the following paths:
        /Users/sferrone/Library/Jupyter
        /Users/sferrone/Library/Python/3.11/share/jupyter
        /opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/share/jupyter
        /usr/local/share/jupyter
        /usr/share/jupyter
```

### Sphinx extensions

```python
extensions = ['sphinx.ext.autodoc',"sphinx.ext.napoleon","nbsphinx"]
```

### Additional context

``` 
pip3 list 
    nbsphinx                      0.9.3
```

**Comment by salvatore-ferrone** [comment]
Hello, as a note, the build works fine on my remote machine:


```text
Platform:              linux; (Linux-6.2.0-39-generic-x86_64-with-glibc2.35)
Python version:        3.11.2 (main, Mar 27 2023, 23:42:44) [GCC 11.2.0])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.3
Pygments version:      2.14.0
```

and 

```text

pip3 list 
   nbsphinx                      0.9.3
```

**Comment by AA-Turner** [comment]
This is a problem in the nbspbinx extension--please would you report to that team? 

https://github.com/spatialaudio/nbsphinx

A
