### ISSUE TITLE
Multiple references in the same line return the same link with i18n

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1193]
When I generate a po file with gettext, I make a translation from a text like below

```
#!txt

Look :ref:`reference1 <reference1>` for more details, :ref:`reference2 <reference2>`
```

reference1 and reference2 are present in two other files, I have in my generated html a result like below

```
#!html

<p>Voir cette <a href="reference2.html#reference2" class="reference internal"><em>reference1</em></a> et pour plus de details, <a href="reference2.html#reference2" class="reference internal"><em>reference2</em></a></p>
```

As you see, I have two link pointing to the same url athought my 2 references are different. This behaviour is unexpected in my opinion.

You can see the problem by cloning the depot https://github.com/ThomasG77/sphinxi18bug.git and doing a "make html" (configure for Unix like, not tested on Windows)
I am using 1.2beta1

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1193
- Originally reported by: [ThomasG77](https://bitbucket.org/ThomasG77)
- Originally created at: 2013-06-11T16:12:55.662

**Comment by shimizukawa** [comment]
_From Claude Paroz on 2013-06-14 09:18:49+00:00_

We just faced the exact same bug when generating the index page for Django docs:
https://docs.djangoproject.com/fr/1.5/

The links on a same line are always the same while the translation is correct. Tell me if I can help!

**Comment by shimizukawa** [comment]
_From Claude Paroz on 2013-06-14 13:05:54+00:00_

This behaviour was caused by commit b3e09bb. To be investigated...

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-15 04:15:55+00:00_

[Claude Paroz](https://bitbucket.org/claudep) Thanks for the pointer! I'll fix this.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-16 15:20:00+00:00_

Fix: Multiple references in the same line return the same link with i18n. Closes #1193

→ <<cset afc6b6d1f8b9ec9b7fbc249fbe27f9fe9294b12e>>

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-16 15:20:00+00:00_

add tests for "multiple cross references in the same line return the same link". refs #1090, #1193

→ <<cset bd4da7df55312b6cb8606739550743b4ba4b0eb0>>

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-16 15:20:00+00:00_

Fix multiple cross references (term, ref, doc) in the same line return the same link with i18n. refs #1090, #1193

→ <<cset deb01d8e307e9c8df3557bad9d48fabcae8c88fa>>

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-16 15:20:00+00:00_

change: now XMLBuilder.get_target_uri() return docname to keep reference information from document to another document. refs #1193

→ <<cset 472a3a83b2e86a728774e3c4671fc80d7d939a3d>>

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-16 15:22:10+00:00_

[ThomasG77](https://bitbucket.org/ThomasG77) I fixed this issue. Please try the newest (in the repository) version of the Sphinx if you can.

[ThomasG77](https://bitbucket.org/ThomasG77) thanks for the suggestion!

**Comment by shimizukawa** [comment]
_From Claude Paroz on 2013-06-16 17:33:45+00:00_

Mmmh, now I'm getting this:

```
# Sphinx version: 1.2b1
# Python version: 2.6.6
# Docutils version: 0.10 release
# Jinja2 version: 2.7
Traceback (most recent call last):
  File "/home/claude/virtualenvs/djangoproject/src/sphinx/sphinx/cmdline.py", line 247, in main
    app.build(force_all, filenames)
  File "/home/claude/virtualenvs/djangoproject/src/sphinx/sphinx/application.py", line 211, in build
    self.builder.build_update()
  File "/home/claude/virtualenvs/djangoproject/src/sphinx/sphinx/builders/__init__.py", line 211, in build_update
    'out of date' % len(to_build))
  File "/home/claude/virtualenvs/djangoproject/src/sphinx/sphinx/builders/__init__.py", line 231, in build
    purple, length):
  File "/home/claude/virtualenvs/djangoproject/src/sphinx/sphinx/builders/__init__.py", line 131, in status_iterator
    for item in iterable:
  File "/home/claude/virtualenvs/djangoproject/src/sphinx/sphinx/environment.py", line 469, in update_generator
    self.read_doc(docname, app=app)
  File "/home/claude/virtualenvs/djangoproject/src/sphinx/sphinx/environment.py", line 634, in read_doc
    domain.process_doc(self, docname, doctree)
  File "/home/claude/virtualenvs/djangoproject/src/sphinx/sphinx/domains/std.py", line 503, in process_doc
    labelid = document.nameids[name]
KeyError: u'glossary'
```

**Comment by shimizukawa** [comment]
_From [ThomasG77](https://bitbucket.org/ThomasG77) on 2013-06-16 18:23:46+00:00_

For me doing a hg clone and installing works the expected way with my sample repo (A bit dirty but I'm outside a virtualenv FYI)

In a more complex repository, I get like claudep an identical type of error

```
#!python

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2b1dev_20130616-py2.7.egg/sphinx/cmdline.py", line 247, in main
    app.build(force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2b1dev_20130616-py2.7.egg/sphinx/application.py", line 207, in build
    self.builder.build_all()
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2b1dev_20130616-py2.7.egg/sphinx/builders/__init__.py", line 174, in build_all
    self.build(None, summary='all source files', method='all')
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2b1dev_20130616-py2.7.egg/sphinx/builders/__init__.py", line 231, in build
    purple, length):
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2b1dev_20130616-py2.7.egg/sphinx/builders/__init__.py", line 131, in status_iterator
    for item in iterable:
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2b1dev_20130616-py2.7.egg/sphinx/environment.py", line 469, in update_generator
    self.read_doc(docname, app=app)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2b1dev_20130616-py2.7.egg/sphinx/environment.py", line 634, in read_doc
    domain.process_doc(self, docname, doctree)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2b1dev_20130616-py2.7.egg/sphinx/domains/std.py", line 503, in process_doc
    labelid = document.nameids[name]
KeyError: u'about'
```

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-18 09:21:37+00:00_

I'll fix soon

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-19 11:17:02+00:00_

fix: keep reference if link refname was translated. refs #1193

case1::

   Keep link to ExternalSite_.

   It will translated with `\`SomeOtherString\`_`.

   .. _ExternalSite: http://example.com

case2::

   Keep link to `title string`_ before appearing.

   title string
   =============

case3::

   Keep link to glossary 'term string'.

   .. glossary::

```
  term string
     description...
```

→ <<cset a997f98333cbd62bbebbe2a17668d712dcd105e1>>

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-19 11:17:02+00:00_

fix: Duplicated section name will cause crash. refs #1193

→ <<cset 430d0e9895457c8f6243ec22a5019800eab7ed01>>

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-19 11:17:03+00:00_

fix: translation mechanism break label target if label and section name are same. refs #1193

→ <<cset 4579bb6e85432018b2188a4e672025e017f76926>>

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-19 11:19:20+00:00_

[Claude Paroz](https://bitbucket.org/claudep) [Claude Paroz](https://bitbucket.org/claudep) could you check again?

**Comment by shimizukawa** [comment]
_From Claude Paroz on 2013-06-19 14:42:55+00:00_

Thanks Takayuki! It seems to work fine, this time.

**Comment by shimizukawa** [comment]
_From [ThomasG77](https://bitbucket.org/ThomasG77) on 2013-06-19 17:28:43+00:00_

It works. Thanks for this fix: I was really stuck

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-20 00:55:23+00:00_

Thank you for your confirmation!
