### ISSUE TITLE
Error when compiling scikit-learn documentation

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1195]
I cloned the scikit-learn repository as of today (2013.06.15) and after compilation (make) I ran "make doc" with the resulting error message (see attached document)

xubuntu 13.04 x64
python 2.7.4

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1195
- Originally reported by: Anonymous
- Originally created at: 2013-06-15T11:00:25.844

**Comment by tk0miya** [comment]
I salvaged the attached document from bitbucket:

```
# Sphinx version: 1.1.3
# Python version: 2.7.4
# Docutils version: 0.10 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 292, in write
    self.write_doc(docname, doctree)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/html.py", line 419, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/lib/python2.7/dist-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python2.7/dist-packages/sphinx/writers/html.py", line 38, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 1627, in dispatch_visit
    return method(node)
  File "/usr/lib/python2.7/dist-packages/sphinx/writers/html.py", line 377, in visit_image
    BaseTranslator.visit_image(self, node)
  File "/usr/lib/python2.7/dist-packages/docutils/writers/html4css1/__init__.py", line 1032, in visit_image
    and self.settings.file_insertion_enabled):
AttributeError: Values instance has no attribute 'file_insertion_enabled'
```

**Comment by tk0miya** [comment]
I can not reproduce the error with Sphinx-1.3.3.
I use following commands to investigation:

```
$ virtualenv py27
$ . ./py27/bin/activate
$ pip install Sphinx numpy matplotlib cython scipy Pillow
$ git clone https://github.com/scikit-learn/scikit-learn
$ cd scikit-learn
$ git co 0.17.X
$ python setup.py install
$ make doc
```

MEMO: I'd tested on 0.17.X branch. because it seems the master branch has broken. it raises many errors arround sklearn.linear_model.sag_fast.

Please let me know again if you get any errors
