### ISSUE TITLE
KeyError: 'srctree' in 'os.py' when building linux kernel documentation

### ISSUE THREAD

**Issue by hwhsu1231** [sphinx-doc/sphinx#12079]
### Describe the bug

I tried to build linux kernel's documentation locally, but failed with the following exception error:

```
Exception occurred:
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'srctree'
```

### How to Reproduce

Run the following commands in order:

```
git clone --depth=1 https://github.com/torvalds/linux.git
cd linux
git name-rev --name-only HEAD
git rev-parse HEAD
python3 -m venv .venv
source .venv/bin/activate
cd Documentation
pip install -r sphinx/requirements.txt
LANG=en_US.UTF-8 sphinx-build -b html -c . . _build/html
```

### Environment Information

```text
Platform:              linux; (Linux-6.5.0-25-generic-x86_64-with-glibc2.35)
Python version:        3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.16.1
```

### Additional context

<details><summary>Click to expand the full log of 'How to Reproduce'</summary>

```bash
hwhsu1231@vb-kubuntu:~/Repo$ git clone --depth=1 https://github.com/torvalds/linux.git
Cloning into 'linux'...
remote: Enumerating objects: 88987, done.
remote: Counting objects: 100% (88987/88987), done.
remote: Compressing objects: 100% (79973/79973), done.
remote: Total 88987 (delta 9019), reused 67028 (delta 8109), pack-reused 0
Receiving objects: 100% (88987/88987), 247.50 MiB | 3.54 MiB/s, done.
Resolving deltas: 100% (9019/9019), done.
Updating files: 100% (83996/83996), done.
hwhsu1231@vb-kubuntu:~/Repo$ cd linux
hwhsu1231@vb-kubuntu:~/Repo/linux$ git name-rev --name-only HEAD
master
hwhsu1231@vb-kubuntu:~/Repo/linux$ git rev-parse HEAD
480e035fc4c714fb5536e64ab9db04fedc89e910
hwhsu1231@vb-kubuntu:~/Repo/linux$ python3 -m venv .venv
hwhsu1231@vb-kubuntu:~/Repo/linux$ source .venv/bin/activate
(.venv) hwhsu1231@vb-kubuntu:~/Repo/linux$ cd Documentation
(.venv) hwhsu1231@vb-kubuntu:~/Repo/linux/Documentation$ pip install -r sphinx/requirements.txt
Collecting alabaster
  Using cached alabaster-0.7.16-py3-none-any.whl (13 kB)
Collecting Sphinx
  Using cached sphinx-7.2.6-py3-none-any.whl (3.2 MB)
Collecting pyyaml
  Using cached PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (705 kB)
Collecting requests>=2.25.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting sphinxcontrib-devhelp
  Using cached sphinxcontrib_devhelp-1.0.6-py3-none-any.whl (83 kB)
Collecting Pygments>=2.14
  Using cached pygments-2.17.2-py3-none-any.whl (1.2 MB)
Collecting docutils<0.21,>=0.18.1
  Using cached docutils-0.20.1-py3-none-any.whl (572 kB)
Collecting sphinxcontrib-serializinghtml>=1.1.9
  Using cached sphinxcontrib_serializinghtml-1.1.10-py3-none-any.whl (92 kB)
Collecting Jinja2>=3.0
  Using cached Jinja2-3.1.3-py3-none-any.whl (133 kB)
Collecting sphinxcontrib-applehelp
  Using cached sphinxcontrib_applehelp-1.0.8-py3-none-any.whl (120 kB)
Collecting imagesize>=1.3
  Using cached imagesize-1.4.1-py2.py3-none-any.whl (8.8 kB)
Collecting packaging>=21.0
  Using cached packaging-24.0-py3-none-any.whl (53 kB)
Collecting sphinxcontrib-qthelp
  Using cached sphinxcontrib_qthelp-1.0.7-py3-none-any.whl (89 kB)
Collecting babel>=2.9
  Using cached Babel-2.14.0-py3-none-any.whl (11.0 MB)
Collecting sphinxcontrib-jsmath
  Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting sphinxcontrib-htmlhelp>=2.0.0
  Using cached sphinxcontrib_htmlhelp-2.0.5-py3-none-any.whl (99 kB)
Collecting snowballstemmer>=2.0
  Using cached snowballstemmer-2.2.0-py2.py3-none-any.whl (93 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.6-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Installing collected packages: snowballstemmer, urllib3, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, pyyaml, Pygments, packaging, MarkupSafe, imagesize, idna, docutils, charset-normalizer, certifi, babel, alabaster, requests, Jinja2, Sphinx
Successfully installed Jinja2-3.1.3 MarkupSafe-2.1.5 Pygments-2.17.2 Sphinx-7.2.6 alabaster-0.7.16 babel-2.14.0 certifi-2024.2.2 charset-normalizer-3.3.2 docutils-0.20.1 idna-3.6 imagesize-1.4.1 packaging-24.0 pyyaml-6.0.1 requests-2.31.0 snowballstemmer-2.2.0 sphinxcontrib-applehelp-1.0.8 sphinxcontrib-devhelp-1.0.6 sphinxcontrib-htmlhelp-2.0.5 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.7 sphinxcontrib-serializinghtml-1.1.10 urllib3-2.2.1
(.venv) hwhsu1231@vb-kubuntu:~/Repo/linux/Documentation$ LANG=en_US.UTF-8 sphinx-build -b html -c . . _build/html
Running Sphinx v7.2.6
Using alabaster theme
making output directory... done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 3460 source files that are out of date
updating environment: [new config] 3460 added, 0 changed, 0 removed
reading sources... [  2%] admin-guide/abi-obsolete
Exception occurred:
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'srctree'
The full traceback has been saved in /tmp/sphinx-err-xnom7rku.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
(.venv) hwhsu1231@vb-kubuntu:~/Repo/linux/Documentation$
```

</details>

<details><summary>Click to expand the full log of '/tmp/sphinx-err-xnom7rku.log'</summary>

```
# Platform:         linux; (Linux-6.5.0-25-generic-x86_64-with-glibc2.35)
# Sphinx version:   7.2.6
# Python version:   3.10.12 (CPython)
# Docutils version: 0.20.1
# Jinja2 version:   3.1.3
# Pygments version: 2.17.2

# Last messages:
#   admin-guide/README
#   
#   [2K
#   reading sources... [  2%]
#   admin-guide/abi
#   
#   [2K
#   reading sources... [  2%]
#   admin-guide/abi-obsolete
#   

# Loaded extensions:
#   sphinx.ext.mathjax (7.2.6)
#   alabaster (0.7.16)
#   sphinxcontrib.applehelp (1.0.8)
#   sphinxcontrib.devhelp (1.0.6)
#   sphinxcontrib.htmlhelp (2.0.5)
#   sphinxcontrib.serializinghtml (1.1.10)
#   sphinxcontrib.qthelp (1.0.7)
#   kerneldoc (1.0)
#   rstFlatTable (1.0)
#   kernel_include (1.0)
#   kfigure (1.0.0)
#   sphinx.ext.ifconfig (7.2.6)
#   automarkup (unknown version)
#   maintainers_include (1.0)
#   sphinx.ext.autosectionlabel (7.2.6)
#   kernel_abi (1.0)
#   kernel_feat (1.0)
#   translations (unknown version)

# Traceback:
Traceback (most recent call last):
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 420, in read
    self._read_serial(docnames)
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 441, in _read_serial
    self.read_doc(docname)
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 498, in read_doc
    publisher.publish()
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/sphinx/io.py", line 105, in read
    self.parse()
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/sphinx/parsers.py", line 81, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2355, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
  File "/home/hwhsu1231/Repo/linux/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
  File "/home/hwhsu1231/Repo/linux/Documentation/sphinx/kernel_abi.py", line 78, in run
    srctree = os.path.abspath(os.environ["srctree"])
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'srctree'


```

</details>

**Comment by picnixz** [comment]
The issue is with their sphinx extension: 

```
  File "/home/hwhsu1231/Repo/linux/Documentation/sphinx/kernel_abi.py", line 78, in run
    srctree = os.path.abspath(os.environ["srctree"])
```

For that one, you should report the issue to their repo instead.
