### ISSUE TITLE
Pngmath error handling code not compatible with Python 3

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1207]
Forwarded from [LP: #1184658](https://bugs.launchpad.net/bugs/1184658).

``` py3tb
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/pngmath.py", line 188, in html_visit_math
    fname, depth = render_math(self, '$'+node['latex']+'$')
  File "/usr/lib/python3/dist-packages/sphinx/ext/pngmath.py", line 134, in render_math
    '[stdout]\n&#37;s' &#37; (stderr, stdout))
sphinx.ext.pngmath.MathExtError: latex exited with error:
[stderr]
b''
[stdout]
b"This is pdfTeX, Version 3.1415926-2.4-1.40.13 (TeX Live 2012/Debian)\n restricted \\write18 enabled.\nentering extended mode\n(./math.tex\nLaTeX2e <2011/06/27>\nBabel <v3.8m> and hyphenation patterns for english, dumylang, nohyphenation, lo\naded.\n(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls\nDocument Class: article 2007/10/19 v1.4h Standard LaTeX document class\n(/usr/share/texlive/texmf-dist/tex/latex/base/size12.clo))\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty\n\n! LaTeX Error: File `utf8x.def' not found.\n\nType X to quit or <RETURN> to proceed,\nor enter new name. (Default extension: def)\n\nEnter file name: \n! Emergency stop.\n<read *> \n \nl.131 \\endinput\n ^^M\nNo pages of output.\nTranscript written on math.log.\n"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 292, in write
    self.write_doc(docname, doctree)
  File "/usr/lib/python3/dist-packages/sphinx/builders/html.py", line 419, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/lib/python3/dist-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python3/dist-packages/sphinx/writers/html.py", line 38, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 1627, in dispatch_visit
    return method(node)
  File "/usr/lib/python3/dist-packages/sphinx/ext/pngmath.py", line 190, in html_visit_math
    msg = str(str(exc), 'utf-8', 'replace')
TypeError: decoding str is not supported
```

Looks like 2to3 converts `unicode(str(exc), 'utf-8', 'replace')` to `str(str(exc), 'utf-8', 'replace')`, which won't work. I guess we can just use `str(exc)` here, but I'm not sure about that.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1207
- Originally reported by: Dmitry Shachnev
- Originally created at: 2013-07-06T18:14:50.796

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-12 15:26:30+00:00_

Now fixed with 5e2e49235c2b.
