### ISSUE TITLE
IOError: [Errno socket error] [Errno 11004] getaddrinfo failed

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1217]
When I run the "sphinx-build.py", to try change the dojo's rst doc, the console report such error:

```
#!python

The following provides some "live" examples:


None


dojo/on Root Function


None


[18/Jul/2013:23:16:37]  Not In Cache - Request and Cache: http://api/rpc/1.8/doj
o/on

Exception occurred:
  File "D:\Program Files\python\lib\socket.py", line 547, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno 11004] getaddrinfo failed.


And the  full traceback is :
# Sphinx version: 1.2b1
# Python version: 2.6.6
# Docutils version: 0.10 release
# Jinja2 version: 2.7
Traceback (most recent call last):
  File "E:\dojo_study\dojo_rst_parse_tools\birkenfeld-sphinx-379cbebe7b34\sphinx\cmdline.py", line 247, in main
    app.build(force_all, filenames)
  File "E:\dojo_study\dojo_rst_parse_tools\birkenfeld-sphinx-379cbebe7b34\sphinx\application.py", line 211, in build
    self.builder.build_update()
  File "E:\dojo_study\dojo_rst_parse_tools\birkenfeld-sphinx-379cbebe7b34\sphinx\builders\__init__.py", line 214, in build_update
    'out of date' &#37; len(to_build))
  File "E:\dojo_study\dojo_rst_parse_tools\birkenfeld-sphinx-379cbebe7b34\sphinx\builders\__init__.py", line 234, in build
    purple, length):
  File "E:\dojo_study\dojo_rst_parse_tools\birkenfeld-sphinx-379cbebe7b34\sphinx\builders\__init__.py", line 134, in status_iterator
    for item in iterable:
  File "E:\dojo_study\dojo_rst_parse_tools\birkenfeld-sphinx-379cbebe7b34\sphinx\environment.py", line 469, in update_generator
    self.read_doc(docname, app=app)
  File "E:\dojo_study\dojo_rst_parse_tools\birkenfeld-sphinx-379cbebe7b34\sphinx\environment.py", line 617, in read_doc
    pub.publish()
  File "D:\Program Files\python\lib\site-packages\docutils\core.py", line 219, in publish
    self.settings)
  File "D:\Program Files\python\lib\site-packages\docutils\readers\__init__.py", line 73, in read
    self.parse()
  File "D:\Program Files\python\lib\site-packages\docutils\readers\__init__.py", line 79, in parse
    self.parser.parse(self.input, document)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\__init__.py", line 173, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 176, in run
    input_source=document['source'])
  File "D:\Program Files\python\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "D:\Program Files\python\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 2957, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 333, in section
    self.new_subsection(title, lineno, messages)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 401, in new_subsection
    node=section_node, match_titles=True)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 288, in nested_parse
    node=node, match_titles=match_titles)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 201, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "D:\Program Files\python\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "D:\Program Files\python\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 2722, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 333, in section
    self.new_subsection(title, lineno, messages)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 401, in new_subsection
    node=section_node, match_titles=True)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 288, in nested_parse
    node=node, match_titles=match_titles)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 201, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "D:\Program Files\python\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "D:\Program Files\python\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 2295, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 2307, in explicit_construct
    return method(self, expmatch)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 2050, in directive
    directive_class, match, type_name, option_presets)
  File "D:\Program Files\python\lib\site-packages\docutils\parsers\rst\states.py", line 2099, in run_directive
    result = directive_instance.run()
  File "E:\dojo_study\dojo_rst_parse_tools\rstwiki-master\src\dojo.py", line 258, in run
    data = urllib.urlopen(target_url).read()
  File "D:\Program Files\python\lib\urllib.py", line 86, in urlopen
    return opener.open(url)
  File "D:\Program Files\python\lib\urllib.py", line 207, in open
    return getattr(self, name)(url)
  File "D:\Program Files\python\lib\urllib.py", line 346, in open_http
    h.endheaders()
  File "D:\Program Files\python\lib\httplib.py", line 908, in endheaders
    self._send_output()
  File "D:\Program Files\python\lib\httplib.py", line 780, in _send_output
    self.send(msg)
  File "D:\Program Files\python\lib\httplib.py", line 739, in send
    self.connect()
  File "D:\Program Files\python\lib\httplib.py", line 720, in connect
    self.timeout)
  File "D:\Program Files\python\lib\socket.py", line 547, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno 11004] getaddrinfo failed
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1217
- Originally reported by: Anonymous
- Originally created at: 2013-07-18T17:49:15.731

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-07-18 22:38:39+00:00_

I think this issue was caused by `dojo_rst_parse_tools`. The dojo tool(?) accessed to  `http://api/rpc/1.8/dojo/on` but `api`'s IP address was not resolved. Please contact to the tool's author.
