### ISSUE TITLE
Could not import extension sphinx.builders.changes: no module named tomli

### ISSUE THREAD

**Issue by sethrj** [sphinx-doc/sphinx#12291]
### Describe the bug

After a *very* recent update, sometime around Tue Apr 16 23:00:00 UTC 2024, the default GitHub Actions `ubuntu-latest` pip switched from using Sphinx-7.2.6 to Sphinx-7.3.0 . ([Successful job before](https://github.com/celeritas-project/celeritas/actions/runs/8713465677/job/23901909851), [failing job after](https://github.com/celeritas-project/celeritas/actions/runs/8713787573/job/23902848003)).

This results in a failure:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/sphinx/registry.py", line 453, in load_extension
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/sphinx/registry.py", line 453, in load_extension
    mod = import_module(extname)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/sphinx/builders/changes.py", line 13, in <module>
    from sphinx.theming import HTMLThemeFactory
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/sphinx/theming.py", line 27, in <module>
    import tomli as tomllib
ModuleNotFoundError: No module named 'tomli'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/sphinx/application.py", line 225, in __init__
    self.setup_extension(extension)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/sphinx/application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/sphinx/registry.py", line 456, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinx.builders.changes (exception: No module named 'tomli')

Extension error:
Could not import extension sphinx.builders.changes (exception: No module named 'tomli')
    mod = import_module(extname)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/sphinx/builders/changes.py", line 13, in <module>
    from sphinx.theming import HTMLThemeFactory
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/sphinx/theming.py", line 27, in <module>
    import tomli as tomllib
ModuleNotFoundError: No module named 'tomli'
```

### How to Reproduce

https://github.com/sethrj/celeritas/actions/runs/8714034944/job/23903541984

### Environment Information

```text
Platform:              linux; (Linux-6.5.0-1017-azure-x86_64-with-glibc2.35)
Python version:        3.10.14 (main, Mar 20 2024, 15:15:25) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        7.3.0
Docutils version:      0.21.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

**Comment by agjohnson** [comment]
We're also noticing this on projects on Read the Docs that are installing Sphinx unpinned.

**Comment by AA-Turner** [comment]
Fixed in 8a944ac.

A

**Comment by sethrj** [comment]
Thanks! Out of curiosity, how did this not get caught in the Sphinx CI? It looks like you're testing Python 3.10.

**Comment by AA-Turner** [comment]
**Sphinx 7.3.1** has been released.

A

**Comment by AA-Turner** [comment]
> Thanks! Out of curiosity, how did this not get caught in the Sphinx CI? It looks like you're testing Python 3.10.

It looks like ``pytest`` was masking the failure, as it itself requires ``tomli`` in exactly the same scenarios:

https://github.com/pytest-dev/pytest/blob/58844247f7ae4a7a213a73c8af2462253b3d8fc7/pyproject.toml#L47

Thank you for the quick bug-report, and sorry to cause unneeded hassle.

A

**Comment by sethrj** [comment]
Gotcha, thanks for the ridiculously quick fix!
