### ISSUE TITLE
docs fail to build when under Python 3

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1231]
Error message:

```
$ make html
python ../sphinx-build.py -b html -d _build/doctrees    . _build/html
Traceback (most recent call last):
  File "../sphinx-build.py", line 15, in <module>
    sys.exit(main(sys.argv))
  File "/home/tshepang/projects/sphinx/sphinx/__init__.py", line 45, in main
    from sphinx import cmdline
  File "/home/tshepang/projects/sphinx/sphinx/cmdline.py", line 103
    print 'Sphinx (sphinx-build) &#37;s' &#37;  __version__
                                   ^
SyntaxError: invalid syntax
make: *** [html] Error 1
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1231
- Originally reported by: Tshepang Lekhonkhobe
- Originally created at: 2013-08-08T08:25:56.207

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-08-17 13:14:49+00:00_

Sphinx **raw** source code is not support Python3. The source code will be converted for python3 at installation time.

If you want to build the Sphinx documentation with python3, please install Sphinx and make with installed sphinx-build command as like as:

```
$ python setup.py install
$ cd doc
$ make -e SPHINXBUILD=sphinx-build html
```
