### ISSUE TITLE
When compiling linux kernel(drm-tis), failed at module `docutils.nodes` for no attribute ‘reprunicode’

### ISSUE THREAD

**Issue by Ramen-LadyHKG** [sphinx-doc/sphinx#12340]
### Describe the bug

```
  PARSE   include/uapi/linux/lirc.h
Using alabaster theme

Sphinx parallel build error:
AttributeError: module 'docutils.nodes' has no attribute 'reprunicode'
make[2]: *** [Documentation/Makefile:118: htmldocs] Error 2
make[1]: *** [/home/curie/.cache/yay/linux-drm-tip-git/src/linux-drm-tip-git/Makefile:1703: htmldocs] Error 2
make: *** [Makefile:240: __sub-make] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: linux-drm-tip-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
linux-drm-tip-git - exit status 4

```

### How to Reproduce

 I am using the AUR package [https://aur.archlinux.org/packages/linux-drm-tip-git](https://aur.archlinux.org/packages/linux-drm-tip-git)

and failed at this 
[Makefile.txt](https://github.com/sphinx-doc/sphinx/files/15156226/Makefile.txt)

### Environment Information

```text
Platform:              linux; (Linux-6.8.6-arch1-1-surface-x86_64-with-glibc2.39)
Python version:        3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417])
Python implementation: CPython
Sphinx version:        7.3.7
Docutils version:      0.21.2
Jinja2 version:        3.1.3
```

**Comment by AA-Turner** [comment]
Can you try with Docutils 0.20.* or 0.19.*? 

A

**Comment by Ramen-LadyHKG** [comment]
> Docutils

sure
but I'm not sure how to do this. My docutils is installed in a python virtual environment.

What I don't is, if the kernel compiling script is using that library or compiling its own.

HENCE,
I've to look into the makepkg, make config

**Comment by kanakshilledar** [comment]
I am also getting the same error while duing `make htmldocs` for the linux kernel. 
Any idea on how can I solve this error?

`conf.py` of linux kernel looks like this (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/Documentation/conf.py?h=v6.8.8)

**Comment by kanakshilledar** [comment]
Yes definitely you can create the patch and send it to the mailing list.
 Follow [this article](https://nickdesaulniers.github.io/blog/2017/05/16/submitting-your-first-patch-to-the-linux-kernel-and-responding-to-feedback/) on a high level understanding of the process and steps. If you want more detailed one you can refer the [indepth guide](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/Documentation/process/submitting-patches.rst?h=v6.8.8)

**Comment by Ramen-LadyHKG** [comment]
Got some new errors

```
 BTF [M] net/qrtr/qrtr-smd.ko                                                                                                                                                                                          [10/1991]
  BTF [M] net/qrtr/qrtr.ko                                                                                                                                                                                                       
  BTF [M] net/hsr/hsr.ko                                                                                                                                                                                                         
  BTF [M] net/qrtr/qrtr-mhi.ko                                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                               
  File "/home/curie/.cache/yay/linux-drm-tip-git/src/linux-drm-tip-git/./tools/net/ynl/ynl-gen-rst.py", line 26, in <module>                                                                                                     
    import yaml                                                                                                                                                                                                                  
ModuleNotFoundError: No module named 'yaml'                                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                                               
  File "/home/curie/.cache/yay/linux-drm-tip-git/src/linux-drm-tip-git/./tools/net/ynl/ynl-gen-rst.py", line 26, in <module>                                                                                                     
  File "/home/curie/.cache/yay/linux-drm-tip-git/src/linux-drm-tip-git/./tools/net/ynl/ynl-gen-rst.py", line 26, in <module>                                                                                                     
  File "/home/curie/.cache/yay/linux-drm-tip-git/src/linux-drm-tip-git/./tools/net/ynl/ynl-gen-rst.py", line 26, in <module>                                                                                                     
    import yaml                                                                                                 
    import yaml                                                                                                 
    import yaml                                                                                                 
ModuleNotFoundError: No module named 'yaml'                                                                     
ModuleNotFoundError: No module named 'yaml'                                                                     
ModuleNotFoundError: No module named 'yaml'                                                                     
Traceback (most recent call last):                                                                              
  File "/home/curie/.cache/yay/linux-drm-tip-git/src/linux-drm-tip-git/./tools/net/ynl/ynl-gen-rst.py", line 26, in <module>                                                                                                     
    import yaml                                                                                                 
ModuleNotFoundError: No module named 'yaml'                                                                     
Traceback (most recent call last):                                                                              
  File "/home/curie/.cache/yay/linux-drm-tip-git/src/linux-drm-tip-git/./tools/net/ynl/ynl-gen-rst.py", line 26, in <module>                                                                                                     
    import yaml                                                                                                 
ModuleNotFoundError: No module named 'yaml'                                                                     
Traceback (most recent call last):                                                                              
Traceback (most recent call last):                                                                              
  File "/home/curie/.cache/yay/linux-drm-tip-git/src/linux-drm-tip-git/./tools/net/ynl/ynl-gen-rst.py", line 26, in <module>                                                                                                     
    import yaml                                                                                                 
  File "/home/curie/.cache/yay/linux-drm-tip-git/src/linux-drm-tip-git/./tools/net/ynl/ynl-gen-rst.py", line 26, in <module>                                                                                                     
    import yaml                                                                                                 
ModuleNotFoundError: No module named 'yaml'                                                                     
Traceback (most recent call last):                                                                              
  File "/home/curie/.cache/yay/linux-drm-tip-git/src/linux-drm-tip-git/./tools/net/ynl/ynl-gen-rst.py", line 26, in <module>                                                                                                     
ModuleNotFoundError: No module named 'yaml'                                                                     
Traceback (most recent call last):                                                                              
  File "/home/curie/.cache/yay/linux-drm-tip-git/src/linux-drm-tip-git/./tools/net/ynl/ynl-gen-rst.py", line 26, in <module>                                                                                                     
    import yaml                                                                                                 
ModuleNotFoundError: No module named 'yaml'                                                                     
    import yaml                                                                                                 
ModuleNotFoundError: No module named 'yaml'                                                                     
make[2]: *** [Documentation/Makefile:112: Documentation/networking/netlink_spec/mptcp_pm.rst] Error 1                                                                                                                            
make[2]: *** Waiting for unfinished jobs....                                                                    
make[2]: *** [Documentation/Makefile:112: Documentation/networking/netlink_spec/dpll.rst] Error 1                                                                                                                                
make[2]: *** [Documentation/Makefile:112: Documentation/networking/netlink_spec/fou.rst] Error 1                                                                                                                                 
make[2]: *** [Documentation/Makefile:112: Documentation/networking/netlink_spec/nfsd.rst] Error 1                                                                                                                                
make[2]: *** [Documentation/Makefile:112: Documentation/networking/netlink_spec/nlctrl.rst] Error 1                                                                                                                              
make[2]: *** [Documentation/Makefile:112: Documentation/networking/netlink_spec/ovs_datapath.rst] Error 1                                                                                                                        
make[2]: *** [Documentation/Makefile:112: Documentation/networking/netlink_spec/netdev.rst] Error 1                                                                                                                              
make[2]: *** [Documentation/Makefile:112: Documentation/networking/netlink_spec/ethtool.rst] Error 1                                                                                                                             
make[2]: *** [Documentation/Makefile:112: Documentation/networking/netlink_spec/handshake.rst] Error 1                                                                                                                           
make[2]: *** [Documentation/Makefile:112: Documentation/networking/netlink_spec/devlink.rst] Error 1                                                                                                                             
make[1]: *** [/home/curie/.cache/yay/linux-drm-tip-git/src/linux-drm-tip-git/Makefile:1703: htmldocs] Error 2                                                                                                                    make: *** [Makefile:240: __sub-make] Error 2                                                                    
==> ERROR: A failure occurred in build().                                                                       
    Aborting...                                                                                                 
 -> error making: linux-drm-tip-git-exit status 4                                                               
 -> Failed to install the following packages. Manual intervention is required:                                                                                                                                                   
linux-drm-tip-git - exit status 4
```

**Comment by kanakshilledar** [comment]
I was able to build the documentation properly with the changes suggested by @chrisjsewell in the above patch.
Can you check if you have the `yaml` module installed. Try `pip3 install pyyaml`. Hope this helps

**Comment by chrisjsewell** [comment]
Thanks @kanakshilledar, I got a bit stalled trying to build the docs on my Mac, which wasn't as trivial as I'd hoped. But I think I'll just send out the patch tomorrow, now that you've confirmed it works 😄

**Comment by tleb** [comment]
For reference, Akira Yokosawa sent a [patch](https://lore.kernel.org/linux-doc/faf5fa45-2a9d-4573-9d2e-3930bdc1ed65@gmail.com/) on May 1th.  
[It got queued](https://lore.kernel.org/linux-doc/87wmoc6w5a.fsf@meer.lwn.net/) by Jonathan Corbet on May 2nd, meaning this issue can probably be closed. It'll be backported to stable kernel releases as well.

**Comment by Ramen-LadyHKG** [comment]
> For reference, Akira Yokosawa sent a [patch](https://lore.kernel.org/linux-doc/faf5fa45-2a9d-4573-9d2e-3930bdc1ed65@gmail.com/) on May 1th. [It got queued](https://lore.kernel.org/linux-doc/87wmoc6w5a.fsf@meer.lwn.net/) by Jonathan Corbet on May 2nd, meaning this issue can probably be closed. It'll be backported to stable kernel releases as well.

I fixed on my side just remove kernel_doc dependency on make config.

but I agree, just close it
