### ISSUE TITLE
TOWER_HOST=https://awx.example.org TOWER_USERNAME=example TOWER_PASSWORD=secret make clean html

### ISSUE THREAD

**Issue by bacemhlabba** [sphinx-doc/sphinx#12355]
### Describe the bug

````

root@inf01-admin-awx-cpu01:/home/bacem_hlabba/awx/awxkit/awxkit/cli/docs# cat /tmp/sphinx-err-1mlhd478.log
# Platform:         linux; (Linux-5.15.0-1058-gcp-x86_64-with-glibc2.29)
# Sphinx version:   7.1.2
# Python version:   3.8.10 (CPython)
# Docutils version: 0.20.1
# Jinja2 version:   3.1.4
# Pygments version: 2.18.0

# Last messages:


# Loaded extensions:


# Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f3802fc99a0>: Failed to resolve 'sakietna.tn' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sakietna.tn', port=443): Max retries exceeded with url: /api/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3802fc99a0>: Failed to resolve 'sakietna.tn' ([Errno -2] Name or service not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sphinx/cmd/build.py", line 285, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/local/lib/python3.8/dist-packages/sphinx/application.py", line 229, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python3.8/dist-packages/sphinx/application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/lib/python3.8/dist-packages/sphinx/registry.py", line 441, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/awxkit/cli/sphinx.py", line 80, in <module>
    parser = render()
  File "/usr/local/lib/python3.8/dist-packages/awxkit/cli/sphinx.py", line 56, in render
    cli.authenticate()
  File "/usr/local/lib/python3.8/dist-packages/awxkit/cli/client.py", line 95, in authenticate
    self.root.load_session().get()
  File "/usr/local/lib/python3.8/dist-packages/awxkit/api/pages/base.py", line 183, in load_session
    username=username or default_cred.username, password=password or default_cred.password, **self.connection.get_session_requirements()
  File "/usr/local/lib/python3.8/dist-packages/awxkit/api/client.py", line 47, in get_session_requirements
    self.get(config.api_base_path)  # this causes a cookie w/ the CSRF token to be set
  File "/usr/local/lib/python3.8/dist-packages/awxkit/api/client.py", line 113, in get
    return self.request(relative_endpoint, method='get', query_parameters=query_parameters, headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/awxkit/api/client.py", line 104, in request
    raise err
  File "/usr/local/lib/python3.8/dist-packages/awxkit/api/client.py", line 100, in request
    response = session_request_method(url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sakietna.tn', port=443): Max retries exceeded with url: /api/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3802fc99a0>: Failed to resolve 'sakietna.tn' ([Errno -2] Name or service not known)"))

root@inf01-admin-awx-cpu01:/home/bacem_hlabba/awx/awxkit/awxkit/cli/docs# ~ TOWER_HOST=https://awx.example.org TOWER_USERNAME=example TOWER_PASSWORD=secret make clean html
bash: /root: Is a directory
root@inf01-admin-awx-cpu01:/home/bacem_hlabba/awx/awxkit/awxkit/cli/docs# 
root@inf01-admin-awx-cpu01:/home/bacem_hlabba/awx/awxkit/awxkit/cli/docs# ~ TOWER_HOST=https://awx.example.org TOWER_USERNAME=example TOWER_PASSWORD=secret make clean html
bash: /root: Is a directory
root@inf01-admin-awx-cpu01:/home/bacem_hlabba/awx/awxkit/awxkit/cli/docs# TOWER_HOST=https://awx.example.org TOWER_USERNAME=example TOWER_PASSWORD=secret make clean html
Running Sphinx v7.1.2

Exception occurred:
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='awx.example.org', port=443): Max retries exceeded with url: /api/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fc33116e9a0>: Failed to resolve 'awx.example.org' ([Errno -2] Name or service not known)"))
The full traceback has been saved in /tmp/sphinx-err-n01hopil.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

````

### How to Reproduce

````

root@inf01-admin-awx-cpu01:/home/bacem_hlabba/awx/awxkit/awxkit/cli/docs# cat /tmp/sphinx-err-1mlhd478.log
# Platform:         linux; (Linux-5.15.0-1058-gcp-x86_64-with-glibc2.29)
# Sphinx version:   7.1.2
# Python version:   3.8.10 (CPython)
# Docutils version: 0.20.1
# Jinja2 version:   3.1.4
# Pygments version: 2.18.0

# Last messages:


# Loaded extensions:


# Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f3802fc99a0>: Failed to resolve 'sakietna.tn' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sakietna.tn', port=443): Max retries exceeded with url: /api/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3802fc99a0>: Failed to resolve 'sakietna.tn' ([Errno -2] Name or service not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sphinx/cmd/build.py", line 285, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/local/lib/python3.8/dist-packages/sphinx/application.py", line 229, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python3.8/dist-packages/sphinx/application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/lib/python3.8/dist-packages/sphinx/registry.py", line 441, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/awxkit/cli/sphinx.py", line 80, in <module>
    parser = render()
  File "/usr/local/lib/python3.8/dist-packages/awxkit/cli/sphinx.py", line 56, in render
    cli.authenticate()
  File "/usr/local/lib/python3.8/dist-packages/awxkit/cli/client.py", line 95, in authenticate
    self.root.load_session().get()
  File "/usr/local/lib/python3.8/dist-packages/awxkit/api/pages/base.py", line 183, in load_session
    username=username or default_cred.username, password=password or default_cred.password, **self.connection.get_session_requirements()
  File "/usr/local/lib/python3.8/dist-packages/awxkit/api/client.py", line 47, in get_session_requirements
    self.get(config.api_base_path)  # this causes a cookie w/ the CSRF token to be set
  File "/usr/local/lib/python3.8/dist-packages/awxkit/api/client.py", line 113, in get
    return self.request(relative_endpoint, method='get', query_parameters=query_parameters, headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/awxkit/api/client.py", line 104, in request
    raise err
  File "/usr/local/lib/python3.8/dist-packages/awxkit/api/client.py", line 100, in request
    response = session_request_method(url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sakietna.tn', port=443): Max retries exceeded with url: /api/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3802fc99a0>: Failed to resolve 'sakietna.tn' ([Errno -2] Name or service not known)"))

root@inf01-admin-awx-cpu01:/home/bacem_hlabba/awx/awxkit/awxkit/cli/docs# ~ TOWER_HOST=https://awx.example.org TOWER_USERNAME=example TOWER_PASSWORD=secret make clean html
bash: /root: Is a directory
root@inf01-admin-awx-cpu01:/home/bacem_hlabba/awx/awxkit/awxkit/cli/docs# 
root@inf01-admin-awx-cpu01:/home/bacem_hlabba/awx/awxkit/awxkit/cli/docs# ~ TOWER_HOST=https://awx.example.org TOWER_USERNAME=example TOWER_PASSWORD=secret make clean html
bash: /root: Is a directory
root@inf01-admin-awx-cpu01:/home/bacem_hlabba/awx/awxkit/awxkit/cli/docs# TOWER_HOST=https://awx.example.org TOWER_USERNAME=example TOWER_PASSWORD=secret make clean html
Running Sphinx v7.1.2

Exception occurred:
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='awx.example.org', port=443): Max retries exceeded with url: /api/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fc33116e9a0>: Failed to resolve 'awx.example.org' ([Errno -2] Name or service not known)"))
The full traceback has been saved in /tmp/sphinx-err-n01hopil.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

````

### Environment Information

```text
Package                       Version
----------------------------- --------------------
alabaster                     0.7.13
attrs                         19.3.0
Automat                       0.8.0
awxkit                        24.3.1
Babel                         2.15.0
bcrypt                        4.1.3
blinker                       1.4
cachetools                    5.3.3
certifi                       2019.11.28
cffi                          1.16.0
chardet                       5.2.0
charset-normalizer            3.3.2
Click                         7.0
cloud-init                    24.1.3
colorama                      0.4.6
command-not-found             0.3
configobj                     5.0.6
constantly                    15.1.0
cryptography                  42.0.6
dbus-python                   1.2.16
distlib                       0.3.8
distro                        1.9.0
distro-info                   0.23+ubuntu1.1
docker                        7.0.0
docker-compose                1.29.2
dockerpty                     0.4.1
docopt                        0.6.2
docutils                      0.20.1
entrypoints                   0.3
filelock                      3.14.0
httplib2                      0.14.0
hyperlink                     19.0.0
idna                          2.8
imagesize                     1.4.1
importlib_metadata            7.1.0
incremental                   16.10.1
Jinja2                        3.1.4
jsonpatch                     1.22
jsonpointer                   2.0
jsonschema                    3.2.0
keyring                       18.0.1
language-selector             0.1
launchpadlib                  1.10.13
lazr.restfulclient            0.14.2
lazr.uri                      1.0.3
MarkupSafe                    2.1.5
more-itertools                4.2.0
netifaces                     0.10.4
oauthlib                      3.1.0
packaging                     24.0
paramiko                      3.4.0
pexpect                       4.6.0
pip                           24.0
platformdirs                  4.2.1
pluggy                        1.5.0
pyasn1                        0.4.2
pyasn1-modules                0.2.1
pycparser                     2.22
Pygments                      2.18.0
PyGObject                     3.36.0
PyHamcrest                    1.9.0
PyJWT                         1.7.1
pymacaroons                   0.13.0
PyNaCl                        1.5.0
pyOpenSSL                     19.0.0
pyproject-api                 1.6.1
pyrsistent                    0.15.5
pyserial                      3.4
python-apt                    2.0.1+ubuntu0.20.4.1
python-debian                 0.1.36+ubuntu1.1
python-dotenv                 0.21.1
pytz                          2024.1
PyYAML                        5.3.1
requests                      2.31.0
requests-unixsocket           0.2.0
SecretStorage                 2.3.1
service-identity              18.1.0
setuptools                    45.2.0
simplejson                    3.16.0
six                           1.14.0
snowballstemmer               2.2.0
sos                           4.5.6
Sphinx                        7.1.2
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-autoprogram     0.1.9
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
ssh-import-id                 5.10
systemd-python                234
texttable                     1.7.0
tomli                         2.0.1
tox                           4.15.0
Twisted                       18.9.0
ubuntu-pro-client             8001
ufw                           0.36
unattended-upgrades           0.1
urllib3                       2.2.1
virtualenv                    20.26.1
wadllib                       1.3.3
websocket-client              0.59.0
wheel                         0.34.2
zipp                          1.0.0
zope.interface                4.7.1
```

**Comment by AA-Turner** [comment]
I don't know what problem you're reporting here, but it seems you're using Python 3.8 and Sphinx 7.1, neither of which we support any more.

A
