### ISSUE TITLE
7.3.7: missing `defusedxml` install time dependency

### ISSUE THREAD

**Issue by kloczek** [sphinx-doc/sphinx#12370]
### Describe the bug

On testing `sphinx-autodoc-typehints` 2.1.0 I found that this module test suite fails because sphinx code uses `defusedxml`
```cnsole
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-sphinx-autodoc-typehints-2.1.0-2.fc37.x86_64/usr/lib64/python3.10/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-sphinx-autodoc-typehints-2.1.0-2.fc37.x86_64/usr/lib/python3.10/site-packages
+ /usr/bin/pytest -ra -m 'not network' --deselect 'tests/test_sphinx_autodoc_typehints.py::test_always_document_param_types[doc_param_type]'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 856, in import_plugin
    __import__(importspec)
  File "/usr/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/usr/lib/python3.10/site-packages/sphinx/testing/fixtures.py", line 14, in <module>
    from sphinx.testing.util import SphinxTestApp, SphinxTestAppWrapperForSkipBuilding
  File "/usr/lib/python3.10/site-packages/sphinx/testing/util.py", line 14, in <module>
    from defusedxml.ElementTree import parse as xml_parse
ModuleNotFoundError: No module named 'defusedxml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 197, in console_main
    code = main()
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 155, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 337, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3.10/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/python3.10/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.10/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
    config = yield
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1143, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1492, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1396, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/usr/lib/python3.10/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/lib/python3.10/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.10/site-packages/_pytest/warnings.py", line 150, in pytest_load_initial_conftests
    return (yield)
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/usr/lib/python3.10/site-packages/_pytest/capture.py", line 153, in pytest_load_initial_conftests
    yield
  File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1221, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 579, in _set_initial_conftests
    self._try_load_conftest(
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 617, in _try_load_conftest
    self._loadconftestmodules(
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 657, in _loadconftestmodules
    mod = self._importconftest(
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 733, in _importconftest
    self.consider_conftest(mod, registration_name=conftestpath_plugin_name)
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 814, in consider_conftest
    self.register(conftestmodule, name=registration_name)
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 510, in register
    self.consider_module(plugin)
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 822, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 829, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 858, in import_plugin
    raise ImportError(
  File "/usr/lib/python3.10/site-packages/_pytest/config/__init__.py", line 856, in import_plugin
    __import__(importspec)
  File "/usr/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/usr/lib/python3.10/site-packages/sphinx/testing/fixtures.py", line 14, in <module>
    from sphinx.testing.util import SphinxTestApp, SphinxTestAppWrapperForSkipBuilding
  File "/usr/lib/python3.10/site-packages/sphinx/testing/util.py", line 14, in <module>
    from defusedxml.ElementTree import parse as xml_parse
ImportError: Error importing plugin "sphinx.testing.fixtures": No module named 'defusedxml'
```

### How to Reproduce

- install sphinx
- clone https://github.com/tox-dev/sphinx-autodoc-typehints/
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix> using `installer` module
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

### Environment Information

```text
Package                       Version
----------------------------- -----------
alabaster                     0.7.16
attrs                         23.2.0
Babel                         2.15.0
build                         1.2.1
certifi                       2023.7.22
charset-normalizer            3.3.2
docutils                      0.20.1
exceptiongroup                1.1.3
hatch-vcs                     0.4.0
hatchling                     1.24.0
idna                          3.7
imagesize                     1.4.1
importlib_metadata            7.1.0
iniconfig                     2.0.0
installer                     0.7.0
Jinja2                        3.1.4
jsonschema                    4.20.0
jsonschema-specifications     2023.12.1
libdnf                        0.73.1
MarkupSafe                    2.1.5
packaging                     24.0
pathspec                      0.12.1
pluggy                        1.4.0
Pygments                      2.18.0
pyproject_hooks               1.0.0
pytest                        8.1.1
python-dateutil               2.9.0.post0
referencing                   0.32.0
requests                      2.31.0
rpds-py                       0.18.1
setuptools                    69.4.0
setuptools-scm                8.1.0
snowballstemmer               2.2.0
Sphinx                        7.3.7
sphinxcontrib-applehelp       1.0.8
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
sphobjinv                     2.3.1
tokenize_rt                   5.2.0
tomli                         2.0.1
trove-classifiers             2024.4.16
urllib3                       2.2.1
wheel                         0.43.0
zipp                          3.18.1
```

**Comment by chrisjsewell** [comment]
Already fixed

**Comment by kloczek** [comment]
Are you sure? 🤔 
In https://github.com/sphinx-doc/sphinx/blob/master/pyproject.toml In `dependencies` list I don't see `defusedxml`.
That module is only listed in `tests`.
