### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not StringList

### ISSUE THREAD

**Issue by Carreau** [sphinx-doc/sphinx#12429]
### Describe the bug

Changing the default role of scipy to `py:obj`, sphinx crashes on some docutils node when trying to resolve them.

```
scipy-source $ python dev.py doc
`<...>`
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/cmd/build.py", line 337, in build_main
    app.build(args.force_all, args.filenames)
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/application.py", line 376, in build
    self.builder.build_update()
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/builders/__init__.py", line 362, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/builders/__init__.py", line 571, in write
    self._write_serial(sorted(docnames))
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/builders/__init__.py", line 574, in _write_serial
    with logging.pending_warnings():
  File "/Users/bussonniermatthias/miniconda3/envs/scipy-dev/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/util/logging.py", line 273, in pending_warnings
    memhandler.flushTo(logger)
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/util/logging.py", line 238, in flushTo
    logger.handle(record)
  File "/Users/bussonniermatthias/miniconda3/envs/scipy-dev/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/Users/bussonniermatthias/miniconda3/envs/scipy-dev/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/Users/bussonniermatthias/miniconda3/envs/scipy-dev/lib/python3.12/logging/__init__.py", line 1022, in handle
    rv = self.filter(record)
         ^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/miniconda3/envs/scipy-dev/lib/python3.12/logging/__init__.py", line 858, in filter
    result = f.filter(record)
             ^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/util/logging.py", line 573, in filter
    ret = super().filter(record)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/util/logging.py", line 554, in filter
    record.location = get_node_location(location)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/util/logging.py", line 593, in get_node_location
    source = abspath(source)
             ^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 418, in abspath
TypeError: expected str, bytes or os.PathLike object, not StringList
```

### How to Reproduce

I have difficulty making a minimal example, but trying to get more info. Will update if I have smaller one that [building scipy docs](https://docs.scipy.org/doc/scipy/dev/contributor/rendering_documentation.html#rendering-documentation-locally-with-sphinx) with the following patch:
```
$ git diff
diff --git a/doc/source/conf.py b/doc/source/conf.py
index ba383f566e..477a1cae04 100644
--- a/doc/source/conf.py
+++ b/doc/source/conf.py
@@ -97,7 +97,7 @@ today_fmt = '%B %d, %Y'
 #unused_docs = []

 # The reST default role (used for this markup: `text`) to use for all documents.
-default_role = "autolink"
+default_role = "py:obj"

 # List of directories, relative to source directories, that shouldn't be searched
 # for source files.
```

### Environment Information

```text
Sphinx/docutils main + local debug info to try to narrow things down. 




Platform:              darwin; (macOS-13.4-arm64-arm-64bit)
Python version:        3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:35:20) [Clang 16.0.6 ])
Python implementation: CPython
Sphinx version:        7.4.0+/4fbd3682d
Docutils version:      0.22b.dev
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```

### Additional context

As to where the node is set to a non-str/bytes/path:

```
Traceback (most recent call last):
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/cmd/build.py", line 337, in build_main
    app.build(args.force_all, args.filenames)
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/application.py", line 376, in build
    self.builder.build_update()
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/builders/__init__.py", line 419, in read
    self._read_serial(docnames)
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/builders/__init__.py", line 440, in _read_serial
    self.read_doc(docname)
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/builders/__init__.py", line 498, in read_doc
    publisher.publish()
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/io.py", line 107, in read
    self.parse()
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/parsers.py", line 83, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/parsers/rst/states.py", line 2790, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
                   ^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/parsers/rst/states.py", line 2357, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/parsers/rst/states.py", line 2369, in explicit_construct
    return method(self, expmatch)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/parsers/rst/states.py", line 2106, in directive
    return self.run_directive(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/parsers/rst/states.py", line 2156, in run_directive
    result = directive_instance.run()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/domains/__init__.py", line 289, in run
    return super().run()
           ^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/scipy/doc/source/scipyoptdoc.py", line 153, in run
    return base_directive.run(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/directives/__init__.py", line 285, in run
    nested_parse_with_titles(self.state, self.content, contentnode, self.content_offset)
  File "/Users/bussonniermatthias/dev/sphinx/sphinx/util/nodes.py", line 341, in nested_parse_with_titles
    return state.nested_parse(content, content_offset, node, match_titles=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/parsers/rst/states.py", line 2804, in text
    paragraph, literalnext = self.paragraph(lines, startline)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/parsers/rst/states.py", line 418, in paragraph
    p.source, p.line = self.state_machine.get_source_and_line(lineno)
    ^^^^^^^^
  File "/Users/bussonniermatthias/dev/docutils/docutils/docutils/nodes.py", line 61, in source
    assert not isinstance(value, StringList), breakpoint()
```

**Comment by picnixz** [comment]
Can you try using another docutils version? it might be the issue (I see that you are using 0.22b.dev but I'm not sure how it was changed).

By the way, I would prefer closing the issue for now, until you give me a MWE because it's something that I won't be able to investigate easily (I don't even know where to start since I don't even know what kind of node is causing the issue).

**Comment by Carreau** [comment]
Ok, i'll close for now (so that I can reopen), and will try with other docutils.

**Comment by Carreau** [comment]
BTW, when you close I can't reopen, I'll need to open a new issue (unless you reopen and I close in which case I can reopen).

**Comment by picnixz** [comment]
@Carreau You can close it now (I did not know that you were not able to reopen it!)

**Comment by Carreau** [comment]
> (I did not know that you were not able to reopen it!). So there are many issues that I closed (and said "feel free to reopen") but actually, people were never free to do it!

Yeah, that also surprised me as a maintainer, i think submitter used to be able to do so, but I guess there was some disputes with maintainer closing and users reopening in loops, so at some point the default changes to "once closed  by a maintainer, can't be reopened by users".

**Comment by Carreau** [comment]
Ok, I think that is because some directive was doing:

```
self.content = ViewList(new_lines, self.content.parent)
```
(which set the source of self.content.parent)

```
self.content = StringList(new_lines, parent=self.content.parent)
```

(where `new_lines` is derived from `self.content`). I'm not 100% sure if this is 100% correct as the _source_ is indeed self.content.parent, but I can see how it can be confusing to have a source to not be a str/bytes/path.

Keeping closed unless upstream refuse my patch.

**Comment by picnixz** [comment]
Mmh, that may either be an issue in SciPy *or* in docutils where they do not consider the ViewList case.
