### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1245]
```
Exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 247, in main
    app.build(force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 211, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 211, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/gettext.py", line 150, in build
    self._extract_from_template()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/gettext.py", line 145, in _extract_from_template
    for line, meth, msg in extract_translations(context):
  File "/usr/local/lib/python2.7/dist-packages/jinja2/ext.py", line 212, in _extract
    source = self.environment.parse(source)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 452, in parse
    return self._parse(source, name, filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 459, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python2.7/dist-packages/jinja2/parser.py", line 32, in __init__
    self.stream = environment._tokenize(source, name, filename, state)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 490, in _tokenize
    source = self.preprocess(source, name, filename)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 484, in preprocess
    self.iter_extensions(), text_type(source))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3889: ordinal not in range(128)
```

I do not know which character is causing trouble, and it is not onvious to me to see from the log where should I search. The file layout.html is available if necessary.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1245
- Originally reported by: [pcav](https://bitbucket.org/pcav)
- Originally created at: 2013-08-26T15:51:19.854

**Comment by shimizukawa** [comment]
_From [pcav](https://bitbucket.org/pcav) on 2013-08-26 14:08:10+00:00_

Not a real issue, rather a feature req. Sorry for the noise.
