### ISSUE TITLE
Assertion triggered in nodes.py

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1250]
The following exception is caused by an assertion raised in docutils/node.py. It shouldn't be trickled down to the user:

```
#!python

# Sphinx version: 1.2b1
# Python version: 2.6.4
# Docutils version: 0.11 release
# Jinja2 version: 2.3
Traceback (most recent call last):
  File "C:\lang\python26\lib\site-packages\sphinx-1.2b1-py2.6.egg\sphinx\cmdline.py", line 247, in main
    app.build(force_all, filenames)
  File "C:\lang\python26\lib\site-packages\sphinx-1.2b1-py2.6.egg\sphinx\application.py", line 211, in build
    self.builder.build_update()
  File "C:\lang\python26\lib\site-packages\sphinx-1.2b1-py2.6.egg\sphinx\builders\__init__.py", line 211, in build_update
    'out of date' &#37; len(to_build))
  File "C:\lang\python26\lib\site-packages\sphinx-1.2b1-py2.6.egg\sphinx\builders\__init__.py", line 267, in build
    self.write(docnames, list(updated_docnames), method)
  File "C:\lang\python26\lib\site-packages\sphinx-1.2b1-py2.6.egg\sphinx\builders\__init__.py", line 310, in write
    self._write_serial(sorted(docnames), warnings)
  File "C:\lang\python26\lib\site-packages\sphinx-1.2b1-py2.6.egg\sphinx\builders\__init__.py", line 321, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "C:\lang\python26\lib\site-packages\sphinx-1.2b1-py2.6.egg\sphinx\environment.py", line 1084, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "C:\lang\python26\lib\site-packages\sphinx-1.2b1-py2.6.egg\sphinx\environment.py", line 1355, in resolve_references
    node.replace_self(newnode or contnode)
  File "C:\lang\python26\lib\site-packages\docutils\nodes.py", line 954, in replace_self
    'Losing "&#37;s" attribute: &#37;s' &#37; (att, self[att])
AssertionError: Losing "ids" attribute: ['id5']
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1250
- Originally reported by: Anonymous
- Originally created at: 2013-08-30T10:38:42.094

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-09-01 13:35:10+00:00_

Duplicate of #1160.
