### ISSUE TITLE
Crash during html build

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1255]
```
Exception occurred:
  File "/lm/.../sphinx/environ# Sphinx version: 1.1.3
# Python version: 2.7.3
# Docutils version: 0.10 release
# Jinja2 version: 2.7.1
Traceback (most recent call last):
  File "/lm/tools/extern/python/libs/lmportal-env/lib/python2.7/site-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/lm/tools/extern/python/libs/lmportal-env/lib/python2.7/site-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/lm/tools/extern/python/libs/lmportal-env/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "/lm/tools/extern/python/libs/lmportal-env/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/lm/tools/extern/python/libs/lmportal-env/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 291, in write
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/lm/tools/extern/python/libs/lmportal-env/lib/python2.7/site-packages/sphinx/environment.py", line 1230, in get_and_resolve_doctree
    doctree = self.get_doctree(docname)
  File "/lm/tools/extern/python/libs/lmportal-env/lib/python2.7/site-packages/sphinx/environment.py", line 1215, in get_doctree
    doctree = pickle.load(f)
EOFError
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1255
- Originally reported by: Anonymous
- Originally created at: 2013-09-05T20:42:50.336

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-09-08 01:18:56+00:00_

I need more information.
Please file smallest example to reproduce this issue. Thanks.
