### ISSUE TITLE
Crash due to incorrect Pygments dependency in v8.0.0, should be 2.18

### ISSUE THREAD

**Issue by igsilya** [sphinx-doc/sphinx#12711]
### Describe the bug

Sphinx fails to build with Pygments 2.17:
```
Traceback (most recent call last):
  File "/usr/bin/sphinx-build-3", line 5, in <module>
    from sphinx.cmd.build import main
  File "/usr/local/lib/python3.13/site-packages/sphinx/cmd/build.py", line 21, in <module>
    from sphinx.application import Sphinx
  File "/usr/local/lib/python3.13/site-packages/sphinx/application.py", line 29, in <module>
    from sphinx.highlighting import lexer_classes
  File "/usr/local/lib/python3.13/site-packages/sphinx/highlighting.py", line 86, in <module>
    class PygmentsBridge:
    ...<131 lines>...
                return formatter.get_style_defs() + _LATEX_ADD_STYLES
  File "/usr/local/lib/python3.13/site-packages/sphinx/highlighting.py", line 89, in PygmentsBridge
    html_formatter = HtmlFormatter[str]
                     ~~~~~~~~~~~~~^^^^^
TypeError: type 'HtmlFormatter' is not subscriptable
```
Works fine if 2.18 is installed.

The problem is that Ubuntu 24.04 and Fedora 41 are shipping Pygments 2.17 that satisfies the dependency on `pip install sphinx`, but the build fails.

### How to Reproduce

```
# python3 -m pip install -U sphinx==8.0 Pygments==2.17
# sphinx-build -b html ./ html
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/usr/local/lib/python3.13/site-packages/sphinx/cmd/build.py", line 21, in <module>
    from sphinx.application import Sphinx
  File "/usr/local/lib/python3.13/site-packages/sphinx/application.py", line 29, in <module>
    from sphinx.highlighting import lexer_classes
  File "/usr/local/lib/python3.13/site-packages/sphinx/highlighting.py", line 86, in <module>
    class PygmentsBridge:
    ...<131 lines>...
                return formatter.get_style_defs() + _LATEX_ADD_STYLES
  File "/usr/local/lib/python3.13/site-packages/sphinx/highlighting.py", line 89, in PygmentsBridge
    html_formatter = HtmlFormatter[str]
                     ~~~~~~~~~~~~~^^^^^
TypeError: type 'HtmlFormatter' is not subscriptable
```

### Environment Information

Funny enough:

```pytb
# sphinx-build --bug-report
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/usr/local/lib/python3.13/site-packages/sphinx/cmd/build.py", line 21, in <module>
    from sphinx.application import Sphinx
  File "/usr/local/lib/python3.13/site-packages/sphinx/application.py", line 29, in <module>
    from sphinx.highlighting import lexer_classes
  File "/usr/local/lib/python3.13/site-packages/sphinx/highlighting.py", line 86, in <module>
    class PygmentsBridge:
    ...<131 lines>...
                return formatter.get_style_defs() + _LATEX_ADD_STYLES
  File "/usr/local/lib/python3.13/site-packages/sphinx/highlighting.py", line 89, in PygmentsBridge
    html_formatter = HtmlFormatter[str]
                     ~~~~~~~~~~~~~^^^^^
TypeError: type 'HtmlFormatter' is not subscriptable
```

If Pygments upgraded to 2.18:
```text
Platform:              linux; (Linux-6.2.0-39-generic-x86_64-with-glibc2.39.9000)
Python version:        3.13.0b3 (main, Jul  2 2024, 00:00:00) [GCC 14.1.1 20240701 (Red Hat 14.1.1-7)])
Python implementation: CPython
Sphinx version:        8.0.0
Docutils version:      0.20.1
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```

**Comment by AA-Turner** [comment]
See https://github.com/sphinx-doc/sphinx/commit/865b513cf2c88d3e30450718914aa896d90fd14e

A

**Comment by AA-Turner** [comment]
[Sphinx 8.0.1](https://pypi.org/project/Sphinx/8.0.1/) has been released with a fix.

A

**Comment by igsilya** [comment]
@AA-Turner Still doesn't work:
```
[root@e69aac5a584d /]# sphinx-build --bug-report
Please paste all output below into the bug report template

Platform:              linux; (Linux-6.2.0-39-generic-x86_64-with-glibc2.39.9000)
Python version:        3.13.0b3 (main, Jul  2 2024, 00:00:00) [GCC 14.1.1 20240701 (Red Hat 14.1.1-7)])
Python implementation: CPython
Sphinx version:        8.0.1
Docutils version:      0.20.1
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```
```
[root@e69aac5a584d /]# python3 -m pip install -U sphinx==8.0.1 Pygments==2.17
Requirement already satisfied: sphinx==8.0.1 in /usr/local/lib/python3.13/site-packages (8.0.1)
Collecting Pygments==2.17
  Using cached pygments-2.17.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sphinxcontrib-applehelp in /usr/local/lib/python3.13/site-packages (from sphinx==8.0.1) (2.0.0)
Requirement already satisfied: sphinxcontrib-devhelp in /usr/local/lib/python3.13/site-packages (from sphinx==8.0.1) (2.0.0)
Requirement already satisfied: sphinxcontrib-jsmath in /usr/local/lib/python3.13/site-packages (from sphinx==8.0.1) (1.0.1)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in /usr/local/lib/python3.13/site-packages (from sphinx==8.0.1) (2.1.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in /usr/local/lib/python3.13/site-packages (from sphinx==8.0.1) (2.0.0)
Requirement already satisfied: sphinxcontrib-qthelp in /usr/local/lib/python3.13/site-packages (from sphinx==8.0.1) (2.0.0)
Requirement already satisfied: Jinja2>=3.1 in /usr/lib/python3.13/site-packages (from sphinx==8.0.1) (3.1.4)
Requirement already satisfied: docutils<0.22,>=0.20 in /usr/lib/python3.13/site-packages (from sphinx==8.0.1) (0.20.1)
Requirement already satisfied: snowballstemmer>=2.2 in /usr/lib/python3.13/site-packages (from sphinx==8.0.1) (2.2.0)
Requirement already satisfied: babel>=2.13 in /usr/lib/python3.13/site-packages (from sphinx==8.0.1) (2.15.0)
Requirement already satisfied: alabaster>=0.7.14 in /usr/lib/python3.13/site-packages (from sphinx==8.0.1) (0.7.16)
Requirement already satisfied: imagesize>=1.3 in /usr/lib/python3.13/site-packages (from sphinx==8.0.1) (1.4.1)
Requirement already satisfied: requests>=2.30.0 in /usr/lib/python3.13/site-packages (from sphinx==8.0.1) (2.32.3)
Requirement already satisfied: packaging>=23.0 in /usr/lib/python3.13/site-packages (from sphinx==8.0.1) (24.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/lib64/python3.13/site-packages (from Jinja2>=3.1->sphinx==8.0.1) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.13/site-packages (from requests>=2.30.0->sphinx==8.0.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.13/site-packages (from requests>=2.30.0->sphinx==8.0.1) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3.13/site-packages (from requests>=2.30.0->sphinx==8.0.1) (1.26.19)
Using cached pygments-2.17.0-py3-none-any.whl (1.2 MB)
Installing collected packages: Pygments
  Attempting uninstall: Pygments
    Found existing installation: Pygments 2.18.0
    Uninstalling Pygments-2.18.0:
      Successfully uninstalled Pygments-2.18.0
Successfully installed Pygments-2.17.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
[root@e69aac5a584d /]# sphinx-build --bug-report
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/usr/local/lib/python3.13/site-packages/sphinx/cmd/build.py", line 21, in <module>
    from sphinx.application import Sphinx
  File "/usr/local/lib/python3.13/site-packages/sphinx/application.py", line 29, in <module>
    from sphinx.highlighting import lexer_classes
  File "/usr/local/lib/python3.13/site-packages/sphinx/highlighting.py", line 92, in <module>
    class PygmentsBridge:
    ...<131 lines>...
                return formatter.get_style_defs() + _LATEX_ADD_STYLES
  File "/usr/local/lib/python3.13/site-packages/sphinx/highlighting.py", line 95, in PygmentsBridge
    html_formatter = HtmlFormatter[str]
                     ~~~~~~~~~~~~~^^^^^
TypeError: <lambda>() missing 1 required positional argument: 'name'
```

**Comment by AA-Turner** [comment]
[Sphinx 8.0.2](https://pypi.org/project/Sphinx/8.0.2/) has been released with a fix.

A
