### ISSUE TITLE
Failure when running Sphinx 1.2b2

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1272]
I'm seeing the following failure when running sphinx-build on a project which previously worked:

```
Running Sphinx v1.2b2
loading pickled environment... not yet created
ERROR: TypeError: must be unicode, not str [sphinx.util]
Traceback (most recent call last):
  File "<stdin>", line 26, in <module>
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/sphinx/application.py", line 138, in __init__
    self._init_env(freshenv)
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/sphinx/application.py", line 184, in _init_env
    return self._init_env(freshenv=True)
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/sphinx/application.py", line 166, in _init_env
    self.env.find_files(self.config)
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/sphinx/environment.py", line 345, in find_files
    self.srcdir, config.source_suffix, exclude_matchers=matchers))
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/sphinx/util/__init__.py", line 94, in get_matching_docs
    for filename in get_matching_files(dirname, exclude_matchers):
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/sphinx/util/__init__.py", line 78, in get_matching_files
    qdirs = [entry for entry in qdirs if not matcher(entry[1])]
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/sphinx/util/__init__.py", line 74, in <genexpr>
    for dn in dirs)
  File "/Users/tom/Library/Python/2.7/lib/python/site-packages/sphinx/util/__init__.py", line 57, in path_stabilize
    newpath = unicodedata.normalize('NFC', newpath)
TypeError: must be unicode, not str
```

I see this on MacOS X and also Linux (on Travis).

Let me know if I can provide any information to help diagnose this.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1272
- Originally reported by: [astrofrog](https://bitbucket.org/astrofrog)
- Originally created at: 2013-09-21T17:27:20.215

**Comment by shimizukawa** [comment]
_From [astrofrog](https://bitbucket.org/astrofrog) on 2013-09-21 15:31:08+00:00_

One way to fix this is to use:

```
newpath = unicodedata.normalize('NFC', newpath.decode('utf-8'))
```

in `sphinx/util/__init__.py` on line 57.

**Comment by shimizukawa** [comment]
_From [astrofrog](https://bitbucket.org/astrofrog) on 2013-09-21 15:48:32+00:00_

Oh, I think this was fixed in 95a2a34 - can you confirm?

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-09-22 13:53:25+00:00_

Thanks reporting!

As you say it was fixed in the wake of https://bitbucket.org/birkenfeld/sphinx/pull-request/165.

**Comment by shimizukawa** [comment]
_From holger krekel on 2013-10-24 12:45:13+00:00_

would love a new dev release as 1.2b2 consistently fails for me without this fix.
