### ISSUE TITLE
Sphinx 7.2: unknown node type: only 

### ISSUE THREAD

**Issue by JasperCraeghs** [sphinx-doc/sphinx#13022]
### Describe the bug

The use of an `only`-directive that is nested inside of a parent `only`-directive to conditionally include a directive of the Sphinx plugin [`breathe`](https://github.com/breathe-doc/breathe) fails since Sphinx 7.2. Sphinx<=7.1.2 supports this use case.

```
/home/user/git/minimal-doc/<partial node>:: WARNING: unknown node type: <only: <list_item...><list_item...><list_item...>>

Traceback (most recent call last):
...
  File "/home/user/git/minimal-doc/venv/lib/python3.10/site-packages/sphinx/util/docutils.py", line 743, in dispatch_departure
    super().dispatch_departure(node)
  File "/home/user/git/minimal-doc/venv/lib/python3.10/site-packages/docutils/nodes.py", line 2005, in dispatch_departure
    return method(node)
  File "/home/user/git/minimal-doc/venv/lib/python3.10/site-packages/docutils/nodes.py", line 2027, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: only

Exception occurred:
  File "/home/user/git/minimal-doc/venv/lib/python3.10/site-packages/docutils/nodes.py", line 2027, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: only
```

### How to Reproduce

My minimal git repository contains build output of doxygen, needed for the `breathe` directive (`doxygenfile`) to function, which is required to reproduce the bug.
```
git clone git@github.com:JasperCraeghs/minimal-doc.git
pip install virtualenv
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
make html
```

My `index.rst`:
```
minimal-doc documentation
=========================

.. only:: html

    hello world

    .. only:: not text

        .. doxygenfile:: component.c
```

### Environment Information

```text
Platform:              linux; (Linux-6.8.0-45-generic-x86_64-with-glibc2.35)
Python version:        3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        8.1.3
Docutils version:      0.21.2
Jinja2 version:        3.1.2
Pygments version:      2.18.0
```

### Sphinx extensions

```python
["breathe"]
```

### Additional context

The following made me realize that this is likely a bug in `sphinx` and not in `breathe`: https://github.com/sphinx-doc/sphinx/pull/10502

I can use directives of other Sphinx plugins in a nested `only`-directive. The crash is specific to the directives of the `breathe` plugin. The version of `docutils` doesn't seem to matter.

**Comment by Lenbok** [comment]
I am hitting this bug as well. I have directives along the lines of:
```
.. only:: foo or bar

    Something specialized

    .. only:: bar

        Something even more specialized
```

**Comment by JasperCraeghs** [comment]
Hi @AA-Turner. My company recently started sponsoring the Sphinx project, and I wanted to kindly ask if someone could take a look at this issue when they have a moment. We're encountering this bug in our documentation builds and would really appreciate any guidance or insights on how to move forward. We've been using Sphinx version 6 but a recent enhancement of our plugin [`mlx.traceability`](https://github.com/melexis/sphinx-traceability-extension/pull/391) will require Sphinx>=7.4.

Also, we rely heavily on the extension sphinx_selective_exclude, explained in https://github.com/sphinx-doc/sphinx/issues/2150#issuecomment-224753598.

Thank you for all your work on Sphinx!

Best,
Jasper

**Comment by AA-Turner** [comment]
Hi @JasperCraeghs, please can you email me at [my forename] at python dot org?

A
