### ISSUE TITLE
Exception occurred:   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 700, in send     raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='awx.example.org', port=443): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faf8e89e040>: Failed to establish a new connection: [Errno -2] Name or service not known'))

### ISSUE THREAD

**Issue by bijeshgit-cloud** [sphinx-doc/sphinx#13174]
### Describe the bug

```
$ TOWER_HOST=https://awx.example.org TOWER_USERNAME=example TOWER_PASSWORD=secret make clean html
Running Sphinx v7.4.7
loading translations [en]... done

Exception occurred:
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='awx.example.org', port=443): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faf8e89e040>: Failed to establish a new connection: [Errno -2] Name or service not known'))
The full traceback has been saved in /tmp/sphinx-err-xoi1cos_.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: html] Error 2

$ ls
make.bat  Makefile  README.md  source
```

### How to Reproduce

```
$ TOWER_HOST=https://awx.example.org TOWER_USERNAME=example TOWER_PASSWORD=secret make clean html
Running Sphinx v7.4.7
loading translations [en]... done

Exception occurred:
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='awx.example.org', port=443): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faf8e89e040>: Failed to establish a new connection: [Errno -2] Name or service not known'))
The full traceback has been saved in /tmp/sphinx-err-xoi1cos_.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: html] Error 2

$ ls
make.bat  Makefile  README.md  source
```

### Environment Information

```text
[root@localhost docs]# sphinx-build --bug-report
Please paste all output below into the bug report template



Platform:              linux; (Linux-5.14.0-503.14.1.el9_5.x86_64-x86_64-with-glibc2.34)
Python version:        3.9.19 (main, Sep 11 2024, 00:00:00) 
[GCC 11.5.0 20240719 (Red Hat 11.5.0-2)])
Python implementation: CPython
Sphinx version:        7.4.7
Docutils version:      0.21.2
Jinja2 version:        3.1.4
Pygments version:      2.18.0

[root@localhost docs]# python -m sphinx --bug-report
Please paste all output below into the bug report template

Platform:              linux; (Linux-5.14.0-503.14.1.el9_5.x86_64-x86_64-with-glibc2.34)
Python version:        3.9.19 (main, Sep 11 2024, 00:00:00) 
[GCC 11.5.0 20240719 (Red Hat 11.5.0-2)])
Python implementation: CPython
Sphinx version:        7.4.7
Docutils version:      0.21.2
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```

### Additional context

```
# cat /tmp/sphinx-err-xoi1cos_.log 
# Platform:         linux; (Linux-5.14.0-503.14.1.el9_5.x86_64-x86_64-with-glibc2.34)
# Sphinx version:   7.4.7
# Python version:   3.9.19 (CPython)
# Docutils version: 0.21.2
# Jinja2 version:   3.1.4
# Pygments version: 2.18.0

# Last messages:


# Loaded extensions:


# Traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1015, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7faf8e89e040>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 576, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='awx.example.org', port=443): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faf8e89e040>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/local/lib/python3.9/site-packages/sphinx/application.py", line 253, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python3.9/site-packages/sphinx/application.py", line 429, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/lib/python3.9/site-packages/sphinx/registry.py", line 453, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/awxkit/cli/sphinx.py", line 80, in <module>
    parser = render()
  File "/usr/local/lib/python3.9/site-packages/awxkit/cli/sphinx.py", line 56, in render
    cli.authenticate()
  File "/usr/local/lib/python3.9/site-packages/awxkit/cli/client.py", line 95, in authenticate
    self.root.load_session().get()
  File "/usr/local/lib/python3.9/site-packages/awxkit/api/pages/base.py", line 183, in load_session
    username=username or default_cred.username, password=password or default_cred.password, **self.connection.get_session_requirements()
  File "/usr/local/lib/python3.9/site-packages/awxkit/api/client.py", line 47, in get_session_requirements
    self.get(config.api_base_path)  # this causes a cookie w/ the CSRF token to be set
  File "/usr/local/lib/python3.9/site-packages/awxkit/api/client.py", line 113, in get
    return self.request(relative_endpoint, method='get', query_parameters=query_parameters, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/awxkit/api/client.py", line 104, in request
    raise err
  File "/usr/local/lib/python3.9/site-packages/awxkit/api/client.py", line 100, in request
    response = session_request_method(url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='awx.example.org', port=443): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faf8e89e040>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by AA-Turner** [comment]
Hi, these aren't reproduction instructions because we don't have your Makefile and it seems that the `TOWER` env variables are meaningful -- but these aren't part of Sphinx.

The best I can do is that the error says `Failed to establish a new connection: [Errno -2] Name or service not known`, which suggests that the host `awx.example.org` isn't resolving. But again, this doesn't seem part of core Sphinx (the error is in `awxkit/cli/sphinx.py`, and hence the error should be reported to `awxkit`).

A
