### ISSUE TITLE
Autosummary templates not included in Sphinx 0.6 egg

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#132]
The Sphinx 0.6 egg as uploaded to PyPI doesn't come with the sphinx/ext/autosummary/templates directory. Running sphinx-autogen on a file with an autosummary statement that lists a module produces an exception:

Traceback (most recent call last):
  File "bin/sphinx-autogen", line 17, in <module>
    sphinx.ext.autosummary.generate.main(argv=sys.argv+"-o doc/ doc/modules.txt".split())
  File "/var/lib/python-eggs/Sphinx-0.6-py2.5.egg/sphinx/ext/autosummary/generate.py", line 234, in main
    generate_autosummary_docs(args, output_dir, suffix)
  File "/var/lib/python-eggs/Sphinx-0.6-py2.5.egg/sphinx/ext/autosummary/generate.py", line 75, in generate_autosummary_docs
    tmpl = env.get_template('module')
  File "/var/lib/python-eggs/Jinja2-2.1.1-py2.5-linux-i686.egg/jinja2/environment.py", line 499, in get_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/var/lib/python-eggs/Jinja2-2.1.1-py2.5-linux-i686.egg/jinja2/loaders.py", line 95, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/var/lib/python-eggs/Jinja2-2.1.1-py2.5-linux-i686.egg/jinja2/loaders.py", line 193, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: module

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/132
- Originally reported by: Anonymous
- Originally created at: 2009-03-25T17:03:49.554

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-03-26 14:59:55+00:00_

Released 0.6.1 where it should be fixed.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-03-26 15:03:55+00:00_

Fix #132...

→ <<cset 23e77c67a88525ff134d29b67c86be74529a0ba1>>
