### ISSUE TITLE
Sphinx error: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1322]
This is from sphinx building the docs for eventlet-0.14.0.

``` bash
/path/to/eventlet-0.14.0/doc $ make html
PYTHONPATH=../: sphinx-build -b html -d _build/doctrees   . _build/html
Making output directory...
Running Sphinx v1.1.3
loading pickled environment... not yet created
building [html]: targets for 28 source files that are out of date
updating environment: 28 added, 0 changed, 0 removed
Traceback (most recent call last):zmq                                                                                                         
  File "/usr/lib64/python2.7/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/lib64/python2.7/site-packages/sphinx/ext/autodoc.py", line 232, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib64/python2.7/site-packages/sphinx/util/inspect.py", line 70, in safe_getattr
    raise AttributeError(name)
AttributeError: _Context

Sphinx error:
'ascii' codec can't decode byte 0xe2 in position 51: ordinal not in range(128)
make: *** [html] Error 1
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1322
- Originally reported by: [idella5](https://bitbucket.org/idella5)
- Originally created at: 2013-12-14T06:11:31.369

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-09-05 04:54:40+00:00_

confirmed with:

```
$ virtualenv venv
$ cd venv
$ source bin/activate
$ pip install sphinx==1.1.3 pyzmq
$ curl -L https://pypi.python.org/packages/source/e/eventlet/eventlet-0.14.0.tar.gz | tar zxf -
$ cd eventlet-0.14.0/doc
$ make html SPHINXBUILD=../../bin/sphinx-build
../../bin/sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.1.3
loading pickled environment... failed: env version not current
loading intersphinx inventory from http://docs.python.org/objects.inv...
building [html]: targets for 28 source files that are out of date
updating environment: 28 added, 0 changed, 0 removed
Traceback (most recent call last):zmq                                           
  File "/private/tmp/1322/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    obj = self.get_attr(obj, part)
  File "/private/tmp/1322/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 232, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/private/tmp/1322/lib/python2.7/site-packages/sphinx/util/inspect.py", line 70, in safe_getattr
    raise AttributeError(name)
AttributeError: _Context

Sphinx error:
'ascii' codec can't decode byte 0xe2 in position 51: ordinal not in range(128)
make: *** [html] Error 1
```

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-09-05 04:59:46+00:00_

It works with Sphinx-1.2.3.

I don't know what wrong with sphinx-1.1.3, but I think it was fixed at latest version. Please use Sphinx-1.2.3.

```
$ pip install sphinx==1.2.3
$ make html SPHINXBUILD=../../bin/sphinx-build
../../bin/sphinx-build -b html -d _build/doctrees   . _build/html
Making output directory...
Running Sphinx v1.2.3
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
building [html]: targets for 28 source files that are out of date
updating environment: 28 added, 0 changed, 0 removed
reading sources... [100%] zeromq               

...(snip)...

dumping object inventory... done
build succeeded, 63 warnings.

Build finished. The HTML pages are in _build/html.
```
