### ISSUE TITLE
inheritance-digramm failed while autodocumenting a class hineriting from Boost.Python.instance

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1354]
Hello, I am using sphinx 1.2.0 from Debian unstable, and I get this error message during the documentation generation of my package.

you can find the package at this location[1] if you want to do some test.

Exception occurred while building, starting debugger:e/SardanaDevice
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 246, in main
app.build(force_all, filenames)
File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 210, in build
self.builder.build_specific(filenames)
File "/usr/lib/python2.7/dist-packages/sphinx/builders/init.py", line 203, in build_specific
'line' &#37; len(to_write))
File "/usr/lib/python2.7/dist-packages/sphinx/builders/init.py", line 234, in build
purple, length):
File "/usr/lib/python2.7/dist-packages/sphinx/builders/init.py", line 134, in status_iterator
for item in iterable:
File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 470, in update_generator
self.read_doc(docname, app=app)
File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 689, in read_doc
pickle.dump(doctree, f, pickle.HIGHEST_PROTOCOL)
PicklingError: Can't pickle : import of module Boost.Python failed

```
/usr/lib/python2.7/dist-packages/sphinx/environment.py(689)read_doc()
-> pickle.dump(doctree, f, pickle.HIGHEST_PROTOCOL)
```

(Pdb) pickle
<module 'cPickle' (built-in)>
(Pdb) f
<closed file u'/home/picca/Debian/main/sardana/sardana  /doc/source/build/.doctrees/devel/api/sardana/tango/core/SardanaDevice.doctree', mode 'wb' at 0xe009ee8>
(Pdb)

Have a good day

Frederic

[1] https://alioth.debian.org/anonscm/git/debian-science/packages/sardana.git

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1354
- Originally reported by: [picca](https://bitbucket.org/picca)
- Originally created at: 2014-01-21T10:08:41.009

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-21 09:19:49+00:00_

Thanks for the report: this bug should be fixed in the newly released 1.2.1 - can you verify?

**Comment by shimizukawa** [comment]
_From [picca](https://bitbucket.org/picca) on 2014-01-22 06:43:16+00:00_

Great with 1.2.1 it works.

thanks

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-03-01 08:31:16+00:00_

Thanks!
