### ISSUE TITLE
AttributeError using sphinx 1.2.1

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1355]
I upgraded my sphinx using pip, which installed sphinx **1.2.1** on my Mac OS X 10.9.1

I got this exception while compiling the latest stable version of Django docs:

```
#!python

# Sphinx version: 1.2.1
# Python version: 2.7.5
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
# Loaded extensions:
#   djangodocs from /Users/reza/Workspaces/django/docs/_ext/djangodocs.pyc
#   sphinx.ext.oldcmarkup from /Library/Python/2.7/site-packages/sphinx/ext/oldcmarkup.pyc
#   sphinx.ext.intersphinx from /Library/Python/2.7/site-packages/sphinx/ext/intersphinx.pyc

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 212, in build
    self.builder.build_update()
  File "/Library/Python/2.7/site-packages/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' &#37; len(to_build))
  File "/Library/Python/2.7/site-packages/sphinx/builders/__init__.py", line 276, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Library/Python/2.7/site-packages/sphinx/builders/__init__.py", line 320, in write
    self._write_serial(sorted(docnames), warnings)
  File "/Library/Python/2.7/site-packages/sphinx/builders/__init__.py", line 333, in _write_serial
    self.write_doc(docname, doctree)
  File "/Library/Python/2.7/site-packages/sphinx/builders/html.py", line 433, in write_doc
    self.docwriter.write(doctree, destination)
  File "/Library/Python/2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/Library/Python/2.7/site-packages/sphinx/writers/html.py", line 51, in translate
    self.document.walkabout(visitor)
  File "/Library/Python/2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
... (5 more of the same)
  File "/Library/Python/2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Library/Python/2.7/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/Library/Python/2.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/Library/Python/2.7/site-packages/sphinx/writers/html.py", line 153, in visit_desc_parameter
    if self.optional_param_level == 0:
AttributeError: DjangoHTMLTranslator instance has no attribute 'optional_param_level'
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1355
- Originally reported by: Anonymous
- Originally created at: 2014-01-22T14:40:33.416

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-22 16:23:26+00:00_

Closes #1355: compatibility fix for Django docs.

→ <<cset 652b766af975b830dfa7071b5504df0bb2d03435>>

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-22 16:24:24+00:00_

Thanks for the report. This is not really a Sphinx issue (Django has to adapt their extension) but I pushed a fix that should make it work until they do.

**Comment by shimizukawa** [comment]
_From Tim Graham on 2014-01-24 14:18:39+00:00_

Here's [the fix](https://github.com/django/django/commit/e1d18b9d2e8ac292940f070b0a8cb9733756acd9) I pushed for the Django docs. It looks like we're overriding the method just to remove the `<big>` tag that sphinx uses by default. Perhaps we could add a hook for that so that Django can make this change more elegantly.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-25 09:45:21+00:00_

Well, I suggest I just replace the `<big>` by a `<span>` in 1.3, and then everybody should be happy?

**Comment by shimizukawa** [comment]
_From James Turley on 2014-01-25 10:15:07+00:00_

Django style is to take the tag out altogether, so it would be ideal to
have a hook to set the tag with a useful default...

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-25 10:18:12+00:00_

I don't think a hook for a single tag is sensible, but as I said, if it's a `<span class="whatever">` you can easily style that as you like for Django.

**Comment by shimizukawa** [comment]
_From Tim Graham on 2014-01-25 21:02:22+00:00_

<span> with a class sounds good to me.

**Comment by shimizukawa** [comment]
_From Barry Warsaw on 2014-01-28 10:52:38+00:00_

We saw this failure in our Ubuntu archive test rebuild, and the patch Georg applied fixed that particular problem.  Now we're seeing this failure:

```
Exception occurred:
  File "/usr/lib/python2.7/dist-packages/sphinx/writers/html.py", line 155, in visit_desc_parameter
    self.required_params_left -= 1
AttributeError: DjangoHTMLTranslator instance has no attribute 'required_params_left'
```

So I'm guessing a similar patch is required to fix this?

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-28 13:14:02+00:00_

I'll have a look.

**Comment by shimizukawa** [comment]
_From Barry Warsaw on 2014-01-28 13:45:02+00:00_

It may not be worth fixing in Sphinx: https://code.djangoproject.com/ticket/21869

I've tested it and with a vanilla Sphinx and the above patch to Django, everything works.  I probably won't apply this Sphinx patch unless I see other packages break.

**Comment by shimizukawa** [comment]
_From Ned Batchelder on 2014-09-27 15:05:05+00:00_

I just dealt with this in my own extension.  Perhaps the best thing would be to separate the base method into two parts: 1) output the actual text, and 2) set internal state.  Then I could override #1, and just call #2.  As it is, I'm doing just what Django did, copying a bunch of lines from the base class into mine.
