### ISSUE TITLE
sphinxcontrib-{aafig,gnuplot} installation problem

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1361]
I start with sphinx and I come across this issue by wanting install sphinxcontrib-aafig (also with sphinxcontrib-gnuplot). I can not find a solution...

```
# Sphinx version: 1.2.1
# Python version: 2.7.6
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.1-py2.7.egg/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.1-py2.7.egg/sphinx/application.py", line 119, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.1-py2.7.egg/sphinx/application.py", line 283, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib_aafig-1.0dev_20140125-py2.7.egg/sphinxcontrib/aafig.py", line 58, in <module>
    class AafigDirective(directives.images.Image):
AttributeError: 'module' object has no attribute 'images'
```

Merci

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1361
- Originally reported by: Anonymous
- Originally created at: 2014-01-26T02:58:13.869

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-26 07:45:25+00:00_

Please report to the sphinx-contrib tracker or the aafig author directly.

**Comment by shimizukawa** [comment]
_From Jean-Michel Sarlat on 2014-01-26 12:46:05+00:00_

The Image class is, perhaps, improperly located (python 2.7.6).
Rather

```
 import docutils.parsers.rst.directives.images as Images
```

Replacing **images.directives** by **Images**.
