### ISSUE TITLE
sphinx.pycode.ModuleAnalyzer fails with print function in Python 2

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1385]
Using print function by importing it from **future** raises PycodeError.

To reproduce this bug, save the following as `foo.py`:

```
#!python
from __future__ import print_function
import sys

def foo():
    """Foo!"""
    print("Bar", file=sys.stderr)
```

Then run:

```
#!python
>>> from sphinx.pycode import ModuleAnalyzer
>>> a = ModuleAnalyzer.for_module('foo')
>>> a.find_attr_docs()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choongmin/.virtualenvs/audiodiff/lib/python2.7/site-packages/sphinx/pycode/__init__.py", line 266, in find_attr_docs
    self.parse()
  File "/Users/choongmin/.virtualenvs/audiodiff/lib/python2.7/site-packages/sphinx/pycode/__init__.py", line 260, in parse
    raise PycodeError('parsing failed', err)
sphinx.errors.PycodeError: parsing failed (exception was: ParseError("bad input: type=22, value=u'=', context=('', (6, 21))",))
>>> 
```

This bug causes module data members to disappear and autodoc_member_order = 'by source' to be ignored.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1385
- Originally reported by: Choongmin Lee
- Originally created at: 2014-02-11T17:18:36.463

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-03-01 08:19:40+00:00_

This should be fixed in Sphinx 1.2.1.
