### ISSUE TITLE
Building pandas documentation in latex fails with exception in sphinx/highlighting.py

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1392]
I was trying to build the pandas documentation in latex format.

$ git clone git clone https://github.com/pydata/pandas.git
$ cd pandas
$ sudo python setup.py install
$ python make.py html
  <success with various warnings>
$ python make.py latex
  <fails>

Here's the tail of the build output:

--8<---------------cut here---------------start------------->8---
...
resolving references...
writing... /home/nick/src/python/pandas/doc/source/index.rst:: WARNING: unusable reference target found: pandas.pdf
/home/nick/src/python/pandas/doc/source/index.rst:: WARNING: unusable reference target found: pandas.zip

Exception occurred:
  File "/usr/lib/python2.7/site-packages/sphinx/highlighting.py", line 210, in highlight_block
    return hlsource.translate(tex_hl_escape_map_new)
TypeError: expected a character buffer object
The full traceback has been saved in /tmp/sphinx-err-Ho21Ro.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at http://groups.google.com/group/sphinx-dev/,
or report them in the tracker at https://bitbucket.org/birkenfeld/sphinx/issues/. Thanks!
Building LaTeX failed.
--8<---------------cut here---------------end--------------->8---

Here's the backtrace from /tmp/sphinx-err-Ho21Ro.log:

--8<---------------cut here---------------start------------->8---
# Sphinx version: 1.1.3
# Python version: 2.7.3
# Docutils version: 0.10 repository
# Jinja2 version: 2.6

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/site-packages/sphinx/builders/**init**.py", line 191, in build_update
    self.build(['**all**'], to_build)
  File "/usr/lib/python2.7/site-packages/sphinx/builders/**init**.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python2.7/site-packages/sphinx/builders/latex.py", line 104, in write
    docwriter.write(doctree, destination)
  File "/usr/lib/python2.7/site-packages/docutils/writers/**init**.py", line 80, in write
    self.translate()
  File "/usr/lib/python2.7/site-packages/sphinx/writers/latex.py", line 94, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 186, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/lib/python2.7/site-packages/docutils/nodes.py", line 1624, in dispatch_departure
    return method(node)
  File "/usr/lib/python2.7/site-packages/sphinx/writers/latex.py", line 1312, in depart_literal_block
    linenos=linenos, **highlight_args)
  File "/usr/lib/python2.7/site-packages/sphinx/highlighting.py", line 210, in highlight_block
    return hlsource.translate(tex_hl_escape_map_new)
TypeError: expected a character buffer object
--8<---------------cut here---------------end--------------->8---

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1392
- Originally reported by: Anonymous
- Originally created at: 2014-02-14T22:47:21.234

**Comment by shimizukawa** [comment]
_From [foobaron](https://bitbucket.org/foobaron) on 2014-04-10 22:21:49+00:00_

FYI, I got the same error message from docutils.writers.latex2e.LatexTranslator.visit_math() line 2508.

the code assumes node.astext() will return a unicode string.  But I found that it was returning an empty string, which then throws this error message when its translate() method is called.  Forcing the conversion to unicode via

```
#!python

unicode(node.astext()).translate(...)
```

fixes the problem.  Not sure if that is helpful for this issue...

**Comment by tk0miya** [comment]
In my short investigation:

I try to reproduce this, but I got too many exceptions on building like following:

```
>>>-------------------------------------------------------------------------
Exception in /Users/tkomiya/work/pandas/doc/source/sparse.rst at block ending on line 176
Specify :okexcept: as an option in the ipython:: block to suppress this message
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-31-52eb04535613> in <module>()
----> 1 A.todense()

NameError: name 'A' is not defined
<<<-------------------------------------------------------------------------
```

I tested with following commands:

```
$ git clone https://github.com/pydata/pandas.git
$ cd pandas
$ virtualenv -p python2.7 .
$ . bin/activate
$ pip install cython
$ python setup.py install
$ cd doc
$ pip install sphinx
$ pip install jupyter
$ pip install matplotlib
$ python make.py latex
```

In addition, the error message is similar to #905. It come from combination with Sphinx-1.1.3 and pygments-1.5 or older.
Could you try it with newest Sphinx and pygments.

If you got same errors, please let us know in details.

Thanks,

**Comment by tk0miya** [comment]
Now I close this. Please reopen if you got same error.

Thanks,
