### ISSUE TITLE
RuntimeError: No directive named 'function' found

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1404]
I tried to run Sphinx to make the documentation for pylpsolve, and got the following error (the traceback is included below it):

```
#!python

mkdir -p .build/latex .build/doctrees
sphinx-build -b latex -d .build/doctrees   . .build/latex
Running Sphinx v1.2.1

Exception occurred:
  File "/Users/bbradley/src/pylpsolve/doc/sphinxext/numpydoc.py", line 136, in get_directive
    raise RuntimeError("No directive named '&#37;s' found" &#37; name)
RuntimeError: No directive named 'function' found
The full traceback has been saved in /var/folders/19/8g3g1vyd0yj1xqzxqp76h_d4551wdw/T/sphinx-err-TT0izq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-users/>,
or report them in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
```

The traceback is as follows:

```
#!python

# Sphinx version: 1.2.1
# Python version: 2.7.2
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
# Loaded extensions:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Sphinx-1.2.1-py2.7.egg/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/Library/Python/2.7/site-packages/Sphinx-1.2.1-py2.7.egg/sphinx/application.py", line 119, in __init__
    self.setup_extension(extension)
  File "/Library/Python/2.7/site-packages/Sphinx-1.2.1-py2.7.egg/sphinx/application.py", line 292, in setup_extension
    mod.setup(self)
  File "/Users/bbradley/src/pylpsolve/doc/sphinxext/numpydoc.py", line 119, in setup
    app.add_directive('np-' + name, wrap_mangling_directive(name, objtype))
  File "/Users/bbradley/src/pylpsolve/doc/sphinxext/numpydoc.py", line 139, in wrap_mangling_directive
    base_directive = get_directive(base_directive_name)
  File "/Users/bbradley/src/pylpsolve/doc/sphinxext/numpydoc.py", line 136, in get_directive
    raise RuntimeError("No directive named '&#37;s' found" &#37; name)
RuntimeError: No directive named 'function' found

```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1404
- Originally reported by: Anonymous
- Originally created at: 2014-02-26T16:30:26.253

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-02-27 12:18:19+00:00_

Had the error not been caused with Sphinx-1.1.3?

**Comment by shimizukawa** [comment]
_From Bill B on 2014-02-27 14:02:45+00:00_

I seem to get an analogous failure in Sphinx-1.1.3 (listed below).  I should mention that this is the first time I've ever used Sphinx, so I may be making some elementary error in using:

```
#!python

# Sphinx version: 1.1.3
# Python version: 2.7.2
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sphinx/cmdline.py", line 188, in main
    warningiserror, tags)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 114, in __init__
    self.setup_extension(extension)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 256, in setup_extension
    mod.setup(self)
  File "/Users/bbradley/src/pylpsolve/doc/sphinxext/numpydoc.py", line 119, in setup
    app.add_directive('np-' + name, wrap_mangling_directive(name, objtype))
  File "/Users/bbradley/src/pylpsolve/doc/sphinxext/numpydoc.py", line 139, in wrap_mangling_directive
    base_directive = get_directive(base_directive_name)
  File "/Users/bbradley/src/pylpsolve/doc/sphinxext/numpydoc.py", line 136, in get_directive
    raise RuntimeError("No directive named '%s' found" % name)
RuntimeError: No directive named 'function' found
```

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-02-28 01:21:23+00:00_

The pylpsolve's `numpydoc.py` is too old. Perhaps the code was copied from https://github.com/cheshire/numpy/blob/master/doc/sphinxext/numpydoc.py. It seems that the original code is adapted to earlier Sphinx interface.

Please contact to pylpsolve's owner, or replace old sphinxext directory with newer from numpy repository.
Thanks.
