### ISSUE TITLE
sphinxcontrib-exceltable: unclear error when referenced xls file is missing

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1422]
I accidentally deleted one of the xls files that I was referring to in the rst file. The error message is printed below. This could be a little clearer. Perhaps an IOError?

Thanks for the great tool btw!!

regards,
Albert-Jan
# Sphinx version: 1.2.2
# Python version: 2.7.3
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
# Loaded extensions:
# sphinx.ext.coverage from /usr/local/lib/python2.7/dist-packages/sphinx/ext/coverage.pyc
# sphinxcontrib.exceltable from /usr/local/lib/python2.7/dist-packages/sphinxcontrib/exceltable.pyc
# sphinx.ext.autodoc from /usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.pyc
# sphinx.ext.viewcode from /usr/local/lib/python2.7/dist-packages/sphinx/ext/viewcode.pyc
# sphinx.ext.oldcmarkup from /usr/local/lib/python2.7/dist-packages/sphinx/ext/oldcmarkup.pyc

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 212, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/**init**.py", line 214, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/**init**.py", line 234, in build
    purple, length):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/**init**.py", line 134, in status_iterator
    for item in iterable:
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 477, in update_generator
    self.read_doc(docname, app=app)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 624, in read_doc
    pub.publish()
  File "/usr/local/lib/python2.7/dist-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/local/lib/python2.7/dist-packages/docutils/readers/**init**.py", line 72, in read
    self.parse()
  File "/usr/local/lib/python2.7/dist-packages/docutils/readers/**init**.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/**init**.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/exceltable.py", line 160, in run
    return [msgr.error('Error occured while creating table: &#37;s' &#37; e)]
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/exceltable.py", line 63, in error
    return literal_block(text=text)
NameError: global name 'literal_block' is not defined

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1422
- Originally reported by: Anonymous
- Originally created at: 2014-03-14T17:58:14.264

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-03-16 08:30:46+00:00_

Please report this to the sphinxcontrib-exceltable maintainer; it seems like a missing import.
