### ISSUE TITLE
Python 3.4 build failure on sphinx-build

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1433]
Attempting to add python 3.4 variant of Sphinx 2.2 1.2.2 to Fink on Mac OSX.

```
#!python

Installing sphinx-build script to /sw/src/fink.build/root-sphinx-py34-1.2.2-1/sw/bin
mkdir -p /sw/src/fink.build/root-sphinx-py34-1.2.2-1/sw/share/doc/sphinx-py34
cp -R doc /sw/src/fink.build/root-sphinx-py34-1.2.2-1/sw/share/doc/sphinx-py34/doc
make -C doc latex PYTHON=python3.4 SPHINXBUILD="python3.4 ../sphinx-build.py" 
Traceback (most recent call last):
  File "../sphinx-build.py", line 16, in <module>
    sys.exit(make_main(sys.argv))
  File "/sw/src/fink.build/sphinx-py34-1.2.2-1/Sphinx-1.2.2/sphinx/__init__.py", line 85, in make_main
    from sphinx import make_mode
  File "/sw/src/fink.build/sphinx-py34-1.2.2-1/Sphinx-1.2.2/sphinx/make_mode.py", line 72
    print "Error: &#37;r is not a directory!" &#37; self.builddir
                                        ^
SyntaxError: invalid syntax
make: *** [latex] Error 1
```

```
#!bash

 &#37;p/bin/python&#37;type_raw[python] setup.py install --root &#37;d
 mkdir -p &#37;i/share/doc/sphinx-py&#37;type_pkg[python]
 cp -R doc &#37;i/share/doc/sphinx-py&#37;type_pkg[python]/doc

# Dies here in the install process:

 make -C doc latex PYTHON=python&#37;type_raw[python] SPHINXBUILD="python&#37;type_raw[python] ../sphinx-build.py" 
make -C doc/_build/latex all-pdf PYTHON=python&#37;type_raw[python] SPHINXBUILD="python&#37;type_raw[python] ../sphinx-build.py" 

```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1433
- Originally reported by: Kurt Schwehr
- Originally created at: 2014-03-29T19:53:28.794

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-03-29 21:22:14+00:00_

Is the Fink build system aware that the code has to be run through 2to3 for 3.x?

**Comment by shimizukawa** [comment]
_From Kurt Schwehr on 2014-03-29 22:25:17+00:00_

It can run 2to3, but it's best if projects can do that if necessary on their own from within the setup file.  Some projects need neither, some need 2to3, some need 3to2 for 2.x and it's best if that is kept in the library, not in the package managers.  Some day, you'll probably switch from from needing 2to3 over to needing 3to2.

I'm about to add running 2to3 for sphinx in fink, but I'll be happy when I can remove that from the fink side.  An example (that isn't totally there yet for 3.x... async needs 3.x love):

http://fink.cvs.sourceforge.net/viewvc/fink/dists/10.7/stable/main/finkinfo/libs/pythonmods/async-py.info?view=markup

**Comment by shimizukawa** [comment]
_From Kurt Schwehr on 2014-03-29 22:34:24+00:00_

2to3 -w . takes a very long time and I noticed these complains from it along the way. 

RefactoringTool: ./utils/reindent.py
RefactoringTool: Warnings/messages while refactoring:
RefactoringTool: ### In file ./sphinx/pycode/**init**.py ###
RefactoringTool: Line 20: Calls to builtin next() possibly shadowed by global binding
RefactoringTool: ### In file ./sphinx/util/pycompat.py ###
RefactoringTool: Line 139: Calls to builtin next() possibly shadowed by global binding
RefactoringTool: ### In file ./sphinx/util/pycompat.py ###
RefactoringTool: Line 157: You should use 'operator.mul(fillvalue)' here.
phase test: passed
/

During the install process...

Can't parse build/lib/sphinx/apidoc.py: ParseError: bad input: type=22, value='=', context=('', (317, 55))
Can't parse build/lib/sphinx/application.py: ParseError: bad input: type=22, value='=', context=('', (189, 66))
Can't parse build/lib/sphinx/cmdline.py: ParseError: bad input: type=22, value='=', context=('', (31, 23))
Can't parse build/lib/sphinx/make_mode.py: ParseError: bad input: type=22, value='=', context=('', (253, 67))
Can't parse build/lib/sphinx/setup_command.py: ParseError: bad input: type=22, value='=', context=('', (165, 57))
Can't parse build/lib/sphinx/builders/htmlhelp.py: ParseError: bad input: type=22, value='=', context=('', (200, 32))
Can't parse build/lib/sphinx/util/osutil.py: ParseError: bad input: type=22, value='=', context=('', (85, 79))
Can't parse build/lib/sphinx/ext/autosummary/generate.py: ParseError: bad input: type=22, value='=', context=('', (76, 33))

And I'm not sure what's up with this.  The make works on python 2.7

Installing sphinx-autogen script to /sw/src/fink.build/root-sphinx-py34-1.2.2-1/sw/bin
mkdir -p /sw/src/fink.build/root-sphinx-py34-1.2.2-1/sw/share/doc/sphinx-py34
cp -R doc /sw/src/fink.build/root-sphinx-py34-1.2.2-1/sw/share/doc/sphinx-py34/doc
make -C doc latex PYTHON=python3.4 SPHINXBUILD="python3.4 ../sphinx-build.py" 
Making output directory...
Running Sphinx v1.2.2
loading pickled environment... failed: [Errno 2] No such file or directory: '/sw/src/fink.build/sphinx-py34-1.2.2-1/Sphinx-1.2.2/doc/_build/doctrees/environment.pickle'
building [latex]: all documents
updating environment: 55 added, 0 changed, 0 removed
reading sources... [ 12%] domains  
Exception occurred:
  File "/sw/src/fink.build/sphinx-py34-1.2.2-1/Sphinx-1.2.2/sphinx/domains/cpp.py", line 165, in __str__
    return str(self).encode('utf-8')
RuntimeError: maximum recursion depth exceeded while calling a Python object
The full traceback has been saved in /tmp/sphinx-err-7ypozyha.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://bitbucket.org/birkenfeld/sphinx/issues/. Thanks!
make: **\* [latex] Error 1

### execution of make failed, exit code 2

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-03-29 22:39:30+00:00_

Sphinx' setup.py _does_ run 2to3. The problem is that the build appears to be calling "../sphinx-build.py" to build the docs, which is not converted. Only the files in build/ are converted.

So you shouldn't add any 2to3 yourself, but you'll have to use the converted code for doc building if you want to build it with 3.x.

**Comment by shimizukawa** [comment]
It's a user error and there is no update for a long time.
