### ISSUE TITLE
encoding problem with PygmentsBridge for LaTex

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#144]
```
#!python

>>> from sphinx.highlighting import PygmentsBridge
>>> bridge = PygmentsBridge('latex')
>>> ret = bridge.highlight_block('  foo', 'python')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bernhard/src/sphinx/sphinx/highlighting.py", line 172, in highlight_block
    return self.unhighlighted(source)
  File "/home/bernhard/src/sphinx/sphinx/highlighting.py", line 122, in unhighlighted
    source = source.translate(escape_hl_chars)
TypeError: expected a character buffer object
```

The `translate` functions used inside the PygmentsBridge class to escape text for LaTeX output are not robust against non-unicode input. This is at least my interpretation of the Traceback above.

Simply converting into unicode before calling the `translate` functions solves the problem for me... is this an acceptable patch? 

```
diff -r 03f9c91460d2 sphinx/highlighting.py
--- a/sphinx/highlighting.py    Sat Apr 18 10:03:36 2009 +0200
+++ b/sphinx/highlighting.py    Tue Apr 21 18:17:44 2009 +0200
@@ -119,6 +119,7 @@
             return '<pre>' + cgi.escape(source) + '</pre>\n'
         else:
             # first, escape highlighting characters like Pygments does
+            source = unicode(source)
             source = source.translate(escape_hl_chars)
             # then, escape all characters nonrepresentable in LaTeX
             source = source.translate(tex_hl_escape_map)
@@ -189,6 +190,7 @@
                 return highlight(source, lexer, self.fmter[bool(linenos)])
             else:
                 hlsource = highlight(source, lexer, self.fmter[bool(linenos)])
+                hlsource = unicode(hlsource)
                 return hlsource.translate(tex_hl_escape_map)
         except ErrorToken:
             # this is most probably not the selected language,
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/144
- Originally reported by: Bernhard Leiner
- Originally created at: 2009-04-21T18:20:22.875

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-04-28 18:25:23+00:00_

Why do you have non-unicode strings in PygmentsBridge?

**Comment by shimizukawa** [comment]
_From Bernhard Leiner on 2009-04-28 18:58:33+00:00_

Basically this non-unicode string is coming into the PygmentsBridge via an
extension that defines a directive which inserts some generated text as
literal block node:

{{{
#!python

class My_Directive (Directive) :

```
...

def run (self) :

    ...

    generated = generate_text (self.arguments)
    node     = nodes.literal_block (text = generated)
    node['language'] = 'none' # do not try to highlight
    return [node]
```

}}}

This works fine for HTML output but not for LaTeX. Interesting is, that
enforcing unicode encoding of this generated text inside the extension
does not solve the problem. Somehow the "source" parameter of 
PygmentsBridge.highlight_block is always non-unicode. I have not yet
figured out why but maybe it's obvious to you...

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-04-28 21:15:34+00:00_

It's not obvious to me as well.  In any case, I can't see anything wrong with converting to Unicode in highlight(), so I've added that in <<cset ab07eba89591b2909d643aaefd5c432604d0a294>>.  (It will only work if the string is ASCII, though.)
