### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1445]
I have no idea what I'm doing. First look at Sphinx. Novice with Linux as well. I followed the instructions to 'make latexpdf'

This is a copy of the lof file.

Further below is the terminal output.

```
# Sphinx version: 1.2.2
# Python version: 2.7.5+
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
# Loaded extensions:
#   sphinx.ext.oldcmarkup from /usr/local/lib/python2.7/dist-packages/Sphinx-1.2.2-py2.7.egg/sphinx/ext/oldcmarkup.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.2-py2.7.egg/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.2-py2.7.egg/sphinx/application.py", line 217, in build
    os.unlink(envfile)
OSError: [Errno 13] Permission denied: '/home/willem/_build/doctrees/environment.pickle'
```

Terminal output:

```
$ make latexpdf
sphinx-build -b latex -d _build/doctrees   . _build/latex
Running Sphinx v1.2.2
loading pickled environment... done
building [latex]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing Sphinx1.tex... index 
resolving references...
writing... 
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.2-py2.7.egg/sphinx/application.py", line 217, in build
    os.unlink(envfile)
OSError: [Errno 13] Permission denied: '/home/willem/_build/doctrees/environment.pickle'
The full traceback has been saved in /tmp/sphinx-err-HkVpSS.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [latexpdf] Error 1
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1445
- Originally reported by: Anonymous
- Originally created at: 2014-04-09T10:22:17.757

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-04-09 08:42:41+00:00_

I think you executed `sudo make install` once then the `environment.pickle` and some other files under `/home/willem/_build/` were created by root authority.

Please remove `_build` directory once, so that you can `make html` properly.

**Comment by shimizukawa** [comment]
_From [WillemA](https://bitbucket.org/WillemA) on 2014-04-09 09:06:48+00:00_

Sorry for late response. Had to register first (and find this back)

Have deleted  a _build, which was initially created using [...].

'make html' now returned this, which seems good to me.

$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.2.2
loading pickled environment... done
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 1 removed
looking for now-outdated files... none found
no targets are out of date.

Build finished. The HTML pages are in _build/html.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-04-09 09:12:32+00:00_

That's good to know!
