### ISSUE TITLE
Error when parsing variadic templates in C++ domain

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1466]
Exception

```
#!none

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    DefinitionParser('int foo(const A &... a)').parse_function()
  File "/home/viz/workspace/sphinx/sphinx/domains/cpp.py", line 948, in parse_function
    **self._parse_signature())
  File "/home/viz/workspace/sphinx/sphinx/domains/cpp.py", line 845, in _parse_signature
    argname = self._parse_name()
  File "/home/viz/workspace/sphinx/sphinx/domains/cpp.py", line 630, in _parse_name
    return self._parse_name_or_template_arg(False)
  File "/home/viz/workspace/sphinx/sphinx/domains/cpp.py", line 635, in _parse_name_or_template_arg
    self.fail('expected name')
  File "/home/viz/workspace/sphinx/sphinx/domains/cpp.py", line 556, in fail
    (msg, self.pos, self.definition))
sphinx.domains.cpp.DefinitionError: Invalid definition: expected name [error at 17]
  int foo(const A &... a)
```

is thrown when running the code

```
#!none

from sphinx.domains.cpp import DefinitionParser

DefinitionParser('int foo(const A &... a)').parse_function()
```

although `int foo(const A &... a)` is a valid C++11 function signature that uses [variadic templates](http://en.wikipedia.org/wiki/Variadic_template). Example:

```
#!c++

template <typename... A>
int foo(const A &... a) { return 0; }
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1466
- Originally reported by: Victor Zverovich
- Originally created at: 2014-05-12T16:46:09.637

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-05-27 15:21:19+00:00_
- update CHANGES and fix for py3-compat for https://bitbucket.org/birkenfeld/sphinx/pull-request/241. Closes #1466

→ <<cset 9ebee01d19cc28eb12d4b92d2e2b2f49e3b81cf1>>
