### ISSUE TITLE
Sphinx has trouble with some descriptors

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1471]
I've just updated a project (https://bitbucket.org/ericgazoni/openpyxl) to use Sphinx more extensively and hit a roadblock in the way Sphinx handled some descriptors we have. It looks like Sphinx is having trouble with the Alias decorator. It could very well be that this decorator is wrong but the relevant tests work fine.

This is the traceback:

```
#!python

/Users/charlieclark/Projects/openpyxl/doc/source/openpyxl.worksheet.rst:10: WARNING: autodoc: failed to import attribute u'ColumnDimension.auto_size' from module u'openpyxl.worksheet.dimensions'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/charlieclark/Projects/openpyxl/.tox/doc/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 342, in import_object
    obj = self.get_attr(obj, part)
  File "/Users/charlieclark/Projects/openpyxl/.tox/doc/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 241, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/Users/charlieclark/Projects/openpyxl/.tox/doc/lib/python2.7/site-packages/sphinx/util/inspect.py", line 114, in safe_getattr
    raise AttributeError(name)
AttributeError: auto_size
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1471
- Originally reported by: Charlie Clark
- Originally created at: 2014-05-20T15:11:41.028

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-05-20 16:28:42+00:00_

Duplicate of #1254.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-05-20 16:29:42+00:00_

Please check #1254 issue that suggest a workaround for that behavior. Thanks.
