### ISSUE TITLE
make in docs can't find sphinx_bootstrap_theme

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1472]
```

$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Making output directory...
Running Sphinx v1.2.2

Exception occurred:
  File "conf.py", line 17, in <module>
    import sphinx_bootstrap_theme
ImportError: No module named sphinx_bootstrap_theme
The full traceback has been saved in /var/folders/5b/16q9mkz520g517_mpb7xwh0w0000gn/T/sphinx-err-eSgFxz.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1

Full text of log:

# Sphinx version: 1.2.2
# Python version: 2.7.5
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
# Loaded extensions:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Sphinx-1.2.2-py2.7.egg/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/Library/Python/2.7/site-packages/Sphinx-1.2.2-py2.7.egg/sphinx/application.py", line 107, in __init__
    confoverrides or {}, self.tags)
  File "/Library/Python/2.7/site-packages/Sphinx-1.2.2-py2.7.egg/sphinx/config.py", line 229, in __init__
    execfile_(filename, config)
  File "/Library/Python/2.7/site-packages/Sphinx-1.2.2-py2.7.egg/sphinx/util/pycompat.py", line 105, in execfile_
    exec code in _globals
  File "conf.py", line 17, in <module>
    import sphinx_bootstrap_theme
ImportError: No module named sphinx_bootstrap_theme

```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1472
- Originally reported by: Anonymous
- Originally created at: 2014-05-23T21:10:01.454

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-05-24 15:42:35+00:00_

It's a installation problem about sphinx_bootstrap_theme. Please check a installation procedure that is described by `sphinx_bootstrap_theme` documentation. If you can't correct it, please let me know the procedure. 
Thanks.
