### ISSUE TITLE
Error when building sqlalchemy documentation

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1481]
The backtrace I got from running sphinx on sqlalchemy's documentation asked me to send this bug to this site...so...here it is!

Here is my backtrace:

```
Running Sphinx v1.2b3
loading pickled environment... not yet created
loading intersphinx inventory from http://pythonhosted.org/psycopg2/objects.inv...
loading intersphinx inventory from http://alembic.readthedocs.org/en/latest/objects.inv...
building [html]: targets for 80 source files that are out of date
updating environment: 80 added, 0 changed, 0 removed
The name of the builder is: htmllog/changelog_07                                
Exception occurred:
  File "/usr/local/lib/python2.7/site-packages/changelog-0.1.1-py2.7.egg/changelog.py", line 184, in _render_rec
    refuri = render &#37; refname
TypeError: unsupported operand type(s) for &#37;: 'dict' and 'unicode'
The full traceback has been saved in /var/folders/s5/0kkvfdrs3qnbkdq0pffkmgm00000gn/T/sphinx-err-RNy6B9.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-users/>,
or report them in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
```

And here is the log:

```
# Sphinx version: 1.2b3
# Python version: 2.7.5
# Docutils version: 0.11 release
# Jinja2 version: 2.7.1
# Loaded extensions:
#   builder.sqlformatter from /Users/mikesolomon/devel/sqlalchemy/doc/build/builder/sqlformatter.pyc
#   sphinx.ext.autodoc from /Library/Python/2.7/site-packages/Sphinx-1.2b3-py2.7.egg/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx from /Library/Python/2.7/site-packages/Sphinx-1.2b3-py2.7.egg/sphinx/ext/intersphinx.pyc
#   builder.autodoc_mods from /Users/mikesolomon/devel/sqlalchemy/doc/build/builder/autodoc_mods.pyc
#   changelog from /usr/local/lib/python2.7/site-packages/changelog-0.1.1-py2.7.egg/changelog.pyc
#   builder.viewsource from /Users/mikesolomon/devel/sqlalchemy/doc/build/builder/viewsource.pyc
#   builder.dialect_info from /Users/mikesolomon/devel/sqlalchemy/doc/build/builder/dialect_info.pyc
#   sphinx_paramlinks from /usr/local/lib/python2.7/site-packages/sphinx_paramlinks-0.2.2-py2.7.egg/sphinx_paramlinks/__init__.pyc
#   sphinx.ext.oldcmarkup from /Library/Python/2.7/site-packages/Sphinx-1.2b3-py2.7.egg/sphinx/ext/oldcmarkup.pyc
#   builder.mako from /Users/mikesolomon/devel/sqlalchemy/doc/build/builder/mako.pyc
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Sphinx-1.2b3-py2.7.egg/sphinx/cmdline.py", line 246, in main
    app.build(force_all, filenames)
  File "/Library/Python/2.7/site-packages/Sphinx-1.2b3-py2.7.egg/sphinx/application.py", line 212, in build
    self.builder.build_update()
  File "/Library/Python/2.7/site-packages/Sphinx-1.2b3-py2.7.egg/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' &#37; len(to_build))
  File "/Library/Python/2.7/site-packages/Sphinx-1.2b3-py2.7.egg/sphinx/builders/__init__.py", line 234, in build
    purple, length):
  File "/Library/Python/2.7/site-packages/Sphinx-1.2b3-py2.7.egg/sphinx/builders/__init__.py", line 134, in status_iterator
    for item in iterable:
  File "/Library/Python/2.7/site-packages/Sphinx-1.2b3-py2.7.egg/sphinx/environment.py", line 470, in update_generator
    self.read_doc(docname, app=app)
  File "/Library/Python/2.7/site-packages/Sphinx-1.2b3-py2.7.egg/sphinx/environment.py", line 618, in read_doc
    pub.publish()
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/core.py", line 217, in publish
    self.settings)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/parsers/rst/states.py", line 2961, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/Library/Python/2.7/site-packages/docutils-0.11-py2.7.egg/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/usr/local/lib/python2.7/site-packages/changelog-0.1.1-py2.7.egg/changelog.py", line 124, in run
    self._render_rec(rec, section, cat, append_sec)
  File "/usr/local/lib/python2.7/site-packages/changelog-0.1.1-py2.7.egg/changelog.py", line 184, in _render_rec
    refuri = render &#37; refname
TypeError: unsupported operand type(s) for &#37;: 'dict' and 'unicode'
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1481
- Originally reported by: [mike_solomon](https://bitbucket.org/mike_solomon)
- Originally created at: 2014-06-06T16:08:57.286

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-06-07 23:41:27+00:00_

Look like you are using old version `changelog` package.
The issue can be reproduced with `changelog-0.1.1`, however, after updating into `changelog-0.3.4` the issue is gone.

Please update it and try again.
