### ISSUE TITLE
Make "build_sphinx" error more user-friendly when importing setup.py from conf.py

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1499]
If a project imports "setup.py" from "conf.py", as `import setup`, then running the "build_sphinx" fails with a somewhat cryptic error message, due to `setup` being already reserved for Sphinx use.

```
Traceback (most recent call last):
  File "setup.py", line 128, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "C:\Python27\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "(...)\sphinx-1.2.2-py2.7.egg\sphinx\setup_command.py", line 158, in run
    freshenv=self.fresh_env)
  File "(...)\sphinx-1.2.2-py2.7.egg\sphinx\application.py", line 128, in __init__
    self.config.setup(self)
TypeError: 'module' object is not callable
```

Maybe this edge case could be detected and give the user a hint?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1499
- Originally reported by: [marciof](https://bitbucket.org/marciof)
- Originally created at: 2014-06-28T09:35:55.767

**Comment by shimizukawa** [comment]
_From Markus Zapke-Gründemann on 2014-06-30 09:35:10+00:00_

Why are you importing `setup.py`? The import triggers the `setup()` function which seems to cause the traceback. If you want to use any metadata of your package in `conf.py` you should put it into a separate file.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-06-30 12:49:19+00:00_

The `setup` keyword in the conf.py is reserved:
http://sphinx-doc.org/config.html#general-configuration

However, the error message [marciof](https://bitbucket.org/marciof) encounted is kindless, I think so too. I'll fix it to emit a warning message for the situation.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-06-30 13:55:00+00:00_
- With non-callable `setup` in a conf.py, now sphinx-build emits user-friendly error message. Closes #1499

→ <<cset f781f55b28662cf759f06cda48f7b48a6c0c70e6>>

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-06-30 13:57:11+00:00_

BTW, I agree to [Markus Zapke-Gründemann](https://bitbucket.org/keimlink) opinion. `setup.py` shouldn't be imported from any other module.

**Comment by shimizukawa** [comment]
_From [marciof](https://bitbucket.org/marciof) on 2014-06-30 19:01:12+00:00_

[Markus Zapke-Gründemann](https://bitbucket.org/keimlink), I'm importing because I use it as both a regular `setup.py` script and as a module with package metadata. Why should the metadata be put into a separate file?

**Comment by shimizukawa** [comment]
_From Markus Zapke-Gründemann on 2014-07-17 09:40:17+00:00_

[marciof](https://bitbucket.org/marciof) There are several reasons for not putting the metadata into `setup.py`.
1. To prevent side effects like you saw with Sphinx's `conf.py`
2. `setup.py`'s only purpose is to trigger the installation of the package (or better "distribution"). So it should be as simple as possible.
3. If you use tools like [bumpversion](https://pypi.python.org/pypi/bumpversion) it is easier to update the version number if it's in a separate file.

Many Python developers use the `__init__.py` file to store this information in variables like `__version__`  or `__author__`. See [PEP 396](http://legacy.python.org/dev/peps/pep-0396/) for examples. You can do this also if just have a single module. In my opinion PEP 396 is a good guideline even if it has been deferred.
