### ISSUE TITLE
AttributeError: 'list' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1507]
Hi, 
make html produce:

```
# Sphinx version: 1.2.2
# Python version: 2.7.5
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Sphinx-1.2.2-py2.7.egg/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/lib/python2.7/site-packages/Sphinx-1.2.2-py2.7.egg/sphinx/application.py", line 139, in __init__
    self._init_builder(buildername)
  File "/usr/lib/python2.7/site-packages/Sphinx-1.2.2-py2.7.egg/sphinx/application.py", line 200, in _init_builder
    self.builder = builderclass(self)
  File "/usr/lib/python2.7/site-packages/Sphinx-1.2.2-py2.7.egg/sphinx/builders/__init__.py", line 68, in __init__
    self.init()
  File "/usr/lib/python2.7/site-packages/Sphinx-1.2.2-py2.7.egg/sphinx/builders/html.py", line 108, in init
    self.init_templates()
  File "/usr/lib/python2.7/site-packages/Sphinx-1.2.2-py2.7.egg/sphinx/builders/html.py", line 141, in init_templates
    warn=self.warn)
  File "/usr/lib/python2.7/site-packages/Sphinx-1.2.2-py2.7.egg/sphinx/theming.py", line 44, in init_themes
    themedir = path.join(confdir, themedir)
  File "/usr/lib64/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'list' object has no attribute 'startswith'
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1507
- Originally reported by: Anonymous
- Originally created at: 2014-07-11T19:01:30.056

**Comment by shimizukawa** [comment]
_From mrtom31 mrtom31 on 2014-07-11 17:20:25+00:00_

```
#!python
get_html_theme_path()
```

returns a list. So I have to change:

```
#!python
html_theme_path = [sphinx_bootstrap_theme.get_html_theme_path()]
```

into:

```
#!python
get_html_theme_path()
```

returns a list. So I have to change:

```
#!python
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()
```

it's not a bug actually.
But it would be nice to upldate doc and remove brackets.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-07-12 01:08:10+00:00_

https://pypi.python.org/pypi/sphinx-bootstrap-theme/0.3.1#installation describes the `html_theme_path` setting as:

```
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()
```

If you see any wrong documentation, please let me know. (I think Sphinx documentation doesn't mention to sphinx_bootstrap_theme).
