### ISSUE TITLE
IOError with sphinx.ext.graphviz

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1521]
This works:

```
.. graph:: bla

   "First"  -- "Second";
```

Now I want to switch to this, which would also work:

```
.. digraph:: bla

   "First"  -> "Second";
```

But instead by mistake write:

```
.. graph:: bla

   "First"  -> "Second";
```

This doesn't work and says "Please also report this if it was a user error, so that a better error message can be provided next time."

```
# Sphinx version: 1.2b1
# Python version: 2.7.2
# Docutils version: 0.10 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\cmdline.py", line 247, in main
    app.build(force_all, filenames)
  File "c:\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\application.py", line 211, in build
    self.builder.build_update()
  File "c:\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\builders\__init__.py", line 211, in build_update
    'out of date' &#37; len(to_build))
  File "c:\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\builders\__init__.py", line 267, in build
    self.write(docnames, list(updated_docnames), method)
  File "c:\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\builders\__init__.py", line 310, in write
    self._write_serial(sorted(docnames), warnings)
  File "c:\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\builders\__init__.py", line 323, in _write_serial
    self.write_doc(docname, doctree)
  File "c:\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\builders\html.py", line 432, in write_doc
    self.docwriter.write(doctree, destination)
  File "c:\Python27\lib\site-packages\docutils-0.10-py2.7.egg\docutils\writers\__init__.py", line 80, in write
    self.translate()
  File "c:\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\writers\html.py", line 41, in translate
    self.document.walkabout(visitor)
  File "c:\Python27\lib\site-packages\docutils-0.10-py2.7.egg\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "c:\Python27\lib\site-packages\docutils-0.10-py2.7.egg\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "c:\Python27\lib\site-packages\docutils-0.10-py2.7.egg\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "c:\Python27\lib\site-packages\docutils-0.10-py2.7.egg\docutils\nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "c:\Python27\lib\site-packages\docutils-0.10-py2.7.egg\docutils\nodes.py", line 1627, in dispatch_visit
    return method(node)
  File "c:\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\ext\graphviz.py", line 237, in html_visit_graphviz
    render_dot_html(self, node, node['code'], node['options'])
  File "c:\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\ext\graphviz.py", line 213, in render_dot_html
    mapfile = open(outfn + '.map', 'rb')
IOError: [Errno 2] No such file or directory: u'C:\\SphinxProject\\_build\\html\\_images\\graphviz-367d8a20015790dd3c1b80948bd0d2a28865e3ca.png.map'

```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1521
- Originally reported by: Anonymous
- Originally created at: 2014-07-25T11:04:11.896

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2014-07-27 11:43:50+00:00_

This has been fixed in 29ff88d8df23, which went into v1.2.1.
