### ISSUE TITLE
Unicode Problems

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1525]
Hi,
Not quite sure what is the problem. Sphinx worked for days and weeks without any problem until today. I suspect it has something to do with unicode in my code.
I have few strings like this:
u'\xb0C'

I will try figuring out on my own but I don't know much about sphinx internals.
Thank you very much for creating such an amazing tool.
Cheers,
Kirill

The log containing error is listed bellow

```
#!python


# Sphinx version: 1.2.2
# Python version: 2.7.3
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Loaded extensions:
#   sphinx.ext.autodoc from C:\Python27\lib\site-packages\sphinx\ext\autodoc.pyc
#   sphinx.ext.intersphinx from C:\Python27\lib\site-packages\sphinx\ext\intersphinx.pyc
#   sphinx.ext.doctest from C:\Python27\lib\site-packages\sphinx\ext\doctest.pyc
#   sphinx.ext.coverage from C:\Python27\lib\site-packages\sphinx\ext\coverage.pyc
#   sphinx.ext.pngmath from C:\Python27\lib\site-packages\sphinx\ext\pngmath.pyc
#   sphinx.ext.todo from C:\Python27\lib\site-packages\sphinx\ext\todo.pyc
#   sphinx.ext.ifconfig from C:\Python27\lib\site-packages\sphinx\ext\ifconfig.pyc
#   sphinx.ext.oldcmarkup from C:\Python27\lib\site-packages\sphinx\ext\oldcmarkup.pyc
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\sphinx\cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "C:\Python27\lib\site-packages\sphinx\application.py", line 212, in build
    self.builder.build_update()
  File "C:\Python27\lib\site-packages\sphinx\builders\__init__.py", line 214, in build_update
    'out of date' &#37; len(to_build))
  File "C:\Python27\lib\site-packages\sphinx\builders\__init__.py", line 234, in build
    purple, length):
  File "C:\Python27\lib\site-packages\sphinx\builders\__init__.py", line 134, in status_iterator
    for item in iterable:
  File "C:\Python27\lib\site-packages\sphinx\environment.py", line 477, in update_generator
    self.read_doc(docname, app=app)
  File "C:\Python27\lib\site-packages\sphinx\environment.py", line 624, in read_doc
    pub.publish()
  File "C:\Python27\lib\site-packages\docutils\core.py", line 217, in publish
    self.settings)
  File "C:\Python27\lib\site-packages\docutils\readers\__init__.py", line 72, in read
    self.parse()
  File "C:\Python27\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    input_source=document['source'])
  File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "C:\Python27\lib\site-packages\docutils\parsers\rst\states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "C:\Python27\lib\site-packages\sphinx\ext\autodoc.py", line 1401, in run
    documenter.generate(more_content=self.content)
  File "C:\Python27\lib\site-packages\sphinx\ext\autodoc.py", line 733, in generate
    self.analyzer.find_attr_docs()
  File "C:\Python27\lib\site-packages\sphinx\pycode\__init__.py", line 268, in find_attr_docs
    attr_visitor.visit(self.parsetree)
  File "C:\Python27\lib\site-packages\sphinx\pycode\nodes.py", line 201, in visit
    return visitor(node)
  File "C:\Python27\lib\site-packages\sphinx\pycode\nodes.py", line 207, in generic_visit
    self.visit(child)
  File "C:\Python27\lib\site-packages\sphinx\pycode\nodes.py", line 201, in visit
    return visitor(node)
  File "C:\Python27\lib\site-packages\sphinx\pycode\__init__.py", line 135, in visit_simple_stmt
    docstring = literals.evalString(node[0].value, self.encoding)
  File "C:\Python27\lib\site-packages\sphinx\pycode\pgen2\literals.py", line 84, in evalString
    return regex.sub(repl, s)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 0: ordinal not in range(128)

```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1525
- Originally reported by: Anonymous
- Originally created at: 2014-07-30T23:20:03.337

**Comment by shimizukawa** [comment]
_From Kirill Belyayev on 2014-07-30 21:33:09+00:00_

Yep, changed u'\xb0C' to u'°C' and it compiled.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-08-12 04:53:24+00:00_

[Kirill Belyayev](https://bitbucket.org/Barmaley) I can't reproduce the issue. If your problem has been resolved, it's ok, please close this ticket. If not, please attach small sample to reproduce it. In ether case, I want to know what happen ;)  Thanks!

**Comment by andreacassioli** [comment]
Hi I have the same issue with a bibtex file in unicode format. I pass the file to sphinbibtex  and I get 

checking for /home/andrea/mosekprj/dev/docs/manuals/sphinx/matlab-toolbox/source/biblio.bib in bibtex cache... not found  
parsing bibtex file /home/andrea/mosekprj/dev/docs/manuals/sphinx/matlab-toolbox/source/biblio.bib... 
Exception occurred:
  File "/home/andrea/.local/lib/python2.6/site-packages/latexcodec/lexer.py", line 382, in decode
    raise ValueError(e)
ValueError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-a0kI5s.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at http://groups.google.com/group/sphinx-users/,
or report them in the tracker at http://bitbucket.org/birkenfeld/sphinx/issues/. Thanks!

Any ideas?

**Comment by shimizukawa** [comment]
@andreacassioli I think your error is not same as this issue's, it seems latexcodec package caused the error. Please make another ticket with full traceback (As error saied "The full traceback has been saved in /tmp/sphinx-err-a0kI5s.log") or please contact to package owner.
