### ISSUE TITLE
Got RuntimeError with circular referenced toctree

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1540]
I create below as a master_doc::

```
.. toctree::

   index
```

and I build latex docs, and then, I got RuntimeError::

```
make latex                                                                                              ~/work/tmp/foo
../bin/sphinx-build -b latex -d _build/doctrees   . _build/latex
Making output directory...
Running Sphinx v1.2.2
loading pickled environment... not yet created
building [latex]: all documents
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100&#37;] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing a.tex... index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index index /Users/tkomiya/work/tmp/foo/index.rst: WARNING: toctree contains ref to nonexisting file 'index'

resolving references...

Exception occurred:
  File "/Users/tkomiya/.buildout/buildout-eggs/docutils-0.12-py2.7.egg/docutils/nodes.py", line 193, in _fast_traverse
    if isinstance(self, cls):
RuntimeError: maximum recursion depth exceeded while calling a Python object
The full traceback has been saved in /var/folders/2s/79pf79d94r9gxhzl4kpztrr00000gp/T/sphinx-err-QuRnB9.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [latex] Error 1
```

```
# Sphinx version: 1.2.2
# Python version: 2.7.7
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Loaded extensions:
#   sphinx.ext.oldcmarkup from /Users/tkomiya/.buildout/buildout-eggs/Sphinx-1.2.2-py2.7.egg/sphinx/ext/oldcmarkup.pyc
Traceback (most recent call last):
  File "/Users/tkomiya/.buildout/buildout-eggs/Sphinx-1.2.2-py2.7.egg/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/Users/tkomiya/.buildout/buildout-eggs/Sphinx-1.2.2-py2.7.egg/sphinx/application.py", line 212, in build
    self.builder.build_update()
  File "/Users/tkomiya/.buildout/buildout-eggs/Sphinx-1.2.2-py2.7.egg/sphinx/builders/__init__.py", line 209, in build_update
    self.build(['__all__'], to_build)
  File "/Users/tkomiya/.buildout/buildout-eggs/Sphinx-1.2.2-py2.7.egg/sphinx/builders/__init__.py", line 276, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/tkomiya/.buildout/buildout-eggs/Sphinx-1.2.2-py2.7.egg/sphinx/builders/latex.py", line 97, in write
    self.config.latex_appendices or []))
  File "/Users/tkomiya/.buildout/buildout-eggs/Sphinx-1.2.2-py2.7.egg/sphinx/builders/latex.py", line 133, in assemble_doctree
    self.env.resolve_references(largetree, indexfile, self)
  File "/Users/tkomiya/.buildout/buildout-eggs/Sphinx-1.2.2-py2.7.egg/sphinx/environment.py", line 1327, in resolve_references
    for node in doctree.traverse(addnodes.pending_xref):
  File "/Users/tkomiya/.buildout/buildout-eggs/docutils-0.12-py2.7.egg/docutils/nodes.py", line 252, in traverse
    return self._fast_traverse(condition)
  File "/Users/tkomiya/.buildout/buildout-eggs/docutils-0.12-py2.7.egg/docutils/nodes.py", line 196, in _fast_traverse
    result.extend(child._fast_traverse(cls))
  File "/Users/tkomiya/.buildout/buildout-eggs/docutils-0.12-py2.7.egg/docutils/nodes.py", line 196, in _fast_traverse
    result.extend(child._fast_traverse(cls))
...
  File "/Users/tkomiya/.buildout/buildout-eggs/docutils-0.12-py2.7.egg/docutils/nodes.py", line 196, in _fast_traverse
    result.extend(child._fast_traverse(cls))
  File "/Users/tkomiya/.buildout/buildout-eggs/docutils-0.12-py2.7.egg/docutils/nodes.py", line 193, in _fast_traverse
    if isinstance(self, cls):
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

If I build the document to HTML, sphinx warns about circular reference.

```
/Users/tkomiya/work/tmp/foo/index.rst:: WARNING: circular toctree references detected, ignoring: index <- index
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1540
- Originally reported by: Takeshi Komiya
- Originally created at: 2014-08-19T13:19:02.095

**Comment by tushortz** [comment]
I think you have toctrees in more than one document. TOCTREE should only be in the index.rst(main or parent) page

**Comment by shimizukawa** [comment]
@tushortz actually no. toctree directive avoid circular references, exclude latex builder. I think latex builder still has the issue.

**Comment by tushortz** [comment]
Well maybe you are right. I'm just a beginner on using sphinx and got
similar error and fixed it that way. It was searching the error I got this
link and thought I may be of help.

But yes hope it gets solved
