### ISSUE TITLE
no attribute 'verbatim'

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1549]
Dear, 

I recently have downloaded the sphinxtr project, when I tried the make command I saw the exception message posted after. I am not using a virtualenv, but I installed al the requirements. 

```
Exception occurred:
  File "/home/emiliano/Desktop/tmp/tesis_rst/sphinxtr-master/extensions/latex_mods.py", line 41, in visit_Text
    if self.verbatim is not None:
AttributeError: DocTranslator instance has no attribute 'verbatim'
The full traceback has been saved in /tmp/sphinx-err-xPpC_Z.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
Makefile:108: recipe for target 'latexpdf' failed
make: *** [latexpdf] Error 1
```

Here is the complete traceback:

cat /tmp/sphinx-err-xPpC_Z.log

```
#!python

# Sphinx version: 1.2.2
# Python version: 2.7.8
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Loaded extensions:
#   fix_equation_ref from /home/emiliano/Desktop/tmp/tesis_rst/sphinxtr-master/extensions/fix_equation_ref.pyc
#   numfig from /home/emiliano/Desktop/tmp/tesis_rst/sphinxtr-master/extensions/numfig.pyc
#   numsec from /home/emiliano/Desktop/tmp/tesis_rst/sphinxtr-master/extensions/numsec.pyc
#   figtable from /home/emiliano/Desktop/tmp/tesis_rst/sphinxtr-master/extensions/figtable.pyc
#   sphinx.ext.mathjax from /usr/lib/python2.7/dist-packages/sphinx/ext/mathjax.pyc
#   singletext from /home/emiliano/Desktop/tmp/tesis_rst/sphinxtr-master/extensions/singletext.pyc
#   sphinx.ext.oldcmarkup from /usr/lib/python2.7/dist-packages/sphinx/ext/oldcmarkup.pyc
#   singlehtml_toc from /home/emiliano/Desktop/tmp/tesis_rst/sphinxtr-master/extensions/singlehtml_toc.pyc
#   natbib from /home/emiliano/Desktop/tmp/tesis_rst/sphinxtr-master/extensions/natbib/__init__.pyc
#   sphinx.ext.ifconfig from /usr/lib/python2.7/dist-packages/sphinx/ext/ifconfig.pyc
#   subfig from /home/emiliano/Desktop/tmp/tesis_rst/sphinxtr-master/extensions/subfig.pyc
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 212, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 209, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 276, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/emiliano/Desktop/tmp/tesis_rst/sphinxtr-master/extensions/latex_mods.py", line 196, in write
    super(CustomLaTeXBuilder, self).write(*ignored)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/latex.py", line 105, in write
    docwriter.write(doctree, destination)
  File "/usr/lib/python2.7/dist-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python2.7/dist-packages/sphinx/writers/latex.py", line 95, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/home/emiliano/Desktop/tmp/tesis_rst/sphinxtr-master/extensions/latex_mods.py", line 41, in visit_Text
    if self.verbatim is not None:
AttributeError: DocTranslator instance has no attribute 'verbatim'
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1549
- Originally reported by: Emiliano López
- Originally created at: 2014-08-29T06:35:47.815

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-08-29 06:54:46+00:00_

Hi, the traceback indicates that the problem is caused by sphinxtr (not sphinx). Please report it to the sphinxtr owner: https://github.com/jterrace/sphinxtr/issues

Thanks.
