### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'parent'

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1557]
Not sure if this is a real issue or not. Traceback is:

```
#!python

# Sphinx version: 1.2.2
# Python version: 2.7.6
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
# Loaded extensions:
#   sphinx.ext.autodoc from /usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.pyc
#   javasphinx from /usr/local/lib/python2.7/dist-packages/javasphinx/__init__.pyc
#   rst2pdf.pdfbuilder from /usr/local/lib/python2.7/dist-packages/rst2pdf/pdfbuilder.pyc
#   sphinxcontrib.httpdomain from /usr/local/lib/python2.7/dist-packages/sphinxcontrib/httpdomain.py
#   sphinx.ext.pngmath from /usr/lib/python2.7/dist-packages/sphinx/ext/pngmath.pyc
#   sphinx.ext.ifconfig from /usr/lib/python2.7/dist-packages/sphinx/ext/ifconfig.pyc
#   sphinx.ext.oldcmarkup from /usr/lib/python2.7/dist-packages/sphinx/ext/oldcmarkup.pyc
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 212, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 276, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 320, in write
    self._write_serial(sorted(docnames), warnings)
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 331, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 1113, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 1388, in resolve_references
    node.replace_self(newnode or contnode)
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 955, in replace_self
    self.parent.replace(self, new)
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 933, in replace
    self[index:index+1] = new
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 586, in __setitem__
    self.setup_child(node)
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 93, in setup_child
    child.parent = self
AttributeError: 'unicode' object has no attribute 'parent'
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1557
- Originally reported by: Anonymous
- Originally created at: 2014-09-03T16:12:07.145

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-09-03 14:42:42+00:00_

This may be from httpdomain returning wrong things from its resolver function. Can you check if you have the latest version of httpdomain?

**Comment by shimizukawa** [comment]
_From Jay Houghton on 2014-09-03 17:48:42+00:00_

I'm using sphinxcontrib_httpdomain-1.3.0 which is the latest and dated July 31 2014. This issue could be related to my httpdomain issue that I also filed:

[https://bitbucket.org/birkenfeld/sphinx-contrib/issue/79/httpdomain-nonetype-object-has-no](https://bitbucket.org/birkenfeld/sphinx-contrib/issue/79/httpdomain-nonetype-object-has-no)

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-09-03 19:59:17+00:00_

You could try running sphinx-build with `-P` and then doing `p child` at the Pdb prompt to see what the offending string is.

If that doesn't clarify the problem and you're familiar with Pdb, it would also be interesting to go into the resolve_references stackframe and see what `node` and `newnode or contnode` are.

**Comment by shimizukawa** [comment]
_From Jay Houghton on 2014-09-03 21:15:32+00:00_

Gosh, I don't have any Python skills (yet), however my instinct tells me you are correct about httpdomain not returning proper data structure. I think this issue should be dependent upon the resolution of [https://bitbucket.org/birkenfeld/sphinx-contrib/issue/79/httpdomain-nonetype-object-has-no](https://bitbucket.org/birkenfeld/sphinx-contrib/issue/79/httpdomain-nonetype-object-has-no)

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-09-04 06:14:03+00:00_

OK, I've added a pointer there.
