### ISSUE TITLE
IPython notebooks fail to build

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1566]
Running on Linux Mint 17, I cannot build my Sphinx docs with IPython notebooks, due to the fact I get the following error as demonstrated in this Sphinx log:

```
#!bash

# Sphinx version: 1.2.3
# Python version: 2.7.6
# Docutils version: 0.12 release
# Jinja2 version: 2.7.2
# Loaded extensions:
#   sphinx.ext.autodoc from /usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/ext/autodoc.pyc
#   sphinx.ext.mathjax from /usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/ext/mathjax.pyc
#   numpydoc from /home/saubin/git/nengo-docs/src/numpydoc/numpydoc/__init__.py
#   sphinx.ext.viewcode from /usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/ext/viewcode.pyc
#   nengo.utils.docutils from /home/saubin/git/nengo-docs/nengo/utils/docutils.pyc
#   sphinx.ext.todo from /usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/ext/todo.pyc
#   sphinx.ext.autosummary from /usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/ext/autosummary/__init__.pyc
#   sphinx.ext.oldcmarkup from /usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/ext/oldcmarkup.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/application.py", line 220, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/builders/__init__.py", line 234, in build
    purple, length):
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/builders/__init__.py", line 134, in status_iterator
    for item in iterable:
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/environment.py", line 478, in update_generator
    self.read_doc(docname, app=app)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.2.3-py2.7.egg/sphinx/environment.py", line 628, in read_doc
    pub.publish()
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2961, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/local/lib/python2.7/dist-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/home/saubin/git/nengo-docs/nengo/utils/docutils.py", line 97, in run
    evaluated_html = ipext.export_html(nb_eval)
  File "/home/saubin/git/nengo-docs/nengo/utils/ipython.py", line 141, in export_html
    output, resources = exporter.from_notebook_node(nb)
  File "/usr/local/lib/python2.7/dist-packages/IPython/nbconvert/exporters/templateexporter.py", line 209, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python2.7/dist-packages/IPython/nbconvert/exporters/exporter.py", line 119, in from_notebook_node
    if 'language' in nb['metadata']:
TypeError: string indices must be integers, not str
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1566
- Originally reported by: Sean Aubin
- Originally created at: 2014-09-13T21:52:04.162

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-09-13 20:01:47+00:00_

Hi,

this indicates a bug/incompatibility in the "nengo.utils.docutils" extension. Can you report it to its authors?

**Comment by shimizukawa** [comment]
_From Sean Aubin on 2014-09-13 20:04:20+00:00_

_dies of embarrassment_

How the hell did I miss that? I can't believe my speed-reading skills failed me this hard. My apologies for wasting your time.

**Comment by shimizukawa** [comment]
_From Sean Aubin on 2014-09-13 20:06:06+00:00_

It's not a Sphinx problem. It's a Nengo problem.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-09-13 20:11:46+00:00_

No worries. One bug less for us to fix :)
