### ISSUE TITLE
autofunction failing after updating Sphinx

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1578]
I have a glossary of statistical distributions that I use `autofunction` to document in Sphinx, which until I updated to 1.2.3 worked flawlessly to generate documentation. However, these calls all fail now, with errors like the following:

```
/Users/fonnescj/GitHub/pymc2/docs/distributions.rst:21: WARNING: autodoc: failed to import function u'bernoulli_like' from module u'pymc.distributions'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 342, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 241, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/local/lib/python2.7/site-packages/sphinx/util/inspect.py", line 114, in safe_getattr
    raise AttributeError(name)
AttributeError: bernoulli_like
```

We have been building these docs for 5+ years with Sphinx, so I'm thinking there has been some change which has precipitated this.  In any case, any guidance to getting it resolved would be helpful.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1578
- Originally reported by: [fonnesbeck_](https://bitbucket.org/fonnesbeck_)
- Originally created at: 2014-09-24T16:39:29.562

**Comment by shimizukawa** [comment]
_From [fonnesbeck_](https://bitbucket.org/fonnesbeck_) on 2014-09-24 14:40:20+00:00_

If its helpful, the source looks like this:

```
This section describes the likelihood functions of these distributions.

.. module:: pymc.distributions

Discrete distributions
======================

.. autofunction:: bernoulli_like

.. autofunction:: binomial_like

.. autofunction:: categorical_like
```

**Comment by shimizukawa** [comment]
_From [fonnesbeck_](https://bitbucket.org/fonnesbeck_) on 2014-09-24 14:42:27+00:00_

User error. Apologies.
