### ISSUE TITLE
TemplateNotFound error in jinja code when upgrading to 0.6.1

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#158]
We have a separate sidebar for our website and our api docs.  The web sidebar extends the api one.  The code works with sphinx version 0.5.1.  When I upgraded to version 0.6.1 I get the following traceback.

Traceback (most recent call last):
  File "/Users/cburns/local/lib/python2.5/site-packages/Sphinx-0.6.1-py2.5.egg/sphinx/cmdline.py", line 172, in main
    app.build(all_files, filenames)
  File "/Users/cburns/local/lib/python2.5/site-packages/Sphinx-0.6.1-py2.5.egg/sphinx/application.py", line 129, in build
    self.builder.build_update()
  File "/Users/cburns/local/lib/python2.5/site-packages/Sphinx-0.6.1-py2.5.egg/sphinx/builders/**init**.py", line 255, in build_update
    'out of date' &#37; len(to_build))
  File "/Users/cburns/local/lib/python2.5/site-packages/Sphinx-0.6.1-py2.5.egg/sphinx/builders/**init**.py", line 310, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/cburns/local/lib/python2.5/site-packages/Sphinx-0.6.1-py2.5.egg/sphinx/builders/**init**.py", line 349, in write
    self.write_doc(docname, doctree)
  File "/Users/cburns/local/lib/python2.5/site-packages/Sphinx-0.6.1-py2.5.egg/sphinx/builders/html.py", line 351, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/Users/cburns/local/lib/python2.5/site-packages/Sphinx-0.6.1-py2.5.egg/sphinx/builders/html.py", line 648, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/Users/cburns/local/lib/python2.5/site-packages/Sphinx-0.6.1-py2.5.egg/sphinx/jinja2glue.py", line 81, in render
    return self.environment.get_template(template).render(context)
  File "/Users/cburns/local/lib/python2.5/site-packages/Sphinx-0.6.1-py2.5.egg/sphinx/themes/basic/page.html", line 1, in top-level template code
    {&#37; extends "layout.html" &#37;}
  File "/Users/cburns/src/nipy-repo/trunk-lp/doc/www/_templates/layout.html", line 1, in top-level template code
    {&#37; extends "!layout.html" &#37;}
  File "/Users/cburns/local/lib/python2.5/site-packages/Sphinx-0.6.1-py2.5.egg/sphinx/themes/basic/layout.html", line 157, in top-level template code
    {&#37;\- block sidebar1 &#37;} {# possible location for sidebar #} {&#37; endblock &#37;}
  File "/Users/cburns/src/nipy-repo/trunk-lp/doc/www/_templates/layout.html", line 31, in block "sidebar1"
    {&#37; block sidebar1 &#37;}{{ sidebar() }}{&#37; endblock &#37;}
  File "/Users/cburns/local/lib/python2.5/site-packages/Jinja2-2.1.1-py2.5-macosx-10.3-i386.egg/jinja2/sandbox.py", line 238, in return
    call __context.call(__obj, _args, *_kwargs)
  File "/Users/cburns/local/lib/python2.5/site-packages/Jinja2-2.1.1-py2.5-macosx-10.3-i386.egg/jinja2/runtime.py", line 132, in call
    return __obj(_args, *_kwargs)
  File "/Users/cburns/local/lib/python2.5/site-packages/Jinja2-2.1.1-py2.5-macosx-10.3-i386.egg/jinja2/runtime.py", line 352, in __call__
    return self._func(*arguments)
  File "/Users/cburns/local/lib/python2.5/site-packages/Sphinx-0.6.1-py2.5.egg/sphinx/themes/basic/layout.html", line 68, in template
    {&#37; include customsidebar &#37;}
  File "/Users/cburns/src/nipy-repo/trunk-lp/doc/www/_templates/indexsidebar.html", line 1, in top-level template code
    {&#37; extends "../../_templates/indexsidebar.html" &#37;}
  File "/Users/cburns/local/lib/python2.5/site-packages/Jinja2-2.1.1-py2.5-macosx-10.3-i386.egg/jinja2/environment.py", line 499, in get_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/cburns/local/lib/python2.5/site-packages/Jinja2-2.1.1-py2.5-macosx-10.3-i386.egg/jinja2/loaders.py", line 95, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/cburns/local/lib/python2.5/site-packages/Sphinx-0.6.1-py2.5.egg/sphinx/jinja2glue.py", line 102, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: ../../_templates/indexsidebar.html

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/158
- Originally reported by: Christopher Burns
- Originally created at: 2009-05-08T07:17:08.848

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-06-04 16:42:36+00:00_

Thanks for reporting! This was caused by a more restrictive template name rule in Jinja 2, and has now been fixed in <<cset be49adef8c8bf52c3a2db406e6aa954063f1c877>>.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2013-03-31 13:57:07+00:00_

Removing version: 0.6 (automated comment)
