### ISSUE TITLE
module object has no attribute getlogger

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1588]
Looking at bug history this may be a circular ref problem, but I'm damned if I can spot it

```
# Sphinx version: 1.2.3
# Python version: 2.7.8
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Loaded extensions:
Traceback (most recent call last):
  File "c:\dev\python\facilitated-booking\venv\lib\site-packages\sphinx\cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "c:\dev\python\facilitated-booking\venv\lib\site-packages\sphinx\application.py", line 119, in __init__
    self.setup_extension(extension)
  File "c:\dev\python\facilitated-booking\venv\lib\site-packages\sphinx\application.py", line 333, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "c:\dev\python\facilitated-booking\venv\lib\site-packages\sphinx\ext\autodoc.py", line 26, in <module>
    from sphinx.pycode import ModuleAnalyzer, PycodeError
  File "c:\dev\python\facilitated-booking\venv\lib\site-packages\sphinx\pycode\__init__.py", line 27, in <module>
    pygrammar = driver.load_grammar(_grammarfile)
  File "c:\dev\python\facilitated-booking\venv\lib\site-packages\sphinx\pycode\pgen2\driver.py", line 119, in load_grammar
    logger = logging.getLogger()
AttributeError: 'module' object has no attribute 'getLogger'
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1588
- Originally reported by: Anonymous
- Originally created at: 2014-10-08T01:01:53.493

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-10-08 00:04:59+00:00_

Do you by chance have a `logging.py` or `logging/__init__.py` on PYTHONPATH?

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-10-08 00:05:29+00:00_

To find out, you can run Sphinx with `-P` and then do `p logging.__file__`.

**Comment by velumit** [comment]
Hi guys. I am also facing the same issue. Could some body help me how to resolve this ?

**Comment by shimizukawa** [comment]
@velumit we need more information to resolve it. 

> To find out, you can run Sphinx with `-P` and then do `p logging.__file__`.

**Comment by velumit** [comment]
```
C:\Python27\python.exe C:/Users/vesub/PycharmProjects/NetOrch/NetOrchWorkersScheduler.py
Traceback (most recent call last):
  File "C:/Users/vesub/PycharmProjects/NetOrch/NetOrchWorkersScheduler.py", line 3, in <module>
    import cmdproxy
  File "C:\Python27\lib\site-packages\cmdproxy-0.9.7-py2.7.egg\cmdproxy\__init__.py", line 14, in <module>
    import requests
  File "C:\Python27\lib\site-packages\requests\__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Python27\lib\site-packages\requests\packages\__init__.py", line 3, in <module>
    from . import urllib3
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\__init__.py", line 10, in <module>
    from .connectionpool import (
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 31, in <module>
    from .connection import (
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\connection.py", line 45, in <module>
    from .util.ssl_ import (
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\util\__init__.py", line 18, in <module>
    from .retry import Retry
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\util\retry.py", line 14, in <module>
    log = logging.getLogger(__name__)
AttributeError: 'module' object has no attribute 'getLogger'

Process finished with exit code 1
Please see the full trace of the exception. 
```

**Comment by shimizukawa** [comment]
I think it isn't a sphinx issue.

It seems that `requests/packages/urllib3/util/retry.py` expects `logging` python standard library module, but imported `logging` is not I guess. 

To find out, you can run Sphinx with `-P` and then do `p logging.__file__` like:

```
$ make html SPHINXOPTS=-P
...
(Pdb) p logging.__file__
```

**Comment by agpar** [comment]
Is it possible that there is a file in your project your are documenting named `logging.py`? Renaming my own `logging.py` solved the problem for me (pretty knuckle-headed).

**Comment by tk0miya** [comment]
It seems this is not a issue of sphinx.
I close this again.

Please reopen if you still have the same problem.

Thanks,

**Comment by saramirabi** [comment]
Hi Guys,
I suddenly encountered with below error while running Python code, anyone can help me? I searched alot but i couldnt find the solution:
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from flask import Flask, render_template, request, make_response, send_file
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\__init__.py", line 14, in <module>
    from jinja2 import escape
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jinja2\__init__.py", line 82, in <module>
    _patch_async()
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jinja2\__init__.py", line 78, in _patch_async
    from jinja2.asyncsupport import patch_all
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jinja2\asyncsupport.py", line 13, in <module>
    import asyncio
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\asyncio\__init__.py", line 8, in <module>
    from .base_events import *
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 18, in <module>
    import concurrent.futures
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\_base.py", line 7, in <module>
    import logging
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 26, in <module>
    import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\traceback.py", line 5, in <module>
    import linecache
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\linecache.py", line 11, in <module>
    import tokenize
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\tokenize.py", line 34, in <module>
    from token import *
  File "C:\administrations\Portal\token.py", line 1, in <module>
    import requests
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 29, in <module>
    from .connection import (
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 40, in <module>
    from .util.ssl_ import (
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\__init__.py", line 20, in <module>
    from .retry import Retry
  File "C:\Users\bssops\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\retry.py", line 20, in <module>
    log = logging.getLogger(__name__)
AttributeError: partially initialized module 'logging' has no attribute 'getLogger' (most likely due to a circular import)
