### ISSUE TITLE
sphinx-apidoc 1.3b1 -F option doesn't work

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1594]
Hi,

We're using:

sphinx-apidoc -F -o <path> <module>

to autogenerate apidocs. When going from 1.2.3 to 1.3b1, we get:

Traceback (most recent call last):
  File "../../../bin/sphinx-apidoc", line 11, in <module>
    sys.exit(main())
  File "/home/acorcoles/git/ntteam.automation/.tox/docs-django16/local/lib/python2.7/site-packages/sphinx/apidoc.py", line 372, in main
    qs.generate(d, silent=True, overwrite=opts.force)
  File "/home/acorcoles/git/ntteam.automation/.tox/docs-django16/local/lib/python2.7/site-packages/sphinx/quickstart.py", line 1328, in generate
    conf_text = QUICKSTART_CONF &#37; d
KeyError: u'language'

, which I believe happens because now language is a required parameter for quickstart, but apidoc doesn't supply it.

Cheers,

Álex

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1594
- Originally reported by: Anonymous
- Originally created at: 2014-10-13T11:15:59.876

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-10-14 07:59:09+00:00_

Thanks for the report, I'm on it.

**Comment by shimizukawa** [comment]
_From Alex Corcoles on 2014-10-21 08:57:05+00:00_

Hi,

This is fixed if I use hg+https://bitbucket.org/birkenfeld/sphinx/@25a9c50,
