### ISSUE TITLE
aafigure build documentation failed

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1595]
Running make html in the documentation directory :

```
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3b1
making output directory...

Exception occurred:
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinxcontrib_aafig-1.0-py2.7.egg/sphinxcontrib/aafig.py", line 58, in <module>
    class AafigDirective(directives.images.Image):
AttributeError: 'module' object has no attribute 'images'
The full traceback has been saved in /var/folders/26/4_v2k57n5bd30n4zf9tdbxmm0000gn/T/sphinx-err-OJGcXY.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1

This is the log:


# Sphinx version: 1.3b1
# Python version: 2.7.8
# Docutils version: 0.12 release
# Jinja2 version: 2.8-dev
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b1-py2.7.egg/sphinx/cmdline.py", line 245, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b1-py2.7.egg/sphinx/application.py", line 135, in __init__
    self.setup_extension(extension)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b1-py2.7.egg/sphinx/application.py", line 419, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinxcontrib_aafig-1.0-py2.7.egg/sphinxcontrib/aafig.py", line 58, in <module>
    class AafigDirective(directives.images.Image):
AttributeError: 'module' object has no attribute 'images'
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1595
- Originally reported by: Oran Pirani
- Originally created at: 2014-10-15T12:09:28.734

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-10-15 11:37:27+00:00_

This is a bug in aafig: it should not rely on `docutils.parsers.rst.directives.images` having been imported already.

Please report to the aafig author: Leandro Lucarella llucax@gmail.com

**Comment by llucax** [comment]
Fixed in https://bitbucket.org/birkenfeld/sphinx-contrib/commits/f41632b346a569e2a6bcd0194ea491c2550ecf4d (Thanks Tony Narlock!)
