### ISSUE TITLE
AttributeError: 'list' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1605]
Exception occurred:
  File /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 121, in basename
    i = p.rfind('/') + 1
AttributeError: 'list' object has no attribute 'rfind'
The full traceback has been saved in /var/folders/_s/1qy737cn7lb7kly_tvg9sbdh0000gn/T/sphinx-err-Gfobw5.log, if you want to report the issue to the developers.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1605
- Originally reported by: Anonymous
- Originally created at: 2014-10-21T15:39:57.522

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-10-21 14:43:26+00:00_

There is less information to resolve the issue. Please attach error log file.

**Comment by jputrino** [comment]
I just got the same error, which seems to be related to the absolute path. 

```
Exception occurred:
  File "/Users/putrino/velcro/f5-marathon-lb/venv/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'list' object has no attribute 'rfind'
```

Here's how I have it set up in docs/conf.py:

```
import os
import sys

sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('../'))
```

Full traceback is below

```
# Sphinx version: 1.4.8
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   /Users/putrino/velcro/f5-marathon-lb/docs/_includes/topic_csi-mesos-marathon-all.rst:5: WARNING: duplicate label overview, other instance in /Users/putrino/velcro/f5-marathon-lb/docs/README.rst
#   /Users/putrino/velcro/f5-marathon-lb/docs/_includes/topic_csi-mesos-marathon-all.rst:34: WARNING: duplicate label prerequisites, other instance in /Users/putrino/velcro/f5-marathon-lb/docs/_includes/ref_prerequisites.rst
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   /Users/putrino/velcro/f5-marathon-lb/docs/_includes/topic_csi-mesos-marathon-all.rst:: WARNING: document isn't included in any toctree
#   done
#   preparing documents...
# Loaded extensions:
#   sphinx.ext.intersphinx (1.4.8) from /Users/putrino/velcro/f5-marathon-lb/venv/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
#   sphinx.ext.autosectionlabel (unknown version) from /Users/putrino/velcro/f5-marathon-lb/venv/lib/python2.7/site-packages/sphinx/ext/autosectionlabel.pyc
#   sphinx.ext.ifconfig (1.4.8) from /Users/putrino/velcro/f5-marathon-lb/venv/lib/python2.7/site-packages/sphinx/ext/ifconfig.pyc
#   sphinx.ext.coverage (1.4.8) from /Users/putrino/velcro/f5-marathon-lb/venv/lib/python2.7/site-packages/sphinx/ext/coverage.pyc
#   sphinx.ext.todo (1.4.8) from /Users/putrino/velcro/f5-marathon-lb/venv/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   alabaster (0.7.9) from /Users/putrino/velcro/f5-marathon-lb/venv/lib/python2.7/site-packages/alabaster/__init__.pyc
Traceback (most recent call last):
  File "/Users/putrino/velcro/f5-marathon-lb/venv/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/Users/putrino/velcro/f5-marathon-lb/venv/lib/python2.7/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/Users/putrino/velcro/f5-marathon-lb/venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/Users/putrino/velcro/f5-marathon-lb/venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 322, in build
/var/folders/06/0gyp09193p5632bd177_g2pr0r1ztr/T/sphinx-err-OaJdfO.log
```

thanks!

**Comment by shimizukawa** [comment]
Please file a new issue and attach your small sphinx project files. thanks.

2016年10月13日(木) 6:41 Jodie Putrino notifications@github.com:
