### ISSUE TITLE
ImportError: No module named sphinx_rtd_theme

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1636]
I'm having troubles compiling my docs. A few minutes ago I tried a `make html` and everything worked fine. Then I fiddled with `pyenv` in a _different_ folder and now I can't build my docs anymore.

As far as I can tell everything is in place, `pyenv versions` shows:

```
* system (set by /media/rest/github/.python-version)
  2.7.7
  2.7.8
  3.4.1
```

 but when I try `make html` I get:

```
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.2.2

Exception occurred:
  File "conf.py", line 24, in <module>
    import sphinx_rtd_theme
ImportError: No module named sphinx_rtd_theme
The full traceback has been saved in /tmp/sphinx-err-gdoqyz.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1
```

This is a strange error since `sphinx_rtd_theme` _is_ installed as shown by `pip freeze`:

```
sphinx-rtd-theme==0.1.6
```

My `config.py` file has the following block added:

```
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

if not on_rtd:  # only import and set the theme if we're building docs locally
    import sphinx_rtd_theme
    html_theme = 'sphinx_rtd_theme'
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
else:
    html_theme = 'default'
```

This is the log:

```
# Sphinx version: 1.2.2
# Python version: 3.2.3
# Docutils version: 0.11 release
# Jinja2 version: 2.6
# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/Sphinx-1.2.2-py3.2.egg/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/local/lib/python3.2/dist-packages/Sphinx-1.2.2-py3.2.egg/sphinx/application.py", line 107, in __init__
    confoverrides or {}, self.tags)
  File "/usr/local/lib/python3.2/dist-packages/Sphinx-1.2.2-py3.2.egg/sphinx/config.py", line 229, in __init__
    execfile_(filename, config)
  File "/usr/local/lib/python3.2/dist-packages/Sphinx-1.2.2-py3.2.egg/sphinx/util/pycompat.py", line 105, in execfile_
    exec(code, _globals)
  File "conf.py", line 24, in <module>
    import sphinx_rtd_theme
ImportError: No module named sphinx_rtd_theme
```

I have no idea why the python version shown is `3.2.3`. Could this be the issue here?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1636
- Originally reported by: Gabriel Perren
- Originally created at: 2014-12-01T16:30:52.479

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-12-01 15:49:18+00:00_

Sphinx doesn't do anything special when executing `conf.py` - except changing the working directory to the directory of conf.py. 

So to try to debug this, you should change to that directory and then try importing the sphinx_rtd_theme module with a normal Python interpreter.
Or you could use the `-P` Sphinx option, to get a pdb prompt from which you can inspect sys.path etc.

**Comment by shimizukawa** [comment]
_From Gabriel Perren on 2014-12-01 16:39:07+00:00_

From the `conf.py` dir I can do in the terminal:

```
$ python
import sphinx_rtd_theme
```

with no issues.

In any case, after upgrading to v1.3b1 the issue seems to have gone away.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-12-01 16:54:41+00:00_

Thanks for letting us know!
