### ISSUE TITLE
'Sphinx' object has no attribute 'get'

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1639]
Hello,
When running "make html" in a standard doc/ directory I get the following error and traceback:

```
# Sphinx version: 1.3b1
# Python version: 2.7.8
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b1-py2.7.egg/sphinx/cmdline.py", line 245, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b1-py2.7.egg/sphinx/application.py", line 135, in __init__
    self.setup_extension(extension)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b1-py2.7.egg/sphinx/application.py", line 439, in setup_extension
    if not ext_meta.get('version'):
AttributeError: 'Sphinx' object has no attribute 'get'
```

At the very least this log is not informative enough for me to know what I should correct.
Best,
J.D.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1639
- Originally reported by: Anonymous
- Originally created at: 2014-12-03T02:34:24.269

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-12-03 08:12:43+00:00_

One of he extensions used by your doc apparently does "return app" in its setup() function.  This is not supported, as since 1.3 the return value of setup() has a meaning.

**Comment by shimizukawa** [comment]
_From Matthias BUSSONNIER on 2014-12-18 10:33:37+00:00_

here is s link to what setup function should return :  http://sphinx-doc.org/latest/extdev/tutorial.html?highlight=setup#the-setup-function
