### ISSUE TITLE
Python3 incompatibility: sphinx/environment.py", line 1277, in _toctree_prune?

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1660]
Ok I can not seem to build my docs using:

``` bash
gus at jupiter in ~/Dropbox/repos/git/pandoc_circles/docs (f/test_docs) (markdown-docs) 
$ sphinx-build -b html . _build 
```

The last error is:

```
File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/environment.py", line 1277, in _toctree_prune
    if maxdepth > 0 and depth > maxdepth:
TypeError: unorderable types: str() > int()
```

I get this full traceback:

``` bash
$ cat /tmp/sphinx-err-86qoan45.log
# Sphinx version: 1.3b2
# Python version: 3.4.2
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:
#   /home/gus/Dropbox/repos/git/pandoc_circles/docs/reference/pcircles.rst:4: WARNING: autodoc: failed to import module 'pcircles'; the following exception was raised:
Traceback (most recent call last):
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 378, in import_object
    __import__(self.modname)
ImportError: No module named 'pcircles'
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [ 11&#37;] authors
# Loaded extensions:
#   sphinx.ext.viewcode (1.3b2) from /home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.todo (1.3b2) from /home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (1.3b2) from /home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.ifconfig (1.3b2) from /home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.autosummary (1.3b2) from /home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinxcontrib.napoleon (unknown version) from /home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinxcontrib/napoleon/__init__.py
#   sphinx.ext.autodoc (1.3b2) from /home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/ext/autodoc.py
Traceback (most recent call last):
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/cmdline.py", line 246, in main
    app.build(opts.force_all, filenames)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/application.py", line 257, in build
    self.builder.build_update()
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 237, in build_update
    'out of date' &#37; len(to_build))
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 308, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 346, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 354, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/builders/html.py", line 439, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/builders/html.py", line 776, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/jinja2glue.py", line 133, in render
    return self.environment.get_template(template).render(context)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/themes/basic/page.html", line 10, in <module>
    {&#37;- extends "layout.html" &#37;}
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx_py3doc_enhanced_theme/layout.html", line 2, in <module>
    {&#37; extends "!basic/layout.html" &#37;}
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/themes/basic/layout.html", line 160, in <module>
    {&#37;- block content &#37;}
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/themes/basic/layout.html", line 178, in <module>
    {&#37;- block sidebar2 &#37;}{{ sidebar() }}{&#37; endblock &#37;}
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/themes/basic/layout.html", line 178, in <module>
    {&#37;- block sidebar2 &#37;}{{ sidebar() }}{&#37; endblock &#37;}
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/jinja2/sandbox.py", line 356, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/themes/basic/layout.html", line 62, in <module>
    {&#37;- include sidebartemplate &#37;}
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx_py3doc_enhanced_theme/globaltoc.html", line 2, in <module>
    {{ toctree(maxdepth=theme_sidebardepth, collapse=theme_sidebarcollapse, includehidden=True) }}
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/jinja2/sandbox.py", line 356, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/builders/html.py", line 766, in <lambda>
    ctx['toctree'] = lambda **kw: self._get_local_toctree(pagename, **kw)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/builders/html.py", line 702, in _get_local_toctree
    docname, self, collapse, **kwds))['fragment']
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/environment.py", line 1209, in get_toctree_for
    prune=True, **kwds)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/environment.py", line 1461, in resolve_toctree
    self._toctree_prune(newnode, 1, prune and maxdepth or 0, collapse)
  File "/home/gus/.virtualenvs/markdown-docs/lib/python3.4/site-packages/sphinx/environment.py", line 1277, in _toctree_prune
    if maxdepth > 0 and depth > maxdepth:
TypeError: unorderable types: str() > int()

```
## My system info:

virtualenv:

``` bash
$ pip freeze                      
Babel==1.3
Jinja2==2.7.3
MarkupSafe==0.23
PyYAML==3.11
Pygments==2.0.1
Sphinx==1.3b2
argh==0.26.1
binaryornot==0.3.0
certifi==14.05.14
cookiecutter==0.8.0
docutils==0.12
ipython==3.0.0-dev
jsonschema==2.4.0
livereload==2.3.2
mistune==0.5
nose==1.3.4
numpydoc==0.5
pandocfilters==1.2.3
pathtools==0.1.2
py==1.4.26
pydot==1.0.15
pyparsing==2.0.3
pytz==2014.10
pyzmq==14.4.1
requests==2.5.1
six==1.8.0
snowballstemmer==1.2.0
sphinx-autobuild==0.4.0
sphinx-py3doc-enhanced-theme==0.1.1
sphinxcontrib-napoleon==0.2.8
tornado==4.0.2
tox==1.8.1
virtualenv==12.0.4
watchdog==0.8.2
```

Sphinx:

``` bash
$ sphinx-build --version
Sphinx (sphinx-build) 1.3b2
```

Python:

``` bash
$ python --version
Python 3.4.2
```

conf.py:

``` python
# -*- coding: utf-8 -*-
import re
import os
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinxcontrib.napoleon'
]
if os.getenv('SPELLCHECK'):
    extensions += 'sphinxcontrib.spelling',
    spelling_show_suggestions = True
    spelling_lang = 'en_US'

source_suffix = '.rst'
master_doc = 'index'
project = u'Pandoc Circles'
copyright = u'2014, Gus Dunn'
version = release = re.findall(
    'version="(.*)"',
    open(os.path.join(os.path.dirname(__file__), '../setup.py')).read()
)[0]

import sphinx_py3doc_enhanced_theme
html_theme = "sphinx_py3doc_enhanced_theme"
html_theme_path = [sphinx_py3doc_enhanced_theme.get_html_theme_path()]

pygments_style = 'trac'
templates_path = ['.']
html_use_smartypants = True
html_last_updated_fmt = '&#37;b &#37;d, &#37;Y'
html_split_index = True
html_sidebars = {
   '**': ['searchbox.html', 'globaltoc.html', 'sourcelink.html'],
}
html_short_title = '&#37;s-&#37;s' &#37; (project, version)
html_theme_options = {
    'githuburl': 'https://github.com/xguse/pandoc_circles/'
}
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1660
- Originally reported by: Gus Dunn
- Originally created at: 2014-12-30T18:24:20.721

**Comment by birkenfeld** [comment]
@xguse I tried to reproduce this with your pandoc_circles repo, but failed. Can you check?

**Comment by birkenfeld** [comment]
Never mind, I got it. The problem is in the theme's `globaltoc.html`, where the depth argument is not converted to an integer.

**Comment by birkenfeld** [comment]
Reported to and fixed by Ionel.
