### ISSUE TITLE
Cant genrate Slides and HTML

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1662]
```
# Sphinx version: 1.3b2
# Python version: 2.7.3
# Docutils version: 0.12 release
# Jinja2 version: 2.6
# Last messages:
#   
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [100&#37;] index
# Loaded extensions:
#   hieroglyph (unknown version) from /usr/local/lib/python2.7/dist-packages/hieroglyph/__init__.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 246, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 257, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 237, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 308, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 346, in write
    self._write_serial(sorted(docnames), warnings)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 354, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/local/lib/python2.7/dist-packages/hieroglyph/builder.py", line 101, in write_doc
    result = super(AbstractSlideBuilder, self).write_doc(docname, doctree)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/html.py", line 439, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/html.py", line 776, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/jinja2glue.py", line 133, in render
    return self.environment.get_template(template).render(context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 719, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 689, in _load_template
    template = self.cache.get(name)
  File "/usr/lib/python2.7/dist-packages/jinja2/utils.py", line 405, in get
    return self[key]
  File "/usr/lib/python2.7/dist-packages/jinja2/utils.py", line 448, in __getitem__
    rv = self._mapping[key]
TypeError: unhashable type: 'dict'
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1662
- Originally reported by: Ila rana
- Originally created at: 2014-12-31T11:54:05.006

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2015-01-01 04:35:18+00:00_

I think this issue relates to `hieroglyph` slide extension. Could you attache a small sample project to reproduce the issue?

**Comment by eliza411** [comment]
I experienced this problem after using easy_install to install hieroglyph which installed Sphinx 1.3b2

Reinstalling using `pip install sphinx hieroglyph`, Sphinx 1.2.3 was installed, and build slides and build_html worked as expected.

**Comment by birkenfeld** [comment]
This is a bug in hieroglyph: it returns a dictionary from the `html-page-context` event.

In Sphinx 1.2, this event had no return value, so the return value was ignored.
In Sphinx 1.3, the return value has a meaning: it overrides the template name. But for that it must be a string, not a dictionary.

**Comment by birkenfeld** [comment]
https://github.com/nyergler/hieroglyph/issues/84
