### ISSUE TITLE
error during moving rst file to subfolder

### ISSUE THREAD

**Issue by nazarlviv07** [sphinx-doc/sphinx#1678]
Hi,

Now all my .rst files are in the folder ( docs).

```
docs/
    file1.rst
  file2.rst
  file3.rst
```

When I create subfolder ( folder3) and move there file3.rst file.

```
docs/
   file1.rst
   file2.rst
   folder3/
       file3.rst
```

After that error occured
Do you know about that problem?

Logs is below.

```
Sphinx version: 1.2.2
Python version: 2.7.0
Docutils version: 0.11 release
Jinja2 version: unknown
Loaded extensions:
sphinx.ext.autodoc from \deploy\1.9.79-20150004101200\lib\Lib\sphinx\ext\autodoc.py
sphinx.ext.oldcmarkup from \deploy\1.9.79-20150004101200\lib\Lib\sphinx\ext\oldcmarkup.py

Traceback (most recent call last):

File "\deploy\1.9.79-20150004101200\lib\Lib\sphinx\cmdline.py", line 254, in main app.build(force_all, filenames)

File "\deploy\1.9.79-20150004101200\lib\Lib\sphinx\application.py", line 212, in build self.builder.build_update()

File "\deploy\1.9.79-20150004101200\lib\Lib\sphinx\builders__init__.py", line 212, in build_update self.build(to_build,

File "\deploy\1.9.79-20150004101200\lib\Lib\sphinx\builders__init__.py", line 233, in build for docname in self.status_iterator(iterator, 'reading sources... ',

File "\deploy\1.9.79-20150004101200\lib\Lib\sphinx\builders__init__.py", line 134, in status_iterator for item in iterable:

File "\deploy\1.9.79-20150004101200\lib\Lib\sphinx\environment.py", line 477, in update_generator self.read_doc(docname, app=app)

File "\deploy\1.9.79-20150004101200\lib\Lib\sphinx\environment.py", line 690, in read_doc os.makedirs(dirname)

File "\deploy\1.9.79-20150004101200\lib\jython-standalone-2.7-b1.jar\Lib\os.py", line 172, in makedirs mkdir(name, mode) OSError: [Errno 3] No such process: '\\deploy\1.9.79-20150004101200\docs\doctrees\folder3'
```

**Comment by birkenfeld** [comment]
This is actually a Jython issue, please see http://bugs.jython.org/issue2014
