### ISSUE TITLE
'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by ijmorlan** [sphinx-doc/sphinx#1725]
I am trying to apply Sphinx to a substantial existing codebase using sphinx-apidoc. I have been getting the following error, which is similar to what people reported in some other items:

```
Encoding error:
'ascii' codec can't decode byte 0xef in position 399: ordinal not in range(128)
The full traceback has been saved in /var/folders/lD/lDSKCphZE+OJPL1sc+j8UE+++TM/-Tmp-/sphinx-err-kMvlud.log, if you want to report the issue to the developers.
make: *** [html] Error 1
```

Some necessary background: my files are UTF-8, marked as such by the inclusion of a Byte Order Mark (U+FEFF, UTF-8 bytes EF, BB, BF). Most of them start with a docstring comment, so the first six bytes are the three bytes making up the Byte Order Mark followed by three ASCII double quote marks.

By removing most of the apidoc-created files, I was able to generate documentation successfully, then added things back in until the error recurred. I was able to create a short file which causes the problem, and a very similar one that does not.

The problem file I found starts with a "from ... import" statement, and has no module docstring. So the fourth byte of the file, immediately after the BOM, is the "f" in "from". The problem goes away if I either insert a newline or a docstring before the "from".

I found the same results by reducing the file down to just a few letters "impor". With a newline before it, documentation is generated (although naturally a warning is raised concerning the invalid Python syntax); with no newline, I get the same error (trace attached). Note that "import" is fine with or without the newline or docstring.

I can't figure out what the "position 399" is.

Is there any way the error can at least be improved to indicate what source file is causing the problem? Since I want all my files to have docstrings, I'm not expecting this to be a problem, but I'm going to need to do some careful grepping to find all the files which are missing docstrings and put in a placeholder just to get the initial build of the documentation working.

**Comment by ijmorlan** [comment]
Sorry, I don't see how to attach a trace after all. I'll try including it in this comment:

```
# Sphinx version: 1.3b2
# Python version: 2.7.0
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:
#   Running Sphinx v1.3b2
#   loading pickled environment...
#   done
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 0 source files that are out of date
#   updating environment:
#   0 added, 2 changed, 0 removed
#   reading sources... [ 50%] uw
#   reading sources... [100%] uw.sql
# Loaded extensions:
#   sphinx.ext.coverage (1.3b2) from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/ext/coverage.pyc
#   sphinx.ext.autodoc (1.3b2) from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/ext/autodoc.pyc
#   sphinx.ext.viewcode (1.3b2) from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/ext/viewcode.pyc
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/cmdline.py", line 246, in main
    app.build(opts.force_all, filenames)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/application.py", line 257, in build
    self.builder.build_update()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/builders/__init__.py", line 237, in build_update
    'out of date' % len(to_build))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/builders/__init__.py", line 251, in build
    self.doctreedir, self.app))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/environment.py", line 585, in update
    self._read_serial(docnames, app)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/environment.py", line 601, in _read_serial
    self.read_doc(docname, app)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/environment.py", line 753, in read_doc
    pub.publish()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/core.py", line 217, in publish
    self.settings)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/ext/autodoc.py", line 1441, in run
    documenter.generate(more_content=self.content)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/ext/autodoc.py", line 766, in generate
    if not self.import_object():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/ext/autodoc.py", line 407, in import_object
    self.directive.warn(errmsg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Sphinx-1.3b2-py2.7.egg/sphinx/ext/autodoc.py", line 1402, in warn
    self.warnings.append(self.reporter.warning(msg, line=self.lineno))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/utils/__init__.py", line 220, in warning
    return self.system_message(self.WARNING_LEVEL, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/utils/__init__.py", line 187, in system_message
    *children, **attributes)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/nodes.py", line 1672, in __init__
    p = paragraph('', message)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/nodes.py", line 1073, in __init__
    textnode = Text(text)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils-0.12-py2.7.egg/docutils/nodes.py", line 344, in __new__
    return reprunicode.__new__(cls, data)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 399: ordinal not in range(128)
```

**Comment by ijmorlan** [comment]
Sorry again, it's probably my old FireFox. Let me know if the crucial information cannot be extracted from the above.

**Comment by shimizukawa** [comment]
I can't reproduce the error. Could you provide a small sample to reproduce it?

**Comment by ronanpaixao** [comment]
I have a test code for this problem:

`testutf.py`

``` python
# -*- coding: utf-8 -*-
'''
.. testsetup:: *

   from testutf import *
'''
def testutf(utf=False):
    '''
    >>> testutf()
    Traceback (most recent call last):
        ...
    ValueError: Fuuuu
    >>> testutf(True)
    Traceback (most recent call last):
        ...
    ValueError: Fúúúú
    '''
    if not utf:
        raise ValueError, 'Fuuuu'
    else:
        raise ValueError, 'Fúúúú'


# Stub to test from outside Sphinx (with UTF-8 encoding), this works
if __name__ == "__main__":
    import doctest
    doctest.testmod(verbose=True) 
```

`testuft.rst` generated by `sphinx-apidoc`:

``` rst
testutf module
==============

.. automodule:: testutf
    :members:
    :undoc-members:
    :show-inheritance:
```

`make doctest` output:

```
Running Sphinx v1.2.3
loading translations [pt_BR]... done
loading pickled environment... not yet created
building [doctest]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
reading sources... [ 33%] index
reading sources... [ 66%] modules
reading sources... [100%] testutf

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
running tests...

Document: testutf
-----------------

Encoding error:
'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)
The full traceback has been saved in c:\users\u5fs\appdata\local\temp\sphinx-err-yglwg8.log, if you want to report the issue to the
developers.
```

**Note 1:** I have also tried to use the `source_encoding = 'utf-8'` option in `conf.py`, with no success.

**Note 2:** I put a test stub in the source file, so as to doctest it from outside Sphinx, with success:

```
>python ..\testutf.py
Trying:
    testutf()
Expecting:
    Traceback (most recent call last):
        ...
    ValueError: Fuuuu
ok
Trying:
    testutf(True)
Expecting:
    Traceback (most recent call last):
        ...
    ValueError: F├║├║├║├║
ok
1 items had no tests:
    __main__
1 items passed all tests:
   2 tests in __main__.testutf
2 tests in 2 items.
2 passed and 0 failed.
Test passed.
```

This suggests that the problem is with Sphinx passing text to doctest as ASCII. From the terrible error messages (no file names and correct line numbers) I'd think that Sphinx is redoing doctest's job and passing tests by line or by docstring, instead of passing the whole file.

As possible fixes, I'd think about passing the whole file to doctest (this will make sure doctest finds the encoding shebang) or at least copying the shebang for every call to doctest.

**Note 3:** Running on Windows 7, Sphinx 1.2.3, Python 2.7.6 | Anaconda 2.1.0 (32-bit). Hence the strange chars when doctesting in the terminal.

**Comment by shimizukawa** [comment]
I got the issue of @ronanpaixao case. However, I guess the case is different with the @ijmorlan case.

@ijmorlan if you have detail information as @ronanpaixao filed, please let me know.
For now, I'll fix the @ronanpaixao case.

**Comment by shimizukawa** [comment]
The case of @ronanpaixao is fixed.

**Comment by asr** [comment]
I could fix the same reported issue with `make latexpdf` by adding a 'u' in front of the title and the author in `latex_documents` (see https://github.com/agda/agda/commit/dfe479e370ae33e37fb1021a374bedbb8912089d).

**Comment by hqmonaro** [comment]
Are you seeing locale errors like the one below along with the 'ascii' codec error?

```
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

I had to enable the en_US.UTF-8 locale to solve this. On Arch Linux I uncommented the above entry from `/etc/locale.gen` and executed `sudo locale-gen`. After doing this I had no issue.
