### ISSUE TITLE
Localized table caption raises exception

### ISSUE THREAD

**Issue by epenttila** [sphinx-doc/sphinx#1732]
Generating a document with 1.3b2 that uses localized .po files for table captions gives the following output:

```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\sphinx\cmdline.py", line 246, in main
    app.build(opts.force_all, filenames)
  File "C:\Python34\lib\site-packages\sphinx\application.py", line 257, in build
    self.builder.build_update()
  File "C:\Python34\lib\site-packages\sphinx\builders\__init__.py", line 232, in build_update
    self.build(['__all__'], to_build)
  File "C:\Python34\lib\site-packages\sphinx\builders\__init__.py", line 251, in build
    self.doctreedir, self.app))
  File "C:\Python34\lib\site-packages\sphinx\environment.py", line 585, in update
    self._read_serial(docnames, app)
  File "C:\Python34\lib\site-packages\sphinx\environment.py", line 601, in _read_serial
    self.read_doc(docname, app)
  File "C:\Python34\lib\site-packages\sphinx\environment.py", line 753, in read_doc
    pub.publish()
  File "C:\Python34\lib\site-packages\docutils\core.py", line 218, in publish
    self.apply_transforms()
  File "C:\Python34\lib\site-packages\docutils\core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "C:\Python34\lib\site-packages\docutils\transforms\__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "C:\Python34\lib\site-packages\sphinx\transforms.py", line 123, in apply
    self.document.note_implicit_target(node)
  File "C:\Python34\lib\site-packages\docutils\nodes.py", line 1383, in note_implicit_target
    self.set_name_id_map(target, id, msgnode, explicit=None)
  File "C:\Python34\lib\site-packages\docutils\nodes.py", line 1330, in set_name_id_map
    self.set_duplicate_name_id(node, id, name, msgnode, explicit)
  File "C:\Python34\lib\site-packages\docutils\nodes.py", line 1369, in set_duplicate_name_id
    dupname(node, name)
  File "C:\Python34\lib\site-packages\docutils\nodes.py", line 2177, in dupname
    node['names'].remove(name)
ValueError: list.remove(x): x not in list
```

It seems dupname is called twice with the same node from both the Locale transform and AutoNumbering transform (the self.document.note_implicit_target(node) calls).

Sphinx 1.2 works fine as it doesn't have the AutoNumbering transform.

**Comment by shimizukawa** [comment]
Confirmed. Thanks for your reporting. I'll fix it.

**Comment by shimizukawa** [comment]
@epenttila I fixed the bug. Please try 'make html' with git latest version if you have a chance. Thanks.
