### ISSUE TITLE
Encoding error when `make linkcheck`

### ISSUE THREAD

**Issue by uralbash** [sphinx-doc/sphinx#1739]
I'm using the links in the project, such as those https://ru.wikipedia.org/wiki/Система_управления_базами_данных. Sphinx-build to html make all fine, but `-b linkcheck` writes the following error:

``` bash
$ locale
LANG=ru_RU.UTF-8
LANGUAGE=ru_RU
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=

$ make linkcheck 
sphinx-build -b linkcheck -d build/doctrees   docs build/linkcheck
Running Sphinx v1.3b3
loading translations [ru]... done
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [linkcheck]: targets for 37 source files that are out of date
updating environment: 37 added, 0 changed, 0 removed
reading sources... [100%] www.sync/4.framework/pyramid                                                                                           
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  2%] databases/dbms                                                                                                          
(line    4) broken    https://ru.wikipedia.org/wiki/Система_управления_базами_данных - 'ascii' codec can't encode characters in position 11-17: ordinal not in range(128)

Encoding error:
'ascii' codec can't encode characters in position 61-67: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-ytlZ3n.log, if you want to report the issue to the developers.
Makefile:159: ошибка выполнения рецепта для цели «linkcheck»
make: *** [linkcheck] Ошибка 1
```

And with default locale

``` bash
LC_ALL=C make linkcheck 
sphinx-build -b linkcheck -d build/doctrees   docs build/linkcheck
Running Sphinx v1.3b3
loading translations [ru]... done
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [linkcheck]: targets for 37 source files that are out of date
updating environment: 37 added, 0 changed, 0 removed
reading sources... [100%] www.sync/4.framework/pyramid                                                                                           
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  2%] databases/dbms                                                                                                          
(line    4) broken    https://ru.wikipedia.org/wiki/???????_??????????_??????_?????? - 'ascii' codec can't encode characters in position 11-17: ordinal not in range(128)

Encoding error:
'ascii' codec can't encode characters in position 61-67: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-zs43nr.log, if you want to report the issue to the developers.
Makefile:159: recipe for target 'linkcheck' failed
make: *** [linkcheck] Error 1
```

**Comment by birkenfeld** [comment]
Please attach the traceback log referrred to in the error message.

**Comment by uralbash** [comment]
/tmp/sphinx-err-zs43nr.log

``` python
# Sphinx version: 1.3b3
# Python version: 2.7.8
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  2%] databases/dbms
#   
#   (line    4)
#   broken    https://ru.wikipedia.org/wiki/Система_управления_базами_данных - 'ascii' codec can't encode characters in position 11-17: ordinal not in range(128)
# Loaded extensions:
#   alabaster (unknown version) from /home/uralbash/.virtualenvs/sacrud/local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.autodoc (1.3b3) from /home/uralbash/.virtualenvs/sacrud/local/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx (1.3b3) from /home/uralbash/.virtualenvs/sacrud/local/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
#   sphinx.ext.viewcode (1.3b3) from /home/uralbash/.virtualenvs/sacrud/local/lib/python2.7/site-packages/sphinx/ext/viewcode.pyc
#   sphinx.ext.doctest (1.3b3) from /home/uralbash/.virtualenvs/sacrud/local/lib/python2.7/site-packages/sphinx/ext/doctest.pyc
Traceback (most recent call last):
  File "/home/uralbash/.virtualenvs/sacrud/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 246, in main
    app.build(opts.force_all, filenames)
  File "/home/uralbash/.virtualenvs/sacrud/local/lib/python2.7/site-packages/sphinx/application.py", line 263, in build
    self.builder.build_update()
  File "/home/uralbash/.virtualenvs/sacrud/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 237, in build_update
    'out of date' % len(to_build))
  File "/home/uralbash/.virtualenvs/sacrud/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 308, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/uralbash/.virtualenvs/sacrud/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 346, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/uralbash/.virtualenvs/sacrud/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 354, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/uralbash/.virtualenvs/sacrud/local/lib/python2.7/site-packages/sphinx/builders/linkcheck.py", line 257, in write_doc
    self.process_result(self.rqueue.get())
  File "/home/uralbash/.virtualenvs/sacrud/local/lib/python2.7/site-packages/sphinx/builders/linkcheck.py", line 215, in process_result
    self.write_entry('broken', docname, lineno, uri + ': ' + info)
  File "/home/uralbash/.virtualenvs/sacrud/local/lib/python2.7/site-packages/sphinx/builders/linkcheck.py", line 266, in write_entry
    line, what, uri))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 61-67: ordinal not in range(128)
```

**Comment by birkenfeld** [comment]
Thanks! Taking a look...

**Comment by birkenfeld** [comment]
Thanks for the report!
