### ISSUE TITLE
Import error in sphinx - jinja2glue

### ISSUE THREAD

**Issue by ilewismsl** [sphinx-doc/sphinx#1799]
Sphinx reports and error importing SandboxedEnvironment from jinja2.

Believe this failure may be related to trying to use rst2pdf to generate PDF files. However, error occurs no matter what builder I use. Problems started after placing rst2pdf builder and configuration into conf.py. Got better when I removed the rst2pdf configuration. But, also was better when I put that configuration back. 

See various other random import failures during the build, including a failure from sphinxcontrib.nwdiag, and this failure from Sphinx. The actual error in any given build is somewhat random, but if I rebuild without changing anything I get the same error over and over. Deleting the build tree and starting over sometimes makes things work, but often just changes what error I see.

Only reporting this because Sphinx said to do so in its error message. Do not have enough information to help isolate the problem yet.
# Platform

Win7 x64
# Console report
```
Exception occurred:
  File "j:\Apps\Misc\Python\v2.7.6\x64\lib\site-packages\sphinx\builders__init__.py", line 102, in create_template_bridge
    from sphinx.jinja2glue import BuiltinTemplateLoader
ImportError: No module named jinja2glue
The full traceback has been saved in c:\users\ian~1.ntd\appdata\local\temp\sphinx-err-lzkowy.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!
# Traceback

  # Sphinx version: 1.3
  # Python version: 2.7.6 (CPython)
  # Docutils version: 0.12 release
  # Jinja2 version: 2.7.3
  # Last messages:

  # Loaded extensions:
  Traceback (most recent call last):
    File "j:\Apps\Misc\Python\v2.7.6\x64\lib\site-packages\sphinx\cmdline.py", line 244, in main
      opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
    File "j:\Apps\Misc\Python\v2.7.6\x64\lib\site-packages\sphinx\application.py", line 188, in **init**
      self._init_builder(buildername)
    File "j:\Apps\Misc\Python\v2.7.6\x64\lib\site-packages\sphinx\application.py", line 249, in _init_builder
      self.builder = builderclass(self)
    File "j:\Apps\Misc\Python\v2.7.6\x64\lib\site-packages\sphinx\builders__init__.py", line 87, in **init**
      self.init()
    File "j:\Apps\Misc\Python\v2.7.6\x64\lib\site-packages\sphinx\builders\html.py", line 106, in init
      self.init_templates()
    File "j:\Apps\Misc\Python\v2.7.6\x64\lib\site-packages\sphinx\builders\html.py", line 143, in init_templates
      self.create_template_bridge()
    File "j:\Apps\Misc\Python\v2.7.6\x64\lib\site-packages\sphinx\builders__init__.py", line 102, in create_template_bridge
      from sphinx.jinja2glue import BuiltinTemplateLoader
    File "j:\Apps\Misc\Python\v2.7.6\x64\lib\site-packages\sphinx\jinja2glue.py", line 19, in <module>
      from jinja2.sandbox import SandboxedEnvironment
  ImportError: No module named sandbox
```

**Comment by ilewismsl** [comment]
Meant to say it is fine with me if you just close this report as a configuration problem. Really only reported because of recommendation to do so from Sphinx.

**Comment by ilewismsl** [comment]
Definitely somehow related to rst2pdf configuration. If I remove the rst2pdf configuration, the html build always works. If I then put the rst2pdf configuration back, the html build still works (at least most of the time). If I then build the pdf using rst2pdf, the rst2pdf build may work or it may fail. 

After that, all builds fail with various import errors from different pieces of code. 

Do not understand at all how anything can persist across builds in my environment. Running in a Windows command shell and loading Python for each build run. May be that the failure mode related to doing the pdf build is a red herring. Not quite confident of what I see because I cannot easily reproduce the same failure twice. 

Issue does not look to be related to loading the rst2pdf.pdfbuilder. The problem only occurs with the following rst2pdf configuration setup (most of it comments, but including anyhow).

---
```
  # -- Options for rst2pdf PDF output --------------------------------------------------
  # Grouping the document tree into PDF files. List of tuples
  # (source start file, target name, title, author, options).
  #
  # If there is more than one author, separate them with \.
  # For example: r'Guido van Rossum\Fred L. Drake, Jr., editor'
  #
  # The options element is a dictionary that lets you override
  # this config per-document.
  # For example,
  # ('index', u'MyProject', u'My Project', u'Author Name',
  # dict(pdf_compressed = True))
  # would mean that specific document would be compressed
  # regardless of the global pdf_compressed setting.
  pdf_documents = [
  ('index', u's1', u's1 manual', u'Microstar Laboratories, Inc.'),
  ]
  # A comma-separated list of custom stylesheets. Example:
  pdf_stylesheets = ['sphinx','kerning','letter']
  # A list of folders to search for stylesheets. Example:
  pdf_style_path = ['.', '_styles']
  # Create a compressed PDF
  # Use True/False or 1/0
  # Example: compressed=True
  #pdf_compressed = False
  # A colon-separated list of folders to search for fonts. Example:
  # pdf_font_path = ['/usr/share/fonts', '/usr/share/texmf-dist/fonts/']
  # Language to be used for hyphenation support
  #pdf_language = "en_US"
  # Mode for literal blocks wider than the frame. Can be Section 18 Sphinx Page 43
  # overflow, shrink or truncate
  #pdf_fit_mode = "shrink"
  # Section level that forces a break page.
  # For example: 1 means top-level sections start in a new page
  # 0 means disabled
  #pdf_break_level = 0
  # When a section starts in a new page, force it to be 'even', 'odd',
  # or just use 'any'
  #pdf_breakside = 'any'
  # Insert footnotes where they are defined instead of
  # at the end.
  #pdf_inline_footnotes = True
  # verbosity level. 0 1 or 2
  #pdf_verbosity = 0
  # If false, no index is generated.
  #pdf_use_index = True
  # If false, no modindex is generated.
  #pdf_use_modindex = True
  # If false, no coverpage is generated.
  #pdf_use_coverpage = True
  # Name of the cover page template to use
  #pdf_cover_template = 'sphinxcover.tmpl'
  # Documents to append as an appendix to all manuals.
  #pdf_appendices = []
  # Enable experimental feature to split table cells. Use it
  # if you get "DelayedTable too big" errors
  #pdf_splittables = False
  # Set the default DPI for images
  #pdf_default_dpi = 72
  # Enable rst2pdf extension modules (default is only vectorpdf)
  # you need vectorpdf if you want to use sphinx's graphviz support
  #pdf_extensions = ['vectorpdf']
  # Page template name for "regular" pages
  #pdf_page_template = 'cutePage'
  # Show Table Of Contents at the beginning?
  #pdf_use_toc = True
  # How many levels deep should the table of contents be? Page 44 Section 18 Sphinx
  pdf_toc_depth = 9999
  # Add section number to section references
  pdf_use_numbered_links = False
  # Background images fitting mode
  pdf_fit_background_mode = 'scale'
```

**Comment by tk0miya** [comment]
It seems this is an installation problem of jinja2 library.
Please let me know if you still have this problem.

Thanks, and sorry for very very late response.
