### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '../examples/specific/class/xml/index.xml'

### ISSUE THREAD

**Issue by MalloZup** [sphinx-doc/sphinx#1814]
Hi All,

Ubuntu 14:04

```
Exception occurred:
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
 Sphinx version: 1.3.1
 Python version: 2.7.6 (CPython)
 Docutils version: 0.12 release
 Jinja2 version: 2.7.3
 Last messages:
   reading sources... [ 61%] external/breathe/README
   reading sources... [ 62%] external/breathe/testsuite/source/autoindex
   reading sources... [ 63%] external/breathe/testsuite/source/class
   reading sources... [ 64%] external/breathe/testsuite/source/codeguide
   reading sources... [ 65%] external/breathe/testsuite/source/contributing
   reading sources... [ 65%] external/breathe/testsuite/source/credits
   reading sources... [ 66%] external/breathe/testsuite/source/customcss
   reading sources... [ 67%] external/breathe/testsuite/source/define
   reading sources... [ 68%] external/breathe/testsuite/source/directives
   reading sources... [ 69%] external/breathe/testsuite/source/domains
 Loaded extensions:
   breathe (unknown version) from /home/dario/Schreibtisch/haka/external/breathe/breathe__init__.pyc
  alabaster (0.7.3) from /usr/local/lib/python2.7/dist-packages/alabaster/__init__.pyc
   sphinx.ext.coverage (1.3.1) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/coverage.pyc
   sphinx.ext.pngmath (1.3.1) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/pngmath.pyc
   domain.haka (unknown version) from /home/dario/Schreibtisch/haka/doc/domain/haka.pyc
   sphinx.ext.todo (1.3.1) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/todo.pyc
   sphinx.ext.ifconfig (1.3.1) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/ifconfig.pyc 
  sphinx-contrib.ansi (unknown version) from /home/dario/Schreibtisch/haka/external/sphinx-contrib/ansi.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 259, in build
    self.doctreedir, self.app))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 618, in update
    self._read_serial(docnames, app)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 638, in _read_serial
    self.read_doc(docname, app)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 791, in read_doc
    pub.publish()
  File "/usr/local/lib/python2.7/dist-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 126, in read
    self.parse()
  File "/usr/local/lib/python2.7/dist-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 1135, in indent
    elements = self.block_quote(indented, line_offset)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 1150, in block_quote
    self.nested_parse(blockquote_lines, line_offset, blockquote)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python2.7/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/local/lib/python2.7/dist-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/home/dario/Schreibtisch/haka/external/breathe/breathe/directives.py", line 323, in run
    finder = self.finder_factory.create_finder(project_info)
  File "/home/dario/Schreibtisch/haka/external/breathe/breathe/finder/__init__.py", line 59, in create_finder
    root = self.parser.parse(project_info)
  File "/home/dario/Schreibtisch/haka/external/breathe/breathe/parser/__init__.py", line 38, in parse
    self.file_state_cache.update(filename)
  File "/home/dario/Schreibtisch/haka/external/breathe/breathe/directives.py", line 1048, in update
    new_mtime = self.mtimer.get_mtime(source_file)
  File "/home/dario/Schreibtisch/haka/external/breathe/breathe/directives.py", line 1026, in get_mtime
    return self.getmtime(filename)
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '../examples/specific/class/xml/index.xml'
---------
Exception occurred:
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '../examples/specific/class/xml/index.xml'
---------
```

Best regards

**Comment by shimizukawa** [comment]
I guess the issue is caused from breathe extension or haka extension.
Please report it to extension owner.
- breathe: https://github.com/michaeljones/breathe
- haka: https://github.com/haka-security/haka
