### ISSUE TITLE
unicodeerror in test using python3

### ISSUE THREAD

**Issue by arunpersaud** [sphinx-doc/sphinx#1829]
Trying to package Sphinx using python3 on the openSUSE build server and I get unicode errors since the last two versions (1.3 and 1.3.1). Earlier version worked fine.

Here is a copy from the build log. The full log can be seen here:

https://build.opensuse.org/package/show/home:apersaud:branches:devel:languages:python3/python3-Sphinx

HTH

Arun

build log:

```
...................................................................................................................................................................................................................................................................................................................................................................................................................S.S.....S........E.E..............E...EEE.E.S..................................................................................................................................................................................................................SS..S...............................SSSSS.SSSS.
[  174s] ======================================================================
[  174s] ERROR: test_catalogs.test_compile_all_catalogs
[  174s] ----------------------------------------------------------------------
[  174s] Traceback (most recent call last):
[  174s]   File "/usr/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
[  174s]     self.test(*self.arg)
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/util.py", line 228, in deco
[  174s]     func(app, status, warning, *args2, **kwargs2)
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/test_catalogs.py", line 42, in test_compile_all_catalogs
[  174s]     app.builder.compile_all_catalogs()
[  174s]   File "/home/abuild/rpmbuild/BUILDROOT/python3-Sphinx-1.3.1-36.1.i386/usr/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 176, in compile_all_catalogs
[  174s]     self.compile_catalogs(catalogs, message)
[  174s]   File "/home/abuild/rpmbuild/BUILDROOT/python3-Sphinx-1.3.1-36.1.i386/usr/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 167, in compile_catalogs
[  174s]     catalog.write_mo(self.config.language)
[  174s]   File "/home/abuild/rpmbuild/BUILDROOT/python3-Sphinx-1.3.1-36.1.i386/usr/lib/python3.4/site-packages/sphinx/util/i18n.py", line 51, in write_mo
[  174s]     write_mo(mo, read_po(po, locale))
[  174s]   File "/usr/lib/python3.4/site-packages/babel/messages/pofile.py", line 204, in read_po
[  174s]     for lineno, line in enumerate(fileobj.readlines()):
[  174s]   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
[  174s]     return codecs.ascii_decode(input, self.errors)[0]
[  174s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 255: ordinal not in range(128)
[  174s] 
[  174s] ======================================================================
[  174s] ERROR: test_catalogs.test_compile_update_catalogs
[  174s] ----------------------------------------------------------------------
[  174s] Traceback (most recent call last):
[  174s]   File "/usr/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
[  174s]     self.test(*self.arg)
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/util.py", line 228, in deco
[  174s]     func(app, status, warning, *args2, **kwargs2)
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/test_catalogs.py", line 72, in test_compile_update_catalogs
[  174s]     app.builder.compile_update_catalogs()
[  174s]   File "/home/abuild/rpmbuild/BUILDROOT/python3-Sphinx-1.3.1-36.1.i386/usr/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 199, in compile_update_catalogs
[  174s]     self.compile_catalogs(catalogs, message)
[  174s]   File "/home/abuild/rpmbuild/BUILDROOT/python3-Sphinx-1.3.1-36.1.i386/usr/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 167, in compile_catalogs
[  174s]     catalog.write_mo(self.config.language)
[  174s]   File "/home/abuild/rpmbuild/BUILDROOT/python3-Sphinx-1.3.1-36.1.i386/usr/lib/python3.4/site-packages/sphinx/util/i18n.py", line 51, in write_mo
[  174s]     write_mo(mo, read_po(po, locale))
[  174s]   File "/usr/lib/python3.4/site-packages/babel/messages/pofile.py", line 204, in read_po
[  174s]     for lineno, line in enumerate(fileobj.readlines()):
[  174s]   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
[  174s]     return codecs.ascii_decode(input, self.errors)[0]
[  174s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 255: ordinal not in range(128)
[  174s] 
[  174s] ======================================================================
[  174s] ERROR: test_directive_code.test_code_block_caption_latex
[  174s] ----------------------------------------------------------------------
[  174s] Traceback (most recent call last):
[  174s]   File "/usr/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
[  174s]     self.test(*self.arg)
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/util.py", line 228, in deco
[  174s]     func(app, status, warning, *args2, **kwargs2)
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/test_directive_code.py", line 66, in test_code_block_caption_latex
[  174s]     latex = (app.outdir / 'Python.tex').text()
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/path.py", line 145, in text
[  174s]     return f.read()
[  174s]   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
[  174s]     return codecs.ascii_decode(input, self.errors)[0]
[  174s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12043: ordinal not in range(128)
[  174s] 
[  174s] ======================================================================
[  174s] ERROR: test_directive_code.test_literal_include_lineno_match
[  174s] ----------------------------------------------------------------------
[  174s] Traceback (most recent call last):
[  174s]   File "/usr/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
[  174s]     self.test(*self.arg)
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/util.py", line 228, in deco
[  174s]     func(app, status, warning, *args2, **kwargs2)
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/test_directive_code.py", line 148, in test_literal_include_lineno_match
[  174s]     html = (app.outdir / 'lineno_match.html').text()
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/path.py", line 145, in text
[  174s]     return f.read()
[  174s]   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
[  174s]     return codecs.ascii_decode(input, self.errors)[0]
[  174s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 7916: ordinal not in range(128)
[  174s] 
[  174s] ======================================================================
[  174s] ERROR: test_directive_code.test_literal_include_lineno_start
[  174s] ----------------------------------------------------------------------
[  174s] Traceback (most recent call last):
[  174s]   File "/usr/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
[  174s]     self.test(*self.arg)
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/util.py", line 228, in deco
[  174s]     func(app, status, warning, *args2, **kwargs2)
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/test_directive_code.py", line 126, in test_literal_include_lineno_start
[  174s]     html = (app.outdir / 'lineno_start.html').text()
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/path.py", line 145, in text
[  174s]     return f.read()
[  174s]   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
[  174s]     return codecs.ascii_decode(input, self.errors)[0]
[  174s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 7982: ordinal not in range(128)
[  174s] 
[  174s] ======================================================================
[  174s] ERROR: test_directive_code.test_literal_include_linenos
[  174s] ----------------------------------------------------------------------
[  174s] Traceback (most recent call last):
[  174s]   File "/usr/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
[  174s]     self.test(*self.arg)
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/util.py", line 228, in deco
[  174s]     func(app, status, warning, *args2, **kwargs2)
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/test_directive_code.py", line 104, in test_literal_include_linenos
[  174s]     html = (app.outdir / 'linenos.html').text()
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/path.py", line 145, in text
[  174s]     return f.read()
[  174s]   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
[  174s]     return codecs.ascii_decode(input, self.errors)[0]
[  174s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 7694: ordinal not in range(128)
[  174s] 
[  174s] ======================================================================
[  174s] ERROR: test_directive_code.test_literalinclude_caption_latex
[  174s] ----------------------------------------------------------------------
[  174s] Traceback (most recent call last):
[  174s]   File "/usr/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
[  174s]     self.test(*self.arg)
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/util.py", line 228, in deco
[  174s]     func(app, status, warning, *args2, **kwargs2)
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/test_directive_code.py", line 189, in test_literalinclude_caption_latex
[  174s]     latex = (app.outdir / 'Python.tex').text()
[  174s]   File "/home/abuild/rpmbuild/BUILD/Sphinx-1.3.1/tests/path.py", line 145, in text
[  174s]     return f.read()
[  174s]   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
[  174s]     return codecs.ascii_decode(input, self.errors)[0]
[  174s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12043: ordinal not in range(128)
[  174s] 
[  174s] ------------------------------------------------------------------[  151.128960] serial8250: too much work for irq4
[  174s] ----
[  174s] Ran 705 tests in 70.794s
[  174s] 
```

**Comment by termim** [comment]
BTW there is no errors for python2: https://build.opensuse.org/package/show/home:termim:branches:devel:languages:python/python-Sphinx

**Comment by birkenfeld** [comment]
The link now gives "not found". Does the problem still appear with current HEAD?

**Comment by arunpersaud** [comment]
Problem seems to have been fixed. Latest package in the build server builds correctly including executing all the tests.

**Comment by birkenfeld** [comment]
Great, thanks for the feedback!
