### ISSUE TITLE
Builds failing due to missing module recommonmark.parser

### ISSUE THREAD

**Issue by jerearista** [sphinx-doc/sphinx#1875]
The error, below, indicates that the build is unable to find recommonmark.parser but I can find no reference to that within my code and local sphinx-builds work without issue.   Can you advise how I might resolve the issue?
## html

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/puppet-eos/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/puppet-eos/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 126, in **init**
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/puppet-eos/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 277, in **init**
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/puppet-eos/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/puppet-eos/envs/latest/local/lib/python2.7/site-packages/six.py", line 672, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 288, in <module>
    from recommonmark.parser import CommonMarkParser
ImportError: No module named recommonmark.parser

Exception occurred:
  File "conf.py", line 288, in <module>
    from recommonmark.parser import CommonMarkParser
ImportError: No module named recommonmark.parser
The full traceback has been saved in /tmp/sphinx-err-hSXLzS.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!

**Comment by dkirkby** [comment]
I am getting the same error (https://readthedocs.org/builds/bossdata/2712355/) so the problem is not unique to @jerearista.

**Comment by ericholscher** [comment]
This is a read the docs issue, not a Sphinx issue..

**Comment by jerearista** [comment]
Confirmed.   

Also, appears to be resolved now.    Thanks!

**Comment by ashwinkumar12345** [comment]
having the same issue..how to resolve?
