### ISSUE TITLE
Sphinx object has to attribute 'get'

### ISSUE THREAD

**Issue by miketallroth** [sphinx-doc/sphinx#1929]
Any idea where I would go to start diagnosing this problem?

```
# Sphinx version: 1.3.1
# Python version: 2.7.5 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/application.py", line 143, in __init__
    self.setup_extension(extension)
  File "/Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/application.py", line 449, in setup_extension
    if not ext_meta.get('version'):
AttributeError: 'Sphinx' object has no attribute 'get'
```

**Comment by birkenfeld** [comment]
You have an extension that does `return app` in its `setup()` function.  That is not really supported (but will be handled more gracefully in 1.3.2).
