### ISSUE TITLE
API change for Config.init_values() in commit 1356aff6

### ISSUE THREAD

**Issue by toabctl** [sphinx-doc/sphinx#1933]
commit 1356aff6 added a second argument `warn` to the method `init_values()` defined in `sphinx/config.py:Config`. `init_values` is i.e. used by `pbr` and this now breaks `pbr`.
Build i.e. `pbr`'s documentation with Sphinx 1.1.3 works, but building it with 1.3.1 leads to:

```
running build_sphinx
[pbr] Writing ChangeLog
[pbr] Generating ChangeLog
[pbr] Generating AUTHORS
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    **util.cfg_to_args())
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/tom/devel/openstack-dev/pbr/pbr/builddoc.py", line 189, in run
    self._sphinx_run()
  File "/home/tom/devel/openstack-dev/pbr/pbr/builddoc.py", line 133, in _sphinx_run
    sphinx_config.init_values()
TypeError: init_values() takes exactly 2 arguments (1 given)
```

**Comment by lehmannro** [comment]
I think I would consider `sphinx.config.Config` an implementation detail;  also, the change has only been deployed in a new major (in Sphinx terms) release.

The better solution is fixing your code to not read the config itself and instead inspect `sphinx.application.Sphinx.config` after it has initialized the app.
