### ISSUE TITLE
ClassNotFound: Could not find style module 'matizze'

### ISSUE THREAD

**Issue by juanvladimir13** [sphinx-doc/sphinx#1948]
# Sphinx version: 1.3.1
# Python version: 2.7.3 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:
# Loaded extensions:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 188, in **init**
    self._init_builder(buildername)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 249, in _init_builder
    self.builder = builderclass(self)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 88, in **init**
    self.init()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/html.py", line 107, in init
    self.init_highlighter()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/html.py", line 155, in init_highlighter
    self.config.trim_doctest_flags)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/highlighting.py", line 78, in **init**
    style = get_style_by_name(stylename)
  File "/usr/local/lib/python2.7/dist-packages/pygments/styles/**init**.py", line 61, in get_style_by_name
    (builtin and ", though it should be builtin") + ".")
ClassNotFound: Could not find style module 'matizze'.

**Comment by shimizukawa** [comment]
@juanvladimir I suspect that it's a user error.
Pygments doesn't have 'matizze' style ([see](https://bitbucket.org/birkenfeld/pygments-main/src/652e08e410f4f4f3a61add91f75ce5ed9d134711/pygments/styles/?at=default)).

If your conf.py of sphinx document has `pygments_style = 'matizze'`, it isn't correct.
Please try `pygments_style = 'default'` or `'sphinx'`.

**Comment by shimizukawa** [comment]
Now I close this issue. Please feel free to reopen if there is more to discuss.
