### ISSUE TITLE
AttributeError during documentation coverage

### ISSUE THREAD

**Issue by gergelypolonkai** [sphinx-doc/sphinx#1949]
While generating doc coverage report for my Django project that uses [Django-FSM](https://github.com/kmmbvnr/django-fsm) I get an AttributeError:

```
#   /local/scratch/epolger/demand/doc/builds/models.rst:4: WARNING: autodoc: failed to import attribute u'Build.state' from module u'builds.models'; the following exception was raised:
Traceback (most recent call last):
  File "/local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 392, in import_object
    obj = self.get_attr(obj, part)
  File "/local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 288, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: state
#   /local/scratch/epolger/demand/doc/builds/models.rst:4: WARNING: autodoc: failed to import attribute u'FieldValue.state' from module u'builds.models'; the following exception was raised:
Traceback (most recent call last):
  File "/local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 392, in import_object
    obj = self.get_attr(obj, part)
  File "/local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 288, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: state
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
# Loaded extensions:
#   sphinx.ext.coverage (1.3.1) from /local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/ext/coverage.pyc
#   alabaster (0.7.5) from /local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.autodoc (1.3.1) from /local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx (1.3.1) from /local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
Traceback (most recent call last):
  File "/local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 240, in build_update
    self.build(['__all__'], to_build)
  File "/local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 316, in build
    self.write(docnames, list(updated_docnames), method)
  File "/local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/ext/coverage.py", line 77, in write
    self.build_py_coverage()
  File "/local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/sphinx/ext/coverage.py", line 190, in build_py_coverage
    attr = getattr(obj, attr_name)
  File "/local/scratch/epolger/demand/demand-venv/lib/python2.7/site-packages/django_fsm/__init__.py", line 205, in __get__
    raise AttributeError('Can only be accessed via an instance.')
AttributeError: Can only be accessed via an instance.
```

`Build.state` is an `FSMStateField` provided by Django-FSM. This may be a duplicate of, or related to #911.

**Comment by birkenfeld** [comment]
Thanks for the report!
