### ISSUE TITLE
UnboundLocalError: local variable 'domain' referenced before assignment

### ISSUE THREAD

**Issue by GFiedler-ADC** [sphinx-doc/sphinx#1974]
```
# Sphinx version: 1.3.1
# Python version: 3.4.3 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:
#   writing output... [ 29%] _source/algebraixlib/algebraixlib.io.csv
#   writing output... [ 32%] _source/algebraixlib/algebraixlib.io.json
#   writing output... [ 35%] _source/algebraixlib/algebraixlib.io.mojson
#   writing output... [ 37%] _source/algebraixlib/algebraixlib.io.rdf
#   writing output... [ 40%] _source/algebraixlib/algebraixlib.io.xml
#   writing output... [ 43%] _source/algebraixlib/algebraixlib.mathobjects
#   writing output... [ 45%] _source/algebraixlib/algebraixlib.mathobjects.atom
#   writing output... [ 48%] _source/algebraixlib/algebraixlib.mathobjects.couplet
#   writing output... [ 51%] _source/algebraixlib/algebraixlib.mathobjects.mathobject
#   writing output... [ 54%] _source/algebraixlib/algebraixlib.mathobjects.multiset
# Loaded extensions:
#   sphinx.ext.viewcode (1.3.1) from C:\cmd\Python34\lib\site-packages\sphinx\ext\viewcode.py
#   sphinx.ext.doctest (1.3.1) from C:\cmd\Python34\lib\site-packages\sphinx\ext\doctest.py
#   sphinx.ext.todo (1.3.1) from C:\cmd\Python34\lib\site-packages\sphinx\ext\todo.py
#   sphinx.ext.autodoc (1.3.1) from C:\cmd\Python34\lib\site-packages\sphinx\ext\autodoc.py
#   sphinx.ext.mathjax (1.3.1) from C:\cmd\Python34\lib\site-packages\sphinx\ext\mathjax.py
#   sphinx.ext.intersphinx (1.3.1) from C:\cmd\Python34\lib\site-packages\sphinx\ext\intersphinx.py
#   sphinx.ext.coverage (1.3.1) from C:\cmd\Python34\lib\site-packages\sphinx\ext\coverage.py
#   alabaster (0.7.3) from C:\cmd\Python34\lib\site-packages\alabaster\__init__.py
Traceback (most recent call last):
  File "C:\cmd\Python34\lib\site-packages\sphinx\cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "C:\cmd\Python34\lib\site-packages\sphinx\application.py", line 264, in build
    self.builder.build_update()
  File "C:\cmd\Python34\lib\site-packages\sphinx\builders\__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "C:\cmd\Python34\lib\site-packages\sphinx\builders\__init__.py", line 316, in build
    self.write(docnames, list(updated_docnames), method)
  File "C:\cmd\Python34\lib\site-packages\sphinx\builders\__init__.py", line 354, in write
    self._write_serial(sorted(docnames), warnings)
  File "C:\cmd\Python34\lib\site-packages\sphinx\builders\__init__.py", line 360, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "C:\cmd\Python34\lib\site-packages\sphinx\environment.py", line 1291, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "C:\cmd\Python34\lib\site-packages\sphinx\environment.py", line 1557, in resolve_references
    'missing-reference', self, node, contnode)
  File "C:\cmd\Python34\lib\site-packages\sphinx\application.py", line 501, in emit_firstresult
    for result in self.emit(event, *args):
  File "C:\cmd\Python34\lib\site-packages\sphinx\application.py", line 497, in emit
    results.append(callback(self, *args))
  File "C:\cmd\Python34\lib\site-packages\sphinx\ext\intersphinx.py", line 262, in missing_reference
    (domain == 'std' and node['reftype'] == 'keyword'):
UnboundLocalError: local variable 'domain' referenced before assignment
```

**Comment by shimizukawa** [comment]
Thanks for reporting!
A change a973daea418d361627040474c1924eb58d12280b is the cause.
We will fix it.

**Comment by shimizukawa** [comment]
test passed. https://travis-ci.org/sphinx-doc/sphinx/builds/91407415
