### ISSUE TITLE
Babel 2.0 issue with Python v3.4.3 on Windows

### ISSUE THREAD

**Issue by NoralK** [sphinx-doc/sphinx#1976]
On Windows with Python v3.4.3 I try to install Sphinx with:

```
pip install Sphinx
```

During the install it installs [babel v2.0](https://github.com/mitsuhiko/babel/releases) released 5 days ago.  When I try to compile any documentation project I get the following:

```
make html
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\sphinx-build.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\sphinx\__init__.py", line 51, in main
    sys.exit(build_main(argv))
  File "C:\Python34\lib\site-packages\sphinx\__init__.py", line 61, in build_mai
n
    from sphinx import cmdline
  File "C:\Python34\lib\site-packages\sphinx\cmdline.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "C:\Python34\lib\site-packages\sphinx\application.py", line 37, in <modul
e>
    from sphinx.builders import BUILTIN_BUILDERS
  File "C:\Python34\lib\site-packages\sphinx\builders\__init__.py", line 23, in
<module>
    from sphinx.util import i18n, path_stabilize
  File "C:\Python34\lib\site-packages\sphinx\util\i18n.py", line 15, in <module>

    from babel.messages.pofile import read_po
  File "C:\Python34\lib\site-packages\babel\messages\__init__.py", line 12, in <
module>
    from babel.messages.catalog import *
  File "C:\Python34\lib\site-packages\babel\messages\catalog.py", line 23, in <m
odule>
    from babel.dates import format_datetime
  File "C:\Python34\lib\site-packages\babel\dates.py", line 28, in <module>
    from babel.util import UTC, LOCALTZ
  File "C:\Python34\lib\site-packages\babel\util.py", line 278, in <module>
    from babel import localtime
  File "C:\Python34\lib\site-packages\babel\localtime\__init__.py", line 21, in
<module>
    from babel.localtime._win32 import _get_localzone
  File "C:\Python34\lib\site-packages\babel\localtime\_win32.py", line 18, in <m
odule>
    tz_names = get_global('windows_zone_mapping')
  File "C:\Python34\lib\site-packages\babel\core.py", line 58, in get_global
    _global_data = pickle.load(fileobj)
TypeError: an integer is required (got type str)
```

However, if I uninstall babel v2.0 and install 1.3 then all is OK.

```
pip uninstall babel
pip install babel==1.3
```

BTW on Python v2.7.10 on Windows babel v2.0 installs and does not have this issue.

**Comment by shimizukawa** [comment]
It seems that the bug can be reproduced by:

```
C:\> python
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:45:13) [MSC v.1600 64 bit (AMD64)] on win32
>>> from babel.messages.pofile import read_po
...
  File "D:\py34\lib\site-packages\babel\localtime\_win32.py", line 18, in <module>
    tz_names = get_global('windows_zone_mapping')
  File "D:\py34\lib\site-packages\babel\core.py", line 58, in get_global
    _global_data = pickle.load(fileobj)
TypeError: an integer is required (got type str)
```

Related issues are:
https://github.com/mitsuhiko/babel/issues/175
https://github.com/mitsuhiko/babel/issues/174

There is nothing to do from sphinx side.

**Comment by NoralK** [comment]
I would suggest putting something on http://sphinx-doc.org for known issues so people don't have to spend time hunting down solutions to known problems, especially since there is a fix.

**Comment by ideasman42** [comment]
Is there any information on what regular users (not Python experts) should do to resolve?
We had 2 users run into this recently: https://developer.blender.org/T45908

Even after reading over these reports, am not sure what to tell others exactly...
downgrade babel? upgrade since its now marked as fixed?

**Comment by shimizukawa** [comment]
In any case, you can install with avoiding babel issue by this installation command:

```
pip install sphinx "babel<2.0"
```

**Comment by minchinweb** [comment]
I just spent all morning trying to figure out why sphinx stopped working. Can the `setup.py` file be updated such that babel 2.0 isn't installed. So:

`babel<=1.3,>2.0`

Thanks!

**Comment by NoralK** [comment]
I am in complete agreement!
