### ISSUE TITLE
Python 3.4/Windows bug

### ISSUE THREAD

**Issue by dave-yang** [sphinx-doc/sphinx#1977]
Seems like there's a bug when installing sphinx on Python 3.4 for Windows. I didn't touch any line of code, just followed the guide step by step. The problem, is that `sphinx-quickstart` works and generates a structure perfectly. But when calling `sphinx-build html` or `make html`, Python throws the following exception:

```
D:\my-doc>make html
Traceback (most recent call last):

  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code exec(code, run_globals)
  File "C:\Python34\Scripts\sphinx-build.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\sphinx\__init__.py", line 51, in main sys.exit(build_main(argv))
  File "C:\Python34\lib\site-packages\sphinx\__init__.py", line 61, in build_main from sphinx import cmdline
  File "C:\Python34\lib\site-packages\sphinx\cmdline.py", line 23, in <module> from sphinx.application import Sphinx
  File "C:\Python34\lib\site-packages\sphinx\application.py", line 37, in <module> from sphinx.builders import BUILTIN_BUILDERS
  File "C:\Python34\lib\site-packages\sphinx\builders\__init__.py", line 23, in <module> from sphinx.util import i18n, path_stabilize
  File "C:\Python34\lib\site-packages\sphinx\util\i18n.py", line 15, in <module> from babel.messages.pofile import read_po
  File "C:\Python34\lib\site-packages\babel\messages\__init__.py", line 12, in <module> from babel.messages.catalog import *
  File "C:\Python34\lib\site-packages\babel\messages\catalog.py", line 23, in <module> from babel.dates import format_datetime
  File "C:\Python34\lib\site-packages\babel\dates.py", line 28, in <module> from babel.util import UTC, LOCALTZ
  File "C:\Python34\lib\site-packages\babel\util.py", line 278, in <module> from babel import localtime
  File "C:\Python34\lib\site-packages\babel\localtime\__init__.py", line 21, in <module> from babel.localtime._win32 import _get_localzone
  File "C:\Python34\lib\site-packages\babel\localtime\_win32.py", line 18, in <module> tz_names = get_global('windows_zone_mapping')
  File "C:\Python34\lib\site-packages\babel\core.py", line 58, in get_global _global_data = pickle.load(fileobj) TypeError: an integer is required (got type str)
```

While everything works perfectly with Python 2.7.
I guess, there must be something wrong in `\babel\core.py` and this is related to compatibility issue.

**Comment by shimizukawa** [comment]
Thanks. Duplicated #1976.
