### ISSUE TITLE
INFO:  Error and Fix while installing Git branches

### ISSUE THREAD

**Issue by NoralK** [sphinx-doc/sphinx#1988]
I am getting this error when installing on Windows:

```
C:\Users\Administrator>pip install git+https://github.com/sphinx-doc/sphinx@stable
Collecting git+https://github.com/sphinx-doc/sphinx@stable
  Cloning https://github.com/sphinx-doc/sphinx (to stable) to c:\users\admini~1\appdata\local\temp\pip-oekwrlzc-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-oekwrlzc-build\setup.py", line 84, in <module>
        from babel.messages.pofile import read_po
      File "C:\Python34\lib\site-packages\babel\messages\__init__.py", line 12, in <module>
        from babel.messages.catalog import *
      File "C:\Python34\lib\site-packages\babel\messages\catalog.py", line 23, in <module>
        from babel.dates import format_datetime
      File "C:\Python34\lib\site-packages\babel\dates.py", line 28, in <module>
        from babel.util import UTC, LOCALTZ
      File "C:\Python34\lib\site-packages\babel\util.py", line 278, in <module>
        from babel import localtime
      File "C:\Python34\lib\site-packages\babel\localtime\__init__.py", line 21, in <module>
        from babel.localtime._win32 import _get_localzone
      File "C:\Python34\lib\site-packages\babel\localtime\_win32.py", line 18, in <module>
        tz_names = get_global('windows_zone_mapping')
      File "C:\Python34\lib\site-packages\babel\core.py", line 58, in get_global
        _global_data = pickle.load(fileobj)
    TypeError: an integer is required (got type str)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-oekwrlzc-build
```

Again Babel 2.0 is the culprit.  I uninstalled babel 2.0 and reinstalled babel 1.3:

```
pip uninstall babel
pip install babel==1.3 
```

I really think something should be put in the Readme and on the web site.

**Comment by shimizukawa** [comment]
Duplicates #1976
