### ISSUE TITLE
 TemplateNotFound: default/layout.html

### ISSUE THREAD

**Issue by i1abnrk** [sphinx-doc/sphinx#2007]
I have a error building groonga from source on Ubuntu with sphinx install from pip as unprivileged user. Most of the doc built successfully but spit this error. There's a similar error reported for pdf but this involves html docs.

```
Exception occurred:
  File "/usr/local/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/jinja2glue.py", line 159, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: default/layout.html
```

here's trace file:

```
# Sphinx version: 1.3.1
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   /home/zakri/Programs/groonga/groonga-5.0.6/doc/source/reference/cast.rst:: WARNING: document isn't included in any toctree
#   /home/zakri/Programs/groonga/groonga-5.0.6/doc/source/reference/scoring_note.rst:: WARNING: document isn't included in any toctree
#   done
#   preparing documents...
#   done
#   writing output... [  0%] characteristic
# Loaded extensions:
#   alabaster (0.7.3) from /usr/local/anaconda/lib/python2.7/site-packages/alabaster/__init__.pyc
Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/usr/local/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/usr/local/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/builders/__init__.py", line 316, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/builders/__init__.py", line 354, in write
    self._write_serial(sorted(docnames), warnings)
  File "/usr/local/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/builders/__init__.py", line 362, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/local/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/builders/html.py", line 445, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/usr/local/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/builders/html.py", line 786, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/usr/local/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/jinja2glue.py", line 138, in render
    return self.environment.get_template(template).render(context)
  File "/usr/local/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/home/zakri/Programs/groonga/groonga-5.0.6/doc/source/../themes/groonga/layout.html", line 10, in top-level template code
    {% extends "default/layout.html" %}
  File "/usr/local/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/jinja2glue.py", line 159, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: default/layout.html
```

**Comment by kenhys** [comment]
Since [Sphinx 1.3b1](http://sphinx-doc.org/changes.html#release-1-3b3-released-feb-24-2015), the 'default' theme name is changed to 'classic'. 
To fix the issue, change 'default/layout.html' to 'classic/layout.html' in themes/groonga/layout.html.

**Comment by tk0miya** [comment]
This problem was already fixed at groonga repos.
https://github.com/groonga/groonga/commit/e8005662395451480ca1e931d330d43c86da5623
