### ISSUE TITLE
Exception occurred:

### ISSUE THREAD

**Issue by arafune** [sphinx-doc/sphinx#2012]
```
# Sphinx version: 1.3.1
# Python version: 3.4.3 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  5%] Ag111Revisited
#   writing output... [ 10%] Ag111SurfaceBand
# Loaded extensions:
#   sphinx.ext.ifconfig (1.3.1) from /usr/local/lib/python3.4/site-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.mathjax (1.3.1) from /usr/local/lib/python3.4/site-packages/sphinx/ext/mathjax.py
#   sphinx.ext.todo (1.3.1) from /usr/local/lib/python3.4/site-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (1.3.1) from /usr/local/lib/python3.4/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.intersphinx (1.3.1) from /usr/local/lib/python3.4/site-packages/sphinx/ext/intersphinx.py
#   alabaster (0.7.6) from /usr/local/lib/python3.4/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.3.1) from /usr/local/lib/python3.4/site-packages/sphinx/ext/autodoc.py
#   sphinx.ext.doctest (1.3.1) from /usr/local/lib/python3.4/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.viewcode (1.3.1) from /usr/local/lib/python3.4/site-packages/sphinx/ext/viewcode.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python3.4/site-packages/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 316, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 354, in write
    self._write_serial(sorted(docnames), warnings)
  File "/usr/local/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 360, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/local/lib/python3.4/site-packages/sphinx/environment.py", line 1291, in   get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/usr/local/lib/python3.4/site-packages/sphinx/environment.py", line 1546, in resolve_references
    typ, target, node, contnode)
  File "/usr/local/lib/python3.4/site-packages/sphinx/domains/std.py", line 649, in resolve_xref
    newtitle = title % '.'.join(map(str, fignumber))
TypeError: not all arguments converted during string formatting
```

**Comment by shimizukawa** [comment]
I guess you've set custom `numfig_format` in conf.py and the string value doesn't have `%s` placeholder.
Please check it.

**Comment by shimizukawa** [comment]
@tk0miya could you implement friendly error message for illegal `numfig_format`?

**Comment by arafune** [comment]
Thank you for your answer.  I have checked my conf.py and found no
numfig_format was set, unfortunately.

Please see the attached file of conf.py.

Can you identify the problematic points?

Ryuichi Arafune

2015-08-27 15:47 GMT+09:00 Takayuki SHIMIZUKAWA notifications@github.com:

**Comment by shimizukawa** [comment]
> Please see the attached file of conf.py.

github issue cant' have attach files.
Please paste contents of conf.py as a issue comment.

**Comment by arafune** [comment]
The below is just my conf.py file.  Thank you in advance.

```
# -*- coding: utf-8 -*-
#
# VASP for experimentalist documentation build configuration file, created
by
# sphinx-quickstart on Fri Oct 31 13:44:17 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import sphinx_rtd_theme

# If extensions (or modules to document with autodoc) are in another
directory,
# add these directories to sys.path here. If the directory is relative to
the
# documentation root, use os.path.abspath to make it absolute, like shown
here.
#sys.path.insert(0,
os.path.relpath('/Users/arafune/Dropbox/VASP_for_Experimentalist/source/'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

#sys.path.insert(0, os.path.abspath('/Users/arafune/src/sphinx-numfig'))

numfig = True

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
#    'sphinx_numfig',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'VASP for experimentalist'
copyright = u'2014, Ryuichi Arafune'

# The version info for the project you're documenting, acts as replacement
for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.81'
# The full version, including alpha/beta/rc tags.
release = '0.81'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built
documents.
#keep_warnings = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#html_theme = 'default'
#html_theme = 'bizstyle'
html_theme = 'sphinx_rtd_theme'
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# Theme options are theme-specific and customize the look and feel of a
theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = u"実験家による実験家のためのVASP入門"

# A shorter title for the navigation bar.  Default is the same as
html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of
the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets)
here,
# relative to this directory. They are copied after the builtin static
files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page
bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is
True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = False

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be
the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'VASPforexperimentalistdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
'papersize': 'a4paper',

# The font size ('10pt', '11pt' or '12pt').
'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
'preamble':   r'''
\renewcommand{\chaptername}{Chapter}
\addto\captionsjapanese{%
  \def\prepartname{Part}%
  \def\postpartnam{}%
  \def\prechaptername{Chapter}%
  \def\postchaptername{}%
  \def\presectionname{}%
  \def\postsectionname{}%
  \def\prefacename{Preface}%
  \def\refname{Bibliography}%
  \def\bibname{References}%
  \def\abstractname{Abstract}%
  \def\appendixname{Appendix}%
  \def\contentsname{Contents}%
  \def\listfigurename{Figure Contents}%
  \def\listtablename{List contents}%
  \def\indexname{Index}%
  \def\figurename{Fig. }%
  \def\tablename{Table}%
  }
''',
'transition': '',
'extraclassoptions': ',openany,oneside',
'classoptions': ',dvipdfmx',
'babel': '\usepackage[japanese]{babel}',
}


# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'VASPforexperimentalist.tex', u'実験家による実験家のためのVASP入門', u'Ryuichi
Arafune', 'manual'),
]

#latex_docclass = {"howto": "jsarticle", "manual": "jsbook"}

# The name of an image file (relative to this directory) to place at the
top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_use_parts = True

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'vaspforexperimentalist', u'VASP for experimentalist',
     [u'Ryuichi Arafune'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'VASPforexperimentalist', u'VASP for experimentalist
Documentation',
   u'Ryuichi Arafune', 'VASPforexperimentalist', 'One line description of
project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False


# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = u'実験家による実験家のためのVASP入門'
epub_author = u'荒船竜一'
epub_publisher = u'Ryuichi Arafune'
epub_copyright = u'2014, Ryuichi Arafune'

# The basename for the epub file. It defaults to the project name.
#epub_basename = u'VASP for experimentalist'

# The HTML theme for the epub output. Since the default themes are not
optimized
# for small screen space, using the same theme for HTML and epub output is
# usually not wise. This defaults to 'epub', a theme designed to save visual
# space.
epub_theme = 'epub'
#epub_theme = 'agogo'
#epub_theme = 'pyramid'

# The language of the text. It defaults to the language option
# or en if the language is not set.
#epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
#epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#epub_identifier = ''

# A unique identification for the text.
#epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
#epub_cover = ()

# A sequence of (type, uri, title) tuples for the guide element of
content.opf.
#epub_guide = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_pre_files = []

# HTML files shat should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_post_files = []

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# The depth of the table of contents in toc.ncx.
#epub_tocdepth = 3

# Allow duplicate toc entries.
#epub_tocdup = True

# Choose between 'default' and 'includehidden'.
#epub_tocscope = 'default'

# Fix unsupported image types using the PIL.
#epub_fix_images = False

# Scale large images.
#epub_max_image_width = 0

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#epub_show_urls = 'inline'

# If false, no index is generated.
epub_use_index = False


# Example configuration for intersphinx: refer to the Python standard
library.
intersphinx_mapping = {'http://docs.python.org/': None}
```

Ryuichi Arafune

2015-09-20 14:21 GMT+09:00 Takayuki SHIMIZUKAWA notifications@github.com:

**Comment by shimizukawa** [comment]
Hum, I can't reproduce the problem as you mentioned.
Please create and paste a smallest sample of sphinx project to reproduce it.

**Comment by arafune** [comment]
I have found the wrong point.  You changed the format about the :numref: a
little bit.  I can fix the point by changing rst file.
So you don't worry about the point that the new user doesn't meet the
problem I met.

Sorry about bothering you.
Regards,

Ryuichi Arafune

2015-09-22 9:15 GMT+09:00 Takayuki SHIMIZUKAWA notifications@github.com:

**Comment by shimizukawa** [comment]
Good to know :)
