### ISSUE TITLE
sphinx: make html fails Exception Occurred 

### ISSUE THREAD

**Issue by aktech** [sphinx-doc/sphinx#2028]
```
# Sphinx version: 1.3.1
# Python version: 3.4.3 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/amit/anaconda3/lib/python3.4/site-packages/Sphinx-1.3.1-py3.4.egg/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/amit/anaconda3/lib/python3.4/site-packages/Sphinx-1.3.1-py3.4.egg/sphinx/application.py", line 143, in __init__
    self.setup_extension(extension)
  File "/home/amit/anaconda3/lib/python3.4/site-packages/Sphinx-1.3.1-py3.4.egg/sphinx/application.py", line 429, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "ext/numpydoc.py", line 41
    title_re = re.compile(ur'^\s*[#*=]{4,}\n[a-z0-9 -]+\n[#*=]{4,}\s*',
                                                                     ^
SyntaxError: invalid syntax
```

**Comment by QuLogic** [comment]
A `ur` prefix is not valid in Python 3. It's a bug in the `ext/numpydoc.py` (from `sympy`.) If `sympy` didn't ship its own copy, maybe it wouldn't be out of date.

**Comment by asmeurer** [comment]
This isn't a bug in Sphinx. SymPy ships an old version of numpydoc (in `ext`).
