### ISSUE TITLE
UnicodeDecodeError in shpinx-apidoc when author contains non-ascii characters

### ISSUE THREAD

**Issue by bjodah** [sphinx-doc/sphinx#2040]
See below:

```
$ sphinx-apidoc --version
Sphinx (sphinx-apidoc) 1.3.1
$ sphinx-apidoc -F --doc-author="Björn Dahlgren" -f -o doc2 pygslodeiv2/Creating file doc2/pygslodeiv2.rst.
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-apidoc", line 11, in <module>
    sys.exit(main())
  File "/home/bjorn/.local/lib/python2.7/site-packages/sphinx/apidoc.py", line 374, in main
    qs.generate(d, silent=True, overwrite=opts.force)
  File "/home/bjorn/.local/lib/python2.7/site-packages/sphinx/quickstart.py", line 1316, in generate
    d['author_texescaped'] = text_type(d['author']).\
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
```

**Comment by tk0miya** [comment]
Fixed at f1cf5d5.

Thank you for reporting.
