### ISSUE TITLE
__import__ always raises ImportError, (building sphinx and running sphinx-apidoc)

### ISSUE THREAD

**Issue by NucleaPeon** [sphinx-doc/sphinx#2046]
I first discovered what I think is a bug when attempting to run `sphinx-apidoc` on a test python project I created. It looks like this:

```
project/
    modulea/
                  __init__.py 
    moduleb/
                  __init__.py
    modulec/
                  __init__.py
                  module_c_a.py
```

Each file had at least one docstring in it. I ran `sphinx-apidoc -F -o docs/ project/` to create the documentation. 
This is my stack trace:

```
project.rst:16: WARNING: autodoc: failed to import module 'project'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
__import__(self.modname)
  ImportError: No module named 'project'
  /home/dann/Github/smartsphinx/test/docs/project.modulea.rst:7: WARNING: autodoc: failed to import module 'project.modulea'; the following exception was raised:
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
__import__(self.modname)
  ImportError: No module named 'project'
  /home/dann/Github/smartsphinx/test/docs/project.moduleb.rst:7: WARNING: autodoc: failed to import module 'project.moduleb'; the following exception was raised:
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
__import__(self.modname)
  ImportError: No module named 'project'
  /home/dann/Github/smartsphinx/test/docs/project.modulec.rst:10: WARNING: autodoc: failed to import module 'project.modulec.modulec_a'; the following exception was raised:
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
__import__(self.modname)
  ImportError: No module named 'project'
  /home/dann/Github/smartsphinx/test/docs/project.modulec.rst:19: WARNING: autodoc: failed to import module 'project.modulec'; the following exception was raised:
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
__import__(self.modname)
  ImportError: No module named 'project'
  looking for now-outdated files... none found
  pickling environment... done
  checking consistency... done
  preparing documents... done
  writing output... [100%] project.modulec                                                                                         
  writing additional files... (0 module code pages) genindex search
  copying static files... done
  copying extra files... done
  dumping search index... done
  dumping object inventory... done
  build succeeded, 5 warnings.
```

When I run my `python3.4` interpreter, I can import my modules just fine. I also have a `sys.path.insert()` command that adds the directory just above `project` and have tested setting it to `project` as well. No go.

I tried using `importlib` to import my module, and that works fine. 

I notice that in the python docs, https://docs.python.org/3/library/functions.html#__import__, it mentions that `__import__()` use is discouraged.

```
This function is invoked by the import statement. It can be replaced (by importing the builtins 
module and assigning to builtins.__import__) in order to change semantics of the import 
statement, but doing so is strongly discouraged as it is usually simpler to use import hooks (see 
PEP 302) to attain the same goals and does not cause issues with code which assumes the 
default import implementation is in use. Direct use of __import__() is also discouraged in favor of 
importlib.import_module().
```

I tried checking out the master git branch of sphinx to compile it myself in case a fix was there.
For reference, I installed sphinx using pip3 first of all, then python3-sphinx. Both had the same issue. When compiling from master source, the ez_install failed on nose. I installed python3-nose and python3-nose2 and it still failed! I go into my interpreter again, import nose and it is successful! 

I think **import** is a bug. I will attempt a patch.

**Comment by NucleaPeon** [comment]
Weird, `__import__()` also works in my interpreter, but fails when making sphinx....
OK, scratch that, `importlib` does not work either. 

My hunch is that sphinx is still strongly based in the `python2` way of doing things which is causing me issue as my modules and code are `python3`.

**Comment by NucleaPeon** [comment]
I changed the top of the Makefile, line `PYTHON ?= python` to `PYTHON ?= python3.4` and now it fails on this:

```
Traceback (most recent call last):
  File "utils/check_sources.py", line 16, in <module>
import cStringIO
ImportError: No module named 'cStringIO' 
make: *** [check] Error 1
```

`cStringIO` was removed in python3, so it looks like sphinx is just not python3 compatible yet...

**Comment by birkenfeld** [comment]
`project` is not a module/package and therefore cannot be imported if it doesn't have a `__init__.py`.

That `check_sources.py` is not Python 3 compatible is a red herring; it's a little used script that only checks superficial things. I just fixed it. The test suite is run with `make test`.

**Comment by peterjc** [comment]
@birkenfeld I believe you don't need an ``__init__.py`` file as of Python 3.3, see https://www.python.org/dev/peps/pep-0420/

**Comment by tk0miya** [comment]
Now `sphinx-apidoc` supports implicit namespaces when `--implicit-namespace` option given.

I confirmed it with following Dockerfile.
```
FROM tk0miya/sphinx-html

RUN mkdir -p project/modulea
RUN mkdir -p project/moduleb
RUN mkdir -p project/modulec
RUN echo '# coding: utf-8' > project/modulea/__init__.py
RUN echo '# coding: utf-8' > project/moduleb/__init__.py
RUN echo '# coding: utf-8' > project/modulec/__init__.py
RUN echo '# coding: utf-8' > project/modulec/module_c_a.py
RUN sphinx-apidoc -F --implicit-namespace -o docs/ project/
RUN echo '' >> docs/conf.py
RUN echo 'import os, sys' >> docs/conf.py
RUN echo 'sys.path.insert(0, os.path.abspath(".."))' >> docs/conf.py
RUN make -C docs html
```
```
...
Running Sphinx v1.7.1
loading translations [en]... done
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 4 source files that are out of date
updating environment: 4 added, 0 changed, 0 removed
reading sources... [ 25%] index
reading sources... [ 50%] project.modulea
reading sources... [ 75%] project.moduleb
reading sources... [100%] project.modulec

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 25%] index
writing output... [ 50%] project.modulea
writing output... [ 75%] project.moduleb
writing output... [100%] project.modulec

generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.
```

I think this is resolved now.

**Comment by tk0miya** [comment]
I'm closing this now.
Please let me know if newest Sphinx does not work with your intention.
Thanks,
