### ISSUE TITLE
Assertion error on certain declarations in C++ domain.

### ISSUE THREAD

**Issue by Rapptz** [sphinx-doc/sphinx#2058]
Minimal input:

```
.. cpp:function:: template<typename Char, typename Traits> inline std::basic_ostream<Char, Traits> & operator<<(std::basic_ostream<Char, Traits> & os, const c_string_view_base<const Char, Traits> & str)

    Stuff
```

Traceback:

```
# Sphinx version: 1.4a0+
# Python version: 2.7.9 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [100%] index
# Loaded extensions:
#   alabaster (0.7.6) from C:\Python27\lib\site-packages\alabaster\__init__.pyc
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\sphinx\cmdline.py", line 240, in main
    app.build(opts.force_all, filenames)
  File "C:\Python27\lib\site-packages\sphinx\application.py", line 268, in build
    self.builder.build_update()
  File "C:\Python27\lib\site-packages\sphinx\builders\__init__.py", line 252, in build_update
    'out of date' % len(to_build))
  File "C:\Python27\lib\site-packages\sphinx\builders\__init__.py", line 323, in build
    self.write(docnames, list(updated_docnames), method)
  File "C:\Python27\lib\site-packages\sphinx\builders\__init__.py", line 361, in write
    self._write_serial(sorted(docnames), warnings)
  File "C:\Python27\lib\site-packages\sphinx\builders\__init__.py", line 367, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "C:\Python27\lib\site-packages\sphinx\environment.py", line 1291, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "C:\Python27\lib\site-packages\sphinx\environment.py", line 1546, in resolve_references
    typ, target, node, contnode)
  File "C:\Python27\lib\site-packages\sphinx\domains\cpp.py", line 3679, in resolve_xref
    node, contnode)[0]
  File "C:\Python27\lib\site-packages\sphinx\domains\cpp.py", line 3664, in _resolve_xref_inner
    fullNestedName = s.get_full_nested_name()
  File "C:\Python27\lib\site-packages\sphinx\domains\cpp.py", line 2112, in get_full_nested_name
    for nne, templateParams in self.get_lookup_key():
  File "C:\Python27\lib\site-packages\sphinx\domains\cpp.py", line 2098, in get_lookup_key
    assert s.identifier
AssertionError
```

I tried looking into it but I'm not exactly sure why `s.identifier` isn't set.

**Comment by jakobandersen** [comment]
Thanks for the bug report. The identifier is not set because it's an operator. It's the assertion which is wrong. I'll try to fix it soon.
