### ISSUE TITLE
Bug report about sphinx on Windows

### ISSUE THREAD

**Issue by ChrisArnault** [sphinx-doc/sphinx#2079]
Hi,

I'm using sphinx on my Windows 7 platform

I have successfully installed sphinx (Python 2.7)

running Sphinx it felt on error :

here is the traceback

```
===================================================================================
# Sphinx version: 1.2b1
# Python version: 2.7.5
# Docutils version: 0.11 release
# Jinja2 version: 2.7.1
Traceback (most recent call last):
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\cmdline.py", line 247, in main
    app.build(force_all, filenames)
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\application.py", line 211, in build
    self.builder.build_update()
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\builders\__init__.py", line 211, in build_update
    'out of date' % len(to_build))
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\builders\__init__.py", line 267, in build
    self.write(docnames, list(updated_docnames), method)
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\builders\__init__.py", line 310, in write
    self._write_serial(sorted(docnames), warnings)
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\builders\__init__.py", line 323, in _write_serial
    self.write_doc(docname, doctree)
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\builders\html.py", line 438, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\builders\html.py", line 750, in handle_page
    output = self.templates.render(templatename, ctx)
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\jinja2glue.py", line 128, in render
    return self.environment.get_template(template).render(context)
  File "C:\Install\Python27\lib\site-packages\jinja2-2.7.1-py2.7.egg\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Install\Python27\lib\site-packages\jinja2-2.7.1-py2.7.egg\jinja2\environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\themes\basic\page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "C:\workspace\charm\pyplot\doc\source\_templates\layout.html", line 1, in top-level template code
    {% extends "!layout.html" %}
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\themes\sphinxdoc\layout.html", line 10, in top-level template code
    {%- extends "basic/layout.html" %}
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\themes\basic/layout.html", line 160, in top-level template code
    {%- block content %}
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\themes\basic/layout.html", line 161, in block "content"
    {%- block sidebar1 %} {# possible location for sidebar #} {% endblock %}
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\themes\sphinxdoc\layout.html", line 13, in block "sidebar1"
    {% block sidebar1 %}{{ sidebar() }}{% endblock %}
  File "C:\Install\Python27\lib\site-packages\jinja2-2.7.1-py2.7.egg\jinja2\sandbox.py", line 356, in call
    return __context.call(__obj, *args, **kwargs)
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\themes\basic/layout.html", line 62, in template
    {%- include sidebartemplate %}
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\themes\basic\globaltoc.html", line 11, in top-level template code
    {{ toctree() }}
  File "C:\Install\Python27\lib\site-packages\jinja2-2.7.1-py2.7.egg\jinja2\sandbox.py", line 356, in call
    return __context.call(__obj, *args, **kwargs)
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\builders\html.py", line 742, in <lambda>
    ctx['toctree'] = lambda **kw: self._get_local_toctree(pagename, **kw)
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\builders\html.py", line 678, in _get_local_toctree
    docname, self, collapse, **kwds))['fragment']
  File "C:\Install\Python27\lib\site-packages\sphinx-1.2b1-py2.7.egg\sphinx\environment.py", line 1046, in get_toctree_for
    result.extend(toctree.children)
AttributeError: 'NoneType' object has no attribute 'children'
===================================================================================
```

Then in order to move on in my project, I attempted a little patch (no resolution at all but at least I can terminate the HTML generation)

I added a **try block** just pass by the error as follows:

``` python
===================================================================================
...
    def get_toctree_for(self, docname, builder, collapse, **kwds):
        """Return the global TOC nodetree."""
        doctree = self.get_doctree(self.config.master_doc)
        toctrees = []
        if 'includehidden' not in kwds:
            kwds['includehidden'] = True
        if 'maxdepth' not in kwds:
            kwds['maxdepth'] = 0
        kwds['collapse'] = collapse
        for toctreenode in doctree.traverse(addnodes.toctree):
            toctree = self.resolve_toctree(docname, builder, toctreenode,
                                           prune=True, **kwds)
            toctrees.append(toctree)
        if not toctrees:
            return None
        result = toctrees[0]
        for toctree in toctrees[1:]:
            try:
                result.extend(toctree.children)
            except:
                pass
        return result
...
===================================================================================
```

I hope this would help you to understand what happened.

Best regards
Christian

**Comment by tk0miya** [comment]
Thank you for reporting.
This was fixed at #1157 (59d655c435e7ca1a5e48cbbf9809d2553cc71d5d).

Please use newest version. Thanks.
