### ISSUE TITLE
Bug in new C++ template parser

### ISSUE THREAD

**Issue by wjakob** [sphinx-doc/sphinx#2080]
Commit ed29c298a66df9e1293484b9f0dd60a25cac52fe added support for parsing C++ templates, including function templates. I tried using it but get an exception with this expression:

```
.. cpp:function:: template <typename T> arg_t<T> arg::operator=(const T &value)
```

Here is a traceback:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Sphinx-1.4a0.dev20151012-py3.4.egg/sphinx/cmdline.py", line 240, in main
    app.build(opts.force_all, filenames)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Sphinx-1.4a0.dev20151012-py3.4.egg/sphinx/application.py", line 265, in build
    self.builder.build_specific(filenames)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Sphinx-1.4a0.dev20151012-py3.4.egg/sphinx/builders/__init__.py", line 241, in build_specific
    'line' % len(to_write))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Sphinx-1.4a0.dev20151012-py3.4.egg/sphinx/builders/__init__.py", line 323, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Sphinx-1.4a0.dev20151012-py3.4.egg/sphinx/builders/__init__.py", line 361, in write
    self._write_serial(sorted(docnames), warnings)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Sphinx-1.4a0.dev20151012-py3.4.egg/sphinx/builders/__init__.py", line 367, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Sphinx-1.4a0.dev20151012-py3.4.egg/sphinx/environment.py", line 1291, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Sphinx-1.4a0.dev20151012-py3.4.egg/sphinx/environment.py", line 1546, in resolve_references
    typ, target, node, contnode)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Sphinx-1.4a0.dev20151012-py3.4.egg/sphinx/domains/cpp.py", line 3714, in resolve_xref
    node, contnode)[0]
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Sphinx-1.4a0.dev20151012-py3.4.egg/sphinx/domains/cpp.py", line 3703, in _resolve_xref_inner
    fullNestedName = s.get_full_nested_name()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Sphinx-1.4a0.dev20151012-py3.4.egg/sphinx/domains/cpp.py", line 2141, in get_full_nested_name
    for nne, templateParams in self.get_lookup_key():
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Sphinx-1.4a0.dev20151012-py3.4.egg/sphinx/domains/cpp.py", line 2127, in get_lookup_key
    assert s.identifier
AssertionError
```

**Comment by jakobandersen** [comment]
Thanks for the report. It should be the same problem as described in #2058.

**Comment by wjakob** [comment]
(I confirm that it was the same problem, it works now after applying 4e8f630)
