### ISSUE TITLE
SphinxContrib Youtube cannot use it

### ISSUE THREAD

**Issue by rlkee888** [sphinx-doc/sphinx#2107]
Hi,

Having trouble using the extension from https://bitbucket.org/birkenfeld/sphinx-contrib. The error I get when I try to make html is.
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 4 source files that are out of date
updating environment: 4 added, 0 changed, 0 removed
reading sources... [100%] troubleshooting
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 75%] introduction
Exception occurred:
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\s
phinxcontrib_youtube-1.0.dev20151105-py3.5.egg\sphinxcontrib\youtube.py", line 2
2, in css
    return "; ".join(sorted("%s: %s" % kv for kv in d.iteritems()))
AttributeError: 'dict' object has no attribute 'iteritems'
The full traceback has been saved in C:\Users\User\AppData\Local\Temp\sphinx-err
-zu2hkxyq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message c
an be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphin
x/issues>. Thanks!

the error log contains the following....

Sphinx version: 1.3.1
Python version: 3.5.0 (CPython)
Docutils version: 0.12 release
Jinja2 version: 2.8
Last messages:
none found
pickling environment...
done
checking consistency...
done
preparing documents...
done
writing output... [ 25%] index
writing output... [ 50%] installation
writing output... [ 75%] introduction
Loaded extensions:
   sphinx.ext.todo (1.3.1) from C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx\ext\todo.py
sphinxcontrib.youtube (unknown version) from C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinxcontrib_youtube-1.0.dev20151105-py3.5.egg\sphinxcontrib\youtube.py
sphinx.ext.pngmath (1.3.1) from C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx\ext\pngmath.py
sphinx.ext.autodoc (1.3.1) from C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx\ext\autodoc.py
alabaster (0.7.6) from C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\alabaster__init__.py
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx\cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx\application.py", line 264, in build
    self.builder.build_update()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx\builders__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx\builders__init__.py", line 316, in build
    self.write(docnames, list(updated_docnames), method)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx\builders__init__.py", line 354, in write
    self._write_serial(sorted(docnames), warnings)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx\builders__init__.py", line 362, in _write_serial
    self.write_doc(docname, doctree)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx\builders\html.py", line 439, in write_doc
    self.docwriter.write(doctree, destination)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\docutils\writers__init__.py", line 80, in write
    self.translate()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinx\writers\html.py", line 53, in translate
    self.document.walkabout(visitor)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\docutils\nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\docutils\nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinxcontrib_youtube-1.0.dev20151105-py3.5.egg\sphinxcontrib\youtube.py", line 71, in visit_youtube_node
    "style": css(style),
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\sphinxcontrib_youtube-1.0.dev20151105-py3.5.egg\sphinxcontrib\youtube.py", line 22, in css
    return "; ".join(sorted("%s: %s" % kv for kv in d.iteritems()))
AttributeError: 'dict' object has no attribute 'iteritems'

Thank you

**Comment by shimizukawa** [comment]
@rlkee888 Please contact to author.
https://pypi.python.org/pypi/sphinxcontrib.youtube

**Comment by shimizukawa** [comment]
It seems that https://github.com/shomah4a/sphinxcontrib.youtube is newer than bitbucket's one.

**Comment by rlkee888** [comment]
@shimizukawa thank you for the links, I tried it briefly and I am not getting any more errors. Sadly I am also getting nothing from the youtube part as well, honestly I need to spend more time on it.

I will update this post once I get it working...

**Comment by tk0miya** [comment]
Now this issue is obsoleted I think (In addition, this is not a issue of sphinx).
Now, I close it. If you still have any problem, please reopen again.

Thanks.
