### ISSUE TITLE
Doc for Ansible stable fails.

### ISSUE THREAD

**Issue by safiyat** [sphinx-doc/sphinx#2119]
I was looking for the docs of [Ansible](http://ansible.com/) but couldn't find them on [readthedocs](https://readthedocs.org/projects/ansible/).
Upon digging further, I saw that many many builds prior to this have failed. Look [here](https://readthedocs.org/projects/ansible/builds/).

I tried to build again and the error I encountered was:
`IOError: [Errno 2] No such file or directory: u'/home/docs/checkouts/readthedocs.org/user_builds/ansible/checkouts/stable/docsite/_build/doctrees-readthedocs/index.doctree'`

The full traceback was:

```
writing output... [  1%] README

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 316, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 354, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 362, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 445, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 786, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/jinja2glue.py", line 138, in render
    return self.environment.get_template(template).render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/layout.html", line 1, in top-level template code
    {% extends "!layout.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/checkouts/stable/docsite/_themes/srtd/layout.html", line 158, in top-level template code
    {% set toctree = toctree(maxdepth=2, collapse=False) %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/jinja2/sandbox.py", line 355, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 776, in <lambda>
    ctx['toctree'] = lambda **kw: self._get_local_toctree(pagename, **kw)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 712, in _get_local_toctree
    docname, self, collapse, **kwds))['fragment']
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/environment.py", line 1238, in get_toctree_for
    doctree = self.get_doctree(self.config.master_doc)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/environment.py", line 1272, in get_doctree
    f = open(doctree_filename, 'rb')
IOError: [Errno 2] No such file or directory: u'/home/docs/checkouts/readthedocs.org/user_builds/ansible/checkouts/stable/docsite/_build/doctrees-readthedocs/index.doctree'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/ansible/envs/stable/local/lib/python2.7/site-packages/sphinx/environment.py", line 1272, in get_doctree
    f = open(doctree_filename, 'rb')
```

I am not sure if this is an error of sphinx or of the servers there.
Please take a look.

**Comment by shimizukawa** [comment]
https://readthedocs.org/projects/ansible/builds/3486695/ indicates that 

```
WARNING: master file /home/docs/checkouts/readthedocs.org/user_builds/ansible/checkouts/stable/docsite/index.rst not found
```

I guess that `index.rst` is specified as a master_doc in `conf.py`, nevertheless index.rst is not exist.
It's a cause of this problem.
@safiyat please report this to ansible development theam to fix the problem. Thanks.

**Comment by safiyat** [comment]
I checked and found that `index.rst` is in fact [there](https://github.com/ansible/ansible/blob/devel/docsite/rst/index.rst).
Is it a problem with the file layout in the repo or can it be fixed via sphinx itself?
Am sorry, I don't much experience with neither sphinx nor ansible.

**Comment by mitsuhiko** [comment]
Closing this here as this has nothing to do with Sphinx. That's a misconfiguration somewhere.
