### ISSUE TITLE
UnicodeDecodeError when using include directive in non-ascii path

### ISSUE THREAD

**Issue by freidrichen** [sphinx-doc/sphinx#2124]
When using the include-directive I get an error if the root directory has a non-ascii path.

This was reproducable with a very small project containing only a conf.py generated by sphinx-quickstart, index.rst, and one extra rst file which is included by index.rst like so:

``` rst
.. include:: include.rst
```

This project builds successfully if the root directory is an ascii-only path. But if the the root directory path contains non-ascii characters I get the error message:

```
Encoding error:
'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-5UtnRS.log, if you want to report the issue to the developers.
```

Contents of log file:

```
# Sphinx version: 1.2.3
# Python version: 2.7.9
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Loaded extensions:
#   sphinx.ext.oldcmarkup from /usr/lib/python2.7/dist-packages/sphinx/ext/oldcmarkup.pyc
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 220, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 234, in build
    purple, length):
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 134, in status_iterator
    for item in iterable:
  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 478, in update_generator
    self.read_doc(docname, app=app)
  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 633, in read_doc
    self.process_dependencies(docname, doctree)
  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 772, in process_dependencies
    path.normpath(path.join(cwd, dep)))
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
```

**Comment by shimizukawa** [comment]
Thanks for reporting. This issue was fixed on #1512.
Please use Sphinx-1.3 or later.
