### ISSUE TITLE
Reporter instance has no attribute 'get_source_and_line'

### ISSUE THREAD

**Issue by benoit9126** [sphinx-doc/sphinx#2139]
Hi,

I try to generate a html documentation for one of my project. It works fine on my Windows but on my Linux, I have the following error:

```
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 154, in __getattr__
    return getattr(self.reporter, name)
AttributeError: Reporter instance has no attribute 'get_source_and_line'
The full traceback has been saved in /tmp/sphinx-err-OXZgjw.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

Here is the related log:

```
# Sphinx version: 1.3.1
# Python version: 2.7.6 (CPython)
# Docutils version: 0.8 snapshot 2010-09-01, r6395
# Jinja2 version: 2.8
# Last messages:
#   Running Sphinx v1.3.1
#   loading translations [en]...
#   done
#   loading pickled environment...
#   not yet created
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 3 source files that are out of date
#   updating environment:
#   3 added, 0 changed, 0 removed
#   reading sources... [ 33%] basic_asset_replacement_problem
# Loaded extensions:
#   sphinx.ext.autodoc (1.3.1) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.doctest (1.3.1) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/doctest.pyc
#   sphinx.ext.mathjax (1.3.1) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/mathjax.pyc
#   sphinx.ext.viewcode (1.3.1) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/viewcode.pyc
#   sphinx.ext.coverage (1.3.1) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/coverage.pyc
#   alabaster (0.7.6) from /usr/local/lib/python2.7/dist-packages/alabaster/__init__.pyc
#   sphinxcontrib.napoleon (unknown version) from /usr/share/pycharm/helpers/sphinxcontrib/napoleon/__init__.py
#   sphinx.ext.todo (1.3.1) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/todo.pyc
#   sphinx.ext.ifconfig (1.3.1) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/ifconfig.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 259, in build
    self.doctreedir, self.app))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 618, in update
    self._read_serial(docnames, app)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 638, in _read_serial
    self.read_doc(docname, app)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 791, in read_doc
    pub.publish()
  File "/usr/share/pycharm/helpers/docutils/core.py", line 203, in publish
    self.settings)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 126, in read
    self.parse()
  File "/usr/share/pycharm/helpers/docutils/readers/__init__.py", line 75, in parse
    self.parser.parse(self.input, document)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/__init__.py", line 157, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/usr/share/pycharm/helpers/docutils/statemachine.py", line 233, in run
    context, state, transitions)
  File "/usr/share/pycharm/helpers/docutils/statemachine.py", line 454, in check_line
    return method(match, context, next_state)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 2706, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 329, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 398, in new_subsection
    node=section_node, match_titles=1)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 284, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/share/pycharm/helpers/docutils/statemachine.py", line 233, in run
    context, state, transitions)
  File "/usr/share/pycharm/helpers/docutils/statemachine.py", line 454, in check_line
    return method(match, context, next_state)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 2706, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 329, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 398, in new_subsection
    node=section_node, match_titles=1)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 284, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/share/pycharm/helpers/docutils/statemachine.py", line 233, in run
    context, state, transitions)
  File "/usr/share/pycharm/helpers/docutils/statemachine.py", line 454, in check_line
    return method(match, context, next_state)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 2281, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 2293, in explicit_construct
    return method(self, expmatch)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 2035, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 2086, in run_directive
    result = directive_instance.run()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 1488, in run
    nested_parse_with_titles(self.state, self.result, node)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/util/nodes.py", line 165, in nested_parse_with_titles
    return state.nested_parse(content, 0, node, match_titles=1)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 284, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/share/pycharm/helpers/docutils/statemachine.py", line 233, in run
    context, state, transitions)
  File "/usr/share/pycharm/helpers/docutils/statemachine.py", line 454, in check_line
    return method(match, context, next_state)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 2283, in explicit_markup
    self.explicit_list(blank_finish)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 2314, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 321, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/share/pycharm/helpers/docutils/statemachine.py", line 233, in run
    context, state, transitions)
  File "/usr/share/pycharm/helpers/docutils/statemachine.py", line 454, in check_line
    return method(match, context, next_state)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 2587, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 2293, in explicit_construct
    return method(self, expmatch)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 2035, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 2086, in run_directive
    result = directive_instance.run()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/domains/__init__.py", line 197, in run
    return BaseDirective.run(self)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/directives/__init__.py", line 156, in run
    self.state.nested_parse(self.content, self.content_offset, contentnode)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 284, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/share/pycharm/helpers/docutils/statemachine.py", line 233, in run
    context, state, transitions)
  File "/usr/share/pycharm/helpers/docutils/statemachine.py", line 454, in check_line
    return method(match, context, next_state)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 2643, in blank
    context, self.state_machine.abs_line_number() - 1)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 421, in paragraph
    textnodes, messages = self.inline_text(text, lineno)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 430, in inline_text
    return self.inliner.parse(text, lineno, self.memo, self.parent)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 516, in parse
    lineno)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 774, in interpreted_or_phrase_ref
    lineno)
  File "/usr/share/pycharm/helpers/docutils/parsers/rst/states.py", line 830, in interpreted
    nodes, messages2 = role_fn(role, rawsource, text, lineno, self)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/domains/__init__.py", line 179, in role_adapter
    inliner, options, content)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/roles.py", line 136, in __call__
    set_role_source_info(inliner, lineno, refnode)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/util/nodes.py", line 279, in set_role_source_info
    node.source, node.line = inliner.reporter.get_source_and_line(lineno)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 154, in __getattr__
    return getattr(self.reporter, name)
AttributeError: Reporter instance has no attribute 'get_source_and_line'
```

I do not really understand the cause of this error... Everything works fine on Windows...

Thanks.

**Comment by birkenfeld** [comment]
Docutils 0.8 is pretty ancient. Please update to at least 0.11, which is probably what you have installed on Windows :)

**Comment by benoit9126** [comment]
Thanks for the help. My IDE (Pycharm) kept an old version of `docutils` in the folder `/usr/share/pycharm/helpers/docutils`. I deleted this folder and now, the version installed by `pip` (0.12) is used by default.
