### ISSUE TITLE
sphinx/search/non-minified-js/*js not included in pypi tarball of version 1.3.2

### ISSUE THREAD

**Issue by jlec** [sphinx-doc/sphinx#2142]
test fail with

``` python
======================================================================
ERROR: test_i18n.test_i18n
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/pypy/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/sphinx-1.3.2/work/Sphinx-1.3.2-pypy/tests/util.py", line 228, in deco
    func(app, status, warning, *args2, **kwargs2)
  File "/var/tmp/portage/dev-python/sphinx-1.3.2/work/Sphinx-1.3.2-pypy/tests/test_i18n.py", line 17, in test_i18n
    app.builder.build_all()
  File "/var/tmp/portage/dev-python/sphinx-1.3.2/work/Sphinx-1.3.2-pypy/lib/sphinx/builders/__init__.py", line 212, in build_all
    self.build(None, summary='all source files', method='all')
  File "/var/tmp/portage/dev-python/sphinx-1.3.2/work/Sphinx-1.3.2-pypy/lib/sphinx/builders/__init__.py", line 326, in build
    self.finish()
  File "/var/tmp/portage/dev-python/sphinx-1.3.2/work/Sphinx-1.3.2-pypy/lib/sphinx/builders/html.py", line 459, in finish
    self.finish_tasks.add_task(self.copy_static_files)
  File "/var/tmp/portage/dev-python/sphinx-1.3.2/work/Sphinx-1.3.2-pypy/lib/sphinx/util/parallel.py", line 39, in add_task
    res = task_func()
  File "/var/tmp/portage/dev-python/sphinx-1.3.2/work/Sphinx-1.3.2-pypy/lib/sphinx/builders/html.py", line 591, in copy_static_files
    copyfile(jsfile, path.join(self.outdir, '_static', '_stemmer.js'))
  File "/var/tmp/portage/dev-python/sphinx-1.3.2/work/Sphinx-1.3.2-pypy/lib/sphinx/util/osutil.py", line 140, in copyfile
    shutil.copyfile(source, dest)
  File "/usr/lib64/pypy/lib-python/2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/var/tmp/portage/dev-python/sphinx-1.3.2/work/Sphinx-1.3.2-pypy/lib/sphinx/search/non-minified-js/german-stemmer.js'

----------------------------------------------------------------------
```

Please include the missing files

**Comment by shimizukawa** [comment]
Oh.. I'll fix soon.

**Comment by shimizukawa** [comment]
#2114 should be included to stable branch too.

**Comment by bersace** [comment]
Hi, I confirm this bug on 1.3.2 with `french-stemmer.js`.

```
Exception occurred:
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/nova/.virtualenvs/envs/rh2/local/lib/pyth
on2.7/site-packages/sphinx/search/non-minified-js/french-stemmer.js'
The full traceback has been saved in /tmp/sphinx-err-_CsJ8c.log, if you want to report the iss
ue to the developers.
```

**Comment by shimizukawa** [comment]
@bersace thanks for reporting. Let me clarify, it was happen on UnitTest as @jlec ? or on building html output?

**Comment by jlec** [comment]
@shimizukawa That was during unittesting.

**Comment by bersace** [comment]
I hit it on building HTML doc for our project.

**Comment by shimizukawa** [comment]
@bersace @jlec Thanks. I'll release fixed version in next few days.

**Comment by shimizukawa** [comment]
1.3.3 has been released.

**Comment by bersace** [comment]
I confirm. Thanks !! :-)
