### ISSUE TITLE
codec can't decode byte 0xe6 in position 109

### ISSUE THREAD

**Issue by linlinlinlin** [sphinx-doc/sphinx#2149]
```
# Sphinx version: 1.3.2
# Python version: 2.7.6 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   reading sources... [ 50%] log
# Loaded extensions:
#   sphinx.ext.autodoc (1.3.2) from /home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx (1.3.2) from /home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
#   sphinx.ext.doctest (1.3.2) from /home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinx/ext/doctest.pyc
#   alabaster (0.7.6) from /home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   runcode (unknown version) from /home/vagrant/web/doc/../doc/runcode.pyc
#   sphinxcontrib.httpdomain (unknown version) from /home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinxcontrib/httpdomain.pyc
Traceback (most recent call last):
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 240, in main
    app.build(opts.force_all, filenames)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinx/application.py", line 266, in build
    self.builder.build_update()
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 252, in build_update
    'out of date' % len(to_build))
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 266, in build
    self.doctreedir, self.app))
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinx/environment.py", line 618, in update
    self._read_serial(docnames, app)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinx/environment.py", line 638, in _read_serial
    self.read_doc(docname, app)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinx/environment.py", line 791, in read_doc
    pub.publish()
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinx/environment.py", line 128, in read
    self.parse()
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2301, in explicit_markup
    self.explicit_list(blank_finish)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2331, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2604, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinx/domains/__init__.py", line 197, in run
    return BaseDirective.run(self)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinx/directives/__init__.py", line 156, in run
    self.state.nested_parse(self.content, self.content_offset, contentnode)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/home/vagrant/web/doc/../doc/runcode.py", line 20, in run
    return CodeBlock.run(self)
  File "/home/vagrant/.local/share/virtualenvs/test/local/lib/python2.7/site-packages/sphinx/directives/code.py", line 100, in run
    code = u'\n'.join(self.content)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 109: ordinal not in range(128)
```

**Comment by shimizukawa** [comment]
```
  File "/home/vagrant/web/doc/../doc/runcode.py", line 20, in run
    return CodeBlock.run(self)
```

I guess it's a `runcode.py` issue.

**Comment by linlinlinlin** [comment]
Sorry, I will check it again.

But runcode.py:20 is  `CodeBlock.run()` .
And CodeBlock is from `sphinx.directives` .

**Comment by shimizukawa** [comment]
@linlinlinlin what is `runcode.py`? please let me know its source code.

**Comment by linlinlinlin** [comment]
I'm not sure what happened. But it didn't happening again.

**Comment by shimizukawa** [comment]
OK.
