### ISSUE TITLE
autogen aborts

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#217]
I am using a easy_installed zip from yesterday's bitbucket tip.

```
#!python

sphinx-autogen -o generated/ gluon_autosummary.rst 
/usr/local/lib/python2.6/dist-packages/Jinja2-2.1.1-py2.6-linux-i686.egg/jinja2/sandbox.py:35: DeprecationWarning: the sets module is deprecated
  from sets import Set, ImmutableSet
[autosummary] generating autosummary for: gluon_autosummary.rst
[autosummary] writing to generated/
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-autogen", line 8, in <module>
    load_entry_point('Sphinx==1.0dev-20090709', 'console_scripts', 'sphinx-autogen')()
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0dev_20090709-py2.6.egg/sphinx/ext/autosummary/generate.py", line 53, in main
    template_dir=options.templates)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0dev_20090709-py2.6.egg/sphinx/ext/autosummary/generate.py", line 152, in generate_autosummary_docs
    get_members(obj, 'function')
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0dev_20090709-py2.6.egg/sphinx/ext/autosummary/generate.py", line 141, in get_members
    if get_documenter(getattr(obj, name)).objtype == typ
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0dev_20090709-py2.6.egg/sphinx/ext/autosummary/__init__.py", line 146, in get_documenter
    if issubclass(obj, Exception):
TypeError: issubclass() arg 1 must be a class
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/217
- Originally reported by: [timmie](https://bitbucket.org/timmie)
- Originally created at: 2009-07-09T23:44:53.986

**Comment by shimizukawa** [comment]
_From [timmie](https://bitbucket.org/timmie) on 2009-07-09 21:50:03+00:00_

using True for autosummary in config.py

{{{
#!python

Exception occurred:
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0dev_20090709-py2.6.egg/sphinx/ext/autosummary/**init**.py", line 146, in get_documenter
    if issubclass(obj, Exception):
TypeError: issubclass() arg 1 must be a class

}}}

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-08-14 11:16:23+00:00_

Can you try to find out what kind of object {{{obj}}} is? It must be a bit of a strange thing, since the issubclass() check is guarded by {{{inspect.isclass()}}}.

**Comment by shimizukawa** [comment]
_From [timmie](https://bitbucket.org/timmie) on 2009-09-03 21:08:33+00:00_

Sorry I was reporting a diiferent issue.

**Comment by shimizukawa** [comment]
_From [timmie](https://bitbucket.org/timmie) on 2009-09-03 23:26:55+00:00_

the attached file produces this error.

Thanks for loking into this.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-11-08 22:17:28+00:00_

I can't reproduce the traceback with just that file; I'll need more info...

**Comment by shimizukawa** [comment]
_From Anonymous on 2010-08-11 10:06:02+00:00_

**Bump!**

**Comment by shimizukawa** [comment]
_From Anonymous on 2010-08-11 10:06:25+00:00_

The bug is in inspect.isclass(), it returns True if method has **getattr** defined. And next issubclass fails if it is passed an object.
simple fix is change inspect.isclass to isinstance(obj, (types.ClassType, type))
