### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print' , while making the sklearn doc

### ISSUE THREAD

**Issue by sandhan26** [sphinx-doc/sphinx#2187]
i have attached the log and snapshot of the problem below.

![untitled](https://cloud.githubusercontent.com/assets/5576333/11916495/5d40f584-a6ff-11e5-9ba6-be9817599c6b.png)
## error log
# Sphinx version: 1.3.3
# Python version: 3.4.3+ (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
# Loaded extensions:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sphinx/cmdline.py", line 239, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/local/lib/python3.4/dist-packages/sphinx/application.py", line 144, in **init**
    self.setup_extension(extension)
  File "/usr/local/lib/python3.4/dist-packages/sphinx/application.py", line 431, in setup_extension
    mod = **import**(extension, None, None, ['setup'])
  File "/home/sandhan/sklearn_tutorial/doc/sphinxext/gen_rst.py", line 194
    print 80 \* '_'
           ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by tk0miya** [comment]
It seems the errors caused by `sphinxext/gen_rst.py`. It is not a part of Sphinx.
Maybe, it is written by sklearn_tutorial team.
Please let them know about the error.
