### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by tritemio** [sphinx-doc/sphinx#2193]
When building the documentation for phconvert (using [this commands](https://github.com/Photon-HDF5/phconvert/blob/master/docs/Build%20docs.ipynb)) I get this error:

```
writing output... [100%] loader                                                 
generating indices... genindex py-modindex
highlighting module code... [100%] phconvert.loader                             
writing additional pages... search
copying static files... 
Exception occurred:
  File "/Users/anto/miniconda3/lib/python3.5/shutil.py", line 98, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/Users/anto/src/phconvert/docs/_static/ajax-loader.gif' and '/Users/anto/src/phconvert/docs/_static/ajax-loader.gif' are the same file
The full traceback has been saved in /var/folders/fy/f2vfpth16ys0j7sbslk2lx300000gn/T/sphinx-err-21vew181.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

And here the full log:

```
# Sphinx version: 1.3.1
# Python version: 3.5.1 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   genindex
#   py-modindex
#   
#   highlighting module code... [ 50%] phconvert.hdf5
#   highlighting module code... [100%] phconvert.loader
#   
#   writing additional pages...
#   search
#   
#   copying static files...
# Loaded extensions:
#   sphinx.ext.viewcode (1.3.1) from /Users/anto/miniconda3/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/ext/viewcode.py
#   sphinx.ext.intersphinx (1.3.1) from /Users/anto/miniconda3/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/ext/intersphinx.py
#   sphinx.ext.autodoc (1.3.1) from /Users/anto/miniconda3/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/ext/autodoc.py
#   sphinx.ext.napoleon (1.3.1) from /Users/anto/miniconda3/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/ext/napoleon/__init__.py
#   alabaster (0.7.6) from /Users/anto/miniconda3/lib/python3.5/site-packages/alabaster/__init__.py
Traceback (most recent call last):
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/builders/__init__.py", line 319, in build
    self.finish()
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/builders/html.py", line 459, in finish
    self.finish_tasks.add_task(self.copy_static_files)
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/util/parallel.py", line 39, in add_task
    res = task_func()
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/builders/html.py", line 609, in copy_static_files
    ctx, exclude_matchers=matchers)
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/util/__init__.py", line 181, in copy_static_entry
    exclude_matchers=exclude_matchers)
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/util/__init__.py", line 169, in copy_static_entry
    copyfile(source, target)
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/util/osutil.py", line 140, in copyfile
    shutil.copyfile(source, dest)
  File "/Users/anto/miniconda3/lib/python3.5/shutil.py", line 98, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/Users/anto/src/phconvert/docs/_static/ajax-loader.gif' and '/Users/anto/src/phconvert/docs/_static/ajax-loader.gif' are the same file
```

**Comment by tk0miya** [comment]
Could you check variables `$DOCS_DIR` and `$HTML_DIR`?
If both are empty, you'll get the error.

**Comment by tritemio** [comment]
@tk0miya, you are right. I run the command from a Jupyter notebook and, for some reason, the variables are not passed anymore to the shell (they are empty).

This is not an issue with sphinx at all. However, maybe detecting that not enough parameters are passed and printing a relevant message could be useful.

**Comment by tk0miya** [comment]
OK, I understand. I'll handle it and show any messages.

**Comment by tk0miya** [comment]
Fixed at 9c2704b.

Thank you for reporting!

**Comment by tritemio** [comment]
@tk0miya, thanks for adding the error message.

For the record, the error was due to a bug in ipython 4.0.0 that was fixed in 4.0.1. I cannot find a specific issue number, but upgrading fixed the bug.

**Comment by kyrias** [comment]
Any chance that you could add a flag to allow the source and destination directory to be the same? There are a few projects that do it that way for simplicity, when the manpages are generated with sphinx.

**Comment by tk0miya** [comment]
I think Sphinx is designed on "source and destination directories are different" ideas.
Until this issue has been fixed, it has not been checked but it was unexpected behavior.
So, IMO, it is not good idea giving new option to support that situation. Because it would need many fixes to do that.
In addition, it makes the source directory messy if Sphinx generates images or style files (ex. graphviz, inheritance_diagram and so on). 

If you want to discuss more, please open new issue.
This is already closed issue. Not good for discuss.
