### ISSUE TITLE
`Text` object has no attribute `get` error.

### ISSUE THREAD

**Issue by skorokithakis** [sphinx-doc/sphinx#2220]
When trying to compile a document with references, I get the following error:

```
# Sphinx version: 1.3.3
# Python version: 2.7.8 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [ 16%] api
# Loaded extensions:
#   sphinxcontrib.httpdomain (unknown version) from .virtualenvs/generic/local/lib/python2.7/site-packages/sphinxcontrib/httpdomain.pyc
#   alabaster (0.7.7) from .virtualenvs/generic/local/lib/python2.7/site-packages/alabaster/__init__.pyc
Traceback (most recent call last):
  File ".virtualenvs/generic/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 240, in main
    app.build(opts.force_all, filenames)
  File ".virtualenvs/generic/local/lib/python2.7/site-packages/sphinx/application.py", line 266, in build
    self.builder.build_update()
  File ".virtualenvs/generic/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 252, in build_update
    'out of date' % len(to_build))
  File ".virtualenvs/generic/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 323, in build
    self.write(docnames, list(updated_docnames), method)
  File ".virtualenvs/generic/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 361, in write
    self._write_serial(sorted(docnames), warnings)
  File ".virtualenvs/generic/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 367, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File ".virtualenvs/generic/local/lib/python2.7/site-packages/sphinx/environment.py", line 1291, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File ".virtualenvs/generic/local/lib/python2.7/site-packages/sphinx/environment.py", line 1549, in resolve_references
    newnode = self._resolve_any_reference(builder, node, contnode)
  File ".virtualenvs/generic/local/lib/python2.7/site-packages/sphinx/environment.py", line 1672, in _resolve_any_reference
    if newnode and newnode[0].get('classes'):
AttributeError: 'Text' object has no attribute 'get'
```

It seems to be that the reference couldn't be resolved, but the error is rather hostile.

**Comment by tk0miya** [comment]
It seems similar to #1601.
@shimizukawa Are these related?

**Comment by skorokithakis** [comment]
Hmm yes, they may be the same error, it depends on the exception there.

**Comment by shimizukawa** [comment]
Fixed it. Thanks for your reporting!
