### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

### ISSUE THREAD

**Issue by kukgini** [sphinx-doc/sphinx#2256]
I found an error. this change can fix the problem.

sphinx/locale/**init**.py:

```
 73     def __len__(self):
 74         return len(self.data)
 75
 76     def __str__(self):
 77         return unicode(self.data) <--- this line was originally: return str(self.data)
 78
 79     def __unicode__(self):
 80         return text_type(self.data) 
```

---

```
# Sphinx version: 1.3.3
# Python version: 2.7.0 (Jython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   /sproject/tools/ciserv/hudson/workspace/DEPLOY_DOC/src/man/ko/tax-docs/index.rst:1: WARNING: Title overline too short.

=================
전자세금계산서 설명서
=================
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  5%] gw-docs/PRO_000147
# Loaded extensions:
#   sphinx.ext.autodoc (1.3.3) from 
.../lib/sphinx/ext/autodoc$py.class
#   alabaster (0.7.6) from 
.../lib/alabaster/__init__$py.class
Traceback (most recent call last):
  File ".../lib/sphinx/cmdline.py", line 240, in main
    app.build(opts.force_all, filenames)
  File ".../lib/sphinx/application.py", line 266, in build
    self.builder.build_update()
  File ".../lib/sphinx/builders/__init__.py", line 250, in build_update
    self.build(to_build,
  File ".../lib/sphinx/builders/__init__.py", line 323, in build
    self.write(docnames, list(updated_docnames), method)
  File ".../lib/sphinx/builders/__init__.py", line 361, in write
    self._write_serial(sorted(docnames), warnings)
  File ".../lib/sphinx/builders/__init__.py", line 369, in _write_serial
    self.write_doc(docname, doctree)
  File ".../lib/sphinx/builders/html.py", line 439, in write_doc
    self.docwriter.write(doctree, destination)
  File ".../lib/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File ".../lib/sphinx/writers/html.py", line 53, in translate
    self.document.walkabout(visitor)
  File ".../lib/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File ".../lib/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File ".../lib/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File ".../lib/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File ".../lib/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File ".../lib/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File ".../lib/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File ".../lib/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File ".../lib/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File ".../lib/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File ".../lib/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File ".../lib/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File ".../lib/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File ".../lib/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File ".../lib/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File ".../lib/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File ".../lib/sphinx/writers/html.py", line 612, in visit_tip
    self.visit_admonition(node, 'tip')
  File ".../lib/sphinx/writers/html.py", line 241, in visit_admonition
    node.insert(0, nodes.title(name, admonitionlabels[name]))
  File ".../lib/docutils/nodes.py", line 1073, in __init__
    textnode = Text(text)
  File ".../lib/docutils/nodes.py", line 344, in __new__
    return reprunicode.__new__(cls, data)
  File ".../lib/sphinx/locale/__init__.py", line 77, in __str__
    return str(self.data)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

**Comment by shimizukawa** [comment]
Strange.... @kukgini please let me know a result of below code.
1. invoke your jython environment as python interactive shell.
2. type below code:

```
>>> from docutils.nodes import reprunicode
>>> reprunicode.__mro__
```

I expect above code represents this console output:

```
(<class 'docutils.nodes.reprunicode'>, <type 'unicode'>, <type 'basestring'>, <type 'object'>)
```

**Comment by kukgini** [comment]
result is same as what you expected :

```
(<class 'docutils.nodes.reprunicode'>, <type 'unicode'>, <type 'basestring'>, <type 'object'>)
```

**Comment by kukgini** [comment]
I published my environment on github.com. check this out : https://github.com/kukgini/bigglesworth.git
./build.sh will build src/ to target/

**Comment by tk0miya** [comment]
In my environment, It works fine.

```
$ java -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
$ ./build.sh
Running Sphinx v1.3.3
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 7 source files that are out of date
updating environment: 7 added, 0 changed, 0 removed
reading sources... [100%] part3/index
/Users/tkomiya/work/bigglesworth/src/part1/chap1.1.rst:66: ERROR: Document may not end with a transition.
/Users/tkomiya/work/bigglesworth/src/part1/chap1.1.rst:8: WARNING: image file not readable: static/images/sample.png
/Users/tkomiya/work/bigglesworth/src/part1/chap1.1.rst:40: WARNING: image file not readable: static/images/sample2.png
/Users/tkomiya/work/bigglesworth/src/part2/chap2.1.rst:66: ERROR: Document may not end with a transition.
/Users/tkomiya/work/bigglesworth/src/part2/chap2.1.rst:8: WARNING: image file not readable: static/images/sample.png
/Users/tkomiya/work/bigglesworth/src/part2/chap2.1.rst:40: WARNING: image file not readable: static/images/sample2.png
/Users/tkomiya/work/bigglesworth/src/part2/index.rst:None: WARNING: duplicate label 기록물 보관 1, other instance in /Users/tkomiya/work/bigglesworth/src/part1/index.rst
/Users/tkomiya/work/bigglesworth/src/part3/chap3.1.rst:66: ERROR: Document may not end with a transition.
/Users/tkomiya/work/bigglesworth/src/part3/chap3.1.rst:8: WARNING: image file not readable: static/images/sample.png
/Users/tkomiya/work/bigglesworth/src/part3/chap3.1.rst:40: WARNING: image file not readable: static/images/sample2.png
/Users/tkomiya/work/bigglesworth/src/part3/index.rst:None: WARNING: duplicate label 기록물 보관 1, other instance in /Users/tkomiya/work/bigglesworth/src/part2/index.rst
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] part3/index
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 11 warnings.
```

**Comment by kukgini** [comment]
sorry for confusing. it is only the engine part of my document generator.
some kind of src contents (src/*.rst) can raise error. 
I can't share the contents because it's come from my customer who don't want to publish it.

**Comment by shimizukawa** [comment]
If you have a chance, please provide smallest sphinx project to reproduce the issue.
In theory, when `reprunicode` class is delivered from `unicode` class, `__str__` method in `sphinx/locale/__init__.py, line 77` is never called.

**Comment by kukgini** [comment]
I made a smallest project. Can i send it to you by email?

**Comment by shimizukawa** [comment]
@kukgini sure! please send it to `shimizukawa @ gmail.com` OR upload somewhere (like Dropbox or, ...)

**Comment by kukgini** [comment]
I send it to you by email. :-)

**Comment by tk0miya** [comment]
@shimizukawa could you share the file please?

**Comment by kukgini** [comment]
@tk0miya could you share your e-mail address? then I will send it to you.

**Comment by tk0miya** [comment]
I received it from shimizukawa in this weekend.
Please wait a moment, I'll take a look.

**Comment by tk0miya** [comment]
Sorry for late response.
I reproduce this bug from shared project.

It might come from i18n of admonitions. I can reproduce the bug with giving a `-D language=ko` option to https://github.com/kukgini/bigglesworth.git .

Here is smallest example to reproduce the bug.

```
Hello World
===========

.. tip::

   Hello world
```

But I don't still get a reason of the bug. I will continue to the investigation.

Thanks,

**Comment by tk0miya** [comment]
Hmm, it might be a bug of jython. The subclass of `unicode` class calls `__str__()` method of its argument instead of `__unicode__()`.

```
$ java -jar lib/jython-standalone-2.7.0.jar
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_74
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append('/Users/tkomiya/work/tmp/bigglesworth/lib')
>>> sys.path.append('/Users/tkomiya/work/tmp/bigglesworth/lib/docutils')
>>> sys.path.append('/Users/tkomiya/work/tmp/bigglesworth/lib/sphinx')
>>> sys.path.append('/Users/tkomiya/work/tmp/bigglesworth/lib/six')
>>> from docutils import nodes
>>> import sphinx.locale
>>> sphinx.locale.init(['lib/sphinx/locale'], 'ko')
(<gettext.GNUTranslations instance at 0x2>, True)
>>> nodes.title('tip', sphinx.locale.admonitionlabels['tip'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tkomiya/work/tmp/bigglesworth/lib/docutils/nodes.py", line 1073, in __init__
    textnode = Text(text)
  File "/Users/tkomiya/work/tmp/bigglesworth/lib/docutils/nodes.py", line 344, in __new__
    return reprunicode.__new__(cls, data)
  File "/Users/tkomiya/work/tmp/bigglesworth/lib/sphinx/locale/__init__.py", line 77, in __str__
    return str(self.data)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
>>> nodes.reprunicode.__mro__
(<class 'docutils.nodes.reprunicode'>, <type 'unicode'>, <type 'basestring'>, <type 'object'>)
>>> nodes.reprunicode(sphinx.locale.admonitionlabels['tip'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tkomiya/work/tmp/bigglesworth/lib/sphinx/locale/__init__.py", line 77, in __str__
    return str(self.data)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
>>> unicode(sphinx.locale.admonitionlabels['tip'])
u'\ucc38\uace0'
>>> class myunicode(unicode):
...     pass
...
>>> myunicode(sphinx.locale.admonitionlabels['tip'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tkomiya/work/tmp/bigglesworth/lib/sphinx/locale/__init__.py", line 77, in __str__
    return str(self.data)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

Of course, cpython calls `__unicode__` and works fine.

```
$ python
Python 2.7.11 (default, Dec 23 2015, 08:51:26)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from docutils import nodes
>>> import sphinx.locale
>>> sphinx.locale.init(['lib/sphinx/locale'], 'ko')
(<gettext.GNUTranslations instance at 0x10e8683b0>, True)
>>> nodes.title('tip', sphinx.locale.admonitionlabels['tip'])
<title: <#text: '\ucc38\uace0'>>
>>> nodes.reprunicode(sphinx.locale.admonitionlabels['tip'])
'\ucc38\uace0'
```

@kukgini Could you report this to jython project?

**Comment by shimizukawa** [comment]
To reproduce the cause, I wrote a simple test script that independents from Sphinx and docutils.
test.py:

```
# -*- coding utf-8 -*-
from __future__ import print_function

import sys
from UserString import UserString


class myunicode(unicode):
    pass


class mynode(unicode):
    def __new__(cls, data):
        return unicode.__new__(cls, data)


class mystr(UserString):

    def __init__(self, data):
        self.data = data

    def __str__(self):
        return str(self.data)

    def __unicode__(self):
        return unicode(self.data)


def test(code):
    try:
        print(code, end=' -> ')
        exec(code)
        print('ok')
    except:
        print('ng')


print(sys.version)

test("mystr(u'\ucc38\uace0')")
test("unicode(u'\ucc38\uace0')")
test("myunicode(u'\ucc38\uace0')")
test("mynode(u'\ucc38\uace0')")
test("unicode(mystr(u'\ucc39\uace0'))")
test("myunicode(mystr(u'\ucc38\uace0'))")
test("mynode(mystr(u'\ucc38\uace0'))")
test("unicode.__new__(unicode, u'\ucc38\uace0')")
test("unicode.__new__(myunicode, u'\ucc38\uace0')")
test("unicode.__new__(mynode, u'\ucc38\uace0')")
test("unicode.__new__(unicode, mystr(u'\ucc38\uace0'))")
test("unicode.__new__(myunicode, mystr(u'\ucc38\uace0'))")
test("unicode.__new__(mynode, mystr(u'\ucc38\uace0'))")
```

Result with CPython:

```
$ python test.py
2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
mystr(u'\ucc38\uace0') -> ok
unicode(u'\ucc38\uace0') -> ok
myunicode(u'\ucc38\uace0') -> ok
mynode(u'\ucc38\uace0') -> ok
unicode(mystr(u'\ucc38\uace0')) -> ok
myunicode(mystr(u'\ucc38\uace0')) -> ok
mynode(mystr(u'\ucc38\uace0')) -> ok
unicode.__new__(unicode, u'\ucc38\uace0') -> ok
unicode.__new__(myunicode, u'\ucc38\uace0') -> ok
unicode.__new__(mynode, u'\ucc38\uace0') -> ok
unicode.__new__(unicode, mystr(u'\ucc38\uace0')) -> ok
unicode.__new__(myunicode, mystr(u'\ucc38\uace0')) -> ok
unicode.__new__(mynode, mystr(u'\ucc38\uace0')) -> ok
```

Result with Jython:

```
$ java -jar jython-standalone-2.7.0.jar sphinx-2256.py 
2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]
mystr(u'\ucc38\uace0') -> ok
unicode(u'\ucc38\uace0') -> ok
myunicode(u'\ucc38\uace0') -> ok
mynode(u'\ucc38\uace0') -> ok
unicode(mystr(u'\ucc38\uace0')) -> ok
myunicode(mystr(u'\ucc38\uace0')) -> ng
mynode(mystr(u'\ucc38\uace0')) -> ng
unicode.__new__(unicode, u'\ucc38\uace0') -> ok
unicode.__new__(myunicode, u'\ucc38\uace0') -> ok
unicode.__new__(mynode, u'\ucc38\uace0') -> ok
unicode.__new__(unicode, mystr(u'\ucc38\uace0')) -> ok
unicode.__new__(myunicode, mystr(u'\ucc38\uace0')) -> ng
unicode.__new__(mynode, mystr(u'\ucc38\uace0')) -> ng
```
