### ISSUE TITLE
Sphinx doesn't work if docs are in a non-ascii path

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#227]
On Windows, using Sphinx 0.6.2 (and the tip) with the docs sources residing in a path with non-ascii characters, will issue an error like this:

```
Sphinx error:
'ascii' codec can't decode byte 0xe4 in position 16: ordinal not in range(128)
```

This message is of not much help, but it should be easy to reproduce. I guess the message is also an error of the error handling, since the 'ascii' part will change to "utf-8' if I do the same in a console that supports utf-8 stdout/stderr.

This also brings me to the following thoughts:
1. Is it really useful to wrap exceptions inside SphinxError objects or similar and truncate their output? It would be much easier to nail down problems, if I could immediately see the whole traceback.

For example this error message was completely misleading and it took me some time to figure out, what is the real cause, since I first assumed it must be a unicode problem inside one of the doc files. The dumping of the traceback to a log file, as it happens in some other situations, is also very inconvenient for me.

The biggest part of the intended audience have programming knowledge in Python. So my suggestion would be to at least include a command line option, to simply let the code raise the real exceptions with full traceback.
1. Many programs/modules have problems with non-ascii pathes. Much more then I would ever would have guessed. Even Eclipse turns out to be buggy if the project resides in a non-ascii path (although one can workaround this). To make sure my projects don't suffer from the same flaws, I'm using a non-ascii username on my system and non-ascii project pathes. It is just too easy to overlook these unicode issues if I don't actually force myself to deal with unicode everywhere I could.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/227
- Originally reported by: [bitmonster](https://bitbucket.org/bitmonster)
- Originally created at: 2009-07-17T18:37:51.848

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-08-06 20:31:09+00:00_

Ad 1.: The truncation without any traceback info only happens for "Sphinx errors", which I consider user errors. Of course, here we may have a bug in the decision-making :) For unexpected exceptions, you normally only get one stack-frame, but a file with the whole traceback (and version info) is saved.

There is also always the -P option which not only gives you the full traceback but also a Pdb prompt in order to investigate.

Ad 2.: yes, this should work. However, in this instance the error is in docutils, not in Sphinx, as it occurs in the "include" directive. I had a similar error in the Sphinx-specific "literalinclude" directive, which is now fixed in <<cset ea5b0088fadd79584846242769ac8b7d2d264690>>.

**Comment by shimizukawa** [comment]
_From [bitmonster](https://bitbucket.org/bitmonster) on 2009-08-06 23:53:29+00:00_

Thanks, for the reply. The -P option is the one I need. :)

Ok, now I'm not sure, if I have understood your reply right. So this bug should be fixed?

On a document with a "include" directive, I get this error:
{{{
Running Sphinx v1.0
building [htmlhelp]: targets for 36 source files that are out of date
updating environment: 36 added, 0 changed, 0 removed
reading sources... [  2%] changelog
Exception occurred while building, starting debugger:
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\cmdline.py", line 172, in main
    app.build(all_files, filenames)
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\application.py", line 130, in build
    self.builder.build_update()
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\builders__init__.py", line 265, in build_update
    'out of date' % len(to_build))
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\builders__init__.py", line 285, in build
    purple, length):
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\builders__init__.py", line 131, in status_iterator
    for item in iterable:
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\environment.py", line 518, in update_generator
    self.read_doc(docname, app=app)
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\environment.py", line 612, in read_doc
    raise SphinxError(str(err))
SphinxError: 'utf8' codec can't decode bytes in position 16-18: invalid data

> c:\python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\environment.py(612)read_doc()
> }}}

On  another document without "include", I get this:
{{{
Running Sphinx v1.0
building [htmlhelp]: targets for 36 source files that are out of date
updating environment: 36 added, 0 changed, 0 removed
reading sources... [ 13%] controlling_your_living_room_with_eventghost/index
Exception occurred while building, starting debugger:
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\cmdline.py", line 172, in main
    app.build(all_files, filenames)
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\application.py", line 130, in build
    self.builder.build_update()
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\builders__init__.py", line 265, in build_update
    'out of date' % len(to_build))
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\builders__init__.py", line 285, in build
    purple, length):
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\builders__init__.py", line 131, in status_iterator
    for item in iterable:
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\environment.py", line 518, in update_generator
    self.read_doc(docname, app=app)
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\environment.py", line 615, in read_doc
    self.process_images(docname, doctree)
  File "C:\Python26\lib\site-packages\sphinx-1.0dev_20090807-py2.6.egg\sphinx\environment.py", line 756, in process_images
    if not os.access(path.join(self.srcdir, imgpath), os.R_OK):
  File "C:\Python26\lib\ntpath.py", line 108, in join
    path += "\" + b
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 16-18: invalid data

> c:\python26\lib\ntpath.py(108)join()
> -> path += "\" + b
> }}}
> This seems to be a problem with the "image" directive this time.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-08-14 10:56:30+00:00_

As said, `include` is docutils territory, please report this to the docutils team.

The image handling however is in Sphinx, so I'll have to fix this as well. Thanks for persisting :)

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-01-31 15:27:41+00:00_

Issue #330 was marked as a duplicate of this issue.

**Comment by shimizukawa** [comment]
_From [jhackel](https://bitbucket.org/jhackel) on 2010-04-21 10:37:22+00:00_

It seems that when an role extension ('term' in my case) issues a warning ('term not in glossary' in my case) also a decode error occurs if the filename contains non-ascii characters. This time at sphinx/application.py, function warn() (line 145 in Sphinx 0.6.5), which is called for instance from sphinx/environment.py, resolve_references(), line 1266.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-08-26 12:05:03+00:00_

Should be fixed in 1.0.3.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-09-22 10:14:45+00:00_

Removing milestone: 1.0 (automated comment)

**Comment by shimizukawa** [comment]
_From Anonymous on 2012-01-19 19:32:19+00:00_

Hi, I'm running version 1.0.8 and faced the error. With a pure ASCII path everything worked nice. So I guess some regression happened somewere. I'm using the binary packages from Debian Squeeze on a amd64 platform. Either the fix wasn't appropriate for all platforms, or some regression happened.
{{{
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.0.8
WARNING: the config value '**file**' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u"Content".
loading pickled environment... not yet created
building [html]: targets for 29 source files that are out of date
updating environment: 29 added, 0 changed, 0 removed
reading sources... [  3%] alert  
Exception occurred:
  File "/usr/lib/pymodules/python2.7/sphinx/cmdline.py", line 188, in main
    app.build(force_all, filenames)
  File "/usr/lib/pymodules/python2.7/sphinx/application.py", line 207, in build
    self.builder.build_update()
  File "/usr/lib/pymodules/python2.7/sphinx/builders/**init**.py", line 198, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/pymodules/python2.7/sphinx/builders/**init**.py", line 218, in build
    purple, length):
  File "/usr/lib/pymodules/python2.7/sphinx/builders/**init**.py", line 120, in status_iterator
    for item in iterable:
  File "/usr/lib/pymodules/python2.7/sphinx/environment.py", line 514, in update_generator
    self.read_doc(docname, app=app)
  File "/usr/lib/pymodules/python2.7/sphinx/environment.py", line 667, in read_doc
    self.process_images(docname, doctree)
  File "/usr/lib/pymodules/python2.7/sphinx/environment.py", line 845, in process_images
    if not os.access(path.join(self.srcdir, imgpath), os.R_OK):
  File "/usr/lib/python2.7/posixpath.py", line 71, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 30: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-qwTDRB.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at http://groups.google.com/group/sphinx-dev/,
or report them in the tracker at https://bitbucket.org/birkenfeld/sphinx/issues/. Thanks!
make: **\* [html] Error 1
}}}

**Comment by shimizukawa** [comment]
_From [theoden](https://bitbucket.org/theoden) on 2014-04-14 05:32:02+00:00_

Non-Ascii path support seems to be broken on Windows 7 enterprise 32-bit. Or these are just some problems with tests.

**UPD**: the same two tests are failed with a similar output even on Windows 7 Professional 64-bit with the minGW's bash.

Here is the output of `make test`:

```
(sphinx) C:\proj_python\sphinx>make test
running build
running build_py
running egg_info
writing dependency_links to Sphinx.egg-info\dependency_links.txt
writing requirements to Sphinx.egg-info\requires.txt
writing Sphinx.egg-info\PKG-INFO
writing top-level names to Sphinx.egg-info\top_level.txt
writing entry points to Sphinx.egg-info\entry_points.txt
reading manifest file 'Sphinx.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'doc\_build'
writing manifest file 'Sphinx.egg-info\SOURCES.txt'
Copying sources to build/lib/tests...
Running Sphinx test suite...
.....................E........S.................................................
................................................................................
......SS...................................S.............................S......
.SS.F.............SSSSS.SSSS.
======================================================================
ERROR: test_build.test_nonascii_path
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\env\sphinx\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
File "C:\proj_python\sphinx\build\lib\tests\util.py", line 199, in deco
    func(app, *args2, **kwargs2)
File "C:\proj_python\sphinx\build\lib\tests\test_build.py", line 99, in test_n
onascii_path
    app.builder.build_all()
File "C:\proj_python\sphinx\build\lib\sphinx\builders\__init__.py", line 177,
in build_all
    self.build(None, summary='all source files', method='all')
File "C:\proj_python\sphinx\build\lib\sphinx\builders\__init__.py", line 234,
in build
    purple, length):
File "C:\proj_python\sphinx\build\lib\sphinx\builders\__init__.py", line 134,
in status_iterator
    for item in iterable:
File "C:\proj_python\sphinx\build\lib\sphinx\environment.py", line 477, in upd
ate_generator
    self.read_doc(docname, app=app)
File "C:\proj_python\sphinx\build\lib\sphinx\environment.py", line 622, in rea
d_doc
    pub.set_source(None, src_path.encode(fs_encoding))
File "C:\env\sphinx\lib\site-packages\docutils\core.py", line 179, in set_sour
ce
    encoding=self.settings.input_encoding)
File "C:\proj_python\sphinx\build\lib\sphinx\environment.py", line 596, in __i
nit__
    FileInput.__init__(self_, *args, **kwds)
File "C:\env\sphinx\lib\site-packages\docutils\io.py", line 238, in __init__
    raise InputError(error.errno, error.strerror, source_path)
InputError: [Errno 22] invalid mode ('rU') or filename: 'c:\\temp\\tmpcaoweo\\ro
ot\\???\\???.txt'

======================================================================
FAIL: test_setup_command.test_build_sphinx_with_nonascii_path
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\env\sphinx\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
File "C:\proj_python\sphinx\build\lib\tests\test_setup_command.py", line 50, i
n deco
    func(pkgrootdir, proc, *args, **kwds)
File "C:\proj_python\sphinx\build\lib\tests\test_setup_command.py", line 94, i
n test_build_sphinx_with_nonascii_path
    assert proc.returncode == 0
AssertionError:
-------------------- >> begin captured stdout << ---------------------
running build_sphinx
creating c:\temp\tmp1bqwuc\root\build
creating c:\temp\tmp1bqwuc\root\build\sphinx
creating c:\temp\tmp1bqwuc\root\build\sphinx\doctrees
creating c:\temp\tmp1bqwuc\root\build\sphinx\html
Running Sphinx v1.2.2+/6204298faae7+
loading pickled environment... not yet created
building [html]: targets for 2 source files that are out of date
updating environment: 2 added, 0 changed, 0 removed
reading sources... [ 50%] contents
reading sources... [100%] ???/???

error: c:\temp\tmp1bqwuc\root\doc\???\???.txt: invalid mode ('rU') or filename


--------------------- >> end captured stdout << ----------------------
    'running build_sphinx\r\ncreating c:\\temp\\tmp1bqwuc\\root\\build\r\ncreati
ng c:\\temp\\tmp1bqwuc\\root\\build\\sphinx\r\ncreating c:\\temp\\tmp1bqwuc\\roo
t\\build\\sphinx\\doctrees\r\ncreating c:\\temp\\tmp1bqwuc\\root\\build\\sphinx\
\html\r\nRunning Sphinx v1.2.2+/6204298faae7+\r\nloading pickled environment...
not yet created\r\nbuilding [html]: targets for 2 source files that are out of d
ate\r\nupdating environment: 2 added, 0 changed, 0 removed\r\nreading sources...
[ 50%] contents\r\nreading sources... [100%] ???/???\r\n', "error: c:\\temp\\tm
p1bqwuc\\root\\doc\\???\\???.txt: invalid mode ('rU') or filename\r\n" = <subpro
cess.Popen object at 0x050B6C90>.communicate()
    print('running build_sphinx\r\ncreating c:\\temp\\tmp1bqwuc\\root\\build\r\n
creating c:\\temp\\tmp1bqwuc\\root\\build\\sphinx\r\ncreating c:\\temp\\tmp1bqwu
c\\root\\build\\sphinx\\doctrees\r\ncreating c:\\temp\\tmp1bqwuc\\root\\build\\s
phinx\\html\r\nRunning Sphinx v1.2.2+/6204298faae7+\r\nloading pickled environme
nt... not yet created\r\nbuilding [html]: targets for 2 source files that are ou
t of date\r\nupdating environment: 2 added, 0 changed, 0 removed\r\nreading sour
ces... [ 50%] contents\r\nreading sources... [100%] ???/???\r\n')
    print("error: c:\\temp\\tmp1bqwuc\\root\\doc\\???\\???.txt: invalid mode ('r
U') or filename\r\n")
>>  assert <subprocess.Popen object at 0x050B6C90>.returncode == 0


----------------------------------------------------------------------
Ran 268 tests in 130.474s

FAILED (SKIP=16, errors=1, failures=1)
Makefile:52: recipe for target 'test' failed
```

What can I provide additionally to help with this issue?

**Comment by 20-100** [comment]
Hi, I'm still having the UnicodeDecodeError when my project lives in a non-ASCII path.
I have version 1.1.3.

Here is my path : ~/Thèse/svn/code/doc/
The project root is the folder "code" and the doc is in subfolder doc, with source and build separated.
I tried to move the whole "code" folder directly in ~, hence avoiding the non-ASCII letter in "Thèse" and everything works just fine.

**Comment by shimizukawa** [comment]
@20-100 Sphinx supports non-ASCII path since version 1.2. Please use newer version.
If you get UnicodeDecodeError with Sphinx-1.2 or later, please let me know with new ticket. Thanks.
