### ISSUE TITLE
RuntimeError: dictionary changed size during iteration while building with autodoc.py

### ISSUE THREAD

**Issue by NucleaPeon** [sphinx-doc/sphinx#2295]
I encountered a RuntimeError while building python documentation due to the directory size changing while I built the files.

Traceback:

```
# Sphinx version: 1.3.5
# Python version: 3.4.3 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
... 
# Loaded extensions:
#   sphinx.ext.autodoc (1.3.5) from /media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/ext/autodoc.py
#   sphinx.ext.todo (1.3.5) from /media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/ext/todo.py
#   sphinx.ext.intersphinx (1.3.5) from /media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/ext/intersphinx.py
#   alabaster (0.7.7) from /media/dann/external/app.docs/venv/lib/python3.4/site-packages/alabaster/__init__.py
Traceback (most recent call last):
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/application.py", line 266, in build
    self.builder.build_update()
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/environment.py", line 618, in update
    self._read_serial(docnames, app)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/environment.py", line 638, in _read_serial
    self.read_doc(docname, app)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/environment.py", line 791, in read_doc
    pub.publish()
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/environment.py", line 128, in read
    self.parse()
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 1469, in run
    documenter.generate(more_content=self.content)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 828, in generate
    self.document_members(all_members)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 750, in document_members
    check_module=members_check_module and not isattr)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 828, in generate
    self.document_members(all_members)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 1194, in document_members
    ModuleLevelDocumenter.document_members(self, all_members)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 709, in document_members
    members_check_module, members = self.get_object_members(want_all)
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 609, in get_object_members
    for mname in obj_dict.keys()]
  File "/media/dann/external/app.docs/venv/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 608, in <listcomp>
    members = [(mname, self.get_attr(self.object, mname, None))
RuntimeError: dictionary changed size during iteration
```

The command I was using to generate the documentation was this:

```
sphinx-apidoc -T -e -P -o db app.db/mymodule/
```

The fix was to modify line `609` in `venv/lib/python3.4/site-packages/sphinx/ext/autodoc.py`:

```
members = [(mname, self.get_attr(self.object, mname, None))
    for mname in obj_dict.keys()]
```

**became:**

```
members = [(mname, self.get_attr(self.object, mname, None))
    for mname in list(obj_dict.keys())]
```

I got the idea for the fix from here:
https://bitbucket.org/birkenfeld/sphinx/pull-requests/311/fix-sphinx-quickstart-does-not-work-on/diff

**Comment by birkenfeld** [comment]
That fix certainly makes sense. Thanks for the report!
