### ISSUE TITLE
Building docs is non-determinstic and sometimes fails with "RuntimeError: maximum recursion depth exceeded while pickling an object"

### ISSUE THREAD

**Issue by timgraham** [sphinx-doc/sphinx#2324]
Sometimes building the Django docs fails like this:

```
# Sphinx version: 1.3.5
# Python version: 3.4.0 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   reading sources... [ 46%] ref/models/index
#   reading sources... [ 47%] ref/models/instances
#   reading sources... [ 47%] ref/models/lookups
#   reading sources... [ 47%] ref/models/meta
#   reading sources... [ 47%] ref/models/options
#   reading sources... [ 48%] ref/models/querysets
#   reading sources... [ 48%] ref/models/relations
#   reading sources... [ 48%] ref/request-response
#   reading sources... [ 49%] ref/schema-editor
#   reading sources... [ 49%] ref/settings
# Loaded extensions:
#   sphinx.ext.intersphinx (1.3.5) from /home/www/www/venv/lib/python3.4/site-packages/sphinx/ext/intersphinx.py
#   alabaster (0.7.7) from /home/www/www/venv/lib/python3.4/site-packages/alabaster/__init__.py
#   djangodocs (unknown version) from /home/www/www/data/docbuilds/sources/dev/docs/_ext/djangodocs.py
#   ticket_role (unknown version) from /home/www/www/data/docbuilds/sources/dev/docs/_ext/ticket_role.py
#   sphinx.ext.viewcode (1.3.5) from /home/www/www/venv/lib/python3.4/site-packages/sphinx/ext/viewcode.py
Traceback (most recent call last):
  File "/home/www/www/venv/lib/python3.4/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/www/www/venv/lib/python3.4/site-packages/sphinx/application.py", line 266, in build
    self.builder.build_update()
  File "/home/www/www/venv/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/www/www/venv/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/home/www/www/venv/lib/python3.4/site-packages/sphinx/environment.py", line 618, in update
    self._read_serial(docnames, app)
  File "/home/www/www/venv/lib/python3.4/site-packages/sphinx/environment.py", line 638, in _read_serial
    self.read_doc(docname, app)
  File "/home/www/www/venv/lib/python3.4/site-packages/sphinx/environment.py", line 863, in read_doc
    pickle.dump(doctree, f, pickle.HIGHEST_PROTOCOL)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

The problematic file is a long one: `docs/ref/settings.txt`. [Here's a link](https://github.com/timgraham/bug-files/tree/master/sphinx-2324) to a doctree file where the build worked (734kB) and one where it failed with the above error (803kB) -- I dropped into a pdb shell on failure and set `sys.setrecursionlimit(1137)` to allow myself to write the file manually.

[sphinx-dev thread](https://groups.google.com/d/topic/sphinx-dev/MtRf64eGtv4/discussion)

**Comment by timgraham** [comment]
Does the non-deterministic portion of this issue merit any investigation?

**Comment by birkenfeld** [comment]
I suppose it's the usual: hash randomization. You could try with `PYTHONHASHSEED=x` and different x to see if makes it deterministic.
