### ISSUE TITLE
sphinx Anaconda problem ? 

### ISSUE THREAD

**Issue by simone-hochgreb** [sphinx-doc/sphinx#2334]
The code was running fine with sphinx before installing Anaconda. 
Installed package, but after editing the conf.py file, the result seems to show that the theme is no longer found. Possibly wrong directories being searched ? Not sure how to fix this. 

---

```
`make html`
>>
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.3.1
WARNING: the config value 'html_theme' has type `list', defaults to `str.'
loading pickled environment... done

Exception occurred:
  File "//anaconda/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/theming.py", line 97, in __init__
    if name not in self.themes:
TypeError: unhashable type: 'list'
The full traceback has been saved in /var/folders/95/sjm2462s1mz5hxp1g59bvm5r0000gn/T/sphinx-err-pm6jvxfx.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
baiao:Sphinx_orig Simone$ Exception occurred:
-bash: Exception: command not found
baiao:Sphinx_orig Simone$   File "//anaconda/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/theming.py", line 97, in __init__
//anaconda/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/theming.py,: cannot open `//anaconda/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/theming.py,' (No such file or directory)
line:                                                                             cannot open `line' (No such file or directory)
97,:                                                                              cannot open `97,' (No such file or directory)
in:                                                                               cannot open `in' (No such file or directory)
__init__:                                                                         cannot open `__init__' (No such file or directory)
baiao:Sphinx_orig Simone$     if name not in self.themes:
> TypeError: unhashable type: 'list'
> The full traceback has been saved in /var/folders/95/sjm2462s1mz5hxp1g59bvm5r0000gn/T/sphinx-err-pm6jvxfx.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
> make: *** [html] Error 1
```

---

Here is the log file: 

```
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "//anaconda/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/application.py", line 188, in __init__
    self._init_builder(buildername)
  File "//anaconda/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/application.py", line 249, in _init_builder
    self.builder = builderclass(self)
  File "//anaconda/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/builders/__init__.py", line 88, in __init__
    self.init()
  File "//anaconda/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/builders/html.py", line 106, in init
    self.init_templates()
  File "//anaconda/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/builders/html.py", line 141, in init_templates
    self.theme = Theme(themename, warn=self.warn)
  File "//anaconda/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg/sphinx/theming.py", line 97, in __init__
    if name not in self.themes:
TypeError: unhashable type: 'list'
```

**Comment by tk0miya** [comment]
Could you check `html_theme` in your `conf.py`?

Sphinx warns it is assigned list value, but it expects string value.

```
WARNING: the config value 'html_theme' has type `list', defaults to `str.'
```

More details, see http://www.sphinx-doc.org/en/stable/theming.html#using-a-theme

**Comment by simone-hochgreb** [comment]
Thanks. Now solved.
