### ISSUE TITLE
Autodoc 'sa_engine' problem

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#235]
While using  autodoc extension  I get this:

/home/zaba/zosia/zosia/public/docs/test.rst:17: (WARNING/2) autodoc can't import/find module 'controllers.obiekty', it reported error: "'NoneType' object has no attribute 'sa_engine'", please check your spelling and sys.path

In conf.py I have:
sys.path.append(os.path.abspath('../../')) 

Changing this value doesn't help at all. 

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/235
- Originally reported by: [zabsko](https://bitbucket.org/zabsko)
- Originally created at: 2009-08-10T13:30:20.055

**Comment by shimizukawa** [comment]
_From [zabsko](https://bitbucket.org/zabsko) on 2009-08-11 08:01:34+00:00_

It looks like a pydoc problem:

zaba@SRW001:~/zosia/zosia/controllers$ pydoc modules obiekty.py

Please wait a moment while I gather a list of all available modules...

Traceback (most recent call last):
  File "/usr/bin/pydoc", line 5, in <module>
    pydoc.cli()
  File "/usr/lib/python2.5/pydoc.py", line 2225, in cli
    help.help(arg)
  File "/usr/lib/python2.5/pydoc.py", line 1683, in help
    elif request == 'modules': self.listmodules()
  File "/usr/lib/python2.5/pydoc.py", line 1804, in listmodules
    ModuleScanner().run(callback)
  File "/usr/lib/python2.5/pydoc.py", line 1855, in run
    for importer, modname, ispkg in pkgutil.walk_packages():
  File "/usr/lib/python2.5/pkgutil.py", line 125, in walk_packages
    for item in walk_packages(path, name+'.', onerror):
  File "/usr/lib/python2.5/pkgutil.py", line 125, in walk_packages
    for item in walk_packages(path, name+'.', onerror):
  File "/usr/lib/python2.5/pkgutil.py", line 110, in walk_packages
    **import**(name)
  File "/home/zaba/zosia/zosia/lib/raportlib/**init**.py", line 5, in <module>
    from stat_zesp_uproszczony          import *
  File "/home/zaba/zosia/zosia/lib/raportlib/stat_zesp_uproszczony.py", line 6, in <module>
    from zosia.lib.rapfl             import draw_pie, draw_bar3d_statzespupr
  File "/home/zaba/zosia/zosia/lib/rapfl.py", line 4, in <module>
    from zosia.lib.base                     import *
  File "/home/zaba/zosia/zosia/lib/base.py", line 14, in <module>
    import zosia.model as model
  File "/home/zaba/zosia/zosia/model/**init**.py", line 15, in <module>
    bind=config['pylons.g'].sa_engine))
AttributeError: 'NoneType' object has no attribute 'sa_engine'

**Comment by shimizukawa** [comment]
_From [zabsko](https://bitbucket.org/zabsko) on 2009-08-11 09:17:31+00:00_

Problems seems to be resolved by changing:

Session = scoped_session(sessionmaker(autoflush=True,
                                      transactional=True,
                                      bind=econfig['pylons.g'].sa_engine))

to:

engine = config['pylons.g'].sa_engine if config['pylons.g'] else None

Session = scoped_session(sessionmaker(autoflush=True,
                                      transactional=True,
                                      bind=engine))

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2013-03-31 13:57:14+00:00_

Removing version: 0.6.2 (automated comment)
