### ISSUE TITLE
Failure to build python3.5 docs - ValueEror: too many values to unpack

### ISSUE THREAD

**Issue by asottile** [sphinx-doc/sphinx#2400]
I could probably find a smaller testcase but for now I thought I'd report it:
## Version info

```
$ python --version
Python 3.4.2
```

```
$ pip freeze -l
Babel==2.2.0
Jinja2==2.8
MarkupSafe==0.23
Pygments==2.1.3
Sphinx==1.4
alabaster==0.7.7
docutils==0.12
imagesize==0.7.0
pytz==2016.3
six==1.10.0
snowballstemmer==1.2.1
```
## Acquiring the source

```
echo 'deb-src http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu precise main' >> /etc/apt/sources.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5BB92C09DB82666C
apt-get update
apt-get source python3.5="3.5.1-1+precise1"
```
## Building

```
cd python3.5-3.5.1/Doc && sphinx-build . docout
```

Last bits of comandline output:

```
$ sphinx-build . docout
...
/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/whatsnew/2.7.rst:2374: WARNING: unknown option: -r
/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/whatsnew/2.7.rst:2380: WARNING: unknown option: -j
/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/whatsnew/2.7.rst:2380: WARNING: unknown option: -F
/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/whatsnew/3.0.rst:905: WARNING: unknown option: -3
generating indices... genindex
Exception occurred:
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/themes/basic/genindex-single.html", line 40, in block "body"
    {%- for entryname, (links, subitems) in column %}
ValueError: too many values to unpack (expected 2)
The full traceback has been saved in /nail/tmp/sphinx-err-tlel0ybu.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
## Log output

```
cat /nail/tmp/sphinx-err-tlel0ybu.log
# Sphinx version: 1.4
# Python version: 3.4.2 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   /nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/whatsnew/2.7.rst:2221: WARNING: unknown option: --with-valgrind
#   /nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/whatsnew/2.7.rst:2228: WARNING: unknown option: --with-dbmliborder=
#   /nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/whatsnew/2.7.rst:2374: WARNING: unknown option: --randseed=
#   /nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/whatsnew/2.7.rst:2374: WARNING: unknown option: -r
#   /nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/whatsnew/2.7.rst:2374: WARNING: unknown option: -r
#   /nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/whatsnew/2.7.rst:2380: WARNING: unknown option: -j
#   /nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/whatsnew/2.7.rst:2380: WARNING: unknown option: -F
#   /nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/whatsnew/3.0.rst:905: WARNING: unknown option: -3
#   generating indices...
#   genindex
# Loaded extensions:
#   sphinx.ext.doctest (1.4) from /nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/ext/doctest.py
#   alabaster (0.7.7) from /nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/alabaster/__init__.py
#   sphinx.ext.coverage (1.4) from /nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/ext/coverage.py
#   pyspecific (unknown version) from /nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/tools/extensions/pyspecific.py
#   c_annotations (1.0) from /nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/tools/extensions/c_annotations.py
Traceback (most recent call last):
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 325, in build
    self.finish()
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/builders/html.py", line 461, in finish
    self.finish_tasks.add_task(self.gen_indices)
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/util/parallel.py", line 40, in add_task
    res = task_func()
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/builders/html.py", line 477, in gen_indices
    self.write_genindex()
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/builders/html.py", line 535, in write_genindex
    'genindex-single.html')
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/builders/html.py", line 802, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/jinja2glue.py", line 138, in render
    return self.environment.get_template(template).render(context)
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/themes/basic/genindex-single.html", line 32, in top-level template code
    {% set title = _('Index') %}
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/Doc/tools/templates/layout.html", line 1, in top-level template code
    {% extends "!layout.html" %}
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/themes/default/layout.html", line 13, in top-level template code
    {% set script_files = script_files + ['_static/sidebar.js'] %}
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/themes/basic/layout.html", line 160, in top-level template code
    {%- block content %}
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/themes/basic/layout.html", line 164, in block "content"
    {%- block document %}
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/themes/basic/layout.html", line 170, in block "document"
    {% block body %} {% endblock %}
  File "/nail/home/asottile/trees/python3.5/dist/lucid/python3.5-3.5.1/venv/lib/python3.4/site-packages/sphinx/themes/basic/genindex-single.html", line 40, in block "body"
    {%- for entryname, (links, subitems) in column %}
ValueError: too many values to unpack (expected 2)
```
## Workaround

```
pip install 'sphinx<1.4'
```

**Comment by ccanepa** [comment]
Same problem with python 2.7.11 64bits on Windows.
Sphinx 1.4 installed from pypi with pip:
```
		Successfully installed Jinja2-2.8 MarkupSafe-0.23 Pygments-2.1.3 alabaster-0.7.7
		 babel-2.2.0 colorama-0.3.7 docutils-0.12 imagesize-0.7.0 pytz-2016.3 snowballst
		emmer-1.2.1 sphinx-1.4

```

Running the documentation build for https://github.com/los-cocos/cocos.git  (master, current tip, ie at commit  3b410f3

Building with

**Comment by ccanepa** [comment]
Same problem with python 2.7.11 64bits on Windows.
Sphinx 1.4 installed from pypi with pip:

```
        Successfully installed Jinja2-2.8 MarkupSafe-0.23 Pygments-2.1.3 alabaster-0.7.7
         babel-2.2.0 colorama-0.3.7 docutils-0.12 imagesize-0.7.0 pytz-2016.3 snowballst
        emmer-1.2.1 sphinx-1.4

```

Running the documentation build for https://github.com/los-cocos/cocos.git  (master, current tip, ie at commit  3b410f3) , pyglet 1.2.x from pypi needs to be installed,

Building with 

```
  cd docgen
  make html
```

gives

```
...
preparing documents... done
writing output... [100%] programming_guide/transitions
generating indices... genindex
Exception occurred:
  File "c:\python27-64\lib\site-packages\sphinx\themes\basic\genindex-single.htm
l", line 40, in block "body"
    {%- for entryname, (links, subitems) in column %}
ValueError: too many values to unpack
The full traceback has been saved in c:\users\jugar\appdata\local\temp\sphinx-er
r-bn_rho.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message c
an be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphin
x/issues>. Thanks!
```

The log:

```
# Sphinx version: 1.4
# Python version: 2.7.11 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   writing output... [ 92%] programming_guide/installation
#   writing output... [ 94%] programming_guide/interpreter
#   writing output... [ 95%] programming_guide/introduction
#   writing output... [ 96%] programming_guide/quickstart
#   writing output... [ 97%] programming_guide/skeleton/skeleton
#   writing output... [ 98%] programming_guide/tiled_map
#   writing output... [100%] programming_guide/transitions
#   
#   generating indices...
#   genindex
# Loaded extensions:
#   sphinx.ext.graphviz (1.4) from c:\python27-64\lib\site-packages\sphinx\ext\graphviz.pyc
#   sphinx.ext.autosummary (1.4) from c:\python27-64\lib\site-packages\sphinx\ext\autosummary\__init__.pyc
#   sphinx.ext.autodoc (1.4) from c:\python27-64\lib\site-packages\sphinx\ext\autodoc.pyc
#   alabaster (0.7.7) from c:\python27-64\lib\site-packages\alabaster\__init__.pyc
#   sphinx.ext.inheritance_diagram (1.4) from c:\python27-64\lib\site-packages\sphinx\ext\inheritance_diagram.pyc
Traceback (most recent call last):
  File "c:\python27-64\lib\site-packages\sphinx\cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "c:\python27-64\lib\site-packages\sphinx\application.py", line 287, in build
    self.builder.build_update()
  File "c:\python27-64\lib\site-packages\sphinx\builders\__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "c:\python27-64\lib\site-packages\sphinx\builders\__init__.py", line 325, in build
    self.finish()
  File "c:\python27-64\lib\site-packages\sphinx\builders\html.py", line 461, in finish
    self.finish_tasks.add_task(self.gen_indices)
  File "c:\python27-64\lib\site-packages\sphinx\util\parallel.py", line 40, in add_task
    res = task_func()
  File "c:\python27-64\lib\site-packages\sphinx\builders\html.py", line 477, in gen_indices
    self.write_genindex()
  File "c:\python27-64\lib\site-packages\sphinx\builders\html.py", line 535, in write_genindex
    'genindex-single.html')
  File "c:\python27-64\lib\site-packages\sphinx\builders\html.py", line 802, in handle_page
    output = self.templates.render(templatename, ctx)
  File "c:\python27-64\lib\site-packages\sphinx\jinja2glue.py", line 138, in render
    return self.environment.get_template(template).render(context)
  File "c:\python27-64\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\python27-64\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27-64\lib\site-packages\sphinx\themes\basic\genindex-single.html", line 32, in top-level template code
    {% set title = _('Index') %}
  File "c:\python27-64\lib\site-packages\sphinx\themes\classic\layout.html", line 13, in top-level template code
    {% set script_files = script_files + ['_static/sidebar.js'] %}
  File "c:\python27-64\lib\site-packages\sphinx\themes\basic/layout.html", line 160, in top-level template code
    {%- block content %}
  File "c:\python27-64\lib\site-packages\sphinx\themes\basic/layout.html", line 164, in block "content"
    {%- block document %}
  File "c:\python27-64\lib\site-packages\sphinx\themes\basic/layout.html", line 170, in block "document"
    {% block body %} {% endblock %}
  File "c:\python27-64\lib\site-packages\sphinx\themes\basic\genindex-single.html", line 40, in block "body"
    {%- for entryname, (links, subitems) in column %}
ValueError: too many values to unpack
```

Workaround sugested by  asottile worked [pip picked sphinx-1.3.6 sphinx-rtd-theme-0.1.9 this time], thanks asottile !

edit: added   cd in the build instruictions.

**Comment by methane** [comment]
```
le "/Users/inada-n/venvs/pydoc/lib/python3.5/site-packages/sphinx/themes/basic/genindex-single.html", line 40, in block "body"
    {%- for entryname, (links, subitems) in column %}
ValueError: too many values to unpack (expected 2)
> /Users/inada-n/venvs/pydoc/lib/python3.5/site-packages/sphinx/themes/basic/genindex-single.html(40)block "body"()
-> {%- for entryname, (links, subitems) in column %}
(Pdb)
(Pdb) x, (y, z) = column[0]
*** ValueError: too many values to unpack (expected 2)
(Pdb) column[0]
('! (pdb command)', [[('', 'library/pdb.html#pdbcommand-!')], [], None])
(Pdb) x, y = column[0]
(Pdb) y
[[('', 'library/pdb.html#pdbcommand-!')], [], None]
(Pdb) len(y)
3
(Pdb) x, y = column[1]
(Pdb) y
[[], [('operator', [('', 'library/stdtypes.html#index-8')])], None]
(Pdb) len(y)
3
(Pdb)
```

**Comment by shimizukawa** [comment]
Thanks everyone and sorry for your inconvenience. This issue is same as #2396. I'll fix soon.

**Comment by tk0miya** [comment]
I merged #2396 now.
It will be released in a few days.

Thank you for reporting

**Comment by shimizukawa** [comment]
https://pypi.python.org/pypi/Sphinx/1.4.1 has been released. Please try it.

**Comment by ccanepa** [comment]
updated from pypi to 1.4.1, builds normal for cocos.
Thank you !
