### ISSUE TITLE
Note new dependencies prominently in release notes

### ISSUE THREAD

**Issue by cdeil** [sphinx-doc/sphinx#2404]
My package manager, Macports, just updated to Sphinx 1.4 and now it fails like this:

```
$ sphinx-build --version
Traceback (most recent call last):
  File "/opt/local/bin/sphinx-build", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3124, in _call_aside
    f(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 661, in _build_master
    ws.require(__requires__)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 962, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'imagesize' distribution was not found and is required by Sphinx
```

From the changelog 
https://github.com/sphinx-doc/sphinx/blob/55a991e24198b7f10c3ff75a6f937bdcf2e3b408/CHANGES#L100
and 
https://github.com/sphinx-doc/sphinx/blob/master/setup.py#L51
I was able to figure out that in Sphinx 1.4 [imagesize](https://pypi.python.org/pypi/imagesize) was added as a required dependency.

Could you please mention new dependencies more prominently in the changelog, e.g. at the top add a sentence "Sphinx 1.4 introduced `imagesize` (link to PyPI) as a new dependency"?

I'll file an issue in the Macports tracker now, asking them to package `imagesize` and add it as a new dependency for Sphinx.

**Comment by shimizukawa** [comment]
Sphinx (and all other python packages) defines dependencies in setup.py and the information is provided to other programs. For instance, https://pypi.python.org/pypi/pipdeptree read the dependency information and display a dependency tree as a human readable format.

In my opinion, package system maintainers (include for MacPorts) can/should detect "new dependencies" automatically. This is the information technology.
Otherwise, writing dependencies on the top of CHANGES might cause human errors like misreadings and overlooking . Because it is unformatted natural text. I believe the maintainers should refer setup.py on building the packages. It is very simple and less failure way.
