### ISSUE TITLE
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlsplit'

### ISSUE THREAD

**Issue by jburkhardt** [sphinx-doc/sphinx#2443]
`make html` leads to following output:

```
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.4
loading pickled environment... not yet created

Exception occurred:
  File "/Library/Python/2.7/site-packages/sphinx/ext/intersphinx.py", line 148, in _strip_basic_auth
    url_parts = parse.urlsplit(url)
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlsplit'
The full traceback has been saved in /var/folders/0g/x6_0cl8s37sc0mc1hdpscqrh1zms81/T/sphinx-err-qG6hBR.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```

Here is the output of the log file:

```
# Sphinx version: 1.4
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 197, in __init__
    self._init_builder(self.buildername)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 269, in _init_builder
    self.emit('builder-inited')
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 536, in emit
    results.append(callback(self, *args))
  File "/Library/Python/2.7/site-packages/sphinx/ext/intersphinx.py", line 291, in load_mappings
    safe_inv_url = _get_safe_url(inv)
  File "/Library/Python/2.7/site-packages/sphinx/ext/intersphinx.py", line 205, in _get_safe_url
    url, username, _ = _strip_basic_auth(url)
  File "/Library/Python/2.7/site-packages/sphinx/ext/intersphinx.py", line 148, in _strip_basic_auth
    url_parts = parse.urlsplit(url)
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlsplit'
```

OS: OS X El Capitan Version 10.11.4
Python: Version 2.7.10

**Comment by jburkhardt** [comment]
Problem solved: Update of [python six package](https://pypi.python.org/pypi/six) solves the issue.

**Comment by jputrino** [comment]
@jburkhardt -- I'm getting the same error and am using v1.10.0 of six. I got the error in both sphinx 1.4.0 and 1.4.1.

```
# Sphinx version: 1.4.1
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 197, in __init__
    self._init_builder(self.buildername)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 269, in _init_builder
    self.emit('builder-inited')
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 536, in emit
    results.append(callback(self, *args))
  File "/Library/Python/2.7/site-packages/sphinx/ext/intersphinx.py", line 291, in load_mappings
    safe_inv_url = _get_safe_url(inv)
  File "/Library/Python/2.7/site-packages/sphinx/ext/intersphinx.py", line 205, in _get_safe_url
    url, username, _ = _strip_basic_auth(url)
  File "/Library/Python/2.7/site-packages/sphinx/ext/intersphinx.py", line 148, in _strip_basic_auth
    url_parts = parse.urlsplit(url)
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlsplit'
/var/folders/06/0gyp09193p5632bd177_g2pr0r1ztr/T/sphinx-err-MDoklh.log (END)
```

```
$ pip show six
---
Metadata-Version: 2.0
Name: six
Version: 1.10.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
Installer: pip
License: MIT
Location: /Library/Python/2.7/site-packages
Requires:
Classifiers:
  Programming Language :: Python :: 2
  Programming Language :: Python :: 3
  Intended Audience :: Developers
  License :: OSI Approved :: MIT License
  Topic :: Software Development :: Libraries
  Topic :: Utilities
```

**Comment by jburkhardt** [comment]
Updating the six package solved the issue on my machine.

```
pip install six --upgrade
```

Here is the package information:

```
$ pip show six
---
Metadata-Version: 1.1
Name: six
Version: 1.10.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /Library/Python/2.7/site-packages/six-1.10.0-py2.7.egg
Requires: 
Classifiers:
  Programming Language :: Python :: 2
  Programming Language :: Python :: 3
  Intended Audience :: Developers
  License :: OSI Approved :: MIT License
  Topic :: Software Development :: Libraries
  Topic :: Utilities
```

I hope this helps you in some way...
