### ISSUE TITLE
Typing-related tests failure with latest Python 3.5 snapshot

### ISSUE THREAD

**Issue by mitya57** [sphinx-doc/sphinx#2519]
One of the tests fails with the latest Python 3.5 snapshot (what will become 3.5.2):

```
======================================================================
FAIL: test_autodoc.test_type_hints
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/build/sphinx-1.4.1/tests/test_autodoc.py", line 1024, in test_type_hints
    verify_arg_spec(f1, '(x: typing.List[int]) -> typing.List[int]')
  File "/build/sphinx-1.4.1/tests/test_autodoc.py", line 1018, in verify_arg_spec
    eq_(formatargspec(f, *getargspec(f)), expected)
AssertionError: '(x: typing.List[]) -> typing.List[]' != '(x: typing.List[int]) -> typing.List[int]'

----------------------------------------------------------------------
```

Apparently since python/typing@abefbe4a72654e7e385944848b0158969ee33d2e `typing.List[int].__parameters__` is an empty tuple rather than a tuple containing `int`.

On a related note, they changed (in the same commit) the syntax of strings returned by `__repr__` so it is now incompatible with what Sphinx uses (and thus `__repr__` is no longer a sane fallback).

**Comment by mitya57** [comment]
Cc @vlasovskikh

**Comment by tk0miya** [comment]
Now #2532 is merged. So I close this.
Thanks,
