### ISSUE TITLE
Graphviz Extension Runtime Error

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#253]
I'm trying to use graphviz within a project.
Running on Windows, Python 2.5

from a clean quickstart structure, added one file named essai.txt containing the following : 
# Essai Graphviz

.. graphviz::

digraph foo {
      "bar" -> "baz";
   }

which is derived form the graphviz extension documentation.

I get the following error log  when building HTML output (sorry couldn't find a way to better attach it):

Traceback (most recent call last):
  File "c:\python25\lib\site-packages\Sphinx-0.6.1-py2.5.egg\sphinx\cmdline.py", line 172, in main
    app.build(all_files, filenames)
  File "c:\python25\lib\site-packages\Sphinx-0.6.1-py2.5.egg\sphinx\application.py", line 129, in build
    self.builder.build_update()
  File "c:\python25\lib\site-packages\Sphinx-0.6.1-py2.5.egg\sphinx\builders__init__.py", line 255, in build_update
    'out of date' &#37; len(to_build))
  File "c:\python25\lib\site-packages\Sphinx-0.6.1-py2.5.egg\sphinx\builders__init__.py", line 310, in build
    self.write(docnames, list(updated_docnames), method)
  File "c:\python25\lib\site-packages\Sphinx-0.6.1-py2.5.egg\sphinx\builders__init__.py", line 349, in write
    self.write_doc(docname, doctree)
  File "c:\python25\lib\site-packages\Sphinx-0.6.1-py2.5.egg\sphinx\builders\html.py", line 344, in write_doc
    self.docwriter.write(doctree, destination)
  File "C:\Python25\lib\site-packages\docutils\writers__init__.py", line 76, in write
    self.translate()
  File "c:\python25\lib\site-packages\Sphinx-0.6.1-py2.5.egg\sphinx\writers\html.py", line 37, in translate
    self.document.walkabout(visitor)
  File "C:\Python25\lib\site-packages\docutils\nodes.py", line 176, in walkabout
    if child.walkabout(visitor):
  File "C:\Python25\lib\site-packages\docutils\nodes.py", line 176, in walkabout
    if child.walkabout(visitor):
  File "C:\Python25\lib\site-packages\docutils\nodes.py", line 168, in walkabout
    visitor.dispatch_visit(self)
  File "C:\Python25\lib\site-packages\docutils\nodes.py", line 1535, in dispatch_visit
    return method(node)
  File "c:\python25\lib\site-packages\Sphinx-0.6.1-py2.5.egg\sphinx\ext\graphviz.py", line 161, in html_visit_graphviz
    render_dot_html(self, node, node['code'], node['options'])
  File "c:\python25\lib\site-packages\Sphinx-0.6.1-py2.5.egg\sphinx\ext\graphviz.py", line 139, in render_dot_html
    mapfile = open(outfn + '.map', 'rb')
IOError: [Errno 2] No such file or directory: 'D:\projets\oss\cartographie\_build\html\_images\graphviz-871d01b18b7460aea3f8dc2dde57c872cf5c84e7.png.map'

Any idea what's going wrong ?

Regards

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/253
- Originally reported by: Anonymous
- Originally created at: 2009-09-03T11:00:01.830

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-09-03 14:18:59+00:00_

Thanks for the report! Your markup is wrong, because the content of the graphviz directive is not indented. It should be

{{{
.. graphviz::

   digraph foo {
      "bar" -> "baz";
   }
}}}

Nevertheless, the unhandled exception should not occur. I've fixed this in <<cset 3cc52246b205f1c03c8f83d548610c6a35475331>>.

**Comment by shimizukawa** [comment]
_From Anonymous on 2009-09-03 16:29:15+00:00_

Thanks Georg for reactivity !
Im' sorry, but I also tried with correct indent

It's working exactly the same.

I even tested the dot snippet with several other graphviz chains and it's OK.

Have you tried creating a document including graphviz ? Could you send me sample ?

Regards.

Julien

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2013-03-31 13:57:13+00:00_

Removing version: 0.6.2 (automated comment)
