### ISSUE TITLE
"assert parentSymbol" when referring to a non-existent symbol in the C++ domain

### ISSUE THREAD

**Issue by vitaut** [sphinx-doc/sphinx#2536]
The following code

``` rst
.. cpp:namespace:: foo

.. cpp:class:: foo::bar

   :cpp:any:`baz`
```

causes an assertion failure:

```
Target:  bazut... [100%] index                                                  
ParentKey:  [(<ASTNestedNameElement foo>, None), (<ASTNestedNameElement foo>, None), (<ASTNestedNameElement bar>, None)]

Exception occurred:
  File "/usr/local/lib/python3.5/dist-packages/sphinx/domains/cpp.py", line 4112, in _resolve_xref_inner
    assert parentSymbol  # should be there
AssertionError
```

The full log is

```
# Sphinx version: 1.4.1
# Python version: 3.5.1+ (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [100%] index
# Loaded extensions:
#   alabaster (0.7.7) from /usr/local/lib/python3.5/dist-packages/alabaster/__init__.py
#   breathe (4.2.0) from /home/viz/workspace/sphinx-test/breathe/breathe/__init__.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.5/dist-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python3.5/dist-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/builders/__init__.py", line 366, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/environment.py", line 1242, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/environment.py", line 1497, in resolve_references
    typ, target, node, contnode)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/domains/cpp.py", line 4143, in resolve_xref
    target, node, contnode)[0]
  File "/usr/local/lib/python3.5/dist-packages/sphinx/domains/cpp.py", line 4112, in _resolve_xref_inner
    assert parentSymbol  # should be there
AssertionError
```

Removing `.. cpp:namespace:: foo` makes assertion go away.

**Comment by zsquareplusc** [comment]
Getting this error too with Sphinx 1.4.1. Worked fine in Sphinx 1.3.4 which I had installed previously. Now it crashes when outputting the files, not even producing an usable documentation.

```
('Target: ', u'uint8_t')
('ParentKey: ', [(<ASTNestedNameElement nonvolatile>, None), (<ASTNestedNameElement PhonyNameDueToError>, None), (<ASTNestedNameElement PhonyNameDueToError>, None), (<ASTNestedNameElement checksum>, None)])

Exception occurred:
  File "C:\Python27\lib\site-packages\sphinx\domains\cpp.py", line 4112, in _resolve_xref_inner
    assert parentSymbol  # should be there
```

**Comment by jakobandersen** [comment]
Thanks for reporting! The issue was with lookup of nested names where two consecutive names are the same (e.g., "foo::foo" and "PhonyNameDueToError::PhonyNameDueToError").

**Comment by vitaut** [comment]
Thanks, @jakobandersen. This particular example is fixed, but I still get the same error in another one:

```
('Target: ', 'std') 50%] reference                                              
('ParentKey: ', [(<ASTNestedNameElement fmt>, None), (<ASTNestedNameElement fmt>, None), (<ASTNestedNameElement format>, None)])
```

Here's the stack trace:

```
# Sphinx version: 1.4.1
# Python version: 2.7.11+ (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [ 25%] contents
#   writing output... [ 50%] reference
# Loaded extensions:
#   breathe (4.2.0) from /home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/breathe/__init__.pyc
#   alabaster (0.7.8) from /home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.ifconfig (1.4.1) from /home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/ext/ifconfig.pyc
Traceback (most recent call last):
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 366, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/environment.py", line 1242, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/environment.py", line 1497, in resolve_references
    typ, target, node, contnode)
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/domains/cpp.py", line 4143, in resolve_xref
    target, node, contnode)[0]
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/domains/cpp.py", line 4112, in _resolve_xref_inner
    assert parentSymbol  # should be there
AssertionError
```

**Comment by vitaut** [comment]
I'll try to come up with another test case.

**Comment by vitaut** [comment]
Nevermind, the issue was that pip was installing wrong version of sphinx. Thanks for a quick fix, @jakobandersen.
