### ISSUE TITLE
UnicodeEncodeError occurs in cross-reference anything

### ISSUE THREAD

**Issue by togakushi** [sphinx-doc/sphinx#2555]
UnicodeEncodeError occurs when using the Japanese in cross-reference anything.

index.rst

```
Welcome to a's documentation!
=============================

Contents:

.. toctree::
   :maxdepth: 2



Indices and tables
==================

* :any:`genindex`
* :any:`modindex`
* :any:`search`
* :any:`日本語`
```

To `make html` this file.

output of `make html`

```
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.4.1
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index

Encoding error:
'ascii' codec can't encode characters in position 71-73: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-dtkwk1.log, if you want to report the issue to the developers.
Makefile:58: recipe for target 'html' failed
make: *** [html] Error 1
```

/tmp/sphinx-err-dtkwk1.log

```
# Sphinx version: 1.4.1
# Python version: 2.7.11+ (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [100%] index
# Loaded extensions:
#   alabaster (0.7.7) from /usr/local/lib/python2.7/dist-packages/alabaster/__init__.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 366, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 1242, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 1500, in resolve_references
    newnode = self._resolve_any_reference(builder, node, contnode)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 1603, in _resolve_any_reference
    target, node, contnode))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/domains/cpp.py", line 4149, in resolve_any_xref
    emitWarnings=False)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/domains/cpp.py", line 4103, in _resolve_xref_inner
    % (target, str(e.description)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 71-73: ordinal not in range(128)
```

This was thought to be a warning.

For example,

```
WARNING: u'any' reference target not found: 日本語
```

**Comment by jakobandersen** [comment]
Thanks for reporting. It should be fixed in 'stable' now.

**Comment by togakushi** [comment]
thank you for fix!!

error no longer occurs.
looking forward to the next release.
