### ISSUE TITLE
Error when compiling Python 3 docs to DevHelp

### ISSUE THREAD

**Issue by jtojnar** [sphinx-doc/sphinx#2558]
When trying to build DevHelp docs for Python using

```
curl https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tar.xz | tar xJ && cd Python-3.5.1/Doc
sphinx-build -b devhelp -d build/doctrees . build/devhelp
```

build fails:

```
# Sphinx version: 1.4.1
# Python version: 3.5.1 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   copying images... [ 50%] using/win_installer.png
#   copying images... [ 66%] faq/python-video-icon.png
#   copying images... [ 83%] howto/logging_flow.png
#   copying images... [100%] library/tulip_coro.png
#   
#   copying static files...
#   done
#   copying extra files...
#   done
#   dumping devhelp index...
# Loaded extensions:
#   sphinx.ext.coverage (1.4.1) from /usr/lib/python3.5/site-packages/sphinx/ext/coverage.py
#   alabaster (0.7.7) from /usr/lib/python3.5/site-packages/alabaster/__init__.py
#   c_annotations (1.0) from /home/jtojnar/tmp/sphinx-fail/Python-3.5.1/Doc/tools/extensions/c_annotations.py
#   pyspecific (1.0) from /home/jtojnar/tmp/sphinx-fail/Python-3.5.1/Doc/tools/extensions/pyspecific.py
#   sphinx.ext.doctest (1.4.1) from /usr/lib/python3.5/site-packages/sphinx/ext/doctest.py
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python3.5/site-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/usr/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 325, in build
    self.finish()
  File "/usr/lib/python3.5/site-packages/sphinx/builders/html.py", line 471, in finish
    self.handle_finish()
  File "/usr/lib/python3.5/site-packages/sphinx/builders/devhelp.py", line 64, in handle_finish
    self.build_devhelp(self.outdir, self.config.devhelp_basename)
  File "/usr/lib/python3.5/site-packages/sphinx/builders/devhelp.py", line 126, in build_devhelp
    for title, (refs, subitems) in group:
ValueError: too many values to unpack (expected 2)
```

**Comment by tk0miya** [comment]
Fixed at    b4df918.
Thank you for reporting!
