### ISSUE TITLE
Not informative exception message

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2569]
I have just stumbled across an exception whose message does not give much information:

```
Exception occurred:
  File "/home/andrea/.local/lib/python3.4/site-packages/sphinx/util/tags.py", line 66, in eval_condition
    raise ValueError('chunk after expression')
ValueError: chunk after expression
The full traceback has been saved in /tmp/sphinx-err-d_1ltz1g.log, if you want to report the issue to the developers.
```

Note that the log provides a long stack trace, but if one has a certain number of `only` directive it might be hard to figure out which one is offending.

What about including the conditional that causes the exception to be risen?

**Comment by andreacassioli** [comment]
I guess it is here, `sphinx/util/tags.py, line 66`

```
       if not parser.stream.eos:
            raise ValueError('chunk after expression')
```

**Comment by tk0miya** [comment]
Could you paste the full traceback? And tell me the condition for `only` directive please.

**Comment by andreacassioli** [comment]
Hi @tk0miya 
I have moved on the issue, but I remember the problem was I misspelled a tag including some forbidden character, say `-`. Fixed that it was fine.

I am using a custom `only` directive (maybe you remember I opened an issue on the fact that `only` does parse the content even if the condition is false...). But I still call the base system for the evaluation.

My point is that the error message does not point to the file it happens or print out the offending expression. In my understanding the exception ValueError only get a simple message, in that case `chunk after expression`.

Here it is the traceback

```
# Sphinx version: 1.4.1
# Python version: 3.4.3 (CPython)
# Docutils version: 0.11 release
# Jinja2 version: 2.8
# Last messages:
#   Running Sphinx v1.4.1
#   loading intersphinx inventory from http://docs/docs/manuals/generic/modeling-cookbook/objects.inv...
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 19 source files that are out of date
#   updating environment:
#   19 added, 0 changed, 0 removed
#   reading sources... [  5%] changes
# Loaded extensions:
#   numsec (unknown version) from /home/andrea/mosekprj/dev/blddoc/mosekdistro/mosek-distro/source/./numsec.py
#   msk_download (unknown version) from /home/andrea/mosekprj/dev/blddoc/mosekdistro/mosek-distro/source/./msk_download.py
#   sphinxcontrib.bibtex (unknown version) from /home/andrea/.local/lib/python3.4/site-packages/sphinxcontrib/bibtex/__init__.py
#   msk_target_link (unknown version) from /home/andrea/mosekprj/dev/blddoc/mosekdistro/mosek-distro/source/./msk_target_link.py
#   alabaster (0.7.8) from /home/andrea/.local/lib/python3.4/site-packages/alabaster/__init__.py
#   sphinx.ext.graphviz (1.4.1) from /home/andrea/.local/lib/python3.4/site-packages/sphinx/ext/graphviz.py
#   broken_references (unknown version) from /home/andrea/mosekprj/dev/blddoc/mosekdistro/mosek-distro/source/./broken_references.py
#   substitutions (unknown version) from /home/andrea/mosekprj/dev/blddoc/mosekdistro/mosek-distro/source/./substitutions.py
#   msk_literalinclude (unknown version) from /home/andrea/mosekprj/dev/blddoc/mosekdistro/mosek-distro/source/./msk_literalinclude.py
#   msk_only (unknown version) from /home/andrea/mosekprj/dev/blddoc/mosekdistro/mosek-distro/source/./msk_only.py
#   msk_utils (unknown version) from /home/andrea/mosekprj/dev/blddoc/mosekdistro/mosek-distro/source/./msk_utils.py
#   sphinx.ext.mathjax (1.4.1) from /home/andrea/.local/lib/python3.4/site-packages/sphinx/ext/mathjax.py
Traceback (most recent call last):
  File "/home/andrea/.local/lib/python3.4/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/andrea/.local/lib/python3.4/site-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/home/andrea/.local/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/andrea/.local/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/home/andrea/.local/lib/python3.4/site-packages/sphinx/environment.py", line 548, in update
    self._read_serial(docnames, app)
  File "/home/andrea/.local/lib/python3.4/site-packages/sphinx/environment.py", line 568, in _read_serial
    self.read_doc(docname, app)
  File "/home/andrea/.local/lib/python3.4/site-packages/sphinx/environment.py", line 721, in read_doc
    pub.publish()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/andrea/.local/lib/python3.4/site-packages/sphinx/io.py", line 49, in read
    self.parse()
  File "/usr/lib/python3/dist-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2727, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 396, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 283, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2300, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2312, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2055, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2104, in run_directive
    result = directive_instance.run()
  File "/home/andrea/mosekprj/dev/blddoc/mosekdistro/mosek-distro/source/./msk_only.py", line 24, in run
    if not env.app.builder.tags.eval_condition(self.arguments[0]) :
  File "/home/andrea/.local/lib/python3.4/site-packages/sphinx/util/tags.py", line 66, in eval_condition
    raise ValueError('chunk after expression')
ValueError: chunk after expression
```

**Comment by tk0miya** [comment]
Thank you for additional report.

I think your extension should handle the exceptions from `sphinx.util.tags` and display human readable error messages.
`sphinx.util.tags` is designed as internal library to evaluate conditions. So it raises several exceptions to represent many errors. The `ValueError` you said is a part of exceptions the module throws.

For example, `SphinxEnvironment.process_only_nodes()` handles them and show warnings:
https://github.com/sphinx-doc/sphinx/blob/1.4.1/sphinx/environment.py#L1637

**Comment by andreacassioli** [comment]
OK,
thanks
