### ISSUE TITLE
AttributeError: BuildEnvironment instance has no attribute 'included'

### ISSUE THREAD

**Issue by phdru** [sphinx-doc/sphinx#2631]
Hi! I have upgraded to 1.4.3 and got a strange error:

```
# Sphinx version: 1.4.3
# Python version: 2.7.9 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:
#   reading sources... [ 33%] api/m_librarian.config
#   reading sources... [ 66%] api/m_librarian.db
#   reading sources... [100%] command_line
#   
#   /home/phd/current/projects/m_librarian/docs/command_line.rst:189: WARNING: Literal block ends without a blank line; unexpected unindent.
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
# Loaded extensions:
#   alabaster (0.7.8) from /home/phd/.virtualenvs/Sphinx/local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.autodoc (1.4.3) from /home/phd/.virtualenvs/Sphinx/local/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.viewcode (1.4.3) from /home/phd/.virtualenvs/Sphinx/local/lib/python2.7/site-packages/sphinx/ext/viewcode.pyc
Traceback (most recent call last):
  File "/home/phd/.virtualenvs/Sphinx/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/phd/.virtualenvs/Sphinx/local/lib/python2.7/site-packages/sphinx/application.py", line 298, in build
    self.builder.build_update()
  File "/home/phd/.virtualenvs/Sphinx/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/phd/.virtualenvs/Sphinx/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 289, in build
    self.env.check_consistency()
  File "/home/phd/.virtualenvs/Sphinx/local/lib/python2.7/site-packages/sphinx/environment.py", line 1974, in check_consistency
    if docname in self.included:
AttributeError: BuildEnvironment instance has no attribute 'included'
```

Strange because I don't see where `included` was deleted from `self`. Not sure if it's properly initialized.

**Comment by phdru** [comment]
Got it. The attribute hasn't been restored from pickle. I removed old pickles (*.doctree) and successfullly rebuilt my docs.

**Comment by tk0miya** [comment]
Thank you for reporting.
I noticed that I'd forgotten to increment ENV_VERSION from this issue.
