### ISSUE TITLE
make html gives error on windows 10 with Python 3.4.4 and Sphinx 1.4.3 

### ISSUE THREAD

**Issue by Chaitya62** [sphinx-doc/sphinx#2658]
```
# Sphinx version: 1.4.3
# Python version: 3.4.4 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "C:\Python34\Lib\site-packages\sphinx\cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "C:\Python34\Lib\site-packages\sphinx\application.py", line 137, in __init__
    confoverrides or {}, self.tags)
  File "C:\Python34\Lib\site-packages\sphinx\config.py", line 291, in __init__
    execfile_(filename, config)
  File "C:\Python34\Lib\site-packages\sphinx\util\pycompat.py", line 130, in execfile_
    exec_(code, _globals)
  File "conf.py", line 251, in <module>
    u'https://github.com/scikit-learn/'
  File "C:\Users\Chaitya\Desktop\CODE\ml\scikit-learn\doc\sphinxext\github_link.py", line 82, in make_linkcode_resolve
    revision = _get_git_revision()
  File "C:\Users\Chaitya\Desktop\CODE\ml\scikit-learn\doc\sphinxext\github_link.py", line 13, in _get_git_revision
    revision = subprocess.check_output(REVISION_CMD.split()).strip()
  File "C:\Python34\Lib\subprocess.py", line 607, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "C:\Python34\Lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\Lib\subprocess.py", line 1114, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by tk0miya** [comment]
It seems same as #2609. This might be a bug of `github_link.py` made by scikit-learn project.
Could you ask about the error to scikit learn project please?

Thanks,

**Comment by Chaitya62** [comment]
Cool  thanks a lot
