### ISSUE TITLE
dangling symlink causes cryptic cPickle.PicklingError

### ISSUE THREAD

**Issue by aspiers** [sphinx-doc/sphinx#2718]
Steps to reproduce:

```
git clone https://github.com/openstack/nova-specs.git
cd nova-specs/doc/source/specs/liberty
rm template.rst
ln -s nonexistent template.rst
cd ../../../..
tox -e docs
```

This causes an extremely cryptic and hard to debug `PicklingError`:

```
pickling environment... Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    pbr=True)
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/adam/nova-specs/.tox/docs/lib/python2.7/site-packages/pbr/builddoc.py", line 196, in run
    self._sphinx_run()
  File "/home/adam/nova-specs/.tox/docs/lib/python2.7/site-packages/pbr/builddoc.py", line 150, in _sphinx_run
    app.build(force_all=self.all_files)
  File "/home/adam/nova-specs/.tox/docs/lib/python2.7/site-packages/sphinx/application.py", line 206, in build
    self.emit('build-finished', err)
  File "/home/adam/nova-specs/.tox/docs/lib/python2.7/site-packages/sphinx/application.py", line 314, in emit
    results.append(callback(self, *args))
  File "/home/adam/nova-specs/.tox/docs/lib/python2.7/site-packages/yasfb/__init__.py", line 146, in emit_feed
    builder.env.topickle(os.path.join(builder.doctreedir, ENV_PICKLE_FILENAME))
  File "/home/adam/nova-specs/.tox/docs/lib/python2.7/site-packages/sphinx/environment.py", line 303, in topickle
    pickle.dump(self, picklefile, pickle.HIGHEST_PROTOCOL)
cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
```

whereas it should output something which gives the user some kind of clue that one of their symlinks is wrong.

**Comment by tk0miya** [comment]
Fixed at b30d4f4.
Thank you for reporting!
