### ISSUE TITLE
FileExistsError exception

### ISSUE THREAD

**Issue by zaufi** [sphinx-doc/sphinx#2769]
Trying to build LLVM docs I've got an error:

```
Exception occurred:
File "/usr/lib64/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/storage/tmp/paludis/sys-devel-llvm-3.8.0-r3/work/llvm-3.8.0.src-abi_x86_64.amd64/tools/clang/tools/extra/docs/_doctrees/clang-tidy/checks'
The full traceback has been saved in /storage/tmp/paludis/sys-devel-llvm-3.8.0-r3/temp/sphinx-err-5z811099.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

`sphinx-err-5z811099.log` is here:

```
Sphinx version: 1.3.5
# Python version: 3.5.1 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   loading pickled environment...
#   not yet created
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 93 source files that are out of date
#   updating environment:
#   93 added, 0 changed, 0 removed
#   reading sources... [  1%] ModularizeUsage
#   reading sources... [  2%] clang-modernize
#   reading sources... [  3%] clang-tidy
#   reading sources... [  4%] clang-tidy/checks/cert-dcl03-c
# Loaded extensions:
#   sphinx.ext.mathjax (1.3.5) from /usr/lib64/python3.5/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.8) from /usr/lib64/python3.5/site-packages/alabaster/__init__.py
#   sphinx.ext.todo (1.3.5) from /usr/lib64/python3.5/site-packages/sphinx/ext/todo.py
Traceback (most recent call last):
File "/usr/lib64/python3.5/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
File "/usr/lib64/python3.5/site-packages/sphinx/application.py", line 266, in build
    self.builder.build_update()
File "/usr/lib64/python3.5/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
File "/usr/lib64/python3.5/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
File "/usr/lib64/python3.5/site-packages/sphinx/environment.py", line 618, in update
    self._read_serial(docnames, app)
File "/usr/lib64/python3.5/site-packages/sphinx/environment.py", line 638, in _read_serial
    self.read_doc(docname, app)
File "/usr/lib64/python3.5/site-packages/sphinx/environment.py", line 860, in read_doc
    os.makedirs(dirname)
File "/usr/lib64/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/storage/tmp/paludis/sys-devel-llvm-3.8.0-r3/work/llvm-3.8.0.src-abi_x86_64.amd64/tools/clang/tools/extra/docs/_doctrees/clang-tidy/checks'
```

IMHO, presence of the directories when you trying to create a hierarchy shouldn't be an error... it may exists (due previous run) and it is quite Ok... so `os.makedirs()` needs to be fixed to allow this (by adding `exist_ok=True` named parameter)...

**Comment by tk0miya** [comment]
It was fixed at Sphinx-1.3.6 (ref: #2289). Please update your sphinx (current stable version is 1.4.4!).

Thanks,
