### ISSUE TITLE
UnknownExtra: requests 2.2.1 has no such extra feature 'security'

### ISSUE THREAD

**Issue by bilalbaqar** [sphinx-doc/sphinx#2811]
Getting this error while running make html
# Python version: 2.7.6 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
# Loaded extensions:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 181, in **init**
    self.setup_extension(extension)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 501, in setup_extension
    mod = **import**(extension, None, None, ['setup'])
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/linkcheck.py", line 43, in <module>
    pkg_resources.require(['requests[security]'])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 633, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2299, in requires
    "%s has no such extra feature %r" % (self, ext)
UnknownExtra: requests 2.2.1 has no such extra feature 'security'

**Comment by tk0miya** [comment]
Thank you for reporting. I fixed it.
