### ISSUE TITLE
Incompatible versions of numpy in Read The Docs

### ISSUE THREAD

**Issue by bmorris3** [sphinx-doc/sphinx#2813]
I'm trying to build Sphinx docs on Read The Docs, and I'm getting the following error which causes [the build](https://readthedocs.org/projects/shampoo/builds/4238452/) to fail: 

```
Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "/usr/lib/python2.7/dist-packages/six.py", line 549, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 105, in <module>
    __import__(setup_cfg['package_name'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/shampoo-0.1.dev118-py2.7.egg/shampoo/__init__.py", line 8, in <module>
    from .reconstruction import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/shampoo-0.1.dev118-py2.7.egg/shampoo/reconstruction.py", line 19, in <module>
    from .vis import save_scaled_image
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/shampoo-0.1.dev118-py2.7.egg/shampoo/vis.py", line 5, in <module>
    from skimage.io import imsave
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/io/__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/io/manage_plugins.py", line 28, in <module>
    from .collection import imread_collection_wrapper
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/io/collection.py", line 14, in <module>
    from ..external.tifffile import TiffFile
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/external/tifffile/__init__.py", line 1, in <module>
    from .tifffile import imsave, imread, imshow, TiffFile, TiffWriter, TiffSequence
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/external/tifffile/tifffile.py", line 153, in <module>
    from . import _tifffile
RuntimeError: module compiled against API version a but this version of numpy is 9

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/shampoo/envs/latest/local/lib/python2.7/site-packages/skimage/external/tifffile/tifffile.py", line 153, in <module>
    from . import _tifffile
RuntimeError: module compiled against API version a but this version of numpy is 9
The full traceback has been saved in /tmp/sphinx-err-rhH5RI.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Segmentation fault
```

Do you have tips on what causes the numpy version to appear to be incompatible, even though numpy is being installed alongside skimage?

**Comment by tk0miya** [comment]
To my knowledge, you can use `requirements.txt` to specify the version of dependencies.
I don't know whether it works to numpy.

Anyway please ask that in readthedocs project.
https://github.com/rtfd/readthedocs.org
