### ISSUE TITLE
Sphinx-build throws exception for python flask application

### ISSUE THREAD

**Issue by shelkesays** [sphinx-doc/sphinx#2817]
While documenting flask application using following command:

`sphinx-build -b html docs/ docs/_build/`

I am getting exception as follows:

`RuntimeError: working outside of application context`

Following is the stack trace:
`
[sphinx-err-I1_s95.txt](https://github.com/sphinx-doc/sphinx/files/388355/sphinx-err-I1_s95.txt)

Traceback (most recent call last):
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/sphinx/builders/**init**.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/sphinx/builders/**init**.py", line 265, in build
    self.doctreedir, self.app))
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/sphinx/environment.py", line 569, in update
    self._read_serial(docnames, app)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/sphinx/environment.py", line 589, in _read_serial
    self.read_doc(docname, app)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/sphinx/environment.py", line 742, in read_doc
    pub.publish()
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/sphinx/io.py", line 49, in read
    self.parse()
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/**init**.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 1613, in run
    documenter.generate(more_content=self.content)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 963, in generate
    self.document_members(all_members)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 855, in document_members
    if cls.can_document_member(member, mname, isattr, self)]
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 1458, in can_document_member
    isdatadesc = isdescriptor(member) and not \
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/sphinx/util/inspect.py", line 101, in isdescriptor
    if hasattr(safe_getattr(x, item, None), '**call**'):
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/sphinx/util/inspect.py", line 113, in safe_getattr
    if name in obj.**dict**:
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/werkzeug/local.py", line 343, in **getattr**
    return getattr(self._get_current_object(), name)
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/home/rahul/git/sms_cms/venv/local/lib/python2.7/site-packages/flask/globals.py", line 34, in _find_app
    raise RuntimeError('working outside of application context')
RuntimeError: working outside of application context
`

Also Have attached the traceback generated in log file.

**Comment by tk0miya** [comment]
Sorry for inconvenience. Now it was fixed at #2778.
Please wait next release.

Thanks,

**Comment by shelkesays** [comment]
When can I expect new release?

**Comment by tk0miya** [comment]
It is scheduled at 20th of Aug now.
