### ISSUE TITLE
Formatting of Exceptions in apidoc examples

### ISSUE THREAD

**Issue by seclinch** [sphinx-doc/sphinx#2830]
I'm using sphinx-apidoc to generate documentation for a project. The project already uses doctest and so many of the docstrings contain code snippets that serve as both examples and test cases.

I was pleased to find that sphinx automatically formats the example code nicely, but I seem to have found one specific case in which it doesn't work for me.

In the attached example file, the first two example code snippets are correctly formatted by apidoc, the final example is not (using the alabaster theme, I get the grey box for a code snippet but no syntax highlighting).

[doctestsphinxtest.txt](https://github.com/sphinx-doc/sphinx/files/402011/doctestsphinxtest.txt)

The difference appears to be using a user-defined exception rather than an inbuilt one. Is there a way to have an example raising a user-defined exception work correctly?

<img width="798" alt="screen shot 2016-08-04 at 16 48 50" src="https://cloud.githubusercontent.com/assets/4030190/17408508/5d6818a4-5a63-11e6-8c11-9db0663b42df.png">

**Comment by tk0miya** [comment]
As a quick look, it seems a bug of pygments; the highlighting library which sphinx uses.
Could you report this to pygments team please?

```
from pygments import highlight
from pygments.lexers import PythonConsoleLexer
from pygments.formatters import HtmlFormatter


pycon3 = PythonConsoleLexer(python3=True, stripnl=False)
pycon3.add_filter('raiseonerror')
formatter = HtmlFormatter()

source = """
>>> foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/saffy/Desktop/yarely-cookiecut/yarely/doctestsphinxtest.py", line 34, in foo
    raise b
yarely.doctestsphinxtest.FooError
"""

highlight(source, pycon3, formatter)  # => raises pygments.filters.ErrorToken
```

```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    highlight(source, pycon3, formatter)  # => raises pygments.filters.ErrorToken
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/pygments/__init__.py", line 87, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/pygments/formatters/html.py", line 850, in format_unencoded
    for t, piece in source:
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/pygments/formatters/html.py", line 690, in _wrap_div
    for tup in inner:
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/pygments/formatters/html.py", line 708, in _wrap_pre
    for tup in inner:
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/pygments/formatters/html.py", line 727, in _format_lines
    for ttype, value in tokensource:
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/pygments/filter.py", line 20, in _apply
    for token in filter_.filter(lexer, stream):
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/pygments/filters/__init__.py", line 196, in filter
    raise self.exception(value)
pygments.filters.ErrorToken: y
```
