### ISSUE TITLE
ImportError: No module named sphinx_bootstrap_theme

### ISSUE THREAD

**Issue by TomB512** [sphinx-doc/sphinx#2831]
File "conf.py", line 17, in <module>
ImportError: No module named sphinx_bootstrap_theme

Following is text in "sphinx-err-OyWMn8.log"
# Sphinx version: 1.4.5
# Python version: 2.7.6 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
# Loaded extensions:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 137, in **init**
    confoverrides or {}, self.tags)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/config.py", line 292, in **init**
    execfile_(filename, config)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 130, in execfile_
    exec_(code, _globals)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 17, in <module>
ImportError: No module named sphinx_bootstrap_theme

**Comment by TomB512** [comment]
Solved!!!
Typed in the following line and all is well.  The dollar sign is the prompt (not typed-in).
$ pip install sphinx_bootstrap_theme
