### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 5273: ordinal not in range(128)

### ISSUE THREAD

**Issue by igor-raits** [sphinx-doc/sphinx#2888]
``` python
# Sphinx version: 1.4.5
# Python version: 3.5.2 (CPython)
# Docutils version: 0.12 repository
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib/python3.5/site-packages/sphinx/application.py", line 137, in __init__
    confoverrides or {}, self.tags)
  File "/usr/lib/python3.5/site-packages/sphinx/config.py", line 292, in __init__
    execfile_(filename, config)
  File "/usr/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 130, in execfile_
    exec_(code, _globals)
  File "conf.py", line 66, in <module>
    version = '%s' % version_readout()
  File "conf.py", line 61, in version_readout
    lines = f.readlines()
  File "/usr/lib64/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 5273: ordinal not in range(128)
```

Looks like it started appearing only since 1.4.5 release.

**Comment by igor-raits** [comment]
```
def version_readout():
    fn = os.path.join(_dirname, '../dnf-plugins-core.spec')
    with open(fn) as f:
        lines = f.readlines()
    for line in lines:
        if line.startswith('Version:'):
            return line.split(':')[1].strip()

version = '%s' % version_readout()
```

hm, probably it's just our bug.

**Comment by igor-raits** [comment]
my bad, sorry.
