### ISSUE TITLE
build info doesn't get saved and search index couldn't be loaded

### ISSUE THREAD

**Issue by tobiasHeinke** [sphinx-doc/sphinx#2910]
The .docbuild file keys are not saved after full build and the keys vary.
In following the searchindex.js is only generated partially:
after full build: 40kB from 350kB; after normal build: 19kB. (only indices from the altered pages)
While normal build it throws the warning. "sphinx search index couldn't be loaded [...]".

But strangely, the parser gets a problem with underscores.
Removing those makes the warning disappear.

In Sphinx 1.4.4 both test and normal docs work.

Sphinx: 1.4.5 and 1.46; Python: 3.52

This is the traceback during full build:

`Traceback (most recent call last):
  File "[py] \sphinx\builders\html.py", line 184, in get_outdated_docs
    cfg, old_config_hash = fp.readline().strip().split(': ')
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[py] \sphinx\cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "[py] \sphinx\application.py", line 297, in build
    self.builder.build_update()
  File "[py] \sphinx\builders__init__.py", line 248, in build_update
    to_build = list(to_build)
  File "[py] \sphinx\builders\html.py", line 194, in get_outdated_docs
    path.join(self.outdir, '.buildinfo'))
  File "[py] \sphinx\application.py", line 360, in warn
    raise SphinxWarning(warntext)
sphinx.errors.SphinxWarning: WARNING: unsupported build info format in '[repos] \build\.buildinfo', building all`

And the following the search index warning when normal building:

`Traceback (most recent call last):
  File "[py] \sphinx\builders\html.py", line 709, in load_indexer
    self.indexer.load(f, self.indexer_format)
  File "[py] \sphinx\search__init__.py", line 249, in load
    frozen = format.load(stream)
  File "[py] \sphinx\search__init__.py", line 166, in load
    return self.loads(f.read())
  File "[py] \sphinx\search__init__.py", line 160, in loads
    return jsdump.loads(data)
  File "[py] \sphinx\util\jsdump.py", line 187, in loads
    raise ValueError("read error at pos %d" % i)
ValueError: read error at pos 46260

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[py] \sphinx\cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "[py] \sphinx\application.py", line 297, in build
    self.builder.build_update()
  File "[py] \sphinx\builders__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "[py] \sphinx\builders__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "[py] \sphinx\builders__init__.py", line 349, in write
    self.prepare_writing(docnames)
  File "[py] \sphinx\builders\html.py", line 261, in prepare_writing
    self.load_indexer(docnames)
  File "[py] \sphinx\builders\html.py", line 714, in load_indexer
    self.warn('search index couldn\'t be loaded, but not all '
  File "[py] \sphinx\application.py", line 360, in warn
    raise SphinxWarning(warntext)
sphinx.errors.SphinxWarning: WARNING: search index couldn't be loaded, but not all documents will be built: the index will be incomplete.`

**Comment by tobiasHeinke** [comment]
Project: [Blender manual](https://www.blender.org/manual/contents.html)
[Repository conf.py](https://developer.blender.org/diffusion/BM/browse/trunk/blender_docs/manual/conf.py)
https://developer.blender.org/T49126

**Comment by tk0miya** [comment]
it seems this is related with #2902.
At first, I try to fix #2902.  Could you test it after fixed?  If not fixed yet, I will investigate this again.

**Comment by tk0miya** [comment]
Fixed #2902 at acd4d9f.
Could you try the HEAD of stable branch?

**Comment by Blendify** [comment]
I have confirmed that the bug is fixed

**Comment by tk0miya** [comment]
Thank you for confirmation!
