### ISSUE TITLE
Support row/column spanning tables in text build

### ISSUE THREAD

**Issue by TimKam** [sphinx-doc/sphinx#2915]
When trying to build text docs with row/column spanning tables (#28), I get the following `NotImplementedError`:

`Column or row spanning cells are not implemented.`

With the error, the build is aborted.

**Comment by tk0miya** [comment]
I reproduced this with following table:

```
+------+------+
| test | test |
+------+------+
| test test   |
+------+------+
```

Traceback is here:

```
Traceback (most recent call last):
  File "/Users/tkomiya/work/sphinx/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/Users/tkomiya/work/sphinx/sphinx/application.py", line 335, in build
    self.builder.build_update()
  File "/Users/tkomiya/work/sphinx/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/Users/tkomiya/work/sphinx/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/tkomiya/work/sphinx/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/Users/tkomiya/work/sphinx/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/Users/tkomiya/work/sphinx/sphinx/builders/text.py", line 59, in write_doc
    self.writer.write(doctree, destination)
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/Users/tkomiya/work/sphinx/sphinx/writers/text.py", line 152, in translate
    self.document.walkabout(visitor)
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
.. test documentation master file, created by
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/Users/tkomiya/work/sphinx/sphinx/writers/text.py", line 508, in visit_entry
    raise NotImplementedError('Column or row spanning cells are '
NotImplementedError: Column or row spanning cells are not implemented.
```

**Comment by KhaledTo** [comment]
This seems to be fixed in v1.5a2. At least i couldn't reproduce this issue.

**Comment by bluebird75** [comment]
The issue was reproduced with the following table :
```

============  ============  ===================  ================  =============  ===================  ===============
**True assertion family**                                            **False assertion family**
-----------------------------------------------------------------  ---------------------------------------------------
Input Value   assertTrue()   assertEvalToTrue()  assertNotFalse()  assertFalse()  assertEvalToFalse()  assertNotTrue()
============  ============  ===================  ================  =============  ===================  ===============
*true*        OK            OK                   OK                Fail           Fail                 Fail
*false*       Fail          Fail                 Fail              OK             OK                   OK 
*nil*         Fail          Fail                 OK                Fail           OK                   OK 
*0*           Fail          OK                   OK                Fail           Fail                 Fail 
*1*           Fail          OK                   OK                Fail           Fail                 Fail
*"hello"*     Fail          OK                   OK                Fail           Fail                 Fail
============  ============  ===================  ================  =============  ===================  ===============

```

**Comment by JulienPalard** [comment]
I implemented something here: https://github.com/JulienPalard/sphinx/tree/text-colspan-rowspan

But it's late here, I did *not* tested it properly, did *not* checked types anotations, did not ran tests, and github did *not* created my remote branch [1] so I can't create a PR from it... so there's still a lot of work.

[1]: Which is strange I can hit my branch via the link I gave but the branch does *not* exist in the dropdown, disallowing me to PR it... maybe I'm just tired, maybe github is tired...
