### ISSUE TITLE
Exception occured with "make latexpdf"

### ISSUE THREAD

**Issue by vpoughon** [sphinx-doc/sphinx#2923]
When running make latexpdf:

```
Exception occurred:
  File "/usr/lib/python2.7/site-packages/babel/dates.py", line 863, in get_day_of_year
    return (date - date_(date.year, 1, 1)).days + 1
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'
```

Full traceback:

```
# Sphinx version: 1.4.6
# Python version: 2.7.5 (CPython)
# Docutils version: 0.11 repository
# Jinja2 version: 2.7.2
# Last messages:
#   Applications/app_CompareImages
#   Applications/app_HyperspectralUnmixing
#   Applications/app_KmzExport
#   Applications/app_OSMDownloader
#   Applications/app_ObtainUTMZoneFromGeoPoint
#   Applications/app_PixelValue
#   Applications/app_VertexComponentAnalysis
#   
#   resolving references...
#   writing...
# Loaded extensions:
#   sphinx.ext.todo (1.4.6) from /usr/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   alabaster (0.7.9) from /usr/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.mathjax (1.4.6) from /usr/lib/python2.7/site-packages/sphinx/ext/mathjax.pyc
#   sphinx.ext.viewcode (1.4.6) from /usr/lib/python2.7/site-packages/sphinx/ext/viewcode.pyc
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 246, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python2.7/site-packages/sphinx/builders/latex.py", line 133, in write
    docwriter.write(doctree, destination)
  File "/usr/lib/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python2.7/site-packages/sphinx/writers/latex.py", line 114, in translate
    visitor = self.translator_class(self.document, self.builder)
  File "/usr/lib/python2.7/site-packages/sphinx/writers/latex.py", line 391, in __init__
    language=builder.config.language)
  File "/usr/lib/python2.7/site-packages/sphinx/util/i18n.py", line 220, in format_date
    formatter=function))
  File "/usr/lib/python2.7/site-packages/sphinx/util/i18n.py", line 169, in babel_format_date
    return formatter(date, format, locale=locale)
  File "/usr/lib/python2.7/site-packages/babel/dates.py", line 508, in format_datetime
    return parse_pattern(format).apply(datetime, locale)
  File "/usr/lib/python2.7/site-packages/babel/dates.py", line 702, in apply
    return self % DateTimeFormat(datetime, locale)
  File "/usr/lib/python2.7/site-packages/babel/dates.py", line 699, in __mod__
    return self.format % other
  File "/usr/lib/python2.7/site-packages/babel/dates.py", line 720, in __getitem__
    return self.format_year(char, num)
  File "/usr/lib/python2.7/site-packages/babel/dates.py", line 772, in format_year
    week = self.get_week_number(self.get_day_of_year())
  File "/usr/lib/python2.7/site-packages/babel/dates.py", line 863, in get_day_of_year
    return (date - date_(date.year, 1, 1)).days + 1
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'
```

**Comment by tk0miya** [comment]
It seems this bug is related with config variable: `today_fmt`.  Could you configure this variable?
If none, please tell me also `language` setting.

**Comment by vpoughon** [comment]
`today_fmt` and `language` were both unset. I set both to:

```
language = "en"
today_fmt = '%B %d, %Y'
```

and the exception still happens.

**Comment by vpoughon** [comment]
I'm using Sphinx (sphinx-build) 1.4.6 on CentOS 7, by the way.

**Comment by tk0miya** [comment]
What version of babel (python-babel) did you use?

**Comment by vpoughon** [comment]
```
Python 2.7.5 (default, Aug 18 2016, 15:58:25) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import babel
>>> babel.__version__
'2.3.4'
```

**Comment by tk0miya** [comment]
Really? Your stacktrace says error is raised at line 863 of `babel/dates.py`.

```
  File "/usr/lib/python2.7/site-packages/babel/dates.py", line 863, in get_day_of_year
    return (date - date_(date.year, 1, 1)).days + 1
```

But, in babel-2.3.4, the line 863 of `babel/dates.py` is a comment line. 
https://github.com/python-babel/babel/blob/2.3.4/babel/dates.py#L863

**Comment by vpoughon** [comment]
On my system line 863 of dates.py in /usr/lib/python2.7/site-packages/babel/dates.py is:

```
860     def get_day_of_year(self, date=None): 
861         if date is None: 
862             date = self.value
863         return (date - date_(date.year, 1, 1)).days + 1
```

for some reason

**Comment by tk0miya** [comment]
Since v1.0, babel allows datetime object to an argument of `get_day_of_year()`. It seems your babel package is older than 1.0. 
https://github.com/python-babel/babel/commit/920bb01c6bd84e2693aadb39effa24d3f4722e6f

Sphinx depends on babel-1.3 or later.
Please check your environment. Maybe, two babel packages are installed in your environment.

Thanks,
