### ISSUE TITLE
ext.autodoc fails on non-ascii python files

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#298]
I'm using sphinx's sphinx.ext.autodoc and it is failing on a python file with utf-8 characters in it.  The file in question is properly tagged with a "# -*- coding: utf-8" line at the top, as per the python documentation. The traceback I get from sphinx (when using pdb) follows. 

```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/cmdline.py", line 172, in main
    app.build(all_files, filenames)
  File "/usr/lib/python2.6/site-packages/sphinx/application.py", line 130, in build
    self.builder.build_update()
  File "/usr/lib/python2.6/site-packages/sphinx/builders/__init__.py", line 260, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python2.6/site-packages/sphinx/builders/__init__.py", line 285, in build
    purple, length):
  File "/usr/lib/python2.6/site-packages/sphinx/builders/__init__.py", line 131, in status_iterator
    for item in iterable:
  File "/usr/lib/python2.6/site-packages/sphinx/environment.py", line 513, in update_generator
    self.read_doc(docname, app=app)
  File "/usr/lib/python2.6/site-packages/sphinx/environment.py", line 607, in read_doc
    raise SphinxError(str(err))
SphinxError: 'ascii' codec can't decode byte 0xc3 in position 35: ordinal not in range(128)
> /usr/lib/python2.6/site-packages/sphinx/environment.py(607)read_doc()
-> raise SphinxError(str(err))
```

Using sphinx 0.6.3 on Arch Linux.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/298
- Originally reported by: Anonymous
- Originally created at: 2009-12-08T17:54:25.985

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-12-24 12:25:55+00:00_

I can't reproduce this with an example file here.  Could you attach the file, or any other file that causes this behavior?

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-08-25 12:02:30+00:00_

Closing due to lack of response.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2013-03-31 13:57:36+00:00_

Removing version: 0.6.3 (automated comment)
