### ISSUE TITLE
Latest sphinx version crashes with ImportError

### ISSUE THREAD

**Issue by untitaker** [sphinx-doc/sphinx#2996]
```
Traceback (most recent call last):
  File "/home/untitaker/venvs/vdirsyncer/bin/sphinx-build", line 11, in <module>
    sys.exit(main())
  File "/home/untitaker/venvs/vdirsyncer/lib/python3.5/site-packages/sphinx/__init__.py", line 51, in main
    sys.exit(build_main(argv))
  File "/home/untitaker/venvs/vdirsyncer/lib/python3.5/site-packages/sphinx/__init__.py", line 61, in build
_main
    from sphinx import cmdline
  File "/home/untitaker/venvs/vdirsyncer/lib/python3.5/site-packages/sphinx/cmdline.py", line 23, in <modul
e>
    from sphinx.application import Sphinx
  File "/home/untitaker/venvs/vdirsyncer/lib/python3.5/site-packages/sphinx/application.py", line 38, in <m
odule>
    from sphinx.environment import BuildEnvironment
  File "/home/untitaker/venvs/vdirsyncer/lib/python3.5/site-packages/sphinx/environment.py", line 38, in <m
odule>
    from sphinx.io import SphinxStandaloneReader, SphinxDummyWriter, SphinxFileInput
  File "/home/untitaker/venvs/vdirsyncer/lib/python3.5/site-packages/sphinx/io.py", line 16, in <module>
    from sphinx.transforms import ApplySourceWorkaround, ExtraTranslatableNodes, Locale, \
ImportError: cannot import name 'Locale'
```

This is version 1.4.7 uploaded one hour ago, installed from PyPI. Installing from git works fine.

**Comment by quentinus95** [comment]
Same issue here.

"Error: The utils module cannot be found. Did you install Sphinx and its dependencies correctly?"

**Comment by quentinus95** [comment]
Sphinx official website is describing the 1.4.8 as current version, maybe only the tag is missing on the repository ?

**Comment by tk0miya** [comment]
Sorry for inconvenience. It might be a bug of wheel package of Sphinx-1.4.7.
I will repackage it later. Please wait a while.

**Comment by tk0miya** [comment]
I just released new package as v1.4.8
Please try it out.
Sorry for inconvenience and Thank you for quick reporting.
Thanks,

**Comment by untitaker** [comment]
No problem, thanks for the quick response!

**Comment by quentinus95** [comment]
Thx !
