### ISSUE TITLE
image:: causes sphinx to raise TypeError: _warn_node() got an unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by Jenselme** [sphinx-doc/sphinx#2999]
While building the documentation for [this project](https://github.com/crossbario/txaio) with sphinx 1.4.8 (`cd docs && make html`) I get this output:

```
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.8
loading translations [en]... done
loading pickled environment... not yet created
loading intersphinx inventory from https://pythonhosted.org/six/objects.inv...
loading intersphinx inventory from http://docs.python.org/2/objects.inv...
intersphinx inventory has moved: http://docs.python.org/2/objects.inv -> https://docs.python.org/2/objects.inv
loading intersphinx inventory from http://docs.python.org/3/objects.inv...
intersphinx inventory has moved: http://docs.python.org/3/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 6 source files that are out of date
updating environment: 6 added, 0 changed, 0 removed
reading sources... [ 50%] index                                                                                                                                                                                    
Exception occurred:
  File "/home/jenselme/projects/forks/txaio/.venv/lib64/python3.5/site-packages/sphinx/environment.py", line 947, in process_images
    type='image', subtype='nonlocal_uri')
TypeError: _warn_node() got an unexpected keyword argument 'type'
The full traceback has been saved in /tmp/sphinx-err-wu3c48rh.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:55: recipe for target 'html' failed
make: *** [html] Error 1
```

It comes from the "image" links declared like:

```
.. |Version| image:: https://img.shields.io/pypi/v/txaio.svg
   :target: https://pypi.python.org/pypi/txaio
```

If I remove this link, the doc builds as expected.

Here is the full log:

```
# Sphinx version: 1.4.8
# Python version: 3.5.1 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   intersphinx inventory has moved: http://docs.python.org/2/objects.inv -> https://docs.python.org/2/objects.inv
#   loading intersphinx inventory from http://docs.python.org/3/objects.inv...
#   intersphinx inventory has moved: http://docs.python.org/3/objects.inv -> https://docs.python.org/3/objects.inv
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 6 source files that are out of date
#   updating environment:
#   6 added, 0 changed, 0 removed
#   reading sources... [ 16%] api
#   reading sources... [ 33%] contents
#   reading sources... [ 50%] index
# Loaded extensions:
#   alabaster (0.7.9) from /home/jenselme/projects/forks/txaio/.venv/lib64/python3.5/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.4.8) from /home/jenselme/projects/forks/txaio/.venv/lib64/python3.5/site-packages/sphinx/ext/autodoc.py
#   sphinx.ext.viewcode (1.4.8) from /home/jenselme/projects/forks/txaio/.venv/lib64/python3.5/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.intersphinx (1.4.8) from /home/jenselme/projects/forks/txaio/.venv/lib64/python3.5/site-packages/sphinx/ext/intersphinx.py
Traceback (most recent call last):
  File "/home/jenselme/projects/forks/txaio/.venv/lib64/python3.5/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/jenselme/projects/forks/txaio/.venv/lib64/python3.5/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/home/jenselme/projects/forks/txaio/.venv/lib64/python3.5/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/jenselme/projects/forks/txaio/.venv/lib64/python3.5/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/home/jenselme/projects/forks/txaio/.venv/lib64/python3.5/site-packages/sphinx/environment.py", line 569, in update
    self._read_serial(docnames, app)
  File "/home/jenselme/projects/forks/txaio/.venv/lib64/python3.5/site-packages/sphinx/environment.py", line 589, in _read_serial
    self.read_doc(docname, app)
  File "/home/jenselme/projects/forks/txaio/.venv/lib64/python3.5/site-packages/sphinx/environment.py", line 748, in read_doc
    self.process_images(docname, doctree)
  File "/home/jenselme/projects/forks/txaio/.venv/lib64/python3.5/site-packages/sphinx/environment.py", line 947, in process_images
    type='image', subtype='nonlocal_uri')
TypeError: _warn_node() got an unexpected keyword argument 'type'
```

**Comment by tk0miya** [comment]
It looks Sphinx.environment.warn_node is customized on your conf.py.
It's not a bug of Sphinx.
In detail, please refer #2429.

Thanks,

**Comment by Jenselme** [comment]
Thanks for the quick answer and the link to the solution.
