### ISSUE TITLE
toctree depth comparison - Sphinx 1.4.8 - Python 3.5

### ISSUE THREAD

**Issue by gitbenji** [sphinx-doc/sphinx#3011]
Received error when running:
`sphinx-build app/docs/source app/docs/build/html`

Here's the full traceback:

```
Traceback (most recent call last):
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/builders/html.py", line 454, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/builders/html.py", line 815, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/jinja2glue.py", line 160, in render
    return self.environment.get_template(template).render(context)
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/Users/benji/cuttlesoft/docs.cuttlesoft.com/app/docs/source/_themes/sphinx_rtd_theme/layout.html", line 123, in top-level template code
    {% block menu %}
  File "/Users/benji/cuttlesoft/docs.cuttlesoft.com/app/docs/source/_themes/sphinx_rtd_theme/layout.html", line 124, in block "menu"
    {% set toctree = toctree(maxdepth=theme_navigation_depth, collapse=theme_collapse_navigation, includehidden=True) %}
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/jinja2/sandbox.py", line 355, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/builders/html.py", line 805, in <lambda>
    ctx['toctree'] = lambda **kw: self._get_local_toctree(pagename, **kw)
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/builders/html.py", line 731, in _get_local_toctree
    docname, self, collapse, **kwds))['fragment']
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/environment.py", line 1234, in get_toctree_for
    prune=True, **kwds)
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/environment.py", line 1508, in resolve_toctree
    self._toctree_prune(newnode, 1, prune and maxdepth or 0, collapse)
  File "/Users/benji/.virtualenvs/docs/lib/python3.5/site-packages/sphinx/environment.py", line 1302, in _toctree_prune
    if maxdepth > 0 and depth > maxdepth:
TypeError: unorderable types: str() > int()
```

May have to do with Python3.5 and interpreting the input of maxdepth as a string?

**Comment by tk0miya** [comment]
The string formatted `maxdepth` comes from sphinx_rtd_theme. But sphinx expects the value is integer.

```
 File "/Users/benji/cuttlesoft/docs.cuttlesoft.com/app/docs/source/_themes/sphinx_rtd_theme/layout.html", line 124, in block "menu"
    {% set toctree = toctree(maxdepth=theme_navigation_depth, collapse=theme_collapse_navigation, includehidden=True) %}
```

I think this is a bug of sphinx_rtd_theme. And the `navigation_depth` option is not released, in develop feature. Please report this to their team.
