### ISSUE TITLE
application.Sphinx#_log fails in Python 3.x if the message causes UnicodeEncodeError

### ISSUE THREAD

**Issue by hhsprings** [sphinx-doc/sphinx#3024]
To reproduce is easy on Windows 7 (Japanese Edition):

```
$ cd sphinx/tests/roots/test-image-glob
$ # `test-image-glob` has `testimäge.png`
$ sphinx-build -b html -d build/doctrees . build/html
...
Exception occurred:
  File "c:\Python35\lib\site-packages\...\sphinx\application.py", line 364, in _log
    wfile.write(message.encode(encoding, 'replace'))
TypeError: write() argument must be str, not bytes
```

`_log` should be changed (maybe...):

``` python
    def _log(self, message, wfile, nonl=False):
        try:
            wfile.write(message)
        except UnicodeEncodeError:
            encoding = getattr(wfile, 'encoding', 'ascii') or 'ascii'
            wfile.write(message.encode(encoding, 'replace').decode(encoding))  # !!
```

Note: If you uses `colorama`, the error might occur in other location.

**Comment by hhsprings** [comment]
update:

``` python
    def _log(self, message, wfile, nonl=False):
        try:
            wfile.write(message)
        except UnicodeEncodeError:
            encoding = getattr(wfile, 'encoding', 'ascii') or 'ascii'
            message_b = message.encode(encoding, 'replace')
            try:
                wfile.write(message_b)
            except TypeError:  # expected Unicode
                wfile.write(message_b.decode(encoding))
```

**Comment by tk0miya** [comment]
I want to know why the first try has been failed.
Could you show me the full stacktrace?

**Comment by shimizukawa** [comment]
reproduced as:
```Python
>>> app.info('hello')
hello
>>> app.info('hello \u206d')
Traceback (most recent call last):
  File "C:\Users\taka\Anaconda3\lib\site-packages\Sphinx-1.4.6-py3.5.egg\sphinx\application.py", line 322, in _log
    wfile.write(message)
UnicodeEncodeError: 'cp932' codec can't encode character '\u206d' in position 6: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\taka\Anaconda3\lib\site-packages\Sphinx-1.4.6-py3.5.egg\sphinx\application.py", line 370, in info
    self._log(message, self._status, nonl)
  File "C:\Users\taka\Anaconda3\lib\site-packages\Sphinx-1.4.6-py3.5.egg\sphinx\application.py", line 325, in _log
    wfile.write(message.encode(encoding, 'replace'))
TypeError: write() argument must be str, not bytes
```

**Comment by shimizukawa** [comment]
fixed
