### ISSUE TITLE
TypeError: 'UserWarning' object is not subscriptable - label duplicate

### ISSUE THREAD

**Issue by DancingQuanta** [sphinx-doc/sphinx#3038]
f I tried to use same label for an equation in two different files, I will get an error as expected.
However I get two errors, the first about the label duplicate (UserWarning) and the second about the first error handing having TypeError bad syntax.

Here is the full traceback

```
Traceback (most recent call last):
  File "C:\Users\andre\Anaconda3\lib\site-packages\sphinx\ext\mathbase.py", line 204, in add_target
    eqno = domain.add_equation(env, env.docname, node['label'])
  File "C:\Users\andre\Anaconda3\lib\site-packages\sphinx\ext\mathbase.py", line 93, in add_equation
    raise UserWarning(msg)
UserWarning: duplicate label of equation specific-rotation, other instance in C:\Users\andre\Dropbox\bath-uni\course\contemporary\topics\chiral-materials\ellipticity.rst

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\andre\Anaconda3\lib\site-packages\sphinx\cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "C:\Users\andre\Anaconda3\lib\site-packages\sphinx\application.py", line 335, in build
    self.builder.build_update()
  File "C:\Users\andre\Anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "C:\Users\andre\Anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "C:\Users\andre\Anaconda3\lib\site-packages\sphinx\environment.py", line 548, in update
    self._read_serial(docnames, app)
  File "C:\Users\andre\Anaconda3\lib\site-packages\sphinx\environment.py", line 568, in _read_serial
    self.read_doc(docname, app)
  File "C:\Users\andre\Anaconda3\lib\site-packages\sphinx\environment.py", line 675, in read_doc
    pub.publish()
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\core.py", line 217, in publish
    self.settings)
  File "C:\Users\andre\Anaconda3\lib\site-packages\sphinx\io.py", line 55, in read
    self.parse()
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\parsers\rst\__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    input_source=document['source'])
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "C:\Users\andre\Anaconda3\lib\site-packages\docutils\parsers\rst\states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "C:\Users\andre\Anaconda3\lib\site-packages\sphinx\ext\mathbase.py", line 185, in run
    self.add_target(ret)
  File "C:\Users\andre\Anaconda3\lib\site-packages\sphinx\ext\mathbase.py", line 212, in add_target
    self.state_machine.reporter.warning(exc[0], line=self.lineno)
TypeError: 'UserWarning' object is not subscriptable
```

**Comment by tk0miya** [comment]
Fixed.
Thank you for reporting.
