### ISSUE TITLE
AttributeError: 'list' object has no attribute 'rfind' breaks build

### ISSUE THREAD

**Issue by jputrino** [sphinx-doc/sphinx#3050]
(moved from #1605)

When I run `sphinx-build docs/ docs/_build/`, I get the following error:

```
Exception occurred:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'list' object has no attribute 'rfind'
The full traceback has been saved in /var/folders/06/0gyp09193p5632bd177_g2pr0r1ztr/T/sphinx-err-pECbLt.log, if you want to report the issue to the developers.
```

I'm working on Mac OSX Yosemite. Full traceback is below and conf.py is attached. This has happened when I run both v1.4.8 and v1.4.5. Let me know if you need any of the other files. I can't provide access to the repo because it's a private project.

Thanks!

```
# Sphinx version: 1.4.5
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   /Users/putrino/velcro/docs/_includes/ref_config-parameters-virtual-server.rst:: WARNING: document isn't included in any toctree
#   /Users/putrino/velcro/docs/_includes/ref_prerequisites.rst:: WARNING: document isn't included in any toctree
#   /Users/putrino/velcro/docs/_includes/topic_config-example.rst:: WARNING: document isn't included in any toctree
#   /Users/putrino/velcro/docs/_includes/topic_configuration.rst:: WARNING: document isn't included in any toctree
#   /Users/putrino/velcro/docs/_includes/topic_features-all.rst:: WARNING: document isn't included in any toctree
#   /Users/putrino/velcro/docs/_includes/topic_statistics.rst:: WARNING: document isn't included in any toctree
#   /Users/putrino/velcro/docs/minimaps/map_features.rst:: WARNING: document isn't included in any toctree
#   /Users/putrino/velcro/docs/minimaps/map_middleware.rst:: WARNING: document isn't included in any toctree
#   done
#   preparing documents...
# Loaded extensions:
#   sphinx.ext.intersphinx (1.4.5) from /Library/Python/2.7/site-packages/sphinx/ext/intersphinx.pyc
#   sphinx.ext.autosectionlabel (unknown version) from /Library/Python/2.7/site-packages/sphinx/ext/autosectionlabel.pyc
#   sphinx.ext.ifconfig (1.4.5) from /Library/Python/2.7/site-packages/sphinx/ext/ifconfig.pyc
#   sphinx.ext.coverage (1.4.5) from /Library/Python/2.7/site-packages/sphinx/ext/coverage.pyc
#   sphinx.ext.todo (1.4.5) from /Library/Python/2.7/site-packages/sphinx/ext/todo.pyc
#   alabaster (0.7.9) from /Library/Python/2.7/site-packages/alabaster/__init__.pyc
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/Library/Python/2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/Library/Python/2.7/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Library/Python/2.7/site-packages/sphinx/builders/__init__.py", line 349, in write
    self.prepare_writing(docnames)
  File "/Library/Python/2.7/site-packages/sphinx/builders/html.py", line 302, in prepare_writing
    path.basename(self.config.html_logo) or ''
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'list' object has no attribute 'rfind'
/var/folders/06/0gyp09193p5632bd177_g2pr0r1ztr/T/sphinx-err-pECbLt.log (END)
```

[conf-py.txt](https://github.com/sphinx-doc/sphinx/files/527541/conf-py.txt)

**Comment by tk0miya** [comment]
It seems your `html_logo` setting is list value. But it expects a string value.
Please update your conf.py

```
# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#
html_logo = ['_static/f5-logo.png']
```

**Comment by jputrino** [comment]
thanks!
