### ISSUE TITLE
SQLAlchemy-1.1.3 make doc breaks 

### ISSUE THREAD

**Issue by Kadelka** [sphinx-doc/sphinx#3103]
Error in /tmp/sphinx-err-5lYSL9.log:
```
# Sphinx version: 1.4.6
# Python version: 2.7.12 (CPython)
# Docutils version: 0.11 release
# Jinja2 version: 2.7.1
# Last messages:
# /giga/install/python/SQLAlchemy-1.1.3/doc/build/orm/tutorial.rst:199: WARNING: term not in glossary: registry
# /giga/install/python/SQLAlchemy-1.1.3/doc/build/orm/tutorial.rst:1624: WARNING: term not in glossary: eager load
# /giga/install/python/SQLAlchemy-1.1.3/doc/build/orm/tutorial.rst:1624: WARNING: term not in glossary: query options
# /giga/install/python/SQLAlchemy-1.1.3/doc/build/orm/tutorial.rst:2187: WARNING: undefined label: query_api_toplevel (if the link has no caption the label must precede a section header)
# /giga/install/python/SQLAlchemy-1.1.3/doc/build/orm/versioning.rst:6: WARNING: term not in glossary: version id column
# /giga/install/python/SQLAlchemy-1.1.3/doc/build/orm/versioning.rst:31: WARNING: term not in glossary: repeatable read
# generating indices...
# genindex
# The name of the builder is: html
# The name of the builder is: html
# Loaded extensions:
# sphinx.ext.autodoc (1.4.6) from /usr/local/lib/python2.7/site-packages/Sphinx-1.4.6-py2.7.egg/sphinx/ext/autodoc.pyc
# sphinx.ext.intersphinx (1.4.6) from /usr/local/lib/python2.7/site-packages/Sphinx-1.4.6-py2.7.egg/sphinx/ext/intersphinx.pyc
# changelog (unknown version) from /usr/local/lib/python2.7/site-packages/changelog-0.3.4-py2.7.egg/changelog/**init**.pyc
# alabaster (0.7.7) from /usr/local/lib/python2.7/site-packages/alabaster-0.7.7-py2.7.egg/alabaster/**init**.pyc
# sphinx_paramlinks (unknown version) from /usr/local/lib/python2.7/site-packages/sphinx_paramlinks-0.2.2-py2.7.egg/sphinx_paramlinks/**init**.pyc
# zzzeeksphinx (unknown version) from /usr/local/lib/python2.7/site-packages/zzzeeksphinx-1.0.18-py2.7.egg/zzzeeksphinx/**init**.pyc

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.4.6-py2.7.egg/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.4.6-py2.7.egg/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.4.6-py2.7.egg/sphinx/builders/**init**.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.4.6-py2.7.egg/sphinx/builders/**init**.py", line 325, in build
    self.finish()
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.4.6-py2.7.egg/sphinx/builders/html.py", line 462, in finish
    self.finish_tasks.add_task(self.gen_indices)
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.4.6-py2.7.egg/sphinx/util/parallel.py", line 40, in add_task
    res = task_func()
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.4.6-py2.7.egg/sphinx/builders/html.py", line 478, in gen_indices
    self.write_genindex()
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.4.6-py2.7.egg/sphinx/builders/html.py", line 538, in write_genindex
    self.handle_page('genindex', genindexcontext, 'genindex.html')
  File "/usr/local/lib/python2.7/site-packages/Sphinx-1.4.6-py2.7.egg/sphinx/builders/html.py", line 803, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/usr/local/lib/python2.7/site-packages/zzzeeksphinx-1.0.18-py2.7.egg/zzzeeksphinx/mako.py", line 78, in render
    return self.lookup.get_template(template).render_unicode(*_context)
  File "/usr/local/lib/python2.7/site-packages/Mako-0.9.1-py2.7.egg/mako/template.py", line 452, in render_unicode
    as_unicode=True)
  File "/usr/local/lib/python2.7/site-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 807, in _render
    *__kwargs_for_callable(callable_, data))
  File "/usr/local/lib/python2.7/site-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 839, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/site-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 865, in _exec_template
    callable_(context, _args, *_kwargs)
  File "static_base_mako", line 74, in render_body
  File "layout_mako", line 312, in render_body
  File "genindex_mako", line 96, in render_body
ValueError: too many values to unpack
```

**Comment by tk0miya** [comment]
It seems zzzeeksphinx or Mako raises the error.
Anyway this is not a bug of Sphinx.

**Comment by ptomato** [comment]
This error is caused by zzzeeksphinx and seems to be fixed by the unreleased commit https://bitbucket.org/zzzeek/zzzeeksphinx/commits/63dd24ed8cb74ec742f387d444fd3abff19181b8. Debian has included this fix in their packaged version of zzzeeksphinx 1.0.18.
