### ISSUE TITLE
CI raises error with nightly builds

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#3111]
CI raises error with nightly builds:
```
$ python --version
Python 3.7.0a0
...
======================================================================
FAIL: test_autodoc.test_type_hints
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/sphinx-doc/sphinx/tests/test_autodoc.py", line 1095, in test_type_hints
    verify_arg_spec(f8, '(x: typing.Callable[[int, str], int]) -> None')
  File "/home/travis/build/sphinx-doc/sphinx/tests/test_autodoc.py", line 1066, in verify_arg_spec
    eq_(formatargspec(f, *getargspec(f)), expected)
AssertionError: '(x: typing.Callable[int, str, int]) -> None' != '(x: typing.Callable[[int, str], int]) -> None'
>>  raise AssertionError(None or "%r != %r" % ('(x: typing.Callable[int, str, int]) -> None', '(x: typing.Callable[[int, str], int]) -> None'))
```

**Comment by tk0miya** [comment]
The target function is defined as following:

```
def f8(x: Callable[[int, str], int]) -> None:
    # See https://github.com/ambv/typehinting/issues/149 for Callable[..., int]
    pass
```

It seems nightly python returns invalid result. I believe this is a bug of py36.

**Comment by tk0miya** [comment]
In my short investigation:

I execute following script in py3.5.2 and py3.6b3

```
import inspect
from typing import Callable

func = Callable[[int, str], int]
print('typing:', func)
print('args:', func.__args__)
```

```
$ python3.5 foo.py
typing: typing.Callable[[int, str], int]
args: (<class 'int'>, <class 'str'>)

$ python3.6 foo.py
typing: typing.Callable[[int, str], int]
args: (<class 'int'>, <class 'str'>, <class 'int'>)
```

It seems the `typing.Callable.__args__` contains not only arguments but also return-value.
I don't know this is an intended changes or not. But I can't find collect way to obtain the arguments only.

**Comment by shimizukawa** [comment]
This is the cause. I think it is intended.
https://github.com/python/typing/pull/308
