### ISSUE TITLE
Some tests failed with py27

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#3114]
At master branch, I got following errors since a5bdf1fdae99869e3e0e6beab532d62b1df19a3e
```
$ make test
Checking dependencies...
Temporary files will be placed in /Users/tkomiya/work/sphinx/tests/build.
Running Sphinx test suite (with Python 2.7.12)...
...........................E............................................FFF..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F..........................................................................................................................................................................................................................................................................S...................................................................
======================================================================
ERROR: Failure: ImportError (No module named enum)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/USERS/TKOMIYA/WORK/SPHINX/.TOX/PY27/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/USERS/TKOMIYA/WORK/SPHINX/.TOX/PY27/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/USERS/TKOMIYA/WORK/SPHINX/.TOX/PY27/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/tkomiya/work/sphinx/tests/test_autodoc.py", line 17, in <module>
    import enum
ImportError: No module named enum

======================================================================
FAIL: test_build_html.test_html_output(<Element u'html' at 109ce0610>, 'autodoc.html', ".//dt[@id='test_autodoc.Class']", '')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/USERS/TKOMIYA/WORK/SPHINX/.TOX/PY27/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/tkomiya/work/sphinx/tests/test_build_html.py", line 341, in check_xpath
    '%r in file %s' % (path, fname))
AssertionError: did not find any node matching xpath ".//dt[@id='test_autodoc.Class']" in file autodoc.html


======================================================================
FAIL: test_build_html.test_html_output(<Element u'html' at 109ce0610>, 'autodoc.html', ".//dt[@id='test_autodoc.function']/em", '\\*\\*kwds')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/USERS/TKOMIYA/WORK/SPHINX/.TOX/PY27/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/tkomiya/work/sphinx/tests/test_build_html.py", line 341, in check_xpath
    '%r in file %s' % (path, fname))
AssertionError: did not find any node matching xpath ".//dt[@id='test_autodoc.function']/em" in file autodoc.html


======================================================================
FAIL: test_build_html.test_html_output(<Element u'html' at 109ce0610>, 'autodoc.html', './/dd/p', 'Return spam\\.')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/USERS/TKOMIYA/WORK/SPHINX/.TOX/PY27/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/tkomiya/work/sphinx/tests/test_build_html.py", line 369, in check_xpath
    [node.text for node in nodes]))
AssertionError: 'Return spam\\.' not found in any node matching path .//dd/p in autodoc.html: [u'small markup error which should have\ncorrect location information.']


======================================================================
FAIL: test_ext_coverage.test_build
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/USERS/TKOMIYA/WORK/SPHINX/.TOX/PY27/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/tkomiya/work/sphinx/tests/util.py", line 271, in deco
    func(app, status, warning, *args2, **kwargs2)
  File "/Users/tkomiya/work/sphinx/tests/test_ext_coverage.py", line 24, in test_build
    assert 'test_autodoc\n------------\n' in py_undoc
AssertionError:
>>  assert 'test_autodoc\n------------\n' in <python.txt contents>
    assert ' * Class -- missing methods:\n' in <python.txt contents>
    assert ' * process_docstring\n' in <python.txt contents>


----------------------------------------------------------------------
Ran 972 tests in 987.597s

FAILED (SKIP=1, errors=1, failures=4)
make: *** [test] Error 1
```

But it seems Travis CI does not get same errors.
@shimizukawa Do you know such a case?

**Comment by tk0miya** [comment]
As a trial, I installed `enum34` package. It resolves the problem.
It seems test requirements are needed.
