### ISSUE TITLE
Error in parsing.py

### ISSUE THREAD

**Issue by Ben2022** [sphinx-doc/sphinx#3139]
Hello, 

I am trying to run Sphinx but I get the following error:

```
Exception occurred:
  File "/home/bco/anaconda3/lib/python3.5/site-packages/sphinxcontrib/doxylink/parsing.py", line 116, in normalise
    argument_string_list.append(''.join((arg.qualifier,' ')))
TypeError: sequence item 0: expected str instance, ParseResults found `
```
Do you have any idea about how to solve this please?

Here is the log content:
```
Sphinx version: 1.4.6
Python version: 3.5.2 (CPython)
Docutils version: 0.12 release
Jinja2 version: 2.8
Last messages:

Loaded extensions:
Traceback (most recent call last):
  File "/home/bco/anaconda3/lib/python3.5/site-packages/Sphinx-1.4.6-py3.5.egg/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/bco/anaconda3/lib/python3.5/site-packages/Sphinx-1.4.6-py3.5.egg/sphinx/application.py", line 204, in __init__
    self._init_builder(self.buildername)
  File "/home/bco/anaconda3/lib/python3.5/site-packages/Sphinx-1.4.6-py3.5.egg/sphinx/application.py", line 279, in _init_builder
    self.emit('builder-inited')
  File "/home/bco/anaconda3/lib/python3.5/site-packages/Sphinx-1.4.6-py3.5.egg/sphinx/application.py", line 551, in emit
    results.append(callback(self, *args))
  File "/home/bco/anaconda3/lib/python3.5/site-packages/sphinxcontrib/doxylink/doxylink.py", line 448, in setup_doxylink_roles
    app.add_role(name, create_role(app, tag_filename, rootdir))
  File "/home/bco/anaconda3/lib/python3.5/site-packages/sphinxcontrib/doxylink/doxylink.py", line 390, in create_role
    mapping = parse_tag_file(tag_file)
  File "/home/bco/anaconda3/lib/python3.5/site-packages/sphinxcontrib/doxylink/doxylink.py", line 153, in parse_tag_file
    for old_tuple, normalised_tuple in zip(function_list, map(normalise, (member_tuple[1] for member_tuple in function_list))):
  File "/home/bco/anaconda3/lib/python3.5/site-packages/sphinxcontrib/doxylink/parsing.py", line 116, in normalise
    argument_string_list.append(''.join((arg.qualifier,' ')))
TypeError: sequence item 0: expected str instance, ParseResults found'
```
Thanks!

**Comment by tk0miya** [comment]
Thank you for reporting.
But it seems the error comes from `sphinxcontrib.doxylink`.

```
  File "/home/bco/anaconda3/lib/python3.5/site-packages/sphinxcontrib/doxylink/parsing.py", line 116, in normalise
    argument_string_list.append(''.join((arg.qualifier,' ')))
```

So could you report this to their project?
Thanks,

**Comment by victorpaleologue** [comment]
It is currently reported there, in their project: https://bitbucket.org/birkenfeld/sphinx-contrib/issues/172/doxylink-typeerror-sequence-item-0
