### ISSUE TITLE
Encountered unknown tag 'extrahead'

### ISSUE THREAD

**Issue by Blendify** [sphinx-doc/sphinx#3186]
For some reason 'extrahead' is not working for me.

Add this to layout.html:

```
{% extends "!layout.html" %}
{% extrahead %}
{{ super() }}

<script type="text/javascript" src="myfile.js" ></script>

{% endblock %}
```
Here is the full trace back:
```
# Sphinx version: 1.4.9
# Python version: 3.5.2 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  0%] about/contribute/build/index
# Loaded extensions:
#   vimeo (unknown version) from C:\Users\Aaron\BlenderDev\bf_manual\trunk\blender_docs\exts\vimeo.py
#   alabaster (0.7.9) from c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\alabaster\__init__.py
#   youtube (unknown version) from C:\Users\Aaron\BlenderDev\bf_manual\trunk\blender_docs\exts\youtube.py
#   sphinx.ext.intersphinx (1.4.9) from c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\sphinx\ext\intersphinx.py
#   sphinx.ext.mathjax (1.4.9) from c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\sphinx\ext\mathjax.py
Traceback (most recent call last):
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\sphinx\cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\sphinx\application.py", line 297, in build
    self.builder.build_update()
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\sphinx\builders\__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\sphinx\builders\__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\sphinx\builders\__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\sphinx\builders\__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\sphinx\builders\html.py", line 454, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\sphinx\builders\html.py", line 815, in handle_page
    output = self.templates.render(templatename, ctx)
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\sphinx\jinja2glue.py", line 160, in render
    return self.environment.get_template(template).render(context)
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Aaron\BlenderDev\bf_manual\trunk\blender_docs\manual\../resources/templates\layout.html", line 3, in template
    {% extrahead %}
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\jinja2\environment.py", line 986, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\sphinx\themes\basic\page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Aaron\BlenderDev\bf_manual\trunk\blender_docs\manual\../resources/templates\layout.html", line 3, in template
    {% extrahead %}
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\jinja2\environment.py", line 470, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\jinja2\parser.py", line 897, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\jinja2\parser.py", line 879, in subparse
    rv = self.parse_statement()
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\jinja2\parser.py", line 135, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\jinja2\parser.py", line 88, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\jinja2\parser.py", line 81, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "c:\users\aaron\appdata\local\programs\python\python35\lib\site-packages\jinja2\parser.py", line 50, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'extrahead'.

```

**Comment by tk0miya** [comment]
What about `{% block extrahead %}`?
The `extrahead` is a block.

Thanks,

**Comment by Blendify** [comment]
Yes that fixed the issue. Thanks
