### ISSUE TITLE
ContextualVersionConflict: (pyOpenSSL 0.13.1 (/usr/lib64/python2.7/site-packages), Requirement.parse('pyOpenSSL>=0.14; extra == "security"'), set(['requests']))

### ISSUE THREAD

**Issue by johnklee** [sphinx-doc/sphinx#3205]
```
# Sphinx version: 1.5
# Python version: 2.7.5 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib64/python2.7/site-packages/sphinx/application.py", line 189, in __init__
    self.setup_extension(extension)
  File "/usr/lib64/python2.7/site-packages/sphinx/application.py", line 512, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/usr/lib64/python2.7/site-packages/sphinx/builders/linkcheck.py", line 35, in <module>
    from sphinx.util import encode_uri, requests
  File "/usr/lib64/python2.7/site-packages/sphinx/util/requests.py", line 24, in <module>
    pkg_resources.require(['requests[security]'])
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (pyOpenSSL 0.13.1 (/usr/lib64/python2.7/site-packages), Requirement.parse('pyOpenSSL>=0.14; extra == "security"'), set(['requests']))
```

**Comment by shimizukawa** [comment]
Sorry for your inconvenience. As a workaround, please install requests with security option:
```
$ pip install requests[security]
```

**Comment by tk0miya** [comment]
@johnklee Could you try #3218? I think it would fix your problem. But I could not test it because I could not prepare the environment having old pyOpenSSL.
It would be nice if you could confirm the PR.

Thanks,

**Comment by tk0miya** [comment]
Now #3218 is merged.
Thank you for reporting.
