### ISSUE TITLE
[docutils] assert not self.context

### ISSUE THREAD

**Issue by SylvainCorlay** [sphinx-doc/sphinx#3219]
Similar to #3212 . Opening a separate issue as per @tk0miya's comment.

I am seeing the following traceback when building on RTD: (although unable to reproduce locally).
Forcing docutils < 0.13.1 does not seem to help.

https://readthedocs.org/projects/ipywidgets/builds/4771583/

```
Running Sphinx v1.5
making output directory...
loading translations [en]... done
loading pickled environment... not yet created
loading intersphinx inventory from https://nbformat.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://nbconvert.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from http://ipython.org/ipython-doc/dev/objects.inv...
loading intersphinx inventory from https://jupyter.readthedocs.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 26 source files that are out of date
updating environment: 26 added, 0 changed, 0 removed
reading sources... [  3%] changelog
reading sources... [  7%] contributing
reading sources... [ 11%] dev_docs
reading sources... [ 15%] dev_install
reading sources... [ 19%] dev_release
reading sources... [ 23%] dev_testing
reading sources... [ 26%] embedding
reading sources... [ 30%] examples
reading sources... [ 34%] examples/Beat Frequencies
reading sources... [ 38%] examples/Controller
reading sources... [ 42%] examples/Exploring Graphs
reading sources... [ 46%] examples/Export As (nbconvert)
reading sources... [ 50%] examples/Factoring
reading sources... [ 53%] examples/File Upload Widget
reading sources... [ 57%] examples/Lorenz Differential Equations
reading sources... [ 61%] examples/Using Interact
reading sources... [ 65%] examples/Variable Inspector
reading sources... [ 69%] examples/Widget Alignment
reading sources... [ 73%] examples/Widget Basics
reading sources... [ 76%] examples/Widget Custom
reading sources... [ 80%] examples/Widget Events
reading sources... [ 84%] examples/Widget List
reading sources... [ 88%] examples/Widget Low Level
reading sources... [ 92%] examples/Widget Styling
reading sources... [ 96%] index
reading sources... [100%] user_install

/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/Widget Basics.ipynb:38: WARNING: Inline strong start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/Widget Basics.ipynb:38: WARNING: Line block ends without a blank line.
/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/Widget Custom.ipynb:29: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/Widget Styling.ipynb:364: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/Widget Styling.ipynb:449: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/Widget Styling.ipynb:496: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/Widget Styling.ipynb:524: ERROR: Duplicate substitution definition name: "Items".
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples.md:: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/Beat Frequencies.ipynb:: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/Controller.ipynb:: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/Exploring Graphs.ipynb:: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/Export As (nbconvert).ipynb:: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/Factoring.ipynb:: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/File Upload Widget.ipynb:: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/Lorenz Differential Equations.ipynb:: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/checkouts/latest/docs/source/examples/Variable Inspector.ipynb:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [  3%] changelog
writing output... [  7%] contributing
writing output... [ 11%] dev_docs
writing output... [ 15%] dev_install
writing output... [ 19%] dev_release
writing output... [ 23%] dev_testing
writing output... [ 26%] embedding
writing output... [ 30%] examples
writing output... [ 34%] examples/Beat Frequencies
writing output... [ 38%] examples/Controller
writing output... [ 42%] examples/Exploring Graphs
writing output... [ 46%] examples/Export As (nbconvert)
writing output... [ 50%] examples/Factoring
writing output... [ 53%] examples/File Upload Widget
writing output... [ 57%] examples/Lorenz Differential Equations
writing output... [ 61%] examples/Using Interact
writing output... [ 65%] examples/Variable Inspector
writing output... [ 69%] examples/Widget Alignment
writing output... [ 73%] examples/Widget Basics
writing output... [ 76%] examples/Widget Custom
writing output... [ 80%] examples/Widget Events
writing output... [ 84%] examples/Widget List
writing output... [ 88%] examples/Widget Low Level

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/conda/latest/lib/python3.5/site-packages/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/conda/latest/lib/python3.5/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/conda/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/conda/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/conda/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/conda/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/conda/latest/lib/python3.5/site-packages/sphinx/builders/html.py", line 452, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/conda/latest/lib/python3.5/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/conda/latest/lib/python3.5/site-packages/sphinx/writers/html.py", line 48, in translate
    self.document.walkabout(visitor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/conda/latest/lib/python3.5/site-packages/docutils/nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/conda/latest/lib/python3.5/site-packages/docutils/nodes.py", line 1895, in dispatch_departure
    return method(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/conda/latest/lib/python3.5/site-packages/docutils/writers/_html_base.py", line 671, in depart_document
    assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 9

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipywidgets/conda/latest/lib/python3.5/site-packages/docutils/writers/_html_base.py", line 671, in depart_document
    assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 9
The full traceback has been saved in /tmp/sphinx-err-ctagu81t.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by SylvainCorlay** [comment]
Closing as per new comment by  @tk0miya in other issue.
