### ISSUE TITLE
SVG image causes a crash with docutils 0.13

### ISSUE THREAD

**Issue by jasaarim** [sphinx-doc/sphinx#3240]
Subject: SVG image causes a crash with docutils 0.13

# Problem

`.. image::` directive with an svg image crashes `sphinx-build` with the newest docutils.

## Procedure to reproduce the problem
```
sphinx-build -v -E -C -D master_doc=doc  . _build/html
```
`doc.rst` being a document containing a line `.. image:: image.svg` and `image.svg` existing in the current working directory.

## Error logs / results
```
Traceback (most recent call last):
  File "/src/venv/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/src/venv/lib/python2.7/site-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/src/venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/src/venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/src/venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/src/venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/src/venv/lib/python2.7/site-packages/sphinx/builders/html.py", line 446, in write_doc
    self.docwriter.write(doctree, destination)
  File "/src/sandbox/code/trunk/docutils/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/src/venv/lib/python2.7/site-packages/sphinx/writers/html.py", line 47, in translate
    self.document.walkabout(visitor)
  File "/src/sandbox/code/trunk/docutils/docutils/nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "/src/sandbox/code/trunk/docutils/docutils/nodes.py", line 1895, in dispatch_departure
    return method(node)
  File "/src/sandbox/code/trunk/docutils/docutils/writers/html4css1/__init__.py", line 783, in depart_document
    assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 1
```

## Expected results
Not crashing.

# Environment info
- OS: Linux 4.8.12-100, Fedora 23
- Python version: 2.7 and 3.5
- Sphinx version: 1.4.1

# Extra information

Docutils svn commit 7799 (2015-02-23) seems to have caused this. The gist of the commit message: "Wrap SVG images in `<img>` tags not `<object>`."

**Comment by tk0miya** [comment]
It was fixed at #3212 and Sphinx-1.5.1.
Please upgrade to newest Sphnx.

Thanks,
