### ISSUE TITLE
Error building the docs

### ISSUE THREAD

**Issue by shibasisp** [sphinx-doc/sphinx#3249]
Subject: <what happen when you do on which document project> Error Building the docs.
# Problem
- Trying to build the [scipy-lecture-notes](https://github.com/scipy-lectures/scipy-lecture-notes) , I got the following error. Any help is appreciated! 
## Procedure to reproduce the problem
```
shibasisp$  make html
mkdir -p build/html build/doctrees
# This line makes the build a bit more lengthy, and the
# the embedding of images more robust
rm -rf build/html/_images
sphinx-build -b html -d build/doctrees -D latex_paper_size=a4  . build/html
Running Sphinx v1.5

Exception occurred:
  File "/home/shibasisp/.local/lib/python3.5/site-packages/sphinx/application.py", line 512, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/media/shibasisp/New Volume/Github/scipy-lecture-notes/sphinxext/plot_directive.py", line 62
    raise OSError, 'Target does not exist: '+target
                 ^
SyntaxError: invalid syntax
The full traceback has been saved in /tmp/sphinx-err-9ycclx2w.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:48: recipe for target 'html' failed
make: *** [html] Error 1

```

## Error logs / results
```
# Sphinx version: 1.5
# Python version: 3.5.1 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/shibasisp/.local/lib/python3.5/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/shibasisp/.local/lib/python3.5/site-packages/sphinx/application.py", line 199, in __init__
    self.setup_extension(extension)
  File "/home/shibasisp/.local/lib/python3.5/site-packages/sphinx/application.py", line 512, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/media/shibasisp/New Volume/Github/scipy-lecture-notes/sphinxext/plot_directive.py", line 62
    raise OSError, 'Target does not exist: '+target
                 ^
SyntaxError: invalid syntax

```

# Environment info
- OS: <Unix/Linux/Mac/Win/other with version> Ubuntu 16.04.1 LTS
- Python version:3.5.1(Anaconda 3.5)
- Sphinx version:1.5

**Comment by tk0miya** [comment]
The error came from the extension provided by scipy-lecture-notes. So please report this to the project.
```
  File "/media/shibasisp/New Volume/Github/scipy-lecture-notes/sphinxext/plot_directive.py", line 62
    raise OSError, 'Target does not exist: '+target
                 ^
SyntaxError: invalid syntax
```

As a quick look, it seems the extension does not support python 3.
