### ISSUE TITLE
Django docs: make html: AssertionError: len(context) = 1

### ISSUE THREAD

**Issue by qurczak** [sphinx-doc/sphinx#3260]
### Problem

Executing command 'make html' in Django repository in 'docs' directory on branch 'master' revision 'e2112a5e1af001449f0d1c183261369f00e93195' generate an exception.

#### Procedure to reproduce the problem
```
> ~/PycharmProjects/django/docs$ make html
sphinx-build -b djangohtml -n -d _build/doctrees -D language=   . _build/html
Running Sphinx v1.5
A Translator for the djangohtml builder is changed.
A Translator for the json builder is changed.
loading translations []... not available for built-in messages
loading pickled environment... failed: build environment version not current
loading intersphinx inventory from https://pythonhosted.org/six/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://django-formtools.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from http://sphinx-doc.org/objects.inv...
intersphinx inventory has moved: http://sphinx-doc.org/objects.inv -> http://www.sphinx-doc.org/en/1.5.1/objects.inv
loading intersphinx inventory from http://initd.org/psycopg/docs/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [djangohtml]: targets for 380 source files that are out of date
updating environment: 380 added, 0 changed, 0 removed
reading sources... [100%] topics/testing/tools                                                                                                                               
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 11%] internals/contributing/triaging-tickets                                                                                                             
Exception occurred:
  File "/usr/lib/python3.5/site-packages/docutils/writers/_html_base.py", line 671, in depart_document
    assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 1
```

#### Error logs / results
```

# Sphinx version: 1.5
# Python version: 3.5.2 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.8
# Last messages:
#   writing output... [  8%] howto/upgrade-version
#   writing output... [  9%] howto/windows
#   writing output... [  9%] howto/writing-migrations
#   writing output... [  9%] index
#   writing output... [ 10%] internals/contributing/bugs-and-features
#   writing output... [ 10%] internals/contributing/committing-code
#   writing output... [ 10%] internals/contributing/index
#   writing output... [ 10%] internals/contributing/localizing
#   writing output... [ 11%] internals/contributing/new-contributors
#   writing output... [ 11%] internals/contributing/triaging-tickets
# Loaded extensions:
#   sphinx.ext.intersphinx (1.5) from /usr/lib/python3.5/site-packages/sphinx/ext/intersphinx.py
#   sphinx.builders.qthelp (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/qthelp.py
#   sphinx.builders.linkcheck (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/linkcheck.py
#   sphinx.domains.c (unknown version) from /usr/lib/python3.5/site-packages/sphinx/domains/c.py
#   sphinx.builders.applehelp (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/applehelp.py
#   sphinx.builders.htmlhelp (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/htmlhelp.py
#   alabaster (0.7.9) from /usr/lib/python3.5/site-packages/alabaster/__init__.py
#   sphinx.builders.dummy (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/dummy.py
#   sphinx.builders.gettext (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/gettext.py
#   sphinx.roles (unknown version) from /usr/lib/python3.5/site-packages/sphinx/roles.py
#   sphinx.builders.epub (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/epub.py
#   sphinx.domains.javascript (unknown version) from /usr/lib/python3.5/site-packages/sphinx/domains/javascript.py
#   sphinx.builders.epub3 (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/epub3.py
#   sphinx.builders.websupport (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/websupport.py
#   sphinx.directives.patches (unknown version) from /usr/lib/python3.5/site-packages/sphinx/directives/patches.py
#   sphinx.directives.code (unknown version) from /usr/lib/python3.5/site-packages/sphinx/directives/code.py
#   sphinx.builders.devhelp (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/devhelp.py
#   sphinx.builders.changes (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/changes.py
#   sphinx.directives (unknown version) from /usr/lib/python3.5/site-packages/sphinx/directives/__init__.py
#   sphinx.builders.xml (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/xml.py
#   sphinx.domains.rst (unknown version) from /usr/lib/python3.5/site-packages/sphinx/domains/rst.py
#   ticket_role (unknown version) from /home/qurczak/PycharmProjects/django/docs/_ext/ticket_role.py
#   sphinx.builders.manpage (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/manpage.py
#   djangodocs (unknown version) from /home/qurczak/PycharmProjects/django/docs/_ext/djangodocs.py
#   sphinx.domains.python (unknown version) from /usr/lib/python3.5/site-packages/sphinx/domains/python.py
#   cve_role (unknown version) from /home/qurczak/PycharmProjects/django/docs/_ext/cve_role.py
#   sphinx.builders.text (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/text.py
#   sphinx.builders.html (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/html.py
#   sphinx.builders.texinfo (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/texinfo.py
#   sphinx.builders.latex (unknown version) from /usr/lib/python3.5/site-packages/sphinx/builders/latex.py
#   sphinx.directives.other (unknown version) from /usr/lib/python3.5/site-packages/sphinx/directives/other.py
#   sphinx.ext.viewcode (1.5) from /usr/lib/python3.5/site-packages/sphinx/ext/viewcode.py
#   sphinx.domains.cpp (unknown version) from /usr/lib/python3.5/site-packages/sphinx/domains/cpp.py
#   sphinx.domains.std (unknown version) from /usr/lib/python3.5/site-packages/sphinx/domains/std.py
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python3.5/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/usr/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/usr/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/lib/python3.5/site-packages/sphinx/builders/html.py", line 452, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/lib/python3.5/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python3.5/site-packages/sphinx/writers/html.py", line 48, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 1895, in dispatch_departure
    return method(node)
  File "/usr/lib/python3.5/site-packages/docutils/writers/_html_base.py", line 671, in depart_document
    assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 1
```

### Environment info
- OS: Linux
- Python version: 3.5.2
- Sphinx version: 1.5-1
- Django: master https://github.com/django/django/commit/e2112a5e1af001449f0d1c183261369f00e93195

**Comment by tk0miya** [comment]
Thank you for reporting, but it was already reported at #3203 .
As a result, it is a bug of sphinx_rtd_theme.
