### ISSUE TITLE
Adding image of svg type results in a "AssertionError: len(context) = 1"

### ISSUE THREAD

**Issue by cajomferro** [sphinx-doc/sphinx#3266]
Adding image of svg type results in a "AssertionError: len(context) = 1"

### Problem
I added a svg image to my project. I can successfully build it on my machine but when building on the RTD an exception is raise: "AssertionError: len(context) = 1"

#### Procedure to reproduce the problem
This was the line creating the problem:

```
.. image:: _images/model_window_inheritance.svg
```

#### Error logs / results
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycontrol-gui/conda/latest/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycontrol-gui/conda/latest/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/application.py", line 266, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycontrol-gui/conda/latest/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycontrol-gui/conda/latest/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycontrol-gui/conda/latest/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycontrol-gui/conda/latest/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycontrol-gui/conda/latest/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/builders/html.py", line 439, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycontrol-gui/conda/latest/lib/python3.5/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycontrol-gui/conda/latest/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/writers/html.py", line 53, in translate
    self.document.walkabout(visitor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycontrol-gui/conda/latest/lib/python3.5/site-packages/docutils/nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycontrol-gui/conda/latest/lib/python3.5/site-packages/docutils/nodes.py", line 1895, in dispatch_departure
    return method(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycontrol-gui/conda/latest/lib/python3.5/site-packages/docutils/writers/_html_base.py", line 671, in depart_document
    assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 1

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pycontrol-gui/conda/latest/lib/python3.5/site-packages/docutils/writers/_html_base.py", line 671, in depart_document
    assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 1
```

### Environment info
- Python version: 3.5 (using conda)
- Sphinx version: 1.3.5-py35_0
- sphinx_rtd_theme: 0.1.7-py35_0 (tried with other versions as well)

**Comment by tk0miya** [comment]
It was fixed at #3212 and Sphinx-1.5.1.
Please upgrade to newest Sphnx.

Thanks,
