### ISSUE TITLE
specify correct requests version in requirements

### ISSUE THREAD

**Issue by akhmerov** [sphinx-doc/sphinx#3268]
Subject: sphinx fails when running linkcheck on using an old requests version

### Problem
- if a sufficiently old version of `requests` is installed, installing `sphinx` via `pip` will result in a broken `linkcheck`.

#### Procedure to reproduce the problem
```
pip3 install requests==2.4.3
pip3 install sphinx
python3 -c 'import sphinx.builders.linkcheck' 
```

#### Error logs / results
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/sphinx/builders/linkcheck.py", line 35, in <module>
    from sphinx.util import encode_uri, requests
  File "/usr/local/lib/python3.4/dist-packages/sphinx/util/requests.py", line 20, in <module>
    from requests.packages.urllib3.exceptions import SSLError, InsecureRequestWarning
ImportError: cannot import name 'SSLError'
```

#### Expected results
`pip3 install sphinx` should also install the correct version of `requests` (updating `requests` to the current version fixes the import error).

### Environment info
- OS: debian:jessie
- Python version: 3.4
- Sphinx version: 1.5.1 (not fixed on master neither)

**Comment by tk0miya** [comment]
It's a bit strange. requests-2.4.3 has `requests.packages.urllib3.exceptions:SSLError`.
https://github.com/kennethreitz/requests/blob/v2.4.0/requests/packages/urllib3/exceptions.py#L36

**Comment by akhmerov** [comment]
Yes, it is strange: `SSLError` is there, but one cannot import it. That problem should be trivial to fix as well, but I think it is also important to specify the required version.

**Comment by tk0miya** [comment]
Sorry for late response.
To add required version of requests package is easy.
But, I this that does not help your case. Because you'd already installed newer version than required one.

To investigate the environment, could you run following commands?
```
$ python3 -c 'import sphinx.builders.linkcheck' 
$ python3 -c 'from requests.packages.urllib3.exceptions import SSLError'
$ python3 -c 'import requests; print(requests.__version__)' 
```

**Comment by akhmerov** [comment]
It is as I said above.
```bash
sudo docker run -it --rm debian:jessie bash
root@8ef6461594b2:/# apt-get update > /dev/null 
root@8ef6461594b2:/# apt-get install -y python3-pip > /dev/null
debconf: delaying package configuration, since apt-utils is not installed
root@8ef6461594b2:/# pip3 install sphinx
Downloading/unpacking sphinx
  Downloading Sphinx-1.5.1-py2.py3-none-any.whl (1.6MB): 1.6MB downloaded
Downloading/unpacking Pygments>=2.0 (from sphinx)
  Downloading Pygments-2.1.3-py2.py3-none-any.whl (755kB): 755kB downloaded
Downloading/unpacking babel>=1.3,!=2.0 (from sphinx)
  Downloading Babel-2.3.4-py2.py3-none-any.whl (7.1MB): 7.1MB downloaded
Downloading/unpacking docutils>=0.11 (from sphinx)
  Downloading docutils-0.13.1-py3-none-any.whl (536kB): 536kB downloaded
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/lib/python3/dist-packages (from sphinx)
Downloading/unpacking imagesize (from sphinx)
  Downloading imagesize-0.7.1-py2.py3-none-any.whl
Downloading/unpacking snowballstemmer>=1.1 (from sphinx)
  Downloading snowballstemmer-1.2.1-py2.py3-none-any.whl (64kB): 64kB downloaded
Downloading/unpacking Jinja2>=2.3 (from sphinx)
  Downloading Jinja2-2.8.1-py2.py3-none-any.whl (264kB): 264kB downloaded
Downloading/unpacking alabaster>=0.7,<0.8 (from sphinx)
  Downloading alabaster-0.7.9-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3/dist-packages (from sphinx)
Downloading/unpacking pytz>=0a (from babel>=1.3,!=2.0->sphinx)
  Downloading pytz-2016.10-py2.py3-none-any.whl (483kB): 483kB downloaded
Downloading/unpacking MarkupSafe (from Jinja2>=2.3->sphinx)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/pip-build-jlln2ebr/MarkupSafe/setup.py) egg_info for package MarkupSafe
    
Installing collected packages: sphinx, Pygments, babel, docutils, imagesize, snowballstemmer, Jinja2, alabaster, pytz, MarkupSafe
  Running setup.py install for MarkupSafe
    
    building 'markupsafe._speedups' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c markupsafe/_speedups.c -o build/temp.linux-x86_64-3.4/markupsafe/_speedups.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/markupsafe/_speedups.o -o build/lib.linux-x86_64-3.4/markupsafe/_speedups.cpython-34m.so
Successfully installed sphinx Pygments babel docutils imagesize snowballstemmer Jinja2 alabaster pytz MarkupSafe
Cleaning up...
root@8ef6461594b2:/#  python3 -c 'import sphinx.builders.linkcheck' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/sphinx/builders/linkcheck.py", line 35, in <module>
    from sphinx.util import encode_uri, requests
  File "/usr/local/lib/python3.4/dist-packages/sphinx/util/requests.py", line 20, in <module>
    from requests.packages.urllib3.exceptions import SSLError, InsecureRequestWarning
ImportError: cannot import name 'SSLError'
root@8ef6461594b2:/# python3 -c 'from requests.packages.urllib3.exceptions import SSLError'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'SSLError'
root@8ef6461594b2:/# python3 -c 'import requests; print(requests.__version__)' 
2.4.3
```

My personal problem was trivially fixed by upgrading requests to the latest version of requests. Therefore I do believe that specifying the requests dependency spec would be sufficient.

**Comment by tk0miya** [comment]
Did you use debianized requests package?
Could you try it again with pip one?
```
apt-get uninstall python-requests
pip install requests==2.4.3
```
It seems the debian package does not contain `packages` directory.

**Comment by akhmerov** [comment]
You're right, the debian installation of requests is the root of the problem. Not sure what this implies for this issue and sphinx in general.

**Comment by tk0miya** [comment]
I think this problem is caused by packaging bug of debian.
Please report this to the package maintainer.

**Comment by akhmerov** [comment]
wilco; perhaps it's still good to specify a required version of requests.

**Comment by tk0miya** [comment]
Agreed. I will investigate it later.
Maybe it will be 2.0+ or 2.4+.

Thanks,

**Comment by tk0miya** [comment]
Note: `InsecureRequestWarning` is appeared since 2.4.0.

**Comment by tk0miya** [comment]
Finally, I added a fallback for Debian jessie at 62329c8.
I don't tested it because I don't have the environment.
But it might work.

Thanks,

**Comment by akhmerov** [comment]
Thanks, looks great.
