### ISSUE TITLE
Error "width += node['colwidth']" in __init__.py of docutils

### ISSUE THREAD

**Issue by adithyabhatkajake** [sphinx-doc/sphinx#3275]
Subject: Docutils error in __init__.py  node colwidth when trying to `make htmldocs'

### Problem
When trying to build the htmldocs for the latest kernel on Manjaro system, an unexpected exception occurs.
[Error-Logs.zip](https://github.com/sphinx-doc/sphinx/files/668681/Error-Logs.zip)

#### Procedure to reproduce the problem
```
make htmldocs
```

#### Error logs / results
Console log
```
SPHINX  htmldocs --> file:///run/media/adithya/Media/Adithya-Backup/Resources/linux-4.9/linux-4.9/Documentation/output;
make[2]: Nothing to be done for 'all'.
Running Sphinx v1.5.1
Warning: The Sphinx 'sphinx_rtd_theme' HTML theme was not found. Make sure you have the theme installed to produce pretty HTML output. Falling back to the default theme.
WARNING: primary_domain 'C' not found, ignored.
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 535 source files that are out of date
updating environment: 535 added, 0 changed, 0 removed
./include/linux/init.h:1: warning: no structured comments found                 
./include/linux/workqueue.h:392: warning: No description found for parameter '...'
./include/linux/workqueue.h:392: warning: Excess function parameter 'args' description in 'alloc_workqueue'
./include/linux/workqueue.h:413: warning: No description found for parameter '...'
./include/linux/workqueue.h:413: warning: Excess function parameter 'args' description in 'alloc_ordered_workqueue'
./include/linux/kthread.h:26: warning: No description found for parameter '...'
./kernel/sys.c:1: warning: no structured comments found
./drivers/dma-buf/seqno-fence.c:1: warning: no structured comments found        
./include/linux/fence-array.h:61: warning: No description found for parameter 'fence'
./include/sound/core.h:324: warning: No description found for parameter '...'   
./include/sound/core.h:335: warning: No description found for parameter '...'
./include/sound/core.h:388: warning: No description found for parameter '...'
./include/media/media-entity.h:1054: warning: No description found for parameter '...'
reading sources... [100%] media/v4l-drivers/zr364xx                             
./include/net/mac80211.h:3207: ERROR: Unexpected indentation.
./include/net/mac80211.h:3210: WARNING: Block quote ends without a blank line; unexpected unindent.
./include/net/mac80211.h:3212: ERROR: Unexpected indentation.
./include/net/mac80211.h:3213: WARNING: Block quote ends without a blank line; unexpected unindent.
./include/net/mac80211.h:1772: ERROR: Unexpected indentation.
./include/net/mac80211.h:1776: WARNING: Block quote ends without a blank line; unexpected unindent.
./kernel/sched/fair.c:7259: WARNING: Inline emphasis start-string without end-string.
./kernel/time/timer.c:1240: ERROR: Unexpected indentation.
./kernel/time/timer.c:1242: ERROR: Unexpected indentation.
./kernel/time/timer.c:1243: WARNING: Block quote ends without a blank line; unexpected unindent.
./include/linux/wait.h:121: WARNING: Block quote ends without a blank line; unexpected unindent.
./include/linux/wait.h:124: ERROR: Unexpected indentation.
./include/linux/wait.h:126: WARNING: Block quote ends without a blank line; unexpected unindent.
./kernel/time/hrtimer.c:1021: WARNING: Block quote ends without a blank line; unexpected unindent.
./kernel/signal.c:317: WARNING: Inline literal start-string without end-string.
./drivers/base/firmware_class.c:1348: WARNING: Bullet list ends without a blank line; unexpected unindent.
./drivers/message/fusion/mptbase.c:5054: WARNING: Definition list ends without a blank line; unexpected unindent.
./drivers/tty/serial/serial_core.c:1893: WARNING: Definition list ends without a blank line; unexpected unindent.
./include/linux/spi/spi.h:369: ERROR: Unexpected indentation.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  8%] kernel-documentation                                   
Exception occurred:
  File "/usr/lib/python3.5/site-packages/docutils/writers/html4css1/__init__.py", line 288, in write_colspecs
    width += node['colwidth']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
The full traceback has been saved in /tmp/sphinx-err-uwfhsey1.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[1]: *** [Documentation/Makefile.sphinx:67: htmldocs] Error 1
make: *** [Makefile:1451: htmldocs] Error 2
```

Error log stored in "/tmp/sphinx-err-uwfhsey1.log"
```
# Sphinx version: 1.5.1
# Python version: 3.5.2 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.8
# Last messages:
#   writing output... [  7%] gpu/drm-kms-helpers
#   writing output... [  7%] gpu/drm-mm
#   writing output... [  7%] gpu/drm-uapi
#   writing output... [  7%] gpu/i915
#   writing output... [  8%] gpu/index
#   writing output... [  8%] gpu/introduction
#   writing output... [  8%] gpu/vga-switcheroo
#   writing output... [  8%] gpu/vgaarbiter
#   writing output... [  8%] index
#   writing output... [  8%] kernel-documentation
# Loaded extensions:
#   sphinx.directives (builtin) from /usr/lib/python3.5/site-packages/sphinx/directives/__init__.py
#   sphinx.roles (builtin) from /usr/lib/python3.5/site-packages/sphinx/roles.py
#   sphinx.builders.linkcheck (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/linkcheck.py
#   sphinx.builders.epub (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/epub.py
#   sphinx.builders.websupport (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/websupport.py
#   sphinx.domains.javascript (builtin) from /usr/lib/python3.5/site-packages/sphinx/domains/javascript.py
#   sphinx.builders.html (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/html.py
#   sphinx.builders.texinfo (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/texinfo.py
#   alabaster (0.7.9) from /usr/lib/python3.5/site-packages/alabaster/__init__.py
#   sphinx.builders.changes (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/changes.py
#   sphinx.domains.c (builtin) from /usr/lib/python3.5/site-packages/sphinx/domains/c.py
#   kernel_include (1.0) from /run/media/adithya/Media/Adithya-Backup/Resources/linux-4.9/linux-4.9/Documentation/sphinx/kernel_include.py
#   sphinx.builders.applehelp (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/applehelp.py
#   rstFlatTable (1.0) from /run/media/adithya/Media/Adithya-Backup/Resources/linux-4.9/linux-4.9/Documentation/sphinx/rstFlatTable.py
#   sphinx.builders.dummy (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/dummy.py
#   sphinx.domains.cpp (builtin) from /usr/lib/python3.5/site-packages/sphinx/domains/cpp.py
#   cdomain (1.0) from /run/media/adithya/Media/Adithya-Backup/Resources/linux-4.9/linux-4.9/Documentation/sphinx/cdomain.py
#   sphinx.builders.latex (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/latex.py
#   sphinx.ext.imgmath (1.5.1) from /usr/lib/python3.5/site-packages/sphinx/ext/imgmath.py
#   sphinx.directives.other (builtin) from /usr/lib/python3.5/site-packages/sphinx/directives/other.py
#   sphinx.builders.epub3 (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/epub3.py
#   sphinx.builders.text (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/text.py
#   sphinx.builders.manpage (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/manpage.py
#   sphinx.builders.gettext (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/gettext.py
#   sphinx.domains.rst (builtin) from /usr/lib/python3.5/site-packages/sphinx/domains/rst.py
#   sphinx.directives.code (builtin) from /usr/lib/python3.5/site-packages/sphinx/directives/code.py
#   kernel-doc (1.0) from [/run/media/adithya/Media/Adithya-Backup/Resources/linux-4.9/linux-4.9/Documentation/sphinx/kernel-doc.py](url)
#   sphinx.domains.std (builtin) from /usr/lib/python3.5/site-packages/sphinx/domains/std.py
#   sphinx.builders.qthelp (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/qthelp.py
#   sphinx.directives.patches (builtin) from /usr/lib/python3.5/site-packages/sphinx/directives/patches.py
#   sphinx.domains.python (builtin) from /usr/lib/python3.5/site-packages/sphinx/domains/python.py
#   sphinx.builders.htmlhelp (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/htmlhelp.py
#   sphinx.builders.xml (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/xml.py
#   sphinx.builders.devhelp (builtin) from /usr/lib/python3.5/site-packages/sphinx/builders/devhelp.py
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python3.5/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/usr/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/usr/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/lib/python3.5/site-packages/sphinx/builders/html.py", line 452, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/lib/python3.5/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python3.5/site-packages/sphinx/writers/html.py", line 48, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/usr/lib/python3.5/site-packages/docutils/writers/html4css1/__init__.py", line 764, in visit_tbody
    self.write_colspecs()
  File "/usr/lib/python3.5/site-packages/docutils/writers/html4css1/__init__.py", line 288, in write_colspecs
    width += node['colwidth']
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
```

#### Expected results
Generate the html docs

### Reproducible project / your project
- None

### Environment info
- OS: Linux 4.9.0-0-MANJARO SMP PREEMPT x86_64 GNU/Linux
- Python version: Python 3.5.2
- Sphinx version: Sphinx (sphinx-build) 1.5.1
- <Extra tools e.g.: Docutils

**Comment by tk0miya** [comment]
It is similar to https://sourceforge.net/p/docutils/bugs/303/ .
What directive do you use?

**Comment by adithyabhatkajake** [comment]
The problem is a part of that bug, yes.
