### ISSUE TITLE
Sphinx crashes on parallel build with an extension which raises unserializable exception

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#3284]
Subject: <what happen when you do on which document project>

### Problem
- Sphinx crashes on parallel build

#### Procedure to reproduce the problem
- Enable an extension which raises unserializable extension like following
```
from docutils.parsers.rst import Directive
class TestDirective(Directive):
    def run(self):
        import sys
        raise RuntimeError(sys)


def setup(app):
    app.add_directive('test', TestDirective)
    return {
        'version': '1.0',
        'parallel_read_safe': True,
        'parallel_write_safe': True,
    }
```
- Invoke sphinx-build with `-j [n]` option to build parallel

#### Error logs / results
```
$ make clean html
rm -rf _build/*
sphinx-build -b html -d _build/doctrees  -T -j4 . _build/html
Running Sphinx v1.5.2+
making output directory...
loading translations [ja]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 4 source files that are out of date
updating environment: 4 added, 0 changed, 0 removed
reading sources... [100%] qux
waiting for workers...
Process Process-3:
Traceback (most recent call last):
  File "/Users/tkomiya/.pyenv/versions/2.7.13/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/tkomiya/.pyenv/versions/2.7.13/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tkomiya/work/sphinx/sphinx/util/parallel.py", line 76, in _process
    pipe.send((True, (err, traceback.format_exc())))
PicklingError: Can't pickle <type 'module'>: attribute lookup __builtin__.module failed
```

#### Expected results
Not crashes.

**Comment by tk0miya** [comment]
Fixed.
