### ISSUE TITLE
Apparent incompatibility with Python 3.6's typing module

### ISSUE THREAD

**Issue by gdude2002** [sphinx-doc/sphinx#3291]
Error raised during normal processing.

#### Procedure to reproduce the problem
```
sphinx-build -b html -E <project dir>\doc\source <project dir>\doc\build\html
```

#### Error logs / results
*Console output*

```
Running Sphinx v1.5.1
[autosummary] generating autosummary for: api\events\definitions\ultros.events.definitions.general.rst, api\events\ultros.events.constants.rst, api\events\ultros.events.definitions.rst, api\events\ultros.events.manager.rst, api\rules\ultros.rules.constants.rst, api\rules\ultros.rules.engine.rst, api\rules\ultros.rules.predicates.rst, api\rules\ultros.rules.transformers.rst, api\storage\ultros.storage.config.rst, api\storage\ultros.storage.data.rst, api\storage\ultros.storage.database.rst, api\storage\ultros.storage.formats.rst, api\storage\ultros.storage.manager.rst, api\ultros.events.rst, api\ultros.rules.rst, api\ultros.storage.rst, api\ultros.system.rst, apidocs.rst, index.rst
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 19 source files that are out of date
updating environment: 19 added, 0 changed, 0 removed
reading sources... [  5%] api/events/definitions/ultros.events.definitions.general
Exception occurred:
  File "c:\python36\lib\typing.py", line 1419, in get_type_hints
    'or function.'.format(obj))
TypeError: <slot wrapper '__init__' of 'object' objects> is not a module, class, method, or function.
The full traceback has been saved in C:\Users\-GDUDE~1\AppData\Local\Temp\sphinx-err-6vi1sjj4.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

*Traceback from log*
```
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\sphinx\cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "C:\Python36\lib\site-packages\sphinx\application.py", line 333, in build
    self.builder.build_update()
  File "C:\Python36\lib\site-packages\sphinx\builders\__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "C:\Python36\lib\site-packages\sphinx\builders\__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "C:\Python36\lib\site-packages\sphinx\environment\__init__.py", line 556, in update
    self._read_serial(docnames, app)
  File "C:\Python36\lib\site-packages\sphinx\environment\__init__.py", line 576, in _read_serial
    self.read_doc(docname, app)
  File "C:\Python36\lib\site-packages\sphinx\environment\__init__.py", line 684, in read_doc
    pub.publish()
  File "C:\Python36\lib\site-packages\docutils\core.py", line 217, in publish
    self.settings)
  File "C:\Python36\lib\site-packages\sphinx\io.py", line 55, in read
    self.parse()
  File "C:\Python36\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    input_source=document['source'])
  File "C:\Python36\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Python36\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Python36\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "C:\Python36\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 2318, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "C:\Python36\lib\site-packages\docutils\parsers\rst\states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "C:\Python36\lib\site-packages\sphinx\ext\autodoc.py", line 1647, in run
    documenter.generate(more_content=self.content)
  File "C:\Python36\lib\site-packages\sphinx\ext\autodoc.py", line 992, in generate
    self.document_members(all_members)
  File "C:\Python36\lib\site-packages\sphinx\ext\autodoc.py", line 914, in document_members
    check_module=members_check_module and not isattr)
  File "C:\Python36\lib\site-packages\sphinx\ext\autodoc.py", line 989, in generate
    self.add_content(more_content)
  File "C:\Python36\lib\site-packages\sphinx\ext\autodoc.py", line 1362, in add_content
    ModuleLevelDocumenter.add_content(self, more_content)
  File "C:\Python36\lib\site-packages\sphinx\ext\autodoc.py", line 723, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "C:\Python36\lib\site-packages\sphinx\ext\autodoc.py", line 685, in process_doc
    self.options, docstringlines)
  File "C:\Python36\lib\site-packages\sphinx\application.py", line 589, in emit
    results.append(callback(self, *args))
  File "C:\Python36\lib\site-packages\sphinx_autodoc_typehints.py", line 68, in process_docstring
    type_hints = get_type_hints(obj)
  File "C:\Python36\lib\typing.py", line 1419, in get_type_hints
    'or function.'.format(obj))
TypeError: <slot wrapper '__init__' of 'object' objects> is not a module, class, method, or function.
```

### Reproducible project
- https://github.com/UltrosBot/Ultros3K

### Environment info
- OS: Windows 10 x64
- Python version: 3.6.0 x64
- Sphinx version: 1.5.1

**Comment by gdude2002** [comment]
To expand a little, one of the classes in the file it's scanning does not have its own `__init__()`. This means that the `__init__` on your basic `object` is what is being referred to - this is a C method, and so we have a slot wrapper around it instead of an actual function object.

Adding an `__init__` to my class removes this instance of the error, but there are other files with classes like this (for example, that's how you define an `IntEnum` from the `enums` bundled module) and it's certainly something Sphinx should be able to deal with.

**Comment by tk0miya** [comment]
It seems the error was happened inside `sphinx_autodoc_typehints` extension.
```
  File "C:\Python36\lib\site-packages\sphinx_autodoc_typehints.py", line 68, in process_docstring
    type_hints = get_type_hints(obj)
  File "C:\Python36\lib\typing.py", line 1419, in get_type_hints
    'or function.'.format(obj))
TypeError: <slot wrapper '__init__' of 'object' objects> is not a module, class, method, or function.
```
I feel this is not a bug of sphinx.

**Comment by gdude2002** [comment]
Oh, you're right, I completely missed that.

I'll raise it with them and get back to you.

EDIT: https://github.com/agronholm/sphinx-autodoc-typehints/issues/12
