### ISSUE TITLE
AssertionError: len(context) = 1

### ISSUE THREAD

**Issue by igor-raits** [sphinx-doc/sphinx#3298]
Subject: <what happen when you do on which document project>

### Problem
- During build of documentation, exception appears

#### Procedure to reproduce the problem
```
$ git clone https://github.com/quodlibet/mutagen.git -b release-1.36
$ cd mutagen
$ python3 setup.py build
$ sphinx-build-3 -b html -n docs docs/_build
```

#### Error logs / results
```
# Sphinx version: 1.4.9
# Python version: 3.6.0 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.8
# Last messages:
#   writing output... [ 41%] api/oggtheora
#   writing output... [ 44%] api/oggvorbis
#   writing output... [ 46%] api/optimfrog
#   writing output... [ 48%] api/smf
#   writing output... [ 51%] api/trueaudio
#   writing output... [ 53%] api/vcomment
#   writing output... [ 55%] api/wavpack
#   writing output... [ 58%] changelog
#   writing output... [ 60%] contact
#   writing output... [ 62%] index
# Loaded extensions:
#   sphinx.ext.autodoc (1.4.9) from /usr/lib/python3.6/site-packages/sphinx/ext/autodoc.py
#   sphinx.ext.napoleon (1.4.9) from /usr/lib/python3.6/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.intersphinx (1.4.9) from /usr/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   ext (unknown version) from /home/brain/git/fedora/python-mutagen/mutagen-release-1.36/docs/ext.py
#   alabaster (0.7.9) from /usr/lib/python3.6/site-packages/alabaster/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/lib/python3.6/site-packages/sphinx/builders/html.py", line 448, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/lib/python3.6/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python3.6/site-packages/sphinx/writers/html.py", line 47, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.6/site-packages/docutils/nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/lib/python3.6/site-packages/docutils/nodes.py", line 1895, in dispatch_departure
    return method(node)
  File "/usr/lib/python3.6/site-packages/docutils/writers/_html_base.py", line 671, in depart_document
    assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 1
```

#### Expected results
Build documentation without exception.

### Reproducible project / your project
- https://github.com/quodlibet/mutagen

### Environment info
- OS: Linux (Fedora Rawhide)
- Python version: 3.6
- Sphinx version: 1.4.9

**Comment by igor-raits** [comment]
ah, looks like a dupe of #3212
