### ISSUE TITLE
Just got an UnicodeEncodeError

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#330]
Hello,

i am not shure if i in the right place.
But after: make html

i got this error message.

Maybe someone could help me.

Thank you.
# Sphinx version: 0.6.4
# Docutils version: 0.6 release

Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Sphinx-0.6.4-py2.5.egg/sphinx/cmdline.py", line 170, in main
    app.build(all_files, filenames)
  File "/usr/lib/python2.5/site-packages/Sphinx-0.6.4-py2.5.egg/sphinx/application.py", line 131, in build
    self.builder.build_update()
  File "/usr/lib/python2.5/site-packages/Sphinx-0.6.4-py2.5.egg/sphinx/builders/**init**.py", line 265, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/lib/python2.5/site-packages/Sphinx-0.6.4-py2.5.egg/sphinx/builders/**init**.py", line 285, in build
    purple, length):
  File "/usr/lib/python2.5/site-packages/Sphinx-0.6.4-py2.5.egg/sphinx/builders/**init**.py", line 131, in status_iterator
    for item in iterable:
  File "/usr/lib/python2.5/site-packages/Sphinx-0.6.4-py2.5.egg/sphinx/environment.py", line 513, in update_generator
    self.read_doc(docname, app=app)
  File "/usr/lib/python2.5/site-packages/Sphinx-0.6.4-py2.5.egg/sphinx/environment.py", line 610, in read_doc
    self.process_images(docname, doctree)
  File "/usr/lib/python2.5/site-packages/Sphinx-0.6.4-py2.5.egg/sphinx/environment.py", line 751, in process_images
    if not os.access(path.join(self.srcdir, imgpath), os.R_OK):
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 71: ordinal not in range(128)

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/330
- Originally reported by: [vockso](https://bitbucket.org/vockso)
- Originally created at: 2010-01-27T12:50:49.293

**Comment by shimizukawa** [comment]
_From [vockso](https://bitbucket.org/vockso) on 2010-01-27 11:53:11+00:00_

**Bump!**

**Comment by shimizukawa** [comment]
_From [vockso](https://bitbucket.org/vockso) on 2010-01-29 14:29:51+00:00_

This was an ASCII decoding Prob.. Only in every .. figure:: äöüÄÖÜ
and .. image:: äöüÄÖÜ

Maybe someone has an idea, how to fix this.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-01-31 15:27:41+00:00_

Duplicate of #227.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2013-03-31 13:57:15+00:00_

Removing version: 0.6.4 (automated comment)
