### ISSUE TITLE
'IOError: [Errno 2] No such file' but the .yaml file is there

### ISSUE THREAD

**Issue by lglavas** [sphinx-doc/sphinx#3305]
### Problem
Hi this is my first documentation setup and have struggling with it for a while. How i get an error that it cant open  'log_config.yaml' but the file is there in the same '/core' directory so i have no idea how to solve this?
```
$ sudo sphinx-build -b html ../core ./_build/html/
Running Sphinx v1.5.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] index                                                                                 
/home/lglavas/IdeaProjects/mpst/core/index.rst:13: WARNING: autodoc: failed to import module u'executor'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.5.1-py2.7.egg/sphinx/ext/autodoc.py", line 547, in import_object
    __import__(self.modname)
  File "/home/lglavas/IdeaProjects/mpst/core/executor.py", line 42, in <module>
    from validator import Validator
  File "/home/lglavas/IdeaProjects/mpst/core/validator.py", line 2, in <module>
    from pl_tools import verify_locks, get_pl_info
  File "/home/lglavas/IdeaProjects/mpst/core/pl_tools.py", line 20, in <module>
    with open('log_config.yaml', 'r') as f:
IOError: [Errno 2] No such file or directory: 'log_config.yaml'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                  
generating indices... genindex
writing additional pages... search
copying static files... WARNING: html_static_path entry u'/home/lglavas/IdeaProjects/mpst/core/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2 warnings.
$ cd ../core
/core$ ls
conf.py           dynload.py    hw_config.py   installer.py     network.pyc         sample_template.pyc
conf.pyc          dynload.pyc   hw_config.pyc  installer.pyc    pl_tools.py         validator.py
dictionary.3gpp   executor.py   index.rst      log_config.yaml  pl_tools.pyc        validator.pyc
dictionary.pyrad  executor.pyc  __init__.py    network.py       sample_template.py
```

#### Procedure to reproduce the problem
```
sudo sphinx-build -b html ../core ./_build/html/
```

#### Error logs / results
```
IOError: [Errno 2] No such file or directory: 'log_config.yaml'
```

### Environment info
- OS: Ubuntu 16.04
- Python version: 2.7
- Sphinx version: Sphinx v1.5.1

**Comment by shimizukawa** [comment]
I guess `core/executor.py` tried to open 'log_config.yaml' in current directory where you invoke `sphinx-build` command instead of `../core`.

I suggest `core/executor.py` should not be autodoc target. Or you can avoid the behavior by using `__name__ == '__main__'` idiom as http://www.sphinx-doc.org/en/1.5.1/ext/autodoc.html mentioned:
> Sphinx autodoc imports the modules to be documented. If any modules have side effects on import, these will be executed by autodoc when sphinx-build is run.
> If you document scripts (as opposed to library modules), make sure their main routine is protected by a if `__name__ == '__main__'` condition.

**Comment by lglavas** [comment]
Thank you shimizukawa! 
You where absolutely right in your guess and that where good pointers that solved my problems. I am closing the issue now.
