### ISSUE TITLE
Build fails with code variables starting with unicode symbols.

### ISSUE THREAD

**Issue by julienmalard** [sphinx-doc/sphinx#3324]
Subject: <what happen when you do on which document project>

### Problem
- Build fails with code variables starting with unicode symbols.

#### Procedure to reproduce the problem
On automatic build, both lines below cause build fail because of the "índ_mod_fuente" variable.
```
índ_mod_fuente = l_mods.index(modelo_fuente)
modelo_recip = l_mods[(índ_mod_fuente + 1) % 2]
```

#### Error logs / results
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/sphinx/application.py", line 266, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 325, in build
    self.finish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/sphinx/builders/html.py", line 456, in finish
    self.finish_tasks.add_task(self.gen_additional_pages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/sphinx/util/parallel.py", line 40, in add_task
    res = task_func()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/sphinx/builders/html.py", line 481, in gen_additional_pages
    for pagename, context, template in pagelist:
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/sphinx/ext/viewcode.py", line 142, in collect_pages
    highlighted = highlighter.highlight_block(code, 'python', linenos=False)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/sphinx/highlighting.py", line 192, in highlight_block
    raise exc
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/sphinx/highlighting.py", line 185, in highlight_block
    hlsource = highlight(source, lexer, formatter)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/pygments/__init__.py", line 87, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/pygments/formatters/html.py", line 850, in format_unencoded
    for t, piece in source:
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/pygments/formatters/html.py", line 690, in _wrap_div
    for tup in inner:
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/pygments/formatters/html.py", line 708, in _wrap_pre
    for tup in inner:
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/pygments/formatters/html.py", line 727, in _format_lines
    for ttype, value in tokensource:
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/pygments/filter.py", line 20, in _apply
    for token in filter_.filter(lexer, stream):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/pygments/filters/__init__.py", line 196, in filter
    raise self.exception(value)
pygments.filters.ErrorToken: í

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/tinamit/envs/latest/lib/python3.4/site-packages/pygments/filters/__init__.py", line 196, in filter
    raise self.exception(value)
pygments.filters.ErrorToken: í
The full traceback has been saved in /tmp/sphinx-err-q3aolpht.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

#### Expected results
Renaming índ_mod_fuente as n_mod_fuente solved the problem.

### Reproducible project / your project
- https://github.com/julienmalard/Tinamit/blob/master/tinamit/Conectado.py

### Environment info
- OS: ReadTheDocs automated website build
- Python version: 3.4
- Sphinx version: ReadTheDocs default

**Comment by tk0miya** [comment]
Note: build logs
https://readthedocs.org/projects/tinamit/builds/4885161/

**Comment by tk0miya** [comment]
I reproduced the problem with Sphinx-1.3.5 and pygments-1.6.
With newest releases (Sphinx-1.5.1 and pygments-2.1.3), the error does not raised.

Please upgrade your software on reathedocs. AFAIK, you can use `requirements.txt` to upgrade them.

**Comment by julienmalard** [comment]
Hello,


Many thanks for your help!


Would you happen to know, by any chance, how to force the Sphinx upgrade on a Conda environment within ReadTheDocs? ReadTheDocs ends up "downgrading" it back down to 1.3.5 in the Conda install command phase (for another similar project that I have in Python 3.5; http://readthedocs.org/projects/tikon/builds/4904160/):


¨¨¨¨

The following packages will be DOWNGRADED:

    docutils:         0.13.1-py35_0 --> 0.12-py35_2
    pygments:         2.1.3-py35_0  --> 2.1.1-py35_0
    sphinx:           1.5.1-py35_0  --> 1.3.5-py35_0
¨¨¨¨


I specified the Sphinx version of 1.5.1 in both the requirements.txt and the environment.yml files.


Many thanks!

-Julien Malard



________________________________
દ્વારા: Takeshi KOMIYA <notifications@github.com>
મોકલ્યું: 15 જાન્યુઆરી 2017 22:06
પ્રતિ: sphinx-doc/sphinx
Cc: Julien Malard, M; Author
વિષય: Re: [sphinx-doc/sphinx] Build fails with code variables starting with unicode symbols. (#3324)


I reproduced the problem with Sphinx-1.3.5 and pygments-1.6.
With newest releases (Sphinx-1.5.1 and pygments-2.1.3), the error does not raised.

Please upgrade your software on reathedocs. AFAIK, you can use requirements.txt to upgrade them.

**Comment by jfbu** [comment]
I don't know if it will help but I just did a  `conda update --all` on a python 3.5 environement, and then

    conda env export > foo.yml

contains following information:

```
- docutils=0.13.1=py35_0
- pygments=2.1.3=py35_0
- sphinx=1.5.1=py35_0
```

hence the downgrading comes from some other cause.  As per ReadTheDocs, my setup on a shared project was to use readthedocs.yml to specify location of requirements.txt:

at top level a readthedocs.yml file with contents

    requirements_file: requirements/docs.txt
 
and then pu requirements in requirements/docs.txt. In your case I would try

    docutils>=0.13.1
    Pygments>=2.1.3
    Sphinx>=1.5.1

I don't have a RTD project of my own hence can not test quickly.

**Comment by tk0miya** [comment]
Please ask that to readthedocs team. We don't know about it.

**Comment by julienmalard** [comment]
Thanks for the tips! I think it is indeed something to do with ReadTheDocs's implementation of Conda. I will ask there for help!


Merci, ありがと,

Julien Malard

________________________________
દ્વારા: Jean-François B. <notifications@github.com>
મોકલ્યું: 16 જાન્યુઆરી 2017 12:19:53
પ્રતિ: sphinx-doc/sphinx
Cc: Julien Malard, M; Author
વિષય: Re: [sphinx-doc/sphinx] Build fails with code variables starting with unicode symbols. (#3324)


I don't know if it will help but I just did a conda update --all on a python 3.5 environement, and then

conda env export > foo.yml


contains following information:

- docutils=0.13.1=py35_0
- pygments=2.1.3=py35_0
- sphinx=1.5.1=py35_0


hence the downgrading comes from some other cause. As per ReadTheDocs, my setup is to use readthedocs.yml to specify location or requirements.txt:

at top level a readthedocs.yml file with contents

requirements_file: requirements/docs.txt


and requirements/docs.txt with contents for example

Sphinx>=1.4.4


I don't have a RTD project of my own hence can not test quickly but I would try with

docutils>=0.13.1
pygments>=2.1.3
sphinx>=1.5.1

but I don't know if one needs Pygments, Sphinx, etc... (because I had Sphinx above for whatever reason).
