### ISSUE TITLE
In python36,make dirhtml in flask_restful project directory "docs" in win10 platform error

### ISSUE THREAD

**Issue by cunjif** [sphinx-doc/sphinx#3352]
Subject: like title

### Problem
- No module named 'flask_restful.__version__'

#### Procedure to reproduce the problem
```
make dirhtml
```

#### Error logs / results
```
# Sphinx version: 1.5.1
# Python version: 3.6.0 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.8.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\sphinx\cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "c:\python36\lib\site-packages\sphinx\application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "c:\python36\lib\site-packages\sphinx\config.py", line 134, in __init__
    execfile_(filename, config)
  File "c:\python36\lib\site-packages\sphinx\util\pycompat.py", line 129, in execfile_
    exec_(code, _globals)
  File "conf.py", line 54, in <module>
    from flask_restful.__version__ import __version__
ModuleNotFoundError: No module named 'flask_restful.__version__'
```

### Environment info
- OS: window 10 profession 1601
- Python version: 3.6.0
- Sphinx version: (1.5.1,final,0)
- window cmd

**Comment by tk0miya** [comment]
It seems the error is raised at your `conf.py`.
```
  File "conf.py", line 54, in <module>
    from flask_restful.__version__ import __version__
ModuleNotFoundError: No module named 'flask_restful.__version__'
```

Could you check your conf.py please?

**Comment by tk0miya** [comment]
It seems not a bug of Sphinx.
Thanks,
