### ISSUE TITLE
NameError: name 'unicode' is not defined with current master branch HEAD

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3353]
Subject: build fails

#### Procedure to reproduce the problem
```
$ sphinx-quickstart # but it already fails so use pre-existing project...
$ make latex
```

#### Error logs / results
```
$ make latex
Traceback (most recent call last):
  File "/Users/FOO/sphinx-build.py", line 15, in <module>
    sys.exit(main(sys.argv))
  File "/Users/FOO/sphinx/__init__.py", line 66, in main
    sys.exit(build_main(argv))
  File "/Users/FOO/sphinx/__init__.py", line 76, in build_main
    from sphinx import cmdline
  File "/Users/FOO/sphinx/cmdline.py", line 24, in <module>
    from sphinx.application import Sphinx
  File "/Users/FOO/sphinx/application.py", line 33, in <module>
    from sphinx.config import Config
  File "/Users/FOO/sphinx/config.py", line 49, in <module>
    ('rebuild', Union[bool, unicode])])
NameError: name 'unicode' is not defined
make: *** [Makefile:20: latex] Error 1
```

#### Expected results
build completes successfully

### Environment info
- OS: Mac 10.9.5
- Python 3.5.2
- Sphinx current HEAD at 491620e

(this is commit which introduced problem)

**Comment by tk0miya** [comment]
Sorry, it's my mistake. fixed.
