### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by weshouman** [sphinx-doc/sphinx#3385]
Subject: Html Documentation generation failure

### Problem
- Html documentation generation fails with an ambiguous message.

#### Procedure to reproduce the problem
- Generate XML doxygen documentation for [TagainiJisho](https://github.com/Gnurou/tagainijisho)
- Setup [Breathe](https://github.com/michaeljones/breathe/) in the ```conf.py```
- Run ```make html```

#### Error logs / results
```
# Sphinx version: 1.5.2
# Python version: 2.7.6 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.4
# Last messages:
#   Running Sphinx v1.5.2
#   loading pickled environment...
#   not yet created
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 1 source files that are out of date
#   updating environment:
#   1 added, 0 changed, 0 removed
#   reading sources... [100%] index
# Loaded extensions:
#   sphinx.ext.coverage (1.5.2) from /home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/sphinx/ext/coverage.pyc
#   sphinx.ext.viewcode (1.5.2) from /home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/sphinx/ext/viewcode.pyc
#   breathe (4.4.0) from /home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/__init__.pyc
#   sphinx.ext.autodoc (1.5.2) from /home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   alabaster (0.7.9) from /home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/alabaster/__init__.pyc
Traceback (most recent call last):
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 556, in update
    self._read_serial(docnames, app)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 576, in _read_serial
    self.read_doc(docname, app)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 684, in read_doc
    pub.publish()
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/sphinx/io.py", line 55, in read
    self.parse()
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2318, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/directive/index.py", line 90, in run
    return self.handle_contents(project_info)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/directive/index.py", line 59, in handle_contents
    node_list = object_renderer.render(context.node_stack[0], context)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1156, in render
    result = method(self, node)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 345, in visit_doxygen
    nodelist.extend(self.render(compound))
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1156, in render
    result = method(self, node)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1088, in dispatch_compound
    return self.visit_compound(node)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 357, in visit_compound
    rendered_data = self.render(file_data)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1156, in render
    result = method(self, node)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 350, in visit_doxygendef
    return self.render(node.compounddef)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1156, in render
    result = method(self, node)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 494, in visit_compounddef
    child_nodes = self.render(sectiondef)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1156, in render
    result = method(self, node)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 528, in visit_sectiondef
    node_list.extend(self.render_iterable(node.memberdef))
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1167, in render_iterable
    output.extend(self.render(entry))
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1156, in render
    result = method(self, node)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 1096, in dispatch_memberdef
    return self.visit_enum(node)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 938, in visit_enum
    update_signature=update_signature)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 313, in render_declaration
    update_signature(signode, obj_type)
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 935, in update_signature
    signature.children[1][0] = self.node_factory.strong(text="[anonymous]")
IndexError: list index out of range

```
### Environment info
- OS: <Unix/Linux/Mac/Win/other with version>
- Python version: 2.7.6
- Sphinx version: 1.5.2
- Breathe version: 4.4.0

**Comment by weshouman** [comment]
This was due to abusing the doxygenindex directive.  

Following was my ```index.rst``` file:  

```
.. tagaini-jisho documentation master file, created by
   sphinx-quickstart on Mon Jan 23 08:59:51 2017.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.

Welcome to tagaini-jisho's documentation!
=========================================

This documentation is intended to better understand the codebase.

Requirements:

Tagaini Jisho depends on ... .

Contents:

.. toctree::
   :maxdepth: 2
   :caption: Contents:


Indices and tables
==================

.. doxygenindex::

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
```

**Comment by weshouman** [comment]
Shall this issue be left open till the error gets a better error_message?

**Comment by tk0miya** [comment]
Unfortunately, it seems the error is happened inside breathe extension.
Could you report this to their project?

```
  File "/home/walid/Documents/tests/tagaini/tagainijisho/venv/local/lib/python2.7/site-packages/breathe/renderer/sphinxrenderer.py", line 935, in update_signature
    signature.children[1][0] = self.node_factory.strong(text="[anonymous]")
IndexError: list index out of range
```

Thanks,
