### ISSUE TITLE
Cannot create Sphinx build directory

### ISSUE THREAD

**Issue by syee** [sphinx-doc/sphinx#3420]
Subject:  Cannot create Sphinx build directory

### Problem
I'm using a virtualenv. My 'pip freeze' is identical to the pip freeze of another venv that was able to successfully create the build directory. I also have all the same files as the other environment. This is a delightful "works on my local machine but not anywhere else" situation. I think there may be an issue with the autoapi.extension. When I exclude it from the extensions in the conf.py file, the build directory gets completed although it doesn't contain what is expected. I can provide the conf.py and index.rst files if they would be helpful.

extensions = ['sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.githubpages',
    'autoapi.extension']

#### Procedure to reproduce the problem
(venv) $ make html
Running Sphinx v1.5.1
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
[AutoAPI] Loading Data
[AutoAPI] Reading files... [  4%] /Documents/framework/doc/venv/lib/python2.7/types.py   

#### Error logs / results
Traceback (most recent call last):
  File "/Documents/framework/doc/venv/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Documents/framework/doc/venv/lib/python2.7/site-packages/sphinx/application.py", line 244, in __init__
    self._init_builder(self.buildername)
  File "/Documents/framework/doc/venv/lib/python2.7/site-packages/sphinx/application.py", line 315, in _init_builder
    self.emit('builder-inited')
  File "/Documents/framework/doc/venv/lib/python2.7/site-packages/sphinx/application.py", line 589, in emit
    results.append(callback(self, *args))
  File "/Documents/framework/doc/venv/lib/python2.7/site-packages/autoapi/extension.py", line 70, in run_autoapi
    ignore=ignore_patterns,
  File "/Documents/framework/doc/venv/lib/python2.7/site-packages/autoapi/mappers/base.py", line 196, in load
    data = self.read_file(path=path)
  File "/Documents/framework/doc/venv/lib/python2.7/site-packages/autoapi/mappers/python.py", line 31, in read_file
    parsed_data = parsed(path)
  File "/Documents/framework/doc/venv/lib/python2.7/site-packages/epyparse.py", line 104, in parsed
    return Parser().parse(name_or_path)
  File "/Documents/framework/doc/venv/lib/python2.7/site-packages/epyparse.py", line 230, in parse
    return visit(self.iterparse(name_or_path))
  File "/Documents/framework/doc/venv/lib/python2.7/site-packages/epyparse.py", line 224, in visit
    child = visit(child)
  File "/Documents/framework/doc/venv/lib/python2.7/site-packages/epyparse.py", line 220, in visit
    for info, children in iterable:
  File "/Documents/framework/doc/venv/lib/python2.7/site-packages/epyparse.py", line 197, in iterparse
    if val.is_imported:
  File "/Documents/framework/doc/venv/lib/python2.7/site-packages/epydoc/apidoc.py", line 282, in __nonzero__
    self.name)
ValueError: Sentinel value <UNKNOWN> can not be used as a boolean
 

#### Expected results
The build directory should be created.

### Environment info
- OS: Mac
- Python version: 2.7.10 (CPython)
- Sphinx version: 1.5.1
- Jinja2 version 2.9.3

**Comment by syee** [comment]
Sorry I figured it out. There was an exception on my end.
