### ISSUE TITLE
Sphinx throws exception when using certain extensions.

### ISSUE THREAD

**Issue by willcharlton** [sphinx-doc/sphinx#3503]
Subject: Installed `sphinxcontrib-fulltoc`, Sphinx throws exception during make.

### Problem
I had been using sphinx docs on a project for some time and I needed to uses the `sphinxcontrib-fulltoc` extension. Once I installed it my `make html` commands would throw the attached exception. I removed this extension and the problem went away.

#### Procedure to reproduce the problem
```
make html
```

#### Error logs / results
```
$ cat /var/folders/6n/drzf04514fggdvnz_7pp9plr0000gp/T/sphinx-err-Us47ua.log
# Sphinx version: 1.5.3
# Python version: 2.7.9 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.5
# Last messages:
#   checking consistency...
#   /home/user/apidoc/modules.rst:: WARNING: document isn't included in any toctree
#   /home/user/gere/index.rst:: WARNING: document isn't included in any toctree
#   /home/user/gitflow/index.rst:: WARNING: document isn't included in any toctree
#   /home/user/integration-plan/index.rst:: WARNING: document isn't included in any toctree
#   done
#   preparing documents...
#   WARNING: html_favicon is not an .ico file
#   done
#   writing output... [  5%] apidoc/GatewayEngine
# Loaded extensions:
#   sphinx.ext.mathjax (1.5.3) from /home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/ext/mathjax.pyc
#   sphinx.ext.coverage (1.5.3) from /home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/ext/coverage.pyc
#   sphinx.ext.viewcode (1.5.3) from /home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/ext/viewcode.pyc
#   sphinx.ext.todo (1.5.3) from /home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   sphinx.ext.autodoc (1.5.3) from /home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx (1.5.3) from /home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
#   sphinx.ext.doctest (1.5.3) from /home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/ext/doctest.pyc
#   alabaster (0.7.10) from /home/user/.virtualenvs/venv/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinxcontrib.plantuml (unknown version) from /home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinxcontrib/plantuml.pyc
#   sphinxcontrib.fulltoc (unknown version) from /home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinxcontrib/fulltoc.pyc
Traceback (most recent call last):
  File "/home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/builders/html.py", line 461, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/builders/html.py", line 818, in handle_page
    templatename, ctx, event_arg)
  File "/home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/application.py", line 593, in emit_firstresult
    for result in self.emit(event, *args):
  File "/home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/application.py", line 589, in emit
    results.append(callback(self, *args))
  File "/home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinxcontrib/fulltoc.py", line 36, in html_page_context
    rendered_toc = get_rendered_toctree(app.builder, pagename)
  File "/home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinxcontrib/fulltoc.py", line 57, in get_rendered_toctree
    collapse=collapse,
  File "/home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinxcontrib/fulltoc.py", line 82, in build_full_toctree
    env.resolve_references(result, docname, builder)
  File "/home/user/.virtualenvs/venv/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 1036, in resolve_references
    for node in doctree.traverse(addnodes.pending_xref):
AttributeError: 'NoneType' object has no attribute 'traverse'
```
- <public link of unexpected result if you have>

#### Expected results
Sphinx should be able to make the docs.

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
```
$ uname -mprsv
Darwin 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64 i386
$ cat requirements-docs.txt 
plantuml==0.1.1
sphinxcontrib-plantuml==0.7
Sphinx
recommonmark==0.4.0
CommonMark==0.5.4
sphinx_rtd_theme
pdfkit
# sphinxcontrib-fulltoc
$ python --version
Python 2.7.10
```

**Comment by tk0miya** [comment]
I feel fulltoc extension causes the problem. So I think this is not a bug of Sphinx.
Could you report this to their project?
Thanks,
