### ISSUE TITLE
Issue while building sphinx doc

### ISSUE THREAD

**Issue by avijitnsec** [sphinx-doc/sphinx#3535]
Subject: <what happen when you do on which document project>

### Problem
- 
Trying to build django doc 
#### Procedure to reproduce the problem
```
Follow this step to reproduce the issue
https://docs.djangoproject.com/en/1.10/topics/http/urls/


<Paste your command-line here which cause the# Sphinx version: 1.5.3

 problem>

```

#### Error logs / results
```
# Python version: 3.5.1 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.5
# Last messages:
#   writing output... [  7%] howto/initial-data
#   writing output... [  7%] howto/jython
#   writing output... [  7%] howto/legacy-databases
#   writing output... [  8%] howto/outputting-csv
#   writing output... [  8%] howto/outputting-pdf
#   writing output... [  8%] howto/static-files/deployment
#   writing output... [  8%] howto/static-files/index
#   writing output... [  9%] howto/upgrade-version
#   writing output... [  9%] howto/windows
#   writing output... [  9%] howto/writing-migrations
# Loaded extensions:
#   sphinx.ext.intersphinx (1.5.3) from C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sphinx\ext\intersphinx.py
#   cve_role (unknown version) from C:\Users\avijit.das\django\docs\_ext\cve_role.py
#   sphinx.ext.viewcode (1.5.3) from C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sphinx\ext\viewcode.py
#   ticket_role (unknown version) from C:\Users\avijit.das\django\docs\_ext\ticket_role.py
#   alabaster (0.7.10) from C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\alabaster\__init__.py
#   djangodocs (unknown version) from C:\Users\avijit.das\django\docs\_ext\djangodocs.py
Traceback (most recent call last):
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sphinx\cmdline.py", line 297, in main
    return app.statuscode
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sphinx\util\docutils.py", line 29, in docutils_namespace
    yield
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sphinx\cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sphinx\application.py", line 333, in build
    self.builder.build_update()
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sphinx\builders\__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sphinx\builders\__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sphinx\builders\__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sphinx\builders\__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sphinx\builders\html.py", line 455, in write_doc
    self.docwriter.write(doctree, destination)
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\docutils\writers\__init__.py", line 80, in write
    self.translate()
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sphinx\writers\html.py", line 48, in translate
    self.document.walkabout(visitor)
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\docutils\nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\docutils\nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "C:\Users\avijit.das\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sphinx\writers\html.py", line 765, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: snippet_with_filename
```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: Windows (cygwin)
- Python version: 3.5
- Sphinx version: Sphinx-1.5.3
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
Sorry, please ask to django team how to build the docs.
It seems this is not a bug of Sphinx. because `snippet_with_filename` is not a part of Sphinx.
I guess djangodoc extends Sphinx by itself, and that causes the error.

Thanks,
