### ISSUE TITLE
Sphinx, creating html files error

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#355]
# Sphinx version: 0.6.5
# Docutils version: 0.6 release

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-0.6.5-py2.6.egg/sphinx/cmdline.py", line 170, in main
    app.build(all_files, filenames)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-0.6.5-py2.6.egg/sphinx/application.py", line 136, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-0.6.5-py2.6.egg/sphinx/builders/**init**.py", line 265, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-0.6.5-py2.6.egg/sphinx/builders/**init**.py", line 320, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-0.6.5-py2.6.egg/sphinx/builders/**init**.py", line 358, in write
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-0.6.5-py2.6.egg/sphinx/environment.py", line 1000, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-0.6.5-py2.6.egg/sphinx/environment.py", line 1269, in resolve_references
    self.warn(node['refdoc'],
  File "/usr/local/lib/python2.6/dist-packages/docutils-0.6-py2.6.egg/docutils/nodes.py", line 537, in **getitem**
    return self.attributes[key]
KeyError: 'refdoc'

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/355
- Originally reported by: Anonymous
- Originally created at: 2010-03-17T19:42:47.586

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-04-04 17:43:05+00:00_

This can happen after updating from 0.6.x to 0.6.5.  Please use "make clean" (or remove all output directories) and rebuild.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-08-25 12:19:46+00:00_

Removing milestone: 0.6 (automated comment)

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2013-03-31 13:57:21+00:00_

Removing version: 0.6.5 (automated comment)
