### ISSUE TITLE
[linkcheck] UnboundLocalError: local variable 'code' referenced before assignment (case sensitive)

### ISSUE THREAD

**Issue by pawamoy** [sphinx-doc/sphinx#3552]
Subject: Linkchecking URL fails when case change (even if URL is case-insensitive)

### Problem
- For example, link-checking http://KeyCut.readthedocs.io/en/latest/ will fail (with exception and traceback, making the builder unable to terminate), when http://keycut.readthedocs.io/en/latest/ will succeed. Going to http://KeyCut.readthedocs.io/en/latest/ will correctly redirect to http://keycut.readthedocs.io/en/latest/.

#### Procedure to reproduce the problem
```
sphinx-build -b linkcheck docs dist/docs
```

#### Error logs / results
(Full example)
```
Running Sphinx v1.5.3
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [linkcheck]: targets for 5 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
preparing documents... done
writing output... [ 20%] authors                                                                                      
(line    5) ok        http://pawamoy.github.io/
writing output... [ 40%] changelog                                                                                    
writing output... [ 60%] contributing                                                                                 
(line   76) ok        https://travis-ci.org/Pawamoy/keycut/pull_requests
(line   11) ok        https://github.com/Pawamoy/keycut/issues
(line   40) ok        https://github.com/Pawamoy/keycut
(line   27) ok        https://github.com/Pawamoy/keycut/issues
writing output... [ 80%] index                                                                                        
writing output... [100%] readme                                                                                       
(line    8) ok        https://pypi.python.org/pypi/keycut/
(line    8) ok        https://pypi.python.org/pypi/keycut/
(line    8) ok        https://pyup.io/repos/github/Pawamoy/keycut/
(line    8) ok        https://travis-ci.org/Pawamoy/keycut/
(line    8) ok        https://gitter.im/Pawamoy/keycut
(line   17) ok        https://travis-ci.org/Pawamoy/keycut/
(line    8) ok        https://www.codacy.com/app/Pawamoy/keycut/dashboard
(line    8) ok        https://www.codacy.com/app/Pawamoy/keycut/dashboard
(line   56) ok        https://github.com/Pawamoy/keycut-data
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/pawamoy/Data/git/keycut/.tox/linkcheck/local/lib/python2.7/site-packages/sphinx/builders/linkcheck.py", line 207, in check_thread
    status, info, code = check()
  File "/media/pawamoy/Data/git/keycut/.tox/linkcheck/local/lib/python2.7/site-packages/sphinx/builders/linkcheck.py", line 190, in check
    status, info, code = check_uri()
  File "/media/pawamoy/Data/git/keycut/.tox/linkcheck/local/lib/python2.7/site-packages/sphinx/builders/linkcheck.py", line 170, in check_uri
    return 'redirected', new_url, code
UnboundLocalError: local variable 'code' referenced before assignment

(line   21) ok        https://www.codacy.com/app/Pawamoy/keycut/dashboard
(line   25) ok        https://www.codacy.com/app/Pawamoy/keycut/dashboard
^CERROR: KEYBOARDINTERRUPT
^CERROR: keyboardinterrupt

```

#### Expected results
The link-check should succeed with a redirection found.

### Reproducible project / your project
- Travis linkcheck job: https://travis-ci.org/Pawamoy/keycut/jobs/210328586

### Environment info
- OS: Linux, BunsenLabs (Debian based) version 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux
- Python version: 2.7.9, same issue with 3.5.3
- Sphinx version: 1.5.3

**Comment by tk0miya** [comment]
Fixed at 2dae11a.
Thank you for reporting!
