### ISSUE TITLE
Error running sphinx-build docs docs/_build for Stringray documentation

### ISSUE THREAD

**Issue by haroonrashid235** [sphinx-doc/sphinx#3553]
Error Log :
```
# Sphinx version: 1.5.1
# Python version: 2.7.13 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.5
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "C:\Users\Haroon Rashid\Anaconda2\lib\site-packages\Sphinx-1.5.1-py2.7.egg\sphinx\cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "C:\Users\Haroon Rashid\Anaconda2\lib\site-packages\Sphinx-1.5.1-py2.7.egg\sphinx\application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "C:\Users\Haroon Rashid\Anaconda2\lib\site-packages\Sphinx-1.5.1-py2.7.egg\sphinx\config.py", line 134, in __init__
    execfile_(filename, config)
  File "C:\Users\Haroon Rashid\Anaconda2\lib\site-packages\Sphinx-1.5.1-py2.7.egg\sphinx\util\pycompat.py", line 129, in execfile_
    exec_(code, _globals)
  File "C:\Users\Haroon Rashid\Anaconda2\lib\site-packages\six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 85, in <module>
ImportError: No module named stingray
```

**Comment by tk0miya** [comment]
It seems "your `conf.py`" depends on stingray package. Please install it.
And, ask how to build the document to the owner of document.
This is not a bug of Sphinx.

Thanks,
