### ISSUE TITLE
an exception was raised up when i run "make html" in the project "pycodestyle"

### ISSUE THREAD

**Issue by nathaniel0402** [sphinx-doc/sphinx#3569]
Subject: an exception was raised up when i run "make html" in the project "pycodestyle"

### Problem
- an exception was raised up when i run "make html" in the project "pycodestyle"

#### Procedure to reproduce the problem
```
make html
```

#### Error logs / results
```
# Sphinx version: 1.5.1
# Python version: 2.7.13 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.4
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\Sphinx-1.5.1-py2.7.egg\sphinx\cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\Sphinx-1.5.1-py2.7.egg\sphinx\application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "C:\ProgramData\Anaconda2\lib\site-packages\Sphinx-1.5.1-py2.7.egg\sphinx\config.py", line 134, in __init__
    execfile_(filename, config)
  File "C:\ProgramData\Anaconda2\lib\site-packages\Sphinx-1.5.1-py2.7.egg\sphinx\util\pycompat.py", line 129, in execfile_
    exec_(code, _globals)
  File "C:\ProgramData\Anaconda2\lib\site-packages\six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 104, in <module>
    import sphinx_rtd_theme
ImportError: No module named sphinx_rtd_theme
```
- <public link of unexpected result if you have>

#### Expected results
build the html doc

### Reproducible project / your project
- project in github: https://github.com/PyCQA/pycodestyle.git

### Environment info
- OS: Win10
- Python version:Python 2.7.13 |Anaconda 4.3.0 (32-bit)| (default, Dec 19 2016, 13:36:02) [MSC v.1500 32 bit (Intel)] on win32
- Sphinx version:
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
It seems `sphinx_rtd_theme` is not installed. Please install it before building docs.
Since sphinx-1.5, we dropped it from dependencies.

If pycodestyle does not depend to it, please let them know.
Thanks,
