### ISSUE TITLE
Docs compilation fail  :(

### ISSUE THREAD

**Issue by DominiqueMakowski** [sphinx-doc/sphinx#3612]
Subject: Compilation of my docs failed

### Problem
- When I try to build the documentation for [this package](https://github.com/neuropsychology/NeuroKit.py), it fails with an error that *seems* (?) related to python 2.7, if though my package is written in 3.5.

#### Procedure to reproduce the problem

Simply try to build the documentation.

#### Error logs / results

The error is available at readthedocs: [http://readthedocs.org/projects/neurokit/builds/5259505/](http://readthedocs.org/projects/neurokit/builds/5259505/)

```
Running Sphinx v1.5.3
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/neurokit/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/neurokit/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 189, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/neurokit/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 512, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/neurokit/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/applehelp.py", line 19, in <module>
    from sphinx.builders.html import StandaloneHTMLBuilder
  File "/home/docs/checkouts/readthedocs.org/user_builds/neurokit/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 41, in <module>
    from sphinx.theming import Theme
  File "/home/docs/checkouts/readthedocs.org/user_builds/neurokit/envs/latest/local/lib/python2.7/site-packages/sphinx/theming.py", line 22, in <module>
    import pkg_resources
  File "/home/docs/checkouts/readthedocs.org/user_builds/neurokit/envs/latest/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 36, in <module>
    import email.parser
  File "/usr/lib/python2.7/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser
  File "/usr/lib/python2.7/email/feedparser.py", line 27, in <module>
    from email import message
  File "/usr/lib/python2.7/email/message.py", line 16, in <module>
    import email.charset
  File "/usr/lib/python2.7/email/charset.py", line 13, in <module>
    import email.base64mime
  File "/usr/lib/python2.7/email/base64mime.py", line 40, in <module>
    from email.utils import fix_eols
  File "/usr/lib/python2.7/email/utils.py", line 120, in <module>
    ''', re.VERBOSE | re.IGNORECASE)
TypeError: unsupported operand type(s) for |: 'Mock' and 'Mock'

Exception occurred:
  File "/usr/lib/python2.7/email/utils.py", line 120, in <module>
    ''', re.VERBOSE | re.IGNORECASE)
TypeError: unsupported operand type(s) for |: 'Mock' and 'Mock'
The full traceback has been saved in /tmp/sphinx-err-jsFnxI.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

```

#### Expected results

I'd like to have a working documentation.

### Reproducible project / your project
- The package: [https://github.com/neuropsychology/NeuroKit.py](https://github.com/neuropsychology/NeuroKit.py)
- The documentation is in the [docs dir](https://github.com/neuropsychology/NeuroKit.py/tree/master/docs)

### Environment info
- OS: Win
- Python version: 3.5
- Sphinx version: 1.5.3

**Comment by DominiqueMakowski** [comment]
I modified the dependencies (had mispelled a package) and it built itself. However, the API page, where lies the autodoc commands, remains empty...

**Comment by tk0miya** [comment]
It seems you are mocking `re` package. What is currrent your problem?
Please let me know in detail.

**Comment by DominiqueMakowski** [comment]
@tk0miya So I removed the `re` package from the mocking list. However, while the documentation is [successfuly building](http://readthedocs.org/projects/neurokit/builds/), nothing appears on the [API page](http://neurokit.readthedocs.io/en/latest/api.html) where I put the autodoc commands.

**Comment by tk0miya** [comment]
Please check your build logs.
It shows there were some warnings.
```
/home/docs/checkouts/readthedocs.org/user_builds/neurokit/checkouts/latest/docs/api.rst:5: WARNING: autodoc: failed to import module u'neurokit'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/neurokit/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/neurokit/checkouts/latest/neurokit/__init__.py", line 9, in <module>
    from .bio import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/neurokit/checkouts/latest/neurokit/bio/__init__.py", line 7, in <module>
    from .bio_eda import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/neurokit/checkouts/latest/neurokit/bio/bio_eda.py", line 7, in <module>
    import cvxopt as cv
ImportError: No module named cvxopt
```
It seems some dependencies are not installed. Please check your requirements.txt.

**Comment by tk0miya** [comment]
Any updates? It seems the latest build suceeded now. So I'm closing this.
