### ISSUE TITLE
pip install sphinx fails with AttributeError: 'NoneType' object has no attribute 'splitlines'

### ISSUE THREAD

**Issue by AshleySetter** [sphinx-doc/sphinx#3647]
Subject: AttributeError when I attempt to pip install sphinx

### Problem
When I attempt to pip install sphinx I get an attribute error as shown below.

#### Procedure to reproduce the problem
```
pip install sphinx
```

#### Error logs / results
```
Requirement already satisfied: sphinx in /Users/ajs3g11/anaconda/envs/python34/lib/python3.4/site-packages/Sphinx-1.3.1-py3.4.egg
Exception:
Traceback (most recent call last):
  File "/Users/ajs3g11/anaconda/envs/python34/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/ajs3g11/anaconda/envs/python34/lib/python3.4/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/Users/ajs3g11/anaconda/envs/python34/lib/python3.4/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/Users/ajs3g11/anaconda/envs/python34/lib/python3.4/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/ajs3g11/anaconda/envs/python34/lib/python3.4/site-packages/pip/req/req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "/Users/ajs3g11/anaconda/envs/python34/lib/python3.4/site-packages/pip/utils/packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "/Users/ajs3g11/anaconda/envs/python34/lib/python3.4/email/feedparser.py", line 177, in feed
    self._input.push(data)
  File "/Users/ajs3g11/anaconda/envs/python34/lib/python3.4/email/feedparser.py", line 100, in push
    parts = data.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
```
### Environment info
- OS: Mac
- Python version: Python 3.4.5
- conda version: 4.2.13

**Comment by tk0miya** [comment]
>Requirement already satisfied: sphinx in /Users/ajs3g11/anaconda/envs/python34/lib/python3.4/site-packages/Sphinx-1.3.1-py3.4.egg

It seems the installations is finished. And the error is happened inside pip module.
So I think this is a bug of pip.
Thanks,

**Comment by AshleySetter** [comment]
I'm think it was an error with one of sphinx's requirement packages as I got a similar error when attempting `conda install sphinx`. I fixed this by running `pip install --upgrade sphinx`. This updated and install sphinx to my anaconda environment.
