### ISSUE TITLE
TypeError: string argument expected, got 'bytes' when using parallel Sphinx

### ISSUE THREAD

**Issue by grzanka** [sphinx-doc/sphinx#3661]
Subject: TypeError: string argument expected, got 'bytes' when running `sphinx-build -j4 (...)` on https://github.com/pytrip/pytrip

### Problem
- With Sphinx versions until 1.6 there was not such issue. After upgrading to 1.6b1 I've started to see on travis following error:
```
Sphinx parallel build error:
TypeError: string argument expected, got 'bytes'
```

After reproducing locally:
```
→ sphinx-build -j4 -b html -d tmp docs docs/build/_html -v > 1.log                                                                   ~/PycharmProjects/pytrip

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 338, in build
    self.builder.build_update()
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 328, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 341, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 581, in update
    self._read_parallel(docnames, self.app, nproc=self.app.parallel)
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 633, in _read_parallel
    tasks.join()
  File "/usr/lib/python3.6/site-packages/sphinx/util/parallel.py", line 112, in join
    self._join_one()
  File "/usr/lib/python3.6/site-packages/sphinx/util/parallel.py", line 120, in _join_one
    raise SphinxParallelError(*result)
sphinx.errors.SphinxParallelError: TypeError: string argument expected, got 'bytes'

Sphinx parallel build error:
TypeError: string argument expected, got 'bytes'
```

#### Error logs / results
- https://travis-ci.org/pytrip/pytrip/jobs/225092251#L804

#### Expected results
I'd expect nice results as here with Sphinx 1.5:
- https://travis-ci.org/pytrip/pytrip/jobs/224899037#L987

### Reproducible project / your project
- https://github.com/pytrip/pytrip

### Environment info
- OS: Ubuntu 14.04.5 LTS
- Python version: 3.5.2
- Sphinx version: 1.6b2
- see https://travis-ci.org/pytrip/pytrip/jobs/225092251#L804

**Comment by tk0miya** [comment]
Thank you for reporting.
Fixed at 	2807175.
