### ISSUE TITLE
sphinxcontrib-needs exception

### ISSUE THREAD

**Issue by danielvasas** [sphinx-doc/sphinx#3667]
```
Exception occurred:
  File "C:\dev\test3\lib\site-packages\sphinxcontrib\needs.py", line 600, in process_spec_nodes
    all_needs = env.need_all_needs
AttributeError: 'BuildEnvironment' object has no attribute 'need_all_needs'


# Sphinx version: 1.5.3
# Python version: 3.5.3 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.5
# Last messages:
#   
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [ 50%] contents/user_stories
# Loaded extensions:
#   sphinxcontrib.plantuml (unknown version) from C:\dev\test3\lib\site-packages\sphinxcontrib\plantuml.py
#   alabaster (0.7.10) from C:\dev\test3\lib\site-packages\alabaster\__init__.py
#   sphinxcontrib.needs (0.1) from C:\dev\test3\lib\site-packages\sphinxcontrib\needs.py
#   sphinx.ext.autodoc (1.5.3) from C:\dev\test3\lib\site-packages\sphinx\ext\autodoc.py
Traceback (most recent call last):
  File "C:\dev\test3\lib\site-packages\sphinx\cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "C:\dev\test3\lib\site-packages\sphinx\application.py", line 333, in build
    self.builder.build_update()
  File "C:\dev\test3\lib\site-packages\sphinx\builders\__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "C:\dev\test3\lib\site-packages\sphinx\builders\__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "C:\dev\test3\lib\site-packages\sphinx\builders\__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "C:\dev\test3\lib\site-packages\sphinx\builders\__init__.py", line 366, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "C:\dev\test3\lib\site-packages\sphinx\environment\__init__.py", line 1004, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "C:\dev\test3\lib\site-packages\sphinx\environment\__init__.py", line 1075, in resolve_references
    builder.app.emit('doctree-resolved', doctree, fromdocname)
  File "C:\dev\test3\lib\site-packages\sphinx\application.py", line 589, in emit
    results.append(callback(self, *args))
  File "C:\dev\test3\lib\site-packages\sphinxcontrib\needs.py", line 600, in process_spec_nodes
    all_needs = env.need_all_needs
AttributeError: 'BuildEnvironment' object has no attribute 'need_all_needs'
```

**Comment by tk0miya** [comment]
It seems a bug of the extension. Could you report this to the project?

**Comment by danielvasas** [comment]
Wow.. that was a quick reply:)

Indeed it was an issue with the extension, an update solved it. I already
closed the issue.

Cheers,
Daniel
