### ISSUE TITLE
Unable to Make HTML : .buildinfo locked.

### ISSUE THREAD

**Issue by reformstudios** [sphinx-doc/sphinx#3692]
Subject: Unable to Make  HTML : .buildinfo locked.

### Problem
'.buildinfo' cannot be overwritten (locked?) preventing make from completing.

#### Procedure to reproduce the problem
```
from cmd prompt type : "make html"
```

#### Error logs / results
```
# Sphinx version: 1.5.5
# Python version: 2.7.13 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   copying images... [ 84%] images/nukestudio/showreel/clips_after_deleting.png
#   copying images... [ 88%] images/nukestudio/showreel/new_conform_folder.png
#   copying images... [ 92%] images/nukestudio/showreel/sg_sequences.png
#   copying images... [ 96%] images/nukestudio/showreel/sg_shots.png
#   copying images... [100%] images/nukestudio/nukestudio_export_sequence_00.gif
#   
#   copying static files...
#   done
#   copying extra files...
#   done
# Loaded extensions:
#   sphinx.ext.mathjax (1.5.5) from c:\python27\lib\site-packages\sphinx\ext\mathjax.pyc
#   sphinx.ext.coverage (1.5.5) from c:\python27\lib\site-packages\sphinx\ext\coverage.pyc
#   sphinx.ext.graphviz (1.5.5) from c:\python27\lib\site-packages\sphinx\ext\graphviz.pyc
#   sphinx.ext.viewcode (1.5.5) from c:\python27\lib\site-packages\sphinx\ext\viewcode.pyc
#   sphinx.ext.todo (1.5.5) from c:\python27\lib\site-packages\sphinx\ext\todo.pyc
#   sphinx.ext.autodoc (1.5.5) from c:\python27\lib\site-packages\sphinx\ext\autodoc.pyc
#   sphinx.ext.intersphinx (1.5.5) from c:\python27\lib\site-packages\sphinx\ext\intersphinx.pyc
#   sphinx.ext.doctest (1.5.5) from c:\python27\lib\site-packages\sphinx\ext\doctest.pyc
#   alabaster (0.7.10) from c:\python27\lib\site-packages\alabaster\__init__.pyc
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\sphinx\cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "c:\python27\lib\site-packages\sphinx\application.py", line 333, in build
    self.builder.build_update()
  File "c:\python27\lib\site-packages\sphinx\builders\__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "c:\python27\lib\site-packages\sphinx\builders\__init__.py", line 325, in build
    self.finish()
  File "c:\python27\lib\site-packages\sphinx\builders\html.py", line 477, in finish
    self.finish_tasks.add_task(self.write_buildinfo)
  File "c:\python27\lib\site-packages\sphinx\util\parallel.py", line 40, in add_task
    res = task_func()
  File "c:\python27\lib\site-packages\sphinx\builders\html.py", line 667, in write_buildinfo
    with open(path.join(self.outdir, '.buildinfo'), 'w') as fp:
IOError: [Errno 13] Permission denied: u'Z:\\dev\\release\\docs\\_build\\html\\.buildinfo'

```
- <public link of unexpected result if you have>

#### Expected results
I expect Make to do its thing.

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: Windows 7
- Python version: 2.7.13
- Sphinx version: 1.5.5
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
refs: #624 

I guess this might be related with network drives.

**Comment by reformstudios** [comment]
I agree, it is. I have tested locally and it works fine.
I think the script is being executed as the "everyone" user rather than my
user (with 'w' permissions).
Is it possible to execute make 'as administrator'? I have tried, but it
doesn't work.

**Comment by jjbuck** [comment]
I have this exact same issue, but the problem exists even on a locally mounted (non-network) drive. Is this issue still active?

**Comment by tk0miya** [comment]
I added an error handler for this. It emits warning message if writing `.buildinfo` file failed.
I hope this might help you.

Thanks,
