### ISSUE TITLE
KeyError 'citation_refs' in Sphinx std domain

### ISSUE THREAD

**Issue by ViktorHaag** [sphinx-doc/sphinx#3727]
Subject: KeyError `citation_refs` in Sphinx std domain during HTML build

### Problem
- make html with Sphinx 1.6b3 exceptions during reading sources with KeyError exception inside std.py domain (line 537)

#### Procedure to reproduce the problem
```
- make of html builder build, using new-style Makefile (caught by catchall target)
```

#### Error logs / results
```
# Sphinx version: 1.6b3
# Python version: 3.6.1 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   building [mo]: targets for 0 po files that are out of date
#   
#   building [html]: targets for 87 source files that are out of date
#   
#   updating environment:
#   
#   87 added, 0 changed, 0 removed
#   
#   reading sources... [  1%] about
#   
# Loaded extensions:
#   alabaster (0.7.10) from /usr/local/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.6b3) from /usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py
#   sphinx.ext.extlinks (1.6b3) from /usr/local/lib/python3.6/site-packages/sphinx/ext/extlinks.py
#   sphinx.ext.intersphinx (1.6b3) from /usr/local/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.todo (1.6b3) from /usr/local/lib/python3.6/site-packages/sphinx/ext/todo.py
#   sphinxcontrib.actdiag (0.5.4) from /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sphinxcontrib/actdiag.py
#   sphinxcontrib.blockdiag (1.5.3) from /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sphinxcontrib/blockdiag.py
#   sphinxcontrib.nwdiag (1.0.4) from /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sphinxcontrib/nwdiag.py
#   sphinxcontrib.seqdiag (0.9.5) from /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sphinxcontrib/seqdiag.py
#   d2l_local (1.6b3) from /Users/vhaag/src/devsite/valence-api-docs/src/.extensions/d2l_local.py
#   d2l_htmlbuilder (1.6b3) from /Users/vhaag/src/devsite/valence-api-docs/src/.extensions/d2l_htmlbuilder.py
#   d2l_httpdomain (1.6b3) from /Users/vhaag/src/devsite/valence-api-docs/src/.extensions/d2l_httpdomain.py
#   d2l_phpdomain (1.6b3) from /Users/vhaag/src/devsite/valence-api-docs/src/.extensions/d2l_phpdomain.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python3.6/site-packages/sphinx/application.py", line 338, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 328, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 341, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/usr/local/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 584, in update
    self._read_serial(docnames, self.app)
  File "/usr/local/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 602, in _read_serial
    self.clear_doc(docname)
  File "/usr/local/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 323, in clear_doc
    domain.clear_doc(docname)
  File "/usr/local/lib/python3.6/site-packages/sphinx/domains/std.py", line 537, in clear_doc
    for key, docnames in list(self.data['citation_refs'].items()):
KeyError: 'citation_refs'
```

#### Expected results
- Simple `make html` of docs project.
- Build working with 1.6b2, breaks with 1.6b3

### Reproducible project / your project
- project not public

### Environment info
- OS: MacOS 10.12.4
- Python version: 3.6.1
- Sphinx version: 1.6b3
- graphviz
- project uses several extending wrappers around: HTML Builder, HTTP Domain contributed extension, PHP Domain contributed extension

**Comment by tk0miya** [comment]
Thank you for reporting.
As an investigation, could you try `make clean html` command and let me know the result please?

**Comment by ViktorHaag** [comment]
Yep! No problem; I get what appears to be the same error. Here's the output after a `make clean; make html`:

```
# Sphinx version: 1.6b3
# Python version: 3.6.1 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   building [mo]: targets for 0 po files that are out of date
#   
#   building [html]: targets for 87 source files that are out of date
#   
#   updating environment:
#   
#   87 added, 0 changed, 0 removed
#   
#   reading sources... [  1%] about
#   
# Loaded extensions:
#   alabaster (0.7.10) from /usr/local/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.6b3) from /usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py
#   sphinx.ext.extlinks (1.6b3) from /usr/local/lib/python3.6/site-packages/sphinx/ext/extlinks.py
#   sphinx.ext.intersphinx (1.6b3) from /usr/local/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.todo (1.6b3) from /usr/local/lib/python3.6/site-packages/sphinx/ext/todo.py
#   sphinxcontrib.actdiag (0.5.4) from /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sphinxcontrib/actdiag.py
#   sphinxcontrib.blockdiag (1.5.3) from /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sphinxcontrib/blockdiag.py
#   sphinxcontrib.nwdiag (1.0.4) from /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sphinxcontrib/nwdiag.py
#   sphinxcontrib.seqdiag (0.9.5) from /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sphinxcontrib/seqdiag.py
#   d2l_local (1.6b3) from /Users/vhaag/src/devsite/valence-api-docs/src/.extensions/d2l_local.py
#   d2l_htmlbuilder (1.6b3) from /Users/vhaag/src/devsite/valence-api-docs/src/.extensions/d2l_htmlbuilder.py
#   d2l_httpdomain (1.6b3) from /Users/vhaag/src/devsite/valence-api-docs/src/.extensions/d2l_httpdomain.py
#   d2l_phpdomain (1.6b3) from /Users/vhaag/src/devsite/valence-api-docs/src/.extensions/d2l_phpdomain.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python3.6/site-packages/sphinx/application.py", line 338, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 328, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 341, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/usr/local/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 584, in update
    self._read_serial(docnames, self.app)
  File "/usr/local/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 602, in _read_serial
    self.clear_doc(docname)
  File "/usr/local/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 323, in clear_doc
    domain.clear_doc(docname)
  File "/usr/local/lib/python3.6/site-packages/sphinx/domains/std.py", line 537, in clear_doc
    for key, docnames in list(self.data['citation_refs'].items()):
KeyError: 'citation_refs'
```

**Comment by ViktorHaag** [comment]
This issue is on my end, not Sphinx's -- we have an override domain for the standard domain, which I forgot to examine as part of investigating this issue. That override domain provides it's own Class-level definition for `initial_data` that does not account for (and include a default def'n for) the new `citation_refs` key.

I'm closing this issue, and apologize for anyone spending too much time looking into this. 8(

**Comment by tk0miya** [comment]
never mind!
