### ISSUE TITLE
sphinx-bootstrap-theme issue

### ISSUE THREAD

**Issue by zapme** [sphinx-doc/sphinx#3759]
Subject: sphinx-build -b html

### Problem
- Can't complete html build using bootstrap theme

#### Procedure to reproduce the problem
```
sphinx-build -b html source docs
```

#### Error logs / results
```
# Sphinx version: 1.6.1
# Python version: 2.7.5 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  4%] about
# Loaded extensions:
#   sphinx.ext.viewcode (1.6.1) from /home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx/ext/viewcode.pyc
#   sphinx.ext.todo (1.6.1) from /home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   alabaster (0.7.10) from /home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.githubpages (1.6.1) from /home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx/ext/githubpages.pyc
#   sphinx.ext.imgmath (1.6.1) from /home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx/ext/imgmath.pyc
Traceback (most recent call last):
  File "/home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx/application.py", line 338, in build
    self.builder.build_update()
  File "/home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 328, in build_update
    'out of date' % len(to_build))
  File "/home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 394, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 431, in write
    self._write_serial(sorted(docnames))
  File "/home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 440, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx/builders/html.py", line 556, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx/builders/html.py", line 940, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx/jinja2glue.py", line 176, in render
    return self.environment.get_template(template).render(context)
  File "/home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/home/users/xxxx/.virtualenvs/sphinx/lib/python2.7/site-packages/sphinx_bootstrap_theme/bootstrap/layout.html", line 40, in top-level template code
    {% set css_files = css_files + theme_css_files + bootswatch_css_custom %}
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

```
- <public link of unexpected result if you have>

#### Expected results
Successfull build

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: RHEL7
- Python version: 2.7.5 Cython
- Sphinx version: 1.6.1
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
Sorry for inconvenience. It was already fixed at #3754.
Thanks,
