### ISSUE TITLE
txtnode: AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by imphil** [sphinx-doc/sphinx#3761]
I get an error "AttributeError: 'NoneType' object has no attribute 'replace'" when building a sphinx documentation. I didn't get that one before in Sphinx 1.5. How can I find the rst code location causing this issue?

#### Error logs / results

```
.venv/bin/sphinx-build -b latex . /data/home/no56hud/src/optimsoc/objdir/doc/pdf
Running Sphinx v1.6.1
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 26 added, 0 changed, 0 removed
reading sources... [  3%] api/doxygen/group/group__dma

Exception occurred:
  File "/data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/docutils/transforms/universal.py", line 294, in apply
    txtnode.parent.replace(txtnode, nodes.Text(newtext))
AttributeError: 'NoneType' object has no attribute 'replace'
The full traceback has been saved in /tmp/sphinx-err-k7o80w65.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:18: recipe for target 'pdf' failed
make: *** [pdf] Error 1
```

```
# Sphinx version: 1.6.1
# Python version: 3.5.2 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   building [mo]: targets for 0 po files that are out of date
#   
#   building [latex]: all documents
#   
#   updating environment:
#   
#   26 added, 0 changed, 0 removed
#   
#   reading sources... [  3%] api/doxygen/group/group__dma
#   
# Loaded extensions:
#   breathe (4.6.0) from /data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/breathe/__init__.py
#   sphinx.ext.ifconfig (1.6.1) from /data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/sphinx/ext/ifconfig.py
#   alabaster (0.7.10) from /data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/alabaster/__init__.py
#   sphinx.ext.todo (1.6.1) from /data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/sphinx/ext/todo.py
#   local_toctree (unknown version) from /data/home/no56hud/src/optimsoc/doc/sphinxext/local_toctree.py
Traceback (most recent call last):
  File "/data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/sphinx/application.py", line 338, in build
    self.builder.build_update()
  File "/data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 323, in build_update
    self.build(['__all__'], to_build)
  File "/data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 341, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 584, in update
    self._read_serial(docnames, self.app)
  File "/data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 603, in _read_serial
    self.read_doc(docname, app)
  File "/data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 718, in read_doc
    pub.publish()
  File "/data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/data/home/no56hud/src/optimsoc/doc/.venv/lib/python3.5/site-packages/docutils/transforms/universal.py", line 294, in apply
    txtnode.parent.replace(txtnode, nodes.Text(newtext))
AttributeError: 'NoneType' object has no attribute 'replace'
```
- <public link of unexpected result if you have>

#### Expected results
The code compiled fine with Sphinx 1.5.x

### Reproducible project / your project
Unfortunately I'm not sure how to find the exact location in the rst source causing the issue. The full project can be built like that to give the error above:
~~~
git clone git@github.com:optimsoc/sources.git
./tools/build.py --with-docs --without-examples-fpga --without-examples-sim
~~~

### Environment info
- OS: Ubuntu xenial
- Python version: 3.5.2
- Sphinx version: 1.6.1

**Comment by tk0miya** [comment]
Same as #3709. This might be a bug of breathe.
Could you report this to their project?
