### ISSUE TITLE
Sphinx 1.6.1 introduces another TypeError

### ISSUE THREAD

**Issue by cdeil** [sphinx-doc/sphinx#3766]
As mentioned at https://github.com/sphinx-doc/sphinx/issues/3765#issuecomment-302431914 , since today I'm getting this TypeError, which I presume is the result of a change to Sphinx 1.6.1 in our CI build:
https://travis-ci.org/gammapy/gamma-cat/builds/233628422#L394

```
?25hCollecting sphinxcontrib.datatemplates
  Downloading sphinxcontrib.datatemplates-0.1.0-py2.py3-none-any.whl
Collecting gammapy from git+https://github.com/gammapy/gammapy.git#egg=gammapy
  Cloning https://github.com/gammapy/gammapy.git to /tmp/pip-build-vhzio0ha/gammapy
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vhzio0ha/gammapy/setup.py", line 61, in <module>
        cmdclassd = register_commands(PACKAGENAME, VERSION, RELEASE)
      File "/tmp/pip-build-vhzio0ha/gammapy/astropy_helpers/astropy_helpers/setup_helpers.py", line 142, in register_commands
        from .commands.build_sphinx import (AstropyBuildSphinx,
      File "/tmp/pip-build-vhzio0ha/gammapy/astropy_helpers/astropy_helpers/commands/build_sphinx.py", line 17, in <module>
        from sphinx.setup_command import BuildDoc as SphinxBuildDoc
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/site-packages/sphinx/setup_command.py", line 23, in <module>
        from sphinx.application import Sphinx
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/site-packages/sphinx/application.py", line 33, in <module>
        from sphinx.environment import BuildEnvironment
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 45, in <module>
        from sphinx.util.websupport import is_commentable
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/site-packages/sphinx/util/websupport.py", line 11, in <module>
        from sphinxcontrib.websupport.utils import is_commentable  # NOQA
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/site-packages/sphinxcontrib/websupport/__init__.py", line 15, in <module>
        from sphinxcontrib.websupport.core import WebSupport  # NOQA
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/site-packages/sphinxcontrib/websupport/core.py", line 17, in <module>
        from jinja2 import Environment, FileSystemLoader
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/site-packages/jinja2/__init__.py", line 33, in <module>
        from jinja2.environment import Environment, Template
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/site-packages/jinja2/environment.py", line 15, in <module>
        from jinja2 import nodes
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/site-packages/jinja2/nodes.py", line 19, in <module>
        from jinja2.utils import Markup
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/site-packages/jinja2/utils.py", line 486, in <module>
        MutableMapping.register(LRUCache)
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/abc.py", line 158, in register
        if issubclass(subclass, cls):
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/abc.py", line 226, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/abc.py", line 207, in __subclasscheck__
        ok = cls.__subclasshook__(subclass)
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/typing.py", line 860, in __extrahook__
        if issubclass(subclass, scls):
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/abc.py", line 207, in __subclasscheck__
        ok = cls.__subclasshook__(subclass)
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/typing.py", line 860, in __extrahook__
        if issubclass(subclass, scls):
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/abc.py", line 207, in __subclasscheck__
        ok = cls.__subclasshook__(subclass)
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/typing.py", line 851, in __extrahook__
        _valid_for_check(cls)
      File "/home/travis/miniconda/envs/gamma-cat/lib/python3.5/typing.py", line 837, in _valid_for_check
        raise TypeError("Parameterized generics cannot be used with class "
    TypeError: Parameterized generics cannot be used with class or instance checks
    
    ----------------------------------------
�[31mCommand "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vhzio0ha/gammapy/�[0m
```

Let me know if you think the error is outside Sphinx, or if there's something I can maybe to do try and help reproduce or understand the error.

**Comment by tk0miya** [comment]
Thank you for filing!
As a quick look, this might have been caused by importing jinja2 library. I feel this is very strange.
Anyway, I'll take a look later.

**Comment by cdeil** [comment]
PS: here I see similar errors, but the tracebacks are different:
* Python 3: https://travis-ci.org/gammapy/gammapy/jobs/233790108#L626
* Python 2: https://travis-ci.org/gammapy/gammapy/jobs/233790107#L665
I thought I'd mention it in case it helps you figure out the issue.

**Comment by shimizukawa** [comment]
Unfortunately, in my environment I could not reproduce that problem.
There are many related factors, so it seems difficult to narrow down the cause.
I hope someone will make the smallest sphinx-project that will reproduce the problem without using CI.

**Comment by cdeil** [comment]
Locally I see a different error with Sphinx 1.6.1, which I think is a problem in the `astropy-helpers` package we use for Sphinx extensions, so I filed an issue there: https://github.com/astropy/astropy-helpers/issues/302

**Comment by tk0miya** [comment]
Thank you for invenstigation.
Do you mean this is not a bug of Sphinx?
If so, please close this issue.

**Comment by cdeil** [comment]
> Do you mean this is not a bug of Sphinx?

No, I have no clue if this is a bug in Sphinx, or Jinja2 or one of the Sphinx extensions we have.
I don't understand the issue from the traceback.

Would suggest to leave the issue open for now, and see if others run into the same or a similar issue ...

**Comment by tk0miya** [comment]
I also could not reproduce this error.
IMO, this might be not a bug of sphinx. But I'll keep this opened for a while.
Thanks,

**Comment by bsipocz** [comment]
@tk0miya - The error I'm seeing is slightly different, but I think is related to the one above:
https://travis-ci.org/bsipocz/photutils/jobs/237944854

It only affects python2.7, I've tested the same setup with py3.6 and it works well.
I'm fairly certain that this is an issue on the sphinx/typing side. As far as I see it was added as a hard requirement in https://github.com/sphinx-doc/sphinx/pull/3144 for 1.6, thus no wonder we didn't see any issues with 1.5.6. when using the same packages etc.
I even found this old issue here, typing caused errors previously on py 2.7, too https://github.com/sphinx-doc/sphinx/issues/2470

```
Traceback (most recent call last):

  File "setup.py", line 59, in <module>

    cmdclassd = register_commands(PACKAGENAME, VERSION, RELEASE)

  File "/home/travis/build/bsipocz/photutils/astropy_helpers/astropy_helpers/setup_helpers.py", line 142, in register_commands

    from .commands.build_sphinx import (AstropyBuildSphinx,

  File "/home/travis/build/bsipocz/photutils/astropy_helpers/astropy_helpers/commands/build_sphinx.py", line 17, in <module>

    from sphinx.setup_command import BuildDoc as SphinxBuildDoc

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/sphinx/setup_command.py", line 23, in <module>

    from sphinx.application import Sphinx

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/sphinx/application.py", line 33, in <module>

    from sphinx.environment import BuildEnvironment

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 45, in <module>

    from sphinx.util.websupport import is_commentable

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/sphinx/util/websupport.py", line 11, in <module>

    from sphinxcontrib.websupport.utils import is_commentable  # NOQA

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/sphinxcontrib/websupport/__init__.py", line 15, in <module>

    from sphinxcontrib.websupport.core import WebSupport  # NOQA

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/sphinxcontrib/websupport/core.py", line 17, in <module>

    from jinja2 import Environment, FileSystemLoader

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/jinja2/__init__.py", line 33, in <module>

    from jinja2.environment import Environment, Template

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/jinja2/environment.py", line 15, in <module>

    from jinja2 import nodes

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/jinja2/nodes.py", line 19, in <module>

    from jinja2.utils import Markup

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/jinja2/utils.py", line 486, in <module>

    MutableMapping.register(LRUCache)

  File "/home/travis/miniconda/envs/test/lib/python2.7/abc.py", line 109, in register

    if issubclass(subclass, cls):

  File "/home/travis/miniconda/envs/test/lib/python2.7/abc.py", line 180, in __subclasscheck__

    if issubclass(subclass, scls):

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/typing.py", line 1229, in __subclasscheck__

    return super(GenericMeta, self).__subclasscheck__(cls)

TypeError: super() argument 1 must be type, not None
```

**Comment by tk0miya** [comment]
I investigated @cdeil's case:
I can reproduce same error when I use the combination of conda, ah_bootstrap, typing and jinja2 (without Sphinx):
```
root@a87a8158ee95:/docs/gammapy# python
Python 3.5.3 | packaged by conda-forge | (default, May 12 2017, 15:07:14)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ah_bootstrap
Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`
>>>
>>> import typing
>>> import jinja2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda/envs/gamma-cat/lib/python3.5/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/root/miniconda/envs/gamma-cat/lib/python3.5/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/root/miniconda/envs/gamma-cat/lib/python3.5/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/root/miniconda/envs/gamma-cat/lib/python3.5/site-packages/jinja2/utils.py", line 486, in <module>
    MutableMapping.register(LRUCache)
  File "/root/miniconda/envs/gamma-cat/lib/python3.5/abc.py", line 158, in register
    if issubclass(subclass, cls):
  File "/root/miniconda/envs/gamma-cat/lib/python3.5/abc.py", line 226, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/root/miniconda/envs/gamma-cat/lib/python3.5/abc.py", line 207, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/root/miniconda/envs/gamma-cat/lib/python3.5/typing.py", line 860, in __extrahook__
    if issubclass(subclass, scls):
  File "/root/miniconda/envs/gamma-cat/lib/python3.5/abc.py", line 207, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/root/miniconda/envs/gamma-cat/lib/python3.5/typing.py", line 851, in __extrahook__
    _valid_for_check(cls)
  File "/root/miniconda/envs/gamma-cat/lib/python3.5/typing.py", line 837, in _valid_for_check
    raise TypeError("Parameterized generics cannot be used with class "
TypeError: Parameterized generics cannot be used with class or instance checks
```
I don't know what is happened in this process. But it might be related with ah_bootstrap.
The error is raised only if ah_bootstrap invokes `git submodule` initialization. So I don't get the error above at second time:
```
root@a87a8158ee95:/docs/gammapy# python
Python 3.5.3 | packaged by conda-forge | (default, May 12 2017, 15:07:14)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ah_bootstrap
>>> import typing
>>> import jinja2
>>>^D
```

Anyway, I believe this is not a bug of Sphinx.

**Comment by cdeil** [comment]
@tk0miya - Thank you for your time and helpful information in your last comment!

It's clear that this isn't an issue in Sphinx, and it's unlikely that it's an issue in Jinja2, probably it's in `astropy-helpers`. So I'm closing this issue now, and left a comment in the astropy-helpers issue tracker mentioning your findings: https://github.com/astropy/astropy-helpers/issues/302#issuecomment-305976972

**Comment by Russell-Jones-OxPhys** [comment]
@bsipocz See #3976
