### ISSUE TITLE
Problem on basic theme

### ISSUE THREAD

**Issue by mia1024** [sphinx-doc/sphinx#3820]
### Problem
I tried to make a local copy of https://github.com/marczz/rest-sphinx-memo, all I did was invoking `make html` and I got the error message. The same error (`TypeError` in `basic` theme) also happens when I tried to use `cloud_sptheme` on other projects. 

#### Procedure to reproduce the problem
``` sh
make html
```

#### Error logs / results
```Python
# Sphinx version: 1.6.1
# Python version: 2.7.13 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [ 12%] Extensions
# Loaded extensions:
#   sphinx.ext.todo (1.6.1) from /usr/local/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   sphinx.ext.autodoc (1.6.1) from /usr/local/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx (1.6.1) from /usr/local/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
#   sphinx.ext.graphviz (1.6.1) from /usr/local/lib/python2.7/site-packages/sphinx/ext/graphviz.pyc
#   alabaster (0.7.10) from /usr/local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.ifconfig (1.6.1) from /usr/local/lib/python2.7/site-packages/sphinx/ext/ifconfig.pyc
#   sphinx.ext.extlinks (1.6.1) from /usr/local/lib/python2.7/site-packages/sphinx/ext/extlinks.pyc
#   sphinx.ext.imgmath (1.6.1) from /usr/local/lib/python2.7/site-packages/sphinx/ext/imgmath.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 338, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 328, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 394, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 431, in write
    self._write_serial(sorted(docnames))
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 440, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 556, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 940, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/usr/local/lib/python2.7/site-packages/sphinx/jinja2glue.py", line 176, in render
    return self.environment.get_template(template).render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/Users/jerry/Downloads/rest-sphinx-memo-master 2/source/_templates/layout.html", line 3, in top-level template code
    {% set css_files = css_files + ["_static/style.css"] %}
  File "/usr/local/lib/python2.7/site-packages/sphinx/themes/classic/layout.html", line 13, in top-level template code
    {% set script_files = script_files + ['_static/sidebar.js'] %}
  File "/usr/local/lib/python2.7/site-packages/sphinx/themes/classic/../basic/layout.html", line 128, in top-level template code
    {%- block csss %}
  File "/usr/local/lib/python2.7/site-packages/sphinx/themes/classic/../basic/layout.html", line 129, in block "csss"
    {{ css() }}
  File "/usr/local/lib/python2.7/site-packages/jinja2/sandbox.py", line 427, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/jinja2/runtime.py", line 553, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/lib/python2.7/site-packages/sphinx/themes/classic/../basic/layout.html", line 108, in template
    {%- for css in css_files %}
TypeError: 'NoneType' object is not iterable

```

### Reproducible project / your project
- Clone of https://github.com/marczz/rest-sphinx-memo

### Environment info
- OS: macOS 10.12.3
- Python version: 2.7, 3.5, 3.6 (according to error log it should be 2.7 that `make` invoked. 
- Sphinx version: 1.6.1

**Comment by tk0miya** [comment]
Sorry for inconvenience.
It might be same as #3754. And it is fixed at 1.6.2 (just released while ago!).
Please try it out.
