### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by comfix** [sphinx-doc/sphinx#3852]
I encountered this error while installing nextcloud-client
```
# Sphinx version: 1.6.1
# Python version: 3.6.1 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   checking consistency...
#   
#   done
#   
#   writing...
#   
#   owncloud.1 {
#   
#   }
#   
# Loaded extensions:
#   alabaster (0.7.10) from /usr/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.todo (1.6.1) from /usr/lib/python3.6/site-packages/sphinx/ext/todo.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/docutils/utils/error_reporting.py", line 197, in write
    self.stream.write(data)
  File "/usr/lib/python3.6/site-packages/sphinx/util/nodes.py", line 45, in write
    self.warnfunc(self._re.sub(b'\1:', text), None, '')
TypeError: sequence item 1: expected str instance, bytes found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 338, in build
    self.builder.build_update()
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 323, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 394, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.6/site-packages/sphinx/builders/manpage.py", line 102, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.6/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python3.6/site-packages/sphinx/writers/manpage.py", line 45, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.6/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.6/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.6/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 3 more times]
  File "/usr/lib/python3.6/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3.6/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/usr/lib/python3.6/site-packages/docutils/writers/manpage.py", line 622, in visit_entry
    '"table cell spanning" not supported', base_node=node)
  File "/usr/lib/python3.6/site-packages/docutils/utils/__init__.py", line 220, in warning
    return self.system_message(self.WARNING_LEVEL, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docutils/utils/__init__.py", line 191, in system_message
    self.stream.write(msg.astext() + '\n')
  File "/usr/lib/python3.6/site-packages/docutils/utils/error_reporting.py", line 203, in write
    self.encoding_errors))
  File "/usr/lib/python3.6/site-packages/sphinx/util/nodes.py", line 45, in write
    self.warnfunc(self._re.sub(b'\1:', text), None, '')
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by tk0miya** [comment]
Sorry for inconvenience.
It was fixed at v1.6.2 (refs: #3803). So please upgrade it.

Thanks,
