### ISSUE TITLE
sphinx cannot handle PEP 440-compliant docutils version number `0.14rc1`, leading to `ValueError` on import

### ISSUE THREAD

**Issue by gerritholl** [sphinx-doc/sphinx#3868]
Subject: Sphinx import fails with `ValueError: invalid literal for int() with base 10: '14rc1'` when interpreting the version for `docutils==0.14rc1`.

### Problem

Sphinx tries to determine the `docutils` version, which is currently `0.14rc1`. According to [PEP 440](https://www.python.org/dev/peps/pep-0440/), compliant version numbers must adhere to `[N!]N(.N)*[{a|b|rc}N][.postN][.devN]`.  The docutils version does, yet sphinx cannot parse it.  This feeds through to an inability to run user applications like `ipython3`, see below.

#### Procedure to reproduce the problem
```
$ ipython3
```

#### Error logs / results
```
Traceback (most recent call last):
  File "/dev/shm/gerrit/venv/stable-3.6/bin/ipython3", line 7, in <module>
    from IPython import start_ipython
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 32, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/IPython/core/completer.py", line 146, in <module>
    import jedi
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, NotFoundError, set_debug_function
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/jedi/api/__init__.py", line 23, in <module>
    from jedi.api import classes
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/jedi/api/classes.py", line 14, in <module>
    from jedi.evaluate import representation as er
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 69, in <module>
    from jedi.evaluate import representation as er
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/jedi/evaluate/representation.py", line 52, in <module>
    from jedi.evaluate import docstrings
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/jedi/evaluate/docstrings.py", line 46, in <module>
    from numpydoc.docscrape import NumpyDocString
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/numpydoc/__init__.py", line 3, in <module>
    from .numpydoc import setup
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/numpydoc/numpydoc.py", line 32, in <module>
    from sphinx.util.compat import Directive
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/sphinx/util/compat.py", line 21, in <module>
    docutils_version = tuple(int(x) for x in _du_version.split('.')[:2])
  File "/dev/shm/gerrit/venv/stable-3.6/lib/python3.6/site-packages/sphinx/util/compat.py", line 21, in <genexpr>
    docutils_version = tuple(int(x) for x in _du_version.split('.')[:2])
ValueError: invalid literal for int() with base 10: '14rc1'
```
#### Expected results

I was trying to run `ipython3` and I expect this to give me an `ipython3` shell without failing on a sphinx import.

### Environment info
- OS: Red Hat Enterprise Linux Server release 6.8 (Santiago)
- Python version: 3.6.1
- Sphinx version: 1.6.2
- Docutils version: docutils==0.14

**Comment by gerritholl** [comment]
Closing as duplicate of #3846
