### ISSUE TITLE
Impossible to complete all the actions to install boolexpr [http://www.boolexpr.org/] 

### ISSUE THREAD

**Issue by kregus0** [sphinx-doc/sphinx#3892]
Subject : Impossible to complete all the actions to install boolexpr [http://www.boolexpr.org/] 

### Problem
- I am trying to install boolexpr (boolexpr.org) on my laptop Intel Atom CPU running in amd64. Following line per line the README.rst at the time of executing make pyhtml which is the last line of Build Documentation after typing pip install sphinx on the command line I get an « Exception occurred » in the middle of the execution.

My OS version : Ubuntu 15.04.

#### Procedure to reproduce the problem
Path command line :
In /home/kevin/download/boolexpr/build
Command line : 
make pyhtml

#### Error logs / results
```
[100%] Generating stamp
running build_ext
copying build/lib.linux-x86_64-2.7/boolexpr/_boolexpr.so -> boolexpr
running build_sphinx
Running Sphinx v1.6.2

Exception occurred:
  File "/home/kevin/Downloads/BoolExpr_lib/boolexpr/build/python/boolexpr/__init__.py", line 65, in <module>
    import importlib.util
ImportError: No module named util
The full traceback has been saved in /tmp/sphinx-err-zgIFCP.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
python/CMakeFiles/pyhtml.dir/build.make:49: recipe for target 'python/CMakeFiles/pyhtml' failed
make[3]: *** [python/CMakeFiles/pyhtml] Error 1
CMakeFiles/Makefile2:143: recipe for target 'python/CMakeFiles/pyhtml.dir/all' failed
make[2]: *** [python/CMakeFiles/pyhtml.dir/all] Error 2
CMakeFiles/Makefile2:151: recipe for target 'python/CMakeFiles/pyhtml.dir/rule' failed
make[1]: *** [python/CMakeFiles/pyhtml.dir/rule] Error 2
Makefile:177: recipe for target 'pyhtml' failed
make: *** [pyhtml] Error 2
kevin@caspian:~/Downloads/BoolExpr_lib/boolexpr/build$
```

The content of the file mentionned above is present below : 
```
Sphinx version: 1.6.2
Python version: 2.7.9 (CPython)
Docutils version: 0.13.1 release
Jinja2 version: 2.9.6
Last messages:
Loaded extensions:
Traceback (most recent call last):
  File "/home/kevin/.local/lib/python2.7/site-packages/sphinx/setup_command.py", line 191, in run     warningiserror=self.warning_is_error)
  File "/home/kevin/.local/lib/python2.7/site-packages/sphinx/application.py", line 168, in __init__     confoverrides or {}, self.tags)
  File "/home/kevin/.local/lib/python2.7/site-packages/sphinx/config.py", line 150, in __init__     execfile_(filename, config)
  File "/home/kevin/.local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_     exec_(code, _globals)
  File "/home/kevin/.local/lib/python2.7/site-packages/six.py", line 699, in exec_     exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 24, in <module>
  File "/home/kevin/Downloads/BoolExpr_lib/boolexpr/build/python/boolexpr/__init__.py", line 65, in <module>     import importlib.util
ImportError: No module named util
```

### Environment info
- OS: Ubuntu 15.04 this is the output of /etc/issue
- Python version: 2.7.9 this is the output of python -V
- Sphinx version: 2.0.4 –id64-release (r3135) this is the output of searchd --help

**Comment by tk0miya** [comment]
It seems python2 does not provides `importlib.util` package.
Is boolexpr supports python2?

Anyway, this might be an issue of boolexpr, not sphinx's.
So please ask this to boolexpr team.
Thanks,

**Comment by tk0miya** [comment]
I'm closing this now because it seems no updates.
Feel free to reopen this if you still have this problem.

Thanks,
