### ISSUE TITLE
Encoding error: 'ascii' codec can't decode byte 0xc4 in position 13: ordinal not in range(128)

### ISSUE THREAD

**Issue by vedranmiletic** [sphinx-doc/sphinx#3902]
### Problem
Compiling LaTeX PDF from https://bitbucket.org/infuniri/restructuredhgwiki with results in Econding error.

#### Procedure to reproduce the problem
```
make latexpdf
```

#### Error logs / results
```
# Sphinx version: 1.5.6                             
# Python version: 2.7.13 (CPython)                                                            # Docutils version: 0.13.1 release                  
# Jinja2 version: 2.9.6                                                                       # Last messages:                                    
#   materijali/spamassasin-spam-filter                                                        #   materijali/bind9-dns-sustav                     
#   materijali/avahi-zeroconf                                                                 #   materijali/screen-tmux-multipleksiranje-terminala                                         
#   kolegiji/RM-RiTeh                                                                         #   kolegiji/NRM-RiTeh                              
#   materijali/index                                                                          #                                                   
#   resolving references...                                                                   #   writing...                                      
# Loaded extensions:                                                                          #   sphinx.ext.mathjax (1.5.6) from /usr/lib/python2.7/dist-packages/sphinx/ext/mathjax.pyc   
#   sphinx.ext.graphviz (1.5.6) from /usr/lib/python2.7/dist-packages/sphinx/ext/graphviz.pyc #   sphinx.ext.todo (1.5.6) from /usr/lib/python2.7/dist-packages/sphinx/ext/todo.pyc         
#   alabaster (0.7.8) from /usr/lib/python2.7/dist-packages/alabaster/__init__.pyc            Traceback (most recent call last):                  
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 296, in main                    app.build(opts.force_all, filenames)            
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 333, in build               self.builder.build_update()                     
  File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 246, in build_update                                                  
    self.build(['__all__'], to_build)                                                           File "/usr/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 322, in build     
    self.write(docnames, list(updated_docnames), method)                                        File "/usr/lib/python2.7/dist-packages/sphinx/builders/latex.py", line 130, in write        
    docwriter.write(doctree, destination)                                                       File "/usr/lib/python2.7/dist-packages/docutils/writers/__init__.py", line 80, in write     
    self.translate()                                                                            File "/usr/lib/python2.7/dist-packages/sphinx/writers/latex.py", line 162, in translate     
    self.output = visitor.astext()                                                              File "/usr/lib/python2.7/dist-packages/sphinx/writers/latex.py", line 576, in astext        
    return LaTeXRenderer().render(DEFAULT_TEMPLATE, self.elements)                              File "/usr/lib/python2.7/dist-packages/sphinx/util/template.py", line 25, in render         
    return self.env.get_template(template_name).render(context)                                 File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render         
    return self.environment.handle_exception(exc_info, True)                                    File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)                                                            File "/usr/share/sphinx/templates/latex/content.tex_t", line 51, in top-level template code 
    <%= printindex %>               
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 13: ordinal not in range(128)
```

#### Expected results
Get LaTeX PDF without any errors.

### Reproducible project / your project
https://bitbucket.org/infuniri/restructuredhgwiki

### Environment info
- OS: Debian 9
- Python version: Python 2.7.13 (doesn't happen in 3.5.3)
- Sphinx version: 1.5.6 (also occurs in 1.6.2)
- TeX Live 2017 (date tag: 20170629)

**Comment by tk0miya** [comment]
I can't reproduce this on my local. Is there any additional procedure or setting?
```
$ docker run -it --rm tk0miya/sphinx-html bash
root@a32daee80484:/docs# git clone https://bitbucket.org/infuniri/restructuredhgwiki.git
(snip)
root@a32daee80484:/docs# cd restructuredhgwiki/
root@a32daee80484:/docs/restructuredhgwiki# pip3 install sphinx_bootstrap_theme
(snip)
root@a32daee80484:/docs/restructuredhgwiki# pip3 install sphinx==1.5.6
(snip)
root@a32daee80484:/docs/restructuredhgwiki# make clean latex
rm -rf build/*
sphinx-build -b latex -d build/doctrees -D latex_paper_size=a4  source build/latex
Running Sphinx v1.5.6
making output directory...
loading translations [hr]... done
loading pickled environment... not yet created
WARNING: latex_paper_size is deprecated. Define a latex_elements dict with a 'papersize' key.
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 126 added, 0 changed, 0 removed
reading sources... [100%] materijali/yum-rpm-upravljanje-paketima-operacijskog-sustava
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing reStructuredHgWiki.tex... index kolegiji/index kolegiji/OI1 materijali/linux-unix-povijest-osnove materijali/oi1-linux-upravljanje-datotecnim-sustavom materijali/oi1-linux-upravljanje-datotecnim-sustavom-2 materijali/oi1-regularni-izrazi-konacni-automati materijali/oi1-perl kolegiji/OS1 materijali/linux-cli-uvod materijali/linux-direktoriji-mkdir-pwd-cd materijali/linux-datoteke-touch-rm-cp-mv materijali/emacs-text-datoteke materijali/grep-sed-awk-tr materijali/linux-cijevi-preusmjeravanje-ulaza-izlaza materijali/linux-arhiviranje-komprimiranje materijali/linux-shell-varijable-povijest materijali/linux-procesi materijali/linux-disk-particija-filesystem materijali/linux-inode-poveznice materijali/linux-dozvole-datoteka materijali/linux-tipovi-datoteka kolegiji/OS2 materijali/python-osnove-sintakse materijali/python-input-output materijali/python-funkcije-klase materijali/python-modularizacija materijali/python-standardna-biblioteka materijali/python-modul-sys materijali/strace-ltrace-sucelja-operacijskog-sustava materijali/python-modul-time materijali/python-timing-benchmarking materijali/python-modul-os materijali/python-modul-subprocess materijali/python-modul-signal materijali/python-modul-socket materijali/python-modul-select materijali/python-modul-xmlrpc materijali/python-modul-locale materijali/python-modul-fcntl materijali/paralelno-distribuirano-heterogeno-racunarstvo-pojmovi materijali/python-modul-threading materijali/python-modul-multiprocessing materijali/python-modul-mpi4py-osnove materijali/python-modul-mpi4py-komunikacija-tocka-do-tocke materijali/python-modul-mpi4py-kolektivna-komunikacija kolegiji/PPHS materijali/python-testiranje materijali/python-dokumentiranje materijali/git-upravljanje-verzijama materijali/python-modul-numpy materijali/python-modul-scipy materijali/python-modul-matplotlib materijali/python-okvir-waf materijali/python-modul-pycuda-osnove materijali/python-modul-pycuda-zbrajanje-vektora materijali/python-modul-pycuda-redukcija materijali/python-modul-pycuda-matrice materijali/python-modul-pycuda-vektorski-tipovi materijali/python-modul-pycuda-funkcije-uredjaja-domacina materijali/python-modul-pycuda-biblioteke-funkcija materijali/python-modul-pycuda-hijerarhija-memorije materijali/python-modul-pycuda-otklanjanje-gresaka materijali/python-modul-pycuda-profiliranje-optimizacija materijali/python-modul-pycuda-tokovi-asinkrone-operacije materijali/python-modul-pycuda-multi-gpu materijali/python-modul-pyopencl kolegiji/DS materijali/python-modul-mpi4py-komunikatori-grupe materijali/python-modul-mpi4py-dinamicko-upravljanje-procesima materijali/python-modul-mpi4py-jednostrana-komunikacija materijali/python-modul-mpi4py-paralelni-ulaz-izlaz materijali/python-modul-mpi4py-upravljanje-okolinom kolegiji/RM1 materijali/emulator-core-graficko-sucelje materijali/ping-traceroute-nestat-analiza-mreze materijali/wireshark-snimanje-prometa materijali/wireshark-filtriranje-paketa materijali/quagga-usmjeravanje materijali/ifconfig-konfiguracija-mreznih-sucelja materijali/emulator-core-konfiguracija-cvora materijali/emulator-core-subnetiranje materijali/dhcp-posluzitelj-klijent materijali/click-programska-osnova-usmjerivaca kolegiji/RM2 materijali/simulator-ns3-pojmovi materijali/simulator-ns3-povezivanje-cvorova materijali/simulator-ns3-topologije materijali/simulator-ns3-mrezne-aplikacije-promet materijali/simulator-ns3-modeli-gresaka materijali/simulator-ns3-redovi-cekanja materijali/simulator-ns3-tcp-upravljanje-zagusenjem materijali/programiranje-mreznih-aplikacija materijali/curl-protokoli-aplikacijske-razine materijali/openssl-kriptografski-algoritmi materijali/iptables-vatrozid materijali/iptables-prevodjenje-adresa materijali/nmap-analiza-ranjivosti kolegiji/UMS materijali/linux-korisnici-grupe materijali/yum-rpm-upravljanje-paketima-operacijskog-sustava materijali/grub-pokretanje-sustava materijali/systemd-systemctl-upravljanje-uslugama-operacijskog-sustava materijali/systemd-journalctl-pracenje-dogadjaja-operacijskog-sustava materijali/systemd-cron-automatizacija-zadaca-operacijskog-sustava materijali/selinux-mandantna-kontrola-pristupa materijali/linux-kernel-osnove materijali/procfs-sysfs-informacije-konfiguracija materijali/upravljacki-pogrami-hardvera materijali/gcc-gxx-make-prevodjenje-programa materijali/nabavka-prevodjenje-instalacija-softvera-otvorenog-koda materijali/api-abi-kompatibilnost materijali/vlasnicki-softveri-posebne-namjene-i-racunalne-igre materijali/openssh-kljucevi-autentikacija materijali/apache-web-posluzitelj materijali/mariadb-sustav-za-upravljanje-bazom-podataka materijali/apache-wodpress-mediawiki-instalacija-web-aplikacija materijali/postfix-procmail-smtp-posluzitelj materijali/dovecot-pop3-imap-posluzitelj materijali/spamassasin-spam-filter materijali/bind9-dns-sustav materijali/avahi-zeroconf materijali/screen-tmux-multipleksiranje-terminala kolegiji/RM-RiTeh kolegiji/NRM-RiTeh materijali/index
resolving references...
writing... done
copying TeX support files...
done
build succeeded, 1 warning.

Build finished; the LaTeX files are in build/latex.
Run `make' in that directory to run these through (pdf)latex (use `make latexpdf' here to do that automatically).
```

**Comment by vedranmiletic** [comment]
@tk0miya Yes, you are using `pip3` instead of `pip`. This is Python 2-only issue.

**Comment by tk0miya** [comment]
OMG, I missed your report...

>Python version: Python 2.7.13 (doesn't happen in 3.5.3)

I'll take a look again.

**Comment by tk0miya** [comment]
Thanks, I reproduced!
```
$ docker run -it --rm tk0miya/sphinx-html bash
root@03714e86b19c:/docs# apt install python python-pip
root@03714e86b19c:/docs# git clone https://bitbucket.org/infuniri/restructuredhgwiki.git
root@03714e86b19c:/docs# cd restructuredhgwiki/
root@03714e86b19c:/docs/restructuredhgwiki# pip install Sphinx==1.5.6 sphinx_bootstrap_theme
root@03714e86b19c:/docs/restructuredhgwiki# make clean latex SPHINXOPTS=-T
rm -rf build/*
sphinx-build -b latex -d build/doctrees -D latex_paper_size=a4 -T source build/latex
Running Sphinx v1.5.6
making output directory...
loading translations [hr]... done
loading pickled environment... not yet created
WARNING: latex_paper_size is deprecated. Define a latex_elements dict with a 'papersize' key.
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 126 added, 0 changed, 0 removed
reading sources... [100%] materijali/yum-rpm-upravljanje-paketima-operacijskog-sustava
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing reStructuredHgWiki.tex... index kolegiji/index kolegiji/OI1 materijali/linux-unix-povijest-osnove materijali/oi1-linux-upravljanje-datotecnim-sustavom materijali/oi1-linux-upravljanje-datotecnim-sustavom-2 materijali/oi1-regularni-izrazi-konacni-automati materijali/oi1-perl kolegiji/OS1 materijali/linux-cli-uvod materijali/linux-direktoriji-mkdir-pwd-cd materijali/linux-datoteke-touch-rm-cp-mv materijali/emacs-text-datoteke materijali/grep-sed-awk-tr materijali/linux-cijevi-preusmjeravanje-ulaza-izlaza materijali/linux-arhiviranje-komprimiranje materijali/linux-shell-varijable-povijest materijali/linux-procesi materijali/linux-disk-particija-filesystem materijali/linux-inode-poveznice materijali/linux-dozvole-datoteka materijali/linux-tipovi-datoteka kolegiji/OS2 materijali/python-osnove-sintakse materijali/python-input-output materijali/python-funkcije-klase materijali/python-modularizacija materijali/python-standardna-biblioteka materijali/python-modul-sys materijali/strace-ltrace-sucelja-operacijskog-sustava materijali/python-modul-time materijali/python-timing-benchmarking materijali/python-modul-os materijali/python-modul-subprocess materijali/python-modul-signal materijali/python-modul-socket materijali/python-modul-select materijali/python-modul-xmlrpc materijali/python-modul-locale materijali/python-modul-fcntl materijali/paralelno-distribuirano-heterogeno-racunarstvo-pojmovi materijali/python-modul-threading materijali/python-modul-multiprocessing materijali/python-modul-mpi4py-osnove materijali/python-modul-mpi4py-komunikacija-tocka-do-tocke materijali/python-modul-mpi4py-kolektivna-komunikacija kolegiji/PPHS materijali/python-testiranje materijali/python-dokumentiranje materijali/git-upravljanje-verzijama materijali/python-modul-numpy materijali/python-modul-scipy materijali/python-modul-matplotlib materijali/python-okvir-waf materijali/python-modul-pycuda-osnove materijali/python-modul-pycuda-zbrajanje-vektora materijali/python-modul-pycuda-redukcija materijali/python-modul-pycuda-matrice materijali/python-modul-pycuda-vektorski-tipovi materijali/python-modul-pycuda-funkcije-uredjaja-domacina materijali/python-modul-pycuda-biblioteke-funkcija materijali/python-modul-pycuda-hijerarhija-memorije materijali/python-modul-pycuda-otklanjanje-gresaka materijali/python-modul-pycuda-profiliranje-optimizacija materijali/python-modul-pycuda-tokovi-asinkrone-operacije materijali/python-modul-pycuda-multi-gpu materijali/python-modul-pyopencl kolegiji/DS materijali/python-modul-mpi4py-komunikatori-grupe materijali/python-modul-mpi4py-dinamicko-upravljanje-procesima materijali/python-modul-mpi4py-jednostrana-komunikacija materijali/python-modul-mpi4py-paralelni-ulaz-izlaz materijali/python-modul-mpi4py-upravljanje-okolinom kolegiji/RM1 materijali/emulator-core-graficko-sucelje materijali/ping-traceroute-nestat-analiza-mreze materijali/wireshark-snimanje-prometa materijali/wireshark-filtriranje-paketa materijali/quagga-usmjeravanje materijali/ifconfig-konfiguracija-mreznih-sucelja materijali/emulator-core-konfiguracija-cvora materijali/emulator-core-subnetiranje materijali/dhcp-posluzitelj-klijent materijali/click-programska-osnova-usmjerivaca kolegiji/RM2 materijali/simulator-ns3-pojmovi materijali/simulator-ns3-povezivanje-cvorova materijali/simulator-ns3-topologije materijali/simulator-ns3-mrezne-aplikacije-promet materijali/simulator-ns3-modeli-gresaka materijali/simulator-ns3-redovi-cekanja materijali/simulator-ns3-tcp-upravljanje-zagusenjem materijali/programiranje-mreznih-aplikacija materijali/curl-protokoli-aplikacijske-razine materijali/openssl-kriptografski-algoritmi materijali/iptables-vatrozid materijali/iptables-prevodjenje-adresa materijali/nmap-analiza-ranjivosti kolegiji/UMS materijali/linux-korisnici-grupe materijali/yum-rpm-upravljanje-paketima-operacijskog-sustava materijali/grub-pokretanje-sustava materijali/systemd-systemctl-upravljanje-uslugama-operacijskog-sustava materijali/systemd-journalctl-pracenje-dogadjaja-operacijskog-sustava materijali/systemd-cron-automatizacija-zadaca-operacijskog-sustava materijali/selinux-mandantna-kontrola-pristupa materijali/linux-kernel-osnove materijali/procfs-sysfs-informacije-konfiguracija materijali/upravljacki-pogrami-hardvera materijali/gcc-gxx-make-prevodjenje-programa materijali/nabavka-prevodjenje-instalacija-softvera-otvorenog-koda materijali/api-abi-kompatibilnost materijali/vlasnicki-softveri-posebne-namjene-i-racunalne-igre materijali/openssh-kljucevi-autentikacija materijali/apache-web-posluzitelj materijali/mariadb-sustav-za-upravljanje-bazom-podataka materijali/apache-wodpress-mediawiki-instalacija-web-aplikacija materijali/postfix-procmail-smtp-posluzitelj materijali/dovecot-pop3-imap-posluzitelj materijali/spamassasin-spam-filter materijali/bind9-dns-sustav materijali/avahi-zeroconf materijali/screen-tmux-multipleksiranje-terminala kolegiji/RM-RiTeh kolegiji/NRM-RiTeh materijali/index
resolving references...
writing...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 246, in build_update
    self.build(['__all__'], to_build)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/latex.py", line 130, in write
    docwriter.write(doctree, destination)
  File "/usr/local/lib/python2.7/dist-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/writers/latex.py", line 162, in translate
    self.output = visitor.astext()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/writers/latex.py", line 576, in astext
    return LaTeXRenderer().render(DEFAULT_TEMPLATE, self.elements)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/util/template.py", line 25, in render
    return self.env.get_template(template_name).render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/templates/latex/content.tex_t", line 51, in top-level template code
    <%= printindex %>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 13: ordinal not in range(128)

Encoding error:
'ascii' codec can't decode byte 0xc4 in position 13: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-ifYghW.log, if you want to report the issue to the developers.
Makefile:99: recipe for target 'latex' failed
make: *** [latex] Error 1
```

**Comment by tk0miya** [comment]
It seems the document does not expect python2.x series. The author setting contains non-ASCII character, but it does not have `u` prefix.
```
latex_documents = [
  ('index', 'reStructuredHgWiki.tex', 'reStructuredHgWiki Book',
   'Vedran Miletić', 'manual'),
]
```
https://bitbucket.org/infuniri/restructuredhgwiki/src/208f8fb983be3702d1633c2a7eb3dc1b8a354378/source/conf.py?at=master&fileviewer=file-view-default#conf.py-217

Please update your document settings.
Thanks,

**Comment by vedranmiletic** [comment]
Indeed, I will fix it. Is there anything that Sphinx can do to detect such case and emit a nicer error to the user?

**Comment by tk0miya** [comment]
I just added barrier code at 4791c35.

**Comment by vedranmiletic** [comment]
Thanks!
