### ISSUE TITLE
Encoding error: "'ascii' codec can't encode characters in position 0-9" when literalinclude target file doesn't exist.

### ISSUE THREAD

**Issue by tcsh** [sphinx-doc/sphinx#3913]
Subject: Encoding error: "'ascii' codec can't encode characters in position 0-9" when literalinclude target file doesn't exist.

### Problem
- When literalinclude target file doesn't exist, sphinx-build failed build.

#### Procedure to reproduce the problem
```
remove  literalinclude target file.
make html
sphinx failed build.
```

#### Error logs / results
```
Encoding error:
'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)
The full traceback has been saved in /var/folders/2z/4zn2lj154bx84wntcv9v_dlr0000gr/T/sphinx-err-GsJzoX.log, if you want to report the issue to the developers.

(/var/folders/2z/4zn2lj154bx84wntcv9v_dlr0000gr/T/sphinx-err-GsJzoX.log)
# Sphinx version: 1.6.2
# Python version: 2.7.10 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   reading sources... [ 41%] describe-flow-logs/index
#   reading sources... [ 42%] describe-fpga-images/index
#   reading sources... [ 42%] describe-host-reservation-offerings/index
#   reading sources... [ 43%] describe-host-reservations/index
#   reading sources... [ 43%] describe-hosts/index
#   reading sources... [ 44%] describe-iam-instance-profile-associations/index
#   reading sources... [ 44%] describe-id-format/index
#   reading sources... [ 44%] describe-identity-id-format/index
#   reading sources... [ 45%] describe-image-attribute/index
#   reading sources... [ 45%] describe-images/index
# Loaded extensions:
#   sphinx.ext.viewcode (1.6.2) from /Library/Python/2.7/site-packages/sphinx/ext/viewcode.pyc
#   sphinx.ext.todo (1.6.2) from /Library/Python/2.7/site-packages/sphinx/ext/todo.pyc
#   alabaster (0.7.10) from /Library/Python/2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.ifconfig (1.6.2) from /Library/Python/2.7/site-packages/sphinx/ext/ifconfig.pyc
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/Library/Python/2.7/site-packages/sphinx/builders/__init__.py", line 328, in build_update
    'out of date' % len(to_build))
  File "/Library/Python/2.7/site-packages/sphinx/builders/__init__.py", line 341, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/Library/Python/2.7/site-packages/sphinx/environment/__init__.py", line 584, in update
    self._read_serial(docnames, self.app)
  File "/Library/Python/2.7/site-packages/sphinx/environment/__init__.py", line 603, in _read_serial
    self.read_doc(docname, app)
  File "/Library/Python/2.7/site-packages/sphinx/environment/__init__.py", line 724, in read_doc
    pub.publish()
  File "/Library/Python/2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Library/Python/2.7/site-packages/sphinx/io.py", line 74, in read
    self.parse()
  File "/Library/Python/2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/Library/Python/2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Python/2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/states.py", line 2980, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Python/2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Python/2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/states.py", line 1146, in indent
    elements = self.block_quote(indented, line_offset)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/states.py", line 1161, in block_quote
    self.nested_parse(blockquote_lines, line_offset, blockquote)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Python/2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Python/2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/states.py", line 2318, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "/Library/Python/2.7/site-packages/sphinx/directives/code.py", line 459, in run
    return [document.reporter.warning(str(exc), line=self.lineno)]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)
```
- <public link of unexpected result if you have>

#### Expected results
make html successfully.

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: Mac
- Python version: 2.7.10 
- Sphinx version: 1.6.2

**Comment by tcsh** [comment]
This issue have been fixed 1.6.3.
Thx!
