### ISSUE TITLE
sphinx 1.6.2/3: pdflatex error: ! Undefined control sequence. \maketitle ...tnoterule \relax \ifsphinxpdfoutput

### ISSUE THREAD

**Issue by sebhub** [sphinx-doc/sphinx#3914]
### Problem

PDF generation is broken since an update to sphinx 1.6.2/3 (it worked with 1.3 for example).

#### Procedure to reproduce the problem
```
git clone git://git.rtems.org/rtems-docs.git
cd rtems-docs
./waf configure --pdf
./waf
```

#### Error logs / results
```
/usr/bin/pdflatex -shell-escape  /home/EB/sebastian_h/git-rtems-docs/build/user/latex/user.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/TeX Live for SUSE Linux) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
(/home/EB/sebastian_h/git-rtems-docs/build/user/latex/user.tex
LaTeX2e <2015/01/01> patch level 2
Babel <3.9m> and hyphenation patterns for 79 languages loaded.
(./sphinxmanual.cls
Document Class: sphinxmanual 2017/03/26 v1.6 Document class (Sphinx manual)
(/usr/share/texmf/tex/latex/base/report.cls
Document Class: report 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texmf/tex/latex/base/size11.clo)))
(/usr/share/texmf/tex/latex/base/inputenc.sty
(/usr/share/texmf/tex/latex/base/utf8.def
(/usr/share/texmf/tex/latex/base/t1enc.dfu)
(/usr/share/texmf/tex/latex/base/ot1enc.dfu)
(/usr/share/texmf/tex/latex/base/omsenc.dfu)))
(/usr/share/texmf/tex/latex/cmap/cmap.sty)
(/usr/share/texmf/tex/latex/base/fontenc.sty
(/usr/share/texmf/tex/latex/base/t1enc.def)<<t1.cmap>>)
(/usr/share/texmf/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texmf/tex/latex/amsmath/amstext.sty
(/usr/share/texmf/tex/latex/amsmath/amsgen.sty))
(/usr/share/texmf/tex/latex/amsmath/amsbsy.sty)
(/usr/share/texmf/tex/latex/amsmath/amsopn.sty))
(/usr/share/texmf/tex/latex/amsfonts/amssymb.sty
(/usr/share/texmf/tex/latex/amsfonts/amsfonts.sty))
(/usr/share/texmf/tex/generic/babel/babel.sty
(/usr/share/texmf/tex/generic/babel-english/english.ldf
(/usr/share/texmf/tex/generic/babel/babel.def)))
(/usr/share/texmf/tex/latex/psnfss/times.sty)
(/usr/share/texmf/tex/latex/fncychap/fncychap.sty) (./sphinx.sty
(/usr/share/texmf/tex/generic/oberdiek/ltxcmds.sty)
(/usr/share/texmf/tex/latex/graphics/graphicx.sty
(/usr/share/texmf/tex/latex/graphics/keyval.sty)
(/usr/share/texmf/tex/latex/graphics/graphics.sty
(/usr/share/texmf/tex/latex/graphics/trig.sty)
(/usr/share/texmf/tex/latex/latexconfig/graphics.cfg)
(/usr/share/texmf/tex/latex/pdftex-def/pdftex.def
(/usr/share/texmf/tex/generic/oberdiek/infwarerr.sty))))
(/usr/share/texmf/tex/latex/fancyhdr/fancyhdr.sty)
(/usr/share/texmf/tex/latex/base/textcomp.sty
(/usr/share/texmf/tex/latex/base/ts1enc.def
(/usr/share/texmf/tex/latex/base/ts1enc.dfu)))
(/usr/share/texmf/tex/latex/titlesec/titlesec.sty)
(/usr/share/texmf/tex/latex/tabulary/tabulary.sty
(/usr/share/texmf/tex/latex/tools/array.sty))
(/usr/share/texmf/tex/latex/tools/longtable.sty)
(/usr/share/texmf/tex/latex/varwidth/varwidth.sty) (./sphinxmulticell.sty)
(/usr/share/texmf/tex/latex/base/makeidx.sty)
(/usr/share/texmf/tex/latex/framed/framed.sty)
(/usr/share/texmf/tex/latex/xcolor/xcolor.sty
(/usr/share/texmf/tex/latex/latexconfig/color.cfg))
(/usr/share/texmf/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz)) (./footnotehyper-sphinx.sty)
(/usr/share/texmf/tex/latex/float/float.sty)
(/usr/share/texmf/tex/latex/wrapfig/wrapfig.sty)
(/usr/share/texmf/tex/latex/parskip/parskip.sty)
(/usr/share/texmf/tex/latex/base/alltt.sty)
(/usr/share/texmf/tex/latex/upquote/upquote.sty)
(/usr/share/texmf/tex/latex/capt-of/capt-of.sty)
(/usr/share/texmf/tex/latex/needspace/needspace.sty) (./sphinxhighlight.sty)
(/usr/share/texmf/tex/latex/oberdiek/kvoptions.sty
(/usr/share/texmf/tex/generic/oberdiek/kvsetkeys.sty
(/usr/share/texmf/tex/generic/oberdiek/etexcmds.sty
(/usr/share/texmf/tex/generic/oberdiek/ifluatex.sty)))))
(/usr/share/texmf/tex/latex/geometry/geometry.sty
(/usr/share/texmf/tex/generic/oberdiek/ifpdf.sty)
(/usr/share/texmf/tex/generic/oberdiek/ifvtex.sty)
(/usr/share/texmf/tex/generic/ifxetex/ifxetex.sty))
(/usr/share/texmf/tex/latex/hyperref/hyperref.sty
(/usr/share/texmf/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/share/texmf/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/share/texmf/tex/latex/oberdiek/auxhook.sty)
(/usr/share/texmf/tex/latex/hyperref/pd1enc.def)
(/usr/share/texmf/tex/latex/latexconfig/hyperref.cfg)
(/usr/share/texmf/tex/latex/hyperref/puenc.def)
(/usr/share/texmf/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/share/texmf/tex/latex/hyperref/hpdftex.def
(/usr/share/texmf/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/share/texmf/tex/latex/oberdiek/hypcap.sty) (./rtemsstyle.sty
(./minted.sty (/usr/share/texmf/tex/latex/base/ifthen.sty)
(/usr/share/texmf/tex/latex/tools/calc.sty)
(/usr/share/texmf/tex/latex/ifplatform/ifplatform.sty
(/usr/share/texmf/tex/generic/oberdiek/catchfile.sty) (./user.w18))
(/usr/share/texmf/tex/latex/etoolbox/etoolbox.sty)
(/usr/share/texmf/tex/generic/xstring/xstring.sty
(/usr/share/texmf/tex/generic/xstring/xstring.tex))
(/usr/share/texmf/tex/latex/lineno/lineno.sty)
(/usr/share/texmf/tex/latex/psnfss/t1pcr.fd)) (./_minted-user/default.pygstyle)
 (/usr/share/texmf/tex/latex/enumitem/enumitem.sty)
(/usr/share/texmf/tex/latex/psnfss/charter.sty) (./rtemsextrafonts.sty
(/usr/share/texmf/tex/latex/lato/lato.sty
(/usr/share/texmf/tex/latex/slantsc/slantsc.sty))
(/usr/share/texmf/tex/latex/inconsolata/inconsolata.sty
`inconsolata-zi4' v1.05, 2014/06/22 Text macros for Inconsolata (msharpe))))
Writing index file user.idx
/usr/bin/pygmentize
(./user.aux

LaTeX Warning: Label `hosts/index:host-computer' multiply defined.


LaTeX Warning: Label `installation/index:developer' multiply defined.


LaTeX Warning: Label `installation/index:development-version' multiply defined.



LaTeX Warning: Label `installation/index:posix-host-tools-chain' multiply defin
ed.

) (/usr/share/texmf/tex/latex/base/ts1cmr.fd)
(/usr/share/texmf/tex/latex/psnfss/t1bch.fd)
(/usr/share/texmf/tex/context/base/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texmf/tex/latex/oberdiek/epstopdf-base.sty
(/usr/share/texmf/tex/latex/oberdiek/grfext.sty)
(/usr/share/texmf/tex/latex/latexconfig/epstopdf-sys.cfg))
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(/usr/share/texmf/tex/latex/hyperref/nameref.sty
(/usr/share/texmf/tex/generic/oberdiek/gettitlestring.sty)) (./user.out)
(./user.out) (./_minted-user/default-pyg-prefix.pygstyle)
! Undefined control sequence.
\maketitle ...tnoterule \relax \ifsphinxpdfoutput 
                                                  \begingroup \def \\{, } \p...
l.69 \maketitle
               
? 
! Emergency stop.
\maketitle ...tnoterule \relax \ifsphinxpdfoutput 
                                                  \begingroup \def \\{, } \p...
l.69 \maketitle
               
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on user.log.
```

### Environment info
- OS: Opensuse Leap 42.2
- Python version: 3.4.6 or 2.7.13
- Sphinx version: 1.6.3

**Comment by sebhub** [comment]
Known to work version is 1.5.6.

**Comment by tk0miya** [comment]
I tried to reproduce the error. But I got following error instead:
```
...
[ 91/101] Compiling build/rsb/latex/rsb.tex
first pass on pdflatex
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
/usr/local/bin/pygmentize

This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
/usr/local/bin/pygmentize

Waf: Leaving directory `/docs/rtems-docs/build'
Build failed
Traceback (most recent call last):
  File "/docs/rtems-docs/.waf3-1.9.7-d27222240ebc8bcbca7fcd8f4ae914fb/waflib/Task.py", line 145, in process
    ret=self.run()
  File "/docs/rtems-docs/.waf3-1.9.7-d27222240ebc8bcbca7fcd8f4ae914fb/waflib/Tools/tex.py", line 201, in run
    self.call_latex()
  File "/docs/rtems-docs/.waf3-1.9.7-d27222240ebc8bcbca7fcd8f4ae914fb/waflib/Tools/tex.py", line 231, in call_latex
    self.check_status('error when calling latex',self.texfun())
  File "/docs/rtems-docs/.waf3-1.9.7-d27222240ebc8bcbca7fcd8f4ae914fb/waflib/Tools/tex.py", line 116, in check_status
    raise Errors.WafError('%r command exit status %r'%(msg,retcode))
waflib.Errors.WafError: 'error when calling latex' command exit status 1

Traceback (most recent call last):
  File "/docs/rtems-docs/.waf3-1.9.7-d27222240ebc8bcbca7fcd8f4ae914fb/waflib/Task.py", line 145, in process
    ret=self.run()
  File "/docs/rtems-docs/.waf3-1.9.7-d27222240ebc8bcbca7fcd8f4ae914fb/waflib/Tools/tex.py", line 201, in run
    self.call_latex()
  File "/docs/rtems-docs/.waf3-1.9.7-d27222240ebc8bcbca7fcd8f4ae914fb/waflib/Tools/tex.py", line 231, in call_latex
    self.check_status('error when calling latex',self.texfun())
  File "/docs/rtems-docs/.waf3-1.9.7-d27222240ebc8bcbca7fcd8f4ae914fb/waflib/Tools/tex.py", line 116, in check_status
    raise Errors.WafError('%r command exit status %r'%(msg,retcode))
waflib.Errors.WafError: 'error when calling latex' command exit status 1
```

It seems your project is fully automated. How is sphinx-build called? and where is target document?

**Comment by tk0miya** [comment]
Ok, I understand. `rtems-docs` has a copy of `\maketitle` definition as `rtems-docs/common/rtemsstyle.sty`. And it includes `\ifsphinxpdfoutput` macro.
But it was dropped since 1.6 (#3550). so the builds are failed with 1.6.

I'll take a look later again.

**Comment by jfbu** [comment]
@sebhub 

yes, the `\maketitle` as pointed out by @tk0miya is copied from older sphinxmanual.cls. Probably you can fix your issue by copying [newer latex code](https://github.com/sphinx-doc/sphinx/blob/stable/sphinx/texinputs/sphinxmanual.cls#L36)

from quick look this newer code should also work if you compile your project with older Sphinx, once integrated in ``rtems-docs/common/rtemsstyle.sty`` (not tested)

**Comment by kiwichris** [comment]
Thank you for the link to the newer code. I will look into sorting this out.

**Comment by kiwichris** [comment]
Fixed here:
https://git.rtems.org/rtems-docs/commit/?id=c68461134ea5bfe6859ca6c49055252ef978b860
This issue can be closed.

**Comment by sebhub** [comment]
Thanks a lot for your kind help.
