### ISSUE TITLE
docname lost after dynamically parsing RST in extension

### ISSUE THREAD

**Issue by bryevdv** [sphinx-doc/sphinx#3924]
Subject: <what happen when you do on which document project>

### Problem

I've developed a "bokeh-gallery" extension to help with automating our project documentation. It is used to generate the gallery below:

http://bokeh.pydata.org/en/latest/docs/gallery.html

After trying to update from Sphinx 1.5.x to 1.6.x, I get the following exception:
```
Exception occurred:
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/environment/__init__.py", line 785, in docname
    return self.temp_data['docname']
KeyError: 'docname'
```

The full code for the extension is here:

https://github.com/bokeh/bokeh/blob/master/bokeh/sphinxext/bokeh_gallery.py

See also reference: https://groups.google.com/forum/#!topic/sphinx-users/TCnxGFKkfGE which has a slightly updated version that works with the "fix" described below. 

The extension works by reading a JSON config that lists gallery files, then reading doc for all these in a loop. Then it generates some RST txt with `.. image` links to the docs generated in the links, which it passes to self._parse. It's this step that fails. Evidently now the value of `env.docname` is erased during the loop that reads docs. When `self._parse` is called with the generated RST txt, the image collector tries to access `env.docname`, resulting in the exception above.

I can "fix" this by saving the docname before the loop, then setting  `env.temp_data['docname'] = current_docname` as seen in the referenced link above. But this seems like a pretty bad workaround. Should this still be expected to work? If not, what is the right way to do what I am doing, which is basically:

* read in a bunch of files and generate docs for them
* generate a string of RST text for the current doc
* parse that dynamically generated RST text

#### Procedure to reproduce the problem
```
make html
```

#### Error logs / results
```
# Sphinx version: 1.6.2
# Python version: 3.6.1 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   copying bokeh-plot files... [ 97%] bokeh-plot-fbef5a55095a57bd7ec69880b9e491c1.js
#   
#   copying bokeh-plot files... [ 98%] bokeh-plot-fbffcff58bf2df95017e1a6470add3f2.js
#   
#   copying bokeh-plot files... [ 99%] bokeh-plot-fc686a29565cec5272ecc418812f2401.js
#   
#   copying bokeh-plot files... [100%] bokeh-plot-ff7d4e4a58f23d8a18428273c04d26ea.js
#   
#   
#   
# Loaded extensions:
#   alabaster (0.7.10) from /Users/bryan/anaconda/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.6.2) from /Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/ext/autodoc.py
#   sphinx.ext.autosummary (1.6.2) from /Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.ifconfig (1.6.2) from /Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/ext/ifconfig.py
#   sphinx.ext.napoleon (1.6.2) from /Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.intersphinx (1.6.2) from /Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (1.6.2) from /Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/ext/viewcode.py
#   bokeh.sphinxext.bokeh_autodoc (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_autodoc.py
#   bokeh.sphinxext.bokeh_enum (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_enum.py
#   bokeh.sphinxext.bokeh_gallery (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_gallery.py
#   bokeh.sphinxext.bokeh_github (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_github.py
#   bokeh.sphinxext.bokeh_jinja (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_jinja.py
#   bokeh.sphinxext.bokeh_index_toctree (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_index_toctree.py
#   bokeh.sphinxext.bokeh_model (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_model.py
#   bokeh.sphinxext.bokeh_options (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_options.py
#   bokeh.sphinxext.bokeh_palette (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_palette.py
#   bokeh.sphinxext.bokeh_palette_group (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_palette_group.py
#   bokeh.sphinxext.bokeh_plot (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_plot.py
#   bokeh.sphinxext.bokeh_prop (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_prop.py
#   bokeh.sphinxext.bokeh_sitemap (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_sitemap.py
#   bokeh.sphinxext.collapsible_code_block (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/collapsible_code_block.py
Traceback (most recent call last):
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/builders/__init__.py", line 328, in build_update
    'out of date' % len(to_build))
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/builders/__init__.py", line 341, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/environment/__init__.py", line 584, in update
    self._read_serial(docnames, self.app)
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/environment/__init__.py", line 603, in _read_serial
    self.read_doc(docname, app)
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/environment/__init__.py", line 733, in read_doc
    app.emit('doctree-read', doctree)
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/environment/collectors/asset.py", line 51, in process_doc
    docname = app.env.docname
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/environment/__init__.py", line 785, in docname
    return self.temp_data['docname']
KeyError: 'docname'
```

#### Expected results

This pattern previously worked with Spinx < 1.6 Should it still be expected to work? If not, is tehre a "more correct" approach?

### Reproducible project / your project
- https://github.com/bokeh/bokeh/blob/master/bokeh/sphinxext/bokeh_gallery.py
- http://bokeh.pydata.org/en/latest/docs/gallery.html

### Environment info
- OS: OS3
- Python version: 3.6
- Sphinx version: 1.6

**Comment by tk0miya** [comment]
Note: It seems `env.temp_data` has been cleared. `env.apply_post_transforms()` is doubtful. I'll check it later.

**Comment by tk0miya** [comment]
I made #3936 to resolve this. But I can't reproduce this problem on my local.
Could you try it please?

**Comment by bryevdv** [comment]
~~~Yes as soon as I can figure our how to pull down a PR branch from a remote :)~~~ Trying now

**Comment by bryevdv** [comment]
@tk0miya this did not seem to fix the error, output reports sphinx 1.7+ but same error at the bottom
```
❯ BOKEH_DOCS_CDN=local make clean html show
rm -rf _build/*
rm -rf source/docs/gallery/*
sphinx-build -b html -d _build/doctrees   source -W _build/html
Running Sphinx v1.7+
making output directory...
Generating grammar tables from /Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/pycode/Grammar-py3.txt
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
loading intersphinx inventory from http://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
intersphinx inventory has moved: http://docs.scipy.org/doc/numpy/objects.inv -> https://docs.scipy.org/doc/numpy/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 300 source files that are out of date
updating environment: 300 added, 0 changed, 0 removed
copying gallery files... [100%] logaxis.py
copying bokeh-plot files... [100%] bokeh-plot-ff7d4e4a58f23d8a18428273c04d26ea.js

Exception occurred:
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/environment/__init__.py", line 777, in docname
    return self.temp_data['docname']
KeyError: 'docname'
The full traceback has been saved in /var/folders/sz/8b6k71ds0rj34ghn0vg4g0cc0000gp/T/sphinx-err-g9ha6e6o.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```

**Comment by bryevdv** [comment]
Also here is the full traceback, AFAICT it is the same as before
```
# Sphinx version: 1.7+
# Python version: 3.6.1 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   copying bokeh-plot files... [ 97%] /Users/bryan/work/bokeh/sphinx/_build/doctrees/bokeh_plot/bokeh-plot-fbef5a55095a57bd7ec69880b9e491c1.js
#   
#   copying bokeh-plot files... [ 98%] /Users/bryan/work/bokeh/sphinx/_build/doctrees/bokeh_plot/bokeh-plot-fbffcff58bf2df95017e1a6470add3f2.js
#   
#   copying bokeh-plot files... [ 99%] /Users/bryan/work/bokeh/sphinx/_build/doctrees/bokeh_plot/bokeh-plot-fc686a29565cec5272ecc418812f2401.js
#   
#   copying bokeh-plot files... [100%] /Users/bryan/work/bokeh/sphinx/_build/doctrees/bokeh_plot/bokeh-plot-ff7d4e4a58f23d8a18428273c04d26ea.js
#   
#   
#   
# Loaded extensions:
#   alabaster (0.7.10) from /Users/bryan/anaconda/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.7+) from /Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (1.7+) from /Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.ifconfig (1.7+) from /Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/ext/ifconfig.py
#   sphinx.ext.napoleon (1.7+) from /Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.intersphinx (1.7+) from /Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (1.7+) from /Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/ext/viewcode.py
#   bokeh.sphinxext.bokeh_autodoc (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_autodoc.py
#   bokeh.sphinxext.bokeh_enum (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_enum.py
#   bokeh.sphinxext.bokeh_gallery (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_gallery.py
#   bokeh.sphinxext.bokeh_github (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_github.py
#   bokeh.sphinxext.bokeh_jinja (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_jinja.py
#   bokeh.sphinxext.bokeh_index_toctree (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_index_toctree.py
#   bokeh.sphinxext.bokeh_model (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_model.py
#   bokeh.sphinxext.bokeh_options (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_options.py
#   bokeh.sphinxext.bokeh_palette (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_palette.py
#   bokeh.sphinxext.bokeh_palette_group (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_palette_group.py
#   bokeh.sphinxext.bokeh_plot (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_plot.py
#   bokeh.sphinxext.bokeh_prop (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_prop.py
#   bokeh.sphinxext.bokeh_sitemap (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/bokeh_sitemap.py
#   bokeh.sphinxext.collapsible_code_block (unknown version) from /Users/bryan/work/bokeh/bokeh/sphinxext/collapsible_code_block.py
Traceback (most recent call last):
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/builders/__init__.py", line 328, in build_update
    'out of date' % len(to_build))
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/builders/__init__.py", line 341, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/environment/__init__.py", line 583, in update
    self._read_serial(docnames, self.app)
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/environment/__init__.py", line 602, in _read_serial
    self.read_doc(docname, app)
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/environment/__init__.py", line 725, in read_doc
    app.emit('doctree-read', doctree)
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/application.py", line 436, in emit
    return self.events.emit(event, self, *args)
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/environment/collectors/asset.py", line 51, in process_doc
    docname = app.env.docname
  File "/Users/bryan/anaconda/lib/python3.6/site-packages/Sphinx-1.7.dev20170716-py3.6.egg/sphinx/environment/__init__.py", line 777, in docname
    return self.temp_data['docname']
KeyError: 'docname'

```

**Comment by tk0miya** [comment]
Ah, sorry. I understand your problem. You'd called `env.read_doc()` inside directive, right?
https://github.com/bokeh/bokeh/blob/master/bokeh/sphinxext/bokeh_gallery.py#L55
Surely, my PR does not resolve it.

Sphinx does not expect `env.read_doc()` is called as nested. The method resets some context data including `temp_data['docname']` at the end. So some process might be confused. In this case, `sphinx/environment/collectors/asset.py` raises an error. But other process might have been damaged also. For example, python domain uses `env.ref_context` to store current modules and classes.

As a workaround, restoring context data resolve your problem. At same time, we need to find the proper way to add a new document on the processing. I think some new APIs are needed to do that.

**Comment by tk0miya** [comment]
@shimizukawa do you have any idea?

**Comment by bryevdv** [comment]
> Ah, sorry. I understand your problem. You'd called env.read_doc() inside directive, right?

Yes exactly. If there is another/better approach that does not involve `read_doc` I am happy to try that, otherwise I can use the workaround with a comment to this issue in the mean time. Thanks!
