### ISSUE TITLE
AttributeError: 'Values' object has no attribute 'character_level_inline_markup' when attempt to make html

### ISSUE THREAD

**Issue by naoko** [sphinx-doc/sphinx#3951]
Subject: Attempt to run make html and got AttributeError: 'Values' object has no attribute 'character_level_inline_markup'

#### Procedure to reproduce the problem
```
make html
```

#### Error logs / results
```
# Sphinx version: 1.6.3
# Python version: 3.5.3 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   'pattern' package not found; tag filters are not available for English
#
#   Downloading lexicon default-historical_2000.tsv
#
#   Downloading lexicon customer-nextiva_fasttext_100.tsv
#
#   Downloading lexicon industry-technology_subreddit.tsv
#
#   Downloading lexicon industry-techsupport_subreddit.tsv
#
# Loaded extensions:
#   sphinx.ext.autodoc (1.6.3) from /Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/sphinx/ext/autodoc.py
#   alabaster (0.7.10) from /Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/alabaster/__init__.py
#   cornice_sphinx (unknown version) from /Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/cornice_sphinx/__init__.py
#   sphinx.ext.viewcode (1.6.3) from /Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.imgmath (1.6.3) from /Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/sphinx/ext/imgmath.py
Traceback (most recent call last):
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 344, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 583, in update
    self._read_serial(docnames, self.app)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 602, in _read_serial
    self.read_doc(docname, app)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 723, in read_doc
    pub.publish()
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/sphinx/io.py", line 74, in read
    self.parse()
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/parsers/rst/__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2318, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/cornice_sphinx/__init__.py", line 99, in run
    return [self._render_service(s) for s in services]
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/cornice_sphinx/__init__.py", line 99, in <listcomp>
    return [self._render_service(s) for s in services]
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/cornice_sphinx/__init__.py", line 122, in _render_service
    service_node += rst2node(trim(service.description))
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/cornice_sphinx/__init__.py", line 303, in rst2node
    parser.parse(data, document)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/parsers/rst/__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 157, in run
    inliner.init_customizations(document.settings)
  File "/Users/nreeves/projects/ml-api/env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 470, in init_customizations
    if settings.character_level_inline_markup:
AttributeError: 'Values' object has no attribute 'character_level_inline_markup'
```

### Environment info
- OS: Mac
- Python version: 3.5.3
- Sphinx version: 1.6.3

**Comment by naoko** [comment]
UPDATE:
Looks like this issue comes from docutils' latest version 0.13.1
Pinning to docutils==0.12 solves this problem
