### ISSUE TITLE
AttributeError: 'Sphinx' object has no attribute 'domains' when performing make clean html

### ISSUE THREAD

**Issue by serialbandicoot** [sphinx-doc/sphinx#3954]
# Sphinx version: 1.6.3
# Python version: 2.7.10 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/Cellar/sphinx-doc/1.6.3/libexec/lib/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/local/Cellar/sphinx-doc/1.6.3/libexec/lib/python2.7/site-packages/sphinx/application.py", line 196, in __init__
    self.setup_extension(extension)
  File "/usr/local/Cellar/sphinx-doc/1.6.3/libexec/lib/python2.7/site-packages/sphinx/application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/Cellar/sphinx-doc/1.6.3/libexec/lib/python2.7/site-packages/sphinx/registry.py", line 207, in load_extension
    metadata = mod.setup(app)
  File "/Library/Python/2.7/site-packages/sphinxcontrib/autohttp/flask.py", line 46, in setup
    if 'http' not in app.domains:
AttributeError: 'Sphinx' object has no attribute 'domains'

Any ideas would be great?

**Comment by tk0miya** [comment]
It is a bug of sphinxcontrib-httpdomain.
It was already fixed: https://bitbucket.org/birkenfeld/sphinx-contrib/issues/182/sphinxcontribautohttpflask-sphinx-object

Please check this.
Thanks,

**Comment by serialbandicoot** [comment]
I'm currently on version 1.5.0 (sphinxcontrib-httpdomain), which version is this fixed in??

**Comment by tk0miya** [comment]
I'm not sure. Please ask owner of the extension.

**Comment by luog1992** [comment]
I reinstalled the 1.3.4 version and then the bug disappeared.
