### ISSUE TITLE
"make html" fails.

### ISSUE THREAD

**Issue by greyspectrum** [sphinx-doc/sphinx#3957]
Subject: Python package "cryptography" not the latest version.

### Problem
- When I run `make html`, sphinx complains that my cryptography package is out of date, even though I am running the most recent version of Python 2  available through my OS's package manager.

#### Procedure to reproduce the problem

On Ubuntu 16.04 LTS, with Python 2.7.12
```
sudo pip install sphinx sphinx-autobuild
cd /path/to/project
mkdir docs
cd docs
sphinx-quickstart
sudo pip install recommonmark 
```
Then, edit conf.py to include the following:
```
from recommonmark.parser import CommonMarkParser

source_parsers = {
    '.md': CommonMarkParser,
}

source_suffix = ['.rst', '.md']
```
Then, run:
```
make html
```
#### Error logs / results
```
Running Sphinx v1.5a2
making output directory...

Exception occurred:
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (cryptography 1.2.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('cryptography>=1.3.4'), set(['requests']))
The full traceback has been saved in /tmp/sphinx-err-7dHA_E.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:19: recipe for target 'html' failed
make: *** [html] Error 1
```
From /tmp/sphinx-err-7dHA_E.log:
```
# Sphinx version: 1.5a2
# Python version: 2.7.12 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.5a2-py2.7.egg/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.5a2-py2.7.egg/sphinx/application.py", line 192, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.5a2-py2.7.egg/sphinx/application.py", line 513, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.5a2-py2.7.egg/sphinx/builders/linkcheck.py", line 38, in <module>
    from sphinx.util.requests import requests, useragent_header, is_ssl_error
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.5a2-py2.7.egg/sphinx/util/requests.py", line 21, in <module>
    pkg_resources.require(['requests[security]'])
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 962, in require
    needed = self.resolve(parse_requirements(requirements))
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (cryptography 1.2.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('cryptography>=1.3.4'), set(['requests']))
```

#### Expected results
`make html` will build html docs from the Markdown files.

### Reproducible project / your project
https://github.com/tester-robot/moc-docs-public

### Environment info
- OS: Ubuntu 16.04 LTS x64
- Python version: 2.7.12
- Sphinx version: 1.5a2

**Comment by tk0miya** [comment]
>Sphinx version: 1.5a2

Why alpha version? Current stable release is 1.6.3. If you want to use newest sphinx, please update all dependencies libraries.
Or, please use distro's package.

**Comment by greyspectrum** [comment]
>Why alpha version? Current stable release is 1.6.3.

I purged the alpha version and installed 1.6.3. This fixed my issue. Thank you.
