### ISSUE TITLE
TypeError super() argument 1 must be type, not None when trying to install minimal project

### ISSUE THREAD

**Issue by cpaulik** [sphinx-doc/sphinx#3976]
Subject: I'm not sure if this is a bug in Sphinx, pbr or some other library but it works with Sphinx<1.6 and does not work with Sphinx>1.6.

### Problem
- New sphinx version causes installation of projects to fail.

#### Procedure to reproduce the problem
```
pip install pyscaffold
putup test_project
# this gives you the attached zipped test_project
conda create -n test_project -c conda-forge pip sphinx
source activate test_project
pip install .
```

#### Error logs / results
```
Processing /data/Development/python/workspace/test_project
    Complete output from command python setup.py egg_info:
    
    Installed /tmp/pip-pqE7uf-build/.eggs/PyScaffold-2.5.7-py2.7.egg
    [pbr] Generating ChangeLog
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-pqE7uf-build/.eggs/PyScaffold-2.5.7-py2.7.egg/pyscaffold/contrib/pbr/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-pqE7uf-build/.eggs/PyScaffold-2.5.7-py2.7.egg/pyscaffold/contrib/pbr/pbr/util.py", line 264, in cfg_to_args
        wrap_commands(kwargs)
      File "/tmp/pip-pqE7uf-build/.eggs/PyScaffold-2.5.7-py2.7.egg/pyscaffold/contrib/pbr/pbr/util.py", line 566, in wrap_commands
        cmdclass = ep.resolve()
      File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/test_project/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2311, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/test_project/lib/python2.7/site-packages/sphinx/setup_command.py", line 23, in <module>
        from sphinx.application import Sphinx
      File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/test_project/lib/python2.7/site-packages/sphinx/application.py", line 33, in <module>
        from sphinx.environment import BuildEnvironment
      File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/test_project/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 45, in <module>
        from sphinx.util.websupport import is_commentable
      File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/test_project/lib/python2.7/site-packages/sphinx/util/websupport.py", line 11, in <module>
        from sphinxcontrib.websupport.utils import is_commentable  # NOQA
      File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/test_project/lib/python2.7/site-packages/sphinxcontrib/websupport/__init__.py", line 15, in <module>
        from sphinxcontrib.websupport.core import WebSupport  # NOQA
      File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/test_project/lib/python2.7/site-packages/sphinxcontrib/websupport/core.py", line 17, in <module>
        from jinja2 import Environment, FileSystemLoader
      File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/test_project/lib/python2.7/site-packages/jinja2/__init__.py", line 33, in <module>
        from jinja2.environment import Environment, Template
      File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/test_project/lib/python2.7/site-packages/jinja2/environment.py", line 15, in <module>
        from jinja2 import nodes
      File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/test_project/lib/python2.7/site-packages/jinja2/nodes.py", line 19, in <module>
        from jinja2.utils import Markup
      File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/test_project/lib/python2.7/site-packages/jinja2/utils.py", line 486, in <module>
        MutableMapping.register(LRUCache)
      File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/test_project/lib/python2.7/abc.py", line 109, in register
        if issubclass(subclass, cls):
      File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/test_project/lib/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/test_project/lib/python2.7/site-packages/typing.py", line 1229, in __subclasscheck__
        return super(GenericMeta, self).__subclasscheck__(cls)
    TypeError: super() argument 1 must be type, not None
    error in setup command: Error parsing /tmp/pip-pqE7uf-build/setup.cfg: TypeError: super() argument 1 must be type, not None
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-pqE7uf-build/

```

#### Expected results
It should just install the package

### Reproducible project / your project
- [test_project.zip](https://github.com/sphinx-doc/sphinx/files/1191187/test_project.zip)

### Environment info
- OS: Linux Ubuntu 14.04
- Python version: 2.7.13
- Sphinx version: 1.6.3

#### conda env
```
name: test_project
channels:
- defaults
- conda-forge
dependencies:
- alabaster=0.7.10=py27_0
- asn1crypto=0.22.0=py27_0
- babel=2.3.4=py27_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py27_0
- cffi=1.10.0=py27_0
- chardet=3.0.2=py27_1
- cryptography=1.9=py27_0
- docutils=0.13.1=py27_0
- enum34=1.1.6=py27_1
- idna=2.5=py27_0
- imagesize=0.7.1=py27_0
- ipaddress=1.0.18=py27_0
- jinja2=2.9.5=py27_0
- libffi=3.2.1=3
- markupsafe=1.0=py27_0
- ncurses=5.9=10
- openssl=1.0.2l=0
- pip=9.0.1=py27_0
- pycparser=2.18=py27_0
- pygments=2.2.0=py27_0
- pyopenssl=16.2.0=py27_0
- pysocks=1.6.7=py27_0
- python=2.7.13=1
- pytz=2017.2=py27_0
- readline=6.2=0
- requests=2.18.2=py27_0
- setuptools=36.2.2=py27_0
- six=1.10.0=py27_1
- snowballstemmer=1.2.1=py27_0
- sphinx=1.6.3=py27_0
- sphinxcontrib-websupport=1.0.1=py27_0
- sqlite=3.13.0=1
- tk=8.5.19=2
- typing=3.6.1=py27_0
- urllib3=1.21.1=py27_1
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
```

**Comment by tk0miya** [comment]
I can't reproduce the error with standard toolkit (setuptools and pip).
I think this is not a bug of Sphinx.
```
$ docker run -it --rm ubuntu:trusty bash
root@98538de53506:/# apt update
root@98538de53506:/# apt install curl unzip git python-pip
root@98538de53506:/# curl -LO https://github.com/sphinx-doc/sphinx/files/1191187/test_project.zip
root@98538de53506:/# unzip test_project.zip
root@98538de53506:/# cd test_project
root@98538de53506:/test_project# pip install pyscaffold
root@98538de53506:/test_project# pip install --upgrade setuptools
root@98538de53506:/test_project# pip install .
Unpacking /test_project
  Running setup.py (path:/tmp/pip-__u7hP-build/setup.py) egg_info for package from file:///test_project
    [pbr] Processing SOURCES.txt
    [pbr] In git context, generating filelist from git
    warning: no files found matching 'AUTHORS'
    warning: no files found matching 'ChangeLog'
    warning: no previously-included files found matching '.gitreview'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Installing collected packages: test-project
  Running setup.py install for test-project
    [pbr] Processing SOURCES.txt
    [pbr] In git context, generating filelist from git
    warning: no files found matching 'AUTHORS'
    warning: no files found matching 'ChangeLog'
    warning: no previously-included files found matching '.gitreview'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
  Could not find .egg-info directory in install record for test-project==0.0.post0.dev1+nc6be2b7.dirty from file:///test_project
Successfully installed test-project
Cleaning up...
root@98538de53506:/test_project#
```

FYI: #3766 was very similar to this. I don't know what PyScaffold is doing. But it might be related with this (and conda!).

**Comment by cpaulik** [comment]
You have to use a recent pip version and install sphinx to see the problem.

Try the building the following dockerfile:

```
FROM ubuntu:trusty
MAINTAINER cpa

RUN apt update
RUN apt install -y curl unzip git python
RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
RUN python get-pip.py
RUN pip install sphinx
RUN curl -LO https://github.com/sphinx-doc/sphinx/files/1191187/test_project.zip
RUN unzip test_project.zip
RUN cd test_project && pip install .
```

**Comment by jleni** [comment]
I have the same problem and I could fix it using sphinx==1.5.6.
I wonder if the problem is in the configuration created by pyscaffold

**Comment by Russell-Jones-OxPhys** [comment]
(moved from #3766 )

 I'm seeing the same thing with https://github.com/astropy/ccdproc via PyPI (v1.2.0) in a MacPorts 2.7 VE with --system-site-packages on macOS 10.12.6 
Oddly, I can't find astropy-helpers in the VE, or import ah_bootstrap in it. I don't have pyscaffold installed.

The really weird thing is that I have the same MacPorts binaries (rsynced) on two 10.12.6 systems, and I get it on one but not the other. IDK if it's something in ~/.cache or an environment difference. It happens with the same PATH set, and the env vars (except PS1) and shell (bash) are the same.

I'm just trying a non --ssp VE... that works without error. sphinx and astropy_helpers don't get installed in the non-ssp ve by `pip install ccdproc`. `import ah_bootstrap` in the VE python doesn't find such a module.

`pip install sphinx==1.5.6` seems to make everything work in the --ssp ve ¯\_(ツ)_/¯

```
$ pip install ccdproc --no-deps
Collecting ccdproc
  Using cached ccdproc-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/25/safda2md2914g21jdrlflpvm0000ck/T/pip-build-Vd24Kr/ccdproc/setup.py", line 18, in <module>
        from astropy_helpers.setup_helpers import (
      File "/private/var/folders/25/safda2md2914g21jdrlflpvm0000ck/T/pip-build-Vd24Kr/ccdproc/.eggs/astropy_helpers-0.4.8-py2.7.egg/astropy_helpers/setup_helpers.py", line 56, in <module>
        from sphinx.setup_command import BuildDoc as SphinxBuildDoc
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/setup_command.py", line 23, in <module>
        from sphinx.application import Sphinx
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/application.py", line 33, in <module>
        from sphinx.environment import BuildEnvironment
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 45, in <module>
        from sphinx.util.websupport import is_commentable
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/util/websupport.py", line 11, in <module>
        from sphinxcontrib.websupport.utils import is_commentable  # NOQA
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinxcontrib/websupport/__init__.py", line 15, in <module>
        from sphinxcontrib.websupport.core import WebSupport  # NOQA
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinxcontrib/websupport/core.py", line 17, in <module>
        from jinja2 import Environment, FileSystemLoader
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jinja2/__init__.py", line 33, in <module>
        from jinja2.environment import Environment, Template
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jinja2/environment.py", line 15, in <module>
        from jinja2 import nodes
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jinja2/nodes.py", line 19, in <module>
        from jinja2.utils import Markup
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jinja2/utils.py", line 486, in <module>
        MutableMapping.register(LRUCache)
      File "/Data/py27ve/bin/../lib/python2.7/abc.py", line 109, in register
        if issubclass(subclass, cls):
      File "/Data/py27ve/bin/../lib/python2.7/abc.py", line 180, in __subclasscheck__
        if issubclass(subclass, scls):
      File "/Data/py27ve/lib/python2.7/site-packages/typing.py", line 1265, in __subclasscheck__
        return super(GenericMeta, self).__subclasscheck__(cls)
    TypeError: super() argument 1 must be type, not None
```

**Comment by ajkavanagh** [comment]
Yup, we're hitting this too with pylxd (which uses pbr which uses sphinx) -- exactly the same error, when the `MutableMapping.register(LRUCache)` is executed.  There's definitely something odd going on with py2.7 vs Py3.5 which works.

I reckon the bug is being trigged by some oddity around LRUCache() not being a subclass of MutableMapping as the line that fails is:

```python
if issubclass(subclass, cls):
```

It's in the setuptools sandbox, and blowing up in abc.Meta() which is odd; but then it is only happening for me in py27 rather than 3.5 or 3.6.  I'm also getting odd errors about sys being None (which only can happen during shutdown), so it's proving a bit hard to debug!

**Comment by bsipocz** [comment]
For ``ccdproc`` and all other packages that use the ``astropy-helpers`` submodule, if the helpers version is <2.0, you need to stick with sphinx 1.5.6.
As a rule of thumb, if the package was released before this summer, this is always the case.

**Comment by YellowSharkMT** [comment]
I ran into this problem with the `fulltoc` package, and downgrading to sphinx 1.5.6 solved things. Thanks very much for the info!

**Comment by tk0miya** [comment]
Hmm... I still can't reproduce this. Even using @cpaulik 's Dockerfile, I can't.
Please let me know the way to reproduce this. It would be nice if it is on docker.

**Comment by chfw** [comment]
for your reference, it is reproducing in my project: https://readthedocs.org/projects/pyexcel/builds/6321080/

interestingly, it does not fail in another one of mine:

https://readthedocs.org/projects/django-excel/builds/6257520/

**Comment by KajKandler** [comment]
I needed to only downgrade sphinx for installing sphinxcontrib-spelling. Afterwards I was able to upgrade to sphinx version 1.6.7 again and it appears to do no harm

**Comment by wkerzendorf** [comment]
@bsipocz it doesn't seem to be quite true - I'm using astropy-helpers 2.0.6 (astropy_helpers @ 5e30a46) and it gives the same error message when building on readthedocs with the newest sphinx. I've now downgraded to sphinx 1.5.6 (we'll see if that works). This is for github.com/starkit/starkit

No idea why it works now despite readthedocs upgrading to sphinx 1.7.4: https://readthedocs.org/projects/starkit/builds/7206742/ - disregard my comment I guess.
