### ISSUE TITLE
Changing theme from alabaster causes HTML build to fail

### ISSUE THREAD

**Issue by tristan957** [sphinx-doc/sphinx#3987]
Subject: Building HTML fails if theme is not alabaster

### Problem
- Can't use any theme that is not alabaster

#### Procedure to reproduce the problem
```
- Change theme to something other than alabaster
```

#### Error logs / results
```
# Sphinx version: 1.6.3
# Python version: 3.6.1 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.9.6
# Last messages:
#   checking consistency...
#   
#   done
#   
#   preparing documents...
#   
#   done
#   
#   writing output... [  5%] about
#   
# Loaded extensions:
#   alabaster (0.7.10) from C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\alabaster\__init__.py
#   sphinx.ext.autodoc (1.6.3) from C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\ext\autodoc.py
#   sphinx.ext.doctest (1.6.3) from C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\ext\doctest.py
#   sphinx.ext.todo (1.6.3) from C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\ext\todo.py
#   sphinx.ext.mathjax (1.6.3) from C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\ext\mathjax.py
#   sphinx.ext.viewcode (1.6.3) from C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\ext\viewcode.py
Traceback (most recent call last):
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\application.py", line 339, in build
    self.builder.build_update()
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\builders\__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\builders\__init__.py", line 397, in build
    self.write(docnames, list(updated_docnames), method)
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\builders\__init__.py", line 434, in write
    self._write_serial(sorted(docnames))
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\builders\__init__.py", line 443, in _write_serial
    self.write_doc(docname, doctree)
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\builders\html.py", line 561, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\builders\html.py", line 945, in handle_page
    output = self.templates.render(templatename, ctx)
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\jinja2glue.py", line 176, in render
    return self.environment.get_template(template).render(context)
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\themes\basic\page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\themes\basic\layout.html", line 175, in top-level template code
    {%- block content %}
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\themes\basic\layout.html", line 193, in block "content"
    {%- block sidebar2 %}{{ sidebar() }}{% endblock %}
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\themes\basic\layout.html", line 193, in block "sidebar2"
    {%- block sidebar2 %}{{ sidebar() }}{% endblock %}
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\jinja2\sandbox.py", line 427, in call
    return __context.call(__obj, *args, **kwargs)
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\jinja2\runtime.py", line 553, in _invoke
    rv = self._func(*arguments)
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\themes\basic\layout.html", line 64, in template
    {%- include sidebartemplate %}
  File "C:\Users\591709\Documents\Projects\icp-data-tool\lib\site-packages\sphinx\jinja2glue.py", line 200, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: about.html
```

#### Expected results
- Build html

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version> Win 10
- Python version: 3.6.1
- Sphinx version: 1.6.3
- <Extra tools e.g.: Browser, tex or something else>

**Comment by shimizukawa** [comment]
If you have [html_sidebars](http://www.sphinx-doc.org/en/stable/config.html#confval-html_sidebars) in your `conf.py` and it contains `about.html`, please remove it.

Alabaster has `about.html` template file by default.
https://github.com/bitprophet/alabaster/tree/master/alabaster

However Sphinx built-in themes doesn't have it.
https://github.com/sphinx-doc/sphinx/tree/master/sphinx/themes/basic

**Comment by tk0miya** [comment]
OMG, it's bug of `sphinx-quickstart`. It's template contains `about.html` by default. see b52b790e7f.

**Comment by shimizukawa** [comment]
ah... definitely it's a bug :(

**Comment by joinghel** [comment]
Still having this in v1.6.4: `jinja2.exceptions.TemplateNotFound: about.html`
When switching from alabaster to classic.

Edit: same for `navigation.html`.

Removing both sidebars from conf fixed the build.

**Comment by jfbu** [comment]
@joinghel currently the fix has been merged for v1.7 release but I think it will also be merged for v1.6.5. But even if it had been merged into v1.6.4 that would not have changed the fact that already existing projects need their `conf.py` manually adjusted, the #4002 fix is only for new projects created by `sphinx-quickstart`.

**Comment by jfbu** [comment]
I am reopening because the fix at #4002 was applied to master branch only. Besides, the fix makes the alabaster theme produce non-satisfactory html output, which is a problem as it is set-up as default theme.

**Comment by joinghel** [comment]
Oh my bad, I just thought to let you guys know since the Sphinx version of this issue was v1.6.3 and I was using v1.6.4. I should have payed more attention to the fix merge :)

**Comment by tk0miya** [comment]
At present, #4002 is cherry-picked into stable branch. So it will be fixed at next stable release.
