### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by aszmyd** [sphinx-doc/sphinx#4014]
Subject: I get this error when trying to run docs build on Python `3.5.2` and Sphinx `1.6.3`

### Problem

When i try to run docs build, i get following error:

```bash

(tmp) user@:~/workspace$ sphinx-build docs/source/ docs/build/
Running Sphinx v1.6.3

Exception occurred:
  File "/home/user/tmp/workspace/tmp/lib/python3.5/site-packages/sphinx/registry.py", line 196, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/user/tmp/workspace/tmp/lib/python3.5/site-packages/sphinxcontrib/osexample.py", line 136
    get_lexer_by_name('ubuntu')
                              ^
TabError: inconsistent use of tabs and spaces in indentation
The full traceback has been saved in /tmp/sphinx-err-1rb_mcp9.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

```

The contents of `/tmp/sphinx-err-1rb_mcp9.log`:
```
# Sphinx version: 1.6.3
# Python version: 3.5.2 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/user/tmp/workspace/tmp/lib/python3.5/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/user/tmp/workspace/tmp/lib/python3.5/site-packages/sphinx/application.py", line 196, in __init__
    self.setup_extension(extension)
  File "/home/user/tmp/workspace/tmp/lib/python3.5/site-packages/sphinx/application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/user/tmp/workspace/tmp/lib/python3.5/site-packages/sphinx/registry.py", line 196, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/user/tmp/workspace/tmp/lib/python3.5/site-packages/sphinxcontrib/osexample.py", line 136
    get_lexer_by_name('ubuntu')
                              ^
TabError: inconsistent use of tabs and spaces in indentation


```

### Environment info
- OS: Linux Fedora 25
- Python version: 3.5.2
- Sphinx version: 1.6.3

**Comment by aszmyd** [comment]
Nevermind. It was an issue with external extension [sphinxcontrib-osexample](https://github.com/svx/sphinxcontrib-osexample)
