### ISSUE TITLE
unsupported operand type(s) for +: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by undee** [sphinx-doc/sphinx#4060]
Subject: TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

### Problem
- <Detail of problem>

#### Procedure to reproduce the problem
```
make html
```

#### Error logs / results
```
# Sphinx version: 1.6.3
# Python version: 2.7.9 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.5
# Last messages:
#   loading intersphinx inventory from https://django.readthedocs.org/en/latest/objects.inv...
#   intersphinx inventory has moved: https://django.readthedocs.org/en/latest/objects.inv -> https://django.readthedocs.io/en/latest/objects.inv
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 34 source files that are out of date
#   updating environment:
#   34 added, 0 changed, 0 removed
#   reading sources... [  2%] api_integration
#   reading sources... [  5%] git
#   reading sources... [  8%] glossary
#   reading sources... [ 11%] howtos/backend
# Loaded extensions:
#   odoo_ext (unknown version) from C:\Users\undee\Desktop\doc\_extensions\odoo_ext\__init__.pyc
#   patchqueue (unknown version) from c:\python27\lib\site-packages\patchqueue\__init__.pyc
#   sphinx.ext.todo (1.6.3) from c:\python27\lib\site-packages\sphinx\ext\todo.pyc
#   github_link (unknown version) from C:\Users\undee\Desktop\doc\_extensions\github_link.pyc
#   sphinx.ext.autodoc (1.6.3) from c:\python27\lib\site-packages\sphinx\ext\autodoc.pyc
#   sphinx.ext.intersphinx (1.6.3) from c:\python27\lib\site-packages\sphinx\ext\intersphinx.pyc
#   alabaster (0.7.10) from c:\python27\lib\site-packages\alabaster\__init__.pyc
#   html_domain (unknown version) from C:\Users\undee\Desktop\doc\_extensions\html_domain.pyc
#   exercise_admonition (unknown version) from C:\Users\undee\Desktop\doc\_extensions\exercise_admonition.pyc
#   sphinx.ext.ifconfig (1.6.3) from c:\python27\lib\site-packages\sphinx\ext\ifconfig.pyc
#   sphinx.ext.linkcode (1.6.3) from c:\python27\lib\site-packages\sphinx\ext\linkcode.pyc
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\sphinx\cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "c:\python27\lib\site-packages\sphinx\application.py", line 339, in build
    self.builder.build_update()
  File "c:\python27\lib\site-packages\sphinx\builders\__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "c:\python27\lib\site-packages\sphinx\builders\__init__.py", line 344, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "c:\python27\lib\site-packages\sphinx\environment\__init__.py", line 583, in update
    self._read_serial(docnames, self.app)
  File "c:\python27\lib\site-packages\sphinx\environment\__init__.py", line 602, in _read_serial
    self.read_doc(docname, app)
  File "c:\python27\lib\site-packages\sphinx\environment\__init__.py", line 723, in read_doc
    pub.publish()
  File "c:\python27\lib\site-packages\docutils\core.py", line 217, in publish
    self.settings)
  File "c:\python27\lib\site-packages\sphinx\io.py", line 74, in read
    self.parse()
  File "c:\python27\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    input_source=document['source'])
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2980, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2320, in explicit_markup
    self.explicit_list(blank_finish)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2350, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 318, in nested_list_parse
    node=node, match_titles=match_titles)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2623, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "c:\python27\lib\site-packages\docutils\parsers\rst\directives\admonitions.py", line 47, in run
    admonition_node)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2318, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "c:\python27\lib\site-packages\sphinx\directives\other.py", line 377, in run
    node, match_titles=1)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2318, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "c:\python27\lib\site-packages\patchqueue\__init__.py", line 241, in run
    patch = next(series, None)
  File "c:\python27\lib\site-packages\patchqueue\__init__.py", line 92, in next
    mercurial.patch.filestore())
  File "c:\python27\lib\site-packages\mercurial\patch.py", line 1988, in applydiff
    prefix=prefix, eolmode=eolmode)
  File "c:\python27\lib\site-packages\mercurial\patch.py", line 2009, in _applydiff
    ret = current_file.apply(values)
  File "c:\python27\lib\site-packages\mercurial\patch.py", line 806, in apply
    for fuzzlen in xrange(self.ui.configint("patch", "fuzz") + 1):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: Win10>
- Python version:2.7.9
- Sphinx version:1.6.3

**Comment by tk0miya** [comment]
It seems this bug is related with patchqueue extension, and it seems this is not a bug of sphinx.
Could you report this to them?
