### ISSUE TITLE
Parallel build fails on Python 2.7.14

### ISSUE THREAD

**Issue by vstinner** [sphinx-doc/sphinx#4061]
Subject: Parallel build (-j4) fails on Python 2.7.14

### Problem
- When I try to build the Python documentation with sphinx-build in parallel mode, using -j4 option, the compilation fails.

#### Procedure to reproduce the problem
```
cd /home/haypo/prog/python/2.7/
/home/haypo/prog/python/2.7/python -m sphinx -b html -d build/doctrees -D latex_elements.papersize= . build/html -j4
```

#### Error logs / results
```
# Sphinx version: 1.6.3
# Python version: 2.7.14rc1 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.9.6

(...)

#   
#   waiting for workers...
# Loaded extensions:
#   c_annotations (1.0) from /home/haypo/prog/python/2.7/Doc/tools/extensions/c_annotations.pyc
#   sphinx.ext.coverage (1.6.3) from /home/haypo/py27/lib/python2.7/site-packages/sphinx/ext/coverage.pyc
#   sphinx.ext.doctest (1.6.3) from /home/haypo/py27/lib/python2.7/site-packages/sphinx/ext/doctest.pyc
#   alabaster (0.7.10) from /home/haypo/py27/lib/python2.7/site-packages/alabaster/__init__.pyc
#   pyspecific (1.0) from /home/haypo/prog/python/2.7/Doc/tools/extensions/pyspecific.pyc
Traceback (most recent call last):
  File "/home/haypo/py27/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/haypo/py27/lib/python2.7/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/home/haypo/py27/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "/home/haypo/py27/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 344, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/home/haypo/py27/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 581, in update
    self._read_parallel(docnames, self.app, nproc=self.app.parallel)
  File "/home/haypo/py27/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 633, in _read_parallel
    tasks.join()
  File "/home/haypo/py27/lib/python2.7/site-packages/sphinx/util/parallel.py", line 112, in join
    self._join_one()
  File "/home/haypo/py27/lib/python2.7/site-packages/sphinx/util/parallel.py", line 118, in _join_one
    exc, logs, result = pipe.recv()
EOFError
```

#### Expected results
Compilation completes with no error :-)

### Reproducible project / your project
- 2.7 branch of http://github.com/python/cpython/ -- documentation lives in Doc/ subdirectory

### Environment info
- OS: Fedora 26
- Python version: 2.7.14
- Sphinx version: 1.6.3

---

It seems like Sphinx starts to fail since this CPython 2.7 commit: https://github.com/python/cpython/commit/12536bd261ba95cd2748f3d7d47768742a6ffa7a

CPython bugfix related to the commit: https://bugs.python.org/issue30775

CPython Pull Request in the master branch: https://github.com/python/cpython/pull/2470

```
12536bd261ba95cd2748f3d7d47768742a6ffa7a is the first bad commit
commit 12536bd261ba95cd2748f3d7d47768742a6ffa7a
Author: Antoine Pitrou <pitrou@free.fr>
Date:   Wed Jun 28 13:48:38 2017 +0200

    [2.7] Clear potential ref cycle between Process and Process target (GH-2470) (#2473)
    
    * Clear potential ref cycle between Process and Process target
    
    Besides Process.join() not being called, this was an indirect cause of bpo-30775.
    The threading module already does this.
    
    * Add issue reference.
    (cherry picked from commit 79d37ae979a65ada0b2ac820279ccc3b1cd41ba6)

:040000 040000 6d0f329b0a3b6d96dafe66bf48766eab8bd814d2 05b2cc03dd37a48f2c08a4a91cf7ba61fac42d95 M	Lib
```

**Comment by benjaminp** [comment]
Dup of #4006.

**Comment by tk0miya** [comment]
Right, I think this would be same as #4006.
@haypo could you check the HEAD of stable branch?

**Comment by vstinner** [comment]
> @haypo could you check the HEAD of stable branch?

I tested Sphinx HEAD with Python 2.7 HEAD: no more bug. I confirm that the multiprocessing bug has been fixed, thanks!
