### ISSUE TITLE
I got an traceback during make doc for dnf project

### ISSUE THREAD

**Issue by j-mracek** [sphinx-doc/sphinx#4089]
Subject: <what happen when you do on which document project>

### Problem
```
# Sphinx version: 1.6.3
# Python version: 3.6.2 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   reading sources... [ 77%] conf_ref
#   
#   reading sources... [ 81%] dnf-1_vs_dnf-2
#   
#   reading sources... [ 85%] index
#   
#   reading sources... [ 88%] release_notes
#   
#   Using RHBugzilla for URL containing bugzilla.redhat.com
#   
# Loaded extensions:
#   alabaster (0.7.9) from /usr/lib/python3.6/site-packages/alabaster/__init__.py
#   rhbug (unknown version) from /home/jmracek/Projects/dnf/doc/rhbug.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 307, in next_line
    self.line = self.input_lines[self.line_offset]
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 1152, in __getitem__
    return self.data[i]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 230, in run
    self.next_line()
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 310, in next_line
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 344, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 583, in update
    self._read_serial(docnames, self.app)
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 602, in _read_serial
    self.read_doc(docname, app)
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 723, in read_doc
    pub.publish()
  File "/usr/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python3.6/site-packages/sphinx/io.py", line 74, in read
    self.parse()
  File "/usr/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2980, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2980, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 1255, in bullet
    blank_finish=blank_finish)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 318, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2498, in bullet
    listitem, blank_finish = self.list_item(match.end())
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 1271, in list_item
    node=listitem)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 245, in run
    result = state.eof(context)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2688, in eof
    self.blank(None, context, None)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2680, in blank
    context, self.state_machine.abs_line_number() - 1)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 417, in paragraph
    textnodes, messages = self.inline_text(text, lineno)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 426, in inline_text
    return self.inliner.parse(text, lineno, self.memo, self.parent)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 642, in parse
    lineno)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 785, in interpreted_or_phrase_ref
    lineno)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 867, in interpreted
    nodes, messages2 = role_fn(role, rawsource, text, lineno, self)
  File "/home/jmracek/Projects/dnf/doc/rhbug.py", line 75, in RhBug_role
    summary = Summary(summaries_fn)(text)
  File "/home/jmracek/Projects/dnf/doc/rhbug.py", line 39, in __call__
    summary = self._from_bugzilla(bug_id)
  File "/home/jmracek/Projects/dnf/doc/rhbug.py", line 48, in _from_bugzilla
    bug = rhbz.query(query)[0]
IndexError: list index out of range
```

#### Procedure to reproduce the problem
```
<Paste your command-line here which cause the problem>
```

#### Error logs / results
```
<Paste your error log here>
```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version>
- Python version:
- Sphinx version:
- <Extra tools e.g.: Browser, tex or something else>

**Comment by j-mracek** [comment]
Sorry problem with bugzilla entry
