### ISSUE TITLE
Issue in sphinx.pycode.pgen2.driver.Driver when building

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#411]
Hello,
I'm getting this fatal error whenever I'm trying to run sphinx-build. It shows up just after the "Running Sphinx v0.6.5 message.

The error is **AttributeError: 'module' object has no attribute 'getLogger'**. I checked up on the file and it seems all in order, but I read that circular imports may be the culprit here?

```
# Sphinx version: 0.6.5
# Docutils version: 0.6 release
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Sphinx-0.6.5-py2.6.egg/sphinx/cmdline.py", line 169, in main
    warningiserror, tags)
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Sphinx-0.6.5-py2.6.egg/sphinx/application.py", line 104, in __init__
    self.setup_extension(extension)
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Sphinx-0.6.5-py2.6.egg/sphinx/application.py", line 173, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Sphinx-0.6.5-py2.6.egg/sphinx/ext/autodoc.py", line 24, in <module>
    from sphinx.pycode import ModuleAnalyzer, PycodeError
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Sphinx-0.6.5-py2.6.egg/sphinx/pycode/__init__.py", line 24, in <module>
    pygrammar = driver.load_grammar(_grammarfile)
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/Sphinx-0.6.5-py2.6.egg/sphinx/pycode/pgen2/driver.py", line 118, in load_grammar
    logger = logging.getLogger()
AttributeError: 'module' object has no attribute 'getLogger'
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/411
- Originally reported by: Anonymous
- Originally created at: 2010-05-09T18:46:19.847

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-05-22 10:09:12+00:00_

I would assume you have another module "logging" somewhere along your sys.path...

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2013-03-31 13:57:14+00:00_

Removing version: 0.6.5 (automated comment)
