### ISSUE TITLE
Two todolist directives break sphinx-1.6.5

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#4214]
### Problem
- Two todolist directives in one document break `make html`

#### Procedure to reproduce the problem
```
1. put `.. todo:: some` on some doc source.
2. put two `.. todolist::` on some doc source.
3. enable todo extension in conf.py
4. do `make html`
```

#### Error logs / results
```
# Sphinx version: 1.6.5
# Python version: 2.7.10 (CPython)
# Docutils version: 0.14-
# Jinja2 version: 2.9.6
# Last messages:
#   writing output... [ 92%] reverse-dict/writing/indexing
#   writing output... [ 92%] reverse-dict/writing/link
#   writing output... [ 93%] reverse-dict/writing/note
#   writing output... [ 93%] reverse-dict/writing/numbering
#   writing output... [ 94%] reverse-dict/writing/only
#   writing output... [ 94%] reverse-dict/writing/refer
#   writing output... [ 95%] reverse-dict/writing/replace
#   writing output... [ 96%] reverse-dict/writing/strike
#   writing output... [ 96%] reverse-dict/writing/today
#   writing output... [ 97%] reverse-dict/writing/todo
# Loaded extensions:
#   japanesesupport (unknown version) from /Users/shimizukawa/py/sphinxjp/sphinxjp-web/source/japanesesupport.pyc
#   sphinx.ext.todo (1.6.5) from /Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   alabaster (0.7.10) from /Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinxcontrib.gist (unknown version) from /Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinxcontrib/gist/__init__.pyc
Traceback (most recent call last):
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 397, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 434, in write
    self._write_serial(sorted(docnames))
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 441, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 911, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 963, in apply_post_transforms
    self.app.emit('doctree-resolved', doctree, docname)
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/sphinx/ext/todo.py", line 181, in process_todo_nodes
    del todo_entry['targetref']
  File "/Users/shimizukawa/py/sphinxjp/sphinxjp-web/.venv/lib/python2.7/site-packages/docutils/nodes.py", line 594, in __delitem__
    del self.attributes[key]
KeyError: 'targetref'
```
- https://app.wercker.com/sphinxjp/sphinx-users.jp/runs/build/59f806598e888f0001d5feb0

#### Expected results
no error

### Reproducible project / your project
- https://github.com/sphinxjp/sphinx-users.jp/tree/961cc48f57d30ced4ffbca25783390bfaa850d47

(note that it is not a small project)

### Environment info
- OS: any
- Python version: 2.7.10
- Sphinx version: 1.6.5 (1.6.4 doesn't have this error)

**Comment by shimizukawa** [comment]
I think PR #4153 is the cause of this issue.

**Comment by tk0miya** [comment]
@Smattr Could you check this please?

**Comment by Smattr** [comment]
I can reproduce this. I don't know if PR #4153 is the cause, but it certainly seems like the prime suspect. I'll have a look at fixing it. Apologies for the inconvenience.

**Comment by Smattr** [comment]
Confirmed that reverting ed4949e00008311587dc57a3e84e203920f7af00 fixes this problem. Sorry, my fault :( This is reproducible with the LaTeX back end as well, and the underlying problem looks independent of the back end. I'll work on this.

While trying to construct a test case for this I'm getting the following failure for Python 2 and 3. My dev VM isn't exactly a clean environment so I assume this is related to whatever package versions I have installed but the failure looks genuine to me. Have I done something silly to cause this? I realise I haven't given you much to go on, but if you can point me at some likely culprit packages I can check the version numbers.

```
logger = <MagicMock name='logger' id='140645047808128'>

    @mock.patch('sphinx.highlighting.logger')
    def test_default_highlight(logger):
        bridge = PygmentsBridge('html')

        # default: highlights as python3
        ret = bridge.highlight_block('print "Hello sphinx world"', 'default')
>       assert ret == ('<div class="highlight"><pre><span></span><span class="nb">print</span> '
                       '<span class="s2">&quot;Hello sphinx world&quot;</span>\n</pre></div>\n')
E       assert '<div class=".../pre></div>\n' == '<div class="h.../pre></div>\n'
E         - <div class="highlight"><pre><span class="nb">print</span> <span class="s2">&quot;Hello sphinx world&quot;</span>
E         + <div class="highlight"><pre><span></span><span class="nb">print</span> <span class="s2">&quot;Hello sphinx world&quot;</span>
E         ?                                  +++++++++++++
E           </pre></div>

test_highlighting.py:95: AssertionError
```
