### ISSUE TITLE
UnicodeEncodeError when commit author name has unicode characters

### ISSUE THREAD

**Issue by szymonlopaciuk** [sphinx-doc/sphinx#4228]
Subject: UnicodeEncodeError when author commit has unicode characters

### Problem
Committed some code with my name containing a unicode character `Ł`, `sphinx-build` fails with the output below. Had to workaround by converting my name to ASCII.

#### Procedure to reproduce the problem
```
sphinx-build -qnN docs docs/_build/html
```

#### Error logs / results
```
# Sphinx version: 1.6.5
# Python version: 2.7.13 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/szymonlopaciuk/.virtualenvs/inspire-schemas/lib/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/szymonlopaciuk/.virtualenvs/inspire-schemas/lib/python2.7/site-packages/sphinx/application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "/home/szymonlopaciuk/.virtualenvs/inspire-schemas/lib/python2.7/site-packages/sphinx/config.py", line 150, in __init__
    execfile_(filename, config)
  File "/home/szymonlopaciuk/.virtualenvs/inspire-schemas/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/szymonlopaciuk/.virtualenvs/inspire-schemas/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 50, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0141' in position 17: ordinal not in range(128)
```

#### Expected results
Proceed without errors.

### Reproducible project / your project
- https://github.com/inspirehep/inspire-schemas

### Environment info
- OS: Fedora Linux 26
- Python version: 2.7.13
- Sphinx version: 1.6.5

**Comment by tk0miya** [comment]
`conf.py` is a python script. so you need to use unicode literal `u'...'` to use unicode chars if you use python 2.x (Or moving to python 3.x!).
Please check your `conf.py` again.

Thanks,
