### ISSUE TITLE
Get error when generate PDF doc！

### ISSUE THREAD

**Issue by Shadowell** [sphinx-doc/sphinx#4252]
Subject: <what happen when you do on which document project>

### Problem
- I want to generate a pdf document by sphinx,but its fail every time when i use the commond "make latexpdf" in win10 platform.Is there something need be installed?
And what should I do if I want generate pdf doc which include Chinese characters?
Begging For your advices!
Thinks!

#### Procedure to reproduce the problem
```
>make latexpdf

```
Exception occurred:
  File "E:\Data\PBT\Python\Python36\site-packages\sphinx\registry.py", line 196, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "E:\Data\PBT\Python\Python36\site-packages\rst2pdf\pdfbuilder.py", line 129
    except Exception, e:
                    ^
SyntaxError: invalid syntax

#### Error logs / results
```
# Sphinx version: 1.6.5
# Python version: 3.6.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "E:\Data\PBT\Python\Python36\site-packages\sphinx\cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "E:\Data\PBT\Python\Python36\site-packages\sphinx\application.py", line 196, in __init__
    self.setup_extension(extension)
  File "E:\Data\PBT\Python\Python36\site-packages\sphinx\application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "E:\Data\PBT\Python\Python36\site-packages\sphinx\registry.py", line 196, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "E:\Data\PBT\Python\Python36\site-packages\rst2pdf\pdfbuilder.py", line 129
    except Exception, e:
                    ^
SyntaxError: invalid syntax

```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version>Win 10 
- Python version: 3.6.3 (CPython)
- Sphinx version:1.6.5
- <Extra tools e.g.: Browser, tex or something else>

**Comment by stephenfin** [comment]
```
  File "E:\Data\PBT\Python\Python36\site-packages\rst2pdf\pdfbuilder.py", line 129
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

This seems to refer to the `rst2pdf.pdfbuilder` builder which is not part of stock Sphinx. Please remove this from `extensions` and try again.

**Comment by tk0miya** [comment]
rst2pdf is not supported python3. You need to downgrade your python to use it.

Anyway, this is not a bug of Sphinx.
Thanks,
