### ISSUE TITLE
WarningIsErrorFilter fails to print traceback in v1.6.4

### ISSUE THREAD

**Issue by jonny-qmenta** [sphinx-doc/sphinx#4290]
Subject: WarningIsErrorFilter fails to print traceback in v1.6.4 (can't use v1.6.5 due to other un-traceable error)

### Problem
Traceback formatting fails at line 363:
`raise SphinxWarning(message % record.args)`
in this class:
```
class WarningIsErrorFilter(logging.Filter):
    """Raise exception if warning emitted."""

    def __init__(self, app):
        # type: (Sphinx) -> None
        self.app = app
        super(WarningIsErrorFilter, self).__init__()

    def filter(self, record):
        # type: (logging.LogRecord) -> bool
        if getattr(record, 'skip_warningsiserror', False):
            # disabled by DisableWarningIsErrorFilter
            return True
        elif self.app.warningiserror:
            location = getattr(record, 'location', '')
            message = record.msg.replace('%', '%%')
            if location:
                raise SphinxWarning(location + ":" + message % record.args)
            else:
                raise SphinxWarning(message % record.args)
        else:
            return True
```

#### Procedure to reproduce the problem
$ /path/to/python -msphinx -aEW -bhtml /path/to/doc /path/to/doc.html

Minimal conditions under which it happens are not yet known, but it is consistently failing.

#### Error logs / results
Exception occurred:
  File ".../lib/python2.7/site-packages/sphinx/util/logging.py", line 363, in filter
    raise SphinxWarning(message % record.args)
TypeError: not all arguments converted during string formatting

#### Log file
```
# Sphinx version: 1.6.4
# Python version: 2.7.13 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   Running Sphinx v1.6.4
#   building [mo]: all of 0 po files
#   building [html]: all source files
#   updating environment:
#   3 added, 0 changed, 0 removed
#   reading sources... [ 33%] index
#   reading sources... [ 66%] mintclasses
#   reading sources... [100%] minttools
#   
# Loaded extensions:
#   sphinx.ext.napoleon (1.6.4) from /var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/site-packages/sphinx/ext/napoleon/__init__.pyc
#   sphinx.ext.autodoc (1.6.4) from /var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   alabaster (0.7.10) from /var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/site-packages/alabaster/__init__.pyc
Traceback (most recent call last):
  File "/var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_all()
  File "/var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 288, in build_all
    self.build(None, summary='all source files', method='all')
  File "/var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 344, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/site-packages/sphinx/util/logging.py", line 225, in pending_warnings
    memhandler.flushTo(logger)
  File "/var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/site-packages/sphinx/util/logging.py", line 191, in flushTo
    logger.handle(record)
  File "/var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/logging/__init__.py", line 755, in handle
    rv = self.filter(record)
  File "/var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/logging/__init__.py", line 617, in filter
    if not f.filter(record):
  File "/var/lib/go-agent/pipelines/DEV-1211-sphinx-fix.commit/.repo/qmenta_tools/doc/lib/python2.7/site-packages/sphinx/util/logging.py", line 363, in filter
    raise SphinxWarning(message % record.args)
TypeError: not all arguments converted during string formatting
```

#### Expected results
A traceback showing the root cause of the error.

### Environment info
- OS: Ubuntu 16.04 LXC container
- Python version: Python 2.7.13 :: Continuum Analytics, Inc. (i.e. from an anaconda environment)
- Sphinx version: 1.6.4
- <Extra tools e.g.: Browser, tex or something else>: 

$ ./bin/conda list --no-pip
cairo                     1.14.8                        0  
certifi                   2016.2.28                py27_0  
cycler                    0.10.0                   py27_0  
dbus                      1.10.20                       0  
decorator                 4.1.2                    py27_0  
expat                     2.1.0                         0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
functools32               3.2.3.2                  py27_0  
glib                      2.50.2                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
icu                       54.1                          0  
jbig                      2.1                           0  
jpeg                      9b                            0  
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.30                        1  
libtiff                   4.0.6                         3  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
matplotlib                2.0.2               np113py27_0  
mkl                       2017.0.3                      0  
networkx                  1.11                     py27_0  
numpy                     1.13.1                   py27_0  
olefile                   0.44                     py27_0  
openssl                   1.0.2l                        0  
pandas                    0.20.3                   py27_0  
patsy                     0.4.1                    py27_0  
pcre                      8.39                          1  
pillow                    4.2.1                    py27_0  
pip                       9.0.1                    py27_1  
pixman                    0.34.0                        0  
pycairo                   1.10.0                   py27_0  
pyparsing                 2.2.0                    py27_0  
pyqt                      5.6.0                    py27_2  
python                    2.7.13                        0  
python-dateutil           2.6.1                    py27_0  
pytz                      2017.2                   py27_0  
pywavelets                0.5.2               np113py27_0  
qt                        5.6.2                         5  
readline                  6.2                           2  
scikit-image              0.13.0              np113py27_0  
scikit-learn              0.19.0              np113py27_0  
scipy                     0.19.1              np113py27_0  
seaborn                   0.8                      py27_0  
setuptools                36.4.0                   py27_1  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
statsmodels               0.8.0               np113py27_0  
subprocess32              3.2.7                    py27_0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
xz                        5.2.3                         0  
zlib                      1.2.11                        0  

$ ./bin/pip freeze
alabaster==0.7.10
attrs==17.3.0
Babel==2.5.1
certifi==2017.11.5
chardet==3.0.4
click==6.7
configparser==3.5.0
cycler==0.10.0
decorator==4.1.2
dipy==0.13.0
docutils==0.14
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
h5py==2.7.1
idna==2.6
imagesize==0.7.1
isodate==0.6.0
Jinja2==2.10
lxml==4.1.1
MarkupSafe==1.0
matplotlib==2.0.2
mock==2.0.0
mpmath==1.0.0
networkx==1.11
nibabel==2.2.1
nilearn==0.4.0
nipy==0.4.1
nipype==0.14.0
nose==1.3.7
nose-xunitmp==0.4.0
numpy==1.13.1
olefile==0.44
packaging==16.8
pandas==0.20.3
patsy==0.4.1
pbr==3.1.1
Pillow==4.2.1
pluggy==0.6.0
prov==1.5.0
py==1.5.2
pycairo==1.10.0
pydicom==0.9.9
pydot==1.2.3
pydotplus==2.0.2
Pygments==2.2.0
pyparsing==2.2.0
pytest==3.3.1
python-dateutil==2.6.1
pytz==2017.2
PyWavelets==0.5.2
rdflib==4.2.2
requests==2.18.4
scikit-image==0.13.0
scikit-learn==0.19.0
scipy==0.19.1
seaborn==0.8
simplejson==3.13.2
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.6.4
sphinxcontrib-websupport==1.0.1
statsmodels==0.8.0
subprocess32==3.2.7
sympy==1.1.1
testfixtures==5.3.1
traits==4.6.0
typing==3.6.2
urllib3==1.22

**Comment by jonny-qmenta** [comment]
After some more digging this turns out to be hiding the same error I get from 1.6.5, so it's actually already fixed.
