### ISSUE TITLE
problem producing latex with version 1.0b

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#430]
The html build is fine.
# Sphinx version: 1.0b1
# Docutils version: 0.6 release
# Jinja2 version: 2.2.1

Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/Sphinx-1.0b1-py2.6.egg/sphinx/cmdline.py", line 173, in main
    app.build(force_all, filenames)
  File "/Library/Python/2.6/site-packages/Sphinx-1.0b1-py2.6.egg/sphinx/application.py", line 205, in build
    self.builder.build_update()
  File "/Library/Python/2.6/site-packages/Sphinx-1.0b1-py2.6.egg/sphinx/builders/**init**.py", line 193, in build_update
    self.build(['**all**'], to_build)
  File "/Library/Python/2.6/site-packages/Sphinx-1.0b1-py2.6.egg/sphinx/builders/**init**.py", line 254, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Library/Python/2.6/site-packages/Sphinx-1.0b1-py2.6.egg/sphinx/builders/latex.py", line 109, in write
    docwriter.write(doctree, destination)
  File "/Library/Python/2.6/site-packages/docutils-0.6-py2.6.egg/docutils/writers/**init**.py", line 76, in write
    self.translate()
  File "/Library/Python/2.6/site-packages/Sphinx-1.0b1-py2.6.egg/sphinx/writers/latex.py", line 91, in translate
    self.document.walkabout(visitor)
  File "/Library/Python/2.6/site-packages/docutils-0.6-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Library/Python/2.6/site-packages/docutils-0.6-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Library/Python/2.6/site-packages/docutils-0.6-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Library/Python/2.6/site-packages/docutils-0.6-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Library/Python/2.6/site-packages/docutils-0.6-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Library/Python/2.6/site-packages/docutils-0.6-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Library/Python/2.6/site-packages/docutils-0.6-py2.6.egg/docutils/nodes.py", line 165, in walkabout
    visitor.dispatch_visit(self)
  File "/Library/Python/2.6/site-packages/docutils-0.6-py2.6.egg/docutils/nodes.py", line 1604, in dispatch_visit
    return method(node)
  File "/Library/Python/2.6/site-packages/Sphinx-1.0b1-py2.6.egg/sphinx/writers/latex.py", line 1061, in visit_reference
    if len(node) and 'std-term' in node[0].get('classes', []):
AttributeError: 'Text' object has no attribute 'get'

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/430
- Originally reported by: Anonymous
- Originally created at: 2010-05-27T09:52:01.733

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-05-27 17:31:49+00:00_

Thanks for reporting, should be fixed in <<cset d491eda986026c084fa9eb60e0949cd4d83a552c>>.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2013-03-31 13:57:19+00:00_

Removing version: 0.6.5 (automated comment)
