### ISSUE TITLE
(SOLVED) AttributeError: type object 'MESSAGES' has no attribute '__members__'

### ISSUE THREAD

**Issue by HWiese1980** [sphinx-doc/sphinx#4336]
Subject: during `make`ing my documentation the following error occured:

    Exception occurred:
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 902, in get_object_members
        item for item in self.object.__members__.items()
    AttributeError: type object 'MESSAGES' has no attribute '__members__'

### Problem
- ~~I don't really know what that 'MESSAGES' is and where it comes from~~
- `MESSAGE` is a class derived from `enum.Enum` from the package ~~enum34~~ `enum` (obviously the wrong enum package) and looks like this:

        class MESSAGES(Enum):
            NAME = 0
            SUBFLOW_BATCHSIZE = 1
            SUBMITTED = 2
            FINISHED = 3
            CREATION_FINISHED = 4
            EXECUTE_SUBFLOWS = 5
            IS_READY = 6
            GET = 7
            SET = 8
    

#### Procedure to reproduce the problem
I just do a `make html` in a rather big docs project. 

#### Error logs / results
```
    # Sphinx version: 1.6.5
    # Python version: 2.7.12 (CPython)
    # Docutils version: 0.14 
    # Jinja2 version: 2.10
    # Last messages:
    #   building [mo]: targets for 0 po files that are out of date
    #   building [html]: targets for 277 source files that are out of date
    #   updating environment:
    #   285 added, 0 changed, 0 removed
    #   reading sources... [  0%] <some masked project internals>
    #   reading sources... [  0%] <some masked project internals>
    #   reading sources... [  1%] <some masked project internals>
    #   reading sources... [  1%] <some masked project internals>
    #   reading sources... [  1%] <some masked project internals>
    #   reading sources... [  2%] <some masked project internals>
    # Loaded extensions:
    #   sphinx.ext.inheritance_diagram (1.6.5) from /home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/inheritance_diagram.pyc
    #   sphinx.ext.viewcode (1.6.5) from /home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/viewcode.pyc
    #   sphinx.ext.todo (1.6.5) from /home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/todo.pyc
    #   sphinx.ext.autodoc (1.6.5) from /home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
    #   sphinx.ext.intersphinx (1.6.5) from /home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
    #   sphinx.ext.graphviz (1.6.5) from /home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/graphviz.pyc
    #   alabaster (0.7.10) from /home/myuser/virtualenv_py27/lib/python2.7/site-packages/alabaster/__init__.pyc
    #   sphinx.ext.imgmath (1.6.5) from /home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/imgmath.pyc
    #   sphinx.ext.autosummary (1.6.5) from /home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/autosummary/__init__.pyc
    Traceback (most recent call last):
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
        app.build(opts.force_all, filenames)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/application.py", line 339, in build
        self.builder.build_update()
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 331, in build_update
        'out of date' % len(to_build))
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 344, in build
        updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 584, in update
        self._read_serial(docnames, self.app)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 603, in _read_serial
        self.read_doc(docname, app)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 726, in read_doc
        pub.publish()
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
        self.settings)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/io.py", line 74, in read
        self.parse()
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
        self.parser.parse(self.input, document)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
        self.statemachine.run(inputlines, document, inliner=self.inliner)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
        input_source=document['source'])
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
        context, state, transitions)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
        return method(match, context, next_state)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
        self.section(title, source, style, lineno - 1, messages)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
        self.new_subsection(title, lineno, messages)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
        node=section_node, match_titles=True)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
        node=node, match_titles=match_titles)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
        results = StateMachineWS.run(self, input_lines, input_offset)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
        context, state, transitions)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
        return method(match, context, next_state)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
        self.section(title, source, style, lineno - 1, messages)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
        self.new_subsection(title, lineno, messages)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
        node=section_node, match_titles=True)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
        node=node, match_titles=match_titles)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
        results = StateMachineWS.run(self, input_lines, input_offset)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
        context, state, transitions)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
        return method(match, context, next_state)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
        self.section(title, source, style, lineno - 1, messages)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
        self.new_subsection(title, lineno, messages)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
        node=section_node, match_titles=True)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
        node=node, match_titles=match_titles)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
        results = StateMachineWS.run(self, input_lines, input_offset)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
        context, state, transitions)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
        return method(match, context, next_state)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
        nodelist, blank_finish = self.explicit_construct(match)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
        return method(self, expmatch)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
        directive_class, match, type_name, option_presets)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
        result = directive_instance.run()
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 1833, in run
        documenter.generate(more_content=self.content)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 1133, in generate
        self.document_members(all_members)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 1530, in document_members
        ModuleLevelDocumenter.document_members(self, all_members)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 1054, in document_members
        check_module=members_check_module and not isattr)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 1133, in generate
        self.document_members(all_members)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 1530, in document_members
        ModuleLevelDocumenter.document_members(self, all_members)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 1012, in document_members
        members_check_module, members = self.get_object_members(want_all)
      File "/home/myuser/virtualenv_py27/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 902, in get_object_members
        item for item in self.object.__members__.items()
    AttributeError: type object 'MESSAGES' has no attribute '__members__'
```

#### Expected results
Well, the documentation should build

### Reproducible project / your project
There's none that I could link, unfortunately...

### Environment info
- OS: Ubuntu 16.04 LTS
- Python version: 2.7 (in a virtual environment)
- Sphinx version: 1.6.5

**Comment by HWiese1980** [comment]
I've solved this issue myself. It was related to a wrong `enum` package. The correct one is called `enum34`. With that installed instead of `enum` this error is gone.

**Comment by HEHenson** [comment]
I had the same error while working in Ubuntu as well.

**Comment by tk0miya** [comment]
@HEHenson It seems first report was caused by `enum34` pacakge. What about your case? Anyway, this is already closed issue. So please file a new issue if you'd like to fix the error.

Note: At present, we've not support python2. So I believe this problem is not happened now.
