### ISSUE TITLE
Sphink cannot import Celery

### ISSUE THREAD

**Issue by Nemesisesq** [sphinx-doc/sphinx#4348]
Subject: <what happen when you do on which document project>

### Problem
- I am trying to document a django project with sphinx and I'm having a really hard time. I am using autodoc and I appear to have everything configured correctly. I have a celery implementation in my settings folder and it cannot import Celery from celery  

#### Error logs / results
```
/Users/nemesisesq/boldpenguin/emperor/docs/modules/views.rst:3: WARNING: autodoc: failed to import module 'emperor.accounts.views'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/nemesisesq/.virtualenvs/emperor/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/Users/nemesisesq/boldpenguin/emperor/emperor/__init__.py", line 2, in <module>
    from .celery import app as celery_app
  File "/Users/nemesisesq/boldpenguin/emperor/emperor/celery.py", line 4, in <module>
    from celery import Celery
  File "/Users/nemesisesq/boldpenguin/emperor/emperor/celery.py", line 4, in <module>
    from celery import Celery
ImportError: cannot import name 'Celery'

```
### Environment info
- OS: macOS11
- Python version: 3.6s

**Comment by tk0miya** [comment]
Can you import celery from python (not django)? Sphinx imports it on building. So you need to set up your environment (ex. `sys.path`) to import it.

**Comment by tk0miya** [comment]
I'm closing this now because it seems no updates.
Feel free to reopen this if you still have this problem.

Thanks,
