### ISSUE TITLE
IOError: [Errno socket error] [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by wadelee1986** [sphinx-doc/sphinx#4369]
```
Running Sphinx v1.6.5

Exception occurred:
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 110] Connection timed out
The full traceback has been saved in /tmp/sphinx-err-YLn9Zv.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```

```
# Sphinx version: 1.6.5
# Python version: 2.7.5 (CPython)
# Docutils version: 0.14
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib64/python2.7/site-packages/sphinx/application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "/usr/lib64/python2.7/site-packages/sphinx/config.py", line 150, in __init__
    execfile_(filename, config)
  File "/usr/lib64/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/usr/lib/python2.7/site-packages/six.py", line 672, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 185, in <module>
    urllib.urlretrieve(repo+branch+'/ansible/README.rst', filename=tools+'/ansible.rst')
  File "/usr/lib64/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib64/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib64/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib64/python2.7/urllib.py", line 437, in open_https
    h.endheaders(data)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1227, in connect
    HTTPConnection.connect(self)
  File "/usr/lib64/python2.7/httplib.py", line 807, in connect
    self.timeout, self.source_address)
```

**Comment by tk0miya** [comment]
Thank you for reporting. It seems connection timeout has happened in your conf.py (not sphinx-core). Please check your configuration or environment.
Thanks,

**Comment by wadelee1986** [comment]
Thanks a lot;

I have fixed it.
