### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128) 

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#451]
When I make html a the boilerplate project created with sphinx-quickstart I get this traceback:

```
#!python

# Sphinx version: 1.0pre
# Docutils version: 0.6 release
# Jinja2 version: 2.4.1
Traceback (most recent call last):
  File "/Users/Shared/Code/python26/lib/python2.6/site-packages/Sphinx-1.0pre_d2ce667074acdev_20100427-py2.6.egg/sphinx/cmdline.py", line 173, in main
    app.build(force_all, filenames)
  File "/Users/Shared/Code/python26/lib/python2.6/site-packages/Sphinx-1.0pre_d2ce667074acdev_20100427-py2.6.egg/sphinx/application.py", line 205, in build
    self.builder.build_update()
  File "/Users/Shared/Code/python26/lib/python2.6/site-packages/Sphinx-1.0pre_d2ce667074acdev_20100427-py2.6.egg/sphinx/builders/__init__.py", line 198, in build_update
    'out of date' &#37; len(to_build))
  File "/Users/Shared/Code/python26/lib/python2.6/site-packages/Sphinx-1.0pre_d2ce667074acdev_20100427-py2.6.egg/sphinx/builders/__init__.py", line 254, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/Shared/Code/python26/lib/python2.6/site-packages/Sphinx-1.0pre_d2ce667074acdev_20100427-py2.6.egg/sphinx/builders/__init__.py", line 293, in write
    self.write_doc(docname, doctree)
  File "/Users/Shared/Code/python26/lib/python2.6/site-packages/Sphinx-1.0pre_d2ce667074acdev_20100427-py2.6.egg/sphinx/builders/html.py", line 401, in write_doc
    self.docwriter.write(doctree, destination)
  File "/Users/Shared/Code/python26/lib/python2.6/site-packages/docutils-0.6-py2.6.egg/docutils/writers/__init__.py", line 76, in write
    self.translate()
  File "/Users/Shared/Code/python26/lib/python2.6/site-packages/Sphinx-1.0pre_d2ce667074acdev_20100427-py2.6.egg/sphinx/writers/html.py", line 37, in translate
    self.document.walkabout(visitor)
  File "/Users/Shared/Code/python26/lib/python2.6/site-packages/docutils-0.6-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Users/Shared/Code/python26/lib/python2.6/site-packages/docutils-0.6-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Users/Shared/Code/python26/lib/python2.6/site-packages/docutils-0.6-py2.6.egg/docutils/nodes.py", line 186, in walkabout
    visitor.dispatch_departure(self)
  File "/Users/Shared/Code/python26/lib/python2.6/site-packages/docutils-0.6-py2.6.egg/docutils/nodes.py", line 1617, in dispatch_departure
    return method(node)
  File "/Users/Shared/Code/python26/lib/python2.6/site-packages/Sphinx-1.0pre_d2ce667074acdev_20100427-py2.6.egg/sphinx/writers/html.py", line 467, in depart_title
    _('Permalink to this headline'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/451
- Originally reported by: Anonymous
- Originally created at: 2010-06-12T18:36:47.200

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-06-12 17:55:26+00:00_

Can you retry with 1.0 beta 2?  This should be fixed there.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-08-14 15:19:31+00:00_

Removing version: 1.0beta (automated comment)
