### ISSUE TITLE
mock imports failing

### ISSUE THREAD

**Issue by gboeing** [sphinx-doc/sphinx#4554]
Subject: Mock imports are failing when building documentation

### Problem

I have been using sphinx to building docs for [OSMnx](https://github.com/gboeing/osmnx) for a year. It always worked fine. Recently it started failing.

When I run it and do not use `autodoc_mock_imports`:

```
make html
```

Everything works fine because I have the imported modules installed locally:

```
Running Sphinx v1.7.0b2
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: [config changed] 2 added, 0 changed, 0 removed
reading sources... [100%] osmnx
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] osmnx
generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

The HTML pages are in build\html.
```

After running the above, all the individual module pages have documentation in them. But to run it on readthedocs, I need to mock the imports:

```python
autodoc_mock_imports = ['dateutil',
                        'descartes',
                        'fiona',
                        'geopandas',
                        'matplotlib.cm',
                        'matplotlib.collections',
                        'matplotlib.pyplot',
                        'networkx',
                        'numpy',
                        'pandas',
                        'requests',
                        'shapely',
                        'shapely.geometry',
                        'shapely.ops']
```

Now when I run it:

```
make html
```

It fails:

```
Running Sphinx v1.7.0b2
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: [config changed] 2 added, 0 changed, 0 removed
reading sources... [100%] osmnx
WARNING: autodoc: failed to import module 'osmnx.buildings'; the following exception was raised:
Matplotlib requires numpy>=1.7.1; you have <sphinx.ext.autodoc.importer._MockObject object at 0x0000020C6081A588>
WARNING: autodoc: failed to import module 'osmnx.core'; the following exception was raised:
Matplotlib requires numpy>=1.7.1; you have <sphinx.ext.autodoc.importer._MockObject object at 0x0000020C609C32B0>
WARNING: autodoc: failed to import module 'osmnx.elevation'; the following exception was raised:
Matplotlib requires numpy>=1.7.1; you have <sphinx.ext.autodoc.importer._MockObject object at 0x0000020C609C3908>
WARNING: autodoc: failed to import module 'osmnx.plot'; the following exception was raised:
Matplotlib requires numpy>=1.7.1; you have <sphinx.ext.autodoc.importer._MockObject object at 0x0000020C609B05F8>
WARNING: autodoc: failed to import module 'osmnx.projection'; the following exception was raised:
Matplotlib requires numpy>=1.7.1; you have <sphinx.ext.autodoc.importer._MockObject object at 0x0000020C609B0A90>
WARNING: autodoc: failed to import module 'osmnx.save_load'; the following exception was raised:
Matplotlib requires numpy>=1.7.1; you have <sphinx.ext.autodoc.importer._MockObject object at 0x0000020C60A003C8>
WARNING: autodoc: failed to import module 'osmnx.settings'; the following exception was raised:
Matplotlib requires numpy>=1.7.1; you have <sphinx.ext.autodoc.importer._MockObject object at 0x0000020C60A00860>
WARNING: autodoc: failed to import module 'osmnx.simplify'; the following exception was raised:
Matplotlib requires numpy>=1.7.1; you have <sphinx.ext.autodoc.importer._MockObject object at 0x0000020C60A00828>
WARNING: autodoc: failed to import module 'osmnx.stats'; the following exception was raised:
Matplotlib requires numpy>=1.7.1; you have <sphinx.ext.autodoc.importer._MockObject object at 0x0000020C60A00B70>
WARNING: autodoc: failed to import module 'osmnx.utils'; the following exception was raised:
Matplotlib requires numpy>=1.7.1; you have <sphinx.ext.autodoc.importer._MockObject object at 0x0000020C60A12080>
WARNING: autodoc: failed to import module 'osmnx'; the following exception was raised:
Matplotlib requires numpy>=1.7.1; you have <sphinx.ext.autodoc.importer._MockObject object at 0x0000020C609DC5C0>
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] osmnx
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 11 warnings.

The HTML pages are in build\html.
```

None of the module pages have any documentation in them anymore, because none of them could be imported. See: https://osmnx.readthedocs.io/en/latest/osmnx.html

If I do the same thing only with sphinx 1.6.7 instead, it still fails but with a different set of warnings that none of the OSMnx modules could be imported:

```
Running Sphinx v1.6.7
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] osmnx
G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\docs\source\osmnx.rst:10: WARNING: autodoc: failed to import module 'osmnx.buildings'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\__init__.py", line 9, in <module>
    from .buildings import *
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\buildings.py", line 9, in <module>
    import geopandas as gpd
  File "C:\Anaconda\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\Anaconda\lib\site-packages\geopandas\geoseries.py", line 5, in <module>
    from pandas import Series
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Anaconda\lib\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "pandas/_libs/tslib.pyx", line 1, in init pandas._libs.tslib
  File "pandas/_libs/tslibs/timedeltas.pyx", line 4, in init pandas._libs.tslibs.timedeltas
TypeError: '>=' not supported between instances of '_MockObject' and 'int'
G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\docs\source\osmnx.rst:18: WARNING: autodoc: failed to import module 'osmnx.core'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Anaconda\lib\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
ImportError: cannot import name 'iNaT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\__init__.py", line 9, in <module>
    from .buildings import *
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\buildings.py", line 9, in <module>
    import geopandas as gpd
  File "C:\Anaconda\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\Anaconda\lib\site-packages\geopandas\geoseries.py", line 5, in <module>
    from pandas import Series
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: 'iNaT' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\docs\source\osmnx.rst:26: WARNING: autodoc: failed to import module 'osmnx.elevation'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Anaconda\lib\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
ImportError: cannot import name 'iNaT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\__init__.py", line 9, in <module>
    from .buildings import *
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\buildings.py", line 9, in <module>
    import geopandas as gpd
  File "C:\Anaconda\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\Anaconda\lib\site-packages\geopandas\geoseries.py", line 5, in <module>
    from pandas import Series
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: 'iNaT' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\docs\source\osmnx.rst:34: WARNING: autodoc: failed to import module 'osmnx.plot'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Anaconda\lib\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
ImportError: cannot import name 'iNaT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\__init__.py", line 9, in <module>
    from .buildings import *
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\buildings.py", line 9, in <module>
    import geopandas as gpd
  File "C:\Anaconda\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\Anaconda\lib\site-packages\geopandas\geoseries.py", line 5, in <module>
    from pandas import Series
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: 'iNaT' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\docs\source\osmnx.rst:42: WARNING: autodoc: failed to import module 'osmnx.projection'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Anaconda\lib\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
ImportError: cannot import name 'iNaT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\__init__.py", line 9, in <module>
    from .buildings import *
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\buildings.py", line 9, in <module>
    import geopandas as gpd
  File "C:\Anaconda\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\Anaconda\lib\site-packages\geopandas\geoseries.py", line 5, in <module>
    from pandas import Series
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: 'iNaT' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\docs\source\osmnx.rst:50: WARNING: autodoc: failed to import module 'osmnx.save_load'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Anaconda\lib\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
ImportError: cannot import name 'iNaT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\__init__.py", line 9, in <module>
    from .buildings import *
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\buildings.py", line 9, in <module>
    import geopandas as gpd
  File "C:\Anaconda\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\Anaconda\lib\site-packages\geopandas\geoseries.py", line 5, in <module>
    from pandas import Series
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: 'iNaT' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\docs\source\osmnx.rst:58: WARNING: autodoc: failed to import module 'osmnx.settings'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Anaconda\lib\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
ImportError: cannot import name 'iNaT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\__init__.py", line 9, in <module>
    from .buildings import *
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\buildings.py", line 9, in <module>
    import geopandas as gpd
  File "C:\Anaconda\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\Anaconda\lib\site-packages\geopandas\geoseries.py", line 5, in <module>
    from pandas import Series
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: 'iNaT' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\docs\source\osmnx.rst:66: WARNING: autodoc: failed to import module 'osmnx.simplify'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Anaconda\lib\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
ImportError: cannot import name 'iNaT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\__init__.py", line 9, in <module>
    from .buildings import *
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\buildings.py", line 9, in <module>
    import geopandas as gpd
  File "C:\Anaconda\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\Anaconda\lib\site-packages\geopandas\geoseries.py", line 5, in <module>
    from pandas import Series
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: 'iNaT' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\docs\source\osmnx.rst:74: WARNING: autodoc: failed to import module 'osmnx.stats'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Anaconda\lib\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
ImportError: cannot import name 'iNaT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\__init__.py", line 9, in <module>
    from .buildings import *
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\buildings.py", line 9, in <module>
    import geopandas as gpd
  File "C:\Anaconda\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\Anaconda\lib\site-packages\geopandas\geoseries.py", line 5, in <module>
    from pandas import Series
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: 'iNaT' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\docs\source\osmnx.rst:82: WARNING: autodoc: failed to import module 'osmnx.utils'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Anaconda\lib\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
ImportError: cannot import name 'iNaT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\__init__.py", line 9, in <module>
    from .buildings import *
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\buildings.py", line 9, in <module>
    import geopandas as gpd
  File "C:\Anaconda\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\Anaconda\lib\site-packages\geopandas\geoseries.py", line 5, in <module>
    from pandas import Series
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: 'iNaT' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\docs\source\osmnx.rst:91: WARNING: autodoc: failed to import module 'osmnx'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Anaconda\lib\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
ImportError: cannot import name 'iNaT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\__init__.py", line 9, in <module>
    from .buildings import *
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\buildings.py", line 9, in <module>
    import geopandas as gpd
  File "C:\Anaconda\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\Anaconda\lib\site-packages\geopandas\geoseries.py", line 5, in <module>
    from pandas import Series
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: 'iNaT' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] osmnx
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 11 warnings.

Build finished. The HTML pages are in build\html.
```

### Reproducible project / your project

https://github.com/gboeing/osmnx/tree/master/docs

https://osmnx.readthedocs.io/en/latest/osmnx.html

### Environment info
- OS: Win 10
- Python version: 3.6
- Sphinx version: tried with 1.7.0b2 and 1.6.7
- autodoc, napoleon

**Comment by tk0miya** [comment]
```
WARNING: autodoc: failed to import module 'osmnx.buildings'; the following exception was raised:
Matplotlib requires numpy>=1.7.1; you have <sphinx.ext.autodoc.importer._MockObject object at 0x0000020C6081A588>
```
Why don't you mock whole of matplotlib? This message says that matplotlib tried to import numpy, but it failed because numpy was mocked.

```
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\__init__.py", line 9, in <module>
    from .buildings import *
  File "G:\Geoff\Dropbox\Documents\School\PhD\Projects\Code\osmnx-repos\osmnx\osmnx\buildings.py", line 9, in <module>
    import geopandas as gpd
  File "C:\Anaconda\lib\site-packages\geopandas\__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\Anaconda\lib\site-packages\geopandas\geoseries.py", line 5, in <module>
    from pandas import Series
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Anaconda\lib\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "pandas/_libs/tslib.pyx", line 1, in init pandas._libs.tslib
  File "pandas/_libs/tslibs/timedeltas.pyx", line 4, in init pandas._libs.tslibs.timedeltas
TypeError: '>=' not supported between instances of '_MockObject' and 'int'
```
On the other hand, latter message says importing pandas was failed. this is a bit strange because it seems you'd set pandas as mock_imports.

**Comment by tk0miya** [comment]
Any updates? I think this is not a bug of Sphinx.
So I'd like to close this.

**Comment by gboeing** [comment]
fixed it with a conda env: https://github.com/gboeing/osmnx/pull/126
