### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#458]
run

make clean html

and get this:
# Sphinx version: 1.0b2$
# Docutils version: 0.6 release$
# Jinja2 version: 2.2.1$

Traceback (most recent call last):$
  File "/usr/local/lib/python2.6/site-packages/Sphinx-1.0b2-py2.6.egg/sphinx/cmdline.py", line 173, in main$
    app.build(force_all, filenames)$
  File "/usr/local/lib/python2.6/site-packages/Sphinx-1.0b2-py2.6.egg/sphinx/application.py", line 205, in build$
    self.builder.build_update()$
  File "/usr/local/lib/python2.6/site-packages/Sphinx-1.0b2-py2.6.egg/sphinx/builders/**init**.py", line 198, in build_update$
    'out of date' &#37; len(to_build))$
  File "/usr/local/lib/python2.6/site-packages/Sphinx-1.0b2-py2.6.egg/sphinx/builders/**init**.py", line 257, in build$
    self.finish()$
  File "/usr/local/lib/python2.6/site-packages/Sphinx-1.0b2-py2.6.egg/sphinx/builders/html.py", line 421, in finish$
    for pagename, context, template in pagelist:$
  File "/usr/local/lib/python2.6/site-packages/Sphinx-1.0b2-py2.6.egg/sphinx/ext/viewcode.py", line 115, in collect_pages$
    lines[min(end - 1, maxindex)] += '</div>'$
IndexError: list index out of range

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/458
- Originally reported by: Evgeny Fadeev
- Originally created at: 2010-06-27T19:57:45.437

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-07-02 09:54:04+00:00_

Thanks for reporting, this is fixed in trunk already and will be part of beta 3.

Duplicate of #433.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-08-14 15:19:30+00:00_

Removing version: 1.0beta (automated comment)
