### ISSUE TITLE
TypeError happened when running sphinx-build

### ISSUE THREAD

**Issue by stupidchen** [sphinx-doc/sphinx#4681]
Subject: TypeError happened when running sphinx-build

### Problem

When running sphinx-build a TypeError was raised. Nothing was output except .doctree

#### Procedure to reproduce the problem
```
sphinx-build doc/source output
```

#### Error logs / results

```
# Sphinx version: 1.7.1
# Python version: 3.6.2 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   pickling environment...
#   
#   done
#   
#   checking consistency...
#   
#   done
#   
#   preparing documents...
#   
# Loaded extensions:
#   alabaster (0.7.10) from c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\alabaster\__init__.py
#   sphinx.ext.autodoc (1.7.1) from c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\sphinx\ext\autodoc\__init__.py
#   sphinx.ext.doctest (1.7.1) from c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\sphinx\ext\doctest.py
#   sphinx.ext.todo (1.7.1) from c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\sphinx\ext\todo.py
#   sphinx.ext.coverage (1.7.1) from c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\sphinx\ext\coverage.py
#   sphinx.ext.viewcode (1.7.1) from c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\sphinx\ext\viewcode.py
#   sphinxcontrib.httpdomain (unknown version) from c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\sphinxcontrib\httpdomain.py
#   oslosphinx (unknown version) from c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\oslosphinx\__init__.py
Traceback (most recent call last):
  File "c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\sphinx\cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\sphinx\application.py", line 331, in build
    self.builder.build_update()
  File "c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\sphinx\builders\__init__.py", line 333, in build_update
    'out of date' % len(to_build))
  File "c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\sphinx\builders\__init__.py", line 394, in build
    self.write(docnames, list(updated_docnames), method)
  File "c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\sphinx\builders\__init__.py", line 422, in write
    self.prepare_writing(docnames)
  File "c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\sphinx\builders\html.py", line 444, in prepare_writing
    language=self.config.language)
  File "c:\users\ccc\appdata\local\programs\python\python36\lib\site-packages\sphinx\util\i18n.py", line 230, in format_date
    tokens = date_format_re.split(format)
TypeError: cannot use a string pattern on a bytes-like object

```

### Environment info
- OS: Windows 7
- Python version: 3.6.2 (CPython)
- Sphinx version:  1.7.1
- Docutils version: 0.14 
- Jinja2 version: 2.10

**Comment by stupidchen** [comment]
Here is the code raised the exeception: 

`tokens = date_format_re.split(format)`

It seems that format are bytes. Thus before it use re to split the format it should decode the format to text string. I changed the code as below and then sphinx-build works well:

`tokens = date_format_re.split(format.decode('utf-8'))`

**Comment by tk0miya** [comment]
How did you set up `html_last_updated_fmt` in conf.py? I guess it is set bytes object.

**Comment by stupidchen** [comment]
@tk0miya 

`html_last_updated_fmt` was set below in conf.py:

```
git_cmd = ["git", "log", "--pretty=format:'%ad, commit %h'", "--date=local",
           "-n1"]
html_last_updated_fmt = subprocess.Popen(
    git_cmd, stdout=subprocess.PIPE).communicate()[0]
```

I try to get the value and type of `html_last_updated_fmt` in the same environment:

```
>>> git_cmd = ["git", "log", "--pretty=format:'%ad, commit %h'", "--date=local",
...            "-n1"]
>>> html_last_updated_fmt = subprocess.Popen(
...     git_cmd, stdout=subprocess.PIPE).communicate()[0]
>>> print html_last_updated_fmt
'Tue Feb 27 10:23:08 2018, commit 5771138'
>>> print type(html_last_updated_fmt)
<type 'str'>
```

I think `html_last_updated_fmt` is a text string.

**Comment by tk0miya** [comment]
The type of return value of `subprocess.Popen()` is different between py2 and py3.
```
$ python2
Python 2.7.14 (default, Oct  4 2017, 19:47:22)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> git_cmd = ["git", "log", "--pretty=format:'%ad, commit %h'", "--date=local",
...            "-n1"]
>>> html_last_updated_fmt = subprocess.Popen(
...     git_cmd, stdout=subprocess.PIPE).communicate()[0]
>>> html_last_updated_fmt
"'Fri Mar 2 00:41:03 2018, commit bd8340e4e'"
>>> type(html_last_updated_fmt)
<type 'str'>
```
```
$ python3
Python 3.6.4 (default, Dec 20 2017, 01:09:24)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> git_cmd = ["git", "log", "--pretty=format:'%ad, commit %h'", "--date=local",
...            "-n1"]
>>> html_last_updated_fmt = subprocess.Popen(
...     git_cmd, stdout=subprocess.PIPE).communicate()[0]
>>> html_last_updated_fmt
b"'Fri Mar 2 00:41:03 2018, commit bd8340e4e'"
>>> type(html_last_updated_fmt)
<class 'bytes'>
```

And it seems your document is built with `python3`. So it `html_last_update_fmt` is a bytes data.
So please decode it before assignment.

Note: I guess you used `python2` on investigation in last comment. Because there was "print statement" in console log.

**Comment by stupidchen** [comment]
@tk0miya Thanks for your answer. I think the reason your found is right. Can I just change default Python version to make Sphinx works correctly?

P.S. I can't found `python3` command in the environment and the deafult version of `python` command is 2.7.14. But I found `Python/Python36/Scripts` and `Python/Python36` in environment variables(ORIGINAL_PATH and PATH).

**Comment by tk0miya** [comment]
Sphinx is installed as python package. Therefore the python version is determined at installation.
So please use `pip` command of python2 to install Sphinx.

**Comment by stupidchen** [comment]
@tk0miya OK! Thanks for your help!
