### ISSUE TITLE
Getting "tuple index out of range error" when generating PDF>

### ISSUE THREAD

**Issue by dcalvin** [sphinx-doc/sphinx#4686]
Subject: <Getting ` tuple index out of range` error when generating PDF>

### Problem
failed to generating PDF after I firstly installed LaTex and used it with Sphinx. Begging for help. Thanks in advance.

#### Procedure to reproduce the problem
```
# -- CLI lines---------------------------------------------

D:\Sphinx for HLTAPI>make latexpdf
Running Sphinx v1.6.3
loading translations [en]... done
loading pickled environment... done

Exception occurred:
  File "C:\Python27\lib\site-packages\sphinx\builders\latex.py", line 293, in validate_config_values
    text_type(document[3])
IndexError: tuple index out of range

# -- Options for LaTeX output in conf.py---------------------------------------------

latex_engine = 'xelatex'
latex_elements = {
'fontpkg': r'''
\setmainfont{DejaVu Serif}
\setsansfont{DejaVu Sans}
\setmonofont{DejaVu Sans Mono}
''',
'preamble': r'''
\usepackage[titles]{tocloft}
\cftsetpnumwidth {1.25cm}\cftsetrmarg{1.5cm}
\setlength{\cftchapnumwidth}{0.75cm}
\setlength{\cftsecindent}{\cftchapnumwidth}
\setlength{\cftsecnumwidth}{1.25cm}
''',
'fncychap': r'\usepackage[Bjornstrup]{fncychap}',
'printindex': r'\footnotesize\raggedright\printindex',
}
latex_show_urls = 'footnote'
 
latex_documents = [
     ('Index', 'HLTAPICmdRef.tex', 'HLTAPI Cmd Ref Documentation'),
 ]

```

#### Error logs / results
```

# Loaded extensions:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\sphinx\cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "C:\Python27\lib\site-packages\sphinx\application.py", line 234, in __init__
    self._init_builder()
  File "C:\Python27\lib\site-packages\sphinx\application.py", line 312, in _init_builder
    self.emit('builder-inited')
  File "C:\Python27\lib\site-packages\sphinx\application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "C:\Python27\lib\site-packages\sphinx\events.py", line 79, in emit
    results.append(callback(*args))
  File "C:\Python27\lib\site-packages\sphinx\builders\latex.py", line 293, in validate_config_values
    text_type(document[3])
IndexError: tuple index out of range

```
- <public link of unexpected result if you have>

### Environment info
- OS:  Windows 10
- Python version: 2.7.13 (CPython)
- Sphinx version: 1.6.3
- Docutils version: 0.14 
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
`latex_document` should be a list of tuple which has **5 or 6 elements**. I think this is configuration error. Please read our document and update it.
http://www.sphinx-doc.org/en/master/config.html#confval-latex_documents

**Comment by tk0miya** [comment]
As I commented above, this is configuration error.
So I'm closing this now.
Thanks,
