### ISSUE TITLE
AttributeError: 'ModuleAnalyzer' object has no attribute 'tokenize'

### ISSUE THREAD

**Issue by zaufi** [sphinx-doc/sphinx#4754]
https://github.com/sphinx-doc/sphinx/blob/bde42595c6f51e9648658840897d25b0827a3cf6/sphinx/pycode/__init__.py#L132

~~~
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/dev/shm/dev-python-sphinx-1.7.0/work/Sphinx-1.7.0-python3_6/lib/sphinx/pycode/__init__.py", line 129, in <module>
    ma.tokenize()
AttributeError: 'ModuleAnalyzer' object has no attribute 'tokenize'
~~~

**Comment by tk0miya** [comment]
I removed the code by #4756.
Thank you for reporting!
