### ISSUE TITLE
`make html` spits an error because simplejson is not installed.

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#476]
On a Cygwin environment without simplejson installed, I got the following after upgrading to Sphinx 1.0.1 (this worked previously with 1.0 dev):

```
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.0.1
loading pickled environment... failed: env version not current

Exception occurred:
  File "/usr/lib/python2.5/site-packages/Sphinx-1.0.1-py2.5.egg/sphinx/util/jsonimpl.py", line 42, in <module>
    load = json.load
AttributeError: 'NoneType' object has no attribute 'load'
The full traceback has been saved in /tmp/sphinx-err-F1Sjud.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1
```

The issue disappears after installing simplejson with easy_install. Shouldn't there be safeguards against this, though?

Here's the content of the temp logfile:

```
# Sphinx version: 1.0.1
# Docutils version: 0.7 release
# Jinja2 version: 2.5
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Sphinx-1.0.1-py2.5.egg/sphinx/cmdline.py", line 172, in main
    warningiserror, tags)
  File "/usr/lib/python2.5/site-packages/Sphinx-1.0.1-py2.5.egg/sphinx/application.py", line 136, in __init__
    self._init_builder(buildername)
  File "/usr/lib/python2.5/site-packages/Sphinx-1.0.1-py2.5.egg/sphinx/application.py", line 196, in _init_builder
    __import__('sphinx.builders.' + mod, None, None, [cls]), cls)
  File "/usr/lib/python2.5/site-packages/Sphinx-1.0.1-py2.5.egg/sphinx/builders/html.py", line 33, in <module>
    from sphinx.util import jsonimpl, copy_static_entry
  File "/usr/lib/python2.5/site-packages/Sphinx-1.0.1-py2.5.egg/sphinx/util/jsonimpl.py", line 42, in <module>
    load = json.load
AttributeError: 'NoneType' object has no attribute 'load'
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/476
- Originally reported by: Santoso Wijaya
- Originally created at: 2010-07-28T03:00:26.651

**Comment by shimizukawa** [comment]
_From Santoso Wijaya on 2010-07-28 01:15:07+00:00_

Looks like changeset <<cset ebb7a541419276c3207afd3a4ef2543ebac3dd48>> broke it.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-07-28 08:00:20+00:00_

And changeset <<cset a1fd9830e57944b980629ad3bf5b11771dc0af32>> fixes it. Thanks.

**Comment by shimizukawa** [comment]
_From Santoso Wijaya on 2010-08-04 20:30:02+00:00_

Issue #485 was marked as a duplicate of this issue.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-10-18 07:29:32+00:00_

Removing version: 1.0.1 (automated comment)
