### ISSUE TITLE
I make the following error when I make HTML.

### ISSUE THREAD

**Issue by SIM-YYF** [sphinx-doc/sphinx#4776]
```
# Sphinx version: 1.7.2
# Python version: 2.7.14 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   reading sources... [ 21%] doc/han-shu/han-shu-ding-yi-he-diao-yong
#   reading sources... [ 21%] doc/han-shu/han-shu-fan-hui-zhi
#   reading sources... [ 22%] doc/han-shu/han-shu-lei-dui-8c6128-ba-dui-xiang-zuo-wei-han-shu-diao-752829
#   reading sources... [ 23%] doc/han-shu/ni-ming-han-shu
#   reading sources... [ 23%] doc/index
#   reading sources... [ 24%] doc/ji-he
#   reading sources... [ 25%] doc/jin-cheng
#   reading sources... [ 25%] doc/jin-cheng-vs-xian-cheng
#   reading sources... [ 26%] doc/jin-cheng/duo-jin-cheng-kao-bei-wen-jian
#   reading sources... [ 27%] doc/jin-cheng/fork
# Loaded extensions:
#   sphinx.ext.mathjax (1.7.2) from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/ext/mathjax.pyc
#   sphinx.ext.coverage (1.7.2) from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/ext/coverage.pyc
#   sphinx.ext.viewcode (1.7.2) from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/ext/viewcode.pyc
#   sphinx.ext.todo (1.7.2) from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   sphinx.ext.autodoc (1.7.2) from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/ext/autodoc/__init__.pyc
#   sphinx.ext.intersphinx (1.7.2) from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
#   sphinx.ext.doctest (1.7.2) from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/ext/doctest.pyc
#   alabaster (0.7.10) from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.ifconfig (1.7.2) from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/ext/ifconfig.pyc
#   sphinx.ext.githubpages (1.7.2) from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/ext/githubpages.pyc
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 338, in build_update
    'out of date' % len(to_build))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 351, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 565, in update
    self._read_serial(docnames, self.app)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 584, in _read_serial
    self.read_doc(docname, app)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 659, in read_doc
    doctree = read_doc(self.app, self, self.doc2path(docname))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/io.py", line 294, in read_doc
    pub.publish()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommonmark/parser.py", line 87, in parse
    self.convert_block(ast)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommonmark/parser.py", line 49, in convert_block
    self.convert_blocks(block.children)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommonmark/parser.py", line 45, in convert_blocks
    self.convert_block(block)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommonmark/parser.py", line 59, in convert_block
    self.list_block(block)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommonmark/parser.py", line 161, in list_block
    self.convert_blocks(block.children)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommonmark/parser.py", line 45, in convert_blocks
    self.convert_block(block)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommonmark/parser.py", line 57, in convert_block
    self.list_item(block)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommonmark/parser.py", line 148, in list_item
    self.convert_blocks(block.children)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommonmark/parser.py", line 45, in convert_blocks
    self.convert_block(block)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommonmark/parser.py", line 51, in convert_block
    self.section(block)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommonmark/parser.py", line 110, in section
    self.current_node.document.note_implicit_target(new_section, new_section)
AttributeError: 'NoneType' object has no attribute 'note_implicit_target'
```

**Comment by tk0miya** [comment]
Sorry, I can't reproduce the error from this report.
Please use our reporting format.
Thanks,

Note: it seems this error is raised by recommonmark. I guess this error is related with it.
