### ISSUE TITLE
Latex customization via _templates/longtable.tex_t is broken

### ISSUE THREAD

**Issue by christiankossmann** [sphinx-doc/sphinx#4795]
### Subject
I want to customize the Latex output for longtables. In Sphinx 1.6.x this works perfectly fine by adding a template file to `_templates/longtable.tex_t` as described in the [documentation](http://www.sphinx-doc.org/en/master/latex.html#miscellany). 

### Problem
Since Sphinx 1.7.x I get the following exception:

```
Exception occurred:
  File "c:\python35-x64\lib\site-packages\sphinx\jinja2glue.py", line 141, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _templates\longtable.tex_t
```

#### Error logs / results

The full error log:

```
Traceback (most recent call last):
  File "c:\python35-x64\lib\site-packages\sphinx\cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "c:\python35-x64\lib\site-packages\sphinx\application.py", line 331, in build
    self.builder.build_update()
  File "c:\python35-x64\lib\site-packages\sphinx\builders\__init__.py", line 333, in build_update
    self.build(['__all__'], to_build)
  File "c:\python35-x64\lib\site-packages\sphinx\builders\__init__.py", line 399, in build
    self.write(docnames, list(updated_docnames), method)
  File "c:\python35-x64\lib\site-packages\sphinx\builders\latex.py", line 155, in write
    docwriter.write(doctree, destination)
  File "c:\python35-x64\lib\site-packages\docutils\writers\__init__.py", line 80, in write
    self.translate()
  File "c:\python35-x64\lib\site-packages\sphinx\writers\latex.py", line 183, in translate
    self.document.walkabout(visitor)
  File "c:\python35-x64\lib\site-packages\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "c:\python35-x64\lib\site-packages\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "c:\python35-x64\lib\site-packages\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "c:\python35-x64\lib\site-packages\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "c:\python35-x64\lib\site-packages\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "c:\python35-x64\lib\site-packages\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "c:\python35-x64\lib\site-packages\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "c:\python35-x64\lib\site-packages\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "c:\python35-x64\lib\site-packages\docutils\nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "c:\python35-x64\lib\site-packages\docutils\nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "c:\python35-x64\lib\site-packages\docutils\nodes.py", line 1895, in dispatch_departure
    return method(node)
  File "c:\python35-x64\lib\site-packages\sphinx\writers\latex.py", line 1394, in depart_table
    dict(table=self.table, labels=labels))
  File "c:\python35-x64\lib\site-packages\sphinx\writers\latex.py", line 933, in render
    return LaTeXRenderer().render(template, variables)
  File "c:\python35-x64\lib\site-packages\sphinx\util\template.py", line 35, in render
    return self.env.get_template(template_name).render(context)
  File "c:\python35-x64\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\python35-x64\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\python35-x64\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\python35-x64\lib\site-packages\sphinx\jinja2glue.py", line 141, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _templates\longtable.tex_t
```

### Environment info
- OS: Windows 10
- Python version: 3.5.4
- Sphinx version: 1.7.x

**Comment by jfbu** [comment]
Thanks for report. Confirmed on Mac OS X, with same error and this test case

```
.. rst-class:: longtable

==== ====
 A    B
==== ====
 c    d
---- ----
 e    f
==== ====

```

```

**Comment by jfbu** [comment]
30edc3fa866c95d3f7050d2f183a7ba5cc404c47 is the first bad commit

**Comment by christiankossmann** [comment]
Thanks a lot!

**Comment by jfbu** [comment]
Thanks to your for report! Now fixed at https://github.com/sphinx-doc/sphinx/commit/14bef5d8ca204455437da3c88be14b326b5a2c98.
