### ISSUE TITLE
Exception occurred:   File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/log_cabinet.py", line 62, in __init__     super(ChangelogVisitor, self).__init__(document) TypeError: super() argument 1 must be type, not classobj

### ISSUE THREAD

**Issue by jhonlen** [sphinx-doc/sphinx#4907]
Subject: <Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/log_cabinet.py", line 62, in __init__
    super(ChangelogVisitor, self).__init__(document)
TypeError: super() argument 1 must be type, not classobj>

### Problem
- <Detail of problem>

#### Procedure to reproduce the problem
```
<sphinx-build -b html docs/ _build>
```

#### Error logs / results
```
<# Sphinx version: 1.7.4
# Python version: 2.7.13 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.10
# Last messages:
#   
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  1%] advanced_foreword
# Loaded extensions:
#   sphinx.ext.autodoc (1.7.4) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc/__init__.pyc
#   sphinx.ext.intersphinx (1.7.4) from /usr/local/lib/python2.7/dist-packages/sphinx/ext/intersphinx.pyc
#   alabaster (0.7.10) from /usr/local/lib/python2.7/dist-packages/alabaster/__init__.pyc
#   sphinxcontrib.log_cabinet (1.0.0) from /usr/local/lib/python2.7/dist-packages/sphinxcontrib/log_cabinet.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 338, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 399, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 436, in write
    self._write_serial(sorted(docnames))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 443, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment/__init__.py", line 813, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment/__init__.py", line 865, in apply_post_transforms
    self.app.emit('doctree-resolved', doctree, docname)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 444, in emit
    return self.events.emit(event, self, *args)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/log_cabinet.py", line 28, in handle_doctree_resolved
    visitor = ChangelogVisitor(doctree, app)
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/log_cabinet.py", line 62, in __init__
    super(ChangelogVisitor, self).__init__(document)
TypeError: super() argument 1 must be type, not classobj
>
```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: <Distributor ID:	Debian
Description:	Debian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch>
- Python version: 2.7.13 (CPython)
- Sphinx version:  1.7.4
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
It seems this error was raised inside `sphinxcontrib.log_cabinet`. I think this is not a bug of Sphinx. Could you report this to their project?
```
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/log_cabinet.py", line 28, in handle_doctree_resolved
    visitor = ChangelogVisitor(doctree, app)
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/log_cabinet.py", line 62, in __init__
    super(ChangelogVisitor, self).__init__(document)
```

Thanks,
