### ISSUE TITLE
Documentation build fails with TypeError

### ISSUE THREAD

**Issue by csadorf** [sphinx-doc/sphinx#5014]
### Problem

The documentation build fails with a `TypeError`.
The issue may be related to the `IPython.sphinxext.ipython_console_highlighting` extension.

#### Procedure to reproduce the problem

I am not able to reproduce the error locally, but this is the command used on the readthedocs platform:
```
python /home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
```

#### Error logs / results
```
Running Sphinx v1.7.4
loading translations [en]... done
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from https://api.mongodb.com/python/current/objects.inv...
loading intersphinx inventory from https://docs.python.org/3.6/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 26 source files that are out of date
updating environment: 26 added, 0 changed, 0 removed
reading sources... [  3%] acknowledge
reading sources... [  7%] collections
reading sources... [ 11%] configuration
reading sources... [ 15%] index
reading sources... [ 19%] indexing
reading sources... [ 23%] installation
reading sources... [ 26%] overview
reading sources... [ 30%] projects
reading sources... [ 34%] query
reading sources... [ 38%] quick_reference
reading sources... [ 42%] reference
reading sources... [ 46%] signac
reading sources... [ 50%] signac.common
reading sources... [ 53%] signac.contrib
reading sources... [ 57%] signac.core
reading sources... [ 61%] signac.db
reading sources... [ 65%] signac_101_Getting_Started

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 338, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 351, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 565, in update
    self._read_serial(docnames, self.app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 584, in _read_serial
    self.read_doc(docname, app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 659, in read_doc
    doctree = read_doc(self.app, self, self.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/sphinx/io.py", line 294, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/nbsphinx.py", line 526, in parse
    nb = nbformat.reads(inputstring, as_version=_ipynbversion)
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/nbformat/__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/nbformat/reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/nbformat/reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'StringList'

Exception occurred:
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'StringList'
The full traceback has been saved in /tmp/sphinx-err-rqdbh7tc.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
- https://readthedocs.org/projects/signac/builds/7242036/

#### Expected results

Docs should build.

### Reproducible project / your project

- https://bitbucket.org/glotzer/signac

### Environment info

On RTD with Python 3.5.

**Comment by tk0miya** [comment]
```
  File "/home/docs/checkouts/readthedocs.org/user_builds/signac/envs/latest/lib/python3.5/site-packages/nbformat/reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
```
It seems this error is raised from `nbformat` extension.

>The issue may be related to the IPython.sphinxext.ipython_console_highlighting extension.

If so, please post this to ipython project. We can't fix the error because we don't know the extension at all.

**Comment by csadorf** [comment]
You are correct, this issue appears to be directly related to the Jupyter `nbformat` extension.
