### ISSUE TITLE
AttributeError: 'module' object has no attribute 'version_info' ?

### ISSUE THREAD

**Issue by ScottBrenner** [sphinx-doc/sphinx#5023]
### Problem
- Trying to build kernel docs on a Jenkins pipeline and am seeing `AttributeError: 'module' object has no attribute 'version_info'`, additional traceback below.

#### Procedure to reproduce the problem
```
make htmldocs mandocs
```

#### Error logs / results
Jenkins output:
```
Running Sphinx v0.6.6

Exception occurred:
  File "/root/rpmbuild/BUILD/kernel-4.14.44/linux-4.14.44-1.x86_64/Documentation/conf.py", line 20, in <module>
    major, minor, patch = sphinx.version_info[:3]
AttributeError: 'module' object has no attribute 'version_info'
The full traceback has been saved in /tmp/sphinx-err-jwUDVQ.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at <http://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make[1]: *** [htmldocs] Error 1
make: *** [htmldocs] Error 2
```
Traceback a from Vagrant VM:
```
[vagrant@localhost ~]$ cat /tmp/sphinx-err-ci_cpU.log
# Sphinx version: 0.6.6
# Docutils version: 0.6 release
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/cmdline.py", line 169, in main
    warningiserror, tags)
  File "/usr/lib/python2.6/site-packages/sphinx/application.py", line 94, in __init__
    self.config = Config(confdir, CONFIG_FILENAME, confoverrides, self.tags)
  File "/usr/lib/python2.6/site-packages/sphinx/config.py", line 126, in __init__
    execfile(config['__file__'], config)
  File "/home/vagrant/rpmbuild/BUILD/kernel-4.14.41/linux-4.14.41-1.x86_64/Documentation/conf.py", line 20, in <module>
    major, minor, patch = sphinx.version_info[:3]
AttributeError: 'module' object has no attribute 'version_info'
```
Here's the `Documentation/conf.py` file - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/tree/Documentation/conf.py?h=linux-4.14.y#n20

### Environment info
- OS: CentOS release 6.7 (Final).
- Python version: 2.6.6
- Sphinx version: 0.6.6

Any ideas?

**Comment by tk0miya** [comment]
0.6.6 was released 8 years ago. It is very old and unsupported version.
Please update to latest one.
