### ISSUE TITLE
Getting bad magic number when trying to `sphinx-gallery` with `sphinx`

### ISSUE THREAD

**Issue by jakirkham** [sphinx-doc/sphinx#5073]
Subject: Getting `bad magic number` when trying to `sphinx-gallery` with `sphinx`

### Problem
- Trying to build scikit-learn's documentation, which requires `sphinx` and `sphinx-gallery`. Have used `pip install` for both (though have tried `conda` packages as well). Both seem to run into some `bad magic number` issue though.

#### Procedure to reproduce the problem

Created a `conda` environment using the `env.yaml` file below. Also built `scikit-learn` from source using a cloned copy of the [GitHub repo]( https://github.com/scikit-learn/scikit-learn ).

```yaml
name: sklearndev
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.10=py36_1
  - appnope=0.1.0=py36_0
  - asn1crypto=0.24.0=py36_0
  - atomicwrites=1.1.5=py36_0
  - attrs=18.1.0=py_0
  - babel=2.6.0=py36_0
  - backcall=0.1.0=py_0
  - blas=1.1=openblas
  - bleach=2.1.3=py_0
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36_0
  - chardet=3.0.4=py36_0
  - cryptography=2.2.1=py36_0
  - cycler=0.10.0=py36_0
  - cython=0.28.3=py36_0
  - decorator=4.3.0=py_0
  - docutils=0.14=py36_0
  - entrypoints=0.2.3=py36_1
  - freetype=2.8.1=0
  - html5lib=1.0.1=py_0
  - idna=2.6=py36_1
  - imagesize=1.0.0=py36_0
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.12.0=py36_0
  - jinja2=2.10=py36_0
  - jsonschema=2.6.0=py36_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.0.1=py36_1
  - libffi=3.2.1=3
  - libgfortran=3.0.0=0
  - libpng=1.6.34=0
  - libsodium=1.0.16=0
  - markupsafe=1.0=py36_0
  - matplotlib=2.2.2=py36_1
  - mistune=0.8.3=py36_1
  - more-itertools=4.2.0=py_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - ncurses=5.9=10
  - notebook=5.5.0=py36_0
  - numpy=1.14.3=py36_blas_openblas_200
  - openblas=0.2.20=8
  - openssl=1.0.2o=0
  - packaging=17.1=py_0
  - pandoc=2.2.1=hde52d81_0
  - pandocfilters=1.4.2=py36_0
  - parso=0.2.1=py_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pip=9.0.3=py36_0
  - pluggy=0.6.0=py_0
  - prompt_toolkit=1.0.15=py36_0
  - ptyprocess=0.5.2=py36_0
  - py=1.5.3=py_0
  - pycparser=2.18=py36_0
  - pygments=2.2.0=py36_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py36_0
  - pysocks=1.6.8=py36_1
  - pytest=3.6.0=py36_1
  - python=3.6.5=1
  - python-dateutil=2.7.3=py_0
  - pytz=2018.4=py_0
  - pyzmq=17.0.0=py36_4
  - readline=7.0=0
  - requests=2.18.4=py36_1
  - scipy=1.1.0=py36_blas_openblas_200
  - send2trash=1.5.0=py_0
  - setuptools=39.2.0=py36_0
  - simplegeneric=0.8.1=py36_0
  - six=1.11.0=py36_1
  - snowballstemmer=1.2.1=py36_0
  - sphinxcontrib-websupport=1.1.0=py36_0
  - sqlite=3.20.1=2
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - tk=8.6.7=0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36_0
  - typing=3.6.4=py36_0
  - urllib3=1.22=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_0
  - wheel=0.31.0=py36_0
  - xz=5.2.3=0
  - zeromq=4.2.5=1
  - zlib=1.2.11=h470a237_3
  - pip:
    - scikit-learn==0.20.dev0
    - sphinx==1.7.5
    - sphinx-gallery==0.2.0
```

#### Error logs / results
```
$ make html
# These two lines make the build a bit more lengthy, and the
# the embedding of images more robust
rm -rf _build/html/_images
#rm -rf _build/doctrees/
sphinx-build -b html -d _build/doctrees    . _build/html/stable
Running Sphinx v1.7.5

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/zopt/conda2/envs/sklearndev/lib/python3.6/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/zopt/conda2/envs/sklearndev/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 27, in <module>
    import sphinx_gallery
ImportError: bad magic number in 'sphinx_gallery': b'\x03\xf3\r\n'

make: *** [html] Error 2
```

#### Expected results

There is `no bad magic number` raised.

### Reproducible project / your project
- [GitHub repo fro `scikit-learn`]( https://github.com/scikit-learn/scikit-learn )

### Environment info
- OS: macOS 10.11
- Python version: 3.6.5
- Sphinx version: 1.7.5

**Comment by jakirkham** [comment]
Should add that running `python -c "import sphinx_gallery"` executes without issues.

**Comment by jakirkham** [comment]
NVM appears that `scikit-learn` adds a [`sphinxext` directory]( https://github.com/scikit-learn/scikit-learn/tree/master/doc/sphinxext ) to the path, which contained an outdated copy of `sphinx_gallery`. Cleaning it out fixed the issue.
