### ISSUE TITLE
Sphinx x Jython casuing StackOverflowError

### ISSUE THREAD

**Issue by cindyluba** [sphinx-doc/sphinx#5197]
Subject: <what happen when you do on which document project>

 Attempting to run sphinx-quickstart (or any sphinx command)

### Problem
- Running Sphinx commands on Jython

#### Procedure to reproduce the problem
```
 C:\jython2.7.0\bin>sphinx-quickstart.exe
```

#### Error logs / results
```
Traceback (most recent call last):
  File "C:\jython2.7.0\Lib\runpy.py", line 161, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\jython2.7.0\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\jython2.7.0\bin\sphinx-quickstart.exe\__main__.py", line 5, in <module>
  File "C:\jython2.7.0\Lib\site-packages\sphinx\cmd\quickstart.py", line 44, in <module>
    from sphinx.util.template import SphinxRenderer
  File "C:\jython2.7.0\Lib\site-packages\sphinx\util\template.py", line 17, in <module>
    from sphinx.jinja2glue import SphinxFileSystemLoader
  File "C:\jython2.7.0\Lib\site-packages\sphinx\jinja2glue.py", line 14, in <module>
    from typing import Any, Callable, Iterator, Tuple  # NOQA
  File "C:\jython2.7.0\Lib\site-packages\typing.py", line 1302, in <module>
    class Generic(object):
  File "C:\jython2.7.0\Lib\site-packages\typing.py", line 1035, in __new__
    if (isinstance(base, GenericMeta) and
RuntimeError: maximum recursion depth exceeded (Java StackOverflowError)
```
- <public link of unexpected result if you have>

#### Expected results
I expect the quickstart document structure to be setup.

### Reproducible project / your project
- Running sphinx-quickstart in empty directory with jython 2.7.0

### Environment info
- OS: Windows
- Python version: Jython 2.7.0
- Sphinx version: 1.7.6

**Comment by tk0miya** [comment]
I don't know about jython so much. But it seems the stacktrace you pasted is too shallow.
Is it enough memory settings? Anyway, I feel there are nothing to do from Sphinx side.

**Comment by tk0miya** [comment]
I'm closing this because this might be caused by jython's setting.
Please feel free to reopen if you are still in trouble even if setting changed.
Thanks,
