### ISSUE TITLE
Encoding Error reading sources 'UTF-8'

### ISSUE THREAD

**Issue by r4ph43l-GitHub** [sphinx-doc/sphinx#5296]
# Encoding Error reading sources 'UTF-8'

### Problem
- After fixing the *NotImplementedError: Column or row spanning cells are not implemented.* by updating to 1.6.4, I receive 

    **Encoding error:**
*'utf8' codec can't decode byte 0xe4 in position 568: invalid continuation byte
The full traceback has been saved in c:\users\r4ph43l\appdata\local\temp\sphinx-err-h5mqes.log, if you want to report the issue to the developers.
make: *** [html] Error 1*

#### Procedure to reproduce the problem
```
make html
```

#### Error logs / results
```
# Sphinx version: 1.6.4
# Python version: 2.7.15 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.9.6
# Last messages:
#   Running Sphinx v1.6.4
#   loading pickled environment...
#   not yet created
#   loading intersphinx inventory from https://docs.python.org/objects.inv...
#   intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 6 source files that are out of date
#   updating environment:
#   6 added, 0 changed, 0 removed
#   reading sources... [ 16%] Notenverwaltung
# Loaded extensions:
#   sphinx.ext.coverage (1.6.4) from c:\python27\lib\site-packages\sphinx\ext\coverage.pyc
#   sphinx.ext.viewcode (1.6.4) from c:\python27\lib\site-packages\sphinx\ext\viewcode.pyc
#   sphinx.ext.todo (1.6.4) from c:\python27\lib\site-packages\sphinx\ext\todo.pyc
#   sphinx.ext.autodoc (1.6.4) from c:\python27\lib\site-packages\sphinx\ext\autodoc.pyc
#   sphinx.ext.intersphinx (1.6.4) from c:\python27\lib\site-packages\sphinx\ext\intersphinx.pyc
#   sphinx.ext.doctest (1.6.4) from c:\python27\lib\site-packages\sphinx\ext\doctest.pyc
#   alabaster (0.7.10) from c:\python27\lib\site-packages\alabaster\__init__.pyc
#   sphinx.ext.ifconfig (1.6.4) from c:\python27\lib\site-packages\sphinx\ext\ifconfig.pyc
#   sphinx.ext.imgmath (1.6.4) from c:\python27\lib\site-packages\sphinx\ext\imgmath.pyc
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\sphinx\cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "c:\python27\lib\site-packages\sphinx\application.py", line 339, in build
    self.builder.build_update()
  File "c:\python27\lib\site-packages\sphinx\builders\__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "c:\python27\lib\site-packages\sphinx\builders\__init__.py", line 344, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "c:\python27\lib\site-packages\sphinx\environment\__init__.py", line 584, in update
    self._read_serial(docnames, self.app)
  File "c:\python27\lib\site-packages\sphinx\environment\__init__.py", line 603, in _read_serial
    self.read_doc(docname, app)
  File "c:\python27\lib\site-packages\sphinx\environment\__init__.py", line 725, in read_doc
    pub.publish()
  File "c:\python27\lib\site-packages\docutils\core.py", line 217, in publish
    self.settings)
  File "c:\python27\lib\site-packages\sphinx\io.py", line 74, in read
    self.parse()
  File "c:\python27\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 171, in run
    input_source=document['source'])
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\python27\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "c:\python27\lib\site-packages\docutils\parsers\rst\states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "c:\python27\lib\site-packages\sphinx\ext\autodoc.py", line 1834, in run
    documenter.generate(more_content=self.content)
  File "c:\python27\lib\site-packages\sphinx\ext\autodoc.py", line 1082, in generate
    if not self.import_object():
  File "c:\python27\lib\site-packages\sphinx\ext\autodoc.py", line 687, in import_object
    errmsg = errmsg.decode('utf-8')  # type: ignore
  File "c:\python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 568: invalid continuation byte

```

#### Expected results
As this is character is not inside the rst files but only in png-Images, I would not expect sphinx to fail here...

```
C:\Users\r4ph43l\Repositories\_<ProjectName>_\Documentation>grep -ri ä source/*
Binary file source/_images/LoginScreen_Layout.png matches
Binary file source/_images/_dev_LoginScreen_Layout.png matches
Binary file source/_images/_user_LoginScreen_Layout.png matches
```

### Reproducible project / your project
- N/A

### Environment info
- OS: Windows 10 Pro x64
- Python version: 2.7.15
- Sphinx version: 1.6.4

**Comment by tk0miya** [comment]
It seems this error was raised inside autodoc module. Could you check where autodoc is used?
```
  File "c:\python27\lib\site-packages\sphinx\ext\autodoc.py", line 687, in import_object
    errmsg = errmsg.decode('utf-8')  # type: ignore
```

I'd like to know how to reproduce this error. So please let me know about your documentation in detail.

**Comment by r4ph43l-GitHub** [comment]
Will do in some hours.

**Comment by r4ph43l-GitHub** [comment]
Unfortunately I cannot tell you where the error came from... Running 1.7.6 and 1.7.7 this issue is no longer reproducable and can be marked fixed in 1.7.6

**Comment by tk0miya** [comment]
Okay, I'm closing this because unreproducible. But please reopen this again if you get same error in future.
Thanks,


Note: The error was raised on decoding error message. It means the original error message contains non-ASCII characters. So it would be nice what message was raised originally to fix it (if reproduced again).
```
  File "c:\python27\lib\site-packages\sphinx\ext\autodoc.py", line 687, in import_object
    errmsg = errmsg.decode('utf-8')  # type: ignore
  File "c:\python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 568: invalid continuation byte
```

**Comment by danielkanzel** [comment]
OK I get it. How you can see version 1.8.3.
![image](https://user-images.githubusercontent.com/26162864/51611463-5830df80-1f30-11e9-82c2-63d3e2a806bd.png)

Here sources:
![image](https://user-images.githubusercontent.com/26162864/51611498-6da60980-1f30-11e9-9510-7e4ff2748e14.png)

**Comment by danielkanzel** [comment]
Logs

```
# Sphinx version: 1.8.3
# Python version: 3.6.7 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   building [html]: targets for 7 source files that are out of date
#   
#   updating environment:
#   
#   7 added, 0 changed, 0 removed
#   
#   reading sources... [ 14%] cases
#   
#   reading sources... [ 28%] codes
#   
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.3) from /home/daniel/.local/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.8) from /usr/lib/python3/dist-packages/alabaster/__init__.py
#   sphinx.ext.githubpages (1.8.3) from /home/daniel/.local/lib/python3.6/site-packages/sphinx/ext/githubpages.py
#   sphinx_inplat (unknown version) from /home/daniel/.local/lib/python3.6/site-packages/sphinx_inplat/__init__.py
Traceback (most recent call last):
  File "/home/daniel/.local/lib/python3.6/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/daniel/.local/lib/python3.6/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/daniel/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/daniel/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/daniel/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/daniel/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/daniel/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/daniel/.local/lib/python3.6/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/daniel/.local/lib/python3.6/site-packages/sphinx/parsers.py", line 88, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/directives/tables.py", line 242, in run
    csv_data, source = self.get_csv_data()
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/parsers/rst/directives/tables.py", line 314, in get_csv_data
    csv_data = csv_file.read().splitlines()
  File "/home/daniel/.local/lib/python3.6/site-packages/docutils/io.py", line 274, in read
    data = self.source.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/usr/lib/python3.6/encodings/utf_8_sig.py", line 69, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 0: invalid continuation byte
```

**Comment by danielkanzel** [comment]
Problem in csv-tables.

**Comment by danielkanzel** [comment]
OK. I solve this. Problem was in tables. I save them not in UTF-8. Maybe it be useful for someone.
