### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by GSebastian-Adil** [sphinx-doc/sphinx#5389]
Subject: <what happen when you do on which document project>

### Problem
******@******:~/projects/Sphinx$ sphinx-build -b pdf source build/pdf
Running Sphinx v1.7.8

Exception occurred:
  File "/home/******/.local/lib/python3.6/site-packages/sphinx/registry.py", line 315, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/******/.local/lib/python3.6/site-packages/rst2pdf/pdfbuilder.py", line 129
    except Exception, e:
                    ^
SyntaxError: invalid syntax
The full traceback has been saved in /tmp/sphinx-err-_9n6c5ti.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

#### Procedure to reproduce the problem
```
```

#### Error logs / results
```
----------sphinx-err-_9n6c5ti.log----------
# Sphinx version: 1.7.8
# Python version: 3.6.5 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/******/.local/lib/python3.6/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/******/.local/lib/python3.6/site-packages/sphinx/application.py", line 191, in __init__
    self.setup_extension(extension)
  File "/home/******/.local/lib/python3.6/site-packages/sphinx/application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/******/.local/lib/python3.6/site-packages/sphinx/registry.py", line 315, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/******/.local/lib/python3.6/site-packages/rst2pdf/pdfbuilder.py", line 129
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```
- <public link of unexpected result if you have>

#### Expected results
produce a "PDF file" directly from "index.rst" using "rst2pdf: sphinx-build -b pdf source build/pdf"

### Reproducible project / your project
No project, Just experimentation

### Environment info
- OS: <Linux: Kubuntu 18.04 LTS>
- Python version: 3.6.5
- Sphinx version: 1.7.8
- Extra tools: rst2pdf

**Comment by tk0miya** [comment]
Unfortunately, rst2pdf does not support python 3.x.
Please report this to their project.
Thanks,

**Comment by GSebastian-Adil** [comment]
Thanks, Ok it is done
