### ISSUE TITLE
unqualified exec is not allowed in function 'run'

### ISSUE THREAD

**Issue by petr-balogh** [sphinx-doc/sphinx#5423]
Subject:  unqualified exec is not allowed in function 'run'

### Problem
- when running in tox build of documentation:

`/root/workspace/gate-jenkins-jobs/automation/rhevm-jenkins-jobs/.tox/docs/bin/sphinx-build -b linkcheck doc /root/workspace/gate-jenkins-jobs/automation/rhevm-jenkins-jobs/doc/html 
`
we are getting exception:
```
Exception occurred:
  File "/root/workspace/gate-jenkins-jobs/automation/rhevm-jenkins-jobs/.tox/docs/lib/python2.7/site-packages/sphinx/highlighting.py", line 26, in <module>
```

When I switch back to 1.7.9, it's working well.

Tox is using virtualenv.

#### Procedure to reproduce the problem
```
<Paste your command-line here which cause the problem>
```

#### Error logs / results
```
# Sphinx version: 1.8.0
# Python version: 2.7.5 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/root/workspace/gate-jenkins-jobs/automation/rhevm-jenkins-jobs/.tox/docs/lib/python2.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/root/workspace/gate-jenkins-jobs/automation/rhevm-jenkins-jobs/.tox/docs/lib/python2.7/site-packages/sphinx/application.py", line 224, in __init__
    self.setup_extension(extension)
  File "/root/workspace/gate-jenkins-jobs/automation/rhevm-jenkins-jobs/.tox/docs/lib/python2.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/root/workspace/gate-jenkins-jobs/automation/rhevm-jenkins-jobs/.tox/docs/lib/python2.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/root/workspace/gate-jenkins-jobs/automation/rhevm-jenkins-jobs/.tox/docs/lib/python2.7/site-packages/sphinx/builders/applehelp.py", line 20, in <module>
    from sphinx.builders.html import StandaloneHTMLBuilder
  File "/root/workspace/gate-jenkins-jobs/automation/rhevm-jenkins-jobs/.tox/docs/lib/python2.7/site-packages/sphinx/builders/html.py", line 40, in <module>
    from sphinx.highlighting import PygmentsBridge
  File "/root/workspace/gate-jenkins-jobs/automation/rhevm-jenkins-jobs/.tox/docs/lib/python2.7/site-packages/sphinx/highlighting.py", line 26, in <module>
    from sphinx.ext import doctest
SyntaxError: unqualified exec is not allowed in function 'run' it contains a nested function with free variables (doctest.py, line 97)

```

#### Expected results
Build doc without error

### Environment info
- OS: Rhel 7.5
- Python version:  2.7.5
- Sphinx version:1.8.0

**Comment by tk0miya** [comment]
Sorry for inconvenience. I'm working for this in #5417.
So I'm closing this because of dup.
