### ISSUE TITLE
TypeError in docutils/writers/_html_base.py for autodoc'd class data member

### ISSUE THREAD

**Issue by terrisgit** [sphinx-doc/sphinx#5426]
This bug does not occur with previous versions of Sphinx.

A class's data member must have a specifically formatted docstring.

The first part of the docstring (the main text) must match the regular expression /:\s*$/ (ends with a colon). After the colon, any amount of whitespace may be present. The text thereafter is an enumerated list (both - and * work) of any number of items. The first list item matches the expression /:/ (contains a colon).

# Environment

- OS: OSX 10.13.6
- Python version: 3.7 (installed via homebrew). Also happens in 3.6.4.
- Sphinx version: 1.8.0

# Test Case

Run autodoc on the following and generate HTML:

```python
class SomeClass:
  some_data = 0
  """data member description:

  - a: b
  """
```

# Actual Result

Sphinx crashes with the following output:

```writing output...                                                                                                                                          
Exception occurred:
  File ".../site-packages/docutils/writers/_html_base.py", line 399, in set_class_on_child
    child['classes'].append(class_)
TypeError: string indices must be integers
```

# Error logs / results

```
# Sphinx version: 1.8.0
# Python version: 3.7.0 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   writing output... [ 59%] someclass
#   
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.0) from /.venv/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.11) from /.venv/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.8.0) from /.venv/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.napoleon (1.8.0) from /.venv/lib/python3.7/site-packages/sphinx/ext/napoleon/__init__.py
Traceback (most recent call last):
  File "/.venv/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/.venv/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/.venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/.venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 412, in build
    self.write(docnames, list(updated_docnames), method)
  File "/.venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 593, in write
    self._write_serial(sorted(docnames))
  File "/.venv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 604, in _write_serial
    self.write_doc(docname, doctree)
  File "/.venv/lib/python3.7/site-packages/sphinx/builders/html.py", line 730, in write_doc
    self.docwriter.write(doctree, destination)
  File "/.venv/lib/python3.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/.venv/lib/python3.7/site-packages/sphinx/writers/html.py", line 58, in translate
    self.document.walkabout(visitor)
  File "/.venv/lib/python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/.venv/lib/python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/.venv/lib/python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 4 more times]
  File "/.venv/lib/python3.7/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/.venv/lib/python3.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/.venv/lib/python3.7/site-packages/docutils/writers/html4css1/__init__.py", line 402, in visit_field_body
    self.set_class_on_child(node, 'first', 0)
  File "/.venv/lib/python3.7/site-packages/docutils/writers/_html_base.py", line 399, in set_class_on_child
    child['classes'].append(class_)
TypeError: string indices must be integers
```

**Comment by tk0miya** [comment]
It seems this bug is related with napoleon extension.
@RobRuana could you check this please?

**Comment by terrisgit** [comment]
Related to #4869 ?

**Comment by terrisgit** [comment]
Yes, I disabled the Napoleon extension and the problem went away.

**Comment by tk0miya** [comment]
I confirmed the napoleon module expands the docstring to following:
```

b

:type: data member description
:type: - a
```

I don't know this is expected result. But it seems it is not broken.

And I reproduced the error without napoleon module with following docstring:
``` 
class SomeClass:
    some_data = 0
    """:type: - a"""
```

From now on, I'm starting to investigate why Sphinx crashes with such docstring.

**Comment by tk0miya** [comment]
I made a fix #5468 for py-domain. I think this will resolve the crash. But we need to know that napoleon module works as expected or not.
So I'll keep this opened until @RobRuana checks this issue.

**Comment by RobRuana** [comment]
@tk0miya napoleon was behaving badly. This pull request fixes this issue: https://github.com/sphinx-doc/sphinx/pull/5470

**Comment by RobRuana** [comment]
Haha, whoops! I accidentally closed this issue by referencing it in the downstream project! Re-opening until https://github.com/sphinx-doc/sphinx/pull/5470 is merged!
