### ISSUE TITLE
SyntaxError when using sphinx 1.8.0

### ISSUE THREAD

**Issue by samkpo** [sphinx-doc/sphinx#5458]
Hi,
When I'm running Sphinx in a project I'm working on I get the following error:

```
# Loaded extensions:
Traceback (most recent call last):
  File "USER/build/venv/local/lib/python2.7/site-packages/sphinx/setup_command.py", line 192, in run
    warningiserror=self.warning_is_error)
  File "USER/build/venv/local/lib/python2.7/site-packages/sphinx/application.py", line 224, in __init__
    self.setup_extension(extension)
  File "USER/build/venv/local/lib/python2.7/site-packages/sphinx/application.py", line 449, in setup_extension 
    self.registry.load_extension(self, extname)
  File "USER/build/venv/local/lib/python2.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "USER/build/venv/local/lib/python2.7/site-packages/sphinx/builders/applehelp.py", line 20, in <module> 
    from sphinx.builders.html import StandaloneHTMLBuilder
  File "USER/build/venv/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 40, in <module> 
    from sphinx.highlighting import PygmentsBridge
  File "USER/build/venv/local/lib/python2.7/site-packages/sphinx/highlighting.py", line 26, in <module> 
    from sphinx.ext import doctest
SyntaxError: unqualified exec is not allowed in function 'run' it contains a nested function with free variables (doctest.py, line 97)
```
- Sphinx version: 1.8.0
- Python version: 2.7.6 (CPython)
- Docutils version: 0.14 
- Jinja2 version: 2.10

It doesn't happen with version 1.7.9

**Comment by tk0miya** [comment]
Sorry for inconvenience. This is same as #5417, and fixed by #5443.
Thanks,
