### ISSUE TITLE
No such file or directory: ...fontawesome-webfont.svg

### ISSUE THREAD

**Issue by jmayer** [sphinx-doc/sphinx#5466]
While building the documentation of acitoolkit, I get an error. sphinx asked me to report it.
```
=======================================================================
[root@fsdelbea0001 docs]# make html

sphinx-build -b html -d ../docsbuild/doctrees   source ../docsbuild/html
Running Sphinx v1.1.3
loading pickled environment... done
building [html]: targets for 47 source files that are out of date
updating environment: 0 added, 7 changed, 0 removed
reading sources... [100%] objectmodel                                                                                       
<string>:docstring of acitoolkit.acitoolkit.EPG.add_static_leaf_binding:8: WARNING: Field list ends without a blank line; unexpected unindent.
<string>:docstring of acitoolkit.acitoolkit.Subnet.set_scope:4: WARNING: Field list ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] visualizations                                                                                     
writing additional files... genindex py-modindex search
copying images... [100%] eventfeeds_config.png                                                                              
copying static files... 
Exception occurred:
  File "/usr/lib64/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.svg', '/root/work/acitoolkit/docsbuild/html/_static/fonts/fontawesome-webfont.svg', "[Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.svg'"), ('/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff', '/root/work/acitoolkit/docsbuild/html/_static/fonts/fontawesome-webfont.woff', "[Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff'")]
The full traceback has been saved in /tmp/sphinx-err-MzwZVk.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at <http://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1
[root@fsdelbea0001 docs]# 
```
```

=======================================================================
/tmp/sphinx-err-MzwZVk.log

# Sphinx version: 1.1.3
# Python version: 2.7.5
# Docutils version: 0.11 repository
# Jinja2 version: 2.7.2
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 255, in build
    self.finish()
  File "/usr/lib/python2.7/site-packages/sphinx/builders/html.py", line 462, in finish
    self.copy_static_files()
  File "/usr/lib/python2.7/site-packages/sphinx/builders/html.py", line 561, in copy_static_files
    self, ctx)
  File "/usr/lib/python2.7/site-packages/sphinx/util/__init__.py", line 158, in copy_static_entry
    exclude_matchers=exclude_matchers)
  File "/usr/lib/python2.7/site-packages/sphinx/util/__init__.py", line 163, in copy_static_entry
    shutil.copytree(source, target)
  File "/usr/lib64/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.svg', '/root/work/acitoolkit/docsbuild/html/_static/fonts/fontawesome-webfont.svg', "[Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.svg'"), ('/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff', '/root/work/acitoolkit/docsbuild/html/_static/fonts/fontawesome-webfont.woff', "[Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff'")]
```
```
=======================================================================
[root@fsdelbea0001 acitoolkit]# locate fontawesome

/etc/fonts/conf.d/60-fontawesome.conf
/root/work/acitoolkit/docsbuild/html/_static/fonts/fontawesome-webfont.eot
/root/work/acitoolkit/docsbuild/html/_static/fonts/fontawesome-webfont.ttf
/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.eot
/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.svg
/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.ttf
/usr/lib/python2.7/site-packages/sphinx_rtd_theme/static/fonts/fontawesome-webfont.woff
/usr/share/cockpit/base1/fonts/fontawesome.woff
/usr/share/doc/fontawesome-fonts-4.1.0
/usr/share/doc/fontawesome-fonts-4.1.0/README-Trademarks.txt
/usr/share/fontconfig/conf.avail/60-fontawesome.conf
/usr/share/fonts/fontawesome
/usr/share/fonts/fontawesome/FontAwesome.otf
/usr/share/fonts/fontawesome/fontawesome-webfont.ttf
[root@fsdelbea0001 acitoolkit]# 
```
```
=======================================================================
[root@fsdelbea0001 ~]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Scientific
Description:    Scientific Linux release 7.5 (Nitrogen)
Release:        7.5
Codename:       Nitrogen
[root@fsdelbea0001 ~]# 
=======================================================================
```

**Comment by tk0miya** [comment]
Thank you for reporting. But Sphinx-1.1.3 is not supported now. Could you upgrade to newest Sphinx?
Thanks,

**Comment by tk0miya** [comment]
Note: At present, we use `copy_asset()` and `os.walk()` to copy asset files instead of `copytree()`. So this error would not be happened.
