### ISSUE TITLE
AttributeError: module 'doctest' has no attribute 'DocTestParser'

### ISSUE THREAD

**Issue by yong2dayz** [sphinx-doc/sphinx#5473]
Subject: <what happen when you do on which document project>
I am trying to run sphinx-build -b .\source .\build
and get this errror.
I am running this behind a virtual environment and the error popsup saying
```
Exception occurred:
  File "...\Lib\site-packages\sphinx\ext\doctest.py", line 187, in <module>
    parser = doctest.DocTestParser()
AttributeError: module 'doctest' has no attribute 'DocTestParser'
The full traceback has been saved in ...\AppData\Local\Temp\sphinx-err-d8nvpyjw.log, if you want to report
the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
I can't run sphinx-build on this repository.

  Thanks,

### Environment info
- OS: <Win>
- Python version: Python 3.6.6 :: Anaconda, Inc.
- Sphinx version:1.7.9 or even 1.6.6

**Comment by yong2dayz** [comment]
The Error log message is as below:
```
# Sphinx version: 1.7.9
# Python version: 3.6.4 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\sphinx\cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "c:\anaconda3\lib\site-packages\sphinx\application.py", line 187, in __init__
    self.setup_extension(extension)
  File "c:\anaconda3\lib\site-packages\sphinx\application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "c:\anaconda3\lib\site-packages\sphinx\registry.py", line 315, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "c:\anaconda3\lib\site-packages\sphinx\builders\applehelp.py", line 20, in <module>
    from sphinx.builders.html import StandaloneHTMLBuilder
  File "c:\anaconda3\lib\site-packages\sphinx\builders\html.py", line 39, in <module>
    from sphinx.highlighting import PygmentsBridge
  File "c:\anaconda3\lib\site-packages\sphinx\highlighting.py", line 23, in <module>
    from sphinx.ext import doctest
  File "c:\anaconda3\lib\site-packages\sphinx\ext\doctest.py", line 15, in <module>
    import doctest
  File "C:\git\gitlab\sphinxpages\Lib\site-packages\sphinx\ext\doctest.py", line 187, in <module>
    parser = doctest.DocTestParser()
AttributeError: module 'doctest' has no attribute 'DocTestParser'
```

**Comment by tk0miya** [comment]
Strange. `doctest.DocTestParser` is a python's official class. So I think the AttributeError is strange.
https://docs.python.org/3/library/doctest.html#doctest.DocTestParser

Did you override `doctest` module in your project? Could you check what module is named as  `doctest` in your project please?

**Comment by tk0miya** [comment]
I'm closing this now.
Please reopen if you're still in trouble.
Thanks,
