### ISSUE TITLE
Configuration error when importing project module

### ISSUE THREAD

**Issue by kimyen** [sphinx-doc/sphinx#5499]
Subject: Configuration error when importing project module

### Problem
- My package has the following hierarchy:
```
synapsePythonClient
    docs
        conf.py
    synapseclient
    setup.py
```
 
#### Procedure to reproduce the problem
```
cd synapsePythonClient
python3 setup.py install
# verify the the synapseclient is installed in python3
cd docs
make html
```

#### Error logs / results
```
sphinx-build -b html -d build/doctrees   . build/html
Running Sphinx v1.7.9

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 16, in <module>
    import synapseclient
ModuleNotFoundError: No module named 'synapseclient'

make: *** [html] Error 2
```

#### Expected results
- successfully build the html files

### Reproducible project / your project
- https://github.com/Sage-Bionetworks/synapsePythonClient/tree/v1.9.0-rc

### Environment info
- OS: Mac OS X El Capitan (rented from MacStadium)
- Python version: 3.6
- Sphinx version: 1.7.9

**Comment by kimyen** [comment]
It turns out the my python3 was installed differently than how sphinx was installed. I installed sphinx using brew. Brew installed it a different location than where my python3 was. The fix was to re-install python3 using brew.
