### ISSUE TITLE
sphinx_build: build html with docfx from dotnet

### ISSUE THREAD

**Issue by TheBinaryLoop** [sphinx-doc/sphinx#5573]
### Problem
_make html_ returns error after _updating environment_

#### Procedure to reproduce the problem
```
make html
```

#### Error logs / results
```
Running Sphinx v1.8.1
/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/application.py:402: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  RemovedInSphinx20Warning)
[AutoAPI] Loading Data
[AutoAPI] Reading files... [100%] /folder/devspace/csharp/binarytools/BinaryTools/BinaryTools.csproj
[AutoAPI] Ignoring _api/toc.yml
[AutoAPI] Reading files... [100%] _api/BinaryTools.Security.Credentials.PersistanceType.yml
[AutoAPI] Mapping Data
[AutoAPI] Rendering Data
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: 31 added, 0 changed, 0 removed

Exception occurred:
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/util/docfields.py", line 93, in make_xrefs
    return [self.make_xref(rolename, domain, target, innernode, contnode, env)]
TypeError: make_xref() takes from 4 to 6 positional arguments but 7 were given
The full traceback has been saved in /tmp/sphinx-err-41yfuk83.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:19: recipe for target 'html' failed
make: *** [html] Error 2
```

output of /tmp/sphinx-err-41yfuk83.log
```
# Sphinx version: 1.8.1
# Python version: 3.6.6 (CPython)
# Docutils version: 0.14
# Jinja2 version: 2.10
# Last messages:
#   updating environment:
#
#   31 added, 0 changed, 0 removed
#
#   reading sources... [  3%] BinaryTools
#
#   reading sources... [  6%] BinaryTools.ConsoleEx
#
#   reading sources... [  9%] autoapi/BinaryTools/ConsoleEx/index
#
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.1) from /folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.12) from /folder/devspace/readthedocs/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.todo (1.8.1) from /folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/ext/todo.py
#   sphinx.ext.autodoc (1.8.1) from /folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (1.8.1) from /folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/ext/autosummary/__init__.py
#   autoapi.extension (unknown version) from /folder/devspace/readthedocs/lib/python3.6/site-packages/autoapi/extension.py
#   sphinxcontrib.dotnetdomain (unknown version) from /folder/devspace/readthedocs/lib/python3.6/site-packages/sphinxcontrib/dotnetdomain.py
Traceback (most recent call last):
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/parsers.py", line 88, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/domains/__init__.py", line 239, in run
    return BaseDirective.run(self)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinxcontrib/dotnetdomain.py", line 292, in run
    nodes = super(DotNetObjectNested, self).run()
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/directives/__init__.py", line 180, in run
    self.state.nested_parse(self.content, self.content_offset, contentnode)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/domains/__init__.py", line 239, in run
    return BaseDirective.run(self)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/directives/__init__.py", line 181, in run
    DocFieldTransformer(self).transform_all(contentnode)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/util/docfields.py", line 269, in transform_all
    self.transform(child)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/util/docfields.py", line 383, in transform
    content, env=env)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/util/docfields.py", line 229, in make_field
    bodynode = handle_item(fieldarg, content)
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/util/docfields.py", line 208, in handle_item
    addnodes.literal_strong, env=env))
  File "/folder/devspace/readthedocs/lib/python3.6/site-packages/sphinx/util/docfields.py", line 92, in make_xrefs
    return [self.make_xref(rolename, domain, target, innernode, contnode, env)]
TypeError: make_xref() takes from 4 to 6 positional arguments but 7 were given
```

#### Expected results
html files

### Reproducible project / your project
https://gitlab.binarypanther.com/TheBinaryLoop/binarytools

### Environment info
- OS: Ubuntu 18.04
- Python version: 3.6.6 (CPython)
- Sphinx version: 1.8.1
- docfx

**Comment by tk0miya** [comment]
>Reproducible project / your project
>https://gitlab.binarypanther.com/TheBinaryLoop/binarytools

How do I reproduce the error? It seems there are no document in the repository.

**Comment by tk0miya** [comment]
I guess this might be a bug of dotnetdomain. Have you already reported this to the project?

```
#   sphinxcontrib.dotnetdomain (unknown version) from /folder/devspace/readthedocs/lib/python3.6/site-packages/sphinxcontrib/dotnetdomain.py
```

**Comment by TheBinaryLoop** [comment]
@tk0miya I got this error while trying to create the documentation from the csproject file. If there are missing files please let me know.

**Comment by TheBinaryLoop** [comment]
@tk0miya I didn't because it looks like the line that threw the error is in the sphinx code.

**Comment by tk0miya** [comment]
Sorry, I'm not good at C# project. So I can't find the way to build your document. It seems there are no `conf.py` and `.rst` files. I can't imagine how to build document from your repository.
Please, Please let me know the procedure of the error from `git clone`.

Thanks,

**Comment by tk0miya** [comment]
Any updates? if none, I'll close this.

**Comment by tk0miya** [comment]
Closing now.
