### ISSUE TITLE
Convert html to docset failed

### ISSUE THREAD

**Issue by datacruiser** [sphinx-doc/sphinx#5634]
Subject: Build docset from html failed with doc2dash

### Problem
- I try to covert the html to docsets which can be imported Dash via the instructions released in [https://github.com/Kapeli/Dash-User-Contributions/blob/master/docsets/Scikit](https://github.com/Kapeli/Dash-User-Contributions/blob/master/docsets/Scikit), unfortunately, I'm failed.

#### Procedure to reproduce the problem
```
https://github.com/Kapeli/Dash-User-Contributions/blob/master/docsets/Scikit/build.sh
```

#### Error logs / results
The final command line output is as follows:
```
-------------------------------------------------------------------------------
The full traceback has been saved in /var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sphinx-err-2dtjuzin.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
+ rm -rf /var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG
```
and the detail contents of the ```sphinx-err-2dtjuzin.log```file is showed bellow:
```
# Sphinx version: 1.6.2
# Python version: 3.6.6 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   dumping search index in English (code: en) ...
#   
#   done
#   
#   dumping object inventory...
#   
#   done
#   
#   build succeeded, 557 warnings.
#   
# Loaded extensions:
#   alabaster (0.7.12) from /var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.6.2) from /var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sphinx/ext/autodoc.py
#   sphinx.ext.autosummary (1.6.2) from /var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sphinx/ext/autosummary/__init__.py
#   numpydoc (0.8.0) from /var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/numpydoc/__init__.py
#   sphinx.ext.linkcode (1.6.2) from /var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sphinx/ext/linkcode.py
#   sphinx.ext.doctest (1.6.2) from /var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.intersphinx (1.6.2) from /var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx_gallery.gen_gallery (0.2.0) from /var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sphinx_gallery/gen_gallery.py
#   sphinx_issues (unknown version) from /private/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/scikit-learn/doc/sphinxext/sphinx_issues.py
#   sphinx.ext.mathjax (1.6.2) from /var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sphinx/ext/mathjax.py
Traceback (most recent call last):
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sphinx/application.py", line 357, in build
    self.emit('build-finished', None)
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sphinx/application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sphinx_gallery/gen_gallery.py", line 313, in sumarize_failing_examples
    "\n" + "-" * 79)
ValueError: Here is a summary of the problems encountered when running the examples

[31;01mUnexpected failing examples:[39;49;00m
/private/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/scikit-learn/examples/gaussian_process/plot_gpr_co2.py failed leaving traceback:
Traceback (most recent call last):
  File "/private/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/scikit-learn/examples/gaussian_process/plot_gpr_co2.py", line 108, in <module>
    X, y = load_mauna_loa_atmospheric_co2()
  File "/private/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/scikit-learn/examples/gaussian_process/plot_gpr_co2.py", line 83, in load_mauna_loa_atmospheric_co2
    ml_data = fetch_openml(data_id=41187)
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sklearn/datasets/openml.py", line 490, in fetch_openml
    features_list = _get_data_features(data_id, data_home)
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sklearn/datasets/openml.py", line 305, in _get_data_features
    data_home)
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sklearn/datasets/openml.py", line 133, in _get_json_content_from_openml_api
    json_data = json.loads(response.read().decode("utf-8"))
  File "/Users/datacruiser/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/datacruiser/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/datacruiser/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


/private/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/scikit-learn/examples/linear_model/plot_sparse_logistic_regression_mnist.py failed leaving traceback:
Traceback (most recent call last):
  File "/private/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/scikit-learn/examples/linear_model/plot_sparse_logistic_regression_mnist.py", line 39, in <module>
    X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sklearn/datasets/openml.py", line 490, in fetch_openml
    features_list = _get_data_features(data_id, data_home)
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sklearn/datasets/openml.py", line 305, in _get_data_features
    data_home)
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sklearn/datasets/openml.py", line 133, in _get_json_content_from_openml_api
    json_data = json.loads(response.read().decode("utf-8"))
  File "/Users/datacruiser/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/datacruiser/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/datacruiser/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


/private/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/scikit-learn/examples/multioutput/plot_classifier_chain_yeast.py failed leaving traceback:
Traceback (most recent call last):
  File "/private/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/scikit-learn/examples/multioutput/plot_classifier_chain_yeast.py", line 50, in <module>
    X, Y = fetch_openml('yeast', version=4, return_X_y=True)
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sklearn/datasets/openml.py", line 480, in fetch_openml
    data_description = _get_data_description_by_id(data_id, data_home)
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sklearn/datasets/openml.py", line 295, in _get_data_description_by_id
    data_home)
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sklearn/datasets/openml.py", line 133, in _get_json_content_from_openml_api
    json_data = json.loads(response.read().decode("utf-8"))
  File "/Users/datacruiser/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/datacruiser/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/datacruiser/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


-------------------------------------------------------------------------------

```

#### Expected results
I'd like to figure out what's the matter and build the docset of scikit-learn finally.

### Environment info
- OS: Mac 10.14
- Python version: 3.6.6(CPython)
- Sphinx version: 1.6.2
- Docutils version: 0.14
- Jinja2 version: 2.10

**Comment by tk0miya** [comment]
It seems sphinx_gallery extension raises this error. And it says some examples gets error. I don't know why they gets error. Could you ask to their project please?

```
  File "/var/folders/t0/csmkjx2s3cn0dgsd2t4zmf_w0000gn/T/sklearn2dash.g4z0maAG/venv/lib/python3.6/site-packages/sphinx_gallery/gen_gallery.py", line 313, in sumarize_failing_examples
    "\n" + "-" * 79)
ValueError: Here is a summary of the problems encountered when running the examples
```

**Comment by tk0miya** [comment]
I'm closing this now because this would not be a bug of Sphinx.
Thanks,
