### ISSUE TITLE
RuntimeError: Code input with no code at ...

### ISSUE THREAD

**Issue by spencerahill** [sphinx-doc/sphinx#5646]
Subject: confusing RuntimeError when I try to build our docs on my local machine

### Problem
- For the aospy package
- RuntimeError that I don't understand and that doesn't occur in our builds on ReadTheDocs
- I don't see anything wrong with the [code block it refers to in our examples.rst](https://github.com/spencerahill/aospy/blob/master/docs/examples.rst#L352)

#### Procedure to reproduce the problem

From `aospy/docs`:
```
make clean
make dummy
```

#### Error logs / results
```
cat /var/folders/_s/qf0zz57x5xzgbgn4dxbg7k_c0000gn/T/sphinx-err-8ar2qd2o.log
# Sphinx version: 1.8.2
# Python version: 3.7.0 (CPython)
# Docutils version: 0.14
# Jinja2 version: 2.10
# Last messages:
#   building [dummy]: targets for 7 source files that are out of date
#
#   updating environment:
#
#   7 added, 0 changed, 0 removed
#
#   reading sources... [ 14%] api
#
#   reading sources... [ 28%] examples
#
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.2) from /Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.12) from /Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.8.2) from /Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.doctest (1.8.2) from /Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.extlinks (1.8.2) from /Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/extlinks.py
#   sphinx.ext.intersphinx (1.8.2) from /Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.todo (1.8.2) from /Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (1.8.2) from /Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.ifconfig (1.8.2) from /Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.viewcode (1.8.2) from /Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.autosummary (1.8.2) from /Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/ext/autosummary/__init__.py
#   numpydoc (0.8.0) from /Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/numpydoc/__init__.py
#   IPython.sphinxext.ipython_console_highlighting (unknown version) from /Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/IPython/sphinxext/ipython_console_highlighting.py
#   IPython.sphinxext.ipython_directive (unknown version) from /Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/IPython/sphinxext/ipython_directive.py
Traceback (most recent call last):
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/sphinx/parsers.py", line 88, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2988, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/Users/shill/Dropbox/miniconda3/envs/py37/lib/python3.7/site-packages/IPython/sphinxext/ipython_directive.py", line 1018, in run
    raise RuntimeError(message)
RuntimeError: Code input with no code at /Users/shill/Dropbox/py/aospy/docs/examples.rst, line 352
```

#### Expected results
- Docs build successfully, as they do on RTD, e.g. here: https://readthedocs.org/projects/aospy/builds/8113594/

### Reproducible project / your project
- https://github.com/spencerahill/aospy

### Environment info
- OS: macOS Sierra 10.12.6
- Python version: 3.7.1
- Sphinx version: 1.8.2

**Comment by spencerahill** [comment]
Update: this does not occur with sphinx-build 1.5.1:

```
sphinx-build --version
Sphinx (sphinx-build) 1.5.1
[docs-fixes]shill@vpn-248-127:~/Dropbox/py/aospy/doc$ make clean
rm -rf _build/*
[docs-fixes]shill@vpn-248-127:~/Dropbox/py/aospy/doc$ make dummy
sphinx-build -b dummy -d _build/doctrees   . _build/dummy
Running Sphinx v1.5.1
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
building [dummy]: targets for 7 source files that are out of date
updating environment: 7 added, 0 changed, 0 removed
reading sources... [100%] whats-new
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] whats-new
build succeeded.
```

**Comment by jfbu** [comment]
The code-block

```
.. ipython::

   precip_conv_frac = Var(
       name='precip_conv_frac',
       def_time=True,
       variables=(precip_convective, precip_total),
       func=lambda conv, total: conv / total,
   )

```

at https://github.com/spencerahill/aospy/blob/master/doc/examples.rst#L352 the sole one lacking an argument (which is ``python`` for all the other ones).

**Comment by spencerahill** [comment]
Oy, yes that was the problem.  Apparently that was allowed with earlier versions of sphinx but not anymore?

Anyways, changing it to `ipython:: python` fixes the problem.  Feel free to close this.  Thanks very much.

**Comment by jfbu** [comment]
I tried a minimal example with Sphinx 1.5.1 (adding ``:okexcept:`` option to the IPython directive) and got the same:

```
$ make clean html
Removing everything under '_build'...
Running Sphinx v1.5.1
making output directory...
Sphinx version: 1.5.1
Python version: 3.6.7 (CPython)
IPython version: 7.1.1
Docutils version: 0.14 
Jinja2 version: 2.10

loading translations [en]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                 
Exception occurred:
  File "/opt/miniconda3/lib/python3.6/site-packages/IPython/sphinxext/ipython_directive.py", line 1018, in run
    raise RuntimeError(message)
RuntimeError: Code input with no code at /Users/sphinxtests/foo/index.rst, line None
```

I agree the error message originating in IPython is not very clear. Perhaps report it to their project?

Closing as this appears not to be a Sphinx issue.
