### ISSUE TITLE
Sphinx fails to build docs for Botan, because it uses requests that needs idea < 2.8

### ISSUE THREAD

**Issue by mouse07410** [sphinx-doc/sphinx#5734]
### Problem
- Sphinx needs `requests`, `requests` needs `idna` and fails with `idna` v2.8.

#### Procedure to reproduce the problem
Attempt to build docs for Botan (see below).

#### Error logs / results
```
Python src/scripts/build_docs.py --build-dir="build"
   INFO: Starting sphinx-build -q -c ./src/configs/sphinx -b html ./doc/manual build/docs/manual
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 2.8 (/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages), Requirement.parse('idna<2.8,>=2.5'), {'requests'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/bin/sphinx-build", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'idna<2.8,>=2.5' distribution was not found and is required by requests
  ERROR: Error running sphinx-build -q -c ./src/configs/sphinx -b html ./doc/manual build/docs/manual
make: *** [build/doc.stamp] Error 1
```
#### Expected results
```
Python src/scripts/install.py --prefix="/opt/local" --build-dir="build" --bindir=bin --libdir=lib --docdir=doc --includedir=include
   INFO: Botan 2.9.0 installation complete
$
```

### Reproducible project / your project
- https://github.com/randombit/botan.git

### Environment info
- OS: MacOS Mojave 10.14.2
- Python version: 3.7
- Sphinx version: 1.8.2
- in the process of building Botan master

**Comment by mouse07410** [comment]
I'd like to amend: now with the new `requests` pushed out to PYPI, it requires `idna < 2.9`, so that part is satisfied.
