### ISSUE TITLE
role with empy target -> TypeError: 'NoneType' object is unsubscriptable

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#581]
This snippet

```
:func:`len <>`
```

makes Sphinx 1.0.5 produce the following backtrace:

```
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/sphinx/cmdline.py", line 173, in main
    app.build(force_all, filenames)
  File "/usr/lib/pymodules/python2.6/sphinx/application.py", line 207, in build
    self.builder.build_update()
  File "/usr/lib/pymodules/python2.6/sphinx/builders/__init__.py", line 198, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/lib/pymodules/python2.6/sphinx/builders/__init__.py", line 254, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/pymodules/python2.6/sphinx/builders/__init__.py", line 292, in write
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/lib/pymodules/python2.6/sphinx/environment.py", line 1104, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/usr/lib/pymodules/python2.6/sphinx/environment.py", line 1310, in resolve_references
    typ, target, node, contnode)
  File "/usr/lib/pymodules/python2.6/sphinx/domains/python.py", line 649, in resolve_xref
    ', '.join(match[0] for match in matches)),
  File "/usr/lib/pymodules/python2.6/sphinx/domains/python.py", line 649, in <genexpr>
    ', '.join(match[0] for match in matches)),
TypeError: 'NoneType' object is unsubscriptable
```

While this is of course a user error:
- it used to work with Sphinx 0.6;
- a better error message would be nice.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/581
- Originally reported by: Jakub Wilk
- Originally created at: 2011-01-04T23:34:01.937

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-01-04 22:39:00+00:00_

Indeed.  Fixed in <<cset 7e3151dd734e3da48741b0150400a26275055bd9>>.
