### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by dojutsu-user** [sphinx-doc/sphinx#5885]
I'm trying to make a custom role for the sphinx doc and the function for that is as follows:

```python3
from docutils import nodes

def my_custom_role(typ, rawtext, text, lineno, inliner, options=None, content=None):
    term_1 = nodes.term('', nodes.Text('TERM'))
    def_1 = nodes.definition('', nodes.Text('TERM DESCRIPTION'))
    dli = nodes.definition_list_item('', term_1, def_1)
    dl = nodes.definition_list('', dli, dli)
    return [dl], []
```
And I'm getting this error:
```
# Sphinx version: 1.8.2
# Python version: 3.6.7 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   writing output... [ 52%] gsoc
#   
#   writing output... [ 53%] guides/adding-custom-css
#   
#   writing output... [ 55%] guides/build-notifications
#   
#   writing output... [ 56%] guides/build-using-too-many-resources
#   
#   writing output... [ 57%] guides/feature-flags
#   
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.2) from /home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.12) from /home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.8.2) from /home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.intersphinx (1.8.2) from /home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinxcontrib.httpdomain (unknown version) from /home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/sphinxcontrib/httpdomain.py
#   djangodocs (unknown version) from /home/pikachu/Desktop/rtd/readthedocs.org/docs/_ext/djangodocs.py
#   sphinx_tabs.tabs (unknown version) from /home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/sphinx_tabs/tabs.py
Traceback (most recent call last):
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 412, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 593, in write
    self._write_serial(sorted(docnames))
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 604, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/sphinx/builders/html.py", line 730, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/sphinx/writers/html.py", line 58, in translate
    self.document.walkabout(visitor)
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 4 more times]
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/docutils/writers/html4css1/__init__.py", line 308, in visit_definition
    self.set_first_last(node)
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/docutils/writers/html4css1/__init__.py", line 214, in set_first_last
    self.set_class_on_child(node, 'first', 0)
  File "/home/pikachu/Desktop/rtd/venv/lib/python3.6/site-packages/docutils/writers/_html_base.py", line 399, in set_class_on_child
    child['classes'].append(class_)
TypeError: string indices must be integers
```
OS: Ubuntu 18.04

**Comment by dojutsu-user** [comment]
Okay, I get it.
It was a syntax error from my side.
The function should be like this:

```python3
from docutils import nodes

def my_custom_role(typ, rawtext, text, lineno, inliner, options=None, content=None):
    term_1 = nodes.term(text=nodes.Text('TERM'))
    def_1 = nodes.definition('', nodes.paragraph(text='TERM DESCRIPTION'))
    dli = nodes.definition_list_item('', term_1, def_1)
    dl = nodes.definition_list('', dli, dli)
    return [dl], []
```

**Comment by tk0miya** [comment]
I'd glad to hear your problem is resolved.
But this is not a forum of Sphinx. So please post sphinx-dev forum in next time.
https://groups.google.com/d/forum/sphinx-dev

Thanks,
