### ISSUE TITLE
InvalidGitRepositoryError while compiling pandas docs

### ISSUE THREAD

**Issue by justineuroHP** [sphinx-doc/sphinx#6049]
**Describe the bug**
Got `InvalidGitRepositoryError`  when I tried to build the [pandas docs](https://github.com/pandas-dev/panda) in Ubuntu 18.04 LTS (Bionic Beaver) running in WIndows 10

**To Reproduce**
```
$ git clone htps://github.com/pandas-dev/pandas
$ cd pandas
$ python setup.py build_ext --inplace --force
$ cd doc
$ python make.py clean
$ python make.py html
```

**Expected behavior**
Docs get built.

**Your project**
[None]

**Screenshots**
[None]

**Environment info**
- OS: Ubuntu 18.04 LTS (Bionic Beaver) running in Windows 10
- Sphinx version: 1.8.4
- Docutils version: 0.14
- Jinja2 version: 2.10
- Last messages:  
[NOTE:  The output below and in the attached .log file have been edited to allow anonymity.]
```bash
# Loaded extensions:
Traceback (most recent call last):
  File "/USERHOMEDIR/.local/lib/python2.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/USERHOMEDIR/.local/lib/python2.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/USERHOMEDIR/.local/lib/python2.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/USERHOMEDIR/.local/lib/python2.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/mnt/c/Users/path/to/pandas-0.24.1/doc/sphinxext/contributors.py", line 15, in <module>
    from announce import build_components
  File "/mnt/c/Users/path/to/pandas-0.24.1/doc/sphinxext/announce.py", line 46, in <module>
    this_repo = Repo(os.path.join(os.path.dirname(__file__), "..", ".."))
  File "/USERHOMEDIR/.local/lib/python2.7/site-packages/git/repo/base.py", line 168, in __init__
    raise InvalidGitRepositoryError(epath)
InvalidGitRepositoryError: /mnt/c/Users/path/to/pandas-0.24.1
```

**Additional context**
The terminal output after `python make.py html`:
```bash
$ python make.py html
Running Sphinx v1.8.4

Exception occurred:
  File "/USERHOMEDIR/.local/lib/python2.7/site-packages/git/repo/base.py", line 168, in __init__
    raise InvalidGitRepositoryError(epath)
InvalidGitRepositoryError: /mnt/c/Users/path/to/pandas-0.24.1
The full traceback has been saved in /tmp/sphinx-err-ok2HFX.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Traceback (most recent call last):
  File "make.py", line 339, in <module>
    sys.exit(main())
  File "make.py", line 335, in main
    return getattr(builder, args.command)()
  File "make.py", line 226, in html
    self._add_redirects()
  File "make.py", line 209, in _add_redirects
    with open(path, 'w') as moved_page_fd:
IOError: [Errno 2] No such file or directory: '/mnt/c/Users/path/to/pandas-0.24.1/doc/build/html/whatsnew.html'
```

The .log file is: 
[sphinx-err-ok2HFX-EDITED.log](https://github.com/sphinx-doc/sphinx/files/2848543/sphinx-err-ok2HFX-EDITED.log).

**Comment by justineuroHP** [comment]
Apologies. I was working on the wrong folder.  Instead of pandas-0.24.1/doc folder (the latest release  which I downloaded and unzipped) I should have been using the pandas/doc folder.  Using now the right folder, I get the following error after `python make.py html`:
```bash
$ python make.py html
Running Sphinx v1.8.4
making output directory...
[autosummary] generating autosummary for: development/contributing.rst, development/contributing_docstring.rst, development/developer.rst, development/extending.rst, development/index.rst, development/internals.rst, ecosystem.rst, getting_started/10min.rst, getting_started/basics.rst, getting_started/comparison/comparison_with_r.rst, ..., whatsnew/v0.6.0.rst, whatsnew/v0.6.1.rst, whatsnew/v0.7.0.rst, whatsnew/v0.7.1.rst, whatsnew/v0.7.2.rst, whatsnew/v0.7.3.rst, whatsnew/v0.8.0.rst, whatsnew/v0.8.1.rst, whatsnew/v0.9.0.rst, whatsnew/v0.9.1.rst
WARNING: [autosummary] failed to import u'pandas.Timestamp.fold': no module named pandas.Timestamp.fold
[autosummary] generating autosummary for: /path/to/pandas/doc/source/reference/api/pandas.

...

building [mo]: targets for 0 po files that are out of date
building [html]: targets for 106 source files that are out of date
updating environment: 2781 added, 0 changed, 0 removed
/path/to/pandas/pandas/core/generic.py:docstring of pandas.DataFrame.asof:28: WARNING: Unexpected indentation.
/path/to/pandas/pandas/core/generic.py:docstring of pandas.DataFrame.asof:29: WARNING: Block quote ends without a blank line; unexpected unindent.
/path/to/pandas/pandas/core/generic.py:docstring of pandas.DataFrame.ewm:19: WARNING: Unexpected indentation.
/path/to/pandas/pandas/core/generic.py:docstring of pandas.DataFrame.ewm:17: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/path/to/pandas/pandas/core/accessor.py:docstring of pandas.DatetimeIndex.ceil:29: WARNING: Block quote ends without a blank line; unexpected unindent.
/path/to/pandas/pandas/core/accessor.py:docstring of pandas.DatetimeIndex.floor:29: WARNING: Block quote ends without a blank line; unexpected unindent.
/path/to/pandas/pandas/core/accessor.py:docstring of pandas.DatetimeIndex.round:29: WARNING: Block quote ends without a blank line; unexpected unindent.
/path/to/pandas/pandas/core/accessor.py:docstring of pandas.DatetimeIndex.tz_localize:36: WARNING: Block quote ends without a blank line; unexpected unindent.
/path/to/pandas/pandas/core/dtypes/dtypes.py:docstring of pandas.DatetimeTZDtype:36: WARNING: toctree references unknown document u'reference/api/pandas.DatetimeTZDtype.type'
/path/to/pandas/pandas/core/arrays/integer.py:docstring of pandas.Int16Dtype:34: WARNING: toctree references unknown document u'reference/api/pandas.Int16Dtype.type'

Exception occurred:
  File "/usr/lib/python2.7/inspect.py", line 563, in findsource
    raise IOError('could not find class definition')
IOError: could not find class definition
The full traceback has been saved in /tmp/sphinx-err-lTiOie.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Traceback (most recent call last):
  File "make.py", line 339, in <module>
    sys.exit(main())
  File "make.py", line 335, in main
    return getattr(builder, args.command)()
  File "make.py", line 226, in html
    self._add_redirects()
  File "make.py", line 209, in _add_redirects
    with open(path, 'w') as moved_page_fd:
IOError: [Errno 2] No such file or directory: /path/to/pandas/doc/build/html/generated/pandas.api.extensions.ExtensionArray.argsort.html'
```

The .log file (edited to allow anonymity) is also attached: [sphinx-err-lTiOie-EDITED.log](https://github.com/sphinx-doc/sphinx/files/2848671/sphinx-err-lTiOie-EDITED.log)

**Comment by tk0miya** [comment]
The first case, the `InvalidGitRepositoryError` was raised from `sphinxext/announce.py`. It is an extension of pandas document.
```
  File "/mnt/c/Users/path/to/pandas-0.24.1/doc/sphinxext/contributors.py", line 15, in <module>
    from announce import build_components
  File "/mnt/c/Users/path/to/pandas-0.24.1/doc/sphinxext/announce.py", line 46, in <module>
    this_repo = Repo(os.path.join(os.path.dirname(__file__), "..", ".."))
  File "/USERHOMEDIR/.local/lib/python2.7/site-packages/git/repo/base.py", line 168, in __init__
    raise InvalidGitRepositoryError(epath)
InvalidGitRepositoryError: /mnt/c/Users/path/to/pandas-0.24.1
```

On the other hand, the second case was raised from `conf.py`. It is also a part of pandas' document.
```
  File "/USERDIR/.local/lib/python2.7/site-packages/sphinx/ext/linkcode.py", line 63, in doctree_read
    uri = resolve_target(domain, info)
  File "/path/to/pandas/doc/source/conf.py", line 670, in linkcode_resolve
    source, lineno = inspect.getsourcelines(obj)
  File "/usr/lib/python2.7/inspect.py", line 689, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python2.7/inspect.py", line 563, in findsource
    raise IOError('could not find class definition')
IOError: could not find class definition
```

Please ask both cases to pandas' project.
Thanks,

**Comment by justineuroHP** [comment]
Thank you very much! (Posted as [Issue #25258](https://github.com/pandas-dev/pandas/issues/25258) at [pandas-dev/pandas](https://github.com/pandas-dev/pandas).)

**Comment by tk0miya** [comment]
Closing now.
