### ISSUE TITLE
Python2 Doc generation fails with `ImportError: cannot import name UserString`

### ISSUE THREAD

**Issue by cbwest3** [sphinx-doc/sphinx#6090]
**Describe the bug**
Generating documentation with Sphinx v2.0.0b1 fails on Python 2.7.15 due to the use of the [`collections.UserString`](https://docs.python.org/3/library/collections.html#collections.UserString) class, which is only found in Python 3. Pinning Sphinx to 1.8.4 fixed the issue. Running with Python 3.5.3 fixes the issues, I suspect any Python 3.x would work.

**To Reproduce**

```
$ devpi upload --with-docs
detected devpi:upload section in /builds/namespace/project/setup.cfg
using workdir /tmp/devpi0
--> /builds/namespace/project$ /usr/local/bin/python setup.py bdist_wheel 
warning: no files found matching 'AUTHORS'
warning: no files found matching 'ChangeLog'
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
/builds/namespace/project/.eggs/PyScaffold-2.5.11-py2.7.egg/pyscaffold/contrib/pbr/pbr/packaging.py:422: EasyInstallDeprecationWarning: Use get_header
 header = easy_install.get_script_header("", executable, is_wininst)
built: /builds/namespace/project/dist/project-0.0.1.post0.dev21+ngbdd9056-py2.py3-none-any.whl [BDIST_WHEEL] 20kb
--> /builds/namespace/project$ /usr/local/bin/python setup.py build_sphinx -E --build-dir /builds/namespace/project/build 
Traceback (most recent call last):
 File "setup.py", line 23, in <module>
 setup_package()
 File "setup.py", line 19, in setup_package
 use_pyscaffold=True)
 File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
 return distutils.core.setup(**attrs)
 File "/usr/local/lib/python2.7/distutils/core.py", line 137, in setup
 ok = dist.parse_command_line()
 File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 710, in parse_command_line
 result = _Distribution.parse_command_line(self)
 File "/usr/local/lib/python2.7/distutils/dist.py", line 467, in parse_command_line
 args = self._parse_command_opts(parser, args)
 File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 1025, in _parse_command_opts
 nargs = _Distribution._parse_command_opts(self, parser, args)
 File "/usr/local/lib/python2.7/distutils/dist.py", line 523, in _parse_command_opts
 cmd_class = self.get_command_class(command)
 File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 845, in get_command_class
 self.cmdclass[command] = cmdclass = ep.load()
 File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
 return self.resolve()
 File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
 module = __import__(self.module_name, fromlist=['__name__'], level=0)
 File "/builds/namespace/project/.eggs/Sphinx-2.0.0b1-py2.7.egg/sphinx/setup_command.py", line 18, in <module>
 from io import StringIO
 File "/builds/namespace/project/.eggs/Sphinx-2.0.0b1-py2.7.egg/sphinx/io.py", line 22, in <module>
 from sphinx.transforms import (
 File "/builds/namespace/project/.eggs/Sphinx-2.0.0b1-py2.7.egg/sphinx/transforms/__init__.py", line 22, in <module>
 from sphinx.locale import _, __
 File "/builds/namespace/project/.eggs/Sphinx-2.0.0b1-py2.7.egg/sphinx/locale/__init__.py", line 14, in <module>
 from collections import UserString, defaultdict
ImportError: cannot import name UserString
Traceback (most recent call last):
 File "/usr/local/bin/devpi", line 10, in <module>
 sys.exit(main())
 File "/usr/local/lib/python2.7/site-packages/devpi/main.py", line 36, in main
 return method(hub, hub.args)
 File "/usr/local/lib/python2.7/site-packages/devpi/upload.py", line 44, in main
 p = exported.setup_build_docs()
 File "/usr/local/lib/python2.7/site-packages/devpi/upload.py", line 422, in setup_build_docs
 "--build-dir", build], cwd=self.rootpath)
 File "/usr/local/lib/python2.7/site-packages/devpi/main.py", line 283, in popen_output
 return subprocess.check_output(args, cwd=str(cwd)).decode('utf-8')
 File "/usr/local/lib/python2.7/subprocess.py", line 223, in check_output
 raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', 'setup.py', 'build_sphinx', '-E', '--build-dir', '/builds/namespace/project/build']' returned non-zero exit status 1
ERROR: Job failed: exit code 1
```

**Expected behavior**
No stack traces :)

**Environment info**
- OS: Docker python:2 container.
- Python version: 2.7.15
- Sphinx version: 2.0.0b1

**Comment by jfbu** [comment]
Please note that Sphinx 2.0 indeed drops support for Python2.

https://github.com/sphinx-doc/sphinx/blob/12c614911ac1ea94e88ec781fd36281ffd026f0a/CHANGES#L73-L76

Closing as this is a deliberate change, signaled as such...
