### ISSUE TITLE
UnboundLocalError when building changes from module docs

### ISSUE THREAD

**Issue by bz2** [sphinx-doc/sphinx#6134]
Building changes fails if a `::module` directive is included in an rst source file.

**To Reproduce**
For instance, currently trying to build the cpython master changes fails:
```
$ git clone git@github.com:python/cpython.git
$ cd cpython/Doc
$ make venv
$ make changes
```

**Error log**
```
# Python version: 3.6.7 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   pickling environment...
#   
#   done
#   
#   checking consistency...
#   
#   done
#   
#   writing summary file...
#   
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.4) from /home/martin/branches/cpython/Doc/venv/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.12) from /home/martin/branches/cpython/Doc/venv/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.coverage (1.8.4) from /home/martin/branches/cpython/Doc/venv/lib/python3.6/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.doctest (1.8.4) from /home/martin/branches/cpython/Doc/venv/lib/python3.6/site-packages/sphinx/ext/doctest.py
#   pyspecific (1.0) from /home/martin/branches/cpython/Doc/tools/extensions/pyspecific.py
#   c_annotations (1.0) from /home/martin/branches/cpython/Doc/tools/extensions/c_annotations.py
#   escape4chm (1.0) from /home/martin/branches/cpython/Doc/tools/extensions/escape4chm.py
Traceback (most recent call last):
  File "/home/martin/branches/cpython/Doc/venv/lib/python3.6/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/martin/branches/cpython/Doc/venv/lib/python3.6/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/martin/branches/cpython/Doc/venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 342, in build_update
    self.build(['__all__'], to_build)
  File "/home/martin/branches/cpython/Doc/venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 412, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/martin/branches/cpython/Doc/venv/lib/python3.6/site-packages/sphinx/builders/changes.py", line 97, in write
    libchanges.setdefault(module, []).append((entry, changeset.docname,
UnboundLocalError: local variable 'module' referenced before assignment
```

**Comment by tk0miya** [comment]
Closing now.
Thank you for your work!
