### ISSUE TITLE
error occurs when load excel file(merged cell)

### ISSUE THREAD

**Issue by yanbinc** [sphinx-doc/sphinx#6181]
**Describe the bug**
loading the excel file will occur the bug.

<Paste your command-line here which cause the problem>

    Risk_Matrix
    ^^^^^^^^^^^
    
    .. excel-table:: 
        :file: ../_static/wr_Result_20190312/Risk_Matrix.xlsx
    
    \
    
    Risk
    ^^^^^^^^^^^

log file content:

```
# Sphinx version: 1.8.4
# Python version: 3.6.5 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   6 added, 0 changed, 0 removed
#   
#   reading sources... [ 16%] content/T-line_Model
#   
#   reading sources... [ 33%] content/T-topology
#   
#   reading sources... [ 50%] content/Topo_Overview
#   
#   reading sources... [ 66%] content/wr_Result_20190312
#   
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.4) from c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sphinx\ext\mathjax.py
#   alabaster (0.7.12) from c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\alabaster\__init__.py
#   sphinx.ext.autodoc (1.8.4) from c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sphinx\ext\autodoc\__init__.py
#   sphinx.ext.viewcode (1.8.4) from c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sphinx\ext\viewcode.py
#   sphinxcontrib.excel_table (0.0.1) from c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sphinxcontrib\excel_table\__init__.py
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sphinx\cmd\build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sphinx\application.py", line 341, in build
    self.builder.build_update()
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sphinx\builders\__init__.py", line 347, in build_update
    len(to_build))
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sphinx\builders\__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sphinx\builders\__init__.py", line 468, in read
    self._read_serial(docnames)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sphinx\builders\__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sphinx\builders\__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sphinx\io.py", line 318, in read_doc
    pub.publish()
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\core.py", line 217, in publish
    self.settings)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\readers\__init__.py", line 72, in read
    self.parse()
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sphinx\parsers.py", line 88, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 171, in run
    input_source=document['source'])
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\docutils\parsers\rst\states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\sphinxcontrib\excel_table\excel_table.py", line 124, in run
    _row.append(cell.value)
AttributeError: 'MergedCell' object has no attribute 'value'
```

**Comment by tk0miya** [comment]
This must be a bug of `sphinxcontrib-excel-table`, not a Sphinx core.
Please report this to their project.
Thanks,
