### ISSUE TITLE
scikit-learn's circleci failiure: unable to read font (null)

### ISSUE THREAD

**Issue by adrinjalali** [sphinx-doc/sphinx#6210]
Recently we started having issues with the older circle-ci docker image, so we tried switching to a newer image, and now we're having this issues:

```
Traceback (most recent call last):
  File "/home/circleci/miniconda/envs/testenv/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/circleci/miniconda/envs/testenv/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/circleci/miniconda/envs/testenv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/circleci/miniconda/envs/testenv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 412, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/circleci/miniconda/envs/testenv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 593, in write
    self._write_serial(sorted(docnames))
  File "/home/circleci/miniconda/envs/testenv/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 601, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/home/circleci/miniconda/envs/testenv/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 627, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/home/circleci/miniconda/envs/testenv/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 674, in apply_post_transforms
    transformer.apply_transforms()
  File "/home/circleci/miniconda/envs/testenv/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    Transformer.apply_transforms(self)
  File "/home/circleci/miniconda/envs/testenv/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/circleci/miniconda/envs/testenv/lib/python3.7/site-packages/sphinx/transforms/post_transforms/images.py", line 42, in apply
    self.handle(node)
  File "/home/circleci/miniconda/envs/testenv/lib/python3.7/site-packages/sphinx/transforms/post_transforms/images.py", line 264, in handle
    if self.convert(abs_srcpath, destpath):
  File "/home/circleci/miniconda/envs/testenv/lib/python3.7/site-packages/sphinx/ext/imgconverter.py", line 96, in convert
    (stderr, stdout))
sphinx.errors.ExtensionError: convert exited with error:
[stderr]
b"convert-im6.q16: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1362.\nconvert-im6.q16: non-conforming drawing primitive definition `text' @ error/draw.c/DrawImage/3265.\n"
[stdout]
b''

Extension error:
convert exited with error:
[stderr]
b"convert-im6.q16: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1362.\nconvert-im6.q16: non-conforming drawing primitive definition `text' @ error/draw.c/DrawImage/3265.\n"
[stdout]
b''
Makefile:52: recipe for target 'html-noplot' failed
make: *** [html-noplot] Error 2
Exited with code 2
```

This PR(https://github.com/scikit-learn/scikit-learn/pull/13525) is where we're trying the change, and so far I haven't been able to figure where the issue is coming from, and here's the link to the failing build: https://circleci.com/gh/scikit-learn/scikit-learn/52972

**Comment by adrinjalali** [comment]
I know it's most probably not really a bug, more like, I wish it would better tell me what it is that it's trying to do and it's failing.

**Comment by adrinjalali** [comment]
It was some fonts not being installed :man_facepalming: , sorry for the noise.
