### ISSUE TITLE
Windows make html Errno 13 'w' permission denied on \html\.buildinfo

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#624]
I last successfully built docs with 'make html' on my current Windows machine about 1 month ago.  The 'make html' is now failing even though my coworkers are still able to build the same version from our git repo.  Below is the output to the command window, followed by the content of the log file produced.  The error says permission denied for writing to the .buildinfo file .. but a comparison of the permission between files on my machine and coworkers is same .. and theirs works.  Have tried making files writable .. and somewhere in Sphinx processing they get reset to 'r' - see ls snapshot below as well.  I'm guessing some Sphinx support files has changed on my machine .. but have no idea where to start .. haven't changed much over the last month.  Any ideas?

Thanks, Kelly

```
Exception occurred:
  File "C:\Python27\lib\site-packages\sphinx-1.0.5-py2.7.egg\sphinx\builders\html.py", line 575, in write_buildinfo
    fp = open(path.join(self.outdir, '.buildinfo'), 'w')
IOError: [Errno 13] Permission denied: 'D:\\Shared\\mios_spl\\docs\\build\\html\\.buildinfo'
The full traceback has been saved in c:\temp\sphinx-err-gn7axd.log, if you want to report the issue to the developers.



# Sphinx version: 1.0.5
# Python version: 2.7.0
# Docutils version: 0.7 release
# Jinja2 version: 2.5.5
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\sphinx-1.0.5-py2.7.egg\sphinx\cmdline.py", line 173, in main
    app.build(force_all, filenames)
  File "C:\Python27\lib\site-packages\sphinx-1.0.5-py2.7.egg\sphinx\application.py", line 207, in build
    self.builder.build_update()
  File "C:\Python27\lib\site-packages\sphinx-1.0.5-py2.7.egg\sphinx\builders\__init__.py", line 198, in build_update
    'out of date' &#37; len(to_build))
  File "C:\Python27\lib\site-packages\sphinx-1.0.5-py2.7.egg\sphinx\builders\__init__.py", line 257, in build
    self.finish()
  File "C:\Python27\lib\site-packages\sphinx-1.0.5-py2.7.egg\sphinx\builders\html.py", line 446, in finish
    self.write_buildinfo()
  File "C:\Python27\lib\site-packages\sphinx-1.0.5-py2.7.egg\sphinx\builders\html.py", line 575, in write_buildinfo
    fp = open(path.join(self.outdir, '.buildinfo'), 'w')
IOError: [Errno 13] Permission denied: 'D:\\Shared\\mios_spl\\docs\\build\\html\\.buildinfo'



e123456@AZ75LT7QCN4K1 /d/shared/mios_spl/docs/build/html (master)
$ ls -al
total 21
drwxr-xr-x    8 e123456  Administ        0 Jan 31 10:57 .
drwxr-xr-x    6 e123456  Administ        0 Jan 31 10:57 ..
-rw-r--r--    1 e123456  Administ      234 Jan 31 10:57 .buildinfo
drwxr-xr-x    2 e123456  Administ        0 Jan 31 10:58 _images
drwxr-xr-x    5 e123456  Administ        0 Jan 31 10:57 _sources
drwxr-xr-x    2 e123456  Administ        0 Jan 31 10:58 _static
drwxr-xr-x    2 e123456  Administ        0 Jan 31 10:57 application
drwxr-xr-x    2 e123456  Administ        0 Jan 31 10:58 core
drwxr-xr-x    2 e123456  Administ        0 Jan 31 10:57 generated
-rw-r--r--    1 e123456  Administ     3853 Jan 31 11:19 genindex.html
-rw-r--r--    1 e123456  Administ    11506 Jan 31 11:19 index.html
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/624
- Originally reported by: Kelly Morrell
- Originally created at: 2011-01-31T18:53:42.977

**Comment by shimizukawa** [comment]
_From Kelly Morrell on 2011-02-01 19:56:27+00:00_

I have reinstalled Sphinx from the 1.0.5 egg and tried again .. no go.  I then updated to Sphinx 1.0.7 and still getting same error.   I have now attached a file with the command window output that will hopefully help identify the problem in my environment.
Thanks,
Kelly

**Comment by shimizukawa** [comment]
_From Kelly Morrell on 2011-02-02 16:16:40+00:00_

I created a clean clone of our groups repo in a different folder / path and attempted to rebuild .. no go .. so I thought it might be something that had changed in my python 27 environment, libs, or utils.  I created a git repo out of my c:\Python27 directory tree and had my coworker clone it to his machine and use it to build the docs - the build was successful on his machine with my python files.    

So, any thoughts on where I should look now?  I have looked at ../build/html.py It seems like the build is able to read the config info from the .buildinfo file ok (and it should be closing the file pointer at that point) but when it comes time to write out the new config info, it appears the file pointer may still be open.   I have rebooted and changed paths just in case a previous pointer open for write was hanging around, but still no go.  Probably something simple .. just not seeing it.

Thanks,
Kelly

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-09-22 12:27:28+00:00_

Indeed the file was probably kept open longer than it had to; this should be fixed in <<cset f250397f77848926575e0bdba0cd7736ed2c8171>>.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-10-18 07:32:19+00:00_

Removing version: 1.0.7 (automated comment)

**Comment by reformstudios** [comment]
I'm having this issue. Is there any way to fix it? It's a real pain having to manually delete the file every time I want to build!

**Comment by tk0miya** [comment]
This is already closed 6 years ago. Could you file your problem as a new issue please?
