### ISSUE TITLE
Sphinx on Fedora 14 does not support language=fr

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#634]
[oli@cfengine-client2 doc]$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.0.7

Exception occurred:
  File "/home/oli/doc/conf.py", line 57, in <module>
    language = fr
NameError: name 'fr' is not defined
The full traceback has been saved in /tmp/sphinx-err-JD0AwP.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at http://groups.google.com/group/sphinx-dev/,
or report them in the tracker at https://bitbucket.org/birkenfeld/sphinx/issues/. Thanks!
make: **\* [html] Error 1
[oli@cfengine-client2 doc]$ python
Python 2.7 (r27:82500, Sep 16 2010, 18:03:06) 
[GCC 4.5.1 20100907 (Red Hat 4.5.1-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/634
- Originally reported by: Anonymous
- Originally created at: 2011-02-11T23:10:46.790

**Comment by shimizukawa** [comment]
_From Anonymous on 2011-02-11 22:22:35+00:00_

here is the copy of the log file:

# Sphinx version: 1.0.7

# Python version: 2.7.0

# Docutils version: 0.7 release

# Jinja2 version: 2.5.5

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 187, in main
    warningiserror, tags)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 104, in **init**
    confoverrides or {}, self.tags)
  File "/usr/lib/python2.7/site-packages/sphinx/config.py", line 168, in **init**
    execfile(config['**file**'], config)
  File "/home/oli/doc/conf.py", line 57, in <module>
    language = fr
NameError: name 'fr' is not defined

**Comment by shimizukawa** [comment]
_From Anonymous on 2011-02-11 23:10:19+00:00_

Please try setting //language// to the string literal {{{'fr'}}} instead of {{{fr}}}.

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2011-02-11 23:12:05+00:00_

Please try setting //language// to the string literal {{{'fr'}}} instead of {{{fr}}}.
