### ISSUE TITLE
Error when running sphinx-quickstart future = tasks.async(future, loop=self) invalid syntax

### ISSUE THREAD

**Issue by sevaho** [sphinx-doc/sphinx#6437]
When installing sphinx and running sphinx-quickstart I get the following error:

```
Traceback (most recent call last):
  File "/usr/sbin/sphinx-quickstart", line 11, in <module>
    load_entry_point('Sphinx==2.0.1', 'console_scripts', 'sphinx-quickstart')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/sphinx/cmd/quickstart.py", line 43, in <module>
    from sphinx.util.template import SphinxRenderer
  File "/usr/lib/python3.7/site-packages/sphinx/util/template.py", line 13, in <module>
    from jinja2.sandbox import SandboxedEnvironment
  File "/usr/lib/python3.7/site-packages/jinja2/__init__.py", line 82, in <module>
    _patch_async()
  File "/usr/lib/python3.7/site-packages/jinja2/__init__.py", line 78, in _patch_async
    from jinja2.asyncsupport import patch_all
  File "/usr/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 13, in <module>
    import asyncio
  File "/home/sevaho/.local/lib/python3.7/site-packages/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/home/sevaho/.local/lib/python3.7/site-packages/asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                       ^
SyntaxError: invalid syntax
```

I ran it in a pipenv environment so it should be isolated :/

*Environment info**
- OS: [e.g. Linux]
- Python version: [e.g. 3.7.3]
- Sphinx version: [e.g. 2.1]

**Comment by tk0miya** [comment]
This is very strange situation. It seems your PC contains "3rd party" `asyncio` module... And it is not compatible with python 3.7. 
```
  File "/home/sevaho/.local/lib/python3.7/site-packages/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/home/sevaho/.local/lib/python3.7/site-packages/asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                       ^
SyntaxError: invalid syntax
```

I don't know why `asyncio` package is installed. It is no longer needed for python3.7. It was merged into python-core in 3.4.
https://pypi.org/project/asyncio/

Please check why such package is installed and try again after removal of it.

**Comment by sevaho** [comment]
You are totally right, my bad. Thank you!

**Comment by ashxos** [comment]
Any solution on this?

Im facing below issue :
2021-05-15T18:31:18.325995575Z Output is compressed. Extracting it...
2021-05-15T18:31:18.326659481Z Extracting '/home/site/wwwroot/output.tar.gz' to directory '/tmp/8d916ea417c6219'...
2021-05-15T18:31:20.076376793Z App path is set to '/tmp/8d916ea417c6219'
2021-05-15T18:31:21.240716330Z Detected an app based on Flask
2021-05-15T18:31:21.240978933Z Generating `gunicorn` command for 'app:app'
2021-05-15T18:31:21.852584182Z Writing output script to '/opt/startup/startup.sh'
2021-05-15T18:31:22.829488123Z Using packages from virtual environment antenv located at /tmp/8d916ea417c6219/antenv.
2021-05-15T18:31:22.835485181Z Updated PYTHONPATH to ':/tmp/8d916ea417c6219/antenv/lib/python3.8/site-packages'
2021-05-15T18:31:24.045231346Z [2021-05-15 18:31:24 +0000] [36] [INFO] Starting gunicorn 20.0.4
2021-05-15T18:31:24.046341957Z [2021-05-15 18:31:24 +0000] [36] [INFO] Listening at: http://0.0.0.0:8000 (36)
2021-05-15T18:31:24.046758261Z [2021-05-15 18:31:24 +0000] [36] [INFO] Using worker: sync
2021-05-15T18:31:24.058362272Z [2021-05-15 18:31:24 +0000] [38] [INFO] Booting worker with pid: 38
2021-05-15T18:31:27.456225074Z [2021-05-15 18:31:27 +0000] [38] [ERROR] Exception in worker process
2021-05-15T18:31:27.456250774Z Traceback (most recent call last):
2021-05-15T18:31:27.456256074Z   File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2021-05-15T18:31:27.456269774Z     worker.init_process()
2021-05-15T18:31:27.456273474Z   File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
2021-05-15T18:31:27.456277374Z     self.load_wsgi()
2021-05-15T18:31:27.456280674Z   File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2021-05-15T18:31:27.456284275Z     self.wsgi = self.app.wsgi()
2021-05-15T18:31:27.456287675Z   File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
2021-05-15T18:31:27.456291275Z     self.callable = self.load()
2021-05-15T18:31:27.456300975Z   File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2021-05-15T18:31:27.456304575Z     return self.load_wsgiapp()
2021-05-15T18:31:27.456307975Z   File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2021-05-15T18:31:27.456311475Z     return util.import_app(self.app_uri)
2021-05-15T18:31:27.456314975Z   File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
2021-05-15T18:31:27.456318475Z     mod = importlib.import_module(module)
2021-05-15T18:31:27.456321775Z   File "/opt/python/3.8.6/lib/python3.8/importlib/__init__.py", line 127, in import_module
2021-05-15T18:31:27.456325275Z     return _bootstrap._gcd_import(name[level:], package, level)
2021-05-15T18:31:27.456328675Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2021-05-15T18:31:27.456332475Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2021-05-15T18:31:27.456335975Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2021-05-15T18:31:27.456339475Z   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2021-05-15T18:31:27.456342975Z   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2021-05-15T18:31:27.456346475Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-05-15T18:31:27.456349975Z   File "/tmp/8d916ea417c6219/app.py", line 6, in <module>
2021-05-15T18:31:27.456353675Z     from fyers_api import accessToken
2021-05-15T18:31:27.456356975Z   File "/tmp/8d916ea417c6219/antenv/lib/python3.8/site-packages/fyers_api/accessToken.py", line 1, in <module>
2021-05-15T18:31:27.456360775Z     from .fyersService import FyersService
2021-05-15T18:31:27.456364075Z   File "/tmp/8d916ea417c6219/antenv/lib/python3.8/site-packages/fyers_api/fyersService.py", line 6, in <module>
2021-05-15T18:31:27.456367775Z     from tornado import httpclient
2021-05-15T18:31:27.456372375Z   File "/tmp/8d916ea417c6219/antenv/lib/python3.8/site-packages/tornado/httpclient.py", line 46, in <module>
2021-05-15T18:31:27.456379475Z     from tornado.concurrent import (
2021-05-15T18:31:27.456382875Z   File "/tmp/8d916ea417c6219/antenv/lib/python3.8/site-packages/tornado/concurrent.py", line 28, in <module>
2021-05-15T18:31:27.456386575Z     import asyncio
2021-05-15T18:31:27.456390175Z   File "/tmp/8d916ea417c6219/antenv/lib/python3.8/site-packages/asyncio/__init__.py", line 21, in <module>
2021-05-15T18:31:27.456393775Z     from .base_events import *
2021-05-15T18:31:27.456396975Z   File "/tmp/8d916ea417c6219/antenv/lib/python3.8/site-packages/asyncio/base_events.py", line 296
2021-05-15T18:31:27.456400575Z     future = tasks.async(future, loop=self)
2021-05-15T18:31:27.456403875Z                    ^
2021-05-15T18:31:27.456407076Z SyntaxError: invalid syntax
2021-05-15T18:31:27.493341681Z [2021-05-15 18:31:27 +0000] [38] [INFO] Worker exiting (pid: 38)
2021-05-15T18:31:27.626983486Z [2021-05-15 18:31:27 +0000] [36] [INFO] Shutting down: Master
2021-05-15T18:31:27.627438990Z [2021-05-15 18:31:27 +0000] [36] [INFO] Reason: Worker failed to boot.
2021-05-15T18:31:33.721Z ERROR - Container rockettokensaverapp_0_646000ec for site rockettokensaverapp has exited, failing site start
2021-05-15T18:31:33.724Z ERROR - Container rockettokensaverapp_0_646000ec didn't respond to HTTP pings on port: 8000, failing site start. See container logs for debugging.
2021-05-15T18:31:33.760Z INFO  - Stopping site rockettokensaverapp because it failed during startup.

**Comment by keyurm-wmt** [comment]
> Any solution on this?
> 
> Im facing below issue :
> 2021-05-15T18:31:18.325995575Z Output is compressed. Extracting it...
> 2021-05-15T18:31:18.326659481Z Extracting '/home/site/wwwroot/output.tar.gz' to directory '/tmp/8d916ea417c6219'...
> 2021-05-15T18:31:20.076376793Z App path is set to '/tmp/8d916ea417c6219'
> 2021-05-15T18:31:21.240716330Z Detected an app based on Flask
> 2021-05-15T18:31:21.240978933Z Generating `gunicorn` command for 'app:app'
> 2021-05-15T18:31:21.852584182Z Writing output script to '/opt/startup/startup.sh'
> 2021-05-15T18:31:22.829488123Z Using packages from virtual environment antenv located at /tmp/8d916ea417c6219/antenv.
> 2021-05-15T18:31:22.835485181Z Updated PYTHONPATH to ':/tmp/8d916ea417c6219/antenv/lib/python3.8/site-packages'
> 2021-05-15T18:31:24.045231346Z [2021-05-15 18:31:24 +0000] [36] [INFO] Starting gunicorn 20.0.4
> 2021-05-15T18:31:24.046341957Z [2021-05-15 18:31:24 +0000] [36] [INFO] Listening at: http://0.0.0.0:8000 (36)
> 2021-05-15T18:31:24.046758261Z [2021-05-15 18:31:24 +0000] [36] [INFO] Using worker: sync
> 2021-05-15T18:31:24.058362272Z [2021-05-15 18:31:24 +0000] [38] [INFO] Booting worker with pid: 38
> 2021-05-15T18:31:27.456225074Z [2021-05-15 18:31:27 +0000] [38] [ERROR] Exception in worker process
> 2021-05-15T18:31:27.456250774Z Traceback (most recent call last):
> 2021-05-15T18:31:27.456256074Z File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
> 2021-05-15T18:31:27.456269774Z worker.init_process()
> 2021-05-15T18:31:27.456273474Z File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
> 2021-05-15T18:31:27.456277374Z self.load_wsgi()
> 2021-05-15T18:31:27.456280674Z File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
> 2021-05-15T18:31:27.456284275Z self.wsgi = self.app.wsgi()
> 2021-05-15T18:31:27.456287675Z File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
> 2021-05-15T18:31:27.456291275Z self.callable = self.load()
> 2021-05-15T18:31:27.456300975Z File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
> 2021-05-15T18:31:27.456304575Z return self.load_wsgiapp()
> 2021-05-15T18:31:27.456307975Z File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
> 2021-05-15T18:31:27.456311475Z return util.import_app(self.app_uri)
> 2021-05-15T18:31:27.456314975Z File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
> 2021-05-15T18:31:27.456318475Z mod = importlib.import_module(module)
> 2021-05-15T18:31:27.456321775Z File "/opt/python/3.8.6/lib/python3.8/importlib/**init**.py", line 127, in import_module
> 2021-05-15T18:31:27.456325275Z return _bootstrap._gcd_import(name[level:], package, level)
> 2021-05-15T18:31:27.456328675Z File "", line 1014, in _gcd_import
> 2021-05-15T18:31:27.456332475Z File "", line 991, in _find_and_load
> 2021-05-15T18:31:27.456335975Z File "", line 975, in _find_and_load_unlocked
> 2021-05-15T18:31:27.456339475Z File "", line 671, in _load_unlocked
> 2021-05-15T18:31:27.456342975Z File "", line 783, in exec_module
> 2021-05-15T18:31:27.456346475Z File "", line 219, in _call_with_frames_removed
> 2021-05-15T18:31:27.456349975Z File "/tmp/8d916ea417c6219/app.py", line 6, in
> 2021-05-15T18:31:27.456353675Z from fyers_api import accessToken
> 2021-05-15T18:31:27.456356975Z File "/tmp/8d916ea417c6219/antenv/lib/python3.8/site-packages/fyers_api/accessToken.py", line 1, in
> 2021-05-15T18:31:27.456360775Z from .fyersService import FyersService
> 2021-05-15T18:31:27.456364075Z File "/tmp/8d916ea417c6219/antenv/lib/python3.8/site-packages/fyers_api/fyersService.py", line 6, in
> 2021-05-15T18:31:27.456367775Z from tornado import httpclient
> 2021-05-15T18:31:27.456372375Z File "/tmp/8d916ea417c6219/antenv/lib/python3.8/site-packages/tornado/httpclient.py", line 46, in
> 2021-05-15T18:31:27.456379475Z from tornado.concurrent import (
> 2021-05-15T18:31:27.456382875Z File "/tmp/8d916ea417c6219/antenv/lib/python3.8/site-packages/tornado/concurrent.py", line 28, in
> 2021-05-15T18:31:27.456386575Z import asyncio
> 2021-05-15T18:31:27.456390175Z File "/tmp/8d916ea417c6219/antenv/lib/python3.8/site-packages/asyncio/**init**.py", line 21, in
> 2021-05-15T18:31:27.456393775Z from .base_events import *
> 2021-05-15T18:31:27.456396975Z File "/tmp/8d916ea417c6219/antenv/lib/python3.8/site-packages/asyncio/base_events.py", line 296
> 2021-05-15T18:31:27.456400575Z future = tasks.async(future, loop=self)
> 2021-05-15T18:31:27.456403875Z ^
> 2021-05-15T18:31:27.456407076Z SyntaxError: invalid syntax
> 2021-05-15T18:31:27.493341681Z [2021-05-15 18:31:27 +0000] [38] [INFO] Worker exiting (pid: 38)
> 2021-05-15T18:31:27.626983486Z [2021-05-15 18:31:27 +0000] [36] [INFO] Shutting down: Master
> 2021-05-15T18:31:27.627438990Z [2021-05-15 18:31:27 +0000] [36] [INFO] Reason: Worker failed to boot.
> 2021-05-15T18:31:33.721Z ERROR - Container rockettokensaverapp_0_646000ec for site rockettokensaverapp has exited, failing site start
> 2021-05-15T18:31:33.724Z ERROR - Container rockettokensaverapp_0_646000ec didn't respond to HTTP pings on port: 8000, failing site start. See container logs for debugging.
> 2021-05-15T18:31:33.760Z INFO - Stopping site rockettokensaverapp because it failed during startup.

if you install asyncio externally and you use above 3.3 python version then uninstall asyncio using ``` pip uninstall asyncio ``` it's works for me because 3.4 and above version added this in python-core so no need to add externally asyncio

**Comment by astrojuanlu** [comment]
Please take this conversation elsewhere, your problem has nothing to do with Sphinx.
