### ISSUE TITLE
Make html fails - "AttributeError: 'Sphinx' object has no attribute 'warn'"

### ISSUE THREAD

**Issue by rrigdon** [sphinx-doc/sphinx#6484]
**Describe the bug**
When running make html in VS Code 1.30.2, an exception occurs which fails to build the docs.

**To Reproduce**

```
(base) ➜  docs git:(favicon) ✗ make html
Running Sphinx v2.1.0
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 91 source files that are out of date
updating environment: 91 added, 0 changed, 0 removed

Exception occurred:
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinxcontrib/programoutput/__init__.py", line 223, in run_programs
    app.warn('Unexpected return code {0} from command {1}'.format(
AttributeError: 'Sphinx' object has no attribute 'warn' 
```

**Expected behavior**
Documents build in html

Traceback log: 
```
# Sphinx version: 2.1.0
# Python version: 3.7.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   reading sources... [ 12%] commands/create
#   reading sources... [ 13%] commands/info
#   reading sources... [ 14%] commands/install
#   reading sources... [ 15%] commands/list
#   reading sources... [ 16%] commands/package
#   reading sources... [ 17%] commands/remove
#   reading sources... [ 18%] commands/search
#   reading sources... [ 19%] commands/update
#   reading sources... [ 20%] config
#   reading sources... [ 21%] configuration
# Loaded extensions:
#   sphinx.ext.mathjax (2.1.0) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.1) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinxarg.ext (unknown version) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinxarg/ext.py
#   sphinxcontrib.programoutput (unknown version) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinxcontrib/programoutput/__init__.py
#   sphinx.ext.autodoc (2.1.0) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.napoleon (2.1.0) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.autosummary (2.1.0) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.graphviz (2.1.0) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/ext/graphviz.py
#   sphinx.ext.ifconfig (2.1.0) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.inheritance_diagram (2.1.0) from /Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/ext/inheritance_diagram.py
Traceback (most recent call last):
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 345, in build
    self.builder.build_update()
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 319, in build_update
    len(to_build))
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 332, in build
    updated_docnames = set(self.read())
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 438, in read
    self._read_serial(docnames)
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 460, in _read_serial
    self.read_doc(docname)
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 504, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/io.py", line 325, in read_doc
    pub.publish()
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    super().apply_transforms()
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 386, in apply
    self.app.emit('doctree-read', self.document)
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 449, in emit
    return self.events.emit(event, *args)
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinx/events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "/Users/rrigdon/anaconda3/lib/python3.7/site-packages/sphinxcontrib/programoutput/__init__.py", line 223, in run_programs
    app.warn('Unexpected return code {0} from command {1}'.format(
AttributeError: 'Sphinx' object has no attribute 'warn'
``` 

**Environment info**
- OS: Mac 10.14.5
- Python version: 3.7.3
- Sphinx version: 2.1.0
- Sphinx extensions: extensions = 
    'sphinxarg.ext',
    'sphinxcontrib.programoutput',
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.autosummary',
    'sphinx.ext.graphviz',
    'sphinx.ext.ifconfig',
    'sphinx.ext.inheritance_diagram'
- Extra tools: Chrome

**Additional context**

- [e.g. URL or Ticket]

**Comment by tk0miya** [comment]
`Sphinx.warn()` was deprecated since 1.6 and removed at 2.0. Please check your version of programoutput extension. It seems the latest release is supporting Sphinx-2.0.

Thanks,
