### ISSUE TITLE
sphinx unicode decode error when reading getopt.rst from a local copy of the  Python 2.7.1 standard library?

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#657]
This error I got from sphinx looks insane to me.  I ran sphinx-quickstart in the wrong place (my home directory) and thus it happily went and found a local copy pypy has of the 2.7.1 Docs.  Then it gave me a unicode decode error.

Here is what happened.

lac@smartwheels:~$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.0.7
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
building [html]: targets for 1307 source files that are out of date
updating environment: 1307 added, 0 changed, 0 removed
reading sources... [  0&#37;] oejskit/laura-talk/vpython/lib/python2.6/site-packages

<more reading sources lines skipped>

reading sources... [ 18&#37;] pypy/Python/Python-2.7.1/Doc/library/getopt  
Exception occurred:
  File "/usr/local/lib/python2.6/dist-packages/sphinx/ext/viewcode.py", line 34, in has_tag
    entry = analyzer.code.decode(analyzer.encoding), analyzer.tags, {}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 858: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-3RcJNF.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at http://groups.google.com/group/sphinx-dev/,
or report them in the tracker at https://bitbucket.org/birkenfeld/sphinx/issues/. Thanks!
make: **\* [html] Error 1

lac@smartwheels:more /tmp/sphinx-err-3RcJNF.log
# Sphinx version: 1.0.7
# Python version: 2.6.6
# Docutils version: 0.7 release
# Jinja2 version: 2.5.5

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/sphinx/cmdline.py", line 188, in 
main
    app.build(force_all, filenames)
  File "/usr/local/lib/python2.6/dist-packages/sphinx/application.py", line 207,
 in build
    self.builder.build_update()
  File "/usr/local/lib/python2.6/dist-packages/sphinx/builders/**init**.py", lin
e 198, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/local/lib/python2.6/dist-packages/sphinx/builders/**init**.py", lin
e 218, in build
    purple, length):
  File "/usr/local/lib/python2.6/dist-packages/sphinx/builders/**init**.py", lin
e 120, in status_iterator
    for item in iterable:
  File "/usr/local/lib/python2.6/dist-packages/sphinx/environment.py", line 519,
 in update_generator
    self.read_doc(docname, app=app)
  File "/usr/local/lib/python2.6/dist-packages/sphinx/environment.py", line 685,
 in read_doc
    app.emit('doctree-read', doctree)
  File "/usr/local/lib/python2.6/dist-packages/sphinx/application.py", line 317,
 in emit
    results.append(callback(self, *args))
  File "/usr/local/lib/python2.6/dist-packages/sphinx/ext/viewcode.py", line 54,
 in doctree_read
    if not has_tag(modname, fullname, env.docname):
  File "/usr/local/lib/python2.6/dist-packages/sphinx/ext/viewcode.py", line 34,
 in has_tag
    entry = analyzer.code.decode(analyzer.encoding), analyzer.tags, {}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 858: ordinal not in range(128)

....

I would have expected to find something written in latin-1 with no
encoding.  But I couldn't find a thing there.  It looks just the same 
as a different copy of 2.7.1 standard library which I pulled down 
in order to run cmp on them.  So I am puzzled now.

Laura Creighton

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/657
- Originally reported by: [lac](https://bitbucket.org/lac)
- Originally created at: 2011-03-15T21:01:55.803

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-05-15 11:31:58+00:00_

Well, if you do "import getopt" in your Python 2.6, you will get the 2.6 getopt, which is in latin-1 and includes a Å.

Now why the module coding cookie isn't read correctly, this is a bug in viewcode and I'll push a fix soon.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-05-15 11:52:59+00:00_

Closes #657: viewcode now works correctly with source files that have non-ASCII encoding.

→ <<cset 40c294f0c82dac955dba57f75a8906ac2e322452>>
