### ISSUE TITLE
Improve error message for NoUri (latex builder)

### ISSUE THREAD

**Issue by JulienPalard** [sphinx-doc/sphinx#6582]
This is the same as: https://github.com/sphinx-doc/sphinx/issues/241

I'm having it, like this:

```
/srv/docsbuild/venv/bin/sphinx-build -b latex -d build/doctrees -D latex_elements.papersize=a4 -D latex_engine=xelatex -D latex_elements.inputenc= -D latex_ele
ments.fontenc=\\usepackage{fontspec} -q -D locale_dirs=/srv/docsbuild/3.9/locale -D language=fr -D gettext_compact=0 -Ea -A daily=1 -A switchers=1  . build/lat
ex 

Exception occurred:
  File "/srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/builders/latex/__init__.py", line 152, in get_target_uri
    raise NoUri
sphinx.environment.NoUri
The full traceback has been saved in /tmp/sphinx-err-ijnc7cnz.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:44: recipe for target 'build' failed
```

The log contains:
```
# Sphinx version: 2.0.1
# Python version: 3.6.8 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:
#   library/imp
#   
#   library/undoc
#   
#   
#   
#   resolving references...
#   
#   failed
#   
# Loaded extensions:
#   sphinx.ext.mathjax (2.0.1) from /srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /srv/docsbuild/venv/lib/python3.6/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /srv/docsbuild/venv/lib/python3.6/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /srv/docsbuild/venv/lib/python3.6/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /srv/docsbuild/venv/lib/python3.6/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /srv/docsbuild/venv/lib/python3.6/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /srv/docsbuild/venv/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.coverage (2.0.1) from /srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.doctest (2.0.1) from /srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/ext/doctest.py
#   pyspecific (1.0) from /srv/docsbuild/3.9/cpython-fr/Doc/tools/extensions/pyspecific.py
#   c_annotations (1.0) from /srv/docsbuild/3.9/cpython-fr/Doc/tools/extensions/c_annotations.py
#   escape4chm (1.0) from /srv/docsbuild/3.9/cpython-fr/Doc/tools/extensions/escape4chm.py
Traceback (most recent call last):
  File "/srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_all()
  File "/srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 284, in build_all
    self.build(None, summary=__('all source files'), method='all')
  File "/srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 389, in build
    self.write(docnames, list(updated_docnames), method)
  File "/srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/builders/latex/__init__.py", line 266, in write
    appendices=((docclass != 'howto') and self.config.latex_appendices or []))
  File "/srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/builders/latex/__init__.py", line 324, in assemble_doctree
    self.env.resolve_references(largetree, indexfile, self)
  File "/srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 590, in resolve_references
    self.apply_post_transforms(doctree, fromdocname)
  File "/srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 608, in apply_post_transforms
    self.app.emit('doctree-resolved', doctree, docname)
  File "/srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/application.py", line 440, in emit
    return self.events.emit(event, self, *args)
  File "/srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/events.py", line 76, in emit
    results.append(callback(*args))
  File "/srv/docsbuild/3.9/cpython-fr/Doc/tools/extensions/pyspecific.py", line 573, in process_audit_events
    app.builder.get_relative_uri(fromdocname, doc),
  File "/srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/builders/latex/__init__.py", line 159, in get_relative_uri
    return self.get_target_uri(to, typ)
  File "/srv/docsbuild/venv/lib/python3.6/site-packages/sphinx/builders/latex/__init__.py", line 152, in get_target_uri
    raise NoUri
sphinx.environment.NoUri
```

**Describe the bug**
For the moment, I don't know what is causing this, I'm inspecting, bug anyway I hoped for the error to be more verbose.

**To Reproduce**
Steps to reproduce the behavior (there may be a shorter way):
```
git clone https://github.com/python/cpython/
cd cpython/Doc
sphinx-build -b latex -d build/doctrees -D latex_elements.papersize=a4 -D latex_engine=xelatex -D latex_elements.inputenc= -D latex_elements.fontenc=\\\\usepackage{xeCJK} -Ea -A daily=1 -A switchers=1  . build/latex
```

**Expected behavior**
Simply having the missing URL in the exception would help, if any.

**Environment info**

See logs, but also reproduced on:

- OS: Debian buster
- Python version: 3.7.3
- Sphinx version: 2.0.1 and 2.1.2

**Comment by tk0miya** [comment]
Fixed by #6980 
Thanks,
