### ISSUE TITLE
with linux-next and recently updated python after 36hours of compiling

### ISSUE THREAD

**Issue by vanbreukelingen** [sphinx-doc/sphinx#6587]
```
writing output... [ 48%] ia64/index .. leds/leds-lm3556

Exception occurred:
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
The full traceback has been saved in /tmp/sphinx-err-ekuprmyg.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

```

In /tmp/spinx-err-ekuprmyg.log it is to be find the following:

```
# Sphinx version: 2.1.2
# Python version: 3.7.4 (CPython)
# Docutils version: 0.14
# Jinja2 version: 2.10.1
# Last messages:
#   writing output... [ 12%] admin-guide/perf/arm_dsu_pmu .. arm/sa1100/pangolin
#   writing output... [ 16%] arm/sa1100/pleb .. cdrom/index
#   writing output... [ 20%] cdrom/packet-writing .. driver-api/dmaengine/client
#   writing output... [ 24%] driver-api/dmaengine/dmatest .. driver-api/mei/nfc
#   writing output... [ 28%] driver-api/memory-devices/index .. driver-api/usb/bulk-streams
#   writing output... [ 32%] driver-api/usb/callbacks .. filesystems/ext4/index
#   writing output... [ 36%] filesystems/ext4/inlinedata .. hwmon/adc128d818
#   writing output... [ 40%] hwmon/adm1021 .. hwmon/max1668
#   writing output... [ 44%] hwmon/max197 .. ia64/ia64
#   writing output... [ 48%] ia64/index .. leds/leds-lm3556
# Loaded extensions:
#   sphinx.ext.mathjax (2.1.2) from /usr/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /usr/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /usr/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /usr/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /usr/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /usr/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.7/site-packages/alabaster/__init__.py
#   kerneldoc (1.0) from /var/tmp/pamac-build-miranda/linux-next-git/src/linux-next/Documentation/sphinx/kerneldoc.py
#   rstFlatTable (1.0) from /var/tmp/pamac-build-miranda/linux-next-git/src/linux-next/Documentation/sphinx/rstFlatTable.py
#   kernel_include (1.0) from /var/tmp/pamac-build-miranda/linux-next-git/src/linux-next/Documentation/sphinx/kernel_include.py
#   cdomain (1.0) from /var/tmp/pamac-build-miranda/linux-next-git/src/linux-next/Documentation/sphinx/cdomain.py
#   kfigure (1.0.0) from /var/tmp/pamac-build-miranda/linux-next-git/src/linux-next/Documentation/sphinx/kfigure.py
#   sphinx.ext.ifconfig (2.1.2) from /usr/lib/python3.7/site-packages/sphinx/ext/ifconfig.py
#   automarkup (unknown version) from /var/tmp/pamac-build-miranda/linux-next-git/src/linux-next/Documentation/sphinx/automarkup.py
#   sphinx.ext.imgmath (2.1.2) from /usr/lib/python3.7/site-packages/sphinx/ext/imgmath.py
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.7/site-packages/sphinx/application.py", line 345, in build
    self.builder.build_update()
  File "/usr/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 319, in build_update
    len(to_build))
  File "/usr/lib/python3.7/site-packages/sphinx/builders/__init__.py",
```

So there'd been 4 trials from within different kernel modi (custom and generic) and my notebook is fed up with this result. Gonna patch my own kernel, otherwise it won't work, especially with the UFS write support. 

Have fun solving this issue...

**Comment by vanbreukelingen** [comment]
did so... heya, bill is loosing users, now just #3 of (p)richest, if it's going on like this, he's gonna go to hell ASAP - what all of us would appreciate a lot!

Cloned, Xconfigured, compiled and installed special kernel. after 7 abortions and missleading behavior after reboot I through out all of MS hardware support, the Hyper-V module, virtual guest support for M$-fucker and added some new special options like UFS debugging; 

`make xconfig `is a dream for configuring traditionally on arch, everything's fine (even the A207* bluetooth box with the A2DP-fix!), but when releasing PS/2-support, there's no mouse (probably because of z**cat** /proc/....) :-). So just the touchpad, what is meant to be an art p.E. on redshift-widget without 3 button and wheel.

notebook is "fatigue" after a week of steady-compiling, got her at the age of 'round 50 (SALVAGED fsck -y at BSD would say) from the closed bugs and now she starts living and hoping around like my avatar; probably it's never too late for mind changing but the older it gets the harder it becomes.

what will gates get to his retirement age next year from us? probably something for his big ass rundll32; the 'doze kernel from inside is heavy weighted as stone; windoze always suffered adipositas and I think it's gonna explode somehow because of purge-eating. 

it is a ugly war outside the streets because of his win11 and when deleting M$ compatibility in advance  you gonna be lonesome somehow but in fact not having any interface for the ketone-bodies-win-related hw, which is just a stepstone for a healthy and vital life of both, user and admin.
