### ISSUE TITLE
sphinx_autodoc_typehints.py throws an AttributeError in process_signature

### ISSUE THREAD

**Issue by miklasiu** [sphinx-doc/sphinx#6636]
**Describe the bug**
In function process_signature outer = getattr(outer, clsname) fails when inspect.getmodule(obj) returns None:
```
            outer = inspect.getmodule(obj)
            for clsname in obj.__qualname__.split('.')[:-1]:
                outer = getattr(outer, clsname)
```

**To Reproduce**
I have not changed anything in my code regarding affected class - Port but I changed the module in many other places.
```
. ../../py3/bin/activate
SPHINX_APIDOC_OPTIONS=members,show-inheritance ../../py3/bin/sphinx-apidoc -f -M -e -o ./ ../ conf.py
make html

```
**Expected behavior**
Code should not fail if inspect.getmodule() returns None. This as it seems it possible at some cases which I was unfortunate to experience ;) (and it worked just fine yesterday :( )

**Your project**
Doing it at work, not sure how I can share it (part time work) but if needed we can figure something out.

Class that fails:
```
class Port(NamedTuple):
    rack_device: RackDevice
    port: str
    addtnl_port: str = ''

    def __str__(self):
        return "port {port}{addtnl_port} of {dev}".format(
            port=self.port,
            addtnl_port='(%s)' % self.addtnl_port if self.addtnl_port else '',
            dev=str(self.rack_device))
```

**Screenshots**
```
Creating file ./parse_yaml.rst.
Creating file ./pythology.rst.
Creating file ./pythologybase.rst.
Creating file ./telnet.rst.
Creating file ./vr4_db.rst.
Creating file ./hw_support.rst.
Creating file ./hw_support.OS10.rst.
Creating file ./hw_support.OS9.rst.
Creating file ./hw_support.database.rst.
Creating file ./hw_support.server.rst.
Creating file ./modules.rst.
Running Sphinx v2.1.2
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: [] 0 added, 6 changed, 0 removed
reading sources... [ 16%] hw_support.OS10
reading sources... [ 33%] hw_support.OS9
reading sources... [ 50%] hw_support.database
reading sources... [ 66%] hw_support.server
reading sources... [ 83%] parse_yaml
reading sources... [100%] pythologybase

Exception occurred:
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx_autodoc_typehints.py", line 168, in process_signature
    outer = getattr(outer, clsname)
AttributeError: 'NoneType' object has no attribute 'Port'
The full traceback has been saved in /tmp/sphinx-err-j6m9u1dj.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
Process finished with exit code 0
```

**Environment info**
- OS: Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 GNU/Linux
- Python version: 3.6.6
- Sphinx version: 2.1.2
- Sphinx extensions:  'sphinx.ext.autodoc','sphinx.ext.todo','sphinx.ext.mathjax','sphinx.ext.viewcode','sphinx.ext.githubpages','sphinx.ext.napoleon','sphinx_autodoc_typehints'
tools: nothing really

**Additional context**
After following modification I know that for any reason module is not available for that object:
```
            outer = inspect.getmodule(obj)
            if outer is None:
                print('Cannot find module name for %s' % obj)
                outer == obj.__module__
                if outer is None:
                    print('Really cannot find module name for %s' % obj)
                    return signature.format_args().replace('\\', '\\\\'), None
```

I am getting following:
```
Creating file ./parse_yaml.rst.
Creating file ./pythology.rst.
Creating file ./pythologybase.rst.
Creating file ./telnet.rst.
Creating file ./vr4_db.rst.
Creating file ./hw_support.rst.
Creating file ./hw_support.OS10.rst.
Creating file ./hw_support.OS9.rst.
Creating file ./hw_support.database.rst.
Creating file ./hw_support.server.rst.
Creating file ./modules.rst.
Running Sphinx v2.1.2
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 12 source files that are out of date
updating environment: 12 added, 0 changed, 0 removed
reading sources... [  8%] hw_support
reading sources... [ 16%] hw_support.OS10
reading sources... [ 25%] hw_support.OS9
reading sources... [ 33%] hw_support.database
reading sources... [ 41%] hw_support.server
reading sources... [ 50%] index
reading sources... [ 58%] modules
reading sources... [ 66%] parse_yaml
reading sources... [ 75%] pythology
reading sources... [ 83%] pythologybase
Cannot find module name for <function Port.__new__ at 0x7fa83aa12ea0>
Really cannot find module name for <function Port.__new__ at 0x7fa83aa12ea0>
reading sources... [ 91%] telnet
reading sources... [100%] vr4_db

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  8%] hw_support
writing output... [ 16%] hw_support.OS10
writing output... [ 25%] hw_support.OS9
writing output... [ 33%] hw_support.database
writing output... [ 41%] hw_support.server
writing output... [ 50%] index
writing output... [ 58%] modules
writing output... [ 66%] parse_yaml
writing output... [ 75%] pythology
writing output... [ 83%] pythologybase
writing output... [ 91%] telnet
writing output... [100%] vr4_db

generating indices... genindex py-modindex
highlighting module code... [ 10%] hw_support.OS10
highlighting module code... [ 20%] hw_support.OS9
highlighting module code... [ 30%] hw_support.database
highlighting module code... [ 40%] hw_support.server
highlighting module code... [ 50%] namedtuple_Port
highlighting module code... [ 60%] parse_yaml
highlighting module code... [ 70%] pexpect.exceptions
highlighting module code... [ 80%] pythology
highlighting module code... [ 90%] pythologybase
highlighting module code... [100%] telnet

writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

The HTML pages are in html.

Process finished with exit code 0

```
**Sphinx Log File (How to attach a file ?)**
```
cat /tmp/sphinx-err-j6m9u1dj.log
# Sphinx version: 2.1.2
# Python version: 3.6.6 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:
#   reading sources... [ 33%] hw_support.OS9
#   
#   reading sources... [ 50%] hw_support.database
#   
#   reading sources... [ 66%] hw_support.server
#   
#   reading sources... [ 83%] parse_yaml
#   
#   reading sources... [100%] pythologybase
#   
# Loaded extensions:
#   sphinx.ext.mathjax (2.1.2) from /root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (2.1.2) from /root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.todo (2.1.2) from /root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/todo.py
#   sphinx.ext.viewcode (2.1.2) from /root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.githubpages (2.1.2) from /root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/githubpages.py
#   sphinx.ext.napoleon (2.1.2) from /root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx_autodoc_typehints (unknown version) from /root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx_autodoc_typehints.py
#   python_docs_theme (unknown version) from /root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/python_docs_theme/__init__.py
Traceback (most recent call last):
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/application.py", line 345, in build
    self.builder.build_update()
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 319, in build_update
    len(to_build))
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 332, in build
    updated_docnames = set(self.read())
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 438, in read
    self._read_serial(docnames)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 460, in _read_serial
    self.read_doc(docname)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 504, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/io.py", line 325, in read_doc
    pub.publish()
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/io.py", line 113, in read
    self.parse()
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/parsers.py", line 94, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/autodoc/directive.py", line 150, in run
    documenter.generate(more_content=self.content)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 760, in generate
    self.document_members(all_members)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 681, in document_members
    check_module=members_check_module and not isattr)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 1234, in generate
    all_members=all_members)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 760, in generate
    self.document_members(all_members)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 1222, in document_members
    super().document_members(all_members)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 681, in document_members
    check_module=members_check_module and not isattr)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 747, in generate
    sig = self.format_signature()
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 973, in format_signature
    return super().format_signature(**kwargs)  # type: ignore
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 416, in format_signature
    self.object, self.options, args, retann)
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/events.py", line 112, in emit_firstresult
    for result in self.emit(name, *args):
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx/events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "/root/rvr-repo/vr4/trunk/RI/py3/lib/python3.6/site-packages/sphinx_autodoc_typehints.py", line 168, in process_signature
    outer = getattr(outer, clsname)
AttributeError: 'NoneType' object has no attribute 'Port'
```
We are really going to stop running code as root soonish.

**Comment by tapaswenipathak** [comment]
Hi folks: I would be taking a look. Thanks.

**Comment by Syndace** [comment]
I experienced the same issue, also with typing's `NamedTuple`. For now it seems you can manually set `__module__` on `__new__` to circumvent the issue:

```Python
class Foo(typing.NamedTuple):
    ...

Foo.__new__.__module__ = __name__
```

Though I'm not sure if doing this has any other implications.

Edit: sorry for the duplicates, had some connection issues.

**Comment by tk0miya** [comment]
Why did you post this report here? As you titled, this would be a bug of sphinx_autodoc_typehints. Is there anything to do from Sphinx core side?

**Comment by Syndace** [comment]
(I'll assume that this question is directed at @miklasiu, I blindly trusted that this issue was opened on the issue tracker it belongs to)

**Comment by Syndace** [comment]
@miklasiu doesn't seem to be active on GitHub, judging from a look at their profile. So I'm gonna go ahead and say that this is an issue with sphinx_autodoc_typehints, nothing to do for Sphinx core. Feel free to close it.

**Comment by tk0miya** [comment]
Oh, I did not notice this is a too old issue...
@Syndace Thank you for comment.

**Comment by tk0miya** [comment]
I'm closing this now. Please free to reopen if you thought this is a bug of Sphinx-core.
Thanks,
