### ISSUE TITLE
transform.post_transforms.images.DataURIExtractor shouldn't just handle anything that contains `data:`

### ISSUE THREAD

**Issue by blueset** [sphinx-doc/sphinx#6655]
**Describe the bug**
[`transform.post_transforms.images.DataURIExtractor`](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/transforms/post_transforms/images.py#L123) shouldn't just handle anything that contains `"data:"`.

**Slight analysis**

`DataURIExtractor` is using only `'data:' in node['uri']` as an acceptance criteria, while `parse_data_uri` is dropping the URL when it doesn't start with `data:`. 

https://github.com/sphinx-doc/sphinx/blob/86e0dd9a0a3e0ff0b0ddde324bbb6f55539cf878/sphinx/transforms/post_transforms/images.py#L126-L138

https://github.com/sphinx-doc/sphinx/blob/86e0dd9a0a3e0ff0b0ddde324bbb6f55539cf878/sphinx/util/images.py#L80-L82

This creates a discrepancy when the url contains `data:` but doesn't start with one, e.g. `https://img.shields.io/badge/-Telegram-blue.svg?logo=data:image/svg%2Bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI%2BPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTkuNzgsMTguNjVMMTAuMDYsMTQuNDJMMTcuNzQsNy41QzE4LjA4LDcuMTkgMTcuNjcsNy4wNCAxNy4yMiw3LjMxTDcuNzQsMTMuM0wzLjY0LDEyQzIuNzYsMTEuNzUgMi43NSwxMS4xNCAzLjg0LDEwLjdMMTkuODEsNC41NEMyMC41NCw0LjIxIDIxLjI0LDQuNzIgMjAuOTYsNS44NEwxOC4yNCwxOC42NUMxOC4wNSwxOS41NiAxNy41LDE5Ljc4IDE2Ljc0LDE5LjM2TDEyLjYsMTYuM0wxMC42MSwxOC4yM0MxMC4zOCwxOC40NiAxMC4xOSwxOC42NSA5Ljc4LDE4LjY1WiIgLz48L3N2Zz4=` (![Telegram](https://img.shields.io/badge/-Telegram-blue.svg?logo=data:image/svg%2Bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI%2BPHBhdGggZmlsbD0iI2ZmZiIgZD0iTTkuNzgsMTguNjVMMTAuMDYsMTQuNDJMMTcuNzQsNy41QzE4LjA4LDcuMTkgMTcuNjcsNy4wNCAxNy4yMiw3LjMxTDcuNzQsMTMuM0wzLjY0LDEyQzIuNzYsMTEuNzUgMi43NSwxMS4xNCAzLjg0LDEwLjdMMTkuODEsNC41NEMyMC41NCw0LjIxIDIxLjI0LDQuNzIgMjAuOTYsNS44NEwxOC4yNCwxOC42NUMxOC4wNSwxOS41NiAxNy41LDE5Ljc4IDE2Ljc0LDE5LjM2TDEyLjYsMTYuM0wxMC42MSwxOC4yM0MxMC4zOCwxOC40NiAxMC4xOSwxOC42NSA5Ljc4LDE4LjY1WiIgLz48L3N2Zz4=)), which causes the code to break.

**To Reproduce**
```
$ git clone https://gist.github.com/18d95cc19450cac24c5068711cae2a74.git
$ cd 18d95cc19450cac24c5068711cae2a74
$ pip install sphinx sphinx-intl
$ sphinx-build -b gettext . ./locale
```

**Expected behavior**
No error happens

**Your project**
Minimum repro example: https://gist.github.com/blueset/18d95cc19450cac24c5068711cae2a74

**Environment info**
- OS: macOS Mojave 10.14.6
- Python version: 3.7.4
- Sphinx version: 2.1.2
- Sphinx extensions:  sphinx-intl (* probably not an extension)
- Extra tools: N/A

**Additional context**
<details><summary>Console output</summary>

```
Running Sphinx v2.1.2
making output directory... done
building [gettext]: targets for 0 template files
building [gettext]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done

Exception occurred:
  File "/Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinx/transforms/post_transforms/images.py", line 140, in handle
    ext = get_image_extension(image.mimetype)
AttributeError: 'NoneType' object has no attribute 'mimetype'
The full traceback has been saved in /var/folders/fl/nsbwfsl940n4ylvzjz1vz9cc0000gn/T/sphinx-err-v5998nvy.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

</details>

<details><summary>Full log</summary>

```
# Sphinx version: 2.1.2
# Python version: 3.7.4 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.1
# Last messages:
#   
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [100%] index
# Loaded extensions:
#   sphinx.ext.mathjax (2.1.2) from /Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/alabaster/__init__.py
Traceback (most recent call last):
  File "/Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinx/application.py", line 345, in build
    self.builder.build_update()
  File "/Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 319, in build_update
    len(to_build))
  File "/Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinx/builders/gettext.py", line 264, in build
    super().build(docnames, summary, method)
  File "/Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 382, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 562, in write
    self._write_serial(sorted(docnames))
  File "/Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 570, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 554, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 601, in apply_post_transforms
    transformer.apply_transforms()
  File "/Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    super().apply_transforms()
  File "/Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 172, in apply_transforms
    transform.apply(**kwargs)
  File "/Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinx/transforms/post_transforms/images.py", line 40, in apply
    self.handle(node)
  File "/Users/blueset/Codebase/efb-dev-env/lib/python3.7/site-packages/sphinx/transforms/post_transforms/images.py", line 140, in handle
    ext = get_image_extension(image.mimetype)
AttributeError: 'NoneType' object has no attribute 'mimetype'
```

</details>

**Comment by tk0miya** [comment]
Fixed by #6662 .
Thank you for reporting!
