### ISSUE TITLE
Templates broken with 2.2.0

### ISSUE THREAD

**Issue by zbruick** [sphinx-doc/sphinx#6665]
**Describe the bug**
With the update to 2.2.0, the templates for MetPy (https://github.com/Unidata/MetPy) broke, with the module template unable to see an override template. When the name of `module.rst` was updated to `module.rst_t` (following #6492 ), this issue was fixed, allowing the module level documentation to render. However, the class level documentation will not render, whether the template is named `class.rst` or `class.rst_t` (i.e. the links on https://unidata.github.io/MetPy/latest/api/generated/metpy.calc.html#module-metpy.calc are not clickable, and the associated files are empty when docs are built with 2.2.0). 

**Environment info**
- Python version: 3.7.3
- Sphinx version: 2.2.0
- Sphinx extensions:  'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.coverage',
    'sphinx.ext.intersphinx',
    'sphinx.ext.mathjax',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'sphinx_gallery.gen_gallery',
    'matplotlib.sphinxext.plot_directive',
    'm2r'

**Comment by zbruick** [comment]
Here's the traceback of the original error, before updating the module template name to `module.rst_t`:

```
Traceback (most recent call last):
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/site-packages/sphinx/ext/autosummary/generate.py", line 247, in generate_autosummary_docs
    name, obj, parent, mod_name = import_by_name(name)
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/site-packages/sphinx/ext/autosummary/__init__.py", line 599, in import_by_name
    raise ImportError('no module named %s' % ' or '.join(tried))
ImportError: no module named metpy.calc.Apparent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/bin/sphinx-autogen", line 10, in <module>
    sys.exit(main())
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/site-packages/sphinx/ext/autosummary/generate.py", line 450, in main
    app=app)
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/site-packages/sphinx/ext/autosummary/generate.py", line 271, in generate_autosummary_docs
    template_dir=template_dir, app=app)
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/site-packages/sphinx/ext/autosummary/generate.py", line 249, in generate_autosummary_docs
    _warn('[autosummary] failed to import %r: %s' % (name, e))
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/logging/__init__.py", line 1736, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/site-packages/sphinx/util/logging.py", line 124, in log
    super().log(level, msg, *args, **kwargs)
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/logging/__init__.py", line 1768, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/logging/__init__.py", line 1449, in log
    self._log(level, msg, args, **kwargs)
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/logging/__init__.py", line 901, in handle
    rv = self.filter(record)
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/logging/__init__.py", line 762, in filter
    result = f.filter(record)
  File "/Users/zbruick/miniconda3/envs/devel_sphinx22/lib/python3.7/site-packages/sphinx/util/logging.py", line 381, in filter
    self.app._warncount += 1
AttributeError: 'DummyApplication' object has no attribute '_warncount'
make: *** [html] Error 1
```

**Comment by zbruick** [comment]
So this traceback is due to it looking at the section titles found in `overrides/metpy.calc.rst` and erring out when it sees they are not a function. Previously, it only warned that these were not found, but didn't produce a fatal error (with sphinx 2.1.2):

```
[autosummary] generating autosummary for: ./api/generated/metpy.calc.rst, ./api/generated/metpy.constants.rst, ./api/generated/metpy.gridding.rst, ./api/generated/metpy.interpolate.rst, ./api/generated/metpy.io.rst, ./api/generated/metpy.plots.ctables.rst, ./api/generated/metpy.plots.rst, ./api/generated/metpy.units.rst
[autosummary] writing to ./api/generated
WARNING: [autosummary] failed to import 'metpy.calc.Apparent': no module named metpy.calc.Apparent
WARNING: [autosummary] failed to import 'metpy.calc.Boundary': no module named metpy.calc.Boundary
WARNING: [autosummary] failed to import 'metpy.calc.Deprecated': no module named metpy.calc.Deprecated
WARNING: [autosummary] failed to import 'metpy.calc.Dynamic': no module named metpy.calc.Dynamic
WARNING: [autosummary] failed to import 'metpy.calc.Mathematical': no module named metpy.calc.Mathematical
WARNING: [autosummary] failed to import 'metpy.calc.Moist': no module named metpy.calc.Moist
WARNING: [autosummary] failed to import 'metpy.calc.Other': no module named metpy.calc.Other
WARNING: [autosummary] failed to import 'metpy.calc.Soundings': no module named metpy.calc.Soundings
WARNING: [autosummary] failed to import 'metpy.calc.Standard': no module named metpy.calc.Standard
```
So this looks to be a bug introduced by the renaming of the `module.rst` file in #6492?

**Comment by zbruick** [comment]
So this turned out to be a bug on our end. Apologies for opening this issue. In our MetPy.calc.rst file we previously had: 

```
.. automodule:: metpy.calc


   Dry Thermodynamics
   ------------------

   .. autosummary::
      :toctree: ./

      add_height_to_pressure
      add_pressure_to_height
      density
      dry_lapse
      dry_static_energy
      geopotential_to_height
      height_to_geopotential
      mean_pressure_weighted
      potential_temperature
      sigma_to_pressure
      static_stability
      temperature_from_potential_temperature
      thickness_hydrostatic
```

By removing the space before the section header (Dry Thermodynamics), all failures are gone and docs build successfully.
