### ISSUE TITLE
Table of contents works on latexpdf, but fails with html

### ISSUE THREAD

**Issue by oharboe** [sphinx-doc/sphinx#6675]
**Describe the bug**

I'm unsure how to proceed to create an actionable bug-report

```
sphinx-build -M html "source" "build/source/html" -W 
Running Sphinx v2.2.0
[deleted]
reading sources... [100%] index                                                 
/home/oyvind/docs/source/index.rst:9: (WARNING/2) toctree contains reference to nonexisting document ‘aptos/index’ [filtered system message]

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/application.py", line 346, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.6/dist-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/usr/local/lib/python3.6/dist-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/util/logging.py", line 219, in pending_warnings
    memhandler.flushTo(logger)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/util/logging.py", line 184, in flushTo
    logger.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 861, in handle
    rv = self.filter(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 720, in filter
    result = f.filter(record)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/util/logging.py", line 404, in filter
    raise SphinxWarning(location + ":" + message)
sphinx.errors.SphinxWarning: /home/oyvind/docs/source/index.rst:9:toctree contains reference to nonexisting document 'aptos/index'


Warning, treated as error:
/home/oyvind/docs/source/index.rst:9:toctree contains reference to nonexisting document 'aptos/index'
Makefile:37: recipe for target 'html' failed
make: *** [html] Error 2
```

```
sphinx-build -b latex "source" "build/source/latex" -W 
Running Sphinx v2.2.0
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing Aptos.tex... index aptos/index aptos/hello/index [deleted]...
resolving references...
done
[completes successfully]
```

**To Reproduce**

This works on one machine I have Sphinx 2.2.0 installed, but not another. I don't know what the difference is between these two machines.

**Expected behavior**

I would expect Table of Contents to be generated for html when it works for latexpdf.

**Environment info**
- Ubuntu 18.04
- Python version: 3.6.8
- Sphinx version: 2.2.0
- Sphinx extensions:   "sphinx>=2.2.0" "sphinxcontrib-plantuml>=0.17" "sphinxcontrib-nwdiag>=0.9.5" "sphinxcontrib-tikz>=0.4.7" "sphinxcontrib-wavedrom>=2.0.0"
- Extra tools:

**Comment by tkoyama010** [comment]
Thank you for your issue. I have some comment and question. I'm appreciate if you answer it.
-  I think this message you report may help you. Is there a file under ``/home/oyvind/docs/source/aptos`` ?
> toctree contains reference to nonexisting document 'aptos/index'
- All 'Environment info' you report is same in both two machine?
- I want to reproduce this issue in my environment. So If you can, could you share files under doc directory?
Thank you for reading.

**Comment by oharboe** [comment]
@tkoyama010 Thanks for your response. I have since reorganized our document into multiple documents and I no longer experience these problems.

The Environment Info was the same on both machines at the time.
