### ISSUE TITLE
Building reST with sphinx-build got a keyerror

### ISSUE THREAD

**Issue by noisnemid** [sphinx-doc/sphinx#6680]
**Describe the bug**
On MacOS, when trying to build HTML from reST folder of pygame src code, a KeyError occurred

**To Reproduce**
```
<Paste your command-line here which cause the problem>

$ git clone git@github.com:pygame/pygame.git --depth 1
$ cd pygame-master/doc
$ sphinx-build -b html ./reST/ ./pygame_doc_sphinx/

**Expected behavior**
built docs could be seen in the target folder.

**Your project**
none.
[sphinx-err-z__yixpx.log](https://github.com/sphinx-doc/sphinx/files/3563737/sphinx-err-z__yixpx.log)


**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment info**
- OS: Mac OS 10.14.6
- Python version: 3.7.4
- Sphinx version: 2.2.0

**Additional context**
```
```
# Sphinx version: 2.2.0
# Python version: 3.7.4 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.1
# Last messages:
#   reading sources... [ 11%] c_api/freetype
#   reading sources... [ 13%] c_api/mixer
#   reading sources... [ 14%] c_api/rect
#   reading sources... [ 16%] c_api/rwobject
#   reading sources... [ 17%] c_api/surface
#   reading sources... [ 19%] c_api/surflock
#   reading sources... [ 20%] c_api/version
#   reading sources... [ 22%] filepaths
#   reading sources... [ 23%] index
#   reading sources... [ 25%] ref/bufferproxy
# Loaded extensions:
#   sphinx.ext.mathjax (2.2.0) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (2.2.0) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.doctest (2.2.0) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.coverage (2.2.0) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/ext/coverage.py
#   ext.indexer (unknown version) from /Users/ptr/xfolder/on-reading/pygame-master/docs/reST/ext/indexer.py
#   ext.headers (unknown version) from /Users/ptr/xfolder/on-reading/pygame-master/docs/reST/ext/headers.py
#   ext.boilerplate (unknown version) from /Users/ptr/xfolder/on-reading/pygame-master/docs/reST/ext/boilerplate.py
#   ext.customversion (unknown version) from /Users/ptr/xfolder/on-reading/pygame-master/docs/reST/ext/customversion.py
#   ext.edit_on_github (unknown version) from /Users/ptr/xfolder/on-reading/pygame-master/docs/reST/ext/edit_on_github.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/application.py", line 346, in build
    self.builder.build_update()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/io.py", line 326, in read_doc
    pub.publish()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/io.py", line 114, in read
    self.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/parsers.py", line 95, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2346, in explicit_markup
    self.explicit_list(blank_finish)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2376, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2649, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2099, in directive
    directive_class, match, type_name, option_presets)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/domains/__init__.py", line 265, in run
    return super().run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/directives/__init__.py", line 195, in run
    self.state.nested_parse(self.content, self.content_offset, contentnode)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2346, in explicit_markup
    self.explicit_list(blank_finish)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2376, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2649, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2099, in directive
    directive_class, match, type_name, option_presets)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/domains/changeset.py", line 84, in run
    classes = ['versionmodified', versionlabel_classes[self.name]]
KeyError: 'versionextended'

```

- [e.g. URL or Ticket]

**Comment by noisnemid** [comment]
according to the wiki of pygame and the docs of pygame is written under sphinx 1.7 around, and the author of pygame recommended to generate the docs with a similar version to sphinx1.7(e.g, 1.8.5) and generate the docs with command 'python3 setup.py docs', and it really works.
so in fact, it's a version-related thing, which should not be considered as a bug or issue...
