### ISSUE TITLE
KeyError: 'exact-integration-methods'

### ISSUE THREAD

**Issue by tkoyama010** [sphinx-doc/sphinx#6718]
**Describe the bug**
Error occurred when compiling. Error log is following.
```
# Sphinx version: 2.2.0
# Python version: 3.7.3 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.3
# Last messages:
#   ソースを読み込み中...[ 72%] screenshots/stokes-source
#   ソースを読み込み中...[ 72%] screenshots/tripod_source
#   ソースを読み込み中...[ 72%] tutorial/basic_usage
#   ソースを読み込み中...[ 73%] tutorial/index
#   ソースを読み込み中...[ 73%] tutorial/install
#   ソースを読み込み中...[ 73%] tutorial/intro
#   ソースを読み込み中...[ 74%] tutorial/thermo_coupling
#   ソースを読み込み中...[ 74%] tutorial/wheel
#   ソースを読み込み中...[ 74%] userdoc/appendixA
#   ソースを読み込み中...[ 75%] userdoc/appendixB
# Loaded extensions:
#   sphinx.ext.mathjax (2.2.0) from /home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.imgmath (2.2.0) from /home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/ext/imgmath.py
#   sphinx.ext.autodoc (2.2.0) from /home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.coverage (2.2.0) from /home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.doctest (2.2.0) from /home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/ext/doctest.py
Traceback (most recent call last):
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/application.py", line 346, in build
    self.builder.build_update()
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/io.py", line 326, in read_doc
    pub.publish()
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    super().apply_transforms()
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 172, in apply_transforms
    transform.apply(**kwargs)
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/sphinx/transforms/i18n.py", line 186, in apply
    self.document.note_implicit_target(section_node)
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/docutils/nodes.py", line 1405, in note_implicit_target
    self.set_name_id_map(target, id, msgnode, explicit=None)
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/docutils/nodes.py", line 1352, in set_name_id_map
    self.set_duplicate_name_id(node, id, name, msgnode, explicit)
  File "/home/tetsuo/getfem-doc-translations/env/lib/python3.7/site-packages/docutils/nodes.py", line 1389, in set_duplicate_name_id
    old_node = self.ids[old_id]
KeyError: 'exact-integration-methods'
```

**To Reproduce**
Please see Travis config file and log.
https://travis-ci.com/getfem-doc/getfem-doc-translations/builds/130570357#L913-L919
https://travis-ci.com/getfem-doc/getfem-doc-translations/jobs/242516798/config

**Expected behavior**
No error.

**Your project**
https://github.com/getfem-doc/getfem-doc-translations/tree/tkoyama010-patch-2

**Screenshots**
Nothing.

**Environment info**
https://travis-ci.com/getfem-doc/getfem-doc-translations/builds/130570357#L7-L160

**Additional context**
Nothing.

**Comment by tk0miya** [comment]
@tkoyama010 Could you make a minimal reproducible example please? GetFEM is too large to investigate to me. It would be very nice if the error is reproduced with less dependencies and less preparations.

**Comment by tkoyama010** [comment]
@tk0miya Thank you for your comment. OK, please wait.

**Comment by tkoyama010** [comment]
@tk0miya I made a simple example.
https://github.com/getfem-doc/getfem-doc-translations/tree/a8adb191f81607453e6ff0c58ad049406fb3044c
And the building is this.
https://travis-ci.com/getfem-doc/getfem-doc-translations/builds/131648218
When I didn't use -D language=ja option, problem didn't occurre.

**Comment by tk0miya** [comment]
Thank you for quick work!

Reproduced with following Dockerfile.
```
FROM python:3.7-slim

RUN apt update; apt install -y git make
RUN git clone https://github.com/getfem-doc/getfem-doc-translations.git
WORKDIR /getfem-doc-translations
RUN git checkout a8adb191f81607453e6ff0c58ad049406fb3044c
RUN pip install -r requirements.txt
RUN pip install Sphinx
RUN sphinx-build -D language=ja -T . _build/html
```

**Comment by tkoyama010** [comment]
thk
