### ISSUE TITLE
Error installing/loading extension 'chios'

### ISSUE THREAD

**Issue by Edahi** [sphinx-doc/sphinx#6760]
**The extension**
[chios](https://kallimachos.github.io/chios/bolditalic.html)

**The LOG file content**
```
cat /scratch/sphinx-err-7tfz39kz.log
# Sphinx version: 2.1.2
# Python version: 3.7.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/mnt/BioAdHoc/Groups/RaoLab/Edahi/00.Scripts/01.Downloaded/anaconda3/envs/Sphinx/lib/python3.7/site-packages/chios/bolditalic/__init__.py", line 80, in setup
    app.info('adding bolditalic role...', nonl=True)
AttributeError: 'Sphinx' object has no attribute 'info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/BioAdHoc/Groups/RaoLab/Edahi/00.Scripts/01.Downloaded/anaconda3/envs/Sphinx/lib/python3.7/site-packages/sphinx/cmd/build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/mnt/BioAdHoc/Groups/RaoLab/Edahi/00.Scripts/01.Downloaded/anaconda3/envs/Sphinx/lib/python3.7/site-packages/sphinx/application.py", line 235, in __init__
    self.setup_extension(extension)
  File "/mnt/BioAdHoc/Groups/RaoLab/Edahi/00.Scripts/01.Downloaded/anaconda3/envs/Sphinx/lib/python3.7/site-packages/sphinx/application.py", line 394, in setup_extension
    self.registry.load_extension(self, extname)
  File "/mnt/BioAdHoc/Groups/RaoLab/Edahi/00.Scripts/01.Downloaded/anaconda3/envs/Sphinx/lib/python3.7/site-packages/sphinx/registry.py", line 484, in load_extension
    metadata = mod.setup(app)
  File "/mnt/BioAdHoc/Groups/RaoLab/Edahi/00.Scripts/01.Downloaded/anaconda3/envs/Sphinx/lib/python3.7/site-packages/chios/bolditalic/__init__.py", line 85, in setup
    app.warn('Failed to initialize bolditalic styling.')
AttributeError: 'Sphinx' object has no attribute 'warn'
```

**Environment info**
CentOS Linux 7 (Core)
ID_LIKE="rhel fedora"
Python 3.7.3
sphinx 2.1.2

**Describe the bug**
AttributeError: 'Sphinx' object has no attribute 'warn'

**To Reproduce**
Below I pasted my README for the generation of a _conda_ `Sphinx` environment followed by the installation of `chios` since I really wanted to have **_bold italics_** in my Sphinx documentation (seems like there was no other way than adding this extension):

```
conda --version
 # conda 4.7.11
conda create -n Sphinx python sphinx sphinx_rtd_theme 
conda activate Sphinx
sphinx-quickstart
```

All after ">" is the command prompt for Sphinx new documentation configuration.
```
> Root path for the documentation [.]: /mnt/BioAdHoc/Groups/RaoLab/Edahi/Sphinx/ProjectsDocumentation/
> Separate source and build directories (y/n) [n]: n
> Name prefix for templates and static dir [_]: 
> Project name: BiSB - Graduate - PhD - EdahiGA
> Author name(s): Edahi Gonzalez Avalos
> Project version []: 1
> Project release [1]: 1
> Project language [en]: 
> Source file suffix [.rst]: .txt
> Name of your master document (without suffix) [index]: 
> Do you want to use the epub builder (y/n) [n]: 

> autodoc: automatically insert docstrings from modules (y/n) [n]: y
> doctest: automatically test code snippets in doctest blocks (y/n) [n]: y
> intersphinx: link between Sphinx documentation of different projects (y/n) [n]: y
> todo: write "todo" entries that can be shown or hidden on build (y/n) [n]: y
> coverage: checks for documentation coverage (y/n) [n]: y
> imgmath: include math, rendered as PNG or SVG images (y/n) [n]: y
> mathjax: include math, rendered in the browser by MathJax (y/n) [n]: y
imgmath has been deselected.
> ifconfig: conditional inclusion of content based on config values (y/n) [n]: y
> viewcode: include links to the source code of documented Python objects (y/n) [n]: y
> githubpages: create .nojekyll file to publish the document on GitHub pages (y/n) [n]: y
> Create Makefile? (y/n) [y]:  
> Create Windows command file? (y/n) [y]: n
```

**The "It was working until"**
After finished this step, I worked in my webpage and it does work.
I just took this screenshot:

![Screen Shot 2019-10-22 at 9 08 05 PM](https://user-images.githubusercontent.com/22146178/67356785-35a81300-f510-11e9-9495-58fa35df9a3a.png)

Then I wanted to add bold italics, as described before and found the Sphinx extension `chios`. therefore I proceeded to install it in my Sphinx environment:
```
# conda install chios
# ^^^^^^^^^^^^^^^^^^^ Did not work, Trying through conda-forge:
conda config --add channels conda-forge
# conda install chios
# ^^^^^^^^^^^^^^^^^^^ Did not work either, I already had conda-forge. Will try pip it
conda install pip
pip install chios
# ^^^^^^^^^^^^^^^^^^^ Success!
```

Then I added to the conf.py:
```
extensions = ['chios.bolditalic']
```

Modified just one line of my webpage to test the chios' `:bolditalics:` and run the beloved `make html` but I got the 

```
Exception occurred:
  File "/mnt/BioAdHoc/Groups/RaoLab/Edahi/00.Scripts/01.Downloaded/anaconda3/envs/Sphinx/lib/python3.7/site-packages/chios/bolditalic/__init__.py", line 85, in setup
    app.warn('Failed to initialize bolditalic styling.')
AttributeError: 'Sphinx' object has no attribute 'warn'
The full traceback has been saved in /scratch/sphinx-err-7tfz39kz.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

**Thank you**

**Comment by tk0miya** [comment]
>AttributeError: 'Sphinx' object has no attribute 'warn'

The `Sphinx.warn()` method was deprecated at Sphinx-1.6 and removed at 1.8.
So chios extension should be updated to use new `sphinx.util.logging` module.
Please report this to authors.
Thanks,
