### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by inBrackets** [sphinx-doc/sphinx#6819]
This error occurs during building html (make html) after adding the "sphinxcontrib.jsoncall" extension
```
# Sphinx version: 2.2.1
# Python version: 3.7.5 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "c:\users\hp\envs\sphinx\lib\site-packages\sphinx\cmd\build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "c:\users\hp\envs\sphinx\lib\site-packages\sphinx\application.py", line 236, in __init__
    self.setup_extension(extension)
  File "c:\users\hp\envs\sphinx\lib\site-packages\sphinx\application.py", line 395, in setup_extension
    self.registry.load_extension(self, extname)
  File "c:\users\hp\envs\sphinx\lib\site-packages\sphinx\registry.py", line 475, in load_extension
    mod = import_module(extname)
  File "c:\users\hp\envs\sphinx\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\hp\envs\sphinx\lib\site-packages\sphinxcontrib\jsoncall\__init__.py", line 100
    app.add_stylesheet('jsoncall.css')
```

**Comment by inBrackets** [comment]
Forked and fixed on https://github.com/imponderabiliait/sphinxcontrib.jsoncall
BTW, updated to python 3.6

**Comment by tk0miya** [comment]
It seems a bug of jsconcall extension. Is there anything we can do for it?

**Comment by tk0miya** [comment]
I'm closing this because of not a bug of Sphinx.
Thanks,
