### ISSUE TITLE
syntax error when running sphinx-build -b pdf source build/pdf

### ISSUE THREAD

**Issue by drfeinberg** [sphinx-doc/sphinx#6828]
**Describe the bug**
syntax error when running sphinx-build -b pdf source build/pdf

**To Reproduce**

```
(base) david@david-Galago-Pro:~/work/voicelab-gui/voicelab/sphynx$ cat /tmp/sphinx-err-_w6v7pqk.log
# Sphinx version: 1.8.5
# Python version: 3.7.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/david/anaconda3/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/david/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/david/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/david/anaconda3/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/david/anaconda3/lib/python3.7/site-packages/rst2pdf/pdfbuilder.py", line 129
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by tk0miya** [comment]
This is caused by rst2pdf extension you added. Unfortunately it still does not support python3.
Thanks,
