### ISSUE TITLE
TypeError("argument of type 'NoneType' is not iterable") after upgrade to newer version

### ISSUE THREAD

**Issue by martin-ueding** [sphinx-doc/sphinx#6847]
**Describe the bug**

I upgraded my system to Fedora 31 where they bumped various versions and also made `python` start version 3 by default now. I tried to recompile my website which is a Sphinx project with a little extra Python code added to it as well as a custom theme. It has been building just fine with the older version.

**To Reproduce**

I just compile my website with this:

```
PYTHONPATH=. /usr/bin/sphinx-build -b html . _build/html
```

The error that I face is this one:

```
writing output... [ 33%] articles/lagrange-examples/ball-in-cone/index                                                 
Theme error:
An error happened in rendering the page articles/lagrange-examples/ball-in-cone/index.
Reason: TypeError("argument of type 'NoneType' is not iterable")
make: *** [Makefile:54: T-sphinx-html] Fehler 2
```

That particular document looks very benign to me, though. And I haven't changed it in quite a while.

```rst
.. Copyright © 2013-2014, 2016-2017 Martin Ueding <dev@martin-ueding.de>

############
Ball in Cone
############

The System
==========

A ball rolls within a circular cone. Friction and the moment of inertia of the
ball is neglected completely. You can think of the ball as a point mass.

.. figure:: fbd.png

    Diagram of the ball in a cone

Animation
=========

.. raw:: html

    <div id="holder"></div>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.0.0.min.js"></script>
    <script type="text/javascript" src="https://martin-ueding.de/apps/lagrange-simulator/raphael-min.js"></script>
    <script type="text/javascript" src="https://martin-ueding.de/apps/lagrange-simulator/animation.js"></script>
    <script type="text/javascript">start(ball_in_cone);</script>

Derivation
==========

Kinetic and potential energy:

.. math::

    T = \frac m2 \cdot (\dot r^2 + r^2 \dot\phi^2 + \dot z^2)

    V = mgz

Holonomic constraint:

.. math::

    r - z \tan(\alpha) = 0

To increase readability, I will use :math:`\beta := \tan(\alpha)`.

I put that constraint into the energies and yield a Lagrangian without
:math:`r`:

.. math::

    L = \frac m2 \cdot \left((\beta^2 + 1) \dot z^2 + \beta^2 z^2 \dot\phi^2 \right) - mgz

Euler Lagrange equation:

.. math::

    \frac{\partial L}{\partial z} = \frac{\mathrm d}{\mathrm dt} \frac{\partial L}{\partial \dot z}

    \frac{\partial L}{\partial z}
    = m \beta^2 z \dot\phi^2 - mg

    \frac{\mathrm d}{\mathrm dt} \frac{\partial L}{\partial \dot z}
    = \frac{\mathrm d}{\mathrm dt} m \cdot (\beta^2 + 1) \dot z
    = m \cdot (\beta^2 + 1) \ddot z

    m \beta^2 z \dot\phi^2 - mg
    = m \cdot (\beta^2 + 1) \ddot z

    \frac{\partial L}{\partial \phi} = \frac{\mathrm d}{\mathrm dt} \frac{\partial L}{\partial \dot\phi}

    \frac{\partial L}{\partial \phi} = 0

    \frac{\mathrm d}{\mathrm dt} \frac{\partial L}{\partial \dot\phi}
    = \frac{\mathrm d}{\mathrm dt} m \beta^2 z^2 \dot\phi
    = m \beta^2 \cdot (2 z \dot z \dot\phi + z^2 \ddot\phi)

    0 = m \beta^2 \cdot (2 z \dot z \dot\phi + z^2 \ddot\phi)

Bring it into the form of :math:`y' = f(y)`:

.. math::

    \ddot z = \frac{\beta^2 z \dot\phi^2 - g}{\beta^2 + 1}

    \ddot \phi = - 2 \frac{\dot z}{z}

The input for the ODE solver is:

.. math::

    \frac{\mathrm d}{\mathrm dt}
    \begin{pmatrix}
    z \\ \phi \\ \dot z \\ \dot \phi
    \end{pmatrix}
    =
    \begin{pmatrix}
    \dot z \\ \dot \phi \\
    \frac{\beta^2 z \dot\phi^2 - g}{\beta^2 + 1} \\
    - 2 \frac{\dot z}{z}
    \end{pmatrix}
```

**Environment info**

- OS: Fedora 31
- Python version: 3.7.5
- Sphinx version: 2.1.2

**Comment by martin-ueding** [comment]
Running with the `-T` option shows that it happens in my theme:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sphinx/builders/html.py", line 1090, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/usr/lib/python3.7/site-packages/sphinx/jinja2glue.py", line 207, in render
    return self.environment.get_template(template).render(context)
  File "/usr/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/home/mu/Projekte/eigene-webseite/_themes/mu/layout.html", line 115, in top-level template code
    <body lang="{{ meta.lang if 'lang' in meta else 'en' }}">
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.7/site-packages/sphinx/application.py", line 345, in build
    self.builder.build_update()
  File "/usr/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 319, in build_update
    len(to_build))
  File "/usr/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 382, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 562, in write
    self._write_serial(sorted(docnames))
  File "/usr/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 573, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/lib/python3.7/site-packages/sphinx/builders/html.py", line 650, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/usr/lib/python3.7/site-packages/sphinx/builders/html.py", line 1098, in handle_page
    (pagename, exc))
sphinx.errors.ThemeError: An error happened in rendering the page articles/lagrange-examples/ball-in-cone/index.
Reason: TypeError("argument of type 'NoneType' is not iterable")

Theme error:
An error happened in rendering the page articles/lagrange-examples/ball-in-cone/index.
Reason: TypeError("argument of type 'NoneType' is not iterable")
```

There was apparently a breaking change that made the `meta` in the template not be an empty dictionary in case there are no entries but instead a `None`. So I needed to fix my template:

```diff
-                {% if 'date' in meta %}
+                {% if meta is not none and 'date' in meta %}
```

With that it seems to work fine again.
