### ISSUE TITLE
Unidentified error

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#689]
Traceback said to report the error, so I am. It's probably user error, but I can't track down what it is.

```
#!python

# Sphinx version: 1.0.7
# Python version: 2.6.6
# Docutils version: 0.7 release
# Jinja2 version: 2.5.5
Traceback (most recent call last):
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/sphinx/cmdline.py", line 188, in main
    app.build(force_all, filenames)
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/sphinx/application.py", line 207, in build
    self.builder.build_update()
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/sphinx/builders/__init__.py", line 198, in build_update
    'out of date' &#37; len(to_build))
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/sphinx/builders/__init__.py", line 254, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/sphinx/builders/__init__.py", line 294, in write
    self.write_doc(docname, doctree)
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/sphinx/builders/html.py", line 408, in write_doc
    self.docwriter.write(doctree, destination)
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/docutils/writers/__init__.py", line 76, in write
    self.translate()
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/sphinx/writers/html.py", line 38, in translate
    self.document.walkabout(visitor)
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/docutils/nodes.py", line 165, in walkabout
    visitor.dispatch_visit(self)
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/docutils/nodes.py", line 1601, in dispatch_visit
    return method(node)
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/sphinx/writers/html.py", line 533, in visit_literal_block
    HTMLTranslator.visit_literal_block(self, node)
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/sphinx/writers/html.py", line 238, in visit_literal_block
    node.rawsource, lang, linenos, warn=warner)
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/sphinx/highlighting.py", line 190, in highlight_block
    if self.try_parse(source):
  File "/Users/gtaylor/.virtualenvs/ligonier/lib/python2.6/site-packages/sphinx/highlighting.py", line 171, in try_parse
    parser.suite(src)
AttributeError: 'module' object has no attribute 'suite'
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/689
- Originally reported by: Greg Taylor
- Originally created at: 2011-04-30T04:24:10.615

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-05-15 09:44:41+00:00_

I would assume that you have a module called "parser" somewhere on your PYTHONPATH.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-10-18 07:32:18+00:00_

Removing version: 1.0.7 (automated comment)
