### ISSUE TITLE
htmlhelp builder exception

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#69]
Traceback (most recent call last):
  File "/space/sphinx/sphinx/cmdline.py", line 151, in main
    app.build(all_files, filenames)
  File "/space/sphinx/sphinx/application.py", line 143, in build
    self.builder.build_update()
  File "/space/sphinx/sphinx/builders/**init**.py", line 225, in build_update
    'out of date' &#37; len(to_build))
  File "/space/sphinx/sphinx/builders/**init**.py", line 268, in build
    self.finish()
  File "/space/sphinx/sphinx/builders/html.py", line 388, in finish
    self.handle_finish()
  File "/space/sphinx/sphinx/builders/htmlhelp.py", line 143, in handle_finish
    self.build_hhx(self, self.outdir, self.config.htmlhelp_basename)
TypeError: build_hhx() takes exactly 3 arguments (4 given)

Removing the first self in the call fixes it

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/69
- Originally reported by: Anonymous
- Originally created at: 2008-12-05T11:24:29.813

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2008-12-05 11:27:47+00:00_

Changeset <<cset c7dff98745133cf802fb67980da44e8d610785c4>>:

Fix #69: a "self" too much.
