### ISSUE TITLE
<what happen when you do on which document project>

### ISSUE THREAD

**Issue by rrahn** [sphinx-doc/sphinx#6912]
**Describe the bug**
I am trying to build a project with the latest sphinx package using python3 virtual environment.
But when executing it, it raises an exception within the sphinx sources complaining about an invalid syntax.
```
(env3) developer@a9648bc035b7:~$ sphinx-build -W -n -b html -d build/doctrees/ seqan/manual/source build/html
Running Sphinx v2.2.2

Exception occurred:
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/developer/manual-venv/lib/python3.6/site-packages/seqansphinx/includefrags.py", line 111
    except ValueError, err:
                     ^
SyntaxError: invalid syntax
The full traceback has been saved in /tmp/sphinx-err-dznlkolw.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**To Reproduce**
```
$ virtualenv -p python3 env3
$ . env3/bin/activate
$ git clone -b develop https://github.com/seqan/seqan.git
$ pip install -r seqan/manual/requirements.txt
$ mkdir build
$ phinx-build -W -n -b html -d build/doctrees/ seqan/manual/source build/html 
```

**Expected behavior**
The build runs through without errors and the html files are generated in the destination folder

**Your project**
https://github.com/seqan/seqan

**Environment info**
- OS: Linux a9648bc035b7 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Python version: 3.6.9
- Sphinx version: 2.2.2
- Sphinx extensions:  -
- Extra tools: -

**Additional context**

error log:
```
# Sphinx version: 2.2.2
# Python version: 3.6.9 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/developer/manual-venv/lib/python3.6/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/developer/manual-venv/lib/python3.6/site-packages/sphinx/application.py", line 243, in __init__
    self.setup_extension(extension)
  File "/home/developer/manual-venv/lib/python3.6/site-packages/sphinx/application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/developer/manual-venv/lib/python3.6/site-packages/sphinx/registry.py", line 475, in load_extension
    mod = import_module(extname)
  File "/home/developer/manual-venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/developer/manual-venv/lib/python3.6/site-packages/seqansphinx/includefrags.py", line 111
    except ValueError, err:
                     ^
SyntaxError: invalid syntax
```

**Comment by tk0miya** [comment]
Same as #6913. Closing.

**Comment by rrahn** [comment]
> Same as #6913. Closing.

Sorry, I messed this accidently up by going back in the browser instead of just editing the header. Thanks for closing this.
