### ISSUE TITLE
Error''Sphinx' object has no attribute 'add_js_file'' when building doc in readthedocs

### ISSUE THREAD

**Issue by CodingCattwo** [sphinx-doc/sphinx#7026]
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/webasedoc/envs/latest/lib/python3.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/webasedoc/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 196, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/webasedoc/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/webasedoc/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 207, in load_extension
    metadata = mod.setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/webasedoc/envs/latest/lib/python3.7/site-packages/sphinx_copybutton/__init__.py", line 25, in setup
    app.add_js_file('clipboard.min.js')
AttributeError: 'Sphinx' object has no attribute 'add_js_file'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/webasedoc/envs/latest/lib/python3.7/site-packages/sphinx_copybutton/__init__.py", line 25, in setup
    app.add_js_file('clipboard.min.js')
AttributeError: 'Sphinx' object has no attribute 'add_js_file'
```

**Comment by CodingCattwo** [comment]
My doc's repository is [WeBASE-Doc](https://github.com/WeBankFinTech/WeBASE-Doc)

**Comment by tk0miya** [comment]
It seems you've been used Sphinx-1.6.7. But `add_js_file` was added since 1.8. So please upgrade your Sphinx.
https://readthedocs.org/projects/webasedoc/builds/10269740/
https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_js_file

Thanks,
