### ISSUE TITLE
Error on latex output

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#731]
When I use: sphinx-build -b latex doc/ doc/_build/ raise an exception:
Exception occurred:
  File "/usr/lib/python2.7/site-packages/sphinx/writers/latex.py", line 193, in __init__
    babel = ExtBabel(builder.config.language)
TypeError: **init**() takes exactly 3 arguments (2 given)

Works fine for html or devhelp outputs.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/731
- Originally reported by: Anonymous
- Originally created at: 2011-07-13T21:01:56.978

**Comment by shimizukawa** [comment]
_From Anonymous on 2011-07-13 19:04:42+00:00_

Sphinx log:

# Sphinx version: 1.0.7

# Python version: 2.7.1

# Docutils version: 0.8 repository

# Jinja2 version: 2.5.5

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 188, in main
    app.build(force_all, filenames)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 207, in build
    self.builder.build_update()
  File "/usr/lib/python2.7/site-packages/sphinx/builders/**init**.py", line 193, in build_update
    self.build(['**all**'], to_build)
  File "/usr/lib/python2.7/site-packages/sphinx/builders/**init**.py", line 254, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python2.7/site-packages/sphinx/builders/latex.py", line 104, in write
    docwriter.write(doctree, destination)
  File "/usr/lib/python2.7/site-packages/docutils/writers/**init**.py", line 77, in write
    self.translate()
  File "/usr/lib/python2.7/site-packages/sphinx/writers/latex.py", line 91, in translate
    visitor = LaTeXTranslator(self.document, self.builder)
  File "/usr/lib/python2.7/site-packages/sphinx/writers/latex.py", line 193, in **init**
    babel = ExtBabel(builder.config.language)
TypeError: **init**() takes exactly 3 arguments (2 given)

**Comment by shimizukawa** [comment]
_From Akitoshi Ohta on 2011-07-14 02:16:55+00:00_

This Error occured my enviroment with "Docutils version: 0.8".

Works fine for "Docutils version: 0.7".

**Comment by shimizukawa** [comment]
_From Anonymous on 2011-07-14 16:17:49+00:00_

This error occured when option language is set to any value. If I remove or comment this option, then PDF or latex output works again.

**Comment by shimizukawa** [comment]
_From engelbert gruber on 2011-07-22 09:44:57+00:00_

possible fix

{{{

 --- a/sphinx/writers/latex.py  Thu Jul 14 16:57:01 2011 +0200
+++ b/sphinx/writers/latex.py   Fri Jul 22 11:20:18 2011 +0200
@@ -97,6 +97,9 @@

--- a/sphinx/writers/latex.py   Thu Jul 14 16:57:01 2011 +0200
+++ b/sphinx/writers/latex.py   Fri Jul 22 11:43:29 2011 +0200
@@ -95,8 +95,18 @@

 # Helper classes
+class Reporter:
-    """Miniature docutils reporter dummy for class Babel."""
-    def warning(self, msg):
- ```
     sys.stderr.write(msg)
  ```
  
  class ExtBabel(Babel):
-    def **init**(self, language_code):
-        try:
-            Babel.**init**(self, language_code)
-        except TypeError:
-            Babel.**init**(self, language_code, Reporter())
  +
   def get_shorthandoff(self):
       shortlang = self.language.split('_')[0]
       if shortlang in ('de', 'sl', 'pt', 'es', 'nl', 'pl', 'it'):

}}}

and 

{{{

--- docutils/writers/latex2e/**init**.py    (revision 7097)
+++ docutils/writers/latex2e/**init**.py    (working copy)
@@ -411,8 +411,11 @@
                 t += self.next_quote() + part
         return t
-    def get_language(self, language_code):
-        """Return TeX language name for `language_code`"""
-    def get_language(self, language_code=None):
-        """Return TeX language name for `language_code`
-        else the language name from initialization."""
-        if not language_code:
-            return self.language
       for tag in utils.normalize_language_tag(language_code):
           try:
               language = self.language_codes[tag]

}}}

**Comment by shimizukawa** [comment]
_From engelbert gruber on 2011-08-30 09:08:38+00:00_

fixxed in docutils 0.8.1 release
