### ISSUE TITLE
Sphinx-autobuild fails on Python 3.8, on Windows

### ISSUE THREAD

**Issue by Peilonrayz** [sphinx-doc/sphinx#7310]
The source of the issue is better described on this [tornado issue](https://github.com/tornadoweb/tornado/issues/2608), in short 3.8 is making proactor the default asyncio event loop on Windows.

**To Reproduce**

-   Load Windows
-   Install Python 3.8
-   ```shell
    $ pip list
    Sphinx                        2.4.4
    $ cd docs
    $ sphinx-autobulid
    Traceback (most recent call last):
      ...
      File "C:\Program Files\Python\3.8.0\Lib\asyncio\events.py", line 501, in add_reader 
        raise NotImplementedError
    NotImplementedError
    ```

I can provide more complete reproducible instructions if needed.

**Comment by tk0miya** [comment]
Could you paste a full traceback please? In addition, could you check that is the error raised also on using only sphinx-build?

**Comment by Peilonrayz** [comment]
This error is not raised in sphinx-build.

<details>
  <summary>Full traceback</summary>
  
  ```
  nox > sphinx-autobuild --open-browser -b html -W -d _build/doctrees . _build/html     
  
  +--------- manually triggered build ---------------------------------------------
  | Running Sphinx v2.4.4
  | building [mo]: targets for 0 po files that are out of date
  | building [html]: targets for 6 source files that are out of date
  | updating environment: [new config] 6 added, 0 changed, 0 removed
  f:\peilonrayz\nox\.nox\docs\lib\site-packages\recommonmark\parser.py:75: UserWarning: 
  Container node skipped: type=document
    warn("Container node skipped: type={0}".format(mdnode.t))
  | reading sources... [ 16%] CHANGELOG
  | reading sources... [ 33%] CONTRIBUTING
  | reading sources... [ 50%] config
  | reading sources... [ 66%] index
  | reading sources... [ 83%] tutorial
  | reading sources... [100%] usage
  | 
  | looking for now-outdated files... none found
  | pickling environment... done
  | checking consistency... done
  | preparing documents... done
  | writing output... [ 16%] CHANGELOG
  | writing output... [ 33%] CONTRIBUTING
  | writing output... [ 50%] config
  | writing output... [ 66%] index
  | writing output... [ 83%] tutorial
  | writing output... [100%] usage
  | 
  
  Warning, treated as error:
  F:\Peilonrayz\nox\docs\index.rst:4:toctree contains reference to document 'CONTRIBUTING' that doesn't have a title: no link will be generated
  +--------------------------------------------------------------------------------
  
  [I 200315 02:30:42 server:296] Serving on http://127.0.0.1:8000
  Traceback (most recent call last):
    File "c:\program files\python\3.8.0\lib\runpy.py", line 192, in _run_module_as_main 
      return _run_code(code, main_globals, None,
    File "c:\program files\python\3.8.0\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "F:\Peilonrayz\nox\.nox\docs\Scripts\sphinx-autobuild.EXE\__main__.py", line 7, in <module>
    File "f:\peilonrayz\nox\.nox\docs\lib\site-packages\sphinx_autobuild\__init__.py", line 315, in main
      server.serve(port=portn, host=args.host,
    File "f:\peilonrayz\nox\.nox\docs\lib\site-packages\livereload\server.py", line 298, in serve
      self.application(
    File "f:\peilonrayz\nox\.nox\docs\lib\site-packages\livereload\server.py", line 253, in application
      app.listen(port, address=host)
    File "f:\peilonrayz\nox\.nox\docs\lib\site-packages\tornado\web.py", line 2116, in listen
      server.listen(port, address)
    File "f:\peilonrayz\nox\.nox\docs\lib\site-packages\tornado\tcpserver.py", line 152, in listen
      self.add_sockets(sockets)
    File "f:\peilonrayz\nox\.nox\docs\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
      self._handlers[sock.fileno()] = add_accept_handler(
    File "f:\peilonrayz\nox\.nox\docs\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
      io_loop.add_handler(sock, accept_handler, IOLoop.READ)
    File "f:\peilonrayz\nox\.nox\docs\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
      self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
    File "c:\program files\python\3.8.0\lib\asyncio\events.py", line 501, in add_reader 
      raise NotImplementedError
  NotImplementedError
  ```
</details>

**Comment by tk0miya** [comment]
It means this is a bug of sphinx-autobuild, right? This is an issue list for Sphinx core, not autobuild.
Please report this to their project.
Thanks,
