### ISSUE TITLE
Image inclusion (svg) fails with "invalid literal for int()" error (html build)

### ISSUE THREAD

**Issue by tschinz** [sphinx-doc/sphinx#7357]
Since I upgraded the sphinx package from v2.3.1 to 2.4.0 - 2.4.4 my build fails. When I revert back to 2.3.1 all is fine again.
```
Exception occurred:
  File "C:\Users\zas\anaconda3\lib\site-packages\sphinx\writers\html5.py", line 548, in visit_image
    atts['width'] = int(atts['width']) * scale
ValueError: invalid literal for int() with base 10: '100px'
```

The images are mainly `.svg` files but `.png` and `.jpg` too

**To Reproduce**
Insert image with the astrerix (for taking svg in html and jpg for latex
```
.. figure:: /img/logo.*
    :align: left
    :width: 100px
```

**Full Log**
```
# Sphinx version: 2.4.0
# Python version: 3.7.6 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.1
# Last messages:
#   writing output... [ 94%] writing/emoji/curated
#   writing output... [ 94%] writing/emoji/index
#   writing output... [ 95%] writing/gitbook/index
#   writing output... [ 95%] writing/gitbook/intro
#   writing output... [ 96%] writing/latex/index
#   writing output... [ 96%] writing/latex/install
#   writing output... [ 97%] writing/latex/intro
#   writing output... [ 97%] writing/md/index
#   writing output... [ 98%] writing/md/md_github
#   writing output... [ 98%] writing/rst/cheatsheet
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.0) from C:\Users\zas\anaconda3\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from C:\Users\zas\anaconda3\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.2) from C:\Users\zas\anaconda3\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from C:\Users\zas\anaconda3\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from C:\Users\zas\anaconda3\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.3) from C:\Users\zas\anaconda3\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from C:\Users\zas\anaconda3\lib\site-packages\alabaster\__init__.py
#   sphinxcontrib.wavedrom (unknown version) from C:\Users\zas\anaconda3\lib\site-packages\sphinxcontrib\wavedrom.py
#   sphinxcontrib.plantuml (unknown version) from C:\Users\zas\anaconda3\lib\site-packages\sphinxcontrib\plantuml.py
#   recommonmark (0.6.0) from C:\Users\zas\anaconda3\lib\site-packages\recommonmark\__init__.py
#   sphinx.ext.graphviz (2.4.0) from C:\Users\zas\anaconda3\lib\site-packages\sphinx\ext\graphviz.py
#   sphinx.ext.ifconfig (2.4.0) from C:\Users\zas\anaconda3\lib\site-packages\sphinx\ext\ifconfig.py
#   sphinx.ext.todo (2.4.0) from C:\Users\zas\anaconda3\lib\site-packages\sphinx\ext\todo.py
#   sphinx.ext.extlinks (2.4.0) from C:\Users\zas\anaconda3\lib\site-packages\sphinx\ext\extlinks.py
#   sphinx.ext.githubpages (2.4.0) from C:\Users\zas\anaconda3\lib\site-packages\sphinx\ext\githubpages.py
#   sphinxemoji.sphinxemoji (0.1.4) from C:\Users\zas\anaconda3\lib\site-packages\sphinxemoji\sphinxemoji.py
#   sphinx_copybutton (0.2.10) from C:\Users\zas\anaconda3\lib\site-packages\sphinx_copybutton\__init__.py
Traceback (most recent call last):
  File "C:\Users\zas\anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "C:\Users\zas\anaconda3\lib\site-packages\sphinx\application.py", line 349, in build
    self.builder.build_update()
  File "C:\Users\zas\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 299, in build_update
    len(to_build))
  File "C:\Users\zas\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "C:\Users\zas\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 535, in write
    self._write_serial(sorted(docnames))
  File "C:\Users\zas\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 545, in _write_serial
    self.write_doc(docname, doctree)
  File "C:\Users\zas\anaconda3\lib\site-packages\sphinx\builders\html.py", line 612, in write_doc
    self.docwriter.write(doctree, destination)
  File "C:\Users\zas\anaconda3\lib\site-packages\docutils\writers\__init__.py", line 78, in write
    self.translate()
  File "C:\Users\zas\anaconda3\lib\site-packages\sphinx\writers\html.py", line 58, in translate
    self.document.walkabout(visitor)
  File "C:\Users\zas\anaconda3\lib\site-packages\docutils\nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "C:\Users\zas\anaconda3\lib\site-packages\docutils\nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "C:\Users\zas\anaconda3\lib\site-packages\docutils\nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 3 more times]
  File "C:\Users\zas\anaconda3\lib\site-packages\docutils\nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "C:\Users\zas\anaconda3\lib\site-packages\sphinx\util\docutils.py", line 484, in dispatch_visit
    return method(node)
  File "C:\Users\zas\anaconda3\lib\site-packages\sphinx\writers\html5.py", line 548, in visit_image
    atts['width'] = int(atts['width']) * scale
ValueError: invalid literal for int() with base 10: '100px' 
```

I tried all 2.4.x version of sphinx without any luck

**Comment by tk0miya** [comment]
Sorry for the inconvenience. It seems this bug happens when 1) embedding a SVG image and 2) give `width` and `scale` options. I'll try to fix it.
