### ISSUE TITLE
docutils/nodes.py error

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#737]
Hello! I use sphinx to generate docs for my project, OpenColorIO, and I recently have run into an issue building docs.  My apologies if this is a repost, or if the bug has already been fixed. (im a sphinx newbie).

```
reading sources... [ 20&#37;] developers/api/OpenColorTransforms
Exception occurred:
  File "/usr/lib64/python2.6/site-packages/docutils/nodes.py", line 1778, in dupname
    node['names'].remove(name)
ValueError: list.remove(x): x not in list

# Sphinx version: 1.1pre
# Python version: 2.6.4
# Docutils version: 0.5 release
# Jinja2 version: 2.5.5

Traceback (most recent call last):
  File "/net/homedirs/jeremys/git/ocio.spi.pages/build/ext/dist/lib/python2.6/site-packages/Sphinx-1.1predev_20110726-py2.6.egg/sphinx/cmdline.py", line 173, in main
    app.build(force_all, filenames)
  File "/net/homedirs/jeremys/git/ocio.spi.pages/build/ext/dist/lib/python2.6/site-packages/Sphinx-1.1predev_20110726-py2.6.egg/sphinx/application.py", line 203, in build
    self.builder.build_update()
  File "/net/homedirs/jeremys/git/ocio.spi.pages/build/ext/dist/lib/python2.6/site-packages/Sphinx-1.1predev_20110726-py2.6.egg/sphinx/builders/__init__.py", line 193, in build_update
    'out of date' &#37; len(to_build))
  File "/net/homedirs/jeremys/git/ocio.spi.pages/build/ext/dist/lib/python2.6/site-packages/Sphinx-1.1predev_20110726-py2.6.egg/sphinx/builders/__init__.py", line 213, in build
    purple, length):
  File "/net/homedirs/jeremys/git/ocio.spi.pages/build/ext/dist/lib/python2.6/site-packages/Sphinx-1.1predev_20110726-py2.6.egg/sphinx/builders/__init__.py", line 117, in status_iterator
    for item in iterable:
  File "/net/homedirs/jeremys/git/ocio.spi.pages/build/ext/dist/lib/python2.6/site-packages/Sphinx-1.1predev_20110726-py2.6.egg/sphinx/environment.py", line 571, in update_generator
    self.read_doc(docname, app=app)
  File "/net/homedirs/jeremys/git/ocio.spi.pages/build/ext/dist/lib/python2.6/site-packages/Sphinx-1.1predev_20110726-py2.6.egg/sphinx/environment.py", line 713, in read_doc
    pub.publish()
  File "/usr/lib64/python2.6/site-packages/docutils/core.py", line 204, in publish
    self.settings)
  File "/usr/lib64/python2.6/site-packages/docutils/readers/__init__.py", line 69, in read
    self.parse()
  File "/usr/lib64/python2.6/site-packages/docutils/readers/__init__.py", line 75, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/__init__.py", line 157, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/usr/lib64/python2.6/site-packages/docutils/statemachine.py", line 232, in run
    context, state, transitions)
  File "/usr/lib64/python2.6/site-packages/docutils/statemachine.py", line 420, in check_line
    return method(match, context, next_state)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/states.py", line 2658, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/states.py", line 308, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/states.py", line 376, in new_subsection
    node=section_node, match_titles=1)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/states.py", line 266, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib64/python2.6/site-packages/docutils/statemachine.py", line 232, in run
    context, state, transitions)
  File "/usr/lib64/python2.6/site-packages/docutils/statemachine.py", line 420, in check_line
    return method(match, context, next_state)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/states.py", line 2241, in explicit_markup
    self.explicit_list(blank_finish)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/states.py", line 2269, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/states.py", line 300, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib64/python2.6/site-packages/docutils/statemachine.py", line 232, in run
    context, state, transitions)
  File "/usr/lib64/python2.6/site-packages/docutils/statemachine.py", line 420, in check_line
    return method(match, context, next_state)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/states.py", line 2542, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/states.py", line 2251, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/states.py", line 1994, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/lib64/python2.6/site-packages/docutils/parsers/rst/states.py", line 2043, in run_directive
    result = directive_instance.run()
  File "/net/homedirs/jeremys/git/ocio.spi.pages/build/ext/dist/lib/python2.6/site-packages/Sphinx-1.1predev_20110726-py2.6.egg/sphinx/domains/__init__.py", line 188, in run
    return BaseDirective.run(self)
  File "/net/homedirs/jeremys/git/ocio.spi.pages/build/ext/dist/lib/python2.6/site-packages/Sphinx-1.1predev_20110726-py2.6.egg/sphinx/directives/__init__.py", line 156, in run
    self.add_target_and_index(name, sig, signode)
  File "/net/homedirs/jeremys/git/ocio.spi.pages/build/ext/dist/lib/python2.6/site-packages/Sphinx-1.1predev_20110726-py2.6.egg/sphinx/domains/cpp.py", line 848, in add_target_and_index
    self.state.document.note_explicit_target(signode)
  File "/usr/lib64/python2.6/site-packages/docutils/nodes.py", line 1043, in note_explicit_target
    self.set_name_id_map(target, id, msgnode, explicit=1)
  File "/usr/lib64/python2.6/site-packages/docutils/nodes.py", line 986, in set_name_id_map
    self.set_duplicate_name_id(node, id, name, msgnode, explicit)
  File "/usr/lib64/python2.6/site-packages/docutils/nodes.py", line 1014, in set_duplicate_name_id
    dupname(node, name)
  File "/usr/lib64/python2.6/site-packages/docutils/nodes.py", line 1778, in dupname
    node['names'].remove(name)
ValueError: list.remove(x): x not in list
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/737
- Originally reported by: Anonymous
- Originally created at: 2011-07-26T20:09:17.420

**Comment by shimizukawa** [comment]
_From Anonymous on 2011-07-26 18:27:12+00:00_

I found the specific syntax error causing this.

This is valid and works
//!cpp:function:: taco
void dowork();

This is improper syntax, and exposes the above error.
//!cpp:function:: taco
//!more info
void dowork();

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-09-22 08:44:15+00:00_

Cannot reproduce here; I get a nice parsing warning from the C++ domain.
