### ISSUE TITLE
Docs not building on sage math

### ISSUE THREAD

**Issue by ArchitWagle** [sphinx-doc/sphinx#7407]
The sage- reference docs are not building
I ran the following commands
```
  make doc-clean
 ./sage -b && ./sage --docbuild reference html
```

It usually works, but is giving me this error now.
I have posted the log file below

```
# Sphinx version: 1.8.5
# Python version: 3.7.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   linking _static directory.
#   copying extra files...
#   done
#   dumping search index in English (code: en) ...
#   done
#   dumping object inventory...
#   done
#   build succeeded, 1295 warnings.
#   
#   The HTML pages are in local/share/doc/sage/html/en/reference/references.
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.5) from /home/archit/sage/local/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.12) from /home/archit/sage/local/lib/python3.7/site-packages/alabaster/__init__.py
#   inventory_builder (unknown version) from /home/archit/sage/src/sage_setup/docbuild/ext/inventory_builder.py
#   multidocs (unknown version) from /home/archit/sage/src/sage_setup/docbuild/ext/multidocs.py
#   sage_autodoc (1.8.5) from /home/archit/sage/src/sage_setup/docbuild/ext/sage_autodoc.py
#   sphinx.ext.graphviz (1.8.5) from /home/archit/sage/local/lib/python3.7/site-packages/sphinx/ext/graphviz.py
#   sphinx.ext.inheritance_diagram (1.8.5) from /home/archit/sage/local/lib/python3.7/site-packages/sphinx/ext/inheritance_diagram.py
#   sphinx.ext.todo (1.8.5) from /home/archit/sage/local/lib/python3.7/site-packages/sphinx/ext/todo.py
#   sphinx.ext.extlinks (1.8.5) from /home/archit/sage/local/lib/python3.7/site-packages/sphinx/ext/extlinks.py
#   IPython.sphinxext.ipython_directive (unknown version) from /home/archit/sage/local/lib/python3.7/site-packages/IPython/sphinxext/ipython_directive.py
#   matplotlib.sphinxext.plot_directive (unknown version) from /home/archit/sage/local/lib/python3.7/site-packages/matplotlib/sphinxext/plot_directive.py
Traceback (most recent call last):
  File "/home/archit/sage/local/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/archit/sage/local/lib/python3.7/site-packages/sphinx/application.py", line 369, in build
    self.emit('build-finished', None)
  File "/home/archit/sage/local/lib/python3.7/site-packages/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/home/archit/sage/local/lib/python3.7/site-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File "/home/archit/sage/local/lib/python3.7/site-packages/sphinx/ext/graphviz.py", line 414, in on_build_finished
    copy_asset(src, dst)
  File "/home/archit/sage/local/lib/python3.7/site-packages/sphinx/util/fileutil.py", line 81, in copy_asset
    ensuredir(destination)
  File "/home/archit/sage/local/lib/python3.7/site-packages/sphinx/util/osutil.py", line 90, in ensuredir
    os.makedirs(path)
  File "/home/archit/sage/local/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/archit/sage/local/share/doc/sage/html/en/reference/references/_static'


```

**Comment by tk0miya** [comment]
Please remove a file located at `/home/archit/sage/local/share/doc/sage/html/en/reference/references/_static`. The message says Sphinx failed to create a directory at the location.
```
FileExistsError: [Errno 17] File exists: '/home/archit/sage/local/share/doc/sage/html/en/reference/references/_static'
```

**Comment by ArchitWagle** [comment]
thanks for the reply! I did that, but it did not seem to resolve the issue.
 Some other people were facing the same issue and the steps they gave me solved  it.
I will just link the answer over here.
[workaround](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/sage-devel/RHMEHCTp_pU/12BWV897AgAJ)
