### ISSUE TITLE
Adding images gives error

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#742]
i am trying to add image as tutorial like 

.. image:: test.png

or 

.. figure:: test.png

but when i want to add it was giving 

```
Exception occurred:
  File "/usr/lib/python2.6/posixpath.py", line 70, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-sicMkg.log, if you want to report the issue to the developers.
```

and in traceback 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/cmd
line.py", line 188, in main
    app.build(force_all, filenames)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/app
lication.py", line 207, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/bui
lders/__init__.py", line 198, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/bui
lders/__init__.py", line 218, in build
    purple, length):
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/bui
lders/__init__.py", line 120, in status_iterator
    for item in iterable:
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/env
ironment.py", line 519, in update_generator
    self.read_doc(docname, app=app)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/environment.py", line 672, in read_doc
    self.process_images(docname, doctree)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/environment.py", line 852, in process_images
    if not os.access(path.join(self.srcdir, imgpath), os.R_OK):
  File "/usr/lib/python2.6/posixpath.py", line 70, in join
    path += '/' + b
```

pls help me how can i solve this ...
am i upgrade or else

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/742
- Originally reported by: [aragonnette](https://bitbucket.org/aragonnette)
- Originally created at: 2011-08-03T14:43:00.959

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-19 16:40:13+00:00_

This is very probably already fixed.
