### ISSUE TITLE
ClassNotFound: Could not find style module 'simple'.

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#750]
# Sphinx version: 1.0.7
# Python version: 2.7.1
# Docutils version: 0.8 release
# Jinja2 version: 2.6

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Sphinx-1.0.7-py2.7.egg/sphinx/cmdline.py", line 187, in main
    warningiserror, tags)
  File "/Library/Python/2.7/site-packages/Sphinx-1.0.7-py2.7.egg/sphinx/application.py", line 136, in **init**
    self._init_builder(buildername)
  File "/Library/Python/2.7/site-packages/Sphinx-1.0.7-py2.7.egg/sphinx/application.py", line 197, in _init_builder
    self.builder = builderclass(self)
  File "/Library/Python/2.7/site-packages/Sphinx-1.0.7-py2.7.egg/sphinx/builders/__init__.py", line 54, in **init**
    self.init()
  File "/Library/Python/2.7/site-packages/Sphinx-1.0.7-py2.7.egg/sphinx/builders/html.py", line 94, in init
    self.init_highlighter()
  File "/Library/Python/2.7/site-packages/Sphinx-1.0.7-py2.7.egg/sphinx/builders/html.py", line 141, in init_highlighter
    self.config.trim_doctest_flags)
  File "/Library/Python/2.7/site-packages/Sphinx-1.0.7-py2.7.egg/sphinx/highlighting.py", line 116, in **init**
    style = get_style_by_name(stylename)
  File "/Library/Python/2.7/site-packages/Pygments-1.4-py2.7.egg/pygments/styles/**init**.py", line 56, in get_style_by_name
    (builtin and ", though it should be builtin") + ".")
ClassNotFound: Could not find style module 'simple'.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/750
- Originally reported by: Anonymous
- Originally created at: 2011-08-10T07:19:34.362

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-09-19 07:07:52+00:00_

There is no "simple" style for pygments...
