### ISSUE TITLE
TypeError in sphinx/writers/latex.py (Docutils 0.8)

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#754]
After upgrading Docutils to 0.8, LaTeX builder crashes with this exception:

```
# Sphinx version: 1.0.7
# Python version: 2.6.7
# Docutils version: 0.8 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/cmdline.py", line 188, in main
    app.build(force_all, filenames)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/application.py", line 207, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/builders/__init__.py", line 193, in build_update
    self.build(['__all__'], to_build)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/builders/__init__.py", line 254, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/builders/latex.py", line 104, in write
    docwriter.write(doctree, destination)
  File "/usr/lib/pymodules/python2.6/docutils/writers/__init__.py", line 77, in write
    self.translate()
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/writers/latex.py", line 91, in translate
    visitor = LaTeXTranslator(self.document, self.builder)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.0.7-py2.6.egg/sphinx/writers/latex.py", line 193, in __init__
    babel = ExtBabel(builder.config.language)
TypeError: __init__() takes exactly 3 arguments (2 given)
```

It only happens if language is set to something different than None, eg. "en".

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/754
- Originally reported by: Jakub Wilk
- Originally created at: 2011-08-23T13:00:47.347

**Comment by shimizukawa** [comment]
_From Jakub Wilk on 2011-09-02 23:42:48+00:00_

It works again with Docutils 0.8.1. Sorry for the noise.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-10-18 07:32:19+00:00_

Removing version: 1.0.7 (automated comment)
