### ISSUE TITLE
Error while running build

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#761]
Just thought I would send the report along...
# Sphinx version: 1.0.4
# Docutils version: 0.7 release
# Jinja2 version: 2.5.5

Traceback (most recent call last):
  File "/opt/tradelink/share/research/site-packages.beta/Sphinx-1.0.4-py2.4.egg/sphinx/cmdline.py", line 173, in main
    app.build(force_all, filenames)
  File "/opt/tradelink/share/research/site-packages.beta/Sphinx-1.0.4-py2.4.egg/sphinx/application.py", line 207, in build
    self.builder.build_update()
  File "/opt/tradelink/share/research/site-packages.beta/Sphinx-1.0.4-py2.4.egg/sphinx/builders/**init**.py", line 197, in build_update
    summary='targets for &#37;d source files that are '
  File "/opt/tradelink/share/research/site-packages.beta/Sphinx-1.0.4-py2.4.egg/sphinx/builders/**init**.py", line 218, in build
    purple, length):
  File "/opt/tradelink/share/research/site-packages.beta/Sphinx-1.0.4-py2.4.egg/sphinx/builders/**init**.py", line 120, in status_iterator
    for item in iterable:
  File "/opt/tradelink/share/research/site-packages.beta/Sphinx-1.0.4-py2.4.egg/sphinx/environment.py", line 515, in update_generator
    self.read_doc(docname, app=app)
  File "/opt/tradelink/share/research/site-packages.beta/Sphinx-1.0.4-py2.4.egg/sphinx/environment.py", line 652, in read_doc
    pub.set_source(None, src_path)
  File "/home/titan/schwartz/lib/python2.4/site-packages/docutils-0.7-py2.4.egg/docutils/core.py", line 169, in set_source
    encoding=self.settings.input_encoding)
  File "/home/titan/schwartz/lib/python2.4/site-packages/docutils-0.7-py2.4.egg/docutils/io.py", line 243, in **init**
    sys.exit(1)
SystemExit: 1

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/761
- Originally reported by: Anonymous
- Originally created at: 2011-09-02T18:12:14.061

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-09-19 07:06:35+00:00_

You should have gotten a message on stderr that said something like "Unable to read source file". Can you check?
