### ISSUE TITLE
str vs bytes issue?

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#763]
```
# Sphinx version: 1.1pre
# Python version: 3.2.0
# Docutils version: 0.8.1 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/src/build/py32/lib/python3.2/site-packages/Sphinx-1.1predev_20110904-py3.2.egg/sphinx/cmdline.py", line 188, in main
    app.build(force_all, filenames)
  File "/src/build/py32/lib/python3.2/site-packages/Sphinx-1.1predev_20110904-py3.2.egg/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/src/build/py32/lib/python3.2/site-packages/Sphinx-1.1predev_20110904-py3.2.egg/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "/src/build/py32/lib/python3.2/site-packages/Sphinx-1.1predev_20110904-py3.2.egg/sphinx/builders/__init__.py", line 216, in build
    purple, length):
  File "/src/build/py32/lib/python3.2/site-packages/Sphinx-1.1predev_20110904-py3.2.egg/sphinx/builders/__init__.py", line 120, in status_iterator
    for item in iterable:
  File "/src/build/py32/lib/python3.2/site-packages/Sphinx-1.1predev_20110904-py3.2.egg/sphinx/environment.py", line 614, in update_generator
    self.read_doc(docname, app=app)
  File "/src/build/py32/lib/python3.2/site-packages/Sphinx-1.1predev_20110904-py3.2.egg/sphinx/environment.py", line 761, in read_doc
    pub.publish()
  File "/src/build/py32/lib/python3.2/site-packages/docutils/core.py", line 211, in publish
    self.settings)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/readers/__init__.py", line 69, in read
    self.parse()
  File "/src/build/py32/lib/python3.2/site-packages/docutils/readers/__init__.py", line 75, in parse
    self.parser.parse(self.input, document)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/__init__.py", line 157, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/src/build/py32/lib/python3.2/site-packages/docutils/statemachine.py", line 237, in run
    context, state, transitions)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/statemachine.py", line 458, in check_line
    return method(match, context, next_state)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 2709, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 329, in section
    self.new_subsection(title, lineno, messages)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 398, in new_subsection
    node=section_node, match_titles=1)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 284, in nested_parse
    node=node, match_titles=match_titles)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/statemachine.py", line 237, in run
    context, state, transitions)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/statemachine.py", line 458, in check_line
    return method(match, context, next_state)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 2709, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 329, in section
    self.new_subsection(title, lineno, messages)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 398, in new_subsection
    node=section_node, match_titles=1)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 284, in nested_parse
    node=node, match_titles=match_titles)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/statemachine.py", line 237, in run
    context, state, transitions)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/statemachine.py", line 458, in check_line
    return method(match, context, next_state)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 2283, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 2295, in explicit_construct
    return method(self, expmatch)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 2036, in directive
    directive_class, match, type_name, option_presets)
  File "/src/build/py32/lib/python3.2/site-packages/docutils/parsers/rst/states.py", line 2087, in run_directive
    result = directive_instance.run()
  File "/src/build/py32/lib/python3.2/site-packages/Sphinx-1.1predev_20110904-py3.2.egg/sphinx/ext/autodoc.py", line 1298, in run
    documenter.generate(more_content=self.content)
  File "/src/build/py32/lib/python3.2/site-packages/Sphinx-1.1predev_20110904-py3.2.egg/sphinx/ext/autodoc.py", line 693, in generate
    self.analyzer = ModuleAnalyzer.for_module(self.real_modname)
  File "/src/build/py32/lib/python3.2/site-packages/Sphinx-1.1predev_20110904-py3.2.egg/sphinx/pycode/__init__.py", line 202, in for_module
    obj = cls.for_file(source, modname)
  File "/src/build/py32/lib/python3.2/site-packages/Sphinx-1.1predev_20110904-py3.2.egg/sphinx/pycode/__init__.py", line 185, in for_file
    obj = cls(fileobj, modname, filename)
  File "/src/build/py32/lib/python3.2/site-packages/Sphinx-1.1predev_20110904-py3.2.egg/sphinx/pycode/__init__.py", line 219, in __init__
    self.encoding = detect_encoding(self.source.readline)
  File "/src/build/py32/lib/python3.2/site-packages/Sphinx-1.1predev_20110904-py3.2.egg/sphinx/util/__init__.py", line 255, in detect_encoding
    if first and first.startswith(BOM_UTF8):
TypeError: Can't convert 'bytes' object to str implicitly
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/763
- Originally reported by: James Pye
- Originally created at: 2011-09-09T21:43:18.872

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-09-19 06:44:21+00:00_

Duplicate of #705.
