### ISSUE TITLE
Cannot build documentation with sphinx>=3.0

### ISSUE THREAD

**Issue by oleksiyskononenko** [sphinx-doc/sphinx#7737]
First of all, thanks for the great package. 

We're using sphinx to build documentation for our project [datatable](https://github.com/h2oai/datatable) on [readthedocs.org](https://readthedocs.org/projects/datatable/). For sphinx versions `>=1.8,<3.0` we have no issues, however, if we switch to the version `3.0.3` the build fails with the following error message

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/datatable/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/datatable/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/datatable/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/datatable/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/datatable/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/datatable/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 438, in _read_serial
    self.env.clear_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/datatable/envs/latest/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 297, in clear_doc
    domain.clear_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/datatable/envs/latest/lib/python3.7/site-packages/sphinx/domains/python.py", line 1165, in clear_doc
    for fullname, (fn, _x, _x) in list(self.objects.items()):
ValueError: not enough values to unpack (expected 3, got 2)

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/datatable/envs/latest/lib/python3.7/site-packages/sphinx/domains/python.py", line 1165, in clear_doc
    for fullname, (fn, _x, _x) in list(self.objects.items()):
ValueError: not enough values to unpack (expected 3, got 2)
```

More details on the failure can be found here: https://readthedocs.org/projects/datatable/builds/11091640/

This can also be reproduced locally. The following build will fail for sphinx versions `>=3.0`, but is fully ok for `<3.0`
```
git clone https://github.com/h2oai/datatable.git
cd datatable/docs
make html
```

By looking at the source of the issue we found, that the `clear_doc()` function in `python.py` for some reason receives wrong number of items for one of the pages:
```
reading sources... [  5%] api/frame/cbind                                                                                                              
('datatable.Frame', ('api/frame', 'datatable.Frame', 'class'))
('datatable.Frame.keys', ('api/frame', 'datatable.Frame.keys', 'method'))
('datatable.Frame.ltypes', ('api/frame', 'datatable.Frame.ltypes', 'attribute'))
('datatable.Frame.materialize', ('api/frame', 'datatable.Frame.materialize', 'method'))
('datatable.Frame.max', ('api/frame', 'datatable.Frame.max', 'method'))
('datatable.Frame.max1', ('api/frame', 'datatable.Frame.max1', 'method'))
('datatable.Frame.mean', ('api/frame', 'datatable.Frame.mean', 'method'))
('datatable.Frame.mean1', ('api/frame', 'datatable.Frame.mean1', 'method'))
('datatable.Frame.min', ('api/frame', 'datatable.Frame.min', 'method'))
('datatable.Frame.min1', ('api/frame', 'datatable.Frame.min1', 'method'))
('datatable.Frame.mode', ('api/frame', 'datatable.Frame.mode', 'method'))
('datatable.Frame.mode1', ('api/frame', 'datatable.Frame.mode1', 'method'))
('datatable.Frame.ncols', ('api/frame', 'datatable.Frame.ncols', 'attribute'))
('datatable.Frame.ndims', ('api/frame', 'datatable.Frame.ndims', 'attribute'))
('datatable.Frame.newsort', ('api/frame', 'datatable.Frame.newsort', 'method'))
('datatable.Frame.nmodal', ('api/frame', 'datatable.Frame.nmodal', 'method'))
('datatable.Frame.nmodal1', ('api/frame', 'datatable.Frame.nmodal1', 'method'))
('datatable.Frame.nrows', ('api/frame', 'datatable.Frame.nrows', 'attribute'))
('datatable.Frame.nunique', ('api/frame', 'datatable.Frame.nunique', 'method'))
('datatable.Frame.nunique1', ('api/frame', 'datatable.Frame.nunique1', 'method'))
('datatable.Frame.rbind', ('api/frame', 'datatable.Frame.rbind', 'method'))
('datatable.Frame.sd', ('api/frame', 'datatable.Frame.sd', 'method'))
('datatable.Frame.sd1', ('api/frame', 'datatable.Frame.sd1', 'method'))
('datatable.Frame.shape', ('api/frame', 'datatable.Frame.shape', 'attribute'))
('datatable.Frame.sort', ('api/frame', 'datatable.Frame.sort', 'method'))
('datatable.Frame.stype', ('api/frame', 'datatable.Frame.stype', 'attribute'))
('datatable.Frame.stypes', ('api/frame', 'datatable.Frame.stypes', 'attribute'))
('datatable.Frame.sum', ('api/frame', 'datatable.Frame.sum', 'method'))
('datatable.Frame.sum1', ('api/frame', 'datatable.Frame.sum1', 'method'))
('datatable.Frame.to_dict', ('api/frame', 'datatable.Frame.to_dict', 'method'))
('datatable.Frame.to_jay', ('api/frame', 'datatable.Frame.to_jay', 'method'))
('datatable.Frame.to_list', ('api/frame', 'datatable.Frame.to_list', 'method'))
('datatable.Frame.to_numpy', ('api/frame', 'datatable.Frame.to_numpy', 'method'))
('datatable.Frame.to_pandas', ('api/frame', 'datatable.Frame.to_pandas', 'method'))
('datatable.Frame.to_tuples', ('api/frame', 'datatable.Frame.to_tuples', 'method'))
('datatable.Frame.view', ('api/frame', 'datatable.Frame.view', 'method'))

reading sources... [  7%] api/frame/colindex                                                                                                           
('datatable.Frame', ('api/frame', 'datatable.Frame', 'class'))
('datatable.Frame.keys', ('api/frame', 'datatable.Frame.keys', 'method'))
('datatable.Frame.ltypes', ('api/frame', 'datatable.Frame.ltypes', 'attribute'))
('datatable.Frame.materialize', ('api/frame', 'datatable.Frame.materialize', 'method'))
('datatable.Frame.max', ('api/frame', 'datatable.Frame.max', 'method'))
('datatable.Frame.max1', ('api/frame', 'datatable.Frame.max1', 'method'))
('datatable.Frame.mean', ('api/frame', 'datatable.Frame.mean', 'method'))
('datatable.Frame.mean1', ('api/frame', 'datatable.Frame.mean1', 'method'))
('datatable.Frame.min', ('api/frame', 'datatable.Frame.min', 'method'))
('datatable.Frame.min1', ('api/frame', 'datatable.Frame.min1', 'method'))
('datatable.Frame.mode', ('api/frame', 'datatable.Frame.mode', 'method'))
('datatable.Frame.mode1', ('api/frame', 'datatable.Frame.mode1', 'method'))
('datatable.Frame.ncols', ('api/frame', 'datatable.Frame.ncols', 'attribute'))
('datatable.Frame.ndims', ('api/frame', 'datatable.Frame.ndims', 'attribute'))
('datatable.Frame.newsort', ('api/frame', 'datatable.Frame.newsort', 'method'))
('datatable.Frame.nmodal', ('api/frame', 'datatable.Frame.nmodal', 'method'))
('datatable.Frame.nmodal1', ('api/frame', 'datatable.Frame.nmodal1', 'method'))
('datatable.Frame.nrows', ('api/frame', 'datatable.Frame.nrows', 'attribute'))
('datatable.Frame.nunique', ('api/frame', 'datatable.Frame.nunique', 'method'))
('datatable.Frame.nunique1', ('api/frame', 'datatable.Frame.nunique1', 'method'))
('datatable.Frame.rbind', ('api/frame', 'datatable.Frame.rbind', 'method'))
('datatable.Frame.sd', ('api/frame', 'datatable.Frame.sd', 'method'))
('datatable.Frame.sd1', ('api/frame', 'datatable.Frame.sd1', 'method'))
('datatable.Frame.shape', ('api/frame', 'datatable.Frame.shape', 'attribute'))
('datatable.Frame.sort', ('api/frame', 'datatable.Frame.sort', 'method'))
('datatable.Frame.stype', ('api/frame', 'datatable.Frame.stype', 'attribute'))
('datatable.Frame.stypes', ('api/frame', 'datatable.Frame.stypes', 'attribute'))
('datatable.Frame.sum', ('api/frame', 'datatable.Frame.sum', 'method'))
('datatable.Frame.sum1', ('api/frame', 'datatable.Frame.sum1', 'method'))
('datatable.Frame.to_dict', ('api/frame', 'datatable.Frame.to_dict', 'method'))
('datatable.Frame.to_jay', ('api/frame', 'datatable.Frame.to_jay', 'method'))
('datatable.Frame.to_list', ('api/frame', 'datatable.Frame.to_list', 'method'))
('datatable.Frame.to_numpy', ('api/frame', 'datatable.Frame.to_numpy', 'method'))
('datatable.Frame.to_pandas', ('api/frame', 'datatable.Frame.to_pandas', 'method'))
('datatable.Frame.to_tuples', ('api/frame', 'datatable.Frame.to_tuples', 'method'))
('datatable.Frame.view', ('api/frame', 'datatable.Frame.view', 'method'))
('datatable.Frame.cbind', ('api/frame/cbind', 'method'))
```
Note, that the last line has a wrong number of elements in the tuple, so this is where it fails. However, there is nothing special about the `cbind` page and if we disable it in the docs, the build will fail with the exactly same message on the `view` page. 

Do we expect this kind of issues when moving to sphinx `3.0`? If yes, why does it happen and how can we fix it?

Thanks a lot in advance for all your kind help.

**Comment by tk0miya** [comment]
Since Sphinx-3.0, the internal structure of the python domain has been changed. And it seems the extensions that your project uses touches the domain directly. It causes this crash. Please update your extensions to access the python domain via its API.

>By looking at the source of the issue we found, that the clear_doc() function in python.py for some reason receives wrong number of items for one of the pages:

The broken entry was added by your extensions.

Note: Please don't ignore the issue template of OSS projects. I wasted about 1 hour to investigate your project uses its own extensions.

**Comment by oleksiyskononenko** [comment]
Dear @tk0miya, yes, we're using our own extension, sorry, I missed that this info was required by your template. Thanks for the information, we will start using the API and see what happens.

**Comment by st-pasha** [comment]
Hi @tk0miya,
I've been looking through the Sphinx Domain API's [documentation](https://www.sphinx-doc.org/en/master/extdev/domainapi.html) and could not find any method for adding objects to a domain.

In particular, given a page and a node on that page, I'd want to tell to Sphinx that this node should be the target for any 
```
:py:meth:`mymodule.MyClass.my_method()`
```
RST link anywhere else within the docsite.

**Comment by tk0miya** [comment]
Oops... we must mention about the registration API. There are no common API for domains. But each domain has its registration API. For python objects, please use `PythonDomain.note_object()` to do that. I'll add them to our reference later.
