### ISSUE TITLE
NotImplementedError: Unknown node: CodeAreaNode

### ISSUE THREAD

**Issue by dmi-000** [sphinx-doc/sphinx#7816]
**Describe the bug**
NotImplementedError: Unknown node: CodeAreaNode

**To Reproduce**
```
cd docs
make man
```

```
Running Sphinx v2.4.0
loading translations [en]... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 28 added, 0 changed, 0 removed
/Users/dmi/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/dmi/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/dmi/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/dmi/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
reading sources... [100%] readme                                                                                                                                                            
/Users/dmi/headlamp/dowhy/dowhy/causal_estimator.py:docstring of dowhy.causal_estimator.CausalEstimate.get_standard_error:9: WARNING: Inline strong start-string without end-string.
/Users/dmi/headlamp/dowhy/dowhy/causal_estimator.py:docstring of dowhy.causal_estimator.CausalEstimate.test_stat_significance:9: WARNING: Inline strong start-string without end-string.
/Users/dmi/headlamp/dowhy/dowhy/causal_estimator.py:docstring of dowhy.causal_estimator.CausalEstimator.estimate_std_error:4: WARNING: Inline strong start-string without end-string.
/Users/dmi/headlamp/dowhy/dowhy/causal_estimator.py:docstring of dowhy.causal_estimator.CausalEstimator.get_estimator_object:6: WARNING: Field list ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_estimator.py:docstring of dowhy.causal_estimator.CausalEstimator.is_bootstrap_parameter_changed:8: WARNING: Field list ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_model.py:docstring of dowhy.causal_model.CausalModel.refute_estimate:12: WARNING: Inline strong start-string without end-string.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuter.py:docstring of dowhy.causal_refuter.CausalRefuter.test_significance:8: WARNING: Unexpected indentation.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuter.py:docstring of dowhy.causal_refuter.CausalRefuter.test_significance:20: WARNING: Unexpected section title.

Parameters
-----------
/Users/dmi/headlamp/dowhy/dowhy/causal_refuter.py:docstring of dowhy.causal_refuter.CausalRefuter.test_significance:31: WARNING: Unexpected section title.

Returns
--------
/Users/dmi/headlamp/dowhy/dowhy/datasets.py:docstring of dowhy.datasets.choice:10: WARNING: Unexpected section title.

Parameters
----------
/Users/dmi/headlamp/dowhy/dowhy/datasets.py:docstring of dowhy.datasets.choice:26: WARNING: Unexpected section title.

Returns
-------
/Users/dmi/headlamp/dowhy/dowhy/datasets.py:docstring of dowhy.datasets.choice:31: WARNING: Unexpected section title.

Raises
------
/Users/dmi/headlamp/dowhy/dowhy/datasets.py:docstring of dowhy.datasets.choice:40: WARNING: Unexpected section title.

See Also
--------
/Users/dmi/headlamp/dowhy/dowhy/datasets.py:docstring of dowhy.datasets.choice:45: WARNING: Unexpected section title.

Examples
--------
/Users/dmi/headlamp/dowhy/dowhy/api/causal_data_frame.py:docstring of dowhy.api.causal_data_frame.CausalAccessor.do:28: WARNING: Field list ends without a blank line; unexpected unindent.
WARNING: autodoc: failed to import module 'causalml' from module 'dowhy.causal_estimators'; the following exception was raised:
No module named 'causalml'
WARNING: autodoc: failed to import module 'econml' from module 'dowhy.causal_estimators'; the following exception was raised:
No module named 'econml'
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/bootstrap_refuter.py:docstring of dowhy.causal_refuters.bootstrap_refuter.BootstrapRefuter:8: WARNING: Unexpected section title.

Parameters
-----------
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/bootstrap_refuter.py:docstring of dowhy.causal_refuters.bootstrap_refuter.BootstrapRefuter:15: WARNING: Unexpected indentation.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/bootstrap_refuter.py:docstring of dowhy.causal_refuters.bootstrap_refuter.BootstrapRefuter:24: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/bootstrap_refuter.py:docstring of dowhy.causal_refuters.bootstrap_refuter.BootstrapRefuter:25: WARNING: Bullet list ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/data_subset_refuter.py:docstring of dowhy.causal_refuters.data_subset_refuter.DataSubsetRefuter:6: WARNING: Bullet list ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/dummy_outcome_refuter.py:docstring of dowhy.causal_refuters.dummy_outcome_refuter.DummyOutcomeRefuter:6: WARNING: Bullet list ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/dummy_outcome_refuter.py:docstring of dowhy.causal_refuters.dummy_outcome_refuter.DummyOutcomeRefuter:9: WARNING: Bullet list ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/dummy_outcome_refuter.py:docstring of dowhy.causal_refuters.dummy_outcome_refuter.DummyOutcomeRefuter:11: WARNING: Unexpected indentation.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/dummy_outcome_refuter.py:docstring of dowhy.causal_refuters.dummy_outcome_refuter.DummyOutcomeRefuter:14: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/dummy_outcome_refuter.py:docstring of dowhy.causal_refuters.dummy_outcome_refuter.DummyOutcomeRefuter:36: WARNING: Bullet list ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/dummy_outcome_refuter.py:docstring of dowhy.causal_refuters.dummy_outcome_refuter.DummyOutcomeRefuter:46: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/dummy_outcome_refuter.py:docstring of dowhy.causal_refuters.dummy_outcome_refuter.DummyOutcomeRefuter:51: WARNING: Bullet list ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/dummy_outcome_refuter.py:docstring of dowhy.causal_refuters.dummy_outcome_refuter.DummyOutcomeRefuter:54: WARNING: Unexpected indentation.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/dummy_outcome_refuter.py:docstring of dowhy.causal_refuters.dummy_outcome_refuter.DummyOutcomeRefuter:55: WARNING: Unexpected section title.

(max value - min value)
------------------------
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/dummy_outcome_refuter.py:docstring of dowhy.causal_refuters.dummy_outcome_refuter.DummyOutcomeRefuter:59: WARNING: Bullet list ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/dummy_outcome_refuter.py:docstring of dowhy.causal_refuters.dummy_outcome_refuter.DummyOutcomeRefuter.process_data:5: WARNING: Bullet list ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/dummy_outcome_refuter.py:docstring of dowhy.causal_refuters.dummy_outcome_refuter.DummyOutcomeRefuter.process_data:9: WARNING: Unexpected indentation.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/dummy_outcome_refuter.py:docstring of dowhy.causal_refuters.dummy_outcome_refuter.DummyOutcomeRefuter.process_data:11: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/dummy_outcome_refuter.py:docstring of dowhy.causal_refuters.dummy_outcome_refuter.DummyOutcomeRefuter.process_data:12: WARNING: Bullet list ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/dowhy/causal_refuters/placebo_treatment_refuter.py:docstring of dowhy.causal_refuters.placebo_treatment_refuter.PlaceboTreatmentRefuter:6: WARNING: Bullet list ends without a blank line; unexpected unindent.
WARNING: autodoc: failed to import module 'mcmc_sampler' from module 'dowhy.do_samplers'; the following exception was raised:
No module named 'pymc3'
/Users/dmi/headlamp/dowhy/dowhy/utils/cli_helpers.py:docstring of dowhy.utils.cli_helpers.query_yes_no:7: WARNING: Unexpected indentation.
/Users/dmi/headlamp/dowhy/dowhy/utils/cli_helpers.py:docstring of dowhy.utils.cli_helpers.query_yes_no:10: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/dmi/headlamp/dowhy/docs/source/example_notebooks/dowhy_ihdp_data_example.ipynb:849: WARNING: Title level inconsistent:

Refute the obtained estimate using multiple robustness checks.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
/Users/dmi/headlamp/dowhy/docs/source/example_notebooks/dowhy_ihdp_data_example.ipynb:852: WARNING: Title level inconsistent:

4.1 Adding a random common cause
''''''''''''''''''''''''''''''''
/Users/dmi/headlamp/dowhy/docs/source/example_notebooks/dowhy_ihdp_data_example.ipynb:928: WARNING: Title level inconsistent:

4.2 Using a placebo treatment
'''''''''''''''''''''''''''''
/Users/dmi/headlamp/dowhy/docs/source/example_notebooks/dowhy_twins_example .ipynb:6: WARNING: Each notebook should have at least one section title
../README.rst:13: WARNING: Duplicate explicit target name: "release".
../README.rst:13: WARNING: Duplicate explicit target name: "release".
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/dmi/headlamp/dowhy/docs/source/example_notebooks/dowhy_demo_dummy_outcome_refuter.ipynb: WARNING: document isn't included in any toctree
/Users/dmi/headlamp/dowhy/docs/source/example_notebooks/dowhy_multiple_treatments.ipynb: WARNING: document isn't included in any toctree
/Users/dmi/headlamp/dowhy/docs/source/example_notebooks/dowhy_refutation_testing.ipynb: WARNING: document isn't included in any toctree
/Users/dmi/headlamp/dowhy/docs/source/example_notebooks/dowhy_refuter_notebook.ipynb: WARNING: document isn't included in any toctree
/Users/dmi/headlamp/dowhy/docs/source/example_notebooks/dowhy_twins_example .ipynb: WARNING: document isn't included in any toctree
/Users/dmi/headlamp/dowhy/docs/source/modules.rst: WARNING: document isn't included in any toctree
done
writing... dowhy.1 { readme example_notebooks/nb_index example_notebooks/dowhy_simple_example example_notebooks/dowhy_confounder_example example_notebooks/dowhy_estimation_methods example_notebooks/dowhy-conditional-treatment-effects example_notebooks/dowhy_causal_api example_notebooks/do_sampler_demo example_notebooks/load_graph_example example_notebooks/dowhy-simple-iv-example example_notebooks/dowhy_ihdp_data_example example_notebooks/dowhy_lalonde_example example_notebooks/lalonde_pandas_api code_repo dowhy dowhy.api dowhy.causal_estimators dowhy.causal_refuters dowhy.data_transformers dowhy.do_samplers dowhy.utils } failed

Exception occurred:
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/writers/manpage.py", line 459, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: CodeAreaNode
The full traceback has been saved in /var/folders/x4/zdvfs0f57tx0qcrn7v_gqvvw0000gn/T/sphinx-err-zyotvr0_.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [man] Error 2
```
```
cat  /var/folders/x4/zdvfs0f57tx0qcrn7v_gqvvw0000gn/T/sphinx-err-zyotvr0_.log
# Sphinx version: 2.4.0
# Python version: 3.7.6 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.1
# Last messages:
#   code_repo
#   dowhy
#   dowhy.api
#   dowhy.causal_estimators
#   dowhy.causal_refuters
#   dowhy.data_transformers
#   dowhy.do_samplers
#   dowhy.utils
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.0) from /Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Users/dmi/opt/anaconda3/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (2.4.0) from /Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (2.4.0) from /Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.viewcode (2.4.0) from /Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.todo (2.4.0) from /Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/ext/todo.py
#   nbsphinx (0.7.0) from /Users/dmi/opt/anaconda3/lib/python3.7/site-packages/nbsphinx.py
Traceback (most recent call last):
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(['__all__'], to_build)
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/util/__init__.py", line 686, in wrapper
    return f(*args, **kwargs)
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/builders/manpage.py", line 100, in write
    docwriter.write(largetree, destination)
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/writers/manpage.py", line 45, in translate
    self.document.walkabout(visitor)
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 6 more times]
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/util/docutils.py", line 486, in dispatch_visit
    super().dispatch_visit(node)
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 1995, in dispatch_visit
    return method(node)
  File "/Users/dmi/opt/anaconda3/lib/python3.7/site-packages/sphinx/writers/manpage.py", line 459, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: CodeAreaNode
```

**Comment by tk0miya** [comment]
It seems `CodeAreaNode` is a custom node of nbsphinx. So this should be fixed by nbsphinx side.
