### ISSUE TITLE
bizarre ``autodoc`` error upon readthedocs build

### ISSUE THREAD

**Issue by corinwagen** [sphinx-doc/sphinx#7825]
**Describe the bug**
When using ``readthedocs`` for my project ``cctk``, I get an unintelligible Sphinx error pertaining to ``autodoc``:

```
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
[autosummary] generating autosummary for: about.rst, cctk.rst, contact.rst, examples.rst, index.rst, installation.rst, modules.rst, overview.rst, quick-start.rst, recipe_01.rst, ..., recipe_08.rst, recipes.rst, tutorial_01.rst, tutorial_02.rst, tutorial_03.rst, tutorial_04.rst, tutorial_05.rst, tutorial_06.rst, tutorial_07.rst, tutorial_08.rst
[autosummary] generating autosummary for: /home/docs/checkouts/readthedocs.org/user_builds/cctk/checkouts/latest/docs/_autosummary/cctk.ConformationalEnsemble.rst, /home/docs/checkouts/readthedocs.org/user_builds/cctk/checkouts/latest/docs/_autosummary/cctk.Ensemble.rst, /home/docs/checkouts/readthedocs.org/user_builds/cctk/checkouts/latest/docs/_autosummary/cctk.File.rst, /home/docs/checkouts/readthedocs.org/user_builds/cctk/checkouts/latest/docs/_autosummary/cctk.GaussianFile.rst, /home/docs/checkouts/readthedocs.org/user_builds/cctk/checkouts/latest/docs/_autosummary/cctk.GaussianJobType.rst, /home/docs/checkouts/readthedocs.org/user_builds/cctk/checkouts/latest/docs/_autosummary/cctk.Group.rst, /home/docs/checkouts/readthedocs.org/user_builds/cctk/checkouts/latest/docs/_autosummary/cctk.MAEFile.rst, /home/docs/checkouts/readthedocs.org/user_builds/cctk/checkouts/latest/docs/_autosummary/cctk.MOL2File.rst, /home/docs/checkouts/readthedocs.org/user_builds/cctk/checkouts/latest/docs/_autosummary/cctk.Molecule.rst, /home/docs/checkouts/readthedocs.org/user_builds/cctk/checkouts/latest/docs/_autosummary/cctk.XYZFile.rst, /home/docs/checkouts/readthedocs.org/user_builds/cctk/checkouts/latest/docs/_autosummary/cctk.helper_functions.rst
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 26 source files that are out of date
updating environment: 37 added, 0 changed, 0 removed
reading sources... [  2%] _autosummary/cctk.ConformationalEnsemble

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/sphinx/parsers.py", line 88, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2328, in explicit_markup
    self.explicit_list(blank_finish)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2358, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2631, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 121, in run
    documenter_options = process_documenter_options(doccls, self.config, self.options)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 73, in process_documenter_options
    return Options(assemble_option_dict(options.items(), documenter.option_spec))
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/docutils/utils/__init__.py", line 328, in assemble_option_dict
    options[name] = convertor(value)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 82, in members_option
    return [x.strip() for x in arg.split(',')]
AttributeError: 'bool' object has no attribute 'split'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/cctk/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 82, in members_option
    return [x.strip() for x in arg.split(',')]
AttributeError: 'bool' object has no attribute 'split'
The full traceback has been saved in /tmp/sphinx-err-3hj75kv3.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**To Reproduce**
I pushed some minor code changes which were picked by the ``rtd`` webhook and resulted in build failure - I think I added a new function to a module which was being ``autodoc``'ed. 

My ``conf`` file is [here](https://github.com/ekwan/cctk/blob/master/docs/conf.py). Requirements are loading ok, it seems. (full error log attached as [error.txt](https://github.com/sphinx-doc/sphinx/files/4772597/error.txt) )

**Expected behavior**
I want my docs to work like they used to.

**Your project**
[Working docs build](https://cctk.readthedocs.io/en/latest/)
[Github repo](https://github.com/ekwan/cctk)

**Additional context**
I know this is really confusing and I understand if the response here is "go figure it out yourself" - this might not even be a Sphinx problem, but a more comprehensible error message would be appreciated :/.

**Comment by tk0miya** [comment]
The `autodoc_default_options` accepts a boolean value since Sphinx-2.0. So you need to specify the version of Sphinx in RTD.
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_default_options

Thanks,
