### ISSUE TITLE
Error compiling PDF

### ISSUE THREAD

**Issue by netphantom** [sphinx-doc/sphinx#7909]
**Describe the bug**
Sphinx has a type error while compiling the pdf of my documentation. I don't know why it goes looking for the torch code if it is not required to compile torch documentation

**To Reproduce**
in a terminal window, inside the doc folder (with the RST)
```
sphinx-build -b pdf ./ ./build
```

**Expected behavior**
It creates a pdf file in the "build" folder

**Screenshots**
```
# Sphinx version: 3.1.1
# Python version: 3.8.3 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:
#   intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
#   building [mo]: targets for 0 po files that are out of date
#   building [pdf]: targets for 5 source files that are out of date
#   updating environment:
#   [new config]
#   5 added, 0 changed, 0 removed
#   reading sources... [ 20%] changelog
#   reading sources... [ 40%] index
#   reading sources... [ 60%] methods
#   reading sources... [ 80%] modules
# Loaded extensions:
#   sphinx.ext.mathjax (3.1.1) from /Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.intersphinx (3.1.1) from /Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.ifconfig (3.1.1) from /Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.viewcode (3.1.1) from /Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.autodoc.type_comment (3.1.1) from /Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.1.1) from /Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   rst2pdf.pdfbuilder (0.97) from /Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/rst2pdf/pdfbuilder.py
Traceback (most recent call last):
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/io.py", line 126, in read
    self.parse()
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/parsers.py", line 102, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/ext/autodoc/directive.py", line 146, in run
    documenter.generate(more_content=self.content)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 771, in generate
    if not self.parse_name():
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 327, in parse_name
    self.modname, self.objpath = self.resolve_name(modname, parents, path, base)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 979, in resolve_name
    modname, qualname = split_full_qualified_name(stripped)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/sphinx/util/__init__.py", line 624, in split_full_qualified_name
    module = import_module(modname)
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macUser/Documents/Programming/PyCharm/pythonproj/pythonproj/commands.py", line 31, in <module>
    from .cgcn.clustergcn import ClusterGCNTrainer
  File "/Users/macUser/Documents/Programming/PyCharm/pythonproj/pythonproj/cgcn/clustergcn.py", line 5, in <module>
    from .layers import StackedGCN
  File "/Users/macUser/Documents/Programming/PyCharm/pythonproj/pythonproj/cgcn/layers.py", line 2, in <module>
    from torch_geometric.nn import GCNConv
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/Users/macUser/opt/anaconda3/envs/pythonproj38/lib/python3.8/site-packages/torch_sparse/__init__.py", line 20, in <module>
    elif cuda_version < 10000:
TypeError: '<' not supported between instances of 'cuda_version' and 'int'
```

**Environment info**
- OS: Mac Os Catalina 10.15.5
- Python version: 3.8.3
- Sphinx version: 3.1.1
- Sphinx extensions:  
    'sphinx.ext.intersphinx',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.autodoc',
    'rst2pdf.pdfbuilder',
- Extra tools: Pycharm

**Comment by tk0miya** [comment]
autodoc goes to import target module to create document from your source code. It seems your code depends on torch_geometric. So torch_geometric and torch was imported. But it unexpectedly failed in comparing cuda's version. To avoid this error, there are two ways; 1) install cuda to your environment, 2) use `autodoc_mock_imports` to prevents importing `torch_geometric` or `torch`.
Thanks,

**Comment by netphantom** [comment]
Thanks @tk0miya . I already had autodoc_mock_imports["torch"] in my conf.py. I changed it with "torch_geometric" to solve the problem.
