### ISSUE TITLE
Issue with . notation in methode name, e.g. overwriting coder.typeof

### ISSUE THREAD

**Issue by kingjin94** [sphinx-doc/sphinx#7931]
The parser cannot handle function names with a "." in them, such as coder.typeof.

Example class:

```MATLAB
classdef A
  properties
    tmp double = 42;
  end
  methods
    function obj = A(t)
      obj.tmp = t;
    end
    function t = coder.typeof(obj)
      t = coder.newtype('A');
      t.Properties.tmp = coder.typeof(1.)
    end
  end
end
```

make html (with rst that includes this classdef) produces error:

```
Running Sphinx v3.0.3
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 6 source files that are out of date
updating environment: [new config] 6 added, 0 changed, 0 removed
/home/matthias/Documents/Phd/ConfigurationSearch/modular-robot-toolbox/doc/geom_fcns.rst:47: WARNING: [sphinxcontrib-matlabdomain]: failed to import method 'CollisionObjectRT.coder.typeof' from module 'geom_fcns'; the following exception was raised:
Traceback (most recent call last):
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/util/inspect.py", line 307, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: 'NoneType' object has no attribute 'typeof'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinxcontrib/mat_documenters.py", line 136, in import_object
    obj = self.get_attr(obj, part)
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 234, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1742, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/util/inspect.py", line 323, in safe_getattr
    raise AttributeError(name)
AttributeError: typeof


Exception occurred:
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinxcontrib/mat_documenters.py", line 918, in import_object
    if self.object.attrs.get('Static'):
AttributeError: 'NoneType' object has no attribute 'attrs'
The full traceback has been saved in /tmp/sphinx-err-gcs2m3ku.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: html] Error 2
```

and log file:

```
# Sphinx version: 3.0.3
# Python version: 3.8.2 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:
#   Running Sphinx v3.0.3
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 6 source files that are out of date
#   updating environment:
#   [new config]
#   6 added, 0 changed, 0 removed
#   reading sources... [ 16%] background
#   reading sources... [ 33%] geom_fcns
# Loaded extensions:
#   sphinx.ext.mathjax (3.0.3) from /home/matthias/.local/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/matthias/.local/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/matthias/.local/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /home/matthias/.local/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /home/matthias/.local/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/matthias/.local/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/matthias/.local/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (3.0.3) from /home/matthias/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.0.3) from /home/matthias/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinxcontrib.matlab (unknown version) from /home/matthias/.local/lib/python3.8/site-packages/sphinxcontrib/matlab.py
Traceback (most recent call last):
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/io.py", line 126, in read
    self.parse()
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/parsers.py", line 102, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2344, in explicit_markup
    self.explicit_list(blank_finish)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2369, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 318, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2647, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/home/matthias/.local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinx/domains/__init__.py", line 285, in run
    return super().run()
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinxcontrib/mat_directives.py", line 53, in run
    documenter.generate(more_content=self.content)
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinxcontrib/mat_documenters.py", line 565, in generate
    self.document_members(all_members)
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinxcontrib/mat_documenters.py", line 887, in document_members
    MatModuleLevelDocumenter.document_members(self, all_members)
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinxcontrib/mat_documenters.py", line 487, in document_members
    documenter.generate(
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinxcontrib/mat_documenters.py", line 515, in generate
    if not self.import_object():
  File "/home/matthias/.local/lib/python3.8/site-packages/sphinxcontrib/mat_documenters.py", line 918, in import_object
    if self.object.attrs.get('Static'):
AttributeError: 'NoneType' object has no attribute 'attrs'
```

**Comment by tk0miya** [comment]
It seems the error was raised inside `sphinxcontrib/mat_documenters.py`. So could you report this to their project first, please?
