### ISSUE TITLE
Pb with sphinx on mac os x

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#799]
Running Sphinx v1.1

```
Exception occurred:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/sphinx/application.py", line 292, in _validate_event
    event = sys.intern(event)
TypeError: must be str, not bytes
The full traceback:
# Sphinx version: 1.1
# Python version: 3.2.2
# Docutils version: 0.8.1 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/sphinx/cmdline.py", line 188, in main
    warningiserror, tags)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/sphinx/application.py", line 114, in __init__
    self.setup_extension(extension)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/sphinx/application.py", line 256, in setup_extension
    mod.setup(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/sphinxcontrib/programoutput.py", line 242, in setup
    app.connect(b'builder-inited', init_cache)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/sphinx/application.py", line 297, in connect
    self._validate_event(event)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/sphinx/application.py", line 292, in _validate_event
    event = sys.intern(event)
TypeError: must be str, not bytes
# Sphinx version: 1.1
# Python version: 3.2.2
# Docutils version: 0.8.1 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/sphinx/cmdline.py", line 188, in main
    warningiserror, tags)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/sphinx/application.py", line 114, in __init__
    self.setup_extension(extension)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/sphinx/application.py", line 256, in setup_extension
    mod.setup(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/sphinxcontrib/programoutput.py", line 242, in setup
    app.connect(b'builder-inited', init_cache)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/sphinx/application.py", line 297, in connect
    self._validate_event(event)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/sphinx/application.py", line 292, in _validate_event
    event = sys.intern(event)
TypeError: must be str, not bytes
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/799
- Originally reported by: [roza](https://bitbucket.org/roza)
- Originally created at: 2011-10-17T21:04:53.228

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-11-01 08:05:03+00:00_

It seems that programoutput hasn't been correctly ported to Python 3.
