### ISSUE TITLE
Getting TypeError: 'NoneType' object is not subscriptable while running 'make texinfo` in this project

### ISSUE THREAD

**Issue by YorkZ** [sphinx-doc/sphinx#7993]
**Describe the bug**
I was trying to generate an `texinfo` document for `Sphinx` itself, so I ran `make texinfo` and got the error:
```
TypeError: 'NoneType' object is not subscriptable
```
**To Reproduce**
```
$ git clone https://github.com/sphinx-doc/sphinx.git
$ cd sphinx/doc
$ . ~/.virtualenvs/python-3.8/bin/activate
$ pip install -U sphinx
$ make texinfo
$ # open _build/texinfo/index and nothing in the directory
```
The following is the full command and output with `/home/$USER` replaced by `~`
to hide my personal info.

```
make texinfo
Running Sphinx v3.1.2
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [texinfo]: all documents
updating environment: [new config] 81 added, 0 changed, 0 removed
reading sources... [  1%] changes
reading sources... [  2%] contents
reading sources... [  3%] develop
reading sources... [  4%] development/index
reading sources... [  6%] development/tutorials/examples/README
reading sources... [  7%] development/tutorials/helloworld
reading sources... [  8%] development/tutorials/index
reading sources... [  9%] development/tutorials/recipe
reading sources... [ 11%] development/tutorials/todo
reading sources... [ 12%] examples
reading sources... [ 13%] extdev/appapi
reading sources... [ 14%] extdev/builderapi
reading sources... [ 16%] extdev/collectorapi
reading sources... [ 17%] extdev/deprecated
reading sources... [ 18%] extdev/domainapi
reading sources... [ 19%] extdev/envapi
reading sources... [ 20%] extdev/i18n
reading sources... [ 22%] extdev/index
reading sources... [ 23%] extdev/logging
reading sources... [ 24%] extdev/markupapi
reading sources... [ 25%] extdev/nodes
reading sources... [ 27%] extdev/parserapi
reading sources... [ 28%] extdev/projectapi
reading sources... [ 29%] extdev/utils
reading sources... [ 30%] faq
reading sources... [ 32%] glossary
reading sources... [ 33%] internals/authors
reading sources... [ 34%] internals/code-of-conduct
reading sources... [ 35%] internals/contributing
reading sources... [ 37%] internals/index
reading sources... [ 38%] internals/organization
reading sources... [ 39%] internals/release-process
reading sources... [ 40%] latex
reading sources... [ 41%] man/index
reading sources... [ 43%] man/sphinx-apidoc
reading sources... [ 44%] man/sphinx-autogen
reading sources... [ 45%] man/sphinx-build
reading sources... [ 46%] man/sphinx-quickstart
reading sources... [ 48%] templating
reading sources... [ 49%] theming
reading sources... [ 50%] usage/advanced/intl
reading sources... [ 51%] usage/advanced/setuptools
reading sources... [ 53%] usage/advanced/websupport/api
reading sources... [ 54%] usage/advanced/websupport/index
reading sources... [ 55%] usage/advanced/websupport/quickstart
reading sources... [ 56%] usage/advanced/websupport/searchadapters
reading sources... [ 58%] usage/advanced/websupport/storagebackends
reading sources... [ 59%] usage/builders/index
reading sources... [ 60%] usage/configuration
reading sources... [ 61%] usage/extensions/autodoc
reading sources... [ 62%] usage/extensions/autosectionlabel
reading sources... [ 64%] usage/extensions/autosummary
reading sources... [ 65%] usage/extensions/coverage
reading sources... [ 66%] usage/extensions/doctest
reading sources... [ 67%] usage/extensions/duration
reading sources... [ 69%] usage/extensions/example_google
reading sources... [ 70%] usage/extensions/example_numpy
reading sources... [ 71%] usage/extensions/extlinks
reading sources... [ 72%] usage/extensions/githubpages
reading sources... [ 74%] usage/extensions/graphviz
reading sources... [ 75%] usage/extensions/ifconfig
reading sources... [ 76%] usage/extensions/imgconverter
reading sources... [ 77%] usage/extensions/index
reading sources... [ 79%] usage/extensions/inheritance
reading sources... [ 80%] usage/extensions/intersphinx
reading sources... [ 81%] usage/extensions/linkcode
reading sources... [ 82%] usage/extensions/math
reading sources... [ 83%] usage/extensions/napoleon
reading sources... [ 85%] usage/extensions/todo
reading sources... [ 86%] usage/extensions/viewcode
reading sources... [ 87%] usage/index
reading sources... [ 88%] usage/installation
reading sources... [ 90%] usage/markdown
reading sources... [ 91%] usage/quickstart
reading sources... [ 92%] usage/restructuredtext/basics
reading sources... [ 93%] usage/restructuredtext/directives
reading sources... [ 95%] usage/restructuredtext/domains
reading sources... [ 96%] usage/restructuredtext/field-lists
reading sources... [ 97%] usage/restructuredtext/index
reading sources... [ 98%] usage/restructuredtext/roles
reading sources... [100%] usage/theming

WARNING: autodoc: failed to import method 'websupport.WebSupport.build' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.WebSupport.get_document' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.WebSupport.get_data' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.WebSupport.add_comment' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.WebSupport.process_vote' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.WebSupport.get_search_results' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.search.BaseSearch.init_indexing' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.search.BaseSearch.finish_indexing' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.search.BaseSearch.feed' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.search.BaseSearch.add_document' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.search.BaseSearch.query' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.search.BaseSearch.handle_query' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.search.BaseSearch.extract_context' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.storage.StorageBackend.pre_build' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.storage.StorageBackend.add_node' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.storage.StorageBackend.post_build' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.storage.StorageBackend.add_comment' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.storage.StorageBackend.delete_comment' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.storage.StorageBackend.get_data' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.storage.StorageBackend.process_vote' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.storage.StorageBackend.update_username' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
WARNING: autodoc: failed to import method 'websupport.storage.StorageBackend.accept_comment' from module 'sphinxcontrib'; the following exception was raised:
No module named 'sphinxcontrib.websupport'
~/src/sphinx/doc/usage/restructuredtext/domains.rst:742: WARNING: Unknown directive type "c:alias".

.. c:alias:: data
             f
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing sphinx.texi... contents usage/index usage/quickstart usage/installation usage/restructuredtext/index usage/restructuredtext/basics usage/restructuredtext/roles usage/restructuredtext/directives usage/restructuredtext/field-lists usage/restructuredtext/domains usage/markdown usage/configuration usage/builders/index usage/extensions/index usage/extensions/autodoc usage/extensions/autosectionlabel usage/extensions/autosummary usage/extensions/coverage usage/extensions/doctest usage/extensions/duration usage/extensions/extlinks usage/extensions/githubpages usage/extensions/graphviz usage/extensions/ifconfig usage/extensions/imgconverter usage/extensions/inheritance usage/extensions/intersphinx usage/extensions/linkcode usage/extensions/math usage/extensions/napoleon usage/extensions/todo usage/extensions/viewcode usage/theming usage/advanced/intl usage/advanced/setuptools usage/advanced/websupport/index usage/advanced/websupport/quickstart usage/advanced/websupport/api usage/advanced/websupport/searchadapters usage/advanced/websupport/storagebackends development/index development/tutorials/index development/tutorials/helloworld development/tutorials/todo development/tutorials/recipe man/index man/sphinx-quickstart man/sphinx-build man/sphinx-apidoc man/sphinx-autogen theming templating latex extdev/index extdev/appapi extdev/projectapi extdev/envapi extdev/builderapi extdev/collectorapi extdev/markupapi extdev/domainapi extdev/parserapi extdev/nodes extdev/logging extdev/i18n extdev/utils extdev/deprecated internals/index internals/contributing internals/release-process internals/organization internals/code-of-conduct internals/authors faq glossary changes examples 
resolving references...
done
writing... ~/src/sphinx/doc/usage/restructuredtext/domains.rst:709: WARNING: unknown node type: <desc_signature_line: <desc_annotation...><desc_name...>>
~/src/sphinx/doc/usage/restructuredtext/domains.rst:708: WARNING: unknown node type: <desc_signature_line: <desc_annotation...><strong...>>
~/src/sphinx/doc/usage/restructuredtext/domains.rst:707: WARNING: unknown node type: <desc_signature_line: <#text: 'int'><#text: ' '><desc_name...>>
~/src/sphinx/doc/usage/restructuredtext/domains.rst:708: WARNING: unknown node type: <desc_signature_line: <#text: 'double'><#text: ' '><desc_name...>>
~/src/sphinx/doc/usage/restructuredtext/domains.rst:739: WARNING: unknown node type: <desc_signature_line: <#text: 'int'><#text: ' '><desc_name...>>
~/src/sphinx/doc/usage/restructuredtext/domains.rst:741: WARNING: unknown node type: <desc_signature_line: <#text: 'int'><#text: ' '><desc_name...><desc_parameterl ...>
~/src/sphinx/doc/usage/restructuredtext/domains.rst:771: WARNING: unknown node type: <desc_signature_line: <#text: 'int'><#text: ' '><desc_name...><#text: ' = '><# ...>
~/src/sphinx/doc/usage/restructuredtext/domains.rst:773: WARNING: unknown node type: <desc_signature_line: <#text: 'int'><#text: ' '><desc_name...><desc_parameterl ...>
failed

Exception occurred:
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/writers/texinfo.py", line 1457, in visit_desc_annotation
    if txt == self.desc['desctype'] or \
TypeError: 'NoneType' object is not subscriptable
The full traceback has been saved in /tmp/sphinx-err-x3ku_ka6.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: texinfo] Error 2
```

And the following is the full backtrace file:
```
# Sphinx version: 3.1.2
# Python version: 3.8.3 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.1
# Last messages:
#   internals/authors
#   faq
#   glossary
#   changes
#   examples
#   
#   resolving references...
#   done
#   writing...
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (3.1.2) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (3.1.2) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.1.2) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.doctest (3.1.2) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.todo (3.1.2) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/ext/todo.py
#   sphinx.ext.autosummary (3.1.2) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.extlinks (3.1.2) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/ext/extlinks.py
#   sphinx.ext.intersphinx (3.1.2) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (3.1.2) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.graphviz (3.1.2) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/ext/graphviz.py
#   sphinx.ext.inheritance_diagram (3.1.2) from ~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/ext/inheritance_diagram.py
Traceback (most recent call last):
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(['__all__'], to_build)
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/builders/texinfo.py", line 127, in write
    docwriter.write(doctree, destination)
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/writers/texinfo.py", line 140, in translate
    self.document.walkabout(visitor)
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 13 more times]
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/docutils/nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/util/docutils.py", line 468, in dispatch_visit
    method(node)
  File "~/.virtualenvs/python-3.8/lib/python3.8/site-packages/sphinx/writers/texinfo.py", line 1457, in visit_desc_annotation
    if txt == self.desc['desctype'] or \
TypeError: 'NoneType' object is not subscriptable
```

**Expected behavior**
I expected no error, and texinfo file produced in `_build/texinfo_`

**Your project**
https://github.com/sphinx-doc/sphinx.git

**Environment info**
- OS: Arch Linux
- Python version: [e.g. 3.8.3]
- Sphinx version: [e.g. 3.1.2]
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**

- [e.g. URL or Ticket]

**Comment by tk0miya** [comment]
Thank you for reporting. This lets us know texinfo writer contains 3 kinds of bugs.

* It does not support nested object-description
* It does not support a desc_annotation node outside of desc_signature
* It does not support a desc_signature_line node

I'll try to fix them all.

@jakobandersen Is the second case an intended structure of doctree? I found it in here:
https://github.com/sphinx-doc/sphinx/blob/d8064a8b8fe2b6b921a5409eeb636418b480981a/doc/usage/restructuredtext/domains.rst#L776-L777

And it is rendered as following:
```
<paragraph>A type: <literal classes="xref c c-expr"><desc_annotation xml:space="preserve">const</desc_annotation> <reference internal="True" reftitle="Data" refuri="%usage/restructuredtext/domains#c.Data">Data</reference>*</literal>
(or as text <inline classes="xref c c-texpr"><desc_annotation xml:space="preserve">const</desc_annotation> <reference internal="True" reftitle="Data" refuri="%usage/restructuredtext/domains#c.Data">Data</reference>*</inline>).</paragraph>
```

**Comment by YorkZ** [comment]
Thank you so much @tk0miya for your extremely fast response. I was not sure whether you had fixed this issue in your repo fork, so I cherry picked the commit 6689c0a19, and then installed it in my `virtualenv`. I then tested it, but it seems that the problem was still there. So my guess is that you haven't finished the fix yet right?

**Comment by tk0miya** [comment]
Sorry for rack of information. My PR #7995 fixes only the first two issues. I believe it prevents a crash of the build. I'll work for the last one in another PR.

**Comment by YorkZ** [comment]
Thanks a lot @tk0miya .

**Comment by tk0miya** [comment]
Now I added a commit to #7995 to fix the warnings.

**Comment by YorkZ** [comment]
I cherry picked the two commits, and it works now. Fantastic @tk0miya! So when will your fixes be merged to `3.x`?

**Comment by tk0miya** [comment]
Now I'm waiting for the answer from @jakobandersen . Depending on the answer, I need to modify my PR.

>@jakobandersen Is the second case an intended structure of doctree? I found it in here:

**Comment by jakobandersen** [comment]
> Now I'm waiting for the answer from @jakobandersen . Depending on the answer, I need to modify my PR.
> 
> > @jakobandersen Is the second case an intended structure of doctree? I found it in here:

Yes, this is intentional. The ``expr`` roles in the C and C++ domains render types and expressions as inline text, but with hyperlinking. The assumption (by all domains it seems) is that ``desc_annotation`` is a markup construct only.

In the long run I suggest we at some point add a new node type that contains text with the entity type, which can then be removed/ignored by writers in non-haxy way.

**Comment by tk0miya** [comment]
I thought `desc_*` nodes should not appear outside of `desc_signature` at first. But it is still inside of the `desc` node. So nothing is prohibited. Sorry for the noise. I'm merging my PR now.
