### ISSUE TITLE
UnicodeDecodeError in environment.py

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#80]
This bug is in Sphinx 0.5.1

Under some situations the Sphinx throws this exception:

Traceback (most recent call last):
  File "c:\python26\lib\site-packages\Sphinx-0.5.1-py2.6.egg\sphinx\cmdline.py", line 151, in main
    app.build(all_files, filenames)
  File "c:\python26\lib\site-packages\Sphinx-0.5.1-py2.6.egg\sphinx\application.py", line 138, in build
    self.builder.build_update()
  File "c:\python26\lib\site-packages\Sphinx-0.5.1-py2.6.egg\sphinx\builder.py", line 250, in build_update
    'out of date' &#37; len(to_build))
  File "c:\python26\lib\site-packages\Sphinx-0.5.1-py2.6.egg\sphinx\builder.py", line 293, in build
    self.finish()
  File "c:\python26\lib\site-packages\Sphinx-0.5.1-py2.6.egg\sphinx\builder.py", line 539, in finish
    genindex = self.env.create_index(self)
  File "c:\python26\lib\site-packages\Sphinx-0.5.1-py2.6.egg\sphinx\environment.py", line 1222, in create_index
    return [(key, list(group)) for (key, group) in groupby(newlist, keyfunc)]
  File "c:\python26\lib\site-packages\Sphinx-0.5.1-py2.6.egg\sphinx\environment.py", line 1217, in keyfunc
    if letter in ltrs:
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8a in position 26: ordinal not in range(128)

This is because string.uppercase is _NOT_ a unicode string but can contain non-ascii characters. It is a locale dependant string and changes if locale.setlocale() is called. Therefore it has to be converted to unicode first through the current encoding. On my machine it is for example:
'ABCDEFGHIJKLMNOPQRSTUVWXYZ\x8a\x8c\x8e\x9f\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd8\xd9\xda\xdb\xdc\xdd\xde'

Since 'ltrs' is created from string.uppercase, the code crashes.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/80
- Originally reported by: Anonymous
- Originally created at: 2009-01-02T12:16:34.027

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-01-02 13:54:05+00:00_

Changeset <<cset 8af0caea30353cfc39c3f900fed321f6ef23db0a>>:

Fix #80: use string.ascii_\* constants in case locale.setlocale() is
somehow called which then leads to UnicodeErrors.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-01-02 13:55:06+00:00_

Do you know what calls setlocale() in your environment?

Anyway, fixed in <<cset 8af0caea30353cfc39c3f900fed321f6ef23db0a>>

**Comment by shimizukawa** [comment]
_From Anonymous on 2009-01-02 18:00:40+00:00_

Now that you say it, it's clear why it only breaks on some runs at my documentation. When a file that uses autodoc has to be updated, the imported module might call locale.setlocale(), as it is more an application than a normal module/package.
