### ISSUE TITLE
DefinitionError: Error when parsing function declaration

### ISSUE THREAD

**Issue by xvitaly** [sphinx-doc/sphinx#8013]
**Describe the bug**
An exception occurred while building the fmt's 7.0.1 documentation.

**To Reproduce**
```
$ git clone https://github.com/fmtlib/fmt.git
$ cmake .
$ cmake --build .
```

**Expected behavior**
Successful build.

**Environment info**
- OS: Linux, Fedora 33
- Python version: 3.8.3
- Sphinx version: 3.1.1
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**
Exception occurred:
```
  File "/usr/lib/python3.9/site-packages/sphinx/domains/cpp.py", line 6099, in _parse_type
    raise self._make_multi_error(prevErrors, header)
sphinx.util.cfamily.DefinitionError: Error when parsing function declaration.
If the function has no return type:
  Error in declarator or parameters-and-qualifiers
  Invalid C++ declaration: Expecting "(" in parameters-and-qualifiers. [error at 128]
    template<typename CompiledFormat, typename... Args, typename Char = typename CompiledFormat::char_type, CompiledFormat> ::value std::basic_string< Char > format (const CompiledFormat &cf, const Args &... args)
    --------------------------------------------------------------------------------------------------------------------------------^
If the function has a return type:
  Error in declarator or parameters-and-qualifiers
  If pointer to member declarator:
    Invalid C++ declaration: Expected '::' in pointer to member (function). [error at 154]
      template<typename CompiledFormat, typename... Args, typename Char = typename CompiledFormat::char_type, CompiledFormat> ::value std::basic_string< Char > format (const CompiledFormat &cf, const Args &... args)
      ----------------------------------------------------------------------------------------------------------------------------------------------------------^
  If declarator-id:
    Invalid C++ declaration: Expecting "(" in parameters-and-qualifiers. [error at 154]
      template<typename CompiledFormat, typename... Args, typename Char = typename CompiledFormat::char_type, CompiledFormat> ::value std::basic_string< Char > format (const CompiledFormat &cf, const Args &... args)
      ----------------------------------------------------------------------------------------------------------------------------------------------------------^
The full traceback has been saved in /tmp/sphinx-err-363v0ipx.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Traceback (most recent call last):
  File "/builddir/build/BUILD/fmt-7.0.1/doc/build.py", line 72, in <module>
    build_docs(sys.argv[1])
  File "/builddir/build/BUILD/fmt-7.0.1/doc/build.py", line 53, in build_docs
    check_call([sphinx_build,
  File "/usr/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
```

- Fedora RHBZ ticket: https://bugzilla.redhat.com/show_bug.cgi?id=1856369

**Comment by jakobandersen** [comment]
There seems to be something wrong with the signature. After the template parameter list there is a ``::value``.

**Comment by xvitaly** [comment]
@jakobandersen Why did you close this issue?

**Comment by jakobandersen** [comment]
As far as I can see, it's not a valid C++ signature, so the error is correct. Running it through GCC 9 I get
```
test.cpp:1:123: error: ‘value’ in namespace ‘::’ does not name a type
    1 | template<typename CompiledFormat, typename... Args, typename Char = typename CompiledFormat::char_type, CompiledFormat> ::value std::basic_string< Char > format (const CompiledFormat &cf, const Args &... args);
      |                                                                                                                           ^~~~~
```

**Comment by xvitaly** [comment]
> As far as I can see, it's not a valid C++ signature, so the error is correct. Running it through GCC 9 I get

It builds absolutely fine even by GCC 6: https://travis-ci.org/github/fmtlib/fmt

**Comment by jakobandersen** [comment]
I think it's a typo in the docs. The error above is from copying the signature in the error message and trying to compile it.

**Comment by jakobandersen** [comment]
Just noticed you use Breathe, so it may be Doxgen or Breathe that does something wonky.

**Comment by jakobandersen** [comment]
Right, assuming I found the right signature (https://github.com/fmtlib/fmt/blob/master/include/fmt/compile.h#L623), then my best guess is that Doxygen (1.8.17) trips over the FMT_ENABLE_IF. The XML (``namespacefmt.xml``) I found is
```xml
      <memberdef kind="function" id="compile_8h_1a8986689468b2c64b5fe476a3f11e19b9" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <templateparamlist>
          <param>
            <type>typename CompiledFormat</type>
          </param>
          <param>
            <type>typename...</type>
            <declname>Args</declname>
            <defname>Args</defname>
          </param>
          <param>
            <type>typename Char</type>
            <defval>typename CompiledFormat::char_type</defval>
          </param>
          <param>
            <type>CompiledFormat</type>
          </param>
        </templateparamlist>
        <type>::value std::basic_string&lt; Char &gt;</type>
        <definition>::value std::basic_string&lt;Char&gt; fmt::format</definition>
        <argsstring>(const CompiledFormat &amp;cf, const Args &amp;... args)</argsstring>
        <name>format</name>
        <param>
          <type>const CompiledFormat &amp;</type>
          <declname>cf</declname>
        </param>
        <param>
          <type>const Args &amp;...</type>
          <declname>args</declname>
        </param>
        ...
      </memberdef>
```
which has the strange ``::value`` in the beginning of the ``<type>`` tag, which encodes the return type.

**Comment by tchaikov** [comment]
thanks @jakobandersen, i filed https://github.com/doxygen/doxygen/issues/7927 instead for tracking this issue.
