### ISSUE TITLE
Sphinx PDF errors caused by citations.

### ISSUE THREAD

**Issue by alwaeles** [sphinx-doc/sphinx#8029]
**Describe the bug**
When building a PDF with a citation **reference** in, rst2pdf crashes with `IndexError: list index out of range`

**To Reproduce**
[See on my repo](https://github.com/Axelandre42/GIA#procedure).

**Expected behavior**
I wish I could get a PDF out of that.

**Your project**
Here: https://github.com/Axelandre42/GIA

**Screenshots**
I got logs:

```
[ERROR] pdfbuilder.py:149 list index out of range
Traceback (most recent call last):
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\pdfbuilder.py", line 146, in write
    docwriter.write(doctree, destination)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\docutils\writers\__init__.py", line 78, in write
    self.translate()
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\pdfbuilder.py", line 625, in translate
    createpdf.RstToPdf(sphinx=True,
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\createpdf.py", line 554, in createPdf
    elements = self.gen_elements(self.doctree)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 253, in elemdispatch
    elements = self.getelements(client, node, style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 228, in getelements
    elements = self.gather_elements(client, node, style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 208, in gather_elements
    return client.gather_elements(node, style=style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\createpdf.py", line 386, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 253, in elemdispatch
    elements = self.getelements(client, node, style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 228, in getelements
    elements = self.gather_elements(client, node, style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\genelements.py", line 433, in gather_elements
    elements = client.gather_elements(node)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\createpdf.py", line 386, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 253, in elemdispatch
    elements = self.getelements(client, node, style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 228, in getelements
    elements = self.gather_elements(client, node, style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 208, in gather_elements
    return client.gather_elements(node, style=style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\createpdf.py", line 386, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 253, in elemdispatch
    elements = self.getelements(client, node, style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 228, in getelements
    elements = self.gather_elements(client, node, style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 208, in gather_elements
    return client.gather_elements(node, style=style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\createpdf.py", line 386, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 253, in elemdispatch
    elements = self.getelements(client, node, style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 228, in getelements
    elements = self.gather_elements(client, node, style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\genelements.py", line 433, in gather_elements
    elements = client.gather_elements(node)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\createpdf.py", line 386, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 253, in elemdispatch
    elements = self.getelements(client, node, style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 228, in getelements
    elements = self.gather_elements(client, node, style)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\genelements.py", line 186, in gather_elements
    return [Paragraph(client.gen_pdftext(node), style)]
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 283, in textdispatch
    text = self.get_text(client, node, replaceEnt)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 269, in get_text
    return client.gather_pdftext(node)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\createpdf.py", line 376, in gather_pdftext
    return ''.join([self.gen_pdftext(n, replaceEnt)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\createpdf.py", line 376, in <listcomp>
    return ''.join([self.gen_pdftext(n, replaceEnt)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 283, in textdispatch
    text = self.get_text(client, node, replaceEnt)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 269, in get_text
    return client.gather_pdftext(node)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\createpdf.py", line 376, in gather_pdftext
    return ''.join([self.gen_pdftext(n, replaceEnt)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\createpdf.py", line 376, in <listcomp>
    return ''.join([self.gen_pdftext(n, replaceEnt)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\basenodehandler.py", line 282, in textdispatch
    pre, post = self.get_pre_post(client, node, replaceEnt)
  File "c:\users\axela\appdata\local\programs\python\python38\lib\site-packages\rst2pdf\genpdftext.py", line 243, in get_pre_post
    r = client.styleToTags(node['classes'][0])
IndexError: list index out of range
```

**Environment info**
- OS: Windows 10
- Python version: 3.8.5
- Sphinx version: 3.1.2
- Sphinx extensions:  rst2pdf
- Extra tools: none involved.

**Additional context**
Currently none.

**Comment by tk0miya** [comment]
Thank you for reporting. But the error was raised inside rst2pdf extension. Please report this into their project.
Thanks,
