### ISSUE TITLE
make html;

### ISSUE THREAD

**Issue by EdwinPuertas** [sphinx-doc/sphinx#8150]
```
# Sphinx version: 3.2.1
# Python version: 3.8.3 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "C:\Anaconda3\lib\site-packages\sphinx\application.py", line 225, in __init__
    self._init_i18n()
  File "C:\Anaconda3\lib\site-packages\sphinx\application.py", line 292, in _init_i18n
    for catalog in repo.catalogs:
  File "C:\Anaconda3\lib\site-packages\sphinx\util\i18n.py", line 115, in catalogs
    for basedir, filename in self.pofiles:
  File "C:\Anaconda3\lib\site-packages\sphinx\util\i18n.py", line 100, in pofiles
    for locale_dir in self.locale_dirs:
  File "C:\Anaconda3\lib\site-packages\sphinx\util\i18n.py", line 95, in locale_dirs
    if path.exists(path.join(locale_dir, self.language, 'LC_MESSAGES')):
  File "C:\Anaconda3\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Anaconda3\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'
```

**Comment by tk0miya** [comment]
What value did you set to `locale_dirs` and `language`? It seems the wrong value is set.

**Comment by tk0miya** [comment]
I'm closing this now. Please feel free to reopen if you are still in the problem.
Thanks,
