### ISSUE TITLE
init function of Stemmer returned uninitialized object

### ISSUE THREAD

**Issue by gutiersa** [sphinx-doc/sphinx#8181]
**Describe the bug**
I am using FreeBSD 12.1_9,  I am just updating ports using portmaster. I get this problem with cmake update. This is my log:

```
Sphinx version: 3.2.1
Python version: 3.7.9 (CPython)
Docutils version: 0.15.2 release
Jinja2 version: 2.10.1
Last messages:

Loaded extensions:
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
args.tags, args.verbosity, args.jobs, args.keep_going)
File "/usr/local/lib/python3.7/site-packages/sphinx/application.py", line 240, in init
self.setup_extension(extension)
File "/usr/local/lib/python3.7/site-packages/sphinx/application.py", line 398, in setup_extension
self.registry.load_extension(self, extname)
File "/usr/local/lib/python3.7/site-packages/sphinx/registry.py", line 409, in load_extension
mod = import_module(extname)
File "/usr/local/lib/python3.7/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1006, in _gcd_import
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "", line 728, in exec_module
File "", line 219, in _call_with_frames_removed
File "/usr/local/lib/python3.7/site-packages/sphinx/builders/epub3.py", line 20, in
from sphinx.builders import _epub_base
File "/usr/local/lib/python3.7/site-packages/sphinx/builders/_epub_base.py", line 25, in
from sphinx.builders.html import BuildInfo, StandaloneHTMLBuilder
File "/usr/local/lib/python3.7/site-packages/sphinx/builders/html/init.py", line 39, in
from sphinx.search import js_index
File "/usr/local/lib/python3.7/site-packages/sphinx/search/init.py", line 125, in
from sphinx.search.en import SearchEnglish
File "/usr/local/lib/python3.7/site-packages/sphinx/search/en.py", line 14, in
from sphinx.util.stemmer import get_stemmer
File "/usr/local/lib/python3.7/site-packages/sphinx/util/stemmer/init.py", line 14, in
from Stemmer import Stemmer as _PyStemmer
SystemError: init function of Stemmer returned uninitialized object
```

To reproduce the error:

```
$sudo portmaster cmake

```

**Comment by tk0miya** [comment]
Could you check what module is returned by `import Stemmer`? Sphinx expect it returns pystemmer module: https://github.com/snowballstem/pystemmer/

**Comment by gutiersa** [comment]
this is what I get:
import: unable to open X server `' @ error/import.c/ImportImageCommand/344.
But I have a headless box. I don't use X server

I do have py37-pystemmer installed

**Comment by tk0miya** [comment]
I think the trouble about X server is not related to the trouble of pystemmer. To investigate pystemmer's, could you check the pystemmer module is importable? If SystemError is happened, it would be an error of pystemmer module itself. On my local, on macOS Catalina + Python 3.8.2, it can be imported expectedly.
```
$ python
Python 3.8.2 (default, Mar  2 2020, 00:44:41)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from Stemmer import Stemmer as _PyStemmer
>>> _PyStemmer
<class 'Stemmer.Stemmer'>
>>>
```
