### ISSUE TITLE
another error creating django doc

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#827]
writing output... [  5&#37;] howto/apache-auth  
Exception occurred:
  File "/Library/Python/2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/writers/html.py", line 522, in visit_row
    self._table_row_index += 1
AttributeError: DjangoHTMLTranslator instance has no attribute '_table_row_index'
The full traceback has been saved in /var/folders/nb/1vvq4n_91h73g_t66xm3g4lc0000gn/T/sphinx-err-2rTDDl.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at http://groups.google.com/group/sphinx-dev/,
or report them in the tracker at https://bitbucket.org/birkenfeld/sphinx/issues/. Thanks!
make: **\* [html] Error 1

Log file contents:
# Sphinx version: 1.1.2
# Python version: 2.7.1
# Docutils version: 0.8.1 release
# Jinja2 version: 2.6

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/Library/Python/2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/Library/Python/2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/builders/**init**.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "/Library/Python/2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/builders/**init**.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Library/Python/2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/builders/**init**.py", line 292, in write
    self.write_doc(docname, doctree)
  File "/Library/Python/2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/builders/html.py", line 419, in write_doc
    self.docwriter.write(doctree, destination)
  File "/Library/Python/2.7/site-packages/docutils-0.8.1-py2.7.egg/docutils/writers/**init**.py", line 77, in write
    self.translate()
  File "/Library/Python/2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/writers/html.py", line 38, in translate
    self.document.walkabout(visitor)
  File "/Library/Python/2.7/site-packages/docutils-0.8.1-py2.7.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Library/Python/2.7/site-packages/docutils-0.8.1-py2.7.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Library/Python/2.7/site-packages/docutils-0.8.1-py2.7.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Library/Python/2.7/site-packages/docutils-0.8.1-py2.7.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Library/Python/2.7/site-packages/docutils-0.8.1-py2.7.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Library/Python/2.7/site-packages/docutils-0.8.1-py2.7.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/Library/Python/2.7/site-packages/docutils-0.8.1-py2.7.egg/docutils/nodes.py", line 165, in walkabout
    visitor.dispatch_visit(self)
  File "/Library/Python/2.7/site-packages/docutils-0.8.1-py2.7.egg/docutils/nodes.py", line 1604, in dispatch_visit
    return method(node)
  File "/Library/Python/2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/writers/html.py", line 522, in visit_row
    self._table_row_index += 1
AttributeError: DjangoHTMLTranslator instance has no attribute '_table_row_index'

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/827
- Originally reported by: Anonymous
- Originally created at: 2011-11-23T15:09:25.239

**Comment by shimizukawa** [comment]
_From John Woltman on 2011-12-07 12:41:09+00:00_

I have this problem too; my versions match the OP's.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2012-01-29 10:39:03+00:00_

Duplicate of #863.
