### ISSUE TITLE
IndexError: list index out of range in docutils/nodes.py when running `make html`

### ISSUE THREAD

**Issue by fhennecker** [sphinx-doc/sphinx#8300]
**Describe the bug**

`make html` fails with the traceback attached below, on a project which has been building fine so far, and which builds without any issue on the exact same commit in other environments.

I investigated a bit and managed to pinpoint the source of the problem down to the package responsible for this failure: the build runs fine when we use `autodocsumm==0.1.13` and fails when we have `autodocsumm==0.2.0` and above.

I'm unsure if this is the right place to report this as the traceback doesn't make it clear which package exactly is responsible for this bug.

**To Reproduce**

Unfortunately I didn't manage to create a small reproducible example and the project I'm working on is proprietary, but I'm obviously available to run more tests to pinpoint the problem.

**Environment info**
- OS: reproduced this both on Mac OS Catalina and Ubuntu 18.04
- Python version: 3.7.3
- Sphinx version and extensions: see below in the automated bug report

**Automated bug report**

```
# Sphinx version: 3.2.1
# Python version: 3.7.3 (CPython)
# Docutils version: 0.14
# Jinja2 version: 2.10.1
# Last messages:
#   reading sources... [  3%] getting_started
# ...
#   reading sources... [ 15%] (redacted)
# Loaded extensions:
#   sphinx.ext.mathjax (3.2.1) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (3.2.1) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.2.1) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.napoleon (3.2.1) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.todo (3.2.1) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (3.2.1) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.imgmath (3.2.1) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/ext/imgmath.py
#   sphinx.ext.linkcode (3.2.1) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/ext/linkcode.py
#   recommonmark (0.6.0) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/recommonmark/__init__.py
#   sphinx.ext.autosummary (3.2.1) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/ext/autosummary/__init__.py
#   autodocsumm (3.2.1) from /home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/autodocsumm/__init__.py
Traceback (most recent call last):
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/io.py", line 223, in read_doc
    pub.publish()
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/io.py", line 128, in read
    self.parse()
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/parsers.py", line 102, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 157, in run
    result = parse_generated_content(self.state, params.result, documenter)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 100, in parse_generated_content
    nested_parse_with_titles(state, content, node)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/util/nodes.py", line 341, in nested_parse_with_titles
    return state.nested_parse(content, 0, node, match_titles=1)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/ext/autosummary/__init__.py", line 246, in run
    items = self.get_items(names)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/ext/autosummary/__init__.py", line 385, in get_items
    summary = extract_summary(self.bridge.result.data[:], self.state.document)
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/sphinx/ext/autosummary/__init__.py", line 550, in extract_summary
    if not isinstance(node[0], nodes.paragraph):
  File "/home/florentin/.pyenv/versions/3.7.3/envs/sensei/lib/python3.7/site-packages/docutils/nodes.py", line 569, in __getitem__
    return self.children[key]
IndexError: list index out of range
```

**Comment by fhennecker** [comment]
To make it easier to read for others having this issue, the current workaround is to make sure your version of autodocsumm is not higher than `autodocsumm==0.1.13`

**Comment by tk0miya** [comment]
Sorry for the late response. I suppose it is a bug of the extension because it goes well after you downgrade it.
I guess there is nothing to do from Sphinx side.
Thanks,
