### ISSUE TITLE
make latex error with .. math::

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#838]
```
# Sphinx version: 1.1.2
# Python version: 2.6.5
# Docutils version: 0.8.1 release
# Jinja2 version: 2.3.1
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.1.2-py2.6.egg/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.1.2-py2.6.egg/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.1.2-py2.6.egg/sphinx/builders/__init__.py", line 191, in build_update
    self.build(['__all__'], to_build)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.1.2-py2.6.egg/sphinx/builders/__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.1.2-py2.6.egg/sphinx/builders/latex.py", line 104, in write
    docwriter.write(doctree, destination)
  File "/usr/local/lib/python2.6/dist-packages/docutils-0.8.1-py2.6.egg/docutils/writers/__init__.py", line 77, in write
    self.translate()
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.1.2-py2.6.egg/sphinx/writers/latex.py", line 94, in translate
    self.document.walkabout(visitor)
  File "/usr/local/lib/python2.6/dist-packages/docutils-0.8.1-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python2.6/dist-packages/docutils-0.8.1-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python2.6/dist-packages/docutils-0.8.1-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python2.6/dist-packages/docutils-0.8.1-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python2.6/dist-packages/docutils-0.8.1-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python2.6/dist-packages/docutils-0.8.1-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python2.6/dist-packages/docutils-0.8.1-py2.6.egg/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python2.6/dist-packages/docutils-0.8.1-py2.6.egg/docutils/nodes.py", line 165, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/local/lib/python2.6/dist-packages/docutils-0.8.1-py2.6.egg/docutils/nodes.py", line 1604, in dispatch_visit
    return method(node)
  File "/usr/local/lib/python2.6/dist-packages/Sphinx-1.1.2-py2.6.egg/sphinx/writers/latex.py", line 1510, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: math_block
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/838
- Originally reported by: [lyhcode](https://bitbucket.org/lyhcode)
- Originally created at: 2011-12-08T07:20:27.167

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2012-01-29 10:49:12+00:00_

You have to enable one of the math extensions for this to work.
