### ISSUE TITLE
Autodoc extension causes Sphinx 3.3.0 to try (and fail) to pickle a code object.

### ISSUE THREAD

**Issue by sjjessop** [sphinx-doc/sphinx#8383]
**Describe the bug**

When I run "make html" for the attached project, I get an error `TypeError: can't pickle code objects`, at the point where Sphinx is trying to save its environment

This has started happening with Sphinx 3.3.0. With Sphinx 3.2.1 the documentation builds OK.

**To Reproduce**

In the attached zip file:

$ cd docn
$ make html
```
Running Sphinx v3.3.0
WARNING: html_static_path entry '_static' does not exist
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... failed

Exception occurred:
  File "c:\users\steve\miniconda3\envs\sphinxtest\lib\site-packages\sphinx\builders\__init__.py", line 328, in build
    pickle.dump(self.env, f, pickle.HIGHEST_PROTOCOL)
TypeError: can't pickle code objects
The full traceback has been saved in C:\Users\Steve\AppData\Local\Temp\sphinx-err-ngutew7a.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks
```

Contents of log file:
```
# Sphinx version: 3.3.0
# Python version: 3.7.9 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:
#   updating environment:
#   [new config]
#   2 added, 0 changed, 0 removed
#   reading sources... [ 50%] drv
#   reading sources... [100%] index
#   
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (3.3.0) from c:\users\steve\miniconda3\envs\sphinxtest\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from c:\users\steve\miniconda3\envs\sphinxtest\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.2) from c:\users\steve\miniconda3\envs\sphinxtest\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from c:\users\steve\miniconda3\envs\sphinxtest\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from c:\users\steve\miniconda3\envs\sphinxtest\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.3) from c:\users\steve\miniconda3\envs\sphinxtest\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from c:\users\steve\miniconda3\envs\sphinxtest\lib\site-packages\alabaster\__init__.py
#   sphinx.ext.autodoc.type_comment (3.3.0) from c:\users\steve\miniconda3\envs\sphinxtest\lib\site-packages\sphinx\ext\autodoc\type_comment.py
#   sphinx.ext.autodoc (3.3.0) from c:\users\steve\miniconda3\envs\sphinxtest\lib\site-packages\sphinx\ext\autodoc\__init__.py
Traceback (most recent call last):
  File "c:\users\steve\miniconda3\envs\sphinxtest\lib\site-packages\sphinx\cmd\build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "c:\users\steve\miniconda3\envs\sphinxtest\lib\site-packages\sphinx\application.py", line 352, in build
    self.builder.build_update()
  File "c:\users\steve\miniconda3\envs\sphinxtest\lib\site-packages\sphinx\builders\__init__.py", line 299, in build_update
    len(to_build))
  File "c:\users\steve\miniconda3\envs\sphinxtest\lib\site-packages\sphinx\builders\__init__.py", line 328, in build
    pickle.dump(self.env, f, pickle.HIGHEST_PROTOCOL)
TypeError: can't pickle code objects
```

**Expected behavior**

Docs build successfully.

**Your project**

[sphinx_test.zip](https://github.com/sphinx-doc/sphinx/files/5505061/sphinx_test.zip)

My full project is https://github.com/sjjessop/omnidice , but the attached zip shows the issue.

**Environment info**
- OS: Windows 10, but the problem occurred on readthedocs.io as well, so also whatever Linux they're using by default.
- Python version: 3.7.9
- Sphinx version: 3.3.0
- Sphinx extensions:  sphinx.ext.autodoc only

Environment was built as follows:

$ conda create --name=sphinxtest python=3.7
$ conda activate sphinxtest
$ pip install sphinx

Resulting environment:

$ pip freeze
```
alabaster==0.7.12
Babel==2.8.0
certifi==2020.6.20
chardet==3.0.4
colorama==0.4.4
docutils==0.16
idna==2.10
imagesize==1.2.0
Jinja2==2.11.2
MarkupSafe==1.1.1
packaging==20.4
Pygments==2.7.2
pyparsing==2.4.7
pytz==2020.4
requests==2.24.0
six==1.15.0
snowballstemmer==2.0.0
Sphinx==3.3.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
urllib3==1.25.11
wincertstore==0.2
```

$ conda list
```
# packages in environment at C:\Users\Steve\Miniconda3\envs\sphinxtest:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
babel                     2.8.0                    pypi_0    pypi
ca-certificates           2020.10.14                    0
certifi                   2020.6.20          pyhd3eb1b0_3
chardet                   3.0.4                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
idna                      2.10                     pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
openssl                   1.1.1h               he774522_0
packaging                 20.4                     pypi_0    pypi
pip                       20.2.4           py37haa95532_0
pygments                  2.7.2                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.7.9                h60c2a47_0
pytz                      2020.4                   pypi_0    pypi
requests                  2.24.0                   pypi_0    pypi
setuptools                50.3.0           py37haa95532_1
six                       1.15.0                   pypi_0    pypi
snowballstemmer           2.0.0                    pypi_0    pypi
sphinx                    3.3.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.33.0               h2a8f88b_0
urllib3                   1.25.11                  pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wheel                     0.35.1                     py_0
wincertstore              0.2                      py37_0
zlib                      1.2.11               h62dcd97_4
```

**Additional context**

N/A.

**Comment by sjjessop** [comment]
I've realised straight after posting this, that without the workaround in my code for https://github.com/sphinx-doc/sphinx/issues/6518 (in `__init__.py`) the issue doesn't happen. So I'll look at this a bit more, and I may discover it's not a bug at all. Please don't waste your time on it yet!

**Comment by sjjessop** [comment]
Confirmed: removing my hack and using `autodoc_type_aliases` builds exactly the docs I want.
