### ISSUE TITLE
Failed to generate PDF

### ISSUE THREAD

**Issue by yun-zero** [sphinx-doc/sphinx#8384]
**Describe the bug**

**To Reproduce**
```
<Paste your command-line here which cause the problem>

$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

**Expected behavior**

**Your project**
Link to your sphinx project, or attach zipped small project sample.

**Screenshots**

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: [e.g. 3.7.1]
- Sphinx version: [e.g. 1.8.2]
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [e.g. Browser, tex o

```
# Sphinx version: 1.4.9
# Python version: 3.8.5 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.11.2
# Last messages:
#   /home/p1024/work_dir/linux/Documentation/dev-tools/kselftest.rst:15: WARNING: Could not lex literal_block as "c". Highlighting skipped.
#   done
#   processing kernel-doc-guide.tex...
#   doc-guide/index
#   doc-guide/sphinx
#   doc-guide/kernel-doc
#   doc-guide/parse-headers
#   
#   resolving references...
#   writing...
# Loaded extensions:
#   kerneldoc (1.0) from /home/p1024/work_dir/linux/Documentation/sphinx/kerneldoc.py
#   rstFlatTable (1.0) from /home/p1024/work_dir/linux/Documentation/sphinx/rstFlatTable.py
#   kernel_include (1.0) from /home/p1024/work_dir/linux/Documentation/sphinx/kernel_include.py
#   cdomain (1.0) from /home/p1024/work_dir/linux/Documentation/sphinx/cdomain.py
#   kfigure (1.0.0) from /home/p1024/work_dir/linux/Documentation/sphinx/kfigure.py
#   sphinx.ext.imgmath (1.4.9) from /home/p1024/work_dir/linux/sphinx_1.4/lib/python3.8/site-packages/sphinx/ext/imgmath.py
#   alabaster (0.7.12) from /home/p1024/work_dir/linux/sphinx_1.4/lib/python3.8/site-packages/alabaster/__init__.py
Traceback (most recent call last):
  File "/home/p1024/work_dir/linux/sphinx_1.4/lib/python3.8/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/p1024/work_dir/linux/sphinx_1.4/lib/python3.8/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/home/p1024/work_dir/linux/sphinx_1.4/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 246, in build_update
    self.build(['__all__'], to_build)
  File "/home/p1024/work_dir/linux/sphinx_1.4/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/p1024/work_dir/linux/sphinx_1.4/lib/python3.8/site-packages/sphinx/builders/latex.py", line 133, in write
    docwriter.write(doctree, destination)
  File "/home/p1024/work_dir/linux/sphinx_1.4/lib/python3.8/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/p1024/work_dir/linux/sphinx_1.4/lib/python3.8/site-packages/sphinx/writers/latex.py", line 115, in translate
    self.document.walkabout(visitor)
  File "/home/p1024/work_dir/linux/sphinx_1.4/lib/python3.8/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/p1024/work_dir/linux/sphinx_1.4/lib/python3.8/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/p1024/work_dir/linux/sphinx_1.4/lib/python3.8/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 3 more times]
  File "/home/p1024/work_dir/linux/sphinx_1.4/lib/python3.8/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/home/p1024/work_dir/linux/sphinx_1.4/lib/python3.8/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/home/p1024/work_dir/linux/Documentation/sphinx/kfigure.py", line 424, in visit_kernel_render
    kernellog.verbose('visit kernel-render node lang: "%s"' % (srclang))
TypeError: verbose() missing 1 required positional argument: 'message'r something else]
```

**Additional context**

- [e.g. URL or Ticket]

**Comment by tk0miya** [comment]
It seems the error happened inside the kfigure extension. Please ask the maintainer of the extension (or kernellog module?).
```
  File "/home/p1024/work_dir/linux/Documentation/sphinx/kfigure.py", line 424, in visit_kernel_render
    kernellog.verbose('visit kernel-render node lang: "%s"' % (srclang))
TypeError: verbose() missing 1 required positional argument: 'message'r something else]
```
