### ISSUE TITLE
PicklingError appears when I use todolist directive for the first time

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#839]
I use sphinx1.1.2 in ubuntu11.10(python2.6). PicklingError occurs by all means when I use todolist directive for the first time.
How should I evade this problem?

---

```
&#37; make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.1.2
...
build succeeded.
pickling environment... 
Exception occurred:
  File "/usr/local/lib/python2.6/dist-packages/sphinx/environment.py", line 303, in topickle
    pickle.dump(self, picklefile, pickle.HIGHEST_PROTOCOL)
PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
The full traceback has been saved in /tmp/sphinx-err-toQVP_.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1



&#37; cat /tmp/sphinx-err-toQVP_.log
# Sphinx version: 1.1.2
# Python version: 2.6.6
# Docutils version: 0.8.1 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/usr/local/lib/python2.6/dist-packages/sphinx/application.py", line 209, in build
    self.emit('build-finished', None)
  File "/usr/local/lib/python2.6/dist-packages/sphinx/application.py", line 314, in emit
    results.append(callback(self, *args))
  File "/usr/local/lib/python2.6/dist-packages/sphinxfeed.py", line 94, in emit_feed
    builder.env.topickle(path.join(builder.doctreedir, ENV_PICKLE_FILENAME))
  File "/usr/local/lib/python2.6/dist-packages/sphinx/environment.py", line 303, in topickle
    pickle.dump(self, picklefile, pickle.HIGHEST_PROTOCOL)
PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/839
- Originally reported by: [togakushi](https://bitbucket.org/togakushi)
- Originally created at: 2011-12-10T17:58:00.400

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-10 20:27:55+00:00_

Cleaning up old issues; please reopen if this is still a problem.
