### ISSUE TITLE
AttributeError during websupport building

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#840]
I am trying to use `sphinx.websupport`, but its builder raises an `AttributeError` like the following:

```
#!pytb
Traceback (most recent call last):                                              
  File "docserver.py", line 48, in build
    support.build()
  File "/.../sphinx/websupport/__init__.py", line 126, in build
    app.build()
  File "/.../sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/.../sphinx/builders/__init__.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "/.../sphinx/builders/__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/.../sphinx/builders/__init__.py", line 292, in write
    self.write_doc(docname, doctree)
  File "/.../sphinx/builders/websupport.py", line 64, in write_doc
    self.docwriter.write(doctree, destination)
  File "/.../docutils/writers/__init__.py", line 77, in write
    self.translate()
  File "/.../sphinx/writers/html.py", line 38, in translate
    self.document.walkabout(visitor)
  File "/.../docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/.../docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/.../docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/.../docutils/nodes.py", line 165, in walkabout
    visitor.dispatch_visit(self)
  File "/.../sphinx/writers/websupport.py", line 27, in dispatch_visit
    self.handle_visit_commentable(node)
  File "/.../sphinx/writers/websupport.py", line 34, in handle_visit_commentable
    self.add_db_node(node)
  File "/.../sphinx/writers/websupport.py", line 43, in add_db_node
    if not storage.has_node(node.uid):
AttributeError: 'paragraph' object has no attribute 'uid'
```

I don’t understand Sphinx and its websupport in depth, so I cannot debug this issue right now.  Sorry for lack of attached patch. :-(  If anyone tells me some hints helpful for debugging, I will try to resolve it and attach a patch when I succeed.

Thanks!

**Plus**: Actually it was happened in Sphinx **1.1.2**, //not 1.1.1//, but it seems the version 1.1.2 is not listed in the issue tracker yet.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/840
- Originally reported by: Hong Minhee
- Originally created at: 2011-12-13T05:23:09.598

**Comment by shimizukawa** [comment]
_From Hong Minhee on 2012-01-11 09:26:25+00:00_

Note: I did it on a spawned greenlet (using {{{gevent.spawn()}}} function).

**Comment by shimizukawa** [comment]
_From Takafumi Arakaki on 2012-07-27 22:41:15+00:00_

I got the same error when I set todo_include_todos=True.  Setting it to False workarounds the problem.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-10 20:07:57+00:00_

Cleaning up old issues; please reopen if this is still a problem.

**Comment by shimizukawa** [comment]
_From Dmitry Shachnev on 2014-07-13 06:52:13+00:00_

I cannot reopen this issue, so I just filed #1509 with a fresh traceback (with Sphinx 1.2.2) and more details (forwarded from Debian).

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-10-18 07:32:54+00:00_

Removing version: 1.1.1 (automated comment)
