### ISSUE TITLE
Sphinx 3.3.0 incompatible with m2r2 plugin

### ISSUE THREAD

**Issue by shakefu** [sphinx-doc/sphinx#8400]
**Describe the bug**
Sphinx 3.3.0 breaks extensions.

**To Reproduce**
Use m2r2 plugin.
```
root@4ca1af97cb73:/usr/local/src# cat /tmp/sphinx-err-diw8146x.log
# Sphinx version: 3.3.0
# Python version: 3.8.6 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/local/lib/python3.8/site-packages/sphinx/application.py", line 245, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python3.8/site-packages/sphinx/application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/lib/python3.8/site-packages/sphinx/registry.py", line 429, in load_extension
    metadata = setup(app)
  File "/usr/local/lib/python3.8/site-packages/m2r2.py", line 664, in setup
    app.add_source_parser(".md", M2RParser)  # for older sphinx versions
  File "/usr/local/lib/python3.8/site-packages/sphinx/application.py", line 1136, in add_source_parser
    self.registry.add_source_parser(parser, override=override)
  File "/usr/local/lib/python3.8/site-packages/sphinx/registry.py", line 266, in add_source_parser
    for filetype in parser.supported:
AttributeError: 'str' object has no attribute 'supported'
```

**Expected behavior**
Not an error.

**Your project**
https://github.com/networktocode/sphinx-docs

**Environment info**
- OS: Docker Python:3.8
- Python version: 3.8
- Sphinx version: 3.3.0
- Sphinx extensions:  m2r2

**Comment by basnijholt** [comment]
Upstream issue https://github.com/CrossNox/m2r2/issues/13

**Comment by tk0miya** [comment]
Same as #8395. This is a bug of m2r2.
