### ISSUE TITLE
Sphinx doesn't notice circular tocs nicely

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#851]
Assume a broken document set with the following structure:

```
#!python
index.rst:
.. toctree:
   one
   two

one.rst
.. toctree:
   two

two.rst
.. toctree:
   one
   two
```

Now run Sphinx on this, and you see some rather cryptic message from Environment like:

```
#!python
# Sphinx version: 1.1.2
# Python version: 2.7.2
# Docutils version: 0.8 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "D:\sandbox\roadside\win32\debug\img\lib\site-packages\sphinx-1.1.2-py2.7.egg\sphinx\cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "D:\sandbox\roadside\win32\debug\img\lib\site-packages\sphinx-1.1.2-py2.7.egg\sphinx\application.py", line 204, in build
    self.builder.build_update()
  File "D:\sandbox\roadside\win32\debug\img\lib\site-packages\sphinx-1.1.2-py2.7.egg\sphinx\builders\__init__.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "D:\sandbox\roadside\win32\debug\img\lib\site-packages\sphinx-1.1.2-py2.7.egg\sphinx\builders\__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "D:\sandbox\roadside\win32\debug\img\lib\site-packages\sphinx-1.1.2-py2.7.egg\sphinx\builders\__init__.py", line 283, in write
    self.prepare_writing(docnames)
  File "D:\sandbox\roadside\win32\debug\img\lib\site-packages\sphinx-1.1.2-py2.7.egg\sphinx\builders\html.py", line 291, in prepare_writing
    self.relations = self.env.collect_relations()
  File "D:\sandbox\roadside\win32\debug\img\lib\site-packages\sphinx-1.1.2-py2.7.egg\sphinx\environment.py", line 1728, in collect_relations
    collect([(None, 0)], self.config.master_doc, None, None)
  File "D:\sandbox\roadside\win32\debug\img\lib\site-packages\sphinx-1.1.2-py2.7.egg\sphinx\environment.py", line 1726, in collect
    collect([(docname, subindex)] + parents, *args)
  File "D:\sandbox\roadside\win32\debug\img\lib\site-packages\sphinx-
  [a few hundred identical calls elided]
1.1.2-py2.7.egg\sphinx\environment.py", line 1726, in collect
    collect([(docname, subindex)] + parents, *args)
RuntimeError: maximum recursion depth exceeded in cmp
```

This happens in various places in the method, depending on the exact document structure, have also seen it from the include = getinc() call at the start of the collect() method.

Sphinx should detect the include loop and handle it more gracefully.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/851
- Originally reported by: Anonymous
- Originally created at: 2012-01-11T12:49:34.099

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2012-01-29 10:13:53+00:00_

Closes #851: Recognize and warn about circular toctrees, instead of running into recursion errors.

→ <<cset d16875f3e2bdf585a1d44b88651ba1100f2b92c6>>
