### ISSUE TITLE
ImportError: cannot import name AgentClientProxy when trying to generate docs for fabric 1.4 alpha

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#855]
When running make html in Fabric 1.3.4's docs dir I get this error:

```
# Sphinx version: 1.1.2
# Python version: 2.7.0
# Docutils version: 0.8.1 release
# Jinja2 version: 2.6

Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7/lib/python2.7/site-packages/sphinx/cmdline.py", line 188, in main
    warningiserror, tags)
  File "/usr/local/Cellar/python/2.7/lib/python2.7/site-packages/sphinx/application.py", line 102, in __init__
    confoverrides or {}, self.tags)
  File "/usr/local/Cellar/python/2.7/lib/python2.7/site-packages/sphinx/config.py", line 215, in __init__
    exec code in config
  File "/Users/user/Kreationer/programming/python/others/fabric/docs/conf.py", line 173, in <module>
    from fabric.api import local, hide
  File "/Users/user/Kreationer/programming/python/others/fabric/fabric/api.py", line 12, in <module>
    from fabric.operations import (require, prompt, put, get, run, sudo, local,
  File "/Users/user/Kreationer/programming/python/others/fabric/fabric/operations.py", line 18, in <module>
    from ssh.agent import AgentClientProxy
ImportError: cannot import name AgentClientProxy
```

Apparently sphinx-build is evaluating the code when generating, is it supposed to do that?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/855
- Originally reported by: Tuk Bredsdorff
- Originally created at: 2012-01-16T17:22:22.581

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2012-01-16 18:26:43+00:00_

The configuration file is evaluated in the Python interpreter.  The traceback says your {{{conf.py}}} indeed imports the modules in question:
{{{
  File "/Users/user/Kreationer/programming/python/others/fabric/docs/conf.py", line 173, in <module>
    from fabric.api import local, hide
}}}
Refactoring the source code to provide the members you're trying to access (probably version info?) without any other dependencies is the common solution to this problem.

**Comment by shimizukawa** [comment]
_From Tuk Bredsdorff on 2012-01-17 16:27:01+00:00_

Thanks, I'll see if I can patch Fabric or at least notify the developers.
