### ISSUE TITLE
Unresolvable :const: causes uncaught exception

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#859]
If I have a docstring that references an unrecognised const:

```
  def function(args):
      """We use :const:`SOME_NAME`
      """
      pass
```

and try to generate documentation for this (via ".. automodule") then I get an exception:

```
# Sphinx version: 1.1.2
# Python version: 2.7.1+
# Docutils version: 0.7 release
# Jinja2 version: 2.5.5
Traceback (most recent call last):
  File "/home/tibs/bin/sphinx/lib/python2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/home/tibs/bin/sphinx/lib/python2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/home/tibs/bin/sphinx/lib/python2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "/home/tibs/bin/sphinx/lib/python2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/builders/__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/tibs/bin/sphinx/lib/python2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/builders/__init__.py", line 291, in write
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/home/tibs/bin/sphinx/lib/python2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/environment.py", line 1228, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/home/tibs/bin/sphinx/lib/python2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/environment.py", line 1437, in resolve_references
    typ, target, node, contnode)
  File "/home/tibs/bin/sphinx/lib/python2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/domains/python.py", line 676, in resolve_xref
    type, searchmode)
  File "/home/tibs/bin/sphinx/lib/python2.7/site-packages/Sphinx-1.1.2-py2.7.egg/sphinx/domains/python.py", line 630, in find_obj
    if fullname in objects and objects[fullname][1] in objtypes:
TypeError: argument of type 'NoneType' is not iterable
```

Looking at the code:

```
if fullname in objects and objects[fullname][1] in objtypes:
```

it appears that `objtypes`  is None, in this case because there is no definition for SOME_NAME.

(in my case, the constant was defined in a class, and preprending the classname to SOME_NAME fixed the bug - i.e., :const:CLASS_NAME.SOMENAME`)

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/859
- Originally reported by: Tony Ibbs
- Originally created at: 2012-01-20T17:12:13.820

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2012-01-29 09:25:41+00:00_

Closes #859: Fix exception under certain circumstances when not finding appropriate objects to link to.

→ <<cset 5727c053c20c54b66e982c57d01faa92e51c581e>>
