### ISSUE TITLE
Encoding problem with -D and python3

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#862]
It seems that the python3 port of Sphinx does not correctly handle strings vs unicode.

```
Traceback (most recent call last):
  File "/home/hh/.virtualenvs/sweddoc3/lib/python3.1/site-packages/sphinx/cmdline.py", line 138, in main
    val = int(val)
ValueError: invalid literal for int() with base 10: 'SWEDDOC manual'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hh/.virtualenvs/sweddoc3/bin/sphinx-build", line 9, in <module>
    load_entry_point('Sphinx==1.1.2', 'console_scripts', 'sphinx-build')()
  File "/home/hh/.virtualenvs/sweddoc3/lib/python3.1/site-packages/sphinx/__init__.py", line 72, in main
    return cmdline.main(argv)
  File "/home/hh/.virtualenvs/sweddoc3/lib/python3.1/site-packages/sphinx/cmdline.py", line 142, in main
    val = val.decode(likely_encoding)
AttributeError: 'str' object has no attribute 'decode'
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/862
- Originally reported by: [holmboe](https://bitbucket.org/holmboe)
- Originally created at: 2012-01-25T15:17:46.534

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2012-01-29 09:46:46+00:00_

Closes #862: Fix handling of `-D` and `-A` options on Python 3.

→ <<cset b1c5572d8e23e2be9d381044688cacec770c231c>>
