### ISSUE TITLE
python-cryptography<what happen when you do on which document project>

### ISSUE THREAD

**Issue by kloczek** [sphinx-doc/sphinx#8624]
sphinx 3.4.1
```
+ sphinx-build -b man -d python-cryptography docs .
Running Sphinx v3.4.1
Initializing Spelling Checker
WARNING: html_static_path entry '_static' is placed inside outdir
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 58 added, 0 changed, 0 removed
reading sources... [100%] x509/tutorial
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-cryptography.3 { fernet x509/index x509/tutorial x509/certificate-transparency x509/ocsp x509/reference hazmat/primitives/index hazmat/primitives/aead hazmat/primitives/asymmetric/index hazmat/primitives/asymmetric/ed25519 hazmat/primitives/asymmetric/x25519 hazmat/primitives/asymmetric/ed448 hazmat/primitives/asymmetric/x448 hazmat/primitives/asymmetric/ec hazmat/primitives/asymmetric/rsa hazmat/primitives/asymmetric/dh hazmat/primitives/asymmetric/dsa hazmat/primitives/asymmetric/serialization hazmat/primitives/asymmetric/utils hazmat/primitives/constant-time hazmat/primitives/key-derivation-functions hazmat/primitives/keywrap hazmat/primitives/mac/index hazmat/primitives/mac/cmac hazmat/primitives/mac/hmac hazmat/primitives/mac/poly1305 hazmat/primitives/cryptographic-hashes hazmat/primitives/symmetric-encryption hazmat/primitives/padding hazmat/primitives/twofactor exceptions random-numbers hazmat/backends/index hazmat/backends/openssl hazmat/backends/interfaces installation changelog faq development/index development/getting-started development/submitting-patches development/reviewing-patches development/test-vectors development/custom-vectors/secp256k1 development/custom-vectors/rsa-oaep-sha2 development/custom-vectors/arc4 development/custom-vectors/cast5 development/custom-vectors/idea development/custom-vectors/seed development/custom-vectors/hkdf development/c-bindings security limitations api-stability doing-a-release community glossary } failed

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 455, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: Hazmat
The full traceback has been saved in /tmp/sphinx-err-kcl0fxp7.log, if you want to report the issue to the developers.
```
```
$ cat /tmp/sphinx-err-kcl0fxp7.log
# Sphinx version: 3.4.1
# Python version: 3.8.3 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:
#   development/custom-vectors/hkdf
#   development/c-bindings
#   security
#   limitations
#   api-stability
#   doing-a-release
#   community
#   glossary
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (3.4.1) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.1) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (3.4.1) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.4.1) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.doctest (3.4.1) from /usr/lib/python3.8/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.intersphinx (3.4.1) from /usr/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (3.4.1) from /usr/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   cryptography-docs (unknown version) from /home/tkloczko/rpmbuild/BUILD/cryptography-3.3.1/docs/cryptography-docs.py
#   sphinxcontrib.spelling (unknown version) from /usr/lib/python3.8/site-packages/sphinxcontrib/spelling/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 360, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 713, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 103, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 41, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3.8/site-packages/sphinx/util/docutils.py", line 471, in dispatch_visit
    super().dispatch_visit(node)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 1995, in dispatch_visit
    return method(node)
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 455, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: Hazmat
```

**Comment by tk0miya** [comment]
It seems your extension; cryptography-docs does not support manpage output. Please check your own extension.
https://github.com/pyca/cryptography/blob/master/docs/cryptography-docs.py#L53-L57
