### ISSUE TITLE
linux kernel make htmldocs failed

### ISSUE THREAD

**Issue by YuanyeMa** [sphinx-doc/sphinx#8647]
**Describe the bug**
When i run "make htmldocs" under linux kernel source tree. It output :
```
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**To Reproduce**
```

$ git clone https://github.com/torvalds/linux.git
$ cd linux
$ /usr/bin/python3 -m venv sphinx_2.4.4
$ . sphinx_2.4.4/bin/activate
$ pip install -r ./Documentation/sphinx/requirements.txt
$ make htmldocs
```

**Expected behavior**
```
make htmldocs
  SPHINX  htmldocs --> file:///home/myye/linux/Documentation/output
  PARSE   include/uapi/linux/dvb/audio.h
  PARSE   include/uapi/linux/dvb/ca.h
  PARSE   include/uapi/linux/dvb/dmx.h
  PARSE   include/uapi/linux/dvb/frontend.h
  PARSE   include/uapi/linux/dvb/net.h
  PARSE   include/uapi/linux/dvb/video.h
  PARSE   include/uapi/linux/videodev2.h
  PARSE   include/uapi/linux/media.h
  PARSE   include/uapi/linux/cec.h
  PARSE   include/uapi/linux/lirc.h
enabling CJK for LaTeX builder
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:5073: warning: Function parameter or member 'sar_capa' not described in 'wiphy'
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:4302: warning: Function parameter or member 'set_sar_specs' not described in 'cfg80211_ops'
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/cfg80211.h:1759: warning: Cannot understand  * @struct cfg80211_sar_chan_ranges - sar frequency ranges
 on line 1759 - I thought it was a doc line
./include/net/mac80211.h:4200: warning: Function parameter or member 'set_sar_specs' not described in 'ieee80211_ops'
/home/myye/linux/Documentation/virt/kvm/api.rst:4531: WARNING: Unexpected indentation.
/home/myye/linux/Documentation/virt/kvm/api.rst:4533: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/myye/linux/Documentation/ABI/testing/sysfs-firmware-sgi_uv:2: WARNING: Unexpected indentation.
/home/myye/linux/Documentation/networking/device_drivers/ethernet/marvell/octeontx2.rst:169: WARNING: Unexpected indentation.
/home/myye/linux/Documentation/networking/device_drivers/ethernet/marvell/octeontx2.rst:171: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/myye/linux/Documentation/networking/device_drivers/ethernet/marvell/octeontx2.rst:183: WARNING: Unexpected indentation.
/home/myye/linux/Documentation/networking/device_drivers/ethernet/marvell/octeontx2.rst:189: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/myye/linux/Documentation/networking/device_drivers/ethernet/marvell/octeontx2.rst:199: WARNING: Unexpected indentation.
/home/myye/linux/Documentation/networking/device_drivers/ethernet/marvell/octeontx2.rst:202: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/myye/linux/Documentation/hwmon/sbtsi_temp.rst:4: WARNING: Title underline too short.

Kernel driver sbtsi_temp

==================
/home/myye/linux/Documentation/core-api/index.rst:53: WARNING: toctree contains reference to nonexisting document 'core-api/atomic_ops'

抛出异常：
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
如果你想向开发者报告问题，可以查阅已经保存在 /tmp/sphinx-err-pdoymqhg.log 的完整 Traceback 信息 。
如果此处抛出了用户的错误，也请向我们报告，这样以后可以显示更友好、更详细的错误信息。
请向 Bug 追踪系统 <https://github.com/sphinx-doc/sphinx/issues> 投递 Bug 报告。谢谢！
make[1]: *** [Documentation/Makefile:91：htmldocs] 错误 2
make: *** [Makefile:1669：htmldocs] 错误 2

```

**Environment info**
- OS: Ubuntu 20.04 LTS
- Python version: 3.8
- Sphinx version: 2.4.4

**Additional context**
```
$ cat /tmp/sphinx-err-pdoymqhg.log
# Sphinx version: 2.4.4
# Python version: 3.8.5 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:
#   写入输出... [ 27%] driver-api/fpga/intro .. driver-api/media/v4l2-subdev
#   写入输出... [ 31%] driver-api/media/v4l2-tuner .. driver-api/thermal/intel_powerclamp
#   写入输出... [ 34%] driver-api/thermal/nouveau_thermal .. filesystems/cramfs
#   写入输出... [ 37%] filesystems/debugfs .. filesystems/virtiofs
#   写入输出... [ 41%] filesystems/xfs-delayed-logging-design .. hwmon/bel-pfe
#   写入输出... [ 44%] hwmon/bt1-pvt .. hwmon/nct6683
#   写入输出... [ 48%] hwmon/nct6775 .. i2c/dma-considerations
#   写入输出... [ 51%] i2c/fault-codes .. kbuild/modules
#   写入输出... [ 55%] kbuild/reproducible-builds .. networking/batman-adv
#   写入输出... [ 58%] networking/bonding .. networking/devlink/index
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.4) from /home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/alabaster/__init__.py
#   kerneldoc (1.0) from /home/myye/linux/Documentation/sphinx/kerneldoc.py
#   rstFlatTable (1.0) from /home/myye/linux/Documentation/sphinx/rstFlatTable.py
#   kernel_include (1.0) from /home/myye/linux/Documentation/sphinx/kernel_include.py
#   kfigure (1.0.0) from /home/myye/linux/Documentation/sphinx/kfigure.py
#   sphinx.ext.ifconfig (2.4.4) from /home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinx/ext/ifconfig.py
#   automarkup (unknown version) from /home/myye/linux/Documentation/sphinx/automarkup.py
#   maintainers_include (1.0) from /home/myye/linux/Documentation/sphinx/maintainers_include.py
#   kernel_abi (1.0) from /home/myye/linux/Documentation/sphinx/kernel_abi.py
#   kernel_feat (1.0) from /home/myye/linux/Documentation/sphinx/kernel_feat.py
#   cdomain (1.1) from /home/myye/linux/Documentation/sphinx/cdomain.py
#   sphinx.ext.imgmath (2.4.4) from /home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinx/ext/imgmath.py
Traceback (most recent call last):
  File "/home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 532, in write
    self._write_parallel(sorted(docnames),
  File "/home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 572, in _write_parallel
    tasks.add_task(write_process, arg)
  File "/home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinx/util/parallel.py", line 103, in add_task
    self._join_one()
  File "/home/myye/linux/sphinx_2.4.4/lib/python3.8/site-packages/sphinx/util/parallel.py", line 112, in _join_one
    exc, logs, result = pipe.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by francoisfreitag** [comment]
Hi,
I followed the steps to reproduce and got the same error. I don’t see a document named `atomic_ops` in the repo, which is why Sphinx reports that the document `Documentation/core-api/index.rst` references a nonexisting document. It looks like the expected behavior to me.

**Comment by YuanyeMa** [comment]
Thanks very much for your commented.

When i remove the line `atomic_ops` in `Documentation/core-api/index.rst` , the "WARNING" disappered. But the `EOFError` is still here.

**Comment by francoisfreitag** [comment]
:man_facepalming: Sorry, I misread the issue.

I do not get the `EOFError` following those steps with Arch Linux and Python 3.9.1. I’ll spin up an Ubuntu VM to see if I can reproduce.

**Comment by francoisfreitag** [comment]
Yes, I can reproduce the issue with Ubuntu 20.04 (Python 3.8.5 and Python 3.9.0+).

**Comment by tk0miya** [comment]
It seems something bad happened in the child process of the parallel build. Could you try it again in non-parallel build mode? Then you can see what really happened, I guess.

**Comment by tk0miya** [comment]
Note: I still can't reproduce the error on my local. This is a Dockerfile I tried to reproduce.
```
FROM ubuntu:20.04

RUN apt update; apt install -y build-essential curl git make unzip vim
RUN git clone https://github.com/torvalds/linux.git
WORKDIR /linux
ENV DEBIAN_FRONTEND noninteractive
RUN apt install -y python python3 python3-pip fontconfig graphviz imagemagick
RUN pip3 install -r ./Documentation/sphinx/requirements.txt
RUN make htmldocs
```

**Comment by francoisfreitag** [comment]
Here are my steps to reproduce (reconstructed from my history):
```console
$ vagrant init generic/ubuntu2004
$ vagrant up
$ vagrant ssh
# Now running as the vagrant user inside the VM
$ git clone https://github.com/torvalds/linux.git
$ cd linux/
$ sudo apt install fontconfig gcc make graphviz imagemagick python3-venv
$ python3 -m venv venv
$ source venv/bin/activate
$ venv/bin/pip install -r Documentation/sphinx/requirements.txt
$ make htmldocs
```

**Comment by tk0miya** [comment]
@francoisfreitag Thank you for your help.

Finally, I reproduced the error on the default settings of vagrant. And I confirmed it's not reproduced with 4GB RAM.
In the error case, I got the following dmesg log:
```
[  824.378389] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-7.scope,task=sphinx-build,pid=1760,uid=0
[  824.378397] Out of memory: Killed process 1760 (sphinx-build) total-vm:1537512kB, anon-rss:696728kB, file-rss:2612kB, shmem-rss:0kB, UID:0 pgtables:3052kB oom_score_adj:0
[  824.438666] oom_reaper: reaped process 1760 (sphinx-build), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```
It says the subprocess of Sphinx was killed by OOM. I don't know this is the same as @YuanyeMa's case. So I'd like to know what will happen under non-parallel build mode.

Note: My Vagrantfile to reproduce the error:
```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    git clone https://github.com/torvalds/linux.git
    cd linux/
    sudo apt install -y fontconfig gcc make graphviz imagemagick python3-venv
    python3 -m venv venv
    source venv/bin/activate
    venv/bin/pip install -r Documentation/sphinx/requirements.txt
    make htmldocs
  SHELL
end
```

**Comment by YuanyeMa** [comment]
Thanks for your commented. 
I checked my dmsg log. It looks the same as yours.  Is it because my computer has insufficient memory?
```
[36147.454067] [  41660]  1000 41660   297340   135716  2383872   152539             0 sphinx-build
[36147.454070] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service,task=sphinx-build,pid=41660,uid=1000
[36147.454279] Out of memory: Killed process 41660 (sphinx-build) total-vm:1189360kB, anon-rss:542784kB, file-rss:80kB, shmem-rss:0kB, UID:1000 pgtables:2328kB oom_score_adj:0
[36147.536569] oom_reaper: reaped process 41660 (sphinx-build), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by tk0miya** [comment]
Yes.

**Comment by YuanyeMa** [comment]
It seem`s worked, Thank you very much.
