### ISSUE TITLE
AttributeError: 'str' object has no attribute 'supported'

### ISSUE THREAD

**Issue by Sherryzhang2** [sphinx-doc/sphinx#8705]
Sphinx version: 3.4.3
 Python version: 3.7.5 (CPython)
 Docutils version: 0.16 release
 Jinja2 version: 2.11.2
Last messages:

 Loaded extensions:
Traceback (most recent call last):
  File "/home/sherry/.local/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/sherry/.local/lib/python3.7/site-packages/sphinx/application.py", line 245, in __init__
    self.setup_extension(extension)
  File "/home/sherry/.local/lib/python3.7/site-packages/sphinx/application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/sherry/.local/lib/python3.7/site-packages/sphinx/registry.py", line 430, in load_extension
    metadata = setup(app)
  File "/home/sherry/.local/lib/python3.7/site-packages/m2r.py", line 652, in setup
    app.add_source_parser('.md', M2RParser)
  File "/home/sherry/.local/lib/python3.7/site-packages/sphinx/application.py", line 1136, in add_source_parser
    self.registry.add_source_parser(parser, override=override)
  File "/home/sherry/.local/lib/python3.7/site-packages/sphinx/registry.py", line 267, in add_source_parser
    for filetype in parser.supported:
AttributeError: 'str' object has no attribute 'supported'

**Comment by tk0miya** [comment]
Same as #8395. This is a bug of m2r2.
