### ISSUE TITLE
sphinx suffers AssertionError and stops 

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#873]
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/docutils/nodes.py", line 692, in replace_self
    'Losing "&#37;s" attribute: &#37;s' &#37; (att, self[att])
AssertionError: Losing "ids" attribute: ['nat-ref']
The full traceback has been saved in /tmp/sphinx-err-uq1LjW.log, if you want to report the issue to the developers.

*_And this is the mentioned file:
*_

```
# Sphinx version: 1.1.2
# Python version: 2.7.2+
# Docutils version: 0.8.1 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.1.2-py2.7.egg/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.1.2-py2.7.egg/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.1.2-py2.7.egg/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.1.2-py2.7.egg/sphinx/builders/__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.1.2-py2.7.egg/sphinx/builders/__init__.py", line 291, in write
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.1.2-py2.7.egg/sphinx/environment.py", line 1228, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.1.2-py2.7.egg/sphinx/environment.py", line 1472, in resolve_references
    self.process_only_nodes(doctree, builder, fromdocname)
  File "/usr/local/lib/python2.7/dist-packages/Sphinx-1.1.2-py2.7.egg/sphinx/environment.py", line 1510, in process_only_nodes
    node.replace_self(node.children)
  File "/usr/local/lib/python2.7/dist-packages/docutils/nodes.py", line 692, in replace_self
    'Losing "&#37;s" attribute: &#37;s' &#37; (att, self[att])
AssertionError: Losing "ids" attribute: ['nat-ref']
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/873
- Originally reported by: Anonymous
- Originally created at: 2012-02-12T18:16:37.962

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2012-03-10 18:36:36+00:00_

Fixes #873: do not raise assertion errors on empty "only" directives.

→ <<cset 95f0155227e9d0186f38cf492f6a933613b2b4d3>>
