### ISSUE TITLE
test_quickstart_all_answers fails with Python 3 and LC_ALL=C

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#876]
When test_quickstart.test_quickstart_all_answers is run using Python 3 and LC_ALL is set to C, it fails with the following exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/nose/util.py", line 622, in newfunc
    return func(*arg, **kw)
  File "/tmp/sphinx-1.1.2/build/lib/tests/util.py", line 214, in new_func
    func(tempdir, *args, **kwds)
  File "/tmp/sphinx-1.1.2/build/lib/tests/test_quickstart.py", line 156, in test_quickstart_all_answers
    code = compile(f.read(), conffile, 'exec')
  File "/usr/lib/python3.2/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
Exception: UnicodeDecodeError: ascii
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/876
- Originally reported by: Jakub Wilk
- Originally created at: 2012-02-13T00:06:26.797

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2012-03-10 17:46:22+00:00_

Fixes #875 and #876: use the right file mode to successfully read config files under 2.x and 3.x.

→ <<cset 75ec8f27d52a93db4a77b9114f687d7b98fb5504>>
