### ISSUE TITLE
cmdline.py SyntaxError: EOL while scanning string literal

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#881]
```
Traceback (most recent call last):
  File "/home/jbauer/.virtualenvs/sutra/bin/sphinx-build", line 8, in <module>
    load_entry_point('Sphinx==1.2pre-cb2d9ffb441bdev-20120216', 'console_scripts', 'sphinx-build')()
  File "/home/jbauer/.virtualenvs/sutra/lib/python2.7/site-packages/Sphinx-1.2pre_cb2d9ffb441bdev_20120216-py2.7.egg/sphinx/__init__.py", line 47, in main
    from sphinx import cmdline
  File "/home/jbauer/.virtualenvs/sutra/lib/python2.7/site-packages/Sphinx-1.2pre_cb2d9ffb441bdev_20120216-py2.7.egg/sphinx/cmdline.py", line 70
    print >>sys.stderr, 'Error: Cannot find source directory `&#37;s'.' &#37; (
                                                                      ^
SyntaxError: EOL while scanning string literal
```

Environment: Python 2.7.2, Linux, current Sphinx repo

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/881
- Originally reported by: Jeff Bauer
- Originally created at: 2012-02-17T14:32:05.321

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2012-02-17 16:20:03+00:00_

Dang! Mea culpa, fixed in [[https://github.com/sphinx-doc/testing/commit/a3d17de2f9b25b96df3ecb7719d21d713f488493|2f24c25f3eaa]].
