### ISSUE TITLE
Exception when building Python 3.2 docs

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#888]
```
# Sphinx version: 1.0.7
# Python version: 2.6.2
# Docutils version: 0.6 release
# Jinja2 version: unknown
Traceback (most recent call last):
  File "/home/vinay/projects/python/3.2/Doc/tools/sphinx/cmdline.py", line 188, in main
    app.build(force_all, filenames)
  File "/home/vinay/projects/python/3.2/Doc/tools/sphinx/application.py", line 207, in build
    self.builder.build_update()
  File "/home/vinay/projects/python/3.2/Doc/tools/sphinx/builders/__init__.py", line 198, in build_update
    'out of date' &#37; len(to_build))
  File "/home/vinay/projects/python/3.2/Doc/tools/sphinx/builders/__init__.py", line 254, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/vinay/projects/python/3.2/Doc/tools/sphinx/builders/__init__.py", line 294, in write
    self.write_doc(docname, doctree)
  File "/home/vinay/projects/python/3.2/Doc/tools/sphinx/builders/html.py", line 413, in write_doc
    ctx = self.get_doc_context(docname, body, metatags)
  File "/home/vinay/projects/python/3.2/Doc/tools/sphinx/builders/html.py", line 382, in get_doc_context
    toc = self.render_partial(self.env.get_toc_for(docname))['fragment']
  File "/home/vinay/projects/python/3.2/Doc/tools/sphinx/environment.py", line 1063, in get_toc_for
    toc = self.tocs[docname].deepcopy()
KeyError: 'documenting/building'
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/888
- Originally reported by: Vinay Sajip
- Originally created at: 2012-02-27T11:35:21.156

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2012-03-10 17:22:03+00:00_

Duplicate of #870.
