### ISSUE TITLE
make html fails because of zipfile

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#898]
# Sphinx version: 1.1.3
# Python version: 2.7.2
# Docutils version: 0.8.1 release
# Jinja2 version: 2.6

Traceback (most recent call last):
  File "/home/sontek/.virtualenvs/testy/lib/python2.7/site-packages/sphinx/cmdline.py", line 188, in main
    warningiserror, tags)
  File "/home/sontek/.virtualenvs/testy/lib/python2.7/site-packages/sphinx/application.py", line 114, in **init**
    self.setup_extension(extension)
  File "/home/sontek/.virtualenvs/testy/lib/python2.7/site-packages/sphinx/application.py", line 247, in setup_extension
    mod = **import**(extension, None, None, ['setup'])
  File "/home/sontek/.virtualenvs/testy/lib/python2.7/site-packages/sphinx/ext/intersphinx.py", line 38, in <module>
    from sphinx.builders.html import INVENTORY_FILENAME
  File "/home/sontek/.virtualenvs/testy/lib/python2.7/site-packages/sphinx/builders/html.py", line 42, in <module>
    from sphinx.theming import Theme
  File "/home/sontek/.virtualenvs/testy/lib/python2.7/site-packages/sphinx/theming.py", line 14, in <module>
    import zipfile
  File "/usr/lib64/python2.7/zipfile.py", line 462, in <module>
    class ZipExtFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase'

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/898
- Originally reported by: [sontek](https://bitbucket.org/sontek)
- Originally created at: 2012-03-14T02:55:04.945

**Comment by shimizukawa** [comment]
_From [sontek](https://bitbucket.org/sontek) on 2012-03-14 02:03:22+00:00_

This was because we had a module in our namespace also called io.
