### ISSUE TITLE
[4.x] TypeVars rendered fullly qualified

### ISSUE THREAD

**Issue by bluetech** [sphinx-doc/sphinx#8994]
**Describe the bug**

Trying Sphinx 4.0 (from master branch, commit c817c206265f545529b5fabe43fdf162bbc9bea2) I noticed that `TypeVar`s are now rendered `fully.qualified.T` instead of just `T` like they used to in Sphinx 3.x.

**To Reproduce**

I'm using the following code in the example below (though with `_E` -> `E`, but that's not pertinent):

https://github.com/pytest-dev/pytest/blob/146eda93e7baf621475aef07be2c7b153f6acf03/src/_pytest/python_api.py#L577

**Expected behavior**

I think that for `TypeVar`s specifically, for the vast majority of cases, it is better to only use the short name, even though it *could* cause an ambiguity.

**Your project**

https://github.com/pytest-dev/pytest

**Screenshots**

Before:

![before](https://user-images.githubusercontent.com/1223550/111030653-28910a00-840c-11eb-8774-6836c8644bd8.png)

After:

![after](https://user-images.githubusercontent.com/1223550/111030656-2e86eb00-840c-11eb-8cb1-851709052575.png)

**Environment info**
- OS: Linux
- Python version: 3.9.2
- Sphinx version: 4.0.0 (master branch) commit c817c206265f545529b5fabe43fdf162bbc9bea2
- Sphinx extensions: 

```py
extensions = [
    "pallets_sphinx_themes",
    "pygments_pytest",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
    "sphinx_removed_in",
    "sphinxcontrib_trio",
]
```

**Comment by bluetech** [comment]
So I thought now to check the release notes to see if it's actually intentional, found this:

```
* #7199: py domain: Add :confval:`python_use_unqualified_type_names` to suppress
  the module name of the python reference if it can be resolved (experimental)
```

Sounds relevant, but when I try it I get this error so not sure (maybe I messed up the installation):

```
Exception occurred:
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/writers/html5.py", line 776, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: pending_xref_condition
```

Full exception:

```
# Sphinx version: 4.0.0+/610c6250f
# Python version: 3.9.2 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.3
# Last messages:
#   writing output... [ 78%] example/pythoncollection
#   writing output... [ 79%] example/reportingdemo
#   writing output... [ 79%] example/simple
#   writing output... [ 80%] example/special
#   writing output... [ 80%] flaky
#   writing output... [ 81%] funcarg_compare
#   writing output... [ 81%] getting-started
#   writing output... [ 82%] goodpractices
#   writing output... [ 82%] historical-notes
#   writing output... [ 83%] how-to/assert
# Loaded extensions:
#   sphinx.ext.mathjax (4.0.0+/610c6250f) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/alabaster/__init__.py
#   pallets_sphinx_themes (1.2.3) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/pallets_sphinx_themes/__init__.py
#   pygments_pytest (unknown version) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/pygments_pytest.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.0.0+/610c6250f) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.0.0+/610c6250f) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (4.0.0+/610c6250f) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.intersphinx (4.0.0+/610c6250f) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.todo (4.0.0+/610c6250f) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/ext/todo.py
#   sphinx.ext.viewcode (4.0.0+/610c6250f) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/ext/viewcode.py
#   sphinx_removed_in (0.2.1) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx_removed_in/__init__.py
#   sphinxcontrib_trio (1.1.2) from /home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinxcontrib_trio/__init__.py
Traceback (most recent call last):
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 357, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 531, in write
    self._write_serial(sorted(docnames))
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 541, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 616, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/writers/html.py", line 70, in translate
    self.document.walkabout(visitor)
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 3 more times]
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/docutils/nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/util/docutils.py", line 472, in dispatch_visit
    super().dispatch_visit(node)
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/docutils/nodes.py", line 1995, in dispatch_visit
    return method(node)
  File "/home/ran/src/pytest/.tox/docs/lib/python3.9/site-packages/sphinx/writers/html5.py", line 776, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: pending_xref_condition
```

**Comment by ktbarrett** [comment]
@bluetech The option seems to work for me, but unfortunately it only applies if the type name is documented.

It is arguably a good thing to document TypeVars. The default documentation for TypeVars shows covariance, bounds, etc. But it does mean that your project should define TypeVars in one place and reuse them, which is not the current convention.

**Comment by Gobot1234** [comment]
I don't want to document my TypeVars as I don't want people think they are public API and have people potentially use them.

**Comment by ktbarrett** [comment]
Right. I'm not sure what a good solution here because that information is a part of the public interface of definitions that use these TypeVars, and that information is not available otherwise, besides through naming convention (`T`, `S`, `T_co`, `Self`, `MyTypeT`, etc.). Personally, I think they should be documented, but marked as use-private interface-public.
