### ISSUE TITLE
"TypeError: expected a character buffer object" in PygmentsBridge.highlight_block

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#905]
In some circumstances pygments.highlight() returns a byte string instead of unicode string (which might be a bug in Pygments…).
This makes PygmentsBridge.highlight_block explode:

```
>>> import pygments, sphinx
>>> print sphinx.__version__
1.1.3
>>> print pygments.__version__
1.5
>>> from sphinx.highlighting import PygmentsBridge
>>> bridge =  PygmentsBridge('latex')
>>> bridge.highlight_block(u'', 'pycon')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/pymodules/python2.7/sphinx/highlighting.py", line 210, in highlight_block
    return hlsource.translate(tex_hl_escape_map_new)
TypeError: expected a character buffer object
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/905
- Originally reported by: Jakub Wilk
- Originally created at: 2012-03-31T12:08:11.693

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2012-08-19 10:13:47+00:00_

Closes #905: work around Pygments bug returning str instead of Unicode from Latex formatter for empty input.

→ <<cset 14d738c45510bb5847ac7c3e5028f3b549675d75>>
