### ISSUE TITLE
autoclass directive returns object of wrong type

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#906]
I've got the following exception:

```
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.1.3
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
building [html]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
reading sources... [ 33&#37;] api/awwparse
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.1.3
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
building [html]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
reading sources... [ 33&#37;] api/awwparse

Exception occurred:
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2098, in run_directive
    &#37; (type_name, i, result[i]))
AssertionError: Directive "autoclass" returned non-Node object (index 0): <system_message: <paragraph...><literal_block...>>
The full traceback has been saved in /var/folders/b3/jf_438712qx69vgx79nm1mgc0000gn/T/sphinx-err-jP25Ac.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1
```

The complete traceback is:

```
# Sphinx version: 1.1.3
# Python version: 2.7.1
# Docutils version: 0.8.1 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 216, in build
    purple, length):
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 120, in status_iterator
    for item in iterable:
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/sphinx/environment.py", line 613, in update_generator
    self.read_doc(docname, app=app)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/sphinx/environment.py", line 761, in read_doc
    pub.publish()
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/core.py", line 211, in publish
    self.settings)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/readers/__init__.py", line 69, in read
    self.parse()
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/readers/__init__.py", line 75, in parse
    self.parser.parse(self.input, document)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 157, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/statemachine.py", line 237, in run
    context, state, transitions)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/statemachine.py", line 458, in check_line
    return method(match, context, next_state)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2709, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 329, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 398, in new_subsection
    node=section_node, match_titles=1)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 284, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/statemachine.py", line 237, in run
    context, state, transitions)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/statemachine.py", line 458, in check_line
    return method(match, context, next_state)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2285, in explicit_markup
    self.explicit_list(blank_finish)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2316, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 321, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/statemachine.py", line 237, in run
    context, state, transitions)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/statemachine.py", line 458, in check_line
    return method(match, context, next_state)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2589, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2295, in explicit_construct
    return method(self, expmatch)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2036, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/DasIch/Development/dotfiles/virtualenv/envs/awwparse/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2098, in run_directive
    &#37; (type_name, i, result[i]))
AssertionError: Directive "autoclass" returned non-Node object (index 0): <system_message: <paragraph...><literal_block...>>
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/906
- Originally reported by: Daniel Neuhäuser
- Originally created at: 2012-04-04T20:37:44.363

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-06-21 08:47:40+00:00_

Sorry for very late response.

I can't reproduce the issue with your https://github.com/DasIch/awwparse project documentation by using Sphinx-1.1.3 and Sphinx-1.2.2.

Is this error still there? if exists, please inform me.
