### ISSUE TITLE
using intersphinx with parallel building repeatedly will get stuck

### ISSUE THREAD

**Issue by 0xMashiro** [sphinx-doc/sphinx#9072]
**Describe the bug**
 I'm using `sphinx.ext.intersphinx` in my project:

```python
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
}
```
Everything looks normal when the document is built for the first time.

But if you try to clear the built contents and rebuild again, you will not be able to execute the entire process.

```shell
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...

================= After long awaiting
^C^C
Interrupted!
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Makefile:47: recipe for target 'html' failed
make: *** [html] Interrupt
```

 Stop using `intersphinx` or downgrade to sphinx 3.5.1 seems can bypass this problem 

**To Reproduce**
```bash
$ git clone https://github.com/MegEngine/Documentation.git
$ git clone -b dev git@github.com:MegEngine/pydata-sphinx-theme.git
$ pip install --editable pydata-sphinx-theme
$ pip install megengine -f https://megengine.org.cn/whl/mge.html  # The project we build doc for
$ sudo apt install -y pandoc graphviz
$ cd Documentation
$ pip install -r requirements.txt
$ make html # works at the first time
$ make clean # rebuild for some reason (update contents bla bla)
$ make html # get stuck
```

Notice:
The size of `megengine` package is a little big, so I suggest you reproduce it in other ways.

**Expected behavior**
Build files normally.

**Your project**
https://github.com/MegEngine/Documentation

**Environment info**
- OS: Linux - Ubuntu 18.04
- Python version: 3.7.5
- Sphinx version: >=3.5.2
- Sphinx extensions:  sphinx.ext.intersphinx

**Comment by Kakcalu13** [comment]
downgraded to 3.5.1 worked for me. 

- OS: Linux - Ubuntu 20.04
- Python version: 3.8.5
- Sphinx version: >=3.5.1

Before I downgrade my sphinx, this bug is what I had

**Comment by jdillard** [comment]
Closing this due to inactivity, if it is still an issue on the latest version of Sphinx feel free to re-open.
