### ISSUE TITLE
sphinx fails when building HTML documentation from rst format of python modules

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#913]
this is the error log
# Sphinx version: 0.6.6
# Docutils version: 0.6 release

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/sphinx/cmdline.py", line 170, in main
    app.build(all_files, filenames)
  File "/usr/lib/pymodules/python2.6/sphinx/application.py", line 136, in build
    self.builder.build_update()
  File "/usr/lib/pymodules/python2.6/sphinx/builders/**init**.py", line 265, in build_update
    'out of date' &#37; len(to_build))
  File "/usr/lib/pymodules/python2.6/sphinx/builders/**init**.py", line 320, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/pymodules/python2.6/sphinx/builders/**init**.py", line 358, in write
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/lib/pymodules/python2.6/sphinx/environment.py", line 1008, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/usr/lib/pymodules/python2.6/sphinx/environment.py", line 1353, in resolve_references
    builder.app.emit('doctree-resolved', doctree, fromdocname)
  File "/usr/lib/pymodules/python2.6/sphinx/application.py", line 228, in emit
    result.append(callback(self, *args))
  File "/home/lovesh/installs/python modules/mongodb-mongo-python-driver-369d615/doc/mongo_extensions.py", line 77, in process_mongodoc_nodes
    anchor = name["ids"][0]
IndexError: list index out of range

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/913
- Originally reported by: Anonymous
- Originally created at: 2012-04-26T20:37:10.108

**Comment by shimizukawa** [comment]
_From Marc Schlaich on 2012-05-08 12:59:45+00:00_

This is an error of the extension from pymongo, so it has nothing to do with sphinx itself.

**Comment by shimizukawa** [comment]
_From Jon Waltman on 2012-12-05 20:19:15+00:00_

Error in pymongo extension (`mongo_extensions.py`) using old version of Sphinx v0.6.

Feel free to reopen if issue persists but the problem has probably changed since this version was released.
