### ISSUE TITLE
Clearer migration guide for MathJax configuration from Sphinx 3.x to Sphinx 4.x

### ISSUE THREAD

**Issue by astrojuanlu** [sphinx-doc/sphinx#9148]
**Is your feature request related to a problem? Please describe.**
I am testing Sphinx 4.0.0b2 with a project that has no `mathjax_config`, and noticed that, since the default MathJax version changed to 3 (see discussion in https://github.com/sphinx-doc/sphinx/issues/8195 and solution in https://github.com/sphinx-doc/sphinx/pull/9094), I see an error like this:

```
Traceback (most recent call last):
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 292, in build_update
    self.build(to_build,
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 356, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 530, in write
    self._write_serial(sorted(docnames))
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 540, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 213, in pending_warnings
    memhandler.flushTo(logger)
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 178, in flushTo
    logger.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 946, in handle
    rv = self.filter(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 807, in filter
    result = f.filter(record)
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 423, in filter
    raise exc
sphinx.errors.SphinxWarning: mathjax_config/mathjax2_config does not work for the current MathJax version, use mathjax3_config instead

Warning, treated as error:
mathjax_config/mathjax2_config does not work for the current MathJax version, use mathjax3_config instead
```

From what I understand from the comments above, this breaking change is intentional. The workaround involves adding

```
mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
```

to `conf.py`, as already mentioned in https://www.sphinx-doc.org/en/master/usage/extensions/math.html?highlight=mathjax_path#module-sphinx.ext.mathjax.

However, the release notes https://www.sphinx-doc.org/en/master/changes.html#id10 only mention the renaming of `mathjax_config` to `mathjax2_config`, and do not say that the default MathJax version changed. I am worried that users with unpinned Sphinx versions will see their builds break and discovering a solution is not so easy.

**Describe the solution you'd like**
Either:
- Adding a brief, descriptive text to the release notes explaining how to deal with this issue
- Adding a more complete "migration guide" for Sphinx 3.x to Sphinx 4.x that mentions other breaking changes, including this one.

**Describe alternatives you've considered**
The alternative is to do nothing. We more or less anticipate what will happen: builds will break, and after some Googling, people will arrive to the solution, or they will pin Sphinx to `<4`. It's hardly a Sphinx problem, since users should be responsible for pinning their dependencies. But I wonder if we could make this more discoverable.

**Comment by mgeier** [comment]
The warning is caused by `nbsphinx`, because it defines a default value for `mathjax_config`.

This will be fixed in https://github.com/spatialaudio/nbsphinx/pull/558.

I was going to publish a new `nbsphinx` release right after the Sphinx 4 release, but probably it would be better to do it right now, to avoid problems in beta testing ...

**Comment by mgeier** [comment]
I've just released a new version (0.8.4) of `nbsphinx`, can you please try if it works now?

**Comment by astrojuanlu** [comment]
Oh, thanks a lot @mgeier! Sorry for the noise, I should have worked more on providing a short, self-contained example. I'm testing it as we speak.

**Comment by astrojuanlu** [comment]
It worked beautifully 😍  We are avid users of nbsphinx by the way. Thanks again @mgeier! Closing

**Comment by mgeier** [comment]
That's great to hear @astrojuanlu!

That's probably an opportunity for a bit of marketing: people who use `nbsphinx` might also like my Sphinx theme `insipid`: https://insipid-sphinx-theme.readthedocs.io/!

**Comment by tk0miya** [comment]
FYI

>However, the release notes https://www.sphinx-doc.org/en/master/changes.html#id10 only mention the renaming of mathjax_config to mathjax2_config, and do not say that the default MathJax version changed. I am worried that users with unpinned Sphinx versions will see their builds break and discovering a solution is not so easy.

It was mentioned at "Incompatible Changes" section for 4.0.0b1.
https://github.com/sphinx-doc/sphinx/blob/d656acaba3258fa6e9beb75e8409412315efb107/CHANGES#L105-L107

**Comment by astrojuanlu** [comment]
Oops, sorry I didn't see it - thanks @tk0miya!
