### ISSUE TITLE
3.5.4: python botocore module man page generation fails

### ISSUE THREAD

**Issue by kloczek** [sphinx-doc/sphinx#9186]
botocore has gigantic documentation.
```console
[tkloczko@barrel botocore-1.20.69]$ sphinx-build -b man -d botocore docs/source .

[..]

looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/tkloczko/rpmbuild/BUILD/botocore-1.20.69/docs/source/client_upgrades.rst: WARNING: document isn't included in any toctree
done
writing... failed

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 66, in write
    if docname not in self.env.all_docs:
TypeError: unhashable type: 'list'
The full traceback has been saved in /tmp/sphinx-err-3_rkr368.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
[tkloczko@barrel botocore-1.20.69] $ cat /tmp/sphinx-err-3_rkr368.log
# Sphinx version: 3.5.4
# Python version: 3.8.9 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.0rc2
# Last messages:
#   reading sources... [100%] tutorial/index
#
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   writing...
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (3.5.4) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.1) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (3.5.4) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.5.4) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   guzzle_sphinx_theme (unknown version) from /usr/lib/python3.8/site-packages/guzzle_sphinx_theme/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 360, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 713, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 66, in write
    if docname not in self.env.all_docs:
TypeError: unhashable type: 'list'
```

**Comment by tk0miya** [comment]
It seems the error said the first element of the item for `man_pages` settings is a list. It must be a string. Could you check your configuration?

**Comment by kloczek** [comment]
Indeed it was typo.
Sorry my fault. Closing.
