### ISSUE TITLE
code-block in .rst file lex error on UTF-8 Greek characters γ π etc.

### ISSUE THREAD

**Issue by jwoehr** [sphinx-doc/sphinx#9209]
**Describe the bug**
Making html from .rst file wherein `code-block: c` elements have UTF-8 Greek characters.

```
/openqasm/source/language/types.rst:65: WARNING: Could not lex literal_block as "c". Highlighting skipped.
/openqasm/source/language/types.rst:162: WARNING: Could not lex literal_block as "c". Highlighting skipped.
/openqasm/source/language/types.rst:180: WARNING: Could not lex literal_block as "c". Highlighting skipped.
/openqasm/source/language/types.rst:227: WARNING: Could not lex literal_block as "c". Highlighting skipped.
```
For instance, the WARNING for line 65 shown above is triggered by the block:
```
.. code-block:: c

   // Declare a qubit
   qubit gamma;
   // Declare a qubit with a Unicode name
   qubit γ;
   // Declare a qubit array with 20 qubits
   qubit qubit_array[20];
   // CNOT gate between physical qubits 0 and 1
   CX $0, $1;
```

**To Reproduce**
```
$ git clone https://github.com/qiskit/openqasm
$ cd openqasm
$ make html
```

**Expected behavior**
Parsing and conversion without error

**Your project**
 https://github.com/qiskit/openqasm

**Environment info**
- OS: Linux Ubuntu 20.04.2 LTS (Focal Fossa)
- Python version: 3.8.5
- Sphinx version: Sphinx                        3.5.1
- Sphinx extensions:  sphinxcontrib-applehelp       1.0.2
sphinxcontrib-bibtex          1.0.0
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4

**Comment by tk0miya** [comment]
It seems the pygments; the highlighting library that Sphinx uses raises an error when highlighting your code.
```
$ cat test.c
// Declare a qubit
qubit gamma;
// Declare a qubit with a Unicode name
qubit γ;
// Declare a qubit array with 20 qubits
qubit qubit_array[20];
// CNOT gate between physical qubits 0 and 1
CX $0, $1;
```
```
$ pygmentize -l c -F raiseonerror -v < test.c

*****************************************************************
An unhandled exception occurred while highlighting.
Please report the whole traceback to the issue tracker at
<https://github.com/pygments/pygments/issues>.
*****************************************************************

// Declare a qubit
qubit gamma;
// Declare a qubit with a Unicode name
qubit Traceback (most recent call last):
  File "/Users/tkomiya/work/tmp/bin/pygmentize", line 33, in <module>
    sys.exit(load_entry_point('Pygments', 'console_scripts', 'pygmentize')())
  File "/Users/tkomiya/work/tmp/lib/python3.9/site-packages/Pygments-2.7.4-py3.9.egg/pygments/cmdline.py", line 557, in main
    return main_inner(popts, args, usage)
  File "/Users/tkomiya/work/tmp/lib/python3.9/site-packages/Pygments-2.7.4-py3.9.egg/pygments/cmdline.py", line 519, in main_inner
    highlight(code, lexer, fmter, outfile)
  File "/Users/tkomiya/work/tmp/lib/python3.9/site-packages/Pygments-2.7.4-py3.9.egg/pygments/__init__.py", line 84, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/Users/tkomiya/work/tmp/lib/python3.9/site-packages/Pygments-2.7.4-py3.9.egg/pygments/__init__.py", line 66, in format
    formatter.format(tokens, outfile)
  File "/Users/tkomiya/work/tmp/lib/python3.9/site-packages/Pygments-2.7.4-py3.9.egg/pygments/formatters/terminal256.py", line 242, in format
    return Formatter.format(self, tokensource, outfile)
  File "/Users/tkomiya/work/tmp/lib/python3.9/site-packages/Pygments-2.7.4-py3.9.egg/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/Users/tkomiya/work/tmp/lib/python3.9/site-packages/Pygments-2.7.4-py3.9.egg/pygments/formatters/terminal256.py", line 245, in format_unencoded
    for ttype, value in tokensource:
  File "/Users/tkomiya/work/tmp/lib/python3.9/site-packages/Pygments-2.7.4-py3.9.egg/pygments/filter.py", line 20, in _apply
    yield from filter_.filter(lexer, stream)
  File "/Users/tkomiya/work/tmp/lib/python3.9/site-packages/Pygments-2.7.4-py3.9.egg/pygments/filters/__init__.py", line 783, in filter
    raise self.exception(value)
pygments.filters.ErrorToken: γ
```

I don't know this is valid C code or not. If you think this is valid, please report this into their project.

As a workaround, you can avoid the error by passing `:force:` option to `code-block` directive:
```
.. code-block:: c
   :force:

   // Declare a qubit
   qubit gamma;
   // Declare a qubit with a Unicode name
   qubit γ ;
   // Declare a qubit array with 20 qubits
   qubit qubit_array[20];
   // CNOT gate between physical qubits 0 and 1
   CX $0, $1;
```

Thanks,

**Comment by jwoehr** [comment]
@tk0miya it's not really valid C code. We were using c because the syntax for this other language was close. It works fine as long as we don't introduce greek characters. Thank you. We will use the `:force:` option.
