### ISSUE TITLE
Sphinx Quickstart (PyCharm) crashes after giving authors name with Umlaut

### ISSUE THREAD

**Issue by natter1** [sphinx-doc/sphinx#9247]
After installing sphinx in a new venv (python 3.9) I used Sphinx Quickstart from PyCharm's Tool-menu. I think this simply called: `D:\py_projects\sandbox\Enum_doc\venv\Scripts\sphinx-quickstart.exe`.  After giving an authors name, the quickstart crashes:

```
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\py_projects\sandbox\Enum_doc\venv\Scripts\sphinx-quickstart.exe\__main__.py", line 7, in <module>
  File "d:\py_projects\sandbox\enum_doc\venv\lib\site-packages\sphinx\cmd\quickstart.py", line 586, in main
    ask_user(d)
  File "d:\py_projects\sandbox\enum_doc\venv\lib\site-packages\sphinx\cmd\quickstart.py", line 249, in ask_user
    d['author'] = do_prompt(__('Author name(s)'))
  File "d:\py_projects\sandbox\enum_doc\venv\lib\site-packages\sphinx\cmd\quickstart.py", line 148, in do_prompt
    x = term_input(prompt).strip()
  File "d:\py_projects\sandbox\enum_doc\venv\lib\site-packages\sphinx\cmd\quickstart.py", line 82, in term_input
    return input('')
  File "C:\Program Files\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 11: invalid start byte
```
I guess this is caused by Umlaut "ö" in the authors name. When using "oe" instead of "ö", quickstart finishes as expected.

**Comment by tk0miya** [comment]
I'm not familiar with Windows, but you need to set the encoding of your terminal to UTF-8, I think. It seems the standard function `input()` crashes on converting the input string to unicode.

**Comment by natter1** [comment]
Hmm, Windows does indeed not use UTF-8 as default encoding. But on the other hand, input() seems to have no issue with Umlaute normaly. E.g the following python script would work fine with 'ö' when run in a terminal:
```
a = input()
print(a)
```
