### ISSUE TITLE
`AttributeError` when trying to use `autoattribute` directive for an instance variable

### ISSUE THREAD

**Issue by g6ai** [sphinx-doc/sphinx#9283]
**Describe the bug**
I got `AttributeError` when trying to use `autoattribute` directive for an instance variable. This is a follow-up to https://github.com/sphinx-doc/sphinx/issues/904#issuecomment-850864709.

**To Reproduce**
```rst
# index.rst
.. autoclass:: example.Foo

   .. autoattribute:: ivar
```
```python
# example.py
class Foo:
    def __init__(self):
        self.ivar = None
```
```console
$ make html
WARNING: autodoc: failed to import attribute 'Foo.ivar' from module 'example'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/gbai/.pyenv/versions/miniconda3-latest/envs/sphinx/lib/python3.9/site-packages/sphinx/util/inspect.py", line 412, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: type object 'Foo' has no attribute 'ivar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gbai/.pyenv/versions/miniconda3-latest/envs/sphinx/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/Users/gbai/.pyenv/versions/miniconda3-latest/envs/sphinx/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 318, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/Users/gbai/.pyenv/versions/miniconda3-latest/envs/sphinx/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2606, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/Users/gbai/.pyenv/versions/miniconda3-latest/envs/sphinx/lib/python3.9/site-packages/sphinx/util/inspect.py", line 428, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: ivar
```

**Environment info**
- OS: macOS 10.14.6
- Python version: 3.9.5
- Sphinx version: 4.0.2
- Sphinx extensions:  sphinx.ext.autodoc
- Extra tools:

**Comment by tk0miya** [comment]
Thank you for reporting. This is caused if the instance attribute does not have comment. #9285 will fix this.

As a workaround, you can avoid the error via adding comment to the attribute.

Thanks,
