### ISSUE TITLE
No object (name: request) has been registered for this thread

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#935]
Using Sphinx-1.2hg 

```
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.2pre
loading pickled environment... done
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
Traceback (most recent call last):idgets                                        
  File "[snip]/sandbox/lib/python2.7/site-packages/Sphinx-1.2pre_6e960412308fdev_20120525-py2.7.egg/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "[snip]/sandbox/fireplot/fireplot/widgets/plotboxform.py", line 12, in <module>
    class PlotboxForm(TableForm):
  File "[snip]/sandbox/fireplot/fireplot/widgets/plotboxform.py", line 15, in PlotboxForm
    css = [CSSLink(link=url('/css/tooltips.css'))]
  File "[snip]/sandbox/lib/python2.7/site-packages/TurboGears2-2.1.5-py2.7.egg/tg/controllers/util.py", line 97, in url
    base_url = pylons.request.environ['SCRIPT_NAME'] + base_url
  File "[snip]/sandbox/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/registry.py", line 137, in __getattr__
    return getattr(self._current_obj(), attr)
  File "[snip]/sandbox/lib/python2.7/site-packages/Paste-1.7.5.1-py2.7.egg/paste/registry.py", line 197, in _current_obj
    'thread' &#37; self.____name__)
TypeError: No object (name: request) has been registered for this thread

[snip]/sandbox/fireplot/doc/source/widgets.rst:5: WARNING: autodoc can't import/find module 'fireplot.widgets.plotboxform', it reported error: "No object (name: request) has been registered for this thread", please check your spelling and sys.path

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100&#37;] source/widgets                                         
writing additional files... genindex py-modindex search
copying static files... done
dumping search index... done
dumping object inventory... done
build succeeded, 1 warning.
```

Looks similar to the issue addressed here: https://github.com/sphinx-doc/testing/issues/214

Offending code from Paste-1.7.5.1-py2.7.egg/paste/registry.py

```
        try:
            objects = self.____local__.objects
        except AttributeError:
            objects = None
        if objects:
            return objects[-1]
        else:
            obj = self.__dict__.get('____default_object__', NoDefault)
            if obj is not NoDefault:
                return obj
            else:
                raise TypeError(
                    'No object (name: &#37;s) has been registered for this '
                    'thread' &#37; self.____name__)
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/935
- Originally reported by: Anonymous
- Originally created at: 2012-05-25T22:13:33.374

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-11 08:25:36+00:00_

This is not an error anymore, but intended: Sphinx just reports the exception to you so that you can remedy it.  (Perhaps by changing Paste or by putting some code in conf.py that will stop Paste from raising this error.)
