### ISSUE TITLE
building html pages with sphinx exhale and breathe

### ISSUE THREAD

**Issue by kausky** [sphinx-doc/sphinx#9371]
```bash
Exception occurred:
  File "/usr/local/lib/python3.6/dist-packages/sphinx/util/cfamily.py", line 274, in fail
    raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name. [error at 1]
  ("help", "Default help info.", "h")
  -^
```
So this is the main error i see I have integrated exhale, breathe and sphinx with doxygen and i face this in the reading sources step

**To Reproduce**
```
git clone -b doc https://github.com/Aakash-kaushik/mlpack.git
pip3/pip install breathe sphinx karma-sphinx-theme
cd mlpack/doc
make html 
```
**Expected behavior**
A successful build for the html pages for documentation 

**Screenshots**
![image](https://user-images.githubusercontent.com/39410692/122926598-aa86bc80-d385-11eb-8628-6b3a8f9dc713.png)
![image](https://user-images.githubusercontent.com/39410692/122926642-b70b1500-d385-11eb-9a21-0eaf18cc4ce7.png)

**Environment info**
- OS: [Ubuntu 18.04]
- Python version: [3.6.9]
- Sphinx version: [4.0.2]
- Sphinx extensions:  [breathe, exhale, karma-sphinx-theme]
- Extra tools: [graphviz]

**Additional context**
the log generated
```
# Sphinx version: 4.0.2
# Python version: 3.6.9 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.1
# Last messages:
#   reading sources... [ 50%] api/function_namespacemlpack_1_1bindings_1_1cli_1a5f081ca01123f56a6a958ec611f025bd
#   
#   reading sources... [ 50%] api/function_namespacemlpack_1_1bindings_1_1cli_1a61ebeefd1aea01f101a7d52eb2d99be6
#   
#   reading sources... [ 50%] api/function_namespacemlpack_1_1bindings_1_1cli_1a61f79718ab4568bf8a4b263d2f822675
#   
#   reading sources... [ 50%] api/function_namespacemlpack_1_1bindings_1_1cli_1a65cbd524fa46ac7794166033fe768058
#   
#   reading sources... [ 50%] api/function_namespacemlpack_1_1bindings_1_1cli_1a675da324bc5a7dd5b6cd305e6bbec671
#   
# Loaded extensions:
#   sphinx.ext.mathjax (4.0.2) from /usr/local/lib/python3.6/dist-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/local/lib/python3.6/dist-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/local/lib/python3.6/dist-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/local/lib/python3.6/dist-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/local/lib/python3.6/dist-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/local/lib/python3.6/dist-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/local/lib/python3.6/dist-packages/alabaster/__init__.py
#   breathe (4.30.0) from /usr/local/lib/python3.6/dist-packages/breathe/__init__.py
#   exhale (0.2.3) from /usr/local/lib/python3.6/dist-packages/exhale/__init__.py
#   karma_sphinx_theme (0.0.8) from /usr/local/lib/python3.6/dist-packages/karma_sphinx_theme/__init__.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.6/dist-packages/sphinx/builders/__init__.py", line 294, in build_update
    len(to_build))
  File "/usr/local/lib/python3.6/dist-packages/sphinx/builders/__init__.py", line 306, in build
    updated_docnames = set(self.read())
  File "/usr/local/lib/python3.6/dist-packages/sphinx/builders/__init__.py", line 413, in read
    self._read_serial(docnames)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/builders/__init__.py", line 434, in _read_serial
    self.read_doc(docname)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/builders/__init__.py", line 474, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/local/lib/python3.6/dist-packages/sphinx/io.py", line 188, in read_doc
    pub.publish()
  File "/usr/local/lib/python3.6/dist-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/io.py", line 108, in read
    self.parse()
  File "/usr/local/lib/python3.6/dist-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/parsers.py", line 100, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/local/lib/python3.6/dist-packages/docutils/statemachine.py", line 240, in run
    context, state, transitions)
  File "/usr/local/lib/python3.6/dist-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python3.6/dist-packages/docutils/statemachine.py", line 240, in run
    context, state, transitions)
  File "/usr/local/lib/python3.6/dist-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python3.6/dist-packages/docutils/statemachine.py", line 240, in run
    context, state, transitions)
  File "/usr/local/lib/python3.6/dist-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 2097, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/local/lib/python3.6/dist-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/usr/local/lib/python3.6/dist-packages/breathe/directives.py", line 81, in run
    args = self._parse_args(args)
  File "/usr/local/lib/python3.6/dist-packages/breathe/directives.py", line 145, in _parse_args
    paramQual = parser._parse_parameters_and_qualifiers(paramMode='function')
  File "/usr/local/lib/python3.6/dist-packages/sphinx/domains/cpp.py", line 5807, in _parse_parameters_and_qualifiers
    arg = self._parse_type_with_init(outer=None, named='single')
  File "/usr/local/lib/python3.6/dist-packages/sphinx/domains/cpp.py", line 6300, in _parse_type_with_init
    type = self._parse_type(outer=outer, named=named)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/domains/cpp.py", line 6291, in _parse_type
    declSpecs = self._parse_decl_specs(outer=outer)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/domains/cpp.py", line 5985, in _parse_decl_specs
    trailing = self._parse_trailing_type_spec()
  File "/usr/local/lib/python3.6/dist-packages/sphinx/domains/cpp.py", line 5781, in _parse_trailing_type_spec
    nestedName = self._parse_nested_name()
  File "/usr/local/lib/python3.6/dist-packages/sphinx/domains/cpp.py", line 5703, in _parse_nested_name
    self.fail("Expected identifier in nested name.")
  File "/usr/local/lib/python3.6/dist-packages/sphinx/util/cfamily.py", line 274, in fail
    raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name. [error at 1]
  ("help", "Default help info.", "h")
  -^
```

Do let me know if i have missed something.

**Comment by astrojuanlu** [comment]
I tried reproducing this issue, but then I arrived to https://github.com/svenevs/exhale/issues/109.

Besides, could you provide a simpler way to reproduce the issue without having to build the whole mlpack?

**Comment by kausky** [comment]
> I tried reproducing this issue, but then I arrived to [svenevs/exhale#109](https://github.com/svenevs/exhale/issues/109).
> 
> Besides, could you provide a simpler way to reproduce the issue without having to build the whole mlpack?

Hey thanks for the reply,
You don't need to build mlpack to produce the documentation and also the error i got was because i was using a newer version of doxygen, if you use `doxyen=1.18.3` you should be able to reproduce it without needing to build mlpack. 

The make html step only runs doxygen and then sphinx i believe.

**Comment by jakobandersen** [comment]
I'm not sure exactly what is going wrong, but I think it is somewhere in Breathe or Exhale.
From the error Sphinx gets the declaration ``("help", "Default help info.", "h")`` which is clearly it not valid for any kind of declaration.
If you run with ``breathe_debug_trace_directives = True`` in your ``conf.py`` then Breathe will print out what kind of declarations is sends to Sphinx which may reveal a bit more info.
A quick grep for the "declaration" leads me to https://github.com/Aakash-kaushik/mlpack/blob/1313b4eebd362ac9ebe3517ff80ee2454beb83f6/src/mlpack/bindings/cli/parse_command_line.hpp#L26 and https://github.com/Aakash-kaushik/mlpack/blob/1313b4eebd362ac9ebe3517ff80ee2454beb83f6/src/mlpack/core/util/mlpack_main.hpp#L481 as possible origins.
That macro seems to eventually expand to https://github.com/Aakash-kaushik/mlpack/blob/1313b4eebd362ac9ebe3517ff80ee2454beb83f6/src/mlpack/core/util/param.hpp#L1261
I don't know the details of what Exhale does, so perhaps it can provide more clues.
Neither Breathe nor Sphinx performs any kind of macro expansion so in the end Breathe relies on Doxygen being nice in the XML it generates. I can't find a specific Breathe issue at the moment, but I remember similar issues having been reported when declarations are "hidden" behind macros.
If you can produce a slimmed down version of the problem and open an issue over at Breathe I can dive into the XML and see if there is enough info for Breathe to do something better.

**Comment by kausky** [comment]
> I'm not sure exactly what is going wrong, but I think it is somewhere in Breathe or Exhale.
> From the error Sphinx gets the declaration `("help", "Default help info.", "h")` which is clearly it not valid for any kind of declaration.
> If you run with `breathe_debug_trace_directives = True` in your `conf.py` then Breathe will print out what kind of declarations is sends to Sphinx which may reveal a bit more info.
> A quick grep for the "declaration" leads me to https://github.com/Aakash-kaushik/mlpack/blob/1313b4eebd362ac9ebe3517ff80ee2454beb83f6/src/mlpack/bindings/cli/parse_command_line.hpp#L26 and https://github.com/Aakash-kaushik/mlpack/blob/1313b4eebd362ac9ebe3517ff80ee2454beb83f6/src/mlpack/core/util/mlpack_main.hpp#L481 as possible origins.
> That macro seems to eventually expand to https://github.com/Aakash-kaushik/mlpack/blob/1313b4eebd362ac9ebe3517ff80ee2454beb83f6/src/mlpack/core/util/param.hpp#L1261
> I don't know the details of what Exhale does, so perhaps it can provide more clues.
> Neither Breathe nor Sphinx performs any kind of macro expansion so in the end Breathe relies on Doxygen being nice in the XML it generates. I can't find a specific Breathe issue at the moment, but I remember similar issues having been reported when declarations are "hidden" behind macros.
> If you can produce a slimmed down version of the problem and open an issue over at Breathe I can dive into the XML and see if there is enough info for Breathe to do something better.

So if you look here: https://exhale.readthedocs.io/en/latest/mastering_doxygen.html#additional-variables-with-important-impacts there is a variable `MACRO_EXPANSION` that is set to `YES` exhale i think by default enables macro expansion would turning that off be of any help to debug the issue ? 

Correction: doxygen has that variable not exhale.

**Comment by jakobandersen** [comment]
> So if you look here: https://exhale.readthedocs.io/en/latest/mastering_doxygen.html#additional-variables-with-important-impacts there is a variable `MACRO_EXPANSION` that is set to `YES` exhale i think by default enables macro expansion would turning that off be of any help to debug the issue ?

Unfortunately I don't know enough about Exhale and Doxygen to be sure about that. I usually go back to the generated Doxygen XML for the declaration I'm debugging, but the whole mlpack is rather large.

**Comment by kausky** [comment]
> > So if you look here: https://exhale.readthedocs.io/en/latest/mastering_doxygen.html#additional-variables-with-important-impacts there is a variable `MACRO_EXPANSION` that is set to `YES` exhale i think by default enables macro expansion would turning that off be of any help to debug the issue ?
> 
> Unfortunately I don't know enough about Exhale and Doxygen to be sure about that. I usually go back to the generated Doxygen XML for the declaration I'm debugging, but the whole mlpack is rather large.

So what can i really do to debug this, Some help or guidance would be appreciated.

**Comment by jakobandersen** [comment]
> So what can i really do to debug this, Some help or guidance would be appreciated.

Sure. As mentioned, running with ``breathe_debug_trace_directives = True`` in ``conf.py`` will tell you the directive Breathe tried to run just before the crash.
But in the end, I suggest making a copy of the project and delete files to make a slimmed down example which is easier to debug.

**Comment by kausky** [comment]
> > So what can i really do to debug this, Some help or guidance would be appreciated.
> 
> Sure. As mentioned, running with `breathe_debug_trace_directives = True` in `conf.py` will tell you the directive Breathe tried to run just before the crash.
> But in the end, I suggest making a copy of the project and delete files to make a slimmed down example which is easier to debug.

Thanks i will try debugging with `breathe_debug_trace_directives = True` but as you said mlpack is reather large and i don't know which files i can delete without having a problem where it tries to find a function def follwing a file and it just isin't there.

**Comment by kausky** [comment]
Hi, thanks foe helping me out with this, i would close this as this was just a issue with us not configuring it properly and probably can be solved by doing that.
