### ISSUE TITLE
building pyhht docs: AttributeError: 'Sphinx' object has no attribute 'add_javascript'

### ISSUE THREAD

**Issue by johndavidmiller** [sphinx-doc/sphinx#9372]
Doesn't sound like an error with Sphinx, tho perhaps indicates a method missing in v4.0.2. that was in an older version?  I wouldn't be reporting this, were it not for the message in the traceback asking for reports like this. :-)

I'm trying to build the docs for [pyhht,](https://github.com/jaidevd/pyhht) and it throws this error, which is why I think it must be a version thing:

```sh
pyhht/docs $ make singlehtml
sphinx-build -b singlehtml -d build/doctrees   source build/singlehtml
Running Sphinx v4.0.2
making output directory... done

Exception occurred:
  File "/Users/jdm/Dropbox/Tools/Software/Python/pyhht/docs/source/conf.py", line 282, in setup
    app.add_javascript("https://docs.python.org/2/_static/copybutton.js")
AttributeError: 'Sphinx' object has no attribute 'add_javascript'
The full traceback has been saved in /var/folders/cs/lqjsdh5s69dd7csnhrxwmbgm0000gn/T/sphinx-err-gnmyqxeg.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [singlehtml] Error 2
```

And the log file shows this:

```sh
pyhht/docs $ more /var/folders/cs/lqjsdh5s69dd7csnhrxwmbgm0000gn/T/sphinx-err-gnmyqxeg.log
# Sphinx version: 4.0.2
# Python version: 3.8.8 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 2.11.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/Applications/anaconda3/lib/python3.8/site-packages/sphinx/application.py", line 257, in __init__
    self.config.setup(self)
  File "/Users/jdm/Dropbox/Tools/Software/Python/pyhht/docs/source/conf.py", line 282, in setup
    app.add_javascript("https://docs.python.org/2/_static/copybutton.js")
AttributeError: 'Sphinx' object has no attribute 'add_javascript'
```

**Comment by astrojuanlu** [comment]
`app.add_javascript()` was deprecated in 1.8.0b1, 3 years ago https://www.sphinx-doc.org/en/master/changes.html#id116 

About the question of whether that message to report the issue should appear or not, I'm not sure :) But definitely this is not a bug

**Comment by tk0miya** [comment]
Yes, `add_javascript()` was deprecated in v1.8 and removed in v4.0. `add_js_file()` is a successor of the API.

BTW, Sphinx has also provided `html_js_files` configuration since v1.8. I think it's better to use it instead of API.
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_js_files
