### ISSUE TITLE
[sphinxcontrib-excel-table-plus 1.0.8.2] Can't handle LibreOffice created xlsx file (raise IndexError)

### ISSUE THREAD

**Issue by odys-z** [sphinx-doc/sphinx#9388]
Hello,

I've trying include an xlsx file in my sphinx doc project. The file is created by [LibreOffice Calc](https://en.wikipedia.org/wiki/LibreOffice_Calc) then saved as .xlsx file. But sphinx report erros.

**Describe the bug**
Can't handle xlsx file.

Error Report

````
 Exception occurred:
  File "/home/ody/.local/lib/python3.9/site-packages/openpyxl/worksheet/worksheet.py", line 293, in __getitem__
    raise IndexError("{0} is not a valid coordinate or range".format(key))
IndexError: 0 is not a valid coordinate or range
The full traceback has been saved in /tmp/sphinx-err-cwgkwmz5.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:46: recipe for target 'html' failed
make[1]: *** [html] Error 2
make[1]: Leaving directory '/home/ody/git/hello/docsphinx'
Makefile:32: recipe for target 'ghpage' failed
make: *** [ghpage] Error 2
````

in rst

```
.. excel-table::
   :file: res/xmpp-survey.xlsm

```

You can find log file and xlsx file here:

[sphinx source subfolder](https://github.com/odys-z/hello/tree/master/docsphinx/misc/res)

**To Reproduce**

I think the readme file above is enough but in case anyone would like to try to make html pages, here is a way to avoid cloning the large (useless) repository:

- download the zip file [here](https://github.com/odys-z/hello)

- extract locally and in hello/docsphinx, run 

```
make ghpage
```

(Only the 'docsphinx' sub-folder is useful)

**Environment info**
- OS: ubuntu 16.04 LTS
- Python version: 3.9
- Sphinx version: v4.0.2
- Sphinx extensions:  sphinxcontrib-excel-table-plus 1.0.8.2
- Extra tools: LibreOffice Calc for Ubuntu desktop

**Comment by astrojuanlu** [comment]
I see that the repository for this extension is https://github.com/emerge-ehri/sphinxcontrib-excel-table-plus, but issues are not allowed. @larrybabb

**Comment by odys-z** [comment]
Oh, 
I haven't aware of that. I just follow the link in the error message and go here.
I can close this issue if necessary :)

**Comment by astrojuanlu** [comment]
No need to close the issue yet, I think. There's no way to report it there anyway 😅 

For the record, this is the full traceback:

```
# Sphinx version: 4.0.2
# Python version: 3.9.0 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.1
# Last messages:
#   reading sources... [ 80%] acsl/lect06/index
#   reading sources... [ 81%] acsl/lect06/issue_int
#   reading sources... [ 83%] acsl/lect06/topics
#   reading sources... [ 85%] amc/aime-2021
#   reading sources... [ 86%] amc/index
#   reading sources... [ 88%] amc/p01-stars-bars
#   reading sources... [ 90%] amc/p02-mass-point
#   reading sources... [ 91%] cemc/hypatia-galois-2021
#   reading sources... [ 93%] index
#   reading sources... [ 95%] misc/miscellaneous
# Loaded extensions:
#   sphinx.ext.mathjax (4.0.2) from /home/ody/.local/lib/python3.9/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/ody/.local/lib/python3.9/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/ody/.local/lib/python3.9/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /home/ody/.local/lib/python3.9/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /home/ody/.local/lib/python3.9/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/ody/.local/lib/python3.9/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/ody/.local/lib/python3.9/site-packages/alabaster/__init__.py
#   sphinxcontrib.excel_table_plus (0.0.1) from /home/ody/.local/lib/python3.9/site-packages/sphinxcontrib/excel_table_plus/__init__.py
#   sphinx_rtd_theme (unknown version) from /home/ody/.local/lib/python3.9/site-packages/sphinx_rtd_theme/__init__.py
Traceback (most recent call last):
  File "/home/ody/.local/lib/python3.9/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/ody/.local/lib/python3.9/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/home/ody/.local/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 292, in build_update
    self.build(to_build,
  File "/home/ody/.local/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 306, in build
    updated_docnames = set(self.read())
  File "/home/ody/.local/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 413, in read
    self._read_serial(docnames)
  File "/home/ody/.local/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 434, in _read_serial
    self.read_doc(docname)
  File "/home/ody/.local/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 474, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/ody/.local/lib/python3.9/site-packages/sphinx/io.py", line 188, in read_doc
    pub.publish()
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/ody/.local/lib/python3.9/site-packages/sphinx/io.py", line 108, in read
    self.parse()
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/ody/.local/lib/python3.9/site-packages/sphinx/parsers.py", line 100, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/home/ody/.local/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/ody/.local/lib/python3.9/site-packages/sphinxcontrib/excel_table_plus/excel_table.py", line 175, in run
    xforms = [[[None] * len(transforms)] * len(sheet_data[0])] * len(sheet_data)
  File "/home/ody/.local/lib/python3.9/site-packages/openpyxl/worksheet/worksheet.py", line 293, in __getitem__
    raise IndexError("{0} is not a valid coordinate or range".format(key))
IndexError: 0 is not a valid coordinate or range
```

**Comment by tk0miya** [comment]
@astrojuanlu Thank you for your comment. It seems this is a bug of the excel-table-plus extension. Nothing to do from Sphinx-core side, I think.

**Comment by odys-z** [comment]
It's an error raised in a dependency lib I think:

```
    from openpyxl import load_workbook
```

(Mark here for future action if it's possible)

Let's close this.
