### ISSUE TITLE
Templated class with deprecated attribute -> Invalid C++ declaration: Expected identifier in nested name

### ISSUE THREAD

**Issue by Pro** [sphinx-doc/sphinx#9451]
### Describe the bug

I have a code where I use templated classes.
One of these I now marked as deprecated (see code below).

Sphinx fails with:

```
Exception occurred:
  File "/path/to/sphinx/3.4.3/lib/python3.6/site-packages/sphinx/util/cfamily.py", line 291, in fail
    raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name. [error at 1]
  ((deprecated("Do not use this")))
  -^
```

### How to Reproduce

Use the following code:

```cpp

template <typename TReq>
class BaseClass<TReq>
{

}

template <typename TReq>
class [[deprecated("Do not use this!")]] SomeOldClass<TReq> : public BaseClass<Treq>
{

}
```

### Your project

See how to reproduce

### OS

Linux

### Python version

3.6.9

### Sphinx version

3.4.3

**Comment by jakobandersen** [comment]
Thanks for reporting, though I will need some more information:
Do you use Breathe or other extensions? and if so, which version? and which directive was spawned the error?
Have you tried with the latest version of Sphinx (and Breathe if that's what you use)?
Is the code available for reproduction? or do you have a minimal case that reproduces the problem?

**Comment by Pro** [comment]
@Jacob-Stevens-Haas thanks for the response!

I created a simple repo which can be used to reproduce the issue:
https://github.com/Pro/sphinx-cpp-test

Just clone, then run `doxygen && python3 -msphinx docs build `

The CMakeLists.txt is there to verify that it is valid C++ code:
```
mkdir build
cd build
cmake ..
make -j
```

I tested with:
- Sphinx 4.1.1
- Breathe: 4.30.0
- exhale: 0.2.3

I even tested with this MR:
https://github.com/michaeljones/breathe/pull/711

But for all of them I get the following output:

```
Running Sphinx v4.1.1
making output directory... done
[~] Exhale: adding tree view css / javascript.
[+] Exhale: added tree view css / javascript.
[~] Exhale: parsing Doxygen XML.
[+] Exhale: finished parsing Doxygen XML in 0.01 seconds.
[~] Exhale: generating reStructuredText documents.
(!) Unabridged API: unexpected kind 'page' (IGNORED)
[+] Exhale: generated reStructuredText documents in 0.01 seconds.
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: [new config] 16 added, 0 changed, 0 removed
reading sources... [ 50%] api/function_namespacesphinx__test_1a1ab9cb1bffa6c244f60ee002c180178b                                                                                                                                 
Exception occurred:
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/util/cfamily.py", line 275, in fail
    raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name. [error at 1]
  ("This is a deprecated class and you should not use it!")
  -^
```

And the Traceback:

```
# Sphinx version: 4.1.1
# Python version: 3.6.9 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.11.3
# Last messages:
#   reading sources... [ 25%] api/file_README.md
#   
#   reading sources... [ 31%] api/file_include_BaseClass.hpp
#   
#   reading sources... [ 37%] api/file_include_SubClass.hpp
#   
#   reading sources... [ 43%] api/file_view_hierarchy
#   
#   reading sources... [ 50%] api/function_namespacesphinx__test_1a1ab9cb1bffa6c244f60ee002c180178b
#   
# Loaded extensions:
#   sphinx.ext.mathjax (4.1.1) from /home/sp/.local/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/sp/.local/lib/python3.6/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/sp/.local/lib/python3.6/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /home/sp/.local/lib/python3.6/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /home/sp/.local/lib/python3.6/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/sp/.local/lib/python3.6/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.8) from /usr/lib/python3/dist-packages/alabaster/__init__.py
#   breathe (4.30.0) from /home/sp/.local/lib/python3.6/site-packages/breathe/__init__.py
#   exhale (0.2.3) from /home/sp/.local/lib/python3.6/site-packages/exhale/__init__.py
#   sphinx.ext.intersphinx (4.1.1) from /home/sp/.local/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (4.1.1) from /home/sp/.local/lib/python3.6/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /home/sp/.local/lib/python3.6/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.1.1) from /home/sp/.local/lib/python3.6/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.1.1) from /home/sp/.local/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
Traceback (most recent call last):
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 295, in build_update
    len(to_build))
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 307, in build
    updated_docnames = set(self.read())
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 414, in read
    self._read_serial(docnames)
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 435, in _read_serial
    self.read_doc(docname)
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 475, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/io.py", line 188, in read_doc
    pub.publish()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/io.py", line 108, in read
    self.parse()
  File "/usr/lib/python3/dist-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/parsers.py", line 100, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 172, in run
    input_source=document['source'])
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2754, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 396, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 283, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 197, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2754, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 396, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 283, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 197, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2327, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2339, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2082, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2131, in run_directive
    result = directive_instance.run()
  File "/home/sp/.local/lib/python3.6/site-packages/breathe/directives.py", line 81, in run
    args = self._parse_args(args)
  File "/home/sp/.local/lib/python3.6/site-packages/breathe/directives.py", line 145, in _parse_args
    paramQual = parser._parse_parameters_and_qualifiers(paramMode='function')
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/domains/cpp.py", line 5912, in _parse_parameters_and_qualifiers
    arg = self._parse_type_with_init(outer=None, named='single')
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/domains/cpp.py", line 6424, in _parse_type_with_init
    type = self._parse_type(outer=outer, named=named)
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/domains/cpp.py", line 6415, in _parse_type
    declSpecs = self._parse_decl_specs(outer=outer)
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/domains/cpp.py", line 6109, in _parse_decl_specs
    trailing = self._parse_trailing_type_spec()
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/domains/cpp.py", line 5874, in _parse_trailing_type_spec
    nestedName = self._parse_nested_name()
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/domains/cpp.py", line 5796, in _parse_nested_name
    self.fail("Expected identifier in nested name.")
  File "/home/sp/.local/lib/python3.6/site-packages/sphinx/util/cfamily.py", line 275, in fail
    raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name. [error at 1]
  ("This is a deprecated class and you should not use it!")
  -^
```

**Comment by jakobandersen** [comment]
@Pro, I just tried your example (with ``breathe_debug_trace_directives = True`` in ``conf.py``) but I get the following output:
```
Running Sphinx v4.2.0
[~] Exhale: adding tree view css / javascript.
[+] Exhale: added tree view css / javascript.
[~] Exhale: parsing Doxygen XML.
[+] Exhale: finished parsing Doxygen XML in 0.01 seconds.
[~] Exhale: generating reStructuredText documents.
(!) Unabridged API: unexpected kind 'page' (IGNORED)
[+] Exhale: generated reStructuredText documents in 0.01 seconds.
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 16 source files that are out of date
updating environment: [new config] 16 added, 0 changed, 0 removed
Running directive: .. cpp:class:: template<typename T_A, typename T_B> sphinx_test::BaseClass                                                                           
Running directive: .. cpp:class:: template<typename T_A, typename T_B> sphinx_test::SubClass : public sphinx_test::BaseClass< T_A, T_B >                                
Running directive: .. cpp:class:: template<typename T_A, typename T_B> sphinx_test::BaseClass                                                                           
  Running directive: .. cpp:var::   public  
  Running directive: .. cpp:var::  T_A a  
  Running directive: .. cpp:var::  T_B b  
Running directive: .. cpp:class:: template<typename T_A, typename T_B> sphinx_test::SubClass : public sphinx_test::BaseClass< T_A, T_B >
Running directive: .. cpp:type:: sphinx_test
reading sources... [100%] api/unabridged_orphan                                                                                                                         
/sphinx-cpp-test/docs/api/index.rst:6: WARNING: Duplicate C++ declaration, also defined at api/classsphinx__test_1_1BaseClass:22.
Declaration is '.. cpp:class:: template<typename T_A, typename T_B> sphinx_test::BaseClass'.
/sphinx-cpp-test/docs/api/index.rst:6: WARNING: Invalid C++ declaration: Expected identifier in nested name. [error at 6]
  public
  ------^
/sphinx-cpp-test/docs/api/index.rst:6: WARNING: Duplicate C++ declaration, also defined at api/classsphinx__test_1_1SubClass:22.
Declaration is '.. cpp:class:: template<typename T_A, typename T_B> sphinx_test::SubClass : public sphinx_test::BaseClass< T_A, T_B >'.

Sphinx error:
root file /sphinx-cpp-test/docs/index.rst not found
```
Which output do you get now? and with which versions of Doxygen, Exhale, Breathe, and Sphinx?
I'm a bit unsure exactly what Exhale does, so if you can create a minimized example without it that may help figure out where the problem is.

**Comment by Pro** [comment]
Thanks for your answer!

I updated the branch here to fix the requirements, now I am using the following versions:
https://github.com/Pro/sphinx-cpp-test

- Doxygen 1.8.20

And as noted in the requirements.txt:
```
sphinx==4.1.1
breathe==4.31.0
exhale==0.2.3
```

Seems with these versions the issue is fixed!

Thanks
