### ISSUE TITLE
Exception when building  to Latex

### ISSUE THREAD

**Issue by drmartinjaros** [sphinx-doc/sphinx#9465]
### Describe the bug

Exception occurred:
  File "c:\program files\python38\lib\site-packages\sphinx\writers\latex.py", line 2072, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: enumerable_node

Sphinx version: 3.5.4
Python version: 3.8.2 (CPython)
Docutils version: 0.16 release
Jinja2 version: 3.0.1
Last messages:
     resolving references...   done
   writing...
   failed
 Loaded extensions:
   sphinx.ext.mathjax (3.5.4) from c:\program files\python38\lib\site-packages\sphinx\ext\mathjax.py
   sphinxcontrib.applehelp (1.0.2) from c:\program files\python38\lib\site-packages\sphinxcontrib\applehelp\__init__.py
   sphinxcontrib.devhelp (1.0.2) from c:\program files\python38\lib\site-packages\sphinxcontrib\devhelp\__init__.py
   sphinxcontrib.htmlhelp (2.0.0) from c:\program files\python38\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
   sphinxcontrib.serializinghtml (1.1.5) from c:\program files\python38\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
   sphinxcontrib.qthelp (1.0.3) from c:\program files\python38\lib\site-packages\sphinxcontrib\qthelp\__init__.py
   alabaster (0.7.12) from c:\program files\python38\lib\site-packages\alabaster\__init__.py
   rst2pdf.pdfbuilder (0.98) from c:\program files\python38\lib\site-packages\rst2pdf\pdfbuilder.py
   sphinx_copybutton (0.3.3) from c:\program files\python38\lib\site-packages\sphinx_copybutton\__init__.py
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\sphinx\cmd\build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "c:\program files\python38\lib\site-packages\sphinx\application.py", line 352, in build
    self.builder.build_update()
  File "c:\program files\python38\lib\site-packages\sphinx\builders\__init__.py", line 293, in build_update
    self.build(['__all__'], to_build)
  File "c:\program files\python38\lib\site-packages\sphinx\builders\__init__.py", line 360, in build
    self.write(docnames, list(updated_docnames), method)
  File "c:\program files\python38\lib\site-packages\sphinx\builders\latex\__init__.py", line 304, in write
    docwriter.write(doctree, destination)
  File "c:\program files\python38\lib\site-packages\docutils\writers\__init__.py", line 78, in write
    self.translate()
  File "c:\program files\python38\lib\site-packages\sphinx\writers\latex.py", line 101, in translate
    self.document.walkabout(visitor)
  File "c:\program files\python38\lib\site-packages\docutils\nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "c:\program files\python38\lib\site-packages\docutils\nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "c:\program files\python38\lib\site-packages\docutils\nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 4 more times]
  File "c:\program files\python38\lib\site-packages\docutils\nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "c:\program files\python38\lib\site-packages\sphinx\util\docutils.py", line 471, in dispatch_visit
    super().dispatch_visit(node)
  File "c:\program files\python38\lib\site-packages\docutils\nodes.py", line 1995, in dispatch_visit
    return method(node)
  File "c:\program files\python38\lib\site-packages\sphinx\writers\latex.py", line 2072, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: enumerable_node

### How to Reproduce

sphinx-build -b latex ./ ./_latex

### Your project

n/a

### OS

Windows / Mac

### Python version

3.8

### Sphinx version

3.5.4

### Sphinx extensions

['rst2pdf.pdfbuilder', 'sphinx_exercise','sphinx_copybutton']

**Comment by tk0miya** [comment]
It seems sphinx_exercise does not support LaTeX builds. Please report this into their project.
https://github.com/executablebooks/sphinx-exercise/blob/78bf69bd5a68512ea3029999c23f3d186c24203c/sphinx_exercise/__init__.py#L352-L358

Thanks,
