### ISSUE TITLE
app.registry.get_translator_class returns 'property' objects for certain builders.

### ISSUE THREAD

**Issue by domdfcoding** [sphinx-doc/sphinx#9496]
### Describe the bug

`sphinx.builders.html.StandaloneHTMLBuilder` uses a property for `default_translator_class`, but in the base class it's a conventional variable. This means that code using `app.registry.get_translator_class` for any builder that subclasses `StandaloneHTMLBuilder` is given a `property` object rather than the actual `nodes.NodeVisitor` class. 

### How to Reproduce

The example `conf.py` below illustrates what I'm doing:

``` python
from docutils.nodes import paragraph

def setup(app):
    builder = app.registry.builders["epub"]
    epub_translator = app.registry.get_translator_class(builder)
    app.add_node(paragraph, epub=(epub_translator.visit_paragraph, epub_translator.depart_paragraph))
```

Running `sphinx-build -M html . ./build -T`:

```python traceback
Running Sphinx v4.1.1

Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "venv/lib/python3.8/site-packages/sphinx/application.py", line 251, in __init__
    self.config.setup(self)
  File "conf.py", line 7, in setup
    app.add_node(paragraph, epub=(epub_translator.visit_paragraph, epub_translator.depart_paragraph))
AttributeError: 'property' object has no attribute 'visit_paragraph'

Exception occurred:
  File "conf.py", line 7, in setup
    app.add_node(paragraph, epub=(epub_translator.visit_paragraph, epub_translator.depart_paragraph))
AttributeError: 'property' object has no attribute 'visit_paragraph'
The full traceback has been saved in /tmp/sphinx-err-46tp_ln9.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

### Expected behavior

The `default_translator_class` attribute, and `app.registry.get_translator_class`, should always returns a `nodes.NodeVisitor` class, per the type annotations on both.

### Your project

N/A

### OS

Ubuntu 20.04

### Python version

3.8.10

### Sphinx version

2.0.0 - 4.1.1

### Sphinx extensions

None

### Extra tools

None

### Additional context

The offending code is here:
https://github.com/sphinx-doc/sphinx/blob/07598f0d6f3208a6c5e8c20a381730cbb45544b2/sphinx/builders/html/__init__.py#L335-L340

I suspect the `# type: ignore` is there because mypy was warning about exactly this issue. If I remove the comment I get an (albeit cryptic) error:

```
sphinx/builders/html/__init__.py: note: In class "StandaloneHTMLBuilder":
sphinx/builders/html/__init__.py:336:5: error: Signature of "default_translator_class" incompatible with supertype "Builder"
```

mypy has determined the signature to be `def (self: sphinx.builders.html.StandaloneHTMLBuilder) -> Type[docutils.nodes.NodeVisitor]`.

**Comment by tk0miya** [comment]
```
    builder = app.registry.builders["epub"]
    epub_translator = app.registry.get_translator_class(builder)
```

This is incorrect code. `app.registry.get_translator_class()` takes an instance of builder. But you passed a builder class, not an instance. I think the code that you want is this:

```
def setup(app):
    builder = app.registry.create_builder(app, "builder")
    epub_translator = app.registry.get_translator_class(builder)
    app.add_node(paragraph, epub=(epub_translator.visit_paragraph, epub_translator.depart_paragraph))
```

BTW, why do you want to get visitor functions? I think it's enough to call `visit_paragraph()` handler from your custom handler:

```
def epub_visit_my_node(self, node):
    self.visit_paragraph(node)

def setup(app):
    app.add_node(my_node, epub=(epub_visit_my_node, epub_depart_my_node))
```
