### ISSUE TITLE
TypeError: 'AdaLexer' object is not callable

### ISSUE THREAD

**Issue by michelou** [sphinx-doc/sphinx#9544]
### Describe the bug

The generated log file `C:\Temp\sphinx-err-368qgxmo.log` looks as follows (cf. section "How to reproduce"):
```
# Sphinx version: 4.1.2
# Python version: 3.9.6 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.1
# Last messages:
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  8%] aunit_cb
#   writing output... [ 16%] aunit_cb/fixture
# Loaded extensions:
#   sphinx.ext.mathjax (4.1.2) from c:\opt\Python-3.9.6\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from c:\opt\Python-3.9.6\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.2) from c:\opt\Python-3.9.6\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from c:\opt\Python-3.9.6\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from c:\opt\Python-3.9.6\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.3) from c:\opt\Python-3.9.6\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from c:\opt\Python-3.9.6\lib\site-packages\alabaster\__init__.py
Traceback (most recent call last):
  File "c:\opt\Python-3.9.6\lib\site-packages\sphinx\cmd\build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "c:\opt\Python-3.9.6\lib\site-packages\sphinx\application.py", line 343, in build
    self.builder.build_update()
  File "c:\opt\Python-3.9.6\lib\site-packages\sphinx\builders\__init__.py", line 293, in build_update
    self.build(to_build,
  File "c:\opt\Python-3.9.6\lib\site-packages\sphinx\builders\__init__.py", line 357, in build
    self.write(docnames, list(updated_docnames), method)
  File "c:\opt\Python-3.9.6\lib\site-packages\sphinx\builders\__init__.py", line 531, in write
    self._write_serial(sorted(docnames))
  File "c:\opt\Python-3.9.6\lib\site-packages\sphinx\builders\__init__.py", line 541, in _write_serial
    self.write_doc(docname, doctree)
  File "c:\opt\Python-3.9.6\lib\site-packages\sphinx\builders\html\__init__.py", line 622, in write_doc
    self.docwriter.write(doctree, destination)
  File "c:\opt\Python-3.9.6\lib\site-packages\docutils\writers\__init__.py", line 78, in write
    self.translate()
  File "c:\opt\Python-3.9.6\lib\site-packages\sphinx\writers\html.py", line 70, in translate
    self.document.walkabout(visitor)
  File "c:\opt\Python-3.9.6\lib\site-packages\docutils\nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "c:\opt\Python-3.9.6\lib\site-packages\docutils\nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "c:\opt\Python-3.9.6\lib\site-packages\docutils\nodes.py", line 219, in walkabout
    visitor.dispatch_visit(self)
  File "c:\opt\Python-3.9.6\lib\site-packages\sphinx\util\docutils.py", line 469, in dispatch_visit
    method(node)
  File "c:\opt\Python-3.9.6\lib\site-packages\sphinx\writers\html5.py", line 417, in visit_literal_block
    highlighted = self.highlighter.highlight_block(
  File "c:\opt\Python-3.9.6\lib\site-packages\sphinx\highlighting.py", line 149, in highlight_block
    lexer = self.get_lexer(source, lang, opts, force, location)
  File "c:\opt\Python-3.9.6\lib\site-packages\sphinx\highlighting.py", line 127, in get_lexer
    lexer = lexer_classes[lang](**opts)
TypeError: 'AdaLexer' object is not callable
```

### Context
- Directory `aunit-21.0.0\` extracted from archive file [`v21.0.0.zip`](https://github.com/AdaCore/aunit/releases/tag/v21.0.0) in GitHub project [`AdaCore/aunit`](https://github.com/AdaCore/aunit).
- [Python 3.9.6](https://www.python.org/downloads/windows/) installed in directory `c:\opt\python-3.9.6\`

### Console output
```
> cd
C:\aunit-21.0.0

> make -C doc
make: Entering directory '/c/aunit-21.0.0/doc'
make  aunit_cb.html  aunit_cb.pdf  aunit_cb.txt  aunit_cb.info
make[1]: Entering directory '/c/aunit-21.0.0/doc'
DOC_NAME=aunit_cb sphinx-build -b html   -c ./share -d build/aunit_cb/doctrees . build/aunit_cb/html
Running Sphinx v4.1.2
ignoring build
ignoring Makefile
WARNING: html_static_path entry '_static' does not exist
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 12 source files that are out of date
updating environment: [new config] 12 added, 0 changed, 0 removed
reading sources... [100%] share/gnu_free_documentation_license                 es
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 16%] aunit_cb/fixture
Exception occurred:
  File "c:\opt\Python-3.9.6\lib\site-packages\sphinx\highlighting.py", line 127, in get_lexer
    lexer = lexer_classes[lang](**opts)
TypeError: 'AdaLexer' object is not callable
The full traceback has been saved in C:\Temp\sphinx-err-368qgxmo.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[1]: *** [Makefile:51: aunit_cb.html] Error 2
make[1]: Leaving directory '/c/aunit-21.0.0/doc'
make: *** [Makefile:78: aunit_cb.all] Error 2
make: Leaving directory '/c/aunit-21.0.0/doc'
``` 

### Expected behavior

Command `make -C doc` generates the following files: 

```
aunit_cb.html  aunit_cb.pdf  aunit_cb.txt  aunit_cb.info
```

### Your project

https://github.com/AdaCore/aunit/releases/tag/v21.0.0

### OS

Win 10

### Python version

3.9.6

### Sphinx version

4.1.2

**Comment by tk0miya** [comment]
`add_lexer()` takes a Lexer class instead of an instance. Could you pass the `AdaLexer` as a class?
https://github.com/AdaCore/aunit/blob/v21.0.0/doc/share/conf.py#L98-L100

**Comment by michelou** [comment]
@tk0miya Thanks ! The following works for me:
```python
def setup(app):
    app.add_lexer('ada', ada_pygments.AdaLexer)
    app.add_lexer('gpr', ada_pygments.GNATProjectLexer)
```
I now have other pitfalls *not related* to Sphinx for generating the [AUnit documentation](https://github.com/AdaCore/aunit) in my Windows environment; I'm closing this issue.
