### ISSUE TITLE
cannot load library 'pango-1.0-0': pango-1.0-0: cannot open shared object file

### ISSUE THREAD

**Issue by aabanaag** [sphinx-doc/sphinx#9566]
### Describe the bug

I was using django-weasyprint but all of a sudden my build is failing and I can't build my app because of the error. I didn't change anything. I have cookiecutter-django configured but when I created an issue on weasyprint repo it turns out that it is a config issue on sphinx not on weasyprint.

```
water_conservation_docs | Traceback (most recent call last):
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/sphinx/config.py", line 327, in eval_config_file
water_conservation_docs |     execfile_(filename, namespace)
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
water_conservation_docs |     exec(code, _globals)
water_conservation_docs |   File "/docs/conf.py", line 27, in <module>
water_conservation_docs |     django.setup()
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
water_conservation_docs |     apps.populate(settings.INSTALLED_APPS)
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
water_conservation_docs |     app_config.ready()
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/apps.py", line 24, in ready
water_conservation_docs |     self.module.autodiscover()
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
water_conservation_docs |     autodiscover_modules('admin', register_to=site)
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
water_conservation_docs |     import_module('%s.%s' % (app_config.name, module_to_search))
water_conservation_docs |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
water_conservation_docs |     return _bootstrap._gcd_import(name[level:], package, level)
water_conservation_docs |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
water_conservation_docs |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
water_conservation_docs |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
water_conservation_docs |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
water_conservation_docs |   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
water_conservation_docs |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
water_conservation_docs |   File "/app/water_conservation_api/core/admin.py", line 16, in <module>
water_conservation_docs |     from water_conservation_api.core.services import OrganizationService
water_conservation_docs |   File "/app/water_conservation_api/core/services.py", line 27, in <module>
water_conservation_docs |     from water_conservation_api.core.tasks import (
water_conservation_docs |   File "/app/water_conservation_api/core/tasks.py", line 17, in <module>
water_conservation_docs |     from water_conservation_api.utils.helpers import generate_pdf, send_job_notification
water_conservation_docs |   File "/app/water_conservation_api/utils/helpers.py", line 9, in <module>
water_conservation_docs |     from weasyprint import HTML
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/weasyprint/__init__.py", line 322, in <module>
water_conservation_docs |     from .css import preprocess_stylesheet  # noqa isort:skip
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/weasyprint/css/__init__.py", line 27, in <module>
water_conservation_docs |     from . import computed_values, counters, media_queries
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/weasyprint/css/computed_values.py", line 16, in <module>
water_conservation_docs |     from ..text.ffi import ffi, pango, units_to_double
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/weasyprint/text/ffi.py", line 383, in <module>
water_conservation_docs |     pango = _dlopen(
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/weasyprint/text/ffi.py", line 377, in _dlopen
water_conservation_docs |     return ffi.dlopen(names[0])  # pragma: no cover
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 150, in dlopen
water_conservation_docs |     lib, function_cache = _make_ffi_library(self, name, flags)
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library
water_conservation_docs |     backendlib = _load_backend_lib(backend, libname, flags)
water_conservation_docs |   File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 827, in _load_backend_lib
water_conservation_docs |     raise OSError(msg)
water_conservation_docs | OSError: cannot load library 'pango-1.0-0': pango-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'


```

### How to Reproduce

I configured cookiecutter-django then added django-weasyprint or just weasyprint package from pypi

### Your project

I couldn't link anything sorry...

### OS

MacOS

### Python version

3.8.9

### Sphinx version

3.5.3

### Sphinx extensions

autodoc, napoleon

**Comment by astrojuanlu** [comment]
This looks like an installation issue with pango that is not related to Sphinx. Also, I might be mistaken but this seems to come from a Docker image orchestrated by docker-compose and you didn't provide any information to reproduce the issue, so it's unlikely that Sphinx devs can help here.

**Comment by aabanaag** [comment]
I'll create a sample repo to reproduce the issue, but basically the project I'm working with was configured using cookiecutter-django (we didn't change any configurations) then just added django-weasyprint or weasyprint to the requirements.txt
