### ISSUE TITLE
"Exception occurred: IndexError: list index out of range" during make html

### ISSUE THREAD

**Issue by MetinSa** [sphinx-doc/sphinx#9580]
### Describe the bug

The error occurs when i attempt to run `make html`. This is the log:

```
# Sphinx version: 4.1.2
# Python version: 3.8.10 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.1
# Last messages:
#   reading sources... [ 72%] generated/cosmoglobe.Radio
#   reading sources... [ 75%] generated/cosmoglobe.Radio.__call__
#   reading sources... [ 78%] generated/cosmoglobe.Radio.label
#   reading sources... [ 81%] generated/cosmoglobe.Synchrotron
#   reading sources... [ 84%] generated/cosmoglobe.Synchrotron.__call__
#   reading sources... [ 87%] generated/cosmoglobe.Synchrotron.label
#   reading sources... [ 90%] index
#   reading sources... [ 93%] install
#   reading sources... [ 96%] license
#   reading sources... [100%] tutorial
# Loaded extensions:
#   sphinx.ext.mathjax (4.1.2) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.1.2) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.1.2) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (4.1.2) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.viewcode (4.1.2) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   numpydoc (1.1.0) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/numpydoc/__init__.py
#   nbsphinx (0.8.6) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/nbsphinx.py
#   pydata_sphinx_theme (unknown version) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/pydata_sphinx_theme/__init__.py
#   sphinx_rtd_theme (unknown version) from /opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx_rtd_theme/__init__.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 307, in build
    updated_docnames = set(self.read())
  File "/opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 414, in read
    self._read_serial(docnames)
  File "/opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 435, in _read_serial
    self.read_doc(docname)
  File "/opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 475, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/io.py", line 188, in read_doc
    pub.publish()
  File "/opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/sphinx/transforms/__init__.py", line 86, in apply_transforms
    super().apply_transforms()
  File "/opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/nbsphinx.py", line 1655, in apply
    location=self.document[0],
  File "/opt/anaconda3/envs/cosmoglobe/lib/python3.8/site-packages/docutils/nodes.py", line 627, in __getitem__
    return self.children[key]
IndexError: list index out of range
```

It is very similar to this issue https://github.com/sphinx-doc/sphinx/issues/8300, but I have not used `autodocsumm`.
I encountered this bug following a recent switch to using poetry as a dependency manager.

### How to Reproduce

Reproducing this requires poetry (https://python-poetry.org/).

Steps to reproduce:
- start by cloning https://github.com/Cosmoglobe/Cosmoglobe/
- checkout devel branch
- run `poetry install`
- cd into docs/
- run `make html`

### Your project

https://github.com/Cosmoglobe/Cosmoglobe/tree/devel

### OS

Mac

### Python version

3.8

### Sphinx version

4.1.2

### Sphinx extensions

numpydoc, ipython, pydata-sphinx-theme, nbsphinx, ipykernel, pandoc, sphinx, jupyter, sphinx-rtd-theme

**Comment by MetinSa** [comment]
Update: It seems that removing `nbsphinx` from the extensions lists allows the build to pass.

**Comment by MetinSa** [comment]
Update: I was able to make the build run by installing nbsphinx with conda rather than poetry. It seems that there are some hidden dependencies that are not correctly resolved by purely using poetry.
