### ISSUE TITLE
Support Python 3.3

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#962]
I'm fooling around with Python v3.3b1 and Sphinx doesn't seem to work on it. I get this error:

```
# Sphinx version: 1.2pre
# Python version: 3.3.0b1
# Docutils version: 0.9.1 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/Sphinx-1.2predev_20120708-py3.3.egg/sphinx/cmdline.py", line 190, in main
    app.build(force_all, filenames)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/Sphinx-1.2predev_20120708-py3.3.egg/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/Sphinx-1.2predev_20120708-py3.3.egg/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/Sphinx-1.2predev_20120708-py3.3.egg/sphinx/builders/__init__.py", line 216, in build
    purple, length):
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/Sphinx-1.2predev_20120708-py3.3.egg/sphinx/builders/__init__.py", line 120, in status_iterator
    for item in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/Sphinx-1.2predev_20120708-py3.3.egg/sphinx/environment.py", line 613, in update_generator
    self.read_doc(docname, app=app)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/Sphinx-1.2predev_20120708-py3.3.egg/sphinx/environment.py", line 756, in read_doc
    pub.set_components(None, 'restructuredtext', None)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/docutils-0.9.1-py3.3.egg/docutils/core.py", line 96, in set_components
    self.reader.set_parser(parser_name)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/docutils-0.9.1-py3.3.egg/docutils/readers/__init__.py", line 60, in set_parser
    parser_class = parsers.get_parser_class(parser_name)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/docutils-0.9.1-py3.3.egg/docutils/parsers/__init__.py", line 46, in get_parser_class
    module = __import__(parser_name, globals(), locals())
  File "<frozen importlib._bootstrap>", line 1294, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1258, in _find_and_load_unlocked
ImportError: No module named 'rst'
```

Is it a docutils problem or a sphinx one?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/962
- Originally reported by: Virgil Dupras
- Originally created at: 2012-07-08T15:17:05.047

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2012-07-08 13:19:20+00:00_

It's a docutils or Python problem.  3.3 with the importlib import system does a few things more strictly than before. This looks to be an explicit/implicit relative import bug in how docutils loads its parser (but it may also be a Python bug, so please contact the docutils developers about it).

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2012-10-30 05:34:11+00:00_

It is docutils-0.9.1 problem. docutils trunk version (maybe become 0.10.0) fixed this problem.
