### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by dahyun1023** [sphinx-doc/sphinx#9690]
### Describe the bug

Not able to do 'make html'

```
# Sphinx version: 3.5.4
# Python version: 3.5.5 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "c:\users\user\anaconda3\envs\gym\lib\site-packages\sphinx\cmd\build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "c:\users\user\anaconda3\envs\gym\lib\site-packages\sphinx\application.py", line 245, in __init__
    self.setup_extension(extension)
  File "c:\users\user\anaconda3\envs\gym\lib\site-packages\sphinx\application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "c:\users\user\anaconda3\envs\gym\lib\site-packages\sphinx\registry.py", line 430, in load_extension
    metadata = setup(app)
  File "c:\users\user\anaconda3\envs\gym\lib\site-packages\matplotlib\sphinxext\plot_directive.py", line 268, in setup
    app.add_directive('plot', plot_directive, True, (0, 2, False), **options)
TypeError: add_directive() got an unexpected keyword argument 'encoding' 
```

Anyone know how to solve this issue?

### How to Reproduce

```
$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

### Your project

Space robotic arm project

### OS

Win

### Python version

3.5.5

### Sphinx version

3.5.4

**Comment by astrojuanlu** [comment]
Looks like an incompatibility between the matplotlib Sphinx extension and Sphinx itself? One of the two versions is either too new or too old.

**Comment by tk0miya** [comment]
Yes. It seems you're using too old matplotlib. It depends on old Sphinx. Therefore it will be resolved by upgrading matplotlib or downgrading Sphinx.
