### ISSUE TITLE
Attributeerror

### ISSUE THREAD

**Issue by ooliver1** [sphinx-doc/sphinx#9723]
### Describe the bug

```
# Sphinx version: 4.1.2
# Python version: 3.9.1 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.1
# Last messages:
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 16 source files that are out of date
#   updating environment:
#   [new config]
#   16 added, 0 changed, 0 removed
#   reading sources... [  6%] api
#   reading sources... [ 12%] index
#   reading sources... [ 18%] installing
#   reading sources... [ 25%] pincer
#   reading sources... [ 31%] pincer.core
# Loaded extensions:
#   sphinx.ext.mathjax (4.1.2) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.2) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.3) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\alabaster\__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\ext\autodoc\preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.1.2) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\ext\autodoc\type_comment.py
#   sphinx.ext.autodoc (4.1.2) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\ext\autodoc\__init__.py
#   sphinx.ext.napoleon (4.1.2) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\ext\napoleon\__init__.py
#   sphinx.ext.intersphinx (4.1.2) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\ext\intersphinx.py
#   sphinx_autodoc_typehints_updated (unknown version) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx_autodoc_typehints_updated.py
#   exception_hierarchy (unknown version) from C:\Users\olive\OneDrive\Documents\GitHub\Pincer-1\docs\extensions\exception_hierarchy.py
#   attributetable (unknown version) from C:\Users\olive\OneDrive\Documents\GitHub\Pincer-1\docs\extensions\attributetable.py
#   silence (unknown version) from C:\Users\olive\OneDrive\Documents\GitHub\Pincer-1\docs\extensions\silence.py
#   sphinxcontrib_trio (1.1.2+dev) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinxcontrib_trio\__init__.py
#   furo (2021.09.22) from C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\furo\__init__.py
Traceback (most recent call last):
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\cmd\build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\application.py", line 343, in build
    self.builder.build_update()
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\builders\__init__.py", line 293, in build_update
    self.build(to_build,
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\builders\__init__.py", line 307, in build
    updated_docnames = set(self.read())
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\builders\__init__.py", line 414, in read
    self._read_serial(docnames)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\builders\__init__.py", line 435, in _read_serial
    self.read_doc(docname)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\builders\__init__.py", line 475, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\io.py", line 188, in read_doc
    pub.publish()
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\io.py", line 108, in read
    self.parse()
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\parsers.py", line 100, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 2096, in directive
    return self.run_directive(
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\docutils\parsers\rst\states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\ext\autodoc\directive.py", line 162, in run
    documenter.generate(more_content=self.content)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 979, in generate
    self.document_members(all_members)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 860, in document_members
    documenter.generate(
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 1769, in generate
    return super().generate(more_content=more_content,
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 979, in generate
    self.document_members(all_members)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 1760, in document_members
    super().document_members(all_members)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 860, in document_members
    documenter.generate(
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 913, in generate
    if not self.import_object():
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinxcontrib_trio\__init__.py", line 369, in import_object
    obj = inspect.getattr_static(self.parent, self.object_name)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\inspect.py", line 1648, in getattr_static
    raise AttributeError(attr)
AttributeError: __dispatcher
```

### How to Reproduce

I honestly don't know

### Expected behavior

Successful build

### Your project

https://github.com/ooliver1/Pincer

### OS

windows 10 20h2

### Python version

3.9.1

### Sphinx version

4.1.2

### Sphinx extensions

sphinx.ext.napoleon sphinx.ext.autodoc sphinx.ext.intersphinx sphinx_autodoc_typehints_updated exception_hierarchy attributetable silence sphinxcontrib_trio]

### Extra tools

vscode

**Comment by tk0miya** [comment]
It seems the error was raised inside trio extension.
```
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinxcontrib_trio\__init__.py", line 369, in import_object
    obj = inspect.getattr_static(self.parent, self.object_name)
  File "C:\Users\olive\AppData\Local\Programs\Python\Python39\lib\inspect.py", line 1648, in getattr_static
    raise AttributeError(attr)
AttributeError: __dispatcher
```
