### ISSUE TITLE
TypeError: 'generator' object is not reversible

### ISSUE THREAD

**Issue by ugiwgh** [sphinx-doc/sphinx#9727]
### Describe the bug

My cmd: 
/usr/local/bin/sphinx-build -b man -t man -d /root/bu/ceph/build/doc/doctrees -c /root/bu/ceph/man /root/bu/ceph/doc/man /root/bu/ceph/build/doc/man

Error Message: 
Running Sphinx v1.7.6
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 46 added, 0 changed, 0 removed
reading sources... [  2%] 8/ceph
reading sources... [  4%] 8/ceph-authtool
reading sources... [  6%] 8/ceph-bluestore-tool

Exception occurred:
  File "/usr/local/Python-3.6.15/lib/python3.6/site-packages/Sphinx-1.7.6.dev20211011-py3.6.egg/sphinx/util/nodes.py", line 57, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: 'generator' object is not reversible
The full traceback has been saved in /tmp/sphinx-err-jpnnyy28.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

### How to Reproduce

I download the sphinx from https://github.com/sphinx-doc/sphinx.
And build it with "python3 setup.py install".

### Your project

https://github.com/ceph/ceph

### OS

CentOS Linux release 7.9.2009 (Core)

### Python version

Python 3.6.15

### Sphinx version

sphinx-1.7.6.tar.gz

**Comment by throneofshadow** [comment]
Have this error as well. 

Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: 15 added, 0 changed, 0 removed
reading sources... [  6%] hardware/hardware
reading sources... [ 13%] index

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    Transformer.apply_transforms(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 245, in apply
    apply_source_workaround(n)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: 'generator' object is not reversible

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/reachmaster/envs/latest/lib/python3.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: 'generator' object is not reversible
The full traceback has been saved in /tmp/sphinx-err-u2codvq0.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

**Comment by andrewegel** [comment]
I encountered this in my own way. Check your version of docutils thats being utilized here. There was a recent docutils-0.18 release that made a note of this change: https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-18-2021-10-26

```
nodes.Node.traverse() returns an iterator instead of a list.
```

Pinning `docutils==0.17.1` resolved this issue for us.

**Comment by pohmelie** [comment]
This breaks readthedocs build for me. https://readthedocs.org/projects/aioftp/builds/15099286/

**Comment by astrojuanlu** [comment]
Hi @pohmelie , Juan Luis from Read the Docs here - that's to be expected, pin your docutils version to `<0.18`

**Comment by throneofshadow** [comment]
Pinning docutils to <0.18 works!!! Thanks everyone!

**Comment by JohnPaton** [comment]
Shouldn't Sphinx change its own requirements to include `docutils<0.18` in this case?

**Comment by pohmelie** [comment]
@JohnPaton, actually it is already in https://github.com/sphinx-doc/sphinx/blob/4.x/setup.py#L26

**Comment by cirospat** [comment]
thanks you for your replies.
Problem solved.

pin `docutils<0.18`
in your `requirements.txt file`,
and have a `.readthedocs.yaml` file with these contents:

```
version: 2
python:
   install:
   - requirements: docs/requirements.txt
```

as reported by @astrojuanlu 
here: https://github.com/readthedocs/readthedocs.org/issues/8616#issuecomment-952034858

I followed this instruction and it works! Build succes

**Comment by tk0miya** [comment]
The recommended way is upgrading Sphinx to the latest one. It has already pinned the version of docutils. I think no reason to keep using the old version of Sphinx. Let's upgrade!

**Comment by joshuacwnewton** [comment]
> The recommended way is upgrading Sphinx to the latest one. It has already pinned the version of docutils. I think no reason to keep using the old version of Sphinx. Let's upgrade!

Just to expand on why this is happening in the first place, if you have an RTD project that was created prior to October 2020, [RTD will default to `sphinx<2`](https://docs.readthedocs.io/en/stable/builds.html?highlight=october%202020#python), unless you explicitly specify a version of Sphinx to use.

And, `sphinx<2` doesn't have this line:

https://github.com/sphinx-doc/sphinx/blob/2be9d6b092965a2f9354da66b645bf5ea76ce288/setup.py#L26

So, you'll want to specify the version of `sphinx` in RTD's requirements (see [pinning dependencies](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#pinning-dependencies) in RTD's docs), then let `sphinx` handle its own dependencies (in this case, pinning `docutils`).

**Comment by tk0miya** [comment]
>And, sphinx<2 doesn't have this line:

Just FYI, the line was added at v4.0. So docutils-0.18 would be installed if you're using Sphinx < 4.0.

**Comment by andrewegel** [comment]
I should mention, that our invocations of sphinx have been warning us about this issue for a while:

```
$prefix/lib/python3.X/site-packages/sphinx/util/nodes.py:94: FutureWarning: 
    The iterable returned by Node.traverse()
    will become an iterator instead of a list in Docutils > 0.16.
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
```

While docutils didn't make this switch until 0.18, it is a reminder that we should pay attention to warnings.
