### ISSUE TITLE
IndexEntries class takes three FAILs of four testcases.

### ISSUE THREAD

**Issue by KaKkouo** [sphinx-doc/sphinx#9744]
### Describe the bug

When I edit a rst file which has glossary's index_key, I have to use 'make clean' before 'make html'.

This problem depends on IndexEntries class.

- sphinx/envioronment/adapsters/indexentries.py

An other indexentries which I made doesn't have this problem. so, If anyone would consider hiring this indexer, I would like to discuss how to proceed. 

My suggestion is as follows:

1. evaluate two testcases on this issue.
2.  If your sphinx project would have no term with letter '|' or '^', you could use the indexer of a sphinx extention as they are.  
3. prepare a package 'sphinx-indexer'. because the indexer is of the sphinx exetention now.
4. use the package to evaluate.
5. exchange indexentries.py on a day.

related with:

- [About the 'experimental' of 'Changed in version 1.4: Index key for glossary term should be considered experimental'](https://stackoverflow.com/questions/69592462/about-the-experimental-of-changed-in-version-1-4-index-key-for-glossary-term)

note:

- I've only recently registered as a user of both pypi and github.
-  so I may not have a basic understanding of how to proceed.
- If there is any information that I am missing, I would appreciate it if you could let me know.

### How to Reproduce

testcase

```python
#!/usr/bin/python
import unittest
from sphinx.environment.adapters.indexentries import IndexEntries

testcase01i = { 
'doc1': [
    ('single', 'aaa', 'id-111', '', 'clf1'),
    ('single', 'bbb', 'id-112', '', None),
],
'doc2': [
    ('single', 'aaa', 'id-121', '', None),
    ('single', 'bbb', 'id-122', '', 'clf2'),
], }

testcase01o = [
('clf1',
  [('aaa', [[('', 'doc1.html#id-111'), ('', 'doc2.html#id-121')], [], 'clf1']), ]
),
('clf2',
  [('bbb', [[('', 'doc1.html#id-112'), ('', 'doc2.html#id-122')], [], None]), ]
),
]

testcase02i = {
'doc1': [
    ('see','hogehoge; foo','id-211','main',None),
    ('seealso','hogehoge; bar','id-212','main',None), ]
}

testcase02o = [
('H',
    [('hogehoge',
        [[],
         [('see also bar', []), ('see foo', [])],
         None
        ])
    ])
]

testcase03i = {
'doc1': [
    ('single','func1() (aaa module)','id-311','',None),
    ('single','func1() (bbb module)','id-312','',None),
    ('single','func1() (ccc module)','id-313','',None),]
}

testcase03o = [
('F',
  [('func1()',
    [[],
     [('(aaa module)', [('', 'doc1.html#id-311')]),
      ('(bbb module)', [('', 'doc1.html#id-312')]),
      ('(ccc module)', [('', 'doc1.html#id-313')])
     ],
     None])])
]


testcase04i = {
'doc1': [
    ('single','func1() (aaa module)','id-411','',None),
    ('single','func1() (bbb module)','id-412','',None),
    ('single','func1() (ccc module)','id-413','main',None), ]
}

testcase04o = [
('F',
  [('func1()',
    [[],
     [('(aaa module)', [('', 'doc1.html#id-411')]),
      ('(bbb module)', [('', 'doc1.html#id-412')]),
      ('(ccc module)', [('main', 'doc1.html#id-413')]), ],
     None])])
]

#-------------------------------------------------------------------

class _domain(object):
    def __init__(self, entries):
        self.entries = entries

class _env(object):
    def __init__(self, domain):
        self.domain = {}
        self.domain['index'] = domain
    def get_domain(self, domain_type):
        return self.domain[domain_type]

class _builder(object):
    def get_relative_uri(self, uri_type, file_name):
        return f'{file_name}.html'

#-------------------------------------------------------------------

bld = _builder()

class TestcaseIndexEntries(unittest.TestCase):
    def test01_classifier(self):
        self.maxDiff = None
        dmn = _domain(testcase01i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase01o, gidx)
    def test02_see_and_seealso(self):
        self.maxDiff = None
        dmn = _domain(testcase02i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase02o, gidx)
    def test03_homonymous_function(self):
        self.maxDiff = None
        dmn = _domain(testcase03i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase03o, gidx)
    def test04_homonymous_function(self):
        self.maxDiff = None
        dmn = _domain(testcase04i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase04o, gidx)

#-------------------------------------------------------------------

if __name__ == '__main__':
    unittest.main()
```

result

```
F.FF
======================================================================
FAIL: test01_classifier (__main__.TestcaseIndexEntries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./unittest_IndexEntries_so.py", line 103, in test01_classifier
    self.assertEqual(testcase01o, gidx)
AssertionError: Lists differ: [('clf1', [('aaa', [[('', 'doc1.html#id-111'[127 chars]])])] != [('B', [('bbb', [[('', 'doc1.html#id-112'), [124 chars]])])]

First differing element 0:
('clf1', [('aaa', [[('', 'doc1.html#id-111'[39 chars]'])])
('B', [('bbb', [[('', 'doc1.html#id-112'), [34 chars]e])])

+ [('B',
+   [('bbb', [[('', 'doc1.html#id-112'), ('', 'doc2.html#id-122')], [], None])]),
- [('clf1',
? ^

+  ('clf1',
? ^

    [('aaa',
-     [[('', 'doc1.html#id-111'), ('', 'doc2.html#id-121')], [], 'clf1'])]),
?                                                                          ^

+     [[('', 'doc1.html#id-111'), ('', 'doc2.html#id-121')], [], 'clf1'])])]
?                                                                          ^

-  ('clf2',
-   [('bbb', [[('', 'doc1.html#id-112'), ('', 'doc2.html#id-122')], [], None])])]

======================================================================
FAIL: test03_homonymous_function (__main__.TestcaseIndexEntries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./unittest_IndexEntries_so.py", line 115, in test03_homonymous_function
    self.assertEqual(testcase03o, gidx)
AssertionError: Lists differ: [('F', [('func1()', [[], [('(aaa module)', [('', 'doc1.htm[111 chars]])])] != [('F', [('func1() (aaa module)', [[('', 'doc1.html#id-311'[102 chars]])])]

First differing element 0:
('F', [('func1()', [[], [('(aaa module)', [('', 'doc1.htm[110 chars]e])])
('F', [('func1() (aaa module)', [[('', 'doc1.html#id-311'[101 chars]e])])

  [('F',
+   [('func1() (aaa module)',
-   [('func1()',
-     [[],
-      [('(aaa module)', [('', 'doc1.html#id-311')]),
? -     -----------------                          -

+     [[('', 'doc1.html#id-311')],
-       ('(bbb module)', [('', 'doc1.html#id-312')]),
?      ^

+      [('(bbb module)', [('', 'doc1.html#id-312')]),
?      ^

        ('(ccc module)', [('', 'doc1.html#id-313')])],
       None])])]

======================================================================
FAIL: test04_homonymous_function (__main__.TestcaseIndexEntries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./unittest_IndexEntries_so.py", line 121, in test04_homonymous_function
    self.assertEqual(testcase04o, gidx)
AssertionError: Lists differ: [('F', [('func1()', [[], [('(aaa module)', [('', 'doc1.htm[115 chars]])])] != [('F', [('func1() (aaa module)', [[('', 'doc1.html#id-411'[106 chars]])])]

First differing element 0:
('F', [('func1()', [[], [('(aaa module)', [('', 'doc1.htm[114 chars]e])])
('F', [('func1() (aaa module)', [[('', 'doc1.html#id-411'[105 chars]e])])

  [('F',
+   [('func1() (aaa module)',
-   [('func1()',
-     [[],
-      [('(aaa module)', [('', 'doc1.html#id-411')]),
? -     -----------------                          -

+     [[('', 'doc1.html#id-411')],
-       ('(bbb module)', [('', 'doc1.html#id-412')]),
?      ^

+      [('(bbb module)', [('', 'doc1.html#id-412')]),
?      ^

        ('(ccc module)', [('main', 'doc1.html#id-413')])],
       None])])]

----------------------------------------------------------------------
Ran 4 tests in 0.008s

FAILED (failures=3)
```

### Expected behavior

```
....
----------------------------------------------------------------------
Ran 4 tests in 0.001s

OK
```

### Your project

https://github.com/KaKkouo/kana_text

### OS

Win

### Python version

3.8.10

### Sphinx version

4.2.0

### Sphinx extensions

sphinx.ext.todo, sphinxcontrib.yt, sphinxcontrib.kana_text, matplotlib.sphinxext.plot_directive

### Extra tools

unittest

### Additional context

testcase which all is passed with.

```python
#!/usr/bin/python
import unittest
from sphinx.environment.adapters.indexentries import IndexEntries

testcase01i = { 
'doc1': [
    ('single', 'aaa', 'id-111', '', 'clf1'),
    ('single', 'bbb', 'id-112', '', None),
],
'doc2': [
    ('single', 'aaa', 'id-121', '', None),
    ('single', 'bbb', 'id-122', '', 'clf2'),
], }

testcase01o = [
('B',
  [('bbb', [[('', 'doc1.html#id-112'), ('', 'doc2.html#id-122')], [], None]), ]),
('clf1',
  [('aaa', [[('', 'doc1.html#id-111'), ('', 'doc2.html#id-121')], [], 'clf1']), ]),
]

testcase02i = {
'doc1': [
    ('see','hogehoge; foo','id-211','main',None),
    ('seealso','hogehoge; bar','id-212','main',None), ]
}

testcase02o = [
('H',
    [('hogehoge',
        [[],
         [('see also bar', []), ('see foo', [])],
         None
        ])
    ])
]

testcase03i = {
'doc1': [
    ('single','func1() (aaa module)','id-311','',None),
    ('single','func1() (bbb module)','id-312','',None),
    ('single','func1() (ccc module)','id-313','',None),]
}

testcase03o = [
('F',
  [('func1() (aaa module)',
    [[('', 'doc1.html#id-311')],
     [('(bbb module)', [('', 'doc1.html#id-312')]),
      ('(ccc module)', [('', 'doc1.html#id-313')])],
     None])])
]


testcase04i = {
'doc1': [
    ('single','func1() (aaa module)','id-411','',None),
    ('single','func1() (bbb module)','id-412','',None),
    ('single','func1() (ccc module)','id-413','main',None), ]
}

testcase04o = [
('F',
  [('func1() (aaa module)',
    [[('', 'doc1.html#id-411')],
     [('(bbb module)', [('', 'doc1.html#id-412')]),
      ('(ccc module)', [('main', 'doc1.html#id-413')])],
     None])])
]

#-------------------------------------------------------------------

class _domain(object):
    def __init__(self, entries):
        self.entries = entries

class _env(object):
    def __init__(self, domain):
        self.domain = {}
        self.domain['index'] = domain
    def get_domain(self, domain_type):
        return self.domain[domain_type]

class _builder(object):
    def get_relative_uri(self, uri_type, file_name):
        return f'{file_name}.html'

#-------------------------------------------------------------------

bld = _builder()

class TestcaseIndexEntries(unittest.TestCase):
    def test01_classifier(self):
        self.maxDiff = None
        dmn = _domain(testcase01i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase01o, gidx)
    def test02_see_and_seealso(self):
        self.maxDiff = None
        dmn = _domain(testcase02i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase02o, gidx)
    def test03_homonymous_function(self):
        self.maxDiff = None
        dmn = _domain(testcase03i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase03o, gidx)
    def test04_homonymous_function(self):
        self.maxDiff = None
        dmn = _domain(testcase04i)
        env = _env(dmn)
        gidx = IndexEntries(env).create_index(bld)
        self.assertEqual(testcase04o, gidx)

#-------------------------------------------------------------------

if __name__ == '__main__':
    unittest.main()
```

**Comment by AA-Turner** [comment]
Closing due to inactivity. Tests pass on master.

A
