### ISSUE TITLE
Circular import on current master

### ISSUE THREAD

**Issue by hoefling** [sphinx-doc/sphinx#9759]
### Describe the bug

Import `sphinx.addnodes` fails:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/oleg.hoefling/projects/private/sphinx/sphinx/addnodes.py", line 16, in <module>
    from sphinx.util import docutils
  File "/home/oleg.hoefling/projects/private/sphinx/sphinx/util/__init__.py", line 35, in <module>
    from sphinx.util.nodes import (caption_ref_re, explicit_title_re,  # noqa
  File "/home/oleg.hoefling/projects/private/sphinx/sphinx/util/nodes.py", line 183, in <module>
    addnodes.versionmodified,
AttributeError: module 'sphinx.addnodes' has no attribute 'versionmodified'
```
Bisecting shows 335f95afdee2dfb03e85b466a4eff66c236b384b introduced this error.

### How to Reproduce

```
$ python -c 'from sphinx import addnodes'
```
on current `master`.

### Your project

Not necessary

### OS

Linux

### Python version

3.X

### Sphinx version

master

**Comment by tk0miya** [comment]
Sorry for the inconvenience.
This was already fixed on 4.x branch by 2adc41cb867f55f64895f14e55e3d76580b7b225. Now I merged it into the master branch.

Thanks,
