### ISSUE TITLE
Building keeps failing even when I when back to a version that previously worked

### ISSUE THREAD

**Issue by rcruces** [sphinx-doc/sphinx#9794]
### Describe the bug

We are currently having some issues with the documentation. After a git merge the RtD building is continuously failing. I try to build it again from the last commit that passed, from a new branch and is still failling:

https://readthedocs.org/projects/micapipe/builds/15120165
![Screenshot at 2021-10-28 13-56-48](https://user-images.githubusercontent.com/15281416/139309766-e60bf7fd-ba13-46a3-9076-de2d8a2c9e6a.png)

We have all the building here: https://readthedocs.org/projects/micapipe/builds/

The error is always on the same command:
```bash
home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/bin/python -m sphinx -T -b html -d _build/doctrees -D language=en . _build/html
```

The log is the following:
```bash
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 22 source files that are out of date
updating environment: 22 added, 0 changed, 0 removed
reading sources... [  4%] index
reading sources... [  9%] pages/01.execution/index
reading sources... [ 13%] pages/01.install/index
reading sources... [ 18%] pages/01.whatsnew/index
reading sources... [ 22%] pages/01.whatyouneed/index
reading sources... [ 27%] pages/02.dwiproc/index
reading sources... [ 31%] pages/02.microstructproc/index
reading sources... [ 36%] pages/02.qc/index

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    Transformer.apply_transforms(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 245, in apply
    apply_source_workaround(n)
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: 'generator' object is not reversible

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/lib/python3.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: 'generator' object is not reversible
The full traceback has been saved in /tmp/sphinx-err-k5idnqc6.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

### How to Reproduce

```
git clone --no-single-branch --depth 50 https://github.com/MICA-MNI/micapipe .
Cloning into '.'...
Command time: 9s Return: 0
git checkout --force origin/recoverRtD
git clean -d -f -f
python3.7 -mvirtualenv /home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest
/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/bin/python -m pip install --upgrade --no-cache-dir pip setuptools
/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/bin/python -m pip install --upgrade --no-cache-dir mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<2.2
/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/bin/python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
cat docs/conf.py
/home/docs/checkouts/readthedocs.org/user_builds/micapipe/envs/latest/bin/python -m sphinx -T -b html -d _build/doctrees -D language=en . _build/html


### Expected behavior

I expect the building to pass like here:

https://readthedocs.org/projects/micapipe/builds/15067817/

### Your project

https://github.com/MICA-MNI/micapipe/tree/master/docs

### Screenshots

_No response_

### OS

Linux Ubuntu

### Python version

3.7.3

### Sphinx version

sphinx-build 2.1.2

### Sphinx extensions

_No response_

### Extra tools

_No response_

### Additional context

_No response_

**Comment by astrojuanlu** [comment]
Duplicate of #9727, #9786, #9788.
