### ISSUE TITLE
[python3 pngmath throws struct.error

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#982]
---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/982
- Originally reported by: Marcin Wojdyr
- Originally created at: 2012-07-30T20:20:38.020

**Comment by shimizukawa** [comment]
_From Marcin Wojdyr on 2012-07-30 18:29:08+00:00_

I've accidentally pressed enter when editing title and the issue was submitted without description.
Then I wrote a long comment explaining the problem, but this comment is not displayed. Let's try again.

conf.py file: https://github.com/wojdyr/fityk/blob/master/doc/conf.py

It works with python2. If I remove pngmath extension, no exception is thrown. Here is what I get with python3 and pngmath:

{{{

# Sphinx version: 1.1.3

# Python version: 3.2.3

# Docutils version: 0.8.1 release

# Jinja2 version: 2.6

Traceback (most recent call last):
  File "/usr/lib/python3.2/site-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/usr/lib/python3.2/site-packages/sphinx/application.py", line 200, in build
    self.builder.build_all()
  File "/usr/lib/python3.2/site-packages/sphinx/builders/**init**.py", line 159, in build_all
    self.build(None, summary='all source files', method='all')
  File "/usr/lib/python3.2/site-packages/sphinx/builders/**init**.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.2/site-packages/sphinx/builders/**init**.py", line 292, in write
    self.write_doc(docname, doctree)
  File "/usr/lib/python3.2/site-packages/sphinx/builders/html.py", line 419, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/lib/python3.2/site-packages/docutils/writers/**init**.py", line 77, in write
    self.translate()
  File "/usr/lib/python3.2/site-packages/sphinx/writers/html.py", line 38, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.2/site-packages/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.2/site-packages/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.2/site-packages/docutils/nodes.py", line 173, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.2/site-packages/docutils/nodes.py", line 165, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3.2/site-packages/docutils/nodes.py", line 1604, in dispatch_visit
    return method(node)
  File "/usr/lib/python3.2/site-packages/sphinx/ext/pngmath.py", line 213, in html_visit_displaymath
    fname, depth = render_math(self, latex)
  File "/usr/lib/python3.2/site-packages/sphinx/ext/pngmath.py", line 166, in render_math
    write_png_depth(outfn, depth)
  File "/usr/lib/python3.2/site-packages/sphinx/util/png.py", line 54, in write_png_depth
    f.write(struct.pack('!i', binascii.crc32(DEPTH_CHUNK_START + data)))
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
}}}

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-06-04 09:00:22+00:00_

Closes #982: Avoid crash when writing PNG file using Python 3.

binascii.crc32() has changed in version 3.0.
In Py2 it returns value in the range [-2**31, 2**31-1],
in Py3 in [0, 2**32-1].

This change made write_png_depth() crash with:
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

→ <<cset ea605b9589f2872924509a79e826cf1481e9fdaa>>
