### ISSUE TITLE
`TypeVar`s named with trailing underscores produce a spurious warning

### ISSUE THREAD

**Issue by Yoshanuikabundi** [sphinx-doc/sphinx#9836]
### Describe the bug

Documenting a `typing.TypeVar` that is named with a trailing underscore with Autodoc (or Autosummary with the right template)  produces a cryptic warning, though the output appears correct:

```
WARNING: :1: (ERROR/3) Unknown target name: "t".
```

The target name given by the warning (here "t") appears to be the name of the type, converted to lowercase, with the trailing underscore removed.

### How to Reproduce

I've prepared a minimal example. Place these files in a folder together, run `sphinx-build . _build`, and observe the warning. Note that the `T` type variable produces no warning, and neither do strings with trailing underscores. Note also that the output is correct.

[typevar_warning_mre.zip](https://github.com/sphinx-doc/sphinx/files/7510175/typevar_warning_mre.zip)

`conf.py`:
```python
import os
import sys

sys.path.insert(0, os.path.abspath("."))

extensions = [
    "sphinx.ext.autodoc",
]

```

`index.rst`:

```rst
test
----

.. currentmodule:: mod

.. autodata:: T_

```

`mod.py`:

```python
from typing import TypeVar

T = TypeVar("T")
T_ = TypeVar("T_")
# T_ = "T_"

```

### Expected behavior

No warning is produced.

### Your project

https://github.com/sphinx-doc/sphinx/files/7510175/typevar_warning_mre.zip

### Screenshots

![image](https://user-images.githubusercontent.com/28590748/141057263-c2da7102-89eb-4e80-9040-9f6357033fa9.png)

### OS

Linux Arch

### Python version

3.7.10

### Sphinx version

4.2.0

### Sphinx extensions

sphinx.ext.autodoc

### Additional context

<details><summary>Traceback</summary><pre>
 $ rm -r _build; sphinx-build -W -T . _build
Running Sphinx v4.2.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                     

Traceback (most recent call last):
  File "/home/joshmitchell/conda/envs/offdev/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/joshmitchell/conda/envs/offdev/lib/python3.7/site-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/home/joshmitchell/conda/envs/offdev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 295, in build_update
    len(to_build))
  File "/home/joshmitchell/conda/envs/offdev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 307, in build
    updated_docnames = set(self.read())
  File "/home/joshmitchell/conda/envs/offdev/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/joshmitchell/conda/envs/offdev/lib/python3.7/site-packages/sphinx/util/logging.py", line 213, in pending_warnings
    memhandler.flushTo(logger)
  File "/home/joshmitchell/conda/envs/offdev/lib/python3.7/site-packages/sphinx/util/logging.py", line 178, in flushTo
    logger.handle(record)
  File "/home/joshmitchell/conda/envs/offdev/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/home/joshmitchell/conda/envs/offdev/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/home/joshmitchell/conda/envs/offdev/lib/python3.7/logging/__init__.py", line 890, in handle
    rv = self.filter(record)
  File "/home/joshmitchell/conda/envs/offdev/lib/python3.7/logging/__init__.py", line 751, in filter
    result = f.filter(record)
  File "/home/joshmitchell/conda/envs/offdev/lib/python3.7/site-packages/sphinx/util/logging.py", line 423, in filter
    raise exc
sphinx.errors.SphinxWarning: :1: (ERROR/3) Unknown target name: "t".

Warning, treated as error:
:1: (ERROR/3) Unknown target name: "t".
</pre></detail>

**Comment by tk0miya** [comment]
Note: Internally, the autodata call is converted to the following mark-up.

```
.. py:data:: T_
   :module: mod

   alias of TypeVar('T_')
```
