### ISSUE TITLE
Cyrillic chars in path > exception

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#990]
Path is "/home/culebron/Work/курс/sphinxdoc/sphinx/README.rst", or '/home/culebron/Work/\xd0\xba\xd1\x83\xd1\x80\xd1\x81/sphinxdoc/sphinx/README.rst'.

```
# Sphinx version: 1.1.3
# Python version: 2.7.3
# Docutils version: 0.9.1 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 191, in build_update
    self.build(['__all__'], to_build)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 216, in build
    purple, length):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 120, in status_iterator
    for item in iterable:
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 613, in update_generator
    self.read_doc(docname, app=app)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 758, in read_doc
    pub.set_source(None, src_path.encode(fs_encoding))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 20: ordinal not in range(128)
```

I played with the code, and to make it work, seems that you need to decode the path too before encoding it.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/990
- Originally reported by: Dmitri Lebedev
- Originally created at: 2012-08-11T19:11:49.028

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-11 19:18:31+00:00_

This should be fixed in 1.2. Otherwise please reopen.
