### ISSUE TITLE
'rawunicodeescape' codec can't decode bytes

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#992]
I follow the introduction steps for read the docs on Windows 7 and I get this error when I try and run make html.  Works on Linux and read the docs.
# Sphinx version: 1.1.3
# Python version: 2.5.0
# Docutils version: 0.9.1 release
# Jinja2 version: 2.6

Traceback (most recent call last):
  File "c:\python25\lib\site-packages\sphinx-1.1.3-py2.5.egg\sphinx\cmdline.py", line 188, in main
    warningiserror, tags)
  File "c:\python25\lib\site-packages\sphinx-1.1.3-py2.5.egg\sphinx\application.py", line 114, in **init**
    self.setup_extension(extension)
  File "c:\python25\lib\site-packages\sphinx-1.1.3-py2.5.egg\sphinx\application.py", line 247, in setup_extension
    mod = **import**(extension, None, None, ['setup'])
  File "c:\python25\lib\site-packages\sphinx-1.1.3-py2.5.egg\sphinx\ext\intersphinx.py", line 38, in <module>
    from sphinx.builders.html import INVENTORY_FILENAME
  File "c:\python25\lib\site-packages\sphinx-1.1.3-py2.5.egg\sphinx\builders\html.py", line 45, in <module>
    from sphinx.highlighting import PygmentsBridge
  File "c:\python25\lib\site-packages\sphinx-1.1.3-py2.5.egg\sphinx\highlighting.py", line 29, in <module>
    from pygments.lexers import PythonLexer, PythonConsoleLexer, CLexer, \
  File "c:\python25\lib\site-packages\pygments-1.5-py2.5.egg\pygments\lexers__init__.py", line 218, in **getattr**
    _load_lexers(info[0])
  File "c:\python25\lib\site-packages\pygments-1.5-py2.5.egg\pygments\lexers__init__.py", line 32, in _load_lexers
    mod = __import__(module_name, None, None, ['**all**'])
  File "c:\python25\lib\site-packages\pygments-1.5-py2.5.egg\pygments\lexers\text.py", line 20, in <module>
    from pygments.lexers.other import BashLexer
  File "c:\python25\lib\site-packages\pygments-1.5-py2.5.egg\pygments\lexers\other.py", line 18, in <module>
    from pygments.lexers.web import HtmlLexer
UnicodeDecodeError: 'rawunicodeescape' codec can't decode bytes in position 12-22: \Uxxxxxxxx out of range

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/992
- Originally reported by: Anonymous
- Originally created at: 2012-08-14T20:30:58.550

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2012-08-19 10:17:15+00:00_

Pygments bug, see https://bitbucket.org/birkenfeld/pygments-main/issue/778/error-importing-pygmentslexersweb-on
